# Vosk

In [ ]:
!pip install -q vosk
!pip install -q jiwer hazm pandas tqdm soundfile

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 76.8 MB/s eta 0:00:00
  Building wheel for srt (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 19.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 70.2 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
!pip install librosa

In [ ]:
import os
import re
import json
import time
import random

import numpy as np
import pandas as pd
import soundfile as sf
import librosa
import hazm

from tqdm import tqdm
from jiwer import wer, cer

from vosk import Model, KaldiRecognizer

In [ ]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)

In [ ]:
!wget https://alphacephei.com/vosk/models/vosk-model-fa-0.42.zip

!unzip -q vosk-model-fa-0.42.zip

!ls

--2026-06-19 15:12:15--  https://alphacephei.com/vosk/models/vosk-model-fa-0.42.zip
Resolving alphacephei.com (alphacephei.com)... 188.40.21.16, 2a01:4f8:13a:279f::2
Connecting to alphacephei.com (alphacephei.com)|188.40.21.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1667089770 (1.6G) [application/zip]
Saving to: ‘vosk-model-fa-0.42.zip’

vosk-model-fa-0.42. 100%[===================>]   1.55G  19.5MB/s    in 84s

2026-06-19 15:13:40 (18.9 MB/s) - ‘vosk-model-fa-0.42.zip’ saved [1667089770/1667089770]

sample_data  vosk-model-fa-0.42  vosk-model-fa-0.42.zip

In [ ]:
from vosk import Model

VOSK_MODEL_PATH = "/content/vosk-model-fa-0.42"

model = Model(VOSK_MODEL_PATH)

print("Vosk model loaded successfully")

In [ ]:
DATA_ROOT = "/content/drive/MyDrive/asr_project/asr_data/fa_test_only"

TSV_PATH = os.path.join(DATA_ROOT, "test.tsv")
AUDIO_ROOT = os.path.join(DATA_ROOT, "clips")

df = pd.read_csv(TSV_PATH, sep="\t")

df = df.dropna(
    subset=["path", "sentence"]
).reset_index(drop=True)

df["audio_path"] = df["path"].apply(
    lambda x: os.path.join(AUDIO_ROOT, x)
)

print("Total samples:", len(df))

Total samples: 10519

In [ ]:
CHECKPOINT_PATH = (
    "/content/drive/MyDrive/asr_project/"
    "vosk_checkpoint.csv"
)

if os.path.exists(CHECKPOINT_PATH):

    results_df = pd.read_csv(
        CHECKPOINT_PATH
    )

    processed = set(
        results_df["audio_path"].tolist()
    )

    print(
        "Resuming from",
        len(results_df),
        "samples"
    )

else:

    results_df = pd.DataFrame(columns=[

        "audio_path",

        "reference_raw",

        "prediction_raw",

        "audio_duration",

        "inference_time"
    ])

    processed = set()

In [ ]:
def transcribe_vosk(audio_path, model):

    audio, sr = sf.read(audio_path)

    # stereo -> mono
    if len(audio.shape) > 1:
        audio = np.mean(
            audio,
            axis=1
        )

    # resample
    if sr != 16000:

        audio = librosa.resample(
            audio,
            orig_sr=sr,
            target_sr=16000
        )

        sr = 16000

    audio_int16 = (
        audio * 32767
    ).astype(np.int16)

    rec = KaldiRecognizer(
        model,
        16000
    )

    rec.AcceptWaveform(
        audio_int16.tobytes()
    )

    result = json.loads(
        rec.FinalResult()
    )

    return result.get(
        "text",
        ""
    )

In [ ]:
for idx in tqdm(range(len(df))):

    row = df.iloc[idx]

    audio_path = row["audio_path"]

    if audio_path in processed:
        continue

    try:

        info = sf.info(audio_path)

        duration = info.duration

        t0 = time.time()

        pred_text = transcribe_vosk(
            audio_path,
            model
        )

        t1 = time.time()

        inference_time = t1 - t0

        new_row = {

            "audio_path": audio_path,

            "reference_raw": row["sentence"],

            "prediction_raw": pred_text,

            "audio_duration": duration,

            "inference_time": inference_time
        }

        results_df = pd.concat(
            [
                results_df,
                pd.DataFrame([new_row])
            ],
            ignore_index=True
        )

        processed.add(audio_path)

        # checkpoint every 50 samples
        if len(results_df) % 50 == 0:

            results_df.to_csv(
                CHECKPOINT_PATH,
                index=False
            )

            print(
                f"Checkpoint saved "
                f"({len(results_df)} samples)"
            )

    except Exception as e:

        print(
            f"\nFAILED: {audio_path}"
        )

        print(e)

  0%|          | 0/10519 [00:00<?, ?it/s]/tmp/ipykernel_905/2207672906.py:40: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat(
  0%|          | 50/10519 [02:36<8:47:44,  3.02s/it]

Checkpoint saved (50 samples)

  1%|          | 100/10519 [04:27<6:54:12,  2.39s/it]

Checkpoint saved (100 samples)

  1%|▏         | 150/10519 [06:19<5:22:17,  1.86s/it]

Checkpoint saved (150 samples)

  2%|▏         | 200/10519 [07:50<5:07:34,  1.79s/it]

Checkpoint saved (200 samples)

  2%|▏         | 250/10519 [09:42<6:36:19,  2.32s/it]

Checkpoint saved (250 samples)

  3%|▎         | 300/10519 [11:28<7:27:40,  2.63s/it]

Checkpoint saved (300 samples)

  3%|▎         | 350/10519 [13:19<6:25:47,  2.28s/it]

Checkpoint saved (350 samples)

  4%|▍         | 400/10519 [14:45<4:23:04,  1.56s/it]

Checkpoint saved (400 samples)

  4%|▍         | 450/10519 [16:21<5:36:58,  2.01s/it]

Checkpoint saved (450 samples)

  5%|▍         | 500/10519 [18:16<5:55:34,  2.13s/it]

Checkpoint saved (500 samples)

  5%|▌         | 550/10519 [19:43<4:45:42,  1.72s/it]

Checkpoint saved (550 samples)

  6%|▌         | 600/10519 [21:24<7:11:32,  2.61s/it]

Checkpoint saved (600 samples)

  6%|▌         | 650/10519 [22:57<5:54:39,  2.16s/it]

Checkpoint saved (650 samples)

  7%|▋         | 700/10519 [24:32<5:03:57,  1.86s/it]

Checkpoint saved (700 samples)

  7%|▋         | 750/10519 [26:08<6:08:19,  2.26s/it]

Checkpoint saved (750 samples)

  8%|▊         | 800/10519 [27:54<4:49:44,  1.79s/it]

Checkpoint saved (800 samples)

  8%|▊         | 850/10519 [29:37<5:38:56,  2.10s/it]

Checkpoint saved (850 samples)

  9%|▊         | 900/10519 [31:12<5:32:13,  2.07s/it]

Checkpoint saved (900 samples)

  9%|▉         | 950/10519 [32:42<5:07:57,  1.93s/it]

Checkpoint saved (950 samples)

 10%|▉         | 1000/10519 [34:18<5:32:14,  2.09s/it]

Checkpoint saved (1000 samples)

 10%|▉         | 1050/10519 [35:54<4:45:56,  1.81s/it]

Checkpoint saved (1050 samples)

 10%|█         | 1100/10519 [37:29<4:37:58,  1.77s/it]

Checkpoint saved (1100 samples)

 11%|█         | 1150/10519 [39:05<4:14:03,  1.63s/it]

Checkpoint saved (1150 samples)

 11%|█▏        | 1200/10519 [40:37<4:57:04,  1.91s/it]

Checkpoint saved (1200 samples)

 12%|█▏        | 1250/10519 [42:15<5:34:09,  2.16s/it]

Checkpoint saved (1250 samples)

 12%|█▏        | 1300/10519 [44:04<6:34:54,  2.57s/it]

Checkpoint saved (1300 samples)

 13%|█▎        | 1350/10519 [45:49<4:35:32,  1.80s/it]

Checkpoint saved (1350 samples)

 13%|█▎        | 1400/10519 [47:28<5:16:11,  2.08s/it]

Checkpoint saved (1400 samples)

 14%|█▍        | 1450/10519 [49:00<5:07:26,  2.03s/it]

Checkpoint saved (1450 samples)

 14%|█▍        | 1500/10519 [50:43<7:02:08,  2.81s/it]

Checkpoint saved (1500 samples)

 15%|█▍        | 1550/10519 [52:27<4:53:35,  1.96s/it]

Checkpoint saved (1550 samples)

 15%|█▌        | 1600/10519 [54:14<3:46:05,  1.52s/it]

Checkpoint saved (1600 samples)

 16%|█▌        | 1650/10519 [55:54<4:22:21,  1.77s/it]

Checkpoint saved (1650 samples)

 16%|█▌        | 1700/10519 [58:07<35:48:09, 14.61s/it]

Checkpoint saved (1700 samples)

 17%|█▋        | 1750/10519 [59:39<4:56:09,  2.03s/it]

Checkpoint saved (1750 samples)

 17%|█▋        | 1800/10519 [1:01:34<4:21:40,  1.80s/it]

Checkpoint saved (1800 samples)

 18%|█▊        | 1850/10519 [1:03:14<4:39:51,  1.94s/it]

Checkpoint saved (1850 samples)

 18%|█▊        | 1900/10519 [1:04:54<4:47:55,  2.00s/it]

Checkpoint saved (1900 samples)

 19%|█▊        | 1950/10519 [1:06:33<5:06:07,  2.14s/it]

Checkpoint saved (1950 samples)

 19%|█▉        | 2000/10519 [1:08:06<3:39:07,  1.54s/it]

Checkpoint saved (2000 samples)

 19%|█▉        | 2050/10519 [1:09:42<4:16:21,  1.82s/it]

Checkpoint saved (2050 samples)

 20%|█▉        | 2100/10519 [1:11:27<3:55:41,  1.68s/it]

Checkpoint saved (2100 samples)

 20%|██        | 2150/10519 [1:13:02<3:51:45,  1.66s/it]

Checkpoint saved (2150 samples)

 21%|██        | 2200/10519 [1:14:46<5:26:40,  2.36s/it]

Checkpoint saved (2200 samples)

 21%|██▏       | 2250/10519 [1:17:06<20:16:40,  8.83s/it]

Checkpoint saved (2250 samples)

 22%|██▏       | 2300/10519 [1:18:50<3:57:46,  1.74s/it]

Checkpoint saved (2300 samples)

 22%|██▏       | 2350/10519 [1:20:27<4:29:37,  1.98s/it]

Checkpoint saved (2350 samples)

 23%|██▎       | 2400/10519 [1:22:13<4:36:27,  2.04s/it]

Checkpoint saved (2400 samples)

 23%|██▎       | 2450/10519 [1:23:54<4:24:06,  1.96s/it]

Checkpoint saved (2450 samples)

 24%|██▍       | 2500/10519 [1:25:28<3:29:04,  1.56s/it]

Checkpoint saved (2500 samples)

 24%|██▍       | 2550/10519 [1:27:02<3:30:06,  1.58s/it]

Checkpoint saved (2550 samples)

 25%|██▍       | 2600/10519 [1:28:40<2:59:56,  1.36s/it]

Checkpoint saved (2600 samples)

 25%|██▌       | 2650/10519 [1:30:35<3:51:10,  1.76s/it]

Checkpoint saved (2650 samples)

 26%|██▌       | 2700/10519 [1:32:11<4:16:12,  1.97s/it]

Checkpoint saved (2700 samples)

 26%|██▌       | 2750/10519 [1:33:49<4:00:00,  1.85s/it]

Checkpoint saved (2750 samples)

 27%|██▋       | 2800/10519 [1:35:18<3:59:59,  1.87s/it]

Checkpoint saved (2800 samples)

 27%|██▋       | 2850/10519 [1:36:41<3:24:51,  1.60s/it]

Checkpoint saved (2850 samples)

 28%|██▊       | 2900/10519 [1:38:09<3:54:58,  1.85s/it]

Checkpoint saved (2900 samples)

 28%|██▊       | 2950/10519 [1:39:45<3:58:53,  1.89s/it]

Checkpoint saved (2950 samples)

 29%|██▊       | 3000/10519 [1:41:17<4:52:20,  2.33s/it]

Checkpoint saved (3000 samples)

 29%|██▉       | 3050/10519 [1:42:56<3:37:53,  1.75s/it]

Checkpoint saved (3050 samples)

 29%|██▉       | 3100/10519 [1:44:42<4:16:57,  2.08s/it]

Checkpoint saved (3100 samples)

 30%|██▉       | 3150/10519 [1:46:19<4:36:32,  2.25s/it]

Checkpoint saved (3150 samples)

 30%|███       | 3200/10519 [1:47:53<4:20:48,  2.14s/it]

Checkpoint saved (3200 samples)

 31%|███       | 3250/10519 [1:49:22<3:31:05,  1.74s/it]

Checkpoint saved (3250 samples)

 31%|███▏      | 3300/10519 [1:50:59<3:42:42,  1.85s/it]

Checkpoint saved (3300 samples)

 32%|███▏      | 3350/10519 [1:52:36<3:30:21,  1.76s/it]

Checkpoint saved (3350 samples)

 32%|███▏      | 3400/10519 [1:54:06<3:29:37,  1.77s/it]

Checkpoint saved (3400 samples)

 33%|███▎      | 3450/10519 [1:55:41<4:26:46,  2.26s/it]

Checkpoint saved (3450 samples)

 33%|███▎      | 3500/10519 [1:57:19<4:22:23,  2.24s/it]

Checkpoint saved (3500 samples)

 34%|███▎      | 3550/10519 [1:58:42<3:11:16,  1.65s/it]

Checkpoint saved (3550 samples)

 34%|███▍      | 3600/10519 [2:00:07<3:18:06,  1.72s/it]

Checkpoint saved (3600 samples)

 35%|███▍      | 3650/10519 [2:01:45<3:28:45,  1.82s/it]

Checkpoint saved (3650 samples)

 35%|███▌      | 3700/10519 [2:03:13<3:17:37,  1.74s/it]

Checkpoint saved (3700 samples)

 36%|███▌      | 3750/10519 [2:04:42<2:51:32,  1.52s/it]

Checkpoint saved (3750 samples)

 36%|███▌      | 3800/10519 [2:06:11<3:24:01,  1.82s/it]

Checkpoint saved (3800 samples)

 37%|███▋      | 3850/10519 [2:07:40<3:18:06,  1.78s/it]

Checkpoint saved (3850 samples)

 37%|███▋      | 3900/10519 [2:09:05<3:19:55,  1.81s/it]

Checkpoint saved (3900 samples)

 38%|███▊      | 3950/10519 [2:10:32<3:08:07,  1.72s/it]

Checkpoint saved (3950 samples)

 38%|███▊      | 4000/10519 [2:12:15<3:55:06,  2.16s/it]

Checkpoint saved (4000 samples)

 39%|███▊      | 4050/10519 [2:13:52<3:16:25,  1.82s/it]

Checkpoint saved (4050 samples)

 39%|███▉      | 4100/10519 [2:15:37<3:50:51,  2.16s/it]

Checkpoint saved (4100 samples)

 39%|███▉      | 4150/10519 [2:17:07<3:54:53,  2.21s/it]

Checkpoint saved (4150 samples)

 40%|███▉      | 4200/10519 [2:18:47<3:15:40,  1.86s/it]

Checkpoint saved (4200 samples)

 40%|████      | 4250/10519 [2:20:22<3:32:02,  2.03s/it]

Checkpoint saved (4250 samples)

 41%|████      | 4300/10519 [2:21:59<2:58:16,  1.72s/it]

Checkpoint saved (4300 samples)

 41%|████▏     | 4350/10519 [2:23:35<2:52:47,  1.68s/it]

Checkpoint saved (4350 samples)

 42%|████▏     | 4400/10519 [2:25:06<3:33:18,  2.09s/it]

Checkpoint saved (4400 samples)

 42%|████▏     | 4450/10519 [2:26:44<4:51:06,  2.88s/it]

Checkpoint saved (4450 samples)

 43%|████▎     | 4500/10519 [2:28:13<3:34:46,  2.14s/it]

Checkpoint saved (4500 samples)

 43%|████▎     | 4550/10519 [2:29:58<4:20:13,  2.62s/it]

Checkpoint saved (4550 samples)

 44%|████▎     | 4600/10519 [2:31:37<2:26:25,  1.48s/it]

Checkpoint saved (4600 samples)

 44%|████▍     | 4650/10519 [2:33:05<3:37:08,  2.22s/it]

Checkpoint saved (4650 samples)

 45%|████▍     | 4700/10519 [2:34:39<3:18:27,  2.05s/it]

Checkpoint saved (4700 samples)

 45%|████▌     | 4750/10519 [2:36:15<3:25:48,  2.14s/it]

Checkpoint saved (4750 samples)

 46%|████▌     | 4800/10519 [2:37:42<3:15:26,  2.05s/it]

Checkpoint saved (4800 samples)

 46%|████▌     | 4850/10519 [2:39:15<3:25:12,  2.17s/it]

Checkpoint saved (4850 samples)

 47%|████▋     | 4900/10519 [2:40:44<2:55:45,  1.88s/it]

Checkpoint saved (4900 samples)

 47%|████▋     | 4950/10519 [2:42:18<3:30:23,  2.27s/it]

Checkpoint saved (4950 samples)

 48%|████▊     | 5000/10519 [2:43:46<3:10:46,  2.07s/it]

Checkpoint saved (5000 samples)

 48%|████▊     | 5050/10519 [2:45:27<2:57:36,  1.95s/it]

Checkpoint saved (5050 samples)

 48%|████▊     | 5100/10519 [2:47:05<3:10:10,  2.11s/it]

Checkpoint saved (5100 samples)

 49%|████▉     | 5150/10519 [2:48:38<2:26:32,  1.64s/it]

Checkpoint saved (5150 samples)

 49%|████▉     | 5200/10519 [2:50:05<2:09:30,  1.46s/it]

Checkpoint saved (5200 samples)

 50%|████▉     | 5250/10519 [2:51:44<2:07:38,  1.45s/it]

Checkpoint saved (5250 samples)

 50%|█████     | 5300/10519 [2:53:03<2:10:45,  1.50s/it]

Checkpoint saved (5300 samples)

 51%|█████     | 5350/10519 [2:54:37<2:32:24,  1.77s/it]

Checkpoint saved (5350 samples)

 51%|█████▏    | 5400/10519 [2:56:07<3:46:03,  2.65s/it]

Checkpoint saved (5400 samples)

 52%|█████▏    | 5450/10519 [2:57:43<3:32:22,  2.51s/it]

Checkpoint saved (5450 samples)

 52%|█████▏    | 5500/10519 [2:59:21<2:51:15,  2.05s/it]

Checkpoint saved (5500 samples)

 53%|█████▎    | 5550/10519 [3:01:05<6:07:05,  4.43s/it]

Checkpoint saved (5550 samples)

 53%|█████▎    | 5600/10519 [3:02:46<2:13:33,  1.63s/it]

Checkpoint saved (5600 samples)

 54%|█████▎    | 5650/10519 [3:04:35<2:23:38,  1.77s/it]

Checkpoint saved (5650 samples)

 54%|█████▍    | 5700/10519 [3:06:00<2:15:04,  1.68s/it]

Checkpoint saved (5700 samples)

 55%|█████▍    | 5750/10519 [3:07:35<2:12:11,  1.66s/it]

Checkpoint saved (5750 samples)

 55%|█████▌    | 5800/10519 [3:09:07<2:14:33,  1.71s/it]

Checkpoint saved (5800 samples)

 56%|█████▌    | 5850/10519 [3:10:42<2:13:05,  1.71s/it]

Checkpoint saved (5850 samples)

 56%|█████▌    | 5900/10519 [3:12:09<2:39:43,  2.07s/it]

Checkpoint saved (5900 samples)

 57%|█████▋    | 5950/10519 [3:13:43<2:33:01,  2.01s/it]

Checkpoint saved (5950 samples)

 57%|█████▋    | 6000/10519 [3:15:17<2:37:52,  2.10s/it]

Checkpoint saved (6000 samples)

 58%|█████▊    | 6050/10519 [3:16:50<2:17:53,  1.85s/it]

Checkpoint saved (6050 samples)

 58%|█████▊    | 6100/10519 [3:18:43<1:59:32,  1.62s/it]

Checkpoint saved (6100 samples)

 58%|█████▊    | 6150/10519 [3:20:10<2:12:25,  1.82s/it]

Checkpoint saved (6150 samples)

 59%|█████▉    | 6200/10519 [3:21:45<3:06:55,  2.60s/it]

Checkpoint saved (6200 samples)

 59%|█████▉    | 6250/10519 [3:23:13<1:58:49,  1.67s/it]

Checkpoint saved (6250 samples)

 60%|█████▉    | 6300/10519 [3:24:36<1:44:31,  1.49s/it]

Checkpoint saved (6300 samples)

 60%|██████    | 6350/10519 [3:26:13<1:50:48,  1.59s/it]

Checkpoint saved (6350 samples)

 61%|██████    | 6400/10519 [3:27:37<1:37:39,  1.42s/it]

Checkpoint saved (6400 samples)

 61%|██████▏   | 6450/10519 [3:29:10<2:25:39,  2.15s/it]

Checkpoint saved (6450 samples)

 62%|██████▏   | 6500/10519 [3:30:41<2:03:51,  1.85s/it]

Checkpoint saved (6500 samples)

 62%|██████▏   | 6550/10519 [3:32:08<1:51:07,  1.68s/it]

Checkpoint saved (6550 samples)

 63%|██████▎   | 6600/10519 [3:33:34<1:47:23,  1.64s/it]

Checkpoint saved (6600 samples)

 63%|██████▎   | 6650/10519 [3:34:55<1:38:21,  1.53s/it]

Checkpoint saved (6650 samples)

 64%|██████▎   | 6700/10519 [3:36:23<1:40:16,  1.58s/it]

Checkpoint saved (6700 samples)

 64%|██████▍   | 6750/10519 [3:37:49<1:30:21,  1.44s/it]

Checkpoint saved (6750 samples)

 65%|██████▍   | 6800/10519 [3:39:20<1:39:13,  1.60s/it]

Checkpoint saved (6800 samples)

 65%|██████▌   | 6850/10519 [3:40:47<1:57:27,  1.92s/it]

Checkpoint saved (6850 samples)

 66%|██████▌   | 6900/10519 [3:42:22<1:37:13,  1.61s/it]

Checkpoint saved (6900 samples)

 66%|██████▌   | 6950/10519 [3:44:04<2:18:24,  2.33s/it]

Checkpoint saved (6950 samples)

 67%|██████▋   | 7000/10519 [3:45:38<1:33:35,  1.60s/it]

Checkpoint saved (7000 samples)

 67%|██████▋   | 7050/10519 [3:47:08<1:46:14,  1.84s/it]

Checkpoint saved (7050 samples)

 67%|██████▋   | 7100/10519 [3:48:54<1:38:35,  1.73s/it]

Checkpoint saved (7100 samples)

 68%|██████▊   | 7150/10519 [3:50:20<1:56:45,  2.08s/it]

Checkpoint saved (7150 samples)

 68%|██████▊   | 7200/10519 [3:51:55<1:47:46,  1.95s/it]

Checkpoint saved (7200 samples)

 69%|██████▉   | 7250/10519 [3:53:27<1:37:38,  1.79s/it]

Checkpoint saved (7250 samples)

 69%|██████▉   | 7300/10519 [3:55:02<1:37:41,  1.82s/it]

Checkpoint saved (7300 samples)

 70%|██████▉   | 7350/10519 [3:56:36<1:28:53,  1.68s/it]

Checkpoint saved (7350 samples)

 70%|███████   | 7400/10519 [3:58:09<1:56:19,  2.24s/it]

Checkpoint saved (7400 samples)

 71%|███████   | 7450/10519 [3:59:38<1:42:34,  2.01s/it]

Checkpoint saved (7450 samples)

 71%|███████▏  | 7500/10519 [4:01:00<1:31:29,  1.82s/it]

Checkpoint saved (7500 samples)

 72%|███████▏  | 7550/10519 [4:02:22<1:29:22,  1.81s/it]

Checkpoint saved (7550 samples)

 72%|███████▏  | 7600/10519 [4:03:51<1:26:49,  1.78s/it]

Checkpoint saved (7600 samples)

 73%|███████▎  | 7650/10519 [4:05:14<1:28:27,  1.85s/it]

Checkpoint saved (7650 samples)

 73%|███████▎  | 7700/10519 [4:06:37<1:05:34,  1.40s/it]

Checkpoint saved (7700 samples)

 74%|███████▎  | 7750/10519 [4:08:09<1:29:22,  1.94s/it]

Checkpoint saved (7750 samples)

 74%|███████▍  | 7800/10519 [4:09:39<1:33:16,  2.06s/it]

Checkpoint saved (7800 samples)

 75%|███████▍  | 7850/10519 [4:11:20<1:30:08,  2.03s/it]

Checkpoint saved (7850 samples)

 75%|███████▌  | 7900/10519 [4:12:52<1:16:19,  1.75s/it]

Checkpoint saved (7900 samples)

 76%|███████▌  | 7950/10519 [4:14:35<1:33:45,  2.19s/it]

Checkpoint saved (7950 samples)

 76%|███████▌  | 8000/10519 [4:16:10<1:20:38,  1.92s/it]

Checkpoint saved (8000 samples)

 77%|███████▋  | 8050/10519 [4:17:48<1:26:36,  2.10s/it]

Checkpoint saved (8050 samples)

 77%|███████▋  | 8100/10519 [4:19:23<1:13:38,  1.83s/it]

Checkpoint saved (8100 samples)

 77%|███████▋  | 8150/10519 [4:20:50<1:12:17,  1.83s/it]

Checkpoint saved (8150 samples)

 78%|███████▊  | 8200/10519 [4:22:15<1:16:38,  1.98s/it]

Checkpoint saved (8200 samples)

 78%|███████▊  | 8250/10519 [4:23:47<59:44,  1.58s/it]

Checkpoint saved (8250 samples)

 79%|███████▉  | 8300/10519 [4:25:10<59:02,  1.60s/it]

Checkpoint saved (8300 samples)

 79%|███████▉  | 8350/10519 [4:26:38<1:13:24,  2.03s/it]

Checkpoint saved (8350 samples)

 80%|███████▉  | 8400/10519 [4:28:12<1:10:07,  1.99s/it]

Checkpoint saved (8400 samples)

 80%|████████  | 8450/10519 [4:29:40<56:38,  1.64s/it]

Checkpoint saved (8450 samples)

 81%|████████  | 8500/10519 [4:31:14<59:24,  1.77s/it]

Checkpoint saved (8500 samples)

 81%|████████▏ | 8550/10519 [4:32:34<48:51,  1.49s/it]

Checkpoint saved (8550 samples)

 82%|████████▏ | 8600/10519 [4:33:55<48:32,  1.52s/it]

Checkpoint saved (8600 samples)

 82%|████████▏ | 8650/10519 [4:35:17<50:19,  1.62s/it]

Checkpoint saved (8650 samples)

 83%|████████▎ | 8700/10519 [4:36:34<47:49,  1.58s/it]

Checkpoint saved (8700 samples)

 83%|████████▎ | 8750/10519 [4:38:13<56:08,  1.90s/it]

Checkpoint saved (8750 samples)

 84%|████████▎ | 8800/10519 [4:40:24<52:21,  1.83s/it]

Checkpoint saved (8800 samples)

 84%|████████▍ | 8850/10519 [4:41:55<49:50,  1.79s/it]

Checkpoint saved (8850 samples)

 85%|████████▍ | 8900/10519 [4:43:28<59:34,  2.21s/it]

Checkpoint saved (8900 samples)

 85%|████████▌ | 8950/10519 [4:45:05<52:04,  1.99s/it]

Checkpoint saved (8950 samples)

 86%|████████▌ | 9000/10519 [4:46:26<36:34,  1.44s/it]

Checkpoint saved (9000 samples)

 86%|████████▌ | 9050/10519 [4:47:56<42:54,  1.75s/it]

Checkpoint saved (9050 samples)

 87%|████████▋ | 9100/10519 [4:49:24<47:02,  1.99s/it]

Checkpoint saved (9100 samples)

 87%|████████▋ | 9150/10519 [4:50:49<36:34,  1.60s/it]

Checkpoint saved (9150 samples)

 87%|████████▋ | 9200/10519 [4:52:14<36:11,  1.65s/it]

Checkpoint saved (9200 samples)

 88%|████████▊ | 9250/10519 [4:53:40<32:51,  1.55s/it]

Checkpoint saved (9250 samples)

 88%|████████▊ | 9300/10519 [4:55:10<39:05,  1.92s/it]

Checkpoint saved (9300 samples)

 89%|████████▉ | 9350/10519 [4:56:42<32:38,  1.68s/it]

Checkpoint saved (9350 samples)

 89%|████████▉ | 9400/10519 [4:58:13<31:40,  1.70s/it]

Checkpoint saved (9400 samples)

 90%|████████▉ | 9450/10519 [4:59:32<28:47,  1.62s/it]

Checkpoint saved (9450 samples)

 90%|█████████ | 9500/10519 [5:00:56<38:43,  2.28s/it]

Checkpoint saved (9500 samples)

 91%|█████████ | 9550/10519 [5:02:27<26:04,  1.61s/it]

Checkpoint saved (9550 samples)

 91%|█████████▏| 9600/10519 [5:03:53<24:09,  1.58s/it]

Checkpoint saved (9600 samples)

 92%|█████████▏| 9650/10519 [5:05:12<22:28,  1.55s/it]

Checkpoint saved (9650 samples)

 92%|█████████▏| 9700/10519 [5:06:37<24:45,  1.81s/it]

Checkpoint saved (9700 samples)

 93%|█████████▎| 9750/10519 [5:08:09<21:58,  1.72s/it]

Checkpoint saved (9750 samples)

 93%|█████████▎| 9800/10519 [5:09:36<24:33,  2.05s/it]

Checkpoint saved (9800 samples)

 94%|█████████▎| 9850/10519 [5:10:53<16:28,  1.48s/it]

Checkpoint saved (9850 samples)

 94%|█████████▍| 9900/10519 [5:12:22<21:20,  2.07s/it]

Checkpoint saved (9900 samples)

 95%|█████████▍| 9950/10519 [5:14:01<27:32,  2.90s/it]

Checkpoint saved (9950 samples)

 95%|█████████▌| 10000/10519 [5:15:26<14:03,  1.63s/it]

Checkpoint saved (10000 samples)

 96%|█████████▌| 10050/10519 [5:16:45<10:09,  1.30s/it]

Checkpoint saved (10050 samples)

 96%|█████████▌| 10100/10519 [5:18:14<13:07,  1.88s/it]

Checkpoint saved (10100 samples)

 96%|█████████▋| 10150/10519 [5:19:45<10:04,  1.64s/it]

Checkpoint saved (10150 samples)

 97%|█████████▋| 10200/10519 [5:21:10<08:25,  1.58s/it]

Checkpoint saved (10200 samples)

 97%|█████████▋| 10250/10519 [5:22:38<07:37,  1.70s/it]

Checkpoint saved (10250 samples)

 98%|█████████▊| 10300/10519 [5:24:02<06:36,  1.81s/it]

Checkpoint saved (10300 samples)

 98%|█████████▊| 10350/10519 [5:25:20<04:41,  1.66s/it]

Checkpoint saved (10350 samples)

 99%|█████████▉| 10400/10519 [5:26:50<03:45,  1.89s/it]

Checkpoint saved (10400 samples)

 99%|█████████▉| 10450/10519 [5:28:27<02:03,  1.79s/it]

Checkpoint saved (10450 samples)

100%|█████████▉| 10500/10519 [5:29:50<00:26,  1.37s/it]

Checkpoint saved (10500 samples)

100%|██████████| 10519/10519 [5:30:40<00:00,  1.89s/it]

In [ ]:
results_df.to_csv(
    CHECKPOINT_PATH,
    index=False
)

print("Final checkpoint saved.")
print(CHECKPOINT_PATH)

Final checkpoint saved.
/content/drive/MyDrive/asr_project/vosk_checkpoint.csv

In [ ]:
pip -q install hazm jiwer

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 48.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 85.7 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
import re
import pandas as pd
import hazm

from jiwer import wer, cer

In [ ]:
CHECKPOINT_PATH = (
    "/content/drive/MyDrive/asr_project/"
    "vosk_checkpoint.csv"
)

df = pd.read_csv(CHECKPOINT_PATH)

print("Loaded:", len(df))

Loaded: 10519

In [ ]:
normalizer = hazm.Normalizer()

PERSIAN_CHAR_MAP = {
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ؤ": "و",
    "ئ": "ی",
    "ة": "ه",
}

def normalize_persian(text):

    text = str(text)

    text = normalizer.normalize(text)

    for k, v in PERSIAN_CHAR_MAP.items():
        text = text.replace(k, v)

    # number normalization
    text = re.sub(
        r"\d+",
        " <NUM> ",
        text
    )

    text = re.sub(
        r"[^\w\s<>]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

In [ ]:
df["ref_norm"] = (
    df["reference_raw"]
    .apply(normalize_persian)
)

df["hyp_norm"] = (
    df["prediction_raw"]
    .apply(normalize_persian)
)

In [ ]:
refs = df["ref_norm"].tolist()
hyps = df["hyp_norm"].tolist()

wer_score = wer(
    refs,
    hyps
)

cer_score = cer(
    refs,
    hyps
)

total_audio_duration = (
    df["audio_duration"].sum()
)

total_inference_time = (
    df["inference_time"].sum()
)

rtf = (
    total_inference_time
    /
    total_audio_duration
)

avg_latency = (
    df["inference_time"].mean()
)

# CPU model
peak_memory = 0

In [ ]:
print("\n=========== FINAL RESULTS ===========\n")

print("Model: Vosk Persian")

print(f"Samples: {len(df)}")

print(f"WER: {wer_score:.4f}")

print(f"CER: {cer_score:.4f}")

print(f"RTF: {rtf:.4f}")

print(
    f"Avg latency (s): "
    f"{avg_latency:.4f}"
)

print(
    f"Total inference time (s): "
    f"{total_inference_time:.2f}"
)

print(
    f"Total audio duration (s): "
    f"{total_audio_duration:.2f}"
)

print(
    f"Peak GPU memory (GB): "
    f"{peak_memory:.2f}"
)

print("\n====================================\n")

=========== FINAL RESULTS ===========

Model: Vosk Persian
Samples: 10519
WER: 0.3543
CER: 0.2566
RTF: 0.3051
Avg latency (s): 1.5098
Total inference time (s): 15881.76
Total audio duration (s): 52047.28
Peak GPU memory (GB): 0.00

====================================

In [ ]:
summary_df = pd.DataFrame([{

    "model": "Vosk Persian",

    "samples": len(df),

    "wer": wer_score,

    "cer": cer_score,

    "rtf": rtf,

    "avg_latency_sec": avg_latency,

    "gpu_memory_gb": peak_memory,

    "total_inference_time_sec": total_inference_time

}])

summary_df.to_csv(
    "/content/drive/MyDrive/asr_project/vosk_summary.csv",
    index=False
)

print("Summary saved.")

Summary saved.

In [ ]:
import pandas as pd
import re
import unicodedata
from jiwer import wer, cer

CHECKPOINT_PATH = "/content/drive/MyDrive/asr_project/vosk_checkpoint.csv"

df = pd.read_csv(CHECKPOINT_PATH)

df = df.dropna(subset=["reference_raw", "prediction_raw"]).reset_index(drop=True)

In [ ]:
df.head()

,audio_path,reference_raw,prediction_raw,audio_duration,inference_time
0,/content/drive/MyDrive/asr_project/asr_data/fa...,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,2.753750,17.422447
1,/content/drive/MyDrive/asr_project/asr_data/fa...,دعا خوان,دعاخوان,3.103500,0.914036
2,/content/drive/MyDrive/asr_project/asr_data/fa...,اعتماد کرد,اعتماد کرد,4.651043,1.470268
3,/content/drive/MyDrive/asr_project/asr_data/fa...,خب ، تو چیكار می كنی؟,خب تو چیکار می‌کنی,3.701625,1.054197
4,/content/drive/MyDrive/asr_project/asr_data/fa...,آه، نه اصلاُ!,اوه نه اصلا,2.429625,0.902153

In [ ]:
df_sub = df[['prediction_raw', 'reference_raw']]
df_sub.head()

           prediction_raw           reference_raw
0  از مهمونداری کنار بکشم  از مهمونداری کنار بکشم
1                 دعاخوان                دعا خوان
2              اعتماد کرد              اعتماد کرد
3      خب تو چیکار می‌کنی   خب ، تو چیكار می كنی؟
4             اوه نه اصلا           آه، نه اصلاُ!

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:
    if text is None:
        return ""

    text = str(text)

    # Unicode normalization FIRST (important)
    text = unicodedata.normalize("NFKC", text)

    # remove hashtags (NeMo-style filtering)
    text = " ".join(w for w in text.split() if not w.startswith("#"))

    # character replacements
    for k, v in REPLACEMENTS.items():
        text = text.replace(k, v)

    # remove punctuation tokens
    for tok in DISCARD:
        text = text.replace(tok, " ")

    # remove Arabic letter variations like hamza
    text = text.replace("ء", "")

    # collapse whitespace
    text = " ".join(text.split())

    return text

In [ ]:
df_sub["hyp_norm"] = df_sub["prediction_raw"].apply(nemo_paper_normalize)
df_sub["ref_norm"] = df_sub["reference_raw"].apply(nemo_paper_normalize)

/tmp/ipykernel_569/1633250410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["hyp_norm"] = df_sub["prediction_raw"].apply(nemo_paper_normalize)
/tmp/ipykernel_569/1633250410.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["ref_norm"] = df_sub["reference_raw"].apply(nemo_paper_normalize)

In [ ]:
df_sub.loc[df_sub["hyp_norm"] == "", "hyp_norm"] = " "
df_sub.loc[df_sub["ref_norm"] == "", "ref_norm"] = " "

In [ ]:
wer_score = wer(df_sub["ref_norm"].tolist(), df_sub["hyp_norm"].tolist())
cer_score = cer(df_sub["ref_norm"].tolist(), df_sub["hyp_norm"].tolist())

print("NeMo-replicated WER:", wer_score)
print("NeMo-replicated CER:", cer_score)
print("Samples:", len(df_sub))

NeMo-replicated WER: 0.2538651370639632
NeMo-replicated CER: 0.1858016278485446
Samples: 10492

In [ ]:
pip install kaldialign

Collecting kaldialign
  Downloading kaldialign-0.12.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Downloading kaldialign-0.12.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (110 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 4.1 MB/s eta 0:00:00
Installing collected packages: kaldialign
Successfully installed kaldialign-0.12.0

In [ ]:
import pandas as pd
import kaldialign


def _alignment_error_rate(ref_tokens, hyp_tokens):
    """
    Compute error rate using Kaldi/Icefall alignment.

    Returns:
        error_rate, substitutions, deletions, insertions, reference_length
    """
    ali = kaldialign.align(ref_tokens, hyp_tokens, "*")

    subs = dels = ins = 0

    for r, h in ali:
        if r == "*":
            ins += 1
        elif h == "*":
            dels += 1
        elif r != h:
            subs += 1

    n_ref = len(ref_tokens)
    err = (subs + dels + ins) / max(1, n_ref)

    return err, subs, dels, ins, n_ref


def add_wer_cer_columns(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Adds per-sample WER and CER columns to a dataframe.

    Returns
    -------
    DataFrame
        Copy of dataframe with:
            wer
            cer
            wer_sub
            wer_del
            wer_ins
            cer_sub
            cer_del
            cer_ins
    """

    df = df.copy()

    wers = []
    cers = []

    wer_subs = []
    wer_dels = []
    wer_inss = []

    cer_subs = []
    cer_dels = []
    cer_inss = []

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        # ---------- WER ----------
        wer, s, d, i, _ = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        wers.append(wer)
        wer_subs.append(s)
        wer_dels.append(d)
        wer_inss.append(i)

        # ---------- CER ----------
        cer, s, d, i, _ = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        cers.append(cer)
        cer_subs.append(s)
        cer_dels.append(d)
        cer_inss.append(i)

    df["wer"] = wers
    df["cer"] = cers

    df["wer_sub"] = wer_subs
    df["wer_del"] = wer_dels
    df["wer_ins"] = wer_inss

    df["cer_sub"] = cer_subs
    df["cer_del"] = cer_dels
    df["cer_ins"] = cer_inss

    return df


def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
# Add per-utterance metrics
df_sub = add_wer_cer_columns(df_sub)

# Inspect individual utterances
df_sub[["hyp_norm", "ref_norm", "wer", "cer"]].head()

,prediction_raw,reference_raw,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
0,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,0.000000,0.000000,0,0,0,0,0,0
1,دعاخوان,دعا خوان,دعاخوان,دعا خوان,1.000000,0.000000,1,1,0,0,0,0
2,اعتماد کرد,اعتماد کرد,اعتماد کرد,اعتماد کرد,0.000000,0.000000,0,0,0,0,0,0
3,خب تو چیکار می‌کنی,خب ، تو چیكار می كنی؟,خب تو چیکار می‌کنی,خب تو چیکار می کنی,0.400000,0.071429,1,1,0,0,0,1
4,اوه نه اصلا,آه، نه اصلاُ!,اوه نه اصلا,آه نه اصلا,0.333333,0.250000,1,0,0,1,0,1

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

compute_dataset_wer_cer(df_sub)

{'WER': 0.22337633482843375,
 'CER': 0.0592807158426064,
 'word_sub': 11186,
 'word_del': 3783,
 'word_ins': 1117,
 'char_sub': 4040,
 'char_del': 4512,
 'char_ins': 7984,
 'total_words': 72013,
 'total_chars': 278944}

### results

In [ ]:
results = compute_dataset_wer_cer(df_sub)

print(f"WER: {results['WER']:.4f}")
print(f"CER: {results['CER']:.4f}")
print(results)

WER: 0.2234
CER: 0.0593
{'WER': 0.22337633482843375, 'CER': 0.0592807158426064, 'word_sub': 11186, 'word_del': 3783, 'word_ins': 1117, 'char_sub': 4040, 'char_del': 4512, 'char_ins': 7984, 'total_words': 72013, 'total_chars': 278944}

In [ ]:
df_sub[df_sub["ref_norm"].str.match(r"^(?=.*\d)(?=.*[^\d]).+", na=False)]

,prediction_raw,reference_raw,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
1688,هی این خانوم ایده جالبی داره بگذار گوش کنیم,هی، این خانم ایده جالبی دارد بگذار گوش کنیم\t\...,هی این خانوم ایده جالبی داره بگذار گوش کنیم,هی این خانم ایده جالبی دارد بگذار گوش کنیم 2 0...,0.997629,0.999308,2,2943,0,0,50565,0

In [ ]:
df_sub_1 = df_sub[df_sub['cer'] > df_sub['wer']]
df_sub_1

,prediction_raw,reference_raw,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
21,نه گوشی سامسونگ آم هنوزم تلویزیون,هیچ گل مینا دارید؟,نه گوشی سامسونگ آم هنوزم تلویزیون,هیچ گل مینا دارید,1.500000,1.571429,4,0,2,8,0,14
102,نه شروع به لخته شدن می‌کنم,بلافاصله شروع به لخته شدن میکند,نه شروع به لخته شدن می‌کنم,بلافاصله شروع به لخته شدن میکند,0.333333,0.346154,2,0,0,2,6,1
106,هان فقط رفتن تو بزرگراه و گشت زدن,(خنده) فقط، رفتن تو بزرگراه و گشت زدن,هان فقط رفتن تو بزرگراه و گشت زدن,خنده فقط رفتن تو بزرگراه و گشت زدن,0.125000,0.148148,1,0,0,1,2,1
298,دستمال گشود و به سقف خیره شد,چشمانش را گشود و به سقف خیره شد.,دستمال گشود و به سقف خیره شد,چشمانش را گشود و به سقف خیره شد,0.250000,0.291667,1,1,0,3,3,1
355,جشن پنجاه پنجاه‌ساله,جشن پنجاه ساله,جشن پنجاه پنجاه‌ساله,جشن پنجاه ساله,0.333333,0.500000,1,0,0,0,0,6
397,ال دو نقطه روز زن چی,ال:روز زن چی؟,ال دو نقطه روز زن چی,ال روز زن چی,0.500000,0.666667,0,0,2,0,0,6
509,هدفش این بود که در آمریکا,هدفش این بود که در جامعه آمریکا,هدفش این بود که در آمریکا,هدفش این بود که در جامعه آمریکا,0.142857,0.200000,0,1,0,0,5,0
532,روز مکان و حتی زمان مراجعه شما را تعیین می‌کند,روز ، مکان و حتی زمان مراجعه شما را تعیین کنند.,روز مکان و حتی زمان مراجعه شما را تعیین می‌کند,روز مکان و حتی زمان مراجعه شما را تعیین کنند,0.100000,0.114286,1,0,0,0,1,3
555,خب چرا نباید باشم فکر می‌کنم,خب ، چرا نباید باشم ؟,خب چرا نباید باشم فکر می‌کنم,خب چرا نباید باشم,0.500000,0.642857,0,0,2,0,0,9
920,این من برمیگرده به چند سال پیش,این داستان من برمیگرده به چند سال پیش,این من برمیگرده به چند سال پیش,این داستان من برمیگرده به چند سال پیش,0.125000,0.200000,0,1,0,0,6,0
1066,اینجا بسط دادن پهنای مشارکت,بسط دادن پهنای مشارکت,اینجا بسط دادن پهنای مشارکت,بسط دادن پهنای مشارکت,0.250000,0.277778,0,0,1,0,0,5
1197,لطفا توده هوایی دیگر را چک کنید,لطفاً خطوط هوایی دیگر را چک کنید.,لطفا توده هوایی دیگر را چک کنید,لطفا خطوط هوایی دیگر را چک کنید,0.142857,0.160000,1,0,0,2,1,1
1231,مطمئنی یک دقیقه,لطفاً یک گزارش سرقت پر کنید.,مطمئنی یک دقیقه,لطفا یک گزارش سرقت پر کنید,0.833333,0.904762,2,3,0,5,11,3
1236,اما در یک نگاه مند وجود دارد,اما در یک نگاه سامانمند وجود دارد,اما در یک نگاه مند وجود دارد,اما در یک نگاه سامانمند وجود دارد,0.142857,0.185185,1,0,0,0,5,0
1300,همه‌اش قبل از ساعت ده بود,همش قبل از ساعت ده بود,همه‌اش قبل از ساعت ده بود,همش قبل از ساعت ده بود,0.166667,0.176471,1,0,0,0,0,3
1323,حرص و آز شخصیت او را غصب کرده بود,حرص و آز شخصیت او را پست کرده بود.,حرص و آز شخصیت او را غصب کرده بود,حرص و آز شخصیت او را پست کرده بود,0.111111,0.120000,1,0,0,3,0,0
1386,به من کاملا توجه کنید میزنه,به من کاملاً توجه کنید,به من کاملا توجه کنید میزنه,به من کاملا توجه کنید,0.200000,0.294118,0,0,1,0,0,5
1417,پیادهشو اتوبوس بعدی به ریودوژانیرو چه ساعتی است,اتوبوس بعدی به ریودوژانیرو چه ساعتی است؟,پیادهشو اتوبوس بعدی به ریودوژانیرو چه ساعتی است,اتوبوس بعدی به ریودوژانیرو چه ساعتی است,0.142857,0.212121,0,0,1,0,0,7
1418,درد شدید دارد ماریا برم,درد شدید دارد.,درد شدید دارد ماریا برم,درد شدید دارد,0.666667,0.727273,0,0,2,0,0,8
1456,هم خونه ما بزرگه هم دختر بزرگم,هم خونه ما بزرگه هم دختر بزرگم دارم,هم خونه ما بزرگه هم دختر بزرگم,هم خونه ما بزرگه هم دختر بزرگم دارم,0.125000,0.142857,0,1,0,0,4,0
1688,هی این خانوم ایده جالبی داره بگذار گوش کنیم,هی، این خانم ایده جالبی دارد بگذار گوش کنیم\t\...,هی این خانوم ایده جالبی داره بگذار گوش کنیم,هی این خانم ایده جالبی دارد بگذار گوش کنیم 2 0...,0.997629,0.999308,2,2943,0,0,50565,0
1689,نه یه بی حرمتی نیست,نه مسئله بی حرمتی نیست,نه یه بی حرمتی نیست,نه مسئله بی حرمتی نیست,0.200000,0.222222,1,0,0,1,3,0
2593,خواه آنها را با احترام بالا ببرید,خواه آنها را با احترام گذاشتن بالا ببرید,خواه آنها را با احترام بالا ببرید,خواه آنها را با احترام گذاشتن بالا ببرید,0.125000,0.181818,0,1,0,0,6,0
2599,آیا همجنسگرایی گرایی یک اختلال است,آیا همجنسگرایی یک اختلال است؟,آیا همجنسگرایی گرایی یک اختلال است,آیا همجنسگرایی یک اختلال است,0.200000,0.208333,0,0,1,0,0,5
2670,ببخشید تلاش پرشور او برای فرار از زندان,تلاش پرشور او برای فرار از زندان,ببخشید تلاش پرشور او برای فرار از زندان,تلاش پرشور او برای فرار از زندان,0.142857,0.230769,0,0,1,0,0,6
3607,دوربین از سمت راست خارج شوید,از سمت راست خارج شوید,دوربین از سمت راست خارج شوید,از سمت راست خارج شوید,0.200000,0.352941,0,0,1,0,0,6
3698,حسن سلاح میان وراث را فیصله داد,حسن اختلاف میان وراث را فیصله داد.,حسن سلاح میان وراث را فیصله داد,حسن اختلاف میان وراث را فیصله داد,0.142857,0.148148,1,0,0,2,2,0
3783,مردم فکر کنم دو حرف وسطش هم,فکر کنم دو حرف وسطش هم,مردم فکر کنم دو حرف وسطش هم,فکر کنم دو حرف وسطش هم,0.166667,0.235294,0,0,1,0,0,4
4266,شنبه روز کاری است کارشون,شنبه روز کاری است؟,شنبه روز کاری است کارشون,شنبه روز کاری است,0.250000,0.428571,0,0,1,0,0,6
4447,داری قرار نمیدی,برنامه داری قرار نمیدی,داری قرار نمیدی,برنامه داری قرار نمیدی,0.250000,0.315789,0,1,0,0,6,0
4787,زیرا خیلی چیزها هست که دلالت بر ایجاب و بچه بو...,زیرا خیلی چیزها هست که دلالت بر ایجاب و ممکن ب...,زیرا خیلی چیزها هست که دلالت بر ایجاب و بچه بو...,زیرا خیلی چیزها هست که دلالت بر ایجاب و ممکن ب...,0.076923,0.085106,1,0,0,3,1,0
4794,در زمانی که حضورت در مخمصه گرفتار بود,در زمانی که هولفودز در مخمصه گرفتار بود,در زمانی که حضورت در مخمصه گرفتار بود,در زمانی که هولفودز در مخمصه گرفتار بود,0.125000,0.187500,1,0,0,4,2,0
4997,سی و چند قلوزایی,کلومفین و چند قلوزایی,سی و چند قلوزایی,کلومفین و چند قلوزایی,0.250000,0.333333,1,0,0,1,5,0
5001,دیگه اونو راضی نیستم بهش زحمت نمی‌دادین تغییر ...,راضی نیستم بهش زحمت نمی دادی.,دیگه اونو راضی نیستم بهش زحمت نمی‌دادین تغییر ...,راضی نیستم بهش زحمت نمی دادی,0.833333,0.869565,2,0,3,0,0,20
5314,البته من چند باری شده که دیدم تو حیاطشون کفش م...,البته من چند باری شده که دیدم تو حیاطشون کفش م...,البته من چند باری شده که دیدم تو حیاطشون کفش م...,البته من چند باری شده که دیدم تو حیاطشون کفش م...,0.083333,0.136364,1,0,0,0,0,6
5473,حسن با شکست مواجه شد,ترفند با شکست مواجه شد.,حسن با شکست مواجه شد,ترفند با شکست مواجه شد,0.200000,0.222222,1,0,0,2,2,0
5816,من در تا برای سنگاپور هستم,من در ترانزیت برای سنگاپور هستم.,من در تا برای سنگاپور هستم,من در ترانزیت برای سنگاپور هستم,0.166667,0.192308,1,0,0,0,5,0
5842,از عادت بدی دست دست‌کشیدن,از عادت بدی دست کشیدن,از عادت بدی دست دست‌کشیدن,از عادت بدی دست کشیدن,0.200000,0.235294,1,0,0,0,0,4
6334,پول را به اون از او گرفته‌اند,پول را به عنف از او گرفتند.,پول را به اون از او گرفته‌اند,پول را به عنف از او گرفتند,0.285714,0.300000,2,0,0,1,1,4
6469,پول می‌گیرید در جیبم ماند,پول بلیط در جیبم ماند,پول می‌گیرید در جیبم ماند,پول بلیط در جیبم ماند,0.200000,0.411765,1,0,0,3,0,4
6920,در این رشته توییت و دو قسمت بعدی که در روزهای ...,در این #رشتهتوییت و دو قسمت بعدی که در روزهای ...,در این رشته توییت و دو قسمت بعدی که در روزهای ...,در این و دو قسمت بعدی که در روزهای آینده منتشر...,0.153846,0.204545,0,0,2,0,0,9
7476,بیابان آتاکاما در شیلی خوشت ناحیه بر روی زمین است,بیابان آتاکاما در شیلی خشکترین ناحیه بر روی زم...,بیابان آتاکاما در شیلی خوشت ناحیه بر روی زمین است,بیابان آتاکاما در شیلی خشکترین ناحیه بر روی زم...,0.100000,0.116279,1,0,0,0,4,1
7769,وقتی ری که اون داره میره برم,وقتی بزرگ شدم می خوام همونجایی که اون داره میر...,وقتی ری که اون داره میره برم,وقتی بزرگ شدم می خوام همونجایی که اون داره میر...,0.454545,0.463415,1,4,0,0,19,0
7844,حال باید بپردازیم به کار مان که عبارت است از,حال باید بپردازیم به کار اصلیمان که عبارت است ...,حال باید بپردازیم به کار مان که عبارت است از,حال باید بپردازیم به کار اصلیمان که عبارت است از,0.100000,0.102564,1,0,0,0,4,0
8169,حالا که همه سفارش داده‌اند,حالا که همه سفارش دادن,حالا که همه سفارش داده‌اند,حالا که همه سفارش دادن,0.200000,0.222222,1,0,0,0,0,4
8197,ازش روغن استفاده کنی,ازش واقعا استفاده کنی؟,ازش روغن استفاده کنی,ازش واقعا استفاده کنی,0.250000,0.277778,1,0,0,2,2,1
8664,ده دقیقه به دو نکن,ده دقیقه به دو.,ده دقیقه به دو نکن,ده دقیقه به دو,0.250000,0.272727,0,0,1,0,0,3
9002,اما قبل از تمام کردن بحث تاریخی باید ذکری هم ا...,اما قبل از تمام کردن بحث تاریخی، باید ذکری هم ...,اما قبل از تمام کردن بحث تاریخی باید ذکری هم ا...,اما قبل از تمام کردن بحث تاریخی باید ذکری هم ا...,0.076923,0.083333,1,0,0,0,1,3
9224,جمله‌اش درست نیست چی میل دارید هیچ چیزی بخورید,میل دارید هیچ چیزی بخورید؟,جمله‌اش درست نیست چی میل دارید هیچ چیزی بخورید,میل دارید هیچ چیزی بخورید,0.800000,0.809524,0,0,4,0,0,17
9281,بازیکن مراکش گل به خودی زد و کل ایران رفت رو ه...,بازیکن مراکش گل به خودی زد و کل ایران رفت رو ه...,بازیکن مراکش گل به خودی زد و کل ایران رفت رو ه...,بازیکن مراکش گل به خودی زد و کل ایران رفت رو ه...,0.071429,0.080000,1,0,0,0,4,0
9451,پناه به تو داشت کله است,و رحم تو دفع کننده است,پناه به تو داشت کله است,و رحم تو دفع کننده است,0.666667,0.705882,4,0,0,7,2,3
9563,میدونم بخش رپ و رقص نور,بدون موسیقی رپ و رقص نور,میدونم بخش رپ و رقص نور,بدون موسیقی رپ و رقص نور,0.333333,0.368421,2,0,0,4,2,1
9803,ما از ده صبح تا هشت شب هفت روز هفته باز است,ما از ده صبح تا هشت شب، هفت روز هفته باز هستیم.,ما از ده صبح تا هشت شب هفت روز هفته باز است,ما از ده صبح تا هشت شب هفت روز هفته باز هستیم,0.083333,0.088235,1,0,0,1,2,0
9854,آتش را خفه کرده‌اند,آتش را خفه کردن,آتش را خفه کرده‌اند,آتش را خفه کردن,0.250000,0.333333,1,0,0,0,0,4
9934,جنگ باهاشون تحلیل رفتن منابع کشور بود,جنگ باعث تحلیل رفتن منابع کشور بود.,جنگ باهاشون تحلیل رفتن منابع کشور بود,جنگ باعث تحلیل رفتن منابع کشور بود,0.142857,0.178571,1,0,0,2,0,3
10268,امروز به سالن برویم,بیایید امروز به سونا برویم.,امروز به سالن برویم,بیایید امروز به سونا برویم,0.400000,0.409091,1,1,0,1,7,1

In [ ]:
df_sub = df_sub.drop(index=1688)
df_sub.count()

prediction_raw    10491
reference_raw     10491
hyp_norm          10491
ref_norm          10491
wer               10491
cer               10491
wer_sub           10491
wer_del           10491
wer_ins           10491
cer_sub           10491
cer_del           10491
cer_ins           10491
dtype: int64

# Nemo

In [ ]:
!pip install -q pandas==2.2.2
!pip install -q numpy==1.26.4
!pip install -q numba==0.60.0
!pip install -q nemo_toolkit['asr']

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 76.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 kB 7.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 903.9/903.9 kB 43.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.0/811.0 kB 42.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.1/443.1 kB 26.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 75.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 60.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 73.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 68.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 114.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 44.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.8/419.8 kB 40.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 122.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 40.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 125.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 104.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 114.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 126.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 36.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.7/53.7 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 119.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 91.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 57.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 108.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.1 MB/s eta 0:00:00
  Building wheel for sox (setup.py) ... done
  Building wheel for kaldi-python-io (setup.py) ... done
  Building wheel for wget (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
blosc2 4.4.5 requires numexpr>=2.14.1; platform_machine != "wasm32", but you have numexpr 2.13.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.

In [ ]:
!pip install -q jiwer
!pip install -q hazm
!pip install -q soundfile

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 52.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 19.6 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
import os
import re
import time
import random
import numpy as np
import pandas as pd
import torch
import soundfile as sf
from tqdm import tqdm
from jiwer import wer, cer
import nemo.collections.asr as nemo_asr
import hazm

[NeMo W 2026-06-25 10:19:41 megatron_init:62] Megatron num_microbatches_calculator not found, using Apex version.
WARNING:nv_one_logger.api.config:OneLogger: Setting error_handling_strategy to DISABLE_QUIETLY_AND_REPORT_METRIC_ERROR for rank (rank=0) with OneLogger disabled. To override: explicitly set error_handling_strategy parameter.
WARNING:nv_one_logger.training_telemetry.api.training_telemetry_provider:No exporters were provided. This means that no telemetry data will be collected.
[NeMo W 2026-06-25 10:19:43 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:300: SyntaxWarning: invalid escape sequence '\('
      m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)

[NeMo W 2026-06-25 10:19:43 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:301: SyntaxWarning: invalid escape sequence '\('
      m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)

[NeMo W 2026-06-25 10:19:43 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:310: SyntaxWarning: invalid escape sequence '\('
      elif re.match('(flt)p?( \(default\))?$', token):

[NeMo W 2026-06-25 10:19:43 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:314: SyntaxWarning: invalid escape sequence '\('
      elif re.match('(dbl)p?( \(default\))?$', token):

In [ ]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

In [ ]:
data_root = "/content/drive/MyDrive/asr_project/asr_data/fa_test_only"
tsv_path = os.path.join(data_root, "test.tsv")
audio_root = os.path.join(data_root, "clips")

df = pd.read_csv(tsv_path, sep="\t")
df = df.dropna(subset=["path", "sentence"]).reset_index(drop=True)

df["audio_path"] = df["path"].apply(lambda x: os.path.join(audio_root, x))

print("Total samples:", len(df))

Total samples: 10519

In [ ]:
normalizer = hazm.Normalizer()

PERSIAN_CHAR_MAP = {
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ؤ": "و",
    "ئ": "ی",
    "ة": "ه",
}

def normalize_persian(text):
    text = str(text)
    text = normalizer.normalize(text)

    for k, v in PERSIAN_CHAR_MAP.items():
        text = text.replace(k, v)

    text = re.sub(r"\d+", " <NUM> ", text)   # number handling

    text = re.sub(r"[^\w\s<>]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
MODEL_NAME = "nvidia/stt_fa_fastconformer_hybrid_large"
device = "cuda" if torch.cuda.is_available() else "cpu"

model = nemo_asr.models.ASRModel.from_pretrained(MODEL_NAME)
model = model.to(device)

print("Device:", device)

stt_fa_fastconformer_hybrid_large.nemo:   0%|          | 0.00/459M [00:00<?, ?B/s]

[NeMo I 2026-06-19 07:01:23 mixins:184] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-06-19 07:01:24 modelPT:188] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: dummy
    sample_rate: 16000
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: true
    max_duration: 10
    min_duration: 0.5
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: fully_randomized
    bucketing_batch_size: null
    use_lhotse: true
    lhotse:
      shar_path: /data_artifacts/data/shar/train
      batch_duration: 1200
      quadratic_duration: 15
      num_buckets: 10
      num_cuts_for_bins_estimate: 10000
      buffer_size: 10000
      shuffle_buffer_size: 10000

[NeMo W 2026-06-19 07:01:24 modelPT:195] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /data_artifacts/data/nemo/dev_decoded_exprunner.json
    sample_rate: 16000
    batch_size: 512
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo W 2026-06-19 07:01:24 modelPT:202] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: /data_artifacts/data/nemo/test_decoded_exprunner.json
    sample_rate: 16000
    batch_size: 512
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo I 2026-06-19 07:01:25 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-06-19 07:01:25 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-06-19 07:01:25 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-06-19 07:01:26 save_restore_connector:285] Model EncDecHybridRNNTCTCBPEModel was successfully restored from /root/.cache/huggingface/hub/models--nvidia--stt_fa_fastconformer_hybrid_large/snapshots/249cf5bf70dda7220a60ddeeecff2f6aad8e1784/stt_fa_fastconformer_hybrid_large.nemo.
Device: cuda

In [ ]:
CHECKPOINT_PATH = "/content/drive/MyDrive/asr_project/nemo_checkpoint.csv"

if os.path.exists(CHECKPOINT_PATH):
    results_df = pd.read_csv(CHECKPOINT_PATH)
    processed = set(results_df["audio_path"].tolist())
    print("Resuming from:", len(results_df), "samples")
else:
    results_df = pd.DataFrame(columns=[
        "audio_path",
        "reference_raw",
        "prediction_raw",
        "audio_duration",
        "inference_time"
    ])
    processed = set()

In [ ]:
torch.cuda.empty_cache()
if device == "cuda":
    torch.cuda.reset_peak_memory_stats()

total_audio_duration = 0.0
total_inference_time = 0.0

start_time = time.time()

for idx in tqdm(range(len(df))):

    row = df.iloc[idx]
    audio_path = row["audio_path"]

    if audio_path in processed:
        continue

    try:
        # -------------------------
        # duration
        # -------------------------
        info = sf.info(audio_path)
        duration = info.frames / info.samplerate
        total_audio_duration += duration

        # -------------------------
        # inference timing
        # -------------------------
        t0 = time.time()

        pred = model.transcribe([audio_path], batch_size=1)[0]

        t1 = time.time()
        inf_time = t1 - t0
        total_inference_time += inf_time

        # -------------------------
        # store RAW ONLY
        # -------------------------
        new_row = {
            "audio_path": audio_path,
            "reference_raw": row["sentence"],
            "prediction_raw": pred,
            "audio_duration": duration,
            "inference_time": inf_time
        }

        results_df = pd.concat([results_df, pd.DataFrame([new_row])], ignore_index=True)
        processed.add(audio_path)

        # -------------------------
        # checkpoint
        # -------------------------
        if len(results_df) % 50 == 0:
            results_df.to_csv(CHECKPOINT_PATH, index=False)
            print(f"Checkpoint saved: {len(results_df)} samples")

    except Exception as e:
        print("FAILED:", audio_path)
        print(e)

  0%|          | 0/10519 [00:00<?, ?it/s][NeMo W 2026-06-19 07:09:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.35it/s]
  2%|▏         | 169/10519 [00:00<00:08, 1286.35it/s][NeMo W 2026-06-19 07:09:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.09it/s]
[NeMo W 2026-06-19 07:09:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
[NeMo W 2026-06-19 07:09:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.30it/s]
[NeMo W 2026-06-19 07:09:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.55it/s]
[NeMo W 2026-06-19 07:09:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.27it/s]
[NeMo W 2026-06-19 07:09:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.75it/s]
[NeMo W 2026-06-19 07:09:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.55it/s]
[NeMo W 2026-06-19 07:09:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
[NeMo W 2026-06-19 07:09:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.33it/s]
[NeMo W 2026-06-19 07:09:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.45it/s]
[NeMo W 2026-06-19 07:09:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.70it/s]
[NeMo W 2026-06-19 07:09:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.62it/s]
[NeMo W 2026-06-19 07:09:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.29it/s]
  2%|▏         | 169/10519 [00:14<00:08, 1286.35it/s][NeMo W 2026-06-19 07:09:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.39it/s]
  2%|▏         | 183/10519 [00:14<19:00,  9.06it/s]  [NeMo W 2026-06-19 07:09:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.65it/s]
  2%|▏         | 184/10519 [00:15<20:08,  8.55it/s][NeMo W 2026-06-19 07:09:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.72it/s]
[NeMo W 2026-06-19 07:09:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.14it/s]
[NeMo W 2026-06-19 07:09:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.96it/s]
[NeMo W 2026-06-19 07:09:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:09:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.17it/s]
[NeMo W 2026-06-19 07:10:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.70it/s]
[NeMo W 2026-06-19 07:10:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
[NeMo W 2026-06-19 07:10:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
[NeMo W 2026-06-19 07:10:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.44it/s]
[NeMo W 2026-06-19 07:10:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.50it/s]
[NeMo W 2026-06-19 07:10:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.27it/s]
[NeMo W 2026-06-19 07:10:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.86it/s]
[NeMo W 2026-06-19 07:10:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
[NeMo W 2026-06-19 07:10:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.91it/s]
[NeMo W 2026-06-19 07:10:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.14it/s]
[NeMo W 2026-06-19 07:10:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.66it/s]
  2%|▏         | 199/10519 [00:29<46:30,  3.70it/s][NeMo W 2026-06-19 07:10:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.13it/s]
  2%|▏         | 200/10519 [00:30<48:30,  3.55it/s]

Checkpoint saved: 200 samples

[NeMo W 2026-06-19 07:10:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.82it/s]
[NeMo W 2026-06-19 07:10:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.52it/s]
[NeMo W 2026-06-19 07:10:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.53it/s]
[NeMo W 2026-06-19 07:10:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
[NeMo W 2026-06-19 07:10:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.24it/s]
[NeMo W 2026-06-19 07:10:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.64it/s]
[NeMo W 2026-06-19 07:10:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.07it/s]
[NeMo W 2026-06-19 07:10:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.16it/s]
[NeMo W 2026-06-19 07:10:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.59it/s]
[NeMo W 2026-06-19 07:10:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.15it/s]
[NeMo W 2026-06-19 07:10:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.12it/s]
[NeMo W 2026-06-19 07:10:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.30it/s]
[NeMo W 2026-06-19 07:10:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.33it/s]
[NeMo W 2026-06-19 07:10:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.51it/s]
  2%|▏         | 200/10519 [00:44<48:30,  3.55it/s][NeMo W 2026-06-19 07:10:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
  2%|▏         | 215/10519 [00:44<1:20:36,  2.13it/s][NeMo W 2026-06-19 07:10:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
  2%|▏         | 216/10519 [00:45<1:22:44,  2.08it/s][NeMo W 2026-06-19 07:10:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
[NeMo W 2026-06-19 07:10:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.90it/s]
[NeMo W 2026-06-19 07:10:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.58it/s]
[NeMo W 2026-06-19 07:10:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.48it/s]
[NeMo W 2026-06-19 07:10:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.99it/s]
[NeMo W 2026-06-19 07:10:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.77it/s]
[NeMo W 2026-06-19 07:10:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.53it/s]
[NeMo W 2026-06-19 07:10:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.75it/s]
[NeMo W 2026-06-19 07:10:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
[NeMo W 2026-06-19 07:10:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.77it/s]
[NeMo W 2026-06-19 07:10:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.18it/s]
[NeMo W 2026-06-19 07:10:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.27it/s]
[NeMo W 2026-06-19 07:10:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.09it/s]
  2%|▏         | 216/10519 [00:59<1:22:44,  2.08it/s][NeMo W 2026-06-19 07:10:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
  2%|▏         | 230/10519 [00:59<1:50:59,  1.55it/s][NeMo W 2026-06-19 07:10:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
  2%|▏         | 231/10519 [01:00<1:52:43,  1.52it/s][NeMo W 2026-06-19 07:10:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:10:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.27it/s]
[NeMo W 2026-06-19 07:10:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 250 samples

[NeMo W 2026-06-19 07:11:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.54it/s]
[NeMo W 2026-06-19 07:11:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.76it/s]
  2%|▏         | 252/10519 [01:20<2:24:35,  1.18it/s][NeMo W 2026-06-19 07:11:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.93it/s]
[NeMo W 2026-06-19 07:11:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
[NeMo W 2026-06-19 07:11:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
[NeMo W 2026-06-19 07:11:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.61it/s]
[NeMo W 2026-06-19 07:11:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.53it/s]
[NeMo W 2026-06-19 07:11:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.04it/s]
  2%|▏         | 258/10519 [01:26<2:29:30,  1.14it/s][NeMo W 2026-06-19 07:11:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.02it/s]
[NeMo W 2026-06-19 07:11:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
[NeMo W 2026-06-19 07:11:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.54it/s]
[NeMo W 2026-06-19 07:11:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.14it/s]
  2%|▏         | 262/10519 [01:30<2:32:29,  1.12it/s][NeMo W 2026-06-19 07:11:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
[NeMo W 2026-06-19 07:11:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.46it/s]
[NeMo W 2026-06-19 07:11:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
  3%|▎         | 265/10519 [01:33<2:33:18,  1.11it/s][NeMo W 2026-06-19 07:11:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
[NeMo W 2026-06-19 07:11:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
  3%|▎         | 267/10519 [01:35<2:36:25,  1.09it/s][NeMo W 2026-06-19 07:11:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
[NeMo W 2026-06-19 07:11:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
  3%|▎         | 269/10519 [01:36<2:35:04,  1.10it/s][NeMo W 2026-06-19 07:11:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
  3%|▎         | 270/10519 [01:37<2:37:43,  1.08it/s][NeMo W 2026-06-19 07:11:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.88it/s]
  3%|▎         | 271/10519 [01:38<2:39:33,  1.07it/s][NeMo W 2026-06-19 07:11:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.00it/s]
  3%|▎         | 272/10519 [01:39<2:35:21,  1.10it/s][NeMo W 2026-06-19 07:11:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
  3%|▎         | 273/10519 [01:40<2:29:50,  1.14it/s][NeMo W 2026-06-19 07:11:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.67it/s]
  3%|▎         | 274/10519 [01:41<2:35:17,  1.10it/s][NeMo W 2026-06-19 07:11:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.43it/s]
  3%|▎         | 275/10519 [01:42<2:37:52,  1.08it/s][NeMo W 2026-06-19 07:11:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.49it/s]
  3%|▎         | 276/10519 [01:43<2:39:01,  1.07it/s][NeMo W 2026-06-19 07:11:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.59it/s]
  3%|▎         | 277/10519 [01:44<2:39:29,  1.07it/s][NeMo W 2026-06-19 07:11:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.69it/s]
  3%|▎         | 278/10519 [01:45<2:47:26,  1.02it/s][NeMo W 2026-06-19 07:11:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.26it/s]
  3%|▎         | 279/10519 [01:46<2:53:35,  1.02s/it][NeMo W 2026-06-19 07:11:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
  3%|▎         | 280/10519 [01:47<2:51:29,  1.00s/it][NeMo W 2026-06-19 07:11:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
  3%|▎         | 281/10519 [01:48<3:08:11,  1.10s/it][NeMo W 2026-06-19 07:11:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 300 samples

[NeMo W 2026-06-19 07:11:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.54it/s]
  3%|▎         | 301/10519 [02:07<2:40:10,  1.06it/s][NeMo W 2026-06-19 07:11:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.47it/s]
  3%|▎         | 302/10519 [02:08<2:35:41,  1.09it/s][NeMo W 2026-06-19 07:11:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.35it/s]
  3%|▎         | 303/10519 [02:09<2:40:57,  1.06it/s][NeMo W 2026-06-19 07:11:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
  3%|▎         | 304/10519 [02:10<2:41:09,  1.06it/s][NeMo W 2026-06-19 07:11:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.96it/s]
  3%|▎         | 305/10519 [02:11<2:38:50,  1.07it/s][NeMo W 2026-06-19 07:11:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
  3%|▎         | 306/10519 [02:12<2:34:15,  1.10it/s][NeMo W 2026-06-19 07:11:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
  3%|▎         | 307/10519 [02:13<2:41:38,  1.05it/s][NeMo W 2026-06-19 07:11:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.71it/s]
  3%|▎         | 308/10519 [02:14<2:40:39,  1.06it/s][NeMo W 2026-06-19 07:11:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.11it/s]
  3%|▎         | 309/10519 [02:15<2:42:18,  1.05it/s][NeMo W 2026-06-19 07:11:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.34it/s]
  3%|▎         | 310/10519 [02:16<2:35:16,  1.10it/s][NeMo W 2026-06-19 07:11:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.60it/s]
  3%|▎         | 311/10519 [02:16<2:27:56,  1.15it/s][NeMo W 2026-06-19 07:11:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.91it/s]
  3%|▎         | 312/10519 [02:17<2:29:53,  1.13it/s][NeMo W 2026-06-19 07:11:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:11:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.09it/s]
  3%|▎         | 313/10519 [02:18<2:36:49,  1.08it/s][NeMo W 2026-06-19 07:12:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
  3%|▎         | 314/10519 [02:19<2:40:43,  1.06it/s][NeMo W 2026-06-19 07:12:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.79it/s]
  3%|▎         | 315/10519 [02:21<3:02:01,  1.07s/it][NeMo W 2026-06-19 07:12:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
  3%|▎         | 316/10519 [02:22<2:56:24,  1.04s/it][NeMo W 2026-06-19 07:12:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.90it/s]
  3%|▎         | 317/10519 [02:23<2:46:19,  1.02it/s][NeMo W 2026-06-19 07:12:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.91it/s]
  3%|▎         | 318/10519 [02:23<2:40:05,  1.06it/s][NeMo W 2026-06-19 07:12:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
  3%|▎         | 319/10519 [02:24<2:42:46,  1.04it/s][NeMo W 2026-06-19 07:12:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
  3%|▎         | 320/10519 [02:25<2:45:30,  1.03it/s][NeMo W 2026-06-19 07:12:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.69it/s]
  3%|▎         | 321/10519 [02:26<2:42:39,  1.04it/s][NeMo W 2026-06-19 07:12:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.62it/s]
  3%|▎         | 322/10519 [02:27<2:42:06,  1.05it/s][NeMo W 2026-06-19 07:12:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
  3%|▎         | 323/10519 [02:28<2:38:38,  1.07it/s][NeMo W 2026-06-19 07:12:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.63it/s]
  3%|▎         | 324/10519 [02:29<2:51:15,  1.01s/it][NeMo W 2026-06-19 07:12:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
  3%|▎         | 325/10519 [02:30<2:39:34,  1.06it/s][NeMo W 2026-06-19 07:12:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.12it/s]
  3%|▎         | 326/10519 [02:31<2:37:21,  1.08it/s][NeMo W 2026-06-19 07:12:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.64it/s]
  3%|▎         | 327/10519 [02:32<2:37:54,  1.08it/s][NeMo W 2026-06-19 07:12:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
  3%|▎         | 328/10519 [02:33<2:37:24,  1.08it/s][NeMo W 2026-06-19 07:12:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.82it/s]
  3%|▎         | 329/10519 [02:34<2:27:03,  1.15it/s][NeMo W 2026-06-19 07:12:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.16it/s]
  3%|▎         | 330/10519 [02:35<2:40:12,  1.06it/s][NeMo W 2026-06-19 07:12:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 350 samples

[NeMo W 2026-06-19 07:12:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.83it/s]
  3%|▎         | 351/10519 [02:54<2:45:39,  1.02it/s][NeMo W 2026-06-19 07:12:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.22it/s]
  3%|▎         | 352/10519 [02:55<2:44:05,  1.03it/s][NeMo W 2026-06-19 07:12:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.77it/s]
  3%|▎         | 353/10519 [02:56<2:45:15,  1.03it/s][NeMo W 2026-06-19 07:12:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
  3%|▎         | 354/10519 [02:57<2:44:39,  1.03it/s][NeMo W 2026-06-19 07:12:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.64it/s]
  3%|▎         | 355/10519 [02:58<2:44:26,  1.03it/s][NeMo W 2026-06-19 07:12:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.72it/s]
  3%|▎         | 356/10519 [02:59<2:44:36,  1.03it/s][NeMo W 2026-06-19 07:12:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.77it/s]
  3%|▎         | 357/10519 [02:59<2:42:27,  1.04it/s][NeMo W 2026-06-19 07:12:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.02it/s]
  3%|▎         | 358/10519 [03:00<2:39:53,  1.06it/s][NeMo W 2026-06-19 07:12:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
  3%|▎         | 359/10519 [03:01<2:39:17,  1.06it/s][NeMo W 2026-06-19 07:12:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
  3%|▎         | 360/10519 [03:02<2:37:23,  1.08it/s][NeMo W 2026-06-19 07:12:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 19.82it/s]
  3%|▎         | 361/10519 [03:04<3:00:45,  1.07s/it][NeMo W 2026-06-19 07:12:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.32it/s]
  3%|▎         | 362/10519 [03:05<2:52:56,  1.02s/it][NeMo W 2026-06-19 07:12:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.95it/s]
  3%|▎         | 363/10519 [03:06<3:09:36,  1.12s/it][NeMo W 2026-06-19 07:12:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.64it/s]
  3%|▎         | 364/10519 [03:07<2:59:20,  1.06s/it][NeMo W 2026-06-19 07:12:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.82it/s]
  3%|▎         | 365/10519 [03:08<2:55:22,  1.04s/it][NeMo W 2026-06-19 07:12:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.94it/s]
  3%|▎         | 366/10519 [03:09<2:51:23,  1.01s/it][NeMo W 2026-06-19 07:12:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.19it/s]
  3%|▎         | 367/10519 [03:10<2:48:06,  1.01it/s][NeMo W 2026-06-19 07:12:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.88it/s]
  3%|▎         | 368/10519 [03:11<2:47:48,  1.01it/s][NeMo W 2026-06-19 07:12:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.73it/s]
  4%|▎         | 369/10519 [03:12<2:41:58,  1.04it/s][NeMo W 2026-06-19 07:12:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
  4%|▎         | 370/10519 [03:13<2:41:35,  1.05it/s][NeMo W 2026-06-19 07:12:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
  4%|▎         | 371/10519 [03:14<2:52:22,  1.02s/it][NeMo W 2026-06-19 07:12:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
  4%|▎         | 372/10519 [03:15<2:49:48,  1.00s/it][NeMo W 2026-06-19 07:12:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
  4%|▎         | 373/10519 [03:15<2:41:27,  1.05it/s][NeMo W 2026-06-19 07:12:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.06it/s]
  4%|▎         | 374/10519 [03:16<2:42:01,  1.04it/s][NeMo W 2026-06-19 07:12:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.46it/s]
  4%|▎         | 375/10519 [03:17<2:38:57,  1.06it/s][NeMo W 2026-06-19 07:12:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:12:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.49it/s]
  4%|▎         | 376/10519 [03:18<2:29:31,  1.13it/s][NeMo W 2026-06-19 07:13:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 18.09it/s]
  4%|▎         | 377/10519 [03:19<2:34:14,  1.10it/s][NeMo W 2026-06-19 07:13:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.75it/s]
  4%|▎         | 378/10519 [03:20<2:39:40,  1.06it/s][NeMo W 2026-06-19 07:13:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.92it/s]
  4%|▎         | 379/10519 [03:21<2:38:32,  1.07it/s][NeMo W 2026-06-19 07:13:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.84it/s]
  4%|▎         | 380/10519 [03:22<2:39:41,  1.06it/s][NeMo W 2026-06-19 07:13:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 400 samples

[NeMo W 2026-06-19 07:13:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.96it/s]
  4%|▍         | 401/10519 [03:41<2:36:11,  1.08it/s][NeMo W 2026-06-19 07:13:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
  4%|▍         | 402/10519 [03:43<2:44:33,  1.02it/s][NeMo W 2026-06-19 07:13:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.54it/s]
  4%|▍         | 403/10519 [03:44<2:46:07,  1.01it/s][NeMo W 2026-06-19 07:13:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
  4%|▍         | 404/10519 [03:45<2:54:03,  1.03s/it][NeMo W 2026-06-19 07:13:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.82it/s]
  4%|▍         | 405/10519 [03:46<2:53:57,  1.03s/it][NeMo W 2026-06-19 07:13:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.37it/s]
  4%|▍         | 406/10519 [03:47<2:46:57,  1.01it/s][NeMo W 2026-06-19 07:13:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.53it/s]
  4%|▍         | 407/10519 [03:48<2:45:11,  1.02it/s][NeMo W 2026-06-19 07:13:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.42it/s]
  4%|▍         | 408/10519 [03:48<2:42:15,  1.04it/s][NeMo W 2026-06-19 07:13:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.41it/s]
  4%|▍         | 409/10519 [03:49<2:39:33,  1.06it/s][NeMo W 2026-06-19 07:13:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.35it/s]
  4%|▍         | 410/10519 [03:50<2:28:03,  1.14it/s][NeMo W 2026-06-19 07:13:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
  4%|▍         | 411/10519 [03:51<2:33:19,  1.10it/s][NeMo W 2026-06-19 07:13:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
  4%|▍         | 412/10519 [03:52<2:35:47,  1.08it/s][NeMo W 2026-06-19 07:13:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
  4%|▍         | 413/10519 [03:53<2:38:00,  1.07it/s][NeMo W 2026-06-19 07:13:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
  4%|▍         | 414/10519 [03:54<2:37:24,  1.07it/s][NeMo W 2026-06-19 07:13:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.53it/s]
  4%|▍         | 415/10519 [03:55<2:37:22,  1.07it/s][NeMo W 2026-06-19 07:13:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.11it/s]
  4%|▍         | 416/10519 [03:56<2:38:04,  1.07it/s][NeMo W 2026-06-19 07:13:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.30it/s]
  4%|▍         | 417/10519 [03:57<2:40:16,  1.05it/s][NeMo W 2026-06-19 07:13:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.71it/s]
  4%|▍         | 418/10519 [03:58<2:39:41,  1.05it/s][NeMo W 2026-06-19 07:13:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
  4%|▍         | 419/10519 [03:59<2:37:31,  1.07it/s][NeMo W 2026-06-19 07:13:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
  4%|▍         | 420/10519 [04:00<2:40:27,  1.05it/s][NeMo W 2026-06-19 07:13:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.63it/s]
  4%|▍         | 421/10519 [04:00<2:35:25,  1.08it/s][NeMo W 2026-06-19 07:13:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.27it/s]
  4%|▍         | 422/10519 [04:01<2:23:31,  1.17it/s][NeMo W 2026-06-19 07:13:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.08it/s]
  4%|▍         | 423/10519 [04:02<2:27:10,  1.14it/s][NeMo W 2026-06-19 07:13:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.25it/s]
  4%|▍         | 424/10519 [04:03<2:31:16,  1.11it/s][NeMo W 2026-06-19 07:13:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.53it/s]
  4%|▍         | 425/10519 [04:04<2:37:16,  1.07it/s][NeMo W 2026-06-19 07:13:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.59it/s]
  4%|▍         | 426/10519 [04:05<2:41:43,  1.04it/s][NeMo W 2026-06-19 07:13:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.37it/s]
  4%|▍         | 427/10519 [04:06<2:38:45,  1.06it/s][NeMo W 2026-06-19 07:13:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.42it/s]
  4%|▍         | 428/10519 [04:07<2:38:43,  1.06it/s][NeMo W 2026-06-19 07:13:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
  4%|▍         | 429/10519 [04:08<2:36:32,  1.07it/s][NeMo W 2026-06-19 07:13:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:13:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.59it/s]
  4%|▍         | 430/10519 [04:09<2:35:12,  1.08it/s][NeMo W 2026-06-19 07:13:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 450 samples

[NeMo W 2026-06-19 07:14:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
  4%|▍         | 451/10519 [04:29<2:43:50,  1.02it/s][NeMo W 2026-06-19 07:14:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
  4%|▍         | 452/10519 [04:30<2:35:17,  1.08it/s][NeMo W 2026-06-19 07:14:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
  4%|▍         | 453/10519 [04:31<2:36:09,  1.07it/s][NeMo W 2026-06-19 07:14:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.05it/s]
  4%|▍         | 454/10519 [04:32<2:37:31,  1.06it/s][NeMo W 2026-06-19 07:14:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.79it/s]
  4%|▍         | 455/10519 [04:33<2:38:15,  1.06it/s][NeMo W 2026-06-19 07:14:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
  4%|▍         | 456/10519 [04:34<2:38:44,  1.06it/s][NeMo W 2026-06-19 07:14:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.02it/s]
  4%|▍         | 457/10519 [04:35<2:40:04,  1.05it/s][NeMo W 2026-06-19 07:14:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
  4%|▍         | 458/10519 [04:36<2:40:04,  1.05it/s][NeMo W 2026-06-19 07:14:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
  4%|▍         | 459/10519 [04:37<2:41:22,  1.04it/s][NeMo W 2026-06-19 07:14:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
  4%|▍         | 460/10519 [04:37<2:38:31,  1.06it/s][NeMo W 2026-06-19 07:14:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.15it/s]
  4%|▍         | 461/10519 [04:39<2:47:18,  1.00it/s][NeMo W 2026-06-19 07:14:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.05it/s]
  4%|▍         | 462/10519 [04:39<2:41:18,  1.04it/s][NeMo W 2026-06-19 07:14:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
  4%|▍         | 463/10519 [04:40<2:41:44,  1.04it/s][NeMo W 2026-06-19 07:14:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
  4%|▍         | 464/10519 [04:41<2:45:11,  1.01it/s][NeMo W 2026-06-19 07:14:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.84it/s]
  4%|▍         | 465/10519 [04:43<2:47:24,  1.00it/s][NeMo W 2026-06-19 07:14:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.29it/s]
  4%|▍         | 466/10519 [04:43<2:34:42,  1.08it/s][NeMo W 2026-06-19 07:14:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.32it/s]
  4%|▍         | 467/10519 [04:44<2:33:41,  1.09it/s][NeMo W 2026-06-19 07:14:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
  4%|▍         | 468/10519 [04:45<2:36:14,  1.07it/s][NeMo W 2026-06-19 07:14:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
  4%|▍         | 469/10519 [04:46<2:36:59,  1.07it/s][NeMo W 2026-06-19 07:14:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
  4%|▍         | 470/10519 [04:47<2:36:37,  1.07it/s][NeMo W 2026-06-19 07:14:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.35it/s]
  4%|▍         | 471/10519 [04:48<2:37:01,  1.07it/s][NeMo W 2026-06-19 07:14:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.50it/s]
  4%|▍         | 472/10519 [04:49<2:36:23,  1.07it/s][NeMo W 2026-06-19 07:14:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.49it/s]
  4%|▍         | 473/10519 [04:50<2:36:22,  1.07it/s][NeMo W 2026-06-19 07:14:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
  5%|▍         | 474/10519 [04:51<2:29:41,  1.12it/s][NeMo W 2026-06-19 07:14:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
  5%|▍         | 475/10519 [04:52<2:30:57,  1.11it/s][NeMo W 2026-06-19 07:14:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.76it/s]
  5%|▍         | 476/10519 [04:52<2:28:57,  1.12it/s][NeMo W 2026-06-19 07:14:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
  5%|▍         | 477/10519 [04:53<2:31:16,  1.11it/s][NeMo W 2026-06-19 07:14:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
  5%|▍         | 478/10519 [04:54<2:27:53,  1.13it/s][NeMo W 2026-06-19 07:14:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
  5%|▍         | 479/10519 [04:55<2:33:51,  1.09it/s][NeMo W 2026-06-19 07:14:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.84it/s]
  5%|▍         | 480/10519 [04:56<2:36:38,  1.07it/s][NeMo W 2026-06-19 07:14:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 500 samples

[NeMo W 2026-06-19 07:14:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.03it/s]
  5%|▍         | 501/10519 [05:17<2:41:44,  1.03it/s][NeMo W 2026-06-19 07:14:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:14:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
  5%|▍         | 502/10519 [05:18<2:46:36,  1.00it/s][NeMo W 2026-06-19 07:15:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
  5%|▍         | 503/10519 [05:19<2:38:03,  1.06it/s][NeMo W 2026-06-19 07:15:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
  5%|▍         | 504/10519 [05:20<2:40:41,  1.04it/s][NeMo W 2026-06-19 07:15:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.34it/s]
  5%|▍         | 505/10519 [05:21<2:37:56,  1.06it/s][NeMo W 2026-06-19 07:15:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.94it/s]
  5%|▍         | 506/10519 [05:22<2:36:05,  1.07it/s][NeMo W 2026-06-19 07:15:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
  5%|▍         | 507/10519 [05:23<2:35:18,  1.07it/s][NeMo W 2026-06-19 07:15:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.80it/s]
  5%|▍         | 508/10519 [05:24<2:34:27,  1.08it/s][NeMo W 2026-06-19 07:15:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.17it/s]
  5%|▍         | 509/10519 [05:24<2:22:02,  1.17it/s][NeMo W 2026-06-19 07:15:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.19it/s]
  5%|▍         | 510/10519 [05:25<2:27:18,  1.13it/s][NeMo W 2026-06-19 07:15:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.43it/s]
  5%|▍         | 511/10519 [05:26<2:30:37,  1.11it/s][NeMo W 2026-06-19 07:15:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.98it/s]
  5%|▍         | 512/10519 [05:27<2:35:08,  1.07it/s][NeMo W 2026-06-19 07:15:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.55it/s]
  5%|▍         | 513/10519 [05:28<2:35:58,  1.07it/s][NeMo W 2026-06-19 07:15:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.45it/s]
  5%|▍         | 514/10519 [05:29<2:28:01,  1.13it/s][NeMo W 2026-06-19 07:15:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.36it/s]
  5%|▍         | 515/10519 [05:30<2:20:04,  1.19it/s][NeMo W 2026-06-19 07:15:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
  5%|▍         | 516/10519 [05:31<2:27:00,  1.13it/s][NeMo W 2026-06-19 07:15:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
  5%|▍         | 517/10519 [05:32<2:27:59,  1.13it/s][NeMo W 2026-06-19 07:15:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
  5%|▍         | 518/10519 [05:32<2:23:05,  1.16it/s][NeMo W 2026-06-19 07:15:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.01it/s]
  5%|▍         | 519/10519 [05:33<2:17:00,  1.22it/s][NeMo W 2026-06-19 07:15:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
  5%|▍         | 520/10519 [05:34<2:11:04,  1.27it/s][NeMo W 2026-06-19 07:15:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
  5%|▍         | 521/10519 [05:35<2:22:35,  1.17it/s][NeMo W 2026-06-19 07:15:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.41it/s]
  5%|▍         | 522/10519 [05:36<2:36:41,  1.06it/s][NeMo W 2026-06-19 07:15:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.49it/s]
  5%|▍         | 523/10519 [05:37<2:37:29,  1.06it/s][NeMo W 2026-06-19 07:15:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
  5%|▍         | 524/10519 [05:38<2:49:30,  1.02s/it][NeMo W 2026-06-19 07:15:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.99it/s]
  5%|▍         | 525/10519 [05:39<2:34:26,  1.08it/s][NeMo W 2026-06-19 07:15:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
  5%|▌         | 526/10519 [05:40<2:35:02,  1.07it/s][NeMo W 2026-06-19 07:15:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
  5%|▌         | 527/10519 [05:41<2:36:53,  1.06it/s][NeMo W 2026-06-19 07:15:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.38it/s]
  5%|▌         | 528/10519 [05:42<2:34:56,  1.07it/s][NeMo W 2026-06-19 07:15:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
  5%|▌         | 529/10519 [05:43<2:37:19,  1.06it/s][NeMo W 2026-06-19 07:15:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
  5%|▌         | 530/10519 [05:44<2:36:31,  1.06it/s][NeMo W 2026-06-19 07:15:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 550 samples

[NeMo W 2026-06-19 07:15:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.99it/s]
  5%|▌         | 551/10519 [06:05<2:39:39,  1.04it/s][NeMo W 2026-06-19 07:15:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.53it/s]
  5%|▌         | 552/10519 [06:06<2:37:57,  1.05it/s][NeMo W 2026-06-19 07:15:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.39it/s]
  5%|▌         | 553/10519 [06:07<2:41:39,  1.03it/s][NeMo W 2026-06-19 07:15:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
  5%|▌         | 554/10519 [06:08<2:42:35,  1.02it/s][NeMo W 2026-06-19 07:15:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.63it/s]
  5%|▌         | 555/10519 [06:08<2:35:51,  1.07it/s][NeMo W 2026-06-19 07:15:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
  5%|▌         | 556/10519 [06:09<2:26:03,  1.14it/s][NeMo W 2026-06-19 07:15:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.99it/s]
  5%|▌         | 557/10519 [06:10<2:22:58,  1.16it/s][NeMo W 2026-06-19 07:15:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
  5%|▌         | 558/10519 [06:11<2:29:42,  1.11it/s][NeMo W 2026-06-19 07:15:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.12it/s]
  5%|▌         | 559/10519 [06:12<2:31:46,  1.09it/s][NeMo W 2026-06-19 07:15:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
  5%|▌         | 560/10519 [06:13<2:24:37,  1.15it/s][NeMo W 2026-06-19 07:15:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.02it/s]
  5%|▌         | 561/10519 [06:14<2:23:43,  1.15it/s][NeMo W 2026-06-19 07:15:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.86it/s]
  5%|▌         | 562/10519 [06:15<2:28:58,  1.11it/s][NeMo W 2026-06-19 07:15:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
  5%|▌         | 563/10519 [06:15<2:22:13,  1.17it/s][NeMo W 2026-06-19 07:15:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.01it/s]
  5%|▌         | 564/10519 [06:16<2:24:29,  1.15it/s][NeMo W 2026-06-19 07:15:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.72it/s]
  5%|▌         | 565/10519 [06:17<2:22:17,  1.17it/s][NeMo W 2026-06-19 07:15:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:15:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.57it/s]
  5%|▌         | 566/10519 [06:18<2:17:29,  1.21it/s][NeMo W 2026-06-19 07:16:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.43it/s]
  5%|▌         | 567/10519 [06:19<2:24:06,  1.15it/s][NeMo W 2026-06-19 07:16:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
  5%|▌         | 568/10519 [06:20<2:31:05,  1.10it/s][NeMo W 2026-06-19 07:16:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
  5%|▌         | 569/10519 [06:21<2:36:11,  1.06it/s][NeMo W 2026-06-19 07:16:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
  5%|▌         | 570/10519 [06:22<2:38:33,  1.05it/s][NeMo W 2026-06-19 07:16:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.96it/s]
  5%|▌         | 571/10519 [06:23<2:40:00,  1.04it/s][NeMo W 2026-06-19 07:16:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
  5%|▌         | 572/10519 [06:24<2:40:02,  1.04it/s][NeMo W 2026-06-19 07:16:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.55it/s]
  5%|▌         | 573/10519 [06:25<2:39:13,  1.04it/s][NeMo W 2026-06-19 07:16:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.29it/s]
  5%|▌         | 574/10519 [06:25<2:31:07,  1.10it/s][NeMo W 2026-06-19 07:16:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.07it/s]
  5%|▌         | 575/10519 [06:26<2:35:05,  1.07it/s][NeMo W 2026-06-19 07:16:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.96it/s]
  5%|▌         | 576/10519 [06:27<2:36:34,  1.06it/s][NeMo W 2026-06-19 07:16:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.60it/s]
  5%|▌         | 577/10519 [06:28<2:33:28,  1.08it/s][NeMo W 2026-06-19 07:16:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
  5%|▌         | 578/10519 [06:29<2:33:48,  1.08it/s][NeMo W 2026-06-19 07:16:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
  6%|▌         | 579/10519 [06:30<2:35:41,  1.06it/s][NeMo W 2026-06-19 07:16:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.46it/s]
  6%|▌         | 580/10519 [06:31<2:27:07,  1.13it/s][NeMo W 2026-06-19 07:16:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 600 samples

[NeMo W 2026-06-19 07:16:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.37it/s]
  6%|▌         | 601/10519 [06:53<2:39:43,  1.03it/s][NeMo W 2026-06-19 07:16:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
  6%|▌         | 602/10519 [06:54<2:41:24,  1.02it/s][NeMo W 2026-06-19 07:16:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.07it/s]
  6%|▌         | 603/10519 [06:55<2:56:47,  1.07s/it][NeMo W 2026-06-19 07:16:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.18it/s]
  6%|▌         | 604/10519 [06:56<2:50:03,  1.03s/it][NeMo W 2026-06-19 07:16:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
  6%|▌         | 605/10519 [06:57<2:54:16,  1.05s/it][NeMo W 2026-06-19 07:16:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
  6%|▌         | 606/10519 [06:58<2:51:24,  1.04s/it][NeMo W 2026-06-19 07:16:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
  6%|▌         | 607/10519 [06:59<2:46:49,  1.01s/it][NeMo W 2026-06-19 07:16:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.69it/s]
  6%|▌         | 608/10519 [07:00<2:42:51,  1.01it/s][NeMo W 2026-06-19 07:16:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
  6%|▌         | 609/10519 [07:01<2:40:18,  1.03it/s][NeMo W 2026-06-19 07:16:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.41it/s]
  6%|▌         | 610/10519 [07:01<2:30:16,  1.10it/s][NeMo W 2026-06-19 07:16:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.24it/s]
  6%|▌         | 611/10519 [07:02<2:27:40,  1.12it/s][NeMo W 2026-06-19 07:16:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.91it/s]
  6%|▌         | 612/10519 [07:03<2:27:09,  1.12it/s][NeMo W 2026-06-19 07:16:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.43it/s]
  6%|▌         | 613/10519 [07:04<2:30:22,  1.10it/s][NeMo W 2026-06-19 07:16:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.09it/s]
  6%|▌         | 614/10519 [07:05<2:32:16,  1.08it/s][NeMo W 2026-06-19 07:16:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.76it/s]
  6%|▌         | 615/10519 [07:06<2:38:36,  1.04it/s][NeMo W 2026-06-19 07:16:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
  6%|▌         | 616/10519 [07:07<2:38:43,  1.04it/s][NeMo W 2026-06-19 07:16:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.40it/s]
  6%|▌         | 617/10519 [07:08<2:36:47,  1.05it/s][NeMo W 2026-06-19 07:16:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.35it/s]
  6%|▌         | 618/10519 [07:09<2:43:12,  1.01it/s][NeMo W 2026-06-19 07:16:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
  6%|▌         | 619/10519 [07:10<2:42:25,  1.02it/s][NeMo W 2026-06-19 07:16:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
  6%|▌         | 620/10519 [07:11<2:51:59,  1.04s/it][NeMo W 2026-06-19 07:16:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.06it/s]
  6%|▌         | 621/10519 [07:12<2:44:49,  1.00it/s][NeMo W 2026-06-19 07:16:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.95it/s]
  6%|▌         | 622/10519 [07:13<2:54:01,  1.05s/it][NeMo W 2026-06-19 07:16:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.46it/s]
  6%|▌         | 623/10519 [07:14<2:49:57,  1.03s/it][NeMo W 2026-06-19 07:16:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
  6%|▌         | 624/10519 [07:15<2:44:55,  1.00s/it][NeMo W 2026-06-19 07:16:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
  6%|▌         | 625/10519 [07:16<2:49:10,  1.03s/it][NeMo W 2026-06-19 07:16:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
  6%|▌         | 626/10519 [07:17<2:33:34,  1.07it/s][NeMo W 2026-06-19 07:16:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:16:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
  6%|▌         | 627/10519 [07:18<2:44:34,  1.00it/s][NeMo W 2026-06-19 07:17:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.14it/s]
  6%|▌         | 628/10519 [07:19<2:44:22,  1.00it/s][NeMo W 2026-06-19 07:17:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
  6%|▌         | 629/10519 [07:20<2:33:08,  1.08it/s][NeMo W 2026-06-19 07:17:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.93it/s]
  6%|▌         | 630/10519 [07:21<2:31:12,  1.09it/s][NeMo W 2026-06-19 07:17:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 650 samples

[NeMo W 2026-06-19 07:17:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.68it/s]
  6%|▌         | 651/10519 [07:41<2:36:41,  1.05it/s][NeMo W 2026-06-19 07:17:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.34it/s]
  6%|▌         | 652/10519 [07:42<2:41:35,  1.02it/s][NeMo W 2026-06-19 07:17:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.88it/s]
  6%|▌         | 653/10519 [07:43<2:34:52,  1.06it/s][NeMo W 2026-06-19 07:17:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.52it/s]
  6%|▌         | 654/10519 [07:44<2:22:39,  1.15it/s][NeMo W 2026-06-19 07:17:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
  6%|▌         | 655/10519 [07:45<2:34:05,  1.07it/s][NeMo W 2026-06-19 07:17:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
  6%|▌         | 656/10519 [07:46<2:44:05,  1.00it/s][NeMo W 2026-06-19 07:17:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
  6%|▌         | 657/10519 [07:47<2:46:04,  1.01s/it][NeMo W 2026-06-19 07:17:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.57it/s]
  6%|▋         | 658/10519 [07:48<2:43:30,  1.01it/s][NeMo W 2026-06-19 07:17:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
  6%|▋         | 659/10519 [07:49<2:47:12,  1.02s/it][NeMo W 2026-06-19 07:17:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
  6%|▋         | 660/10519 [07:50<2:44:04,  1.00it/s][NeMo W 2026-06-19 07:17:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.40it/s]
  6%|▋         | 661/10519 [07:51<2:38:18,  1.04it/s][NeMo W 2026-06-19 07:17:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.97it/s]
  6%|▋         | 662/10519 [07:52<2:40:02,  1.03it/s][NeMo W 2026-06-19 07:17:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
  6%|▋         | 663/10519 [07:53<2:40:37,  1.02it/s][NeMo W 2026-06-19 07:17:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.61it/s]
  6%|▋         | 664/10519 [07:54<2:37:19,  1.04it/s][NeMo W 2026-06-19 07:17:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.39it/s]
  6%|▋         | 665/10519 [07:55<2:37:11,  1.04it/s][NeMo W 2026-06-19 07:17:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.48it/s]
  6%|▋         | 666/10519 [07:56<2:34:43,  1.06it/s][NeMo W 2026-06-19 07:17:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.87it/s]
  6%|▋         | 667/10519 [07:57<2:34:04,  1.07it/s][NeMo W 2026-06-19 07:17:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.86it/s]
  6%|▋         | 668/10519 [07:57<2:28:14,  1.11it/s][NeMo W 2026-06-19 07:17:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.73it/s]
  6%|▋         | 669/10519 [07:58<2:29:57,  1.09it/s][NeMo W 2026-06-19 07:17:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
  6%|▋         | 670/10519 [07:59<2:42:11,  1.01it/s][NeMo W 2026-06-19 07:17:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
  6%|▋         | 671/10519 [08:00<2:33:29,  1.07it/s][NeMo W 2026-06-19 07:17:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
  6%|▋         | 672/10519 [08:01<2:35:48,  1.05it/s][NeMo W 2026-06-19 07:17:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.50it/s]
  6%|▋         | 673/10519 [08:02<2:33:28,  1.07it/s][NeMo W 2026-06-19 07:17:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.61it/s]
  6%|▋         | 674/10519 [08:03<2:33:26,  1.07it/s][NeMo W 2026-06-19 07:17:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.54it/s]
  6%|▋         | 675/10519 [08:04<2:31:15,  1.08it/s][NeMo W 2026-06-19 07:17:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
  6%|▋         | 676/10519 [08:05<2:39:34,  1.03it/s][NeMo W 2026-06-19 07:17:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
  6%|▋         | 677/10519 [08:06<2:57:07,  1.08s/it][NeMo W 2026-06-19 07:17:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.07it/s]
  6%|▋         | 678/10519 [08:07<2:52:52,  1.05s/it][NeMo W 2026-06-19 07:17:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
  6%|▋         | 679/10519 [08:08<2:48:10,  1.03s/it][NeMo W 2026-06-19 07:17:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:17:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.29it/s]
  6%|▋         | 680/10519 [08:09<2:44:12,  1.00s/it][NeMo W 2026-06-19 07:17:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 700 samples

[NeMo W 2026-06-19 07:18:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
  7%|▋         | 701/10519 [08:29<2:48:35,  1.03s/it][NeMo W 2026-06-19 07:18:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.80it/s]
  7%|▋         | 702/10519 [08:30<2:44:06,  1.00s/it][NeMo W 2026-06-19 07:18:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
  7%|▋         | 703/10519 [08:31<2:31:53,  1.08it/s][NeMo W 2026-06-19 07:18:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.65it/s]
  7%|▋         | 704/10519 [08:31<2:21:39,  1.15it/s][NeMo W 2026-06-19 07:18:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
  7%|▋         | 705/10519 [08:32<2:28:05,  1.10it/s][NeMo W 2026-06-19 07:18:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.61it/s]
  7%|▋         | 706/10519 [08:33<2:28:51,  1.10it/s][NeMo W 2026-06-19 07:18:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.58it/s]
  7%|▋         | 707/10519 [08:34<2:34:29,  1.06it/s][NeMo W 2026-06-19 07:18:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.22it/s]
  7%|▋         | 708/10519 [08:35<2:34:19,  1.06it/s][NeMo W 2026-06-19 07:18:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
  7%|▋         | 709/10519 [08:36<2:43:15,  1.00it/s][NeMo W 2026-06-19 07:18:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
  7%|▋         | 710/10519 [08:38<3:02:49,  1.12s/it][NeMo W 2026-06-19 07:18:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
  7%|▋         | 711/10519 [08:39<2:58:59,  1.10s/it][NeMo W 2026-06-19 07:18:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.23it/s]
  7%|▋         | 712/10519 [08:40<2:51:11,  1.05s/it][NeMo W 2026-06-19 07:18:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.60it/s]
  7%|▋         | 713/10519 [08:41<2:47:25,  1.02s/it][NeMo W 2026-06-19 07:18:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.74it/s]
  7%|▋         | 714/10519 [08:42<2:43:40,  1.00s/it][NeMo W 2026-06-19 07:18:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.78it/s]
  7%|▋         | 715/10519 [08:43<2:43:24,  1.00s/it][NeMo W 2026-06-19 07:18:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
  7%|▋         | 716/10519 [08:44<2:39:42,  1.02it/s][NeMo W 2026-06-19 07:18:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
  7%|▋         | 717/10519 [08:44<2:37:57,  1.03it/s][NeMo W 2026-06-19 07:18:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
  7%|▋         | 718/10519 [08:46<2:40:38,  1.02it/s][NeMo W 2026-06-19 07:18:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.22it/s]
  7%|▋         | 719/10519 [08:47<3:06:32,  1.14s/it][NeMo W 2026-06-19 07:18:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
  7%|▋         | 720/10519 [08:48<2:57:26,  1.09s/it][NeMo W 2026-06-19 07:18:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.14it/s]
  7%|▋         | 721/10519 [08:49<2:48:11,  1.03s/it][NeMo W 2026-06-19 07:18:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
  7%|▋         | 722/10519 [08:50<2:47:50,  1.03s/it][NeMo W 2026-06-19 07:18:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.09it/s]
  7%|▋         | 723/10519 [08:51<2:49:03,  1.04s/it][NeMo W 2026-06-19 07:18:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.41it/s]
  7%|▋         | 724/10519 [08:52<2:49:24,  1.04s/it][NeMo W 2026-06-19 07:18:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
  7%|▋         | 725/10519 [08:53<2:56:29,  1.08s/it][NeMo W 2026-06-19 07:18:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
  7%|▋         | 726/10519 [08:54<2:52:58,  1.06s/it][NeMo W 2026-06-19 07:18:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.91it/s]
  7%|▋         | 727/10519 [08:55<2:46:53,  1.02s/it][NeMo W 2026-06-19 07:18:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
  7%|▋         | 728/10519 [08:56<2:42:59,  1.00it/s][NeMo W 2026-06-19 07:18:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.50it/s]
  7%|▋         | 729/10519 [08:57<2:36:19,  1.04it/s][NeMo W 2026-06-19 07:18:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.53it/s]
  7%|▋         | 730/10519 [08:58<2:23:26,  1.14it/s][NeMo W 2026-06-19 07:18:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 750 samples

[NeMo W 2026-06-19 07:18:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
  7%|▋         | 751/10519 [09:18<2:31:56,  1.07it/s][NeMo W 2026-06-19 07:18:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:18:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
  7%|▋         | 752/10519 [09:19<2:34:49,  1.05it/s][NeMo W 2026-06-19 07:19:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.44it/s]
  7%|▋         | 753/10519 [09:20<2:33:16,  1.06it/s][NeMo W 2026-06-19 07:19:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.39it/s]
  7%|▋         | 754/10519 [09:21<2:32:18,  1.07it/s][NeMo W 2026-06-19 07:19:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.40it/s]
  7%|▋         | 755/10519 [09:21<2:26:48,  1.11it/s][NeMo W 2026-06-19 07:19:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
  7%|▋         | 756/10519 [09:22<2:29:58,  1.08it/s][NeMo W 2026-06-19 07:19:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
  7%|▋         | 757/10519 [09:23<2:31:44,  1.07it/s][NeMo W 2026-06-19 07:19:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
  7%|▋         | 758/10519 [09:24<2:31:48,  1.07it/s][NeMo W 2026-06-19 07:19:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
  7%|▋         | 759/10519 [09:25<2:33:27,  1.06it/s][NeMo W 2026-06-19 07:19:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
  7%|▋         | 760/10519 [09:26<2:30:02,  1.08it/s][NeMo W 2026-06-19 07:19:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
  7%|▋         | 761/10519 [09:27<2:40:52,  1.01it/s][NeMo W 2026-06-19 07:19:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.78it/s]
  7%|▋         | 762/10519 [09:28<2:50:25,  1.05s/it][NeMo W 2026-06-19 07:19:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.58it/s]
  7%|▋         | 763/10519 [09:29<2:46:29,  1.02s/it][NeMo W 2026-06-19 07:19:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.59it/s]
  7%|▋         | 764/10519 [09:30<2:46:36,  1.02s/it][NeMo W 2026-06-19 07:19:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
  7%|▋         | 765/10519 [09:31<2:45:13,  1.02s/it][NeMo W 2026-06-19 07:19:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.46it/s]
  7%|▋         | 766/10519 [09:32<2:40:34,  1.01it/s][NeMo W 2026-06-19 07:19:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.43it/s]
  7%|▋         | 767/10519 [09:33<2:36:57,  1.04it/s][NeMo W 2026-06-19 07:19:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
  7%|▋         | 768/10519 [09:34<2:43:50,  1.01s/it][NeMo W 2026-06-19 07:19:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.92it/s]
  7%|▋         | 769/10519 [09:35<2:39:22,  1.02it/s][NeMo W 2026-06-19 07:19:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
  7%|▋         | 770/10519 [09:36<2:37:36,  1.03it/s][NeMo W 2026-06-19 07:19:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.40it/s]
  7%|▋         | 771/10519 [09:38<3:17:42,  1.22s/it][NeMo W 2026-06-19 07:19:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.00it/s]
  7%|▋         | 772/10519 [09:39<2:54:47,  1.08s/it][NeMo W 2026-06-19 07:19:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.96it/s]
  7%|▋         | 773/10519 [09:40<2:51:21,  1.05s/it][NeMo W 2026-06-19 07:19:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.36it/s]
  7%|▋         | 774/10519 [09:41<2:48:42,  1.04s/it][NeMo W 2026-06-19 07:19:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
  7%|▋         | 775/10519 [09:42<2:48:54,  1.04s/it][NeMo W 2026-06-19 07:19:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
  7%|▋         | 776/10519 [09:43<2:47:43,  1.03s/it][NeMo W 2026-06-19 07:19:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.11it/s]
  7%|▋         | 777/10519 [09:44<2:40:53,  1.01it/s][NeMo W 2026-06-19 07:19:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
  7%|▋         | 778/10519 [09:45<2:39:03,  1.02it/s][NeMo W 2026-06-19 07:19:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
  7%|▋         | 779/10519 [09:46<2:37:45,  1.03it/s][NeMo W 2026-06-19 07:19:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
  7%|▋         | 780/10519 [09:46<2:25:00,  1.12it/s][NeMo W 2026-06-19 07:19:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 800 samples

[NeMo W 2026-06-19 07:19:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.98it/s]
  8%|▊         | 801/10519 [10:07<2:44:23,  1.02s/it][NeMo W 2026-06-19 07:19:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.77it/s]
  8%|▊         | 802/10519 [10:08<2:40:49,  1.01it/s][NeMo W 2026-06-19 07:19:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.00it/s]
  8%|▊         | 803/10519 [10:08<2:31:28,  1.07it/s][NeMo W 2026-06-19 07:19:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
  8%|▊         | 804/10519 [10:09<2:35:28,  1.04it/s][NeMo W 2026-06-19 07:19:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
  8%|▊         | 805/10519 [10:10<2:37:59,  1.02it/s][NeMo W 2026-06-19 07:19:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
  8%|▊         | 806/10519 [10:11<2:34:57,  1.04it/s][NeMo W 2026-06-19 07:19:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.89it/s]
  8%|▊         | 807/10519 [10:12<2:22:50,  1.13it/s][NeMo W 2026-06-19 07:19:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
  8%|▊         | 808/10519 [10:13<2:50:38,  1.05s/it][NeMo W 2026-06-19 07:19:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.91it/s]
  8%|▊         | 809/10519 [10:14<2:43:41,  1.01s/it][NeMo W 2026-06-19 07:19:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.27it/s]
  8%|▊         | 810/10519 [10:15<2:38:23,  1.02it/s][NeMo W 2026-06-19 07:19:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
  8%|▊         | 811/10519 [10:16<2:36:43,  1.03it/s][NeMo W 2026-06-19 07:19:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
  8%|▊         | 812/10519 [10:17<2:38:41,  1.02it/s][NeMo W 2026-06-19 07:19:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:19:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
  8%|▊         | 813/10519 [10:18<2:40:16,  1.01it/s][NeMo W 2026-06-19 07:20:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
  8%|▊         | 814/10519 [10:19<2:48:40,  1.04s/it][NeMo W 2026-06-19 07:20:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
  8%|▊         | 815/10519 [10:21<2:59:27,  1.11s/it][NeMo W 2026-06-19 07:20:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.27it/s]
  8%|▊         | 816/10519 [10:22<3:02:11,  1.13s/it][NeMo W 2026-06-19 07:20:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
  8%|▊         | 817/10519 [10:23<3:01:48,  1.12s/it][NeMo W 2026-06-19 07:20:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
  8%|▊         | 818/10519 [10:24<2:52:32,  1.07s/it][NeMo W 2026-06-19 07:20:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
  8%|▊         | 819/10519 [10:25<2:49:20,  1.05s/it][NeMo W 2026-06-19 07:20:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
  8%|▊         | 820/10519 [10:26<2:49:55,  1.05s/it][NeMo W 2026-06-19 07:20:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
  8%|▊         | 821/10519 [10:27<2:42:14,  1.00s/it][NeMo W 2026-06-19 07:20:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.37it/s]
  8%|▊         | 822/10519 [10:28<2:39:20,  1.01it/s][NeMo W 2026-06-19 07:20:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.22it/s]
  8%|▊         | 823/10519 [10:29<2:39:32,  1.01it/s][NeMo W 2026-06-19 07:20:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
  8%|▊         | 824/10519 [10:30<2:37:41,  1.02it/s][NeMo W 2026-06-19 07:20:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
  8%|▊         | 825/10519 [10:31<2:42:59,  1.01s/it][NeMo W 2026-06-19 07:20:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.65it/s]
  8%|▊         | 826/10519 [10:32<3:07:51,  1.16s/it][NeMo W 2026-06-19 07:20:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.33it/s]
  8%|▊         | 827/10519 [10:33<3:02:35,  1.13s/it][NeMo W 2026-06-19 07:20:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.94it/s]
  8%|▊         | 828/10519 [10:34<2:55:58,  1.09s/it][NeMo W 2026-06-19 07:20:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.40it/s]
  8%|▊         | 829/10519 [10:35<2:52:17,  1.07s/it][NeMo W 2026-06-19 07:20:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.50it/s]
  8%|▊         | 830/10519 [10:36<2:44:30,  1.02s/it][NeMo W 2026-06-19 07:20:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 850 samples

[NeMo W 2026-06-19 07:20:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.24it/s]
  8%|▊         | 851/10519 [10:57<2:52:55,  1.07s/it][NeMo W 2026-06-19 07:20:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
  8%|▊         | 852/10519 [10:58<2:47:50,  1.04s/it][NeMo W 2026-06-19 07:20:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
  8%|▊         | 853/10519 [10:59<2:47:43,  1.04s/it][NeMo W 2026-06-19 07:20:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
  8%|▊         | 854/10519 [11:01<2:52:43,  1.07s/it][NeMo W 2026-06-19 07:20:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.66it/s]
  8%|▊         | 855/10519 [11:01<2:44:05,  1.02s/it][NeMo W 2026-06-19 07:20:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.80it/s]
  8%|▊         | 856/10519 [11:02<2:43:23,  1.01s/it][NeMo W 2026-06-19 07:20:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
  8%|▊         | 857/10519 [11:03<2:41:35,  1.00s/it][NeMo W 2026-06-19 07:20:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
  8%|▊         | 858/10519 [11:04<2:35:26,  1.04it/s][NeMo W 2026-06-19 07:20:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.94it/s]
  8%|▊         | 859/10519 [11:05<2:34:51,  1.04it/s][NeMo W 2026-06-19 07:20:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.34it/s]
  8%|▊         | 860/10519 [11:06<2:33:12,  1.05it/s][NeMo W 2026-06-19 07:20:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
  8%|▊         | 861/10519 [11:07<2:34:57,  1.04it/s][NeMo W 2026-06-19 07:20:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
  8%|▊         | 862/10519 [11:08<2:32:32,  1.06it/s][NeMo W 2026-06-19 07:20:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.29it/s]
  8%|▊         | 863/10519 [11:09<2:32:55,  1.05it/s][NeMo W 2026-06-19 07:20:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
  8%|▊         | 864/10519 [11:10<2:32:14,  1.06it/s][NeMo W 2026-06-19 07:20:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
  8%|▊         | 865/10519 [11:11<2:25:21,  1.11it/s][NeMo W 2026-06-19 07:20:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.62it/s]
  8%|▊         | 866/10519 [11:12<2:29:14,  1.08it/s][NeMo W 2026-06-19 07:20:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
  8%|▊         | 867/10519 [11:13<2:29:41,  1.07it/s][NeMo W 2026-06-19 07:20:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.28it/s]
  8%|▊         | 868/10519 [11:14<2:30:09,  1.07it/s][NeMo W 2026-06-19 07:20:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.70it/s]
  8%|▊         | 869/10519 [11:15<2:36:51,  1.03it/s][NeMo W 2026-06-19 07:20:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.77it/s]
  8%|▊         | 870/10519 [11:16<2:34:33,  1.04it/s][NeMo W 2026-06-19 07:20:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
  8%|▊         | 871/10519 [11:17<2:40:40,  1.00it/s][NeMo W 2026-06-19 07:20:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.81it/s]
  8%|▊         | 872/10519 [11:18<2:35:42,  1.03it/s][NeMo W 2026-06-19 07:20:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:20:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.88it/s]
  8%|▊         | 873/10519 [11:19<2:35:45,  1.03it/s][NeMo W 2026-06-19 07:21:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
  8%|▊         | 874/10519 [11:19<2:27:04,  1.09it/s][NeMo W 2026-06-19 07:21:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
  8%|▊         | 875/10519 [11:20<2:31:52,  1.06it/s][NeMo W 2026-06-19 07:21:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
  8%|▊         | 876/10519 [11:21<2:25:42,  1.10it/s][NeMo W 2026-06-19 07:21:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.01it/s]
  8%|▊         | 877/10519 [11:22<2:15:43,  1.18it/s][NeMo W 2026-06-19 07:21:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
  8%|▊         | 878/10519 [11:23<2:20:37,  1.14it/s][NeMo W 2026-06-19 07:21:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.51it/s]
  8%|▊         | 879/10519 [11:24<2:23:02,  1.12it/s][NeMo W 2026-06-19 07:21:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.78it/s]
  8%|▊         | 880/10519 [11:25<2:33:12,  1.05it/s][NeMo W 2026-06-19 07:21:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 900 samples

[NeMo W 2026-06-19 07:21:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
  9%|▊         | 901/10519 [11:45<2:41:15,  1.01s/it][NeMo W 2026-06-19 07:21:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
  9%|▊         | 902/10519 [11:46<2:37:06,  1.02it/s][NeMo W 2026-06-19 07:21:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.08it/s]
  9%|▊         | 903/10519 [11:47<2:38:48,  1.01it/s][NeMo W 2026-06-19 07:21:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.89it/s]
  9%|▊         | 904/10519 [11:48<2:37:19,  1.02it/s][NeMo W 2026-06-19 07:21:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
  9%|▊         | 905/10519 [11:49<2:36:28,  1.02it/s][NeMo W 2026-06-19 07:21:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
  9%|▊         | 906/10519 [11:50<2:43:17,  1.02s/it][NeMo W 2026-06-19 07:21:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.72it/s]
  9%|▊         | 907/10519 [11:51<2:40:25,  1.00s/it][NeMo W 2026-06-19 07:21:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.82it/s]
  9%|▊         | 908/10519 [11:52<2:37:52,  1.01it/s][NeMo W 2026-06-19 07:21:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.36it/s]
  9%|▊         | 909/10519 [11:53<2:37:19,  1.02it/s][NeMo W 2026-06-19 07:21:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
  9%|▊         | 910/10519 [11:54<2:37:03,  1.02it/s][NeMo W 2026-06-19 07:21:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.52it/s]
  9%|▊         | 911/10519 [11:54<2:24:37,  1.11it/s][NeMo W 2026-06-19 07:21:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.09it/s]
  9%|▊         | 912/10519 [11:55<2:15:31,  1.18it/s][NeMo W 2026-06-19 07:21:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
  9%|▊         | 913/10519 [11:56<2:28:25,  1.08it/s][NeMo W 2026-06-19 07:21:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
  9%|▊         | 914/10519 [11:57<2:33:25,  1.04it/s][NeMo W 2026-06-19 07:21:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
  9%|▊         | 915/10519 [11:58<2:37:00,  1.02it/s][NeMo W 2026-06-19 07:21:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
  9%|▊         | 916/10519 [11:59<2:26:04,  1.10it/s][NeMo W 2026-06-19 07:21:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.67it/s]
  9%|▊         | 917/10519 [12:00<2:29:26,  1.07it/s][NeMo W 2026-06-19 07:21:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.88it/s]
  9%|▊         | 918/10519 [12:01<2:30:24,  1.06it/s][NeMo W 2026-06-19 07:21:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.72it/s]
  9%|▊         | 919/10519 [12:02<2:29:40,  1.07it/s][NeMo W 2026-06-19 07:21:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
  9%|▊         | 920/10519 [12:03<2:30:36,  1.06it/s][NeMo W 2026-06-19 07:21:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.18it/s]
  9%|▉         | 921/10519 [12:04<2:27:27,  1.08it/s][NeMo W 2026-06-19 07:21:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.14it/s]
  9%|▉         | 922/10519 [12:05<2:27:17,  1.09it/s][NeMo W 2026-06-19 07:21:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
  9%|▉         | 923/10519 [12:06<2:31:59,  1.05it/s][NeMo W 2026-06-19 07:21:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.25it/s]
  9%|▉         | 924/10519 [12:07<2:33:12,  1.04it/s][NeMo W 2026-06-19 07:21:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
  9%|▉         | 925/10519 [12:08<2:28:17,  1.08it/s][NeMo W 2026-06-19 07:21:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
  9%|▉         | 926/10519 [12:08<2:30:24,  1.06it/s][NeMo W 2026-06-19 07:21:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
  9%|▉         | 927/10519 [12:09<2:33:00,  1.04it/s][NeMo W 2026-06-19 07:21:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.19it/s]
  9%|▉         | 928/10519 [12:10<2:29:21,  1.07it/s][NeMo W 2026-06-19 07:21:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
  9%|▉         | 929/10519 [12:11<2:21:33,  1.13it/s][NeMo W 2026-06-19 07:21:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:21:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
  9%|▉         | 930/10519 [12:12<2:23:58,  1.11it/s][NeMo W 2026-06-19 07:21:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 950 samples

[NeMo W 2026-06-19 07:22:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.15it/s]
  9%|▉         | 951/10519 [12:32<2:34:06,  1.03it/s][NeMo W 2026-06-19 07:22:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.36it/s]
  9%|▉         | 952/10519 [12:33<2:38:11,  1.01it/s][NeMo W 2026-06-19 07:22:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
  9%|▉         | 953/10519 [12:34<2:38:09,  1.01it/s][NeMo W 2026-06-19 07:22:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
  9%|▉         | 954/10519 [12:35<2:37:46,  1.01it/s][NeMo W 2026-06-19 07:22:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.48it/s]
  9%|▉         | 955/10519 [12:36<2:38:46,  1.00it/s][NeMo W 2026-06-19 07:22:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.64it/s]
  9%|▉         | 956/10519 [12:37<2:41:00,  1.01s/it][NeMo W 2026-06-19 07:22:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
  9%|▉         | 957/10519 [12:38<2:38:41,  1.00it/s][NeMo W 2026-06-19 07:22:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.29it/s]
  9%|▉         | 958/10519 [12:39<2:53:48,  1.09s/it][NeMo W 2026-06-19 07:22:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
  9%|▉         | 959/10519 [12:40<2:46:44,  1.05s/it][NeMo W 2026-06-19 07:22:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
  9%|▉         | 960/10519 [12:41<2:43:50,  1.03s/it][NeMo W 2026-06-19 07:22:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
  9%|▉         | 961/10519 [12:42<2:41:34,  1.01s/it][NeMo W 2026-06-19 07:22:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
  9%|▉         | 962/10519 [12:43<2:46:30,  1.05s/it][NeMo W 2026-06-19 07:22:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
  9%|▉         | 963/10519 [12:45<2:44:54,  1.04s/it][NeMo W 2026-06-19 07:22:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
  9%|▉         | 964/10519 [12:46<2:43:27,  1.03s/it][NeMo W 2026-06-19 07:22:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
  9%|▉         | 965/10519 [12:46<2:31:45,  1.05it/s][NeMo W 2026-06-19 07:22:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.97it/s]
  9%|▉         | 966/10519 [12:47<2:22:46,  1.12it/s][NeMo W 2026-06-19 07:22:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
  9%|▉         | 967/10519 [12:48<2:23:50,  1.11it/s][NeMo W 2026-06-19 07:22:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
  9%|▉         | 968/10519 [12:49<2:30:26,  1.06it/s][NeMo W 2026-06-19 07:22:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
  9%|▉         | 969/10519 [12:50<2:31:58,  1.05it/s][NeMo W 2026-06-19 07:22:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
  9%|▉         | 970/10519 [12:51<2:33:09,  1.04it/s][NeMo W 2026-06-19 07:22:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
  9%|▉         | 971/10519 [12:52<2:32:48,  1.04it/s][NeMo W 2026-06-19 07:22:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.90it/s]
  9%|▉         | 972/10519 [12:53<2:33:03,  1.04it/s][NeMo W 2026-06-19 07:22:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
  9%|▉         | 973/10519 [12:54<2:34:25,  1.03it/s][NeMo W 2026-06-19 07:22:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
  9%|▉         | 974/10519 [12:55<2:35:49,  1.02it/s][NeMo W 2026-06-19 07:22:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
  9%|▉         | 975/10519 [12:56<2:36:25,  1.02it/s][NeMo W 2026-06-19 07:22:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.60it/s]
  9%|▉         | 976/10519 [12:57<2:52:42,  1.09s/it][NeMo W 2026-06-19 07:22:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
  9%|▉         | 977/10519 [12:58<2:46:50,  1.05s/it][NeMo W 2026-06-19 07:22:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
  9%|▉         | 978/10519 [12:59<2:45:35,  1.04s/it][NeMo W 2026-06-19 07:22:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
  9%|▉         | 979/10519 [13:00<2:46:25,  1.05s/it][NeMo W 2026-06-19 07:22:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:22:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.59it/s]
  9%|▉         | 980/10519 [13:01<2:40:18,  1.01s/it][NeMo W 2026-06-19 07:22:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1000 samples

[NeMo W 2026-06-19 07:23:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.97it/s]
 10%|▉         | 1001/10519 [13:21<2:36:14,  1.02it/s][NeMo W 2026-06-19 07:23:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 10%|▉         | 1002/10519 [13:22<2:36:37,  1.01it/s][NeMo W 2026-06-19 07:23:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 10%|▉         | 1003/10519 [13:23<2:37:48,  1.01it/s][NeMo W 2026-06-19 07:23:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 10%|▉         | 1004/10519 [13:24<2:30:09,  1.06it/s][NeMo W 2026-06-19 07:23:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 10%|▉         | 1005/10519 [13:25<2:35:57,  1.02it/s][NeMo W 2026-06-19 07:23:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 10%|▉         | 1006/10519 [13:26<2:41:42,  1.02s/it][NeMo W 2026-06-19 07:23:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
 10%|▉         | 1007/10519 [13:28<2:47:43,  1.06s/it][NeMo W 2026-06-19 07:23:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 10%|▉         | 1008/10519 [13:28<2:41:41,  1.02s/it][NeMo W 2026-06-19 07:23:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 10%|▉         | 1009/10519 [13:29<2:39:16,  1.00s/it][NeMo W 2026-06-19 07:23:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 10%|▉         | 1010/10519 [13:30<2:37:04,  1.01it/s][NeMo W 2026-06-19 07:23:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.32it/s]
 10%|▉         | 1011/10519 [13:31<2:39:42,  1.01s/it][NeMo W 2026-06-19 07:23:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 10%|▉         | 1012/10519 [13:32<2:38:59,  1.00s/it][NeMo W 2026-06-19 07:23:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.74it/s]
 10%|▉         | 1013/10519 [13:34<2:42:23,  1.02s/it][NeMo W 2026-06-19 07:23:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 10%|▉         | 1014/10519 [13:34<2:39:27,  1.01s/it][NeMo W 2026-06-19 07:23:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 10%|▉         | 1015/10519 [13:35<2:35:28,  1.02it/s][NeMo W 2026-06-19 07:23:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 10%|▉         | 1016/10519 [13:36<2:37:02,  1.01it/s][NeMo W 2026-06-19 07:23:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 10%|▉         | 1017/10519 [13:37<2:34:12,  1.03it/s][NeMo W 2026-06-19 07:23:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 10%|▉         | 1018/10519 [13:38<2:37:02,  1.01it/s][NeMo W 2026-06-19 07:23:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 10%|▉         | 1019/10519 [13:39<2:34:29,  1.02it/s][NeMo W 2026-06-19 07:23:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.74it/s]
 10%|▉         | 1020/10519 [13:40<2:34:08,  1.03it/s][NeMo W 2026-06-19 07:23:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.97it/s]
 10%|▉         | 1021/10519 [13:41<2:32:58,  1.03it/s][NeMo W 2026-06-19 07:23:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.73it/s]
 10%|▉         | 1022/10519 [13:42<2:28:31,  1.07it/s][NeMo W 2026-06-19 07:23:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.02it/s]
 10%|▉         | 1023/10519 [13:43<2:27:57,  1.07it/s][NeMo W 2026-06-19 07:23:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.20it/s]
 10%|▉         | 1024/10519 [13:44<2:30:06,  1.05it/s][NeMo W 2026-06-19 07:23:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.53it/s]
 10%|▉         | 1025/10519 [13:45<2:29:14,  1.06it/s][NeMo W 2026-06-19 07:23:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 10%|▉         | 1026/10519 [13:46<2:39:37,  1.01s/it][NeMo W 2026-06-19 07:23:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.03it/s]
 10%|▉         | 1027/10519 [13:47<2:26:41,  1.08it/s][NeMo W 2026-06-19 07:23:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 17.26it/s]
 10%|▉         | 1028/10519 [13:48<2:26:41,  1.08it/s][NeMo W 2026-06-19 07:23:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 10%|▉         | 1029/10519 [13:49<2:29:24,  1.06it/s][NeMo W 2026-06-19 07:23:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 10%|▉         | 1030/10519 [13:50<2:28:35,  1.06it/s][NeMo W 2026-06-19 07:23:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1050 samples

[NeMo W 2026-06-19 07:23:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]
 10%|▉         | 1051/10519 [14:11<2:40:06,  1.01s/it][NeMo W 2026-06-19 07:23:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.30it/s]
 10%|█         | 1052/10519 [14:11<2:26:05,  1.08it/s][NeMo W 2026-06-19 07:23:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
 10%|█         | 1053/10519 [14:12<2:26:27,  1.08it/s][NeMo W 2026-06-19 07:23:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 10%|█         | 1054/10519 [14:13<2:29:55,  1.05it/s][NeMo W 2026-06-19 07:23:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 10%|█         | 1055/10519 [14:14<2:40:14,  1.02s/it][NeMo W 2026-06-19 07:23:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 10%|█         | 1056/10519 [14:15<2:27:00,  1.07it/s][NeMo W 2026-06-19 07:23:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.68it/s]
 10%|█         | 1057/10519 [14:16<2:15:20,  1.17it/s][NeMo W 2026-06-19 07:23:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.95it/s]
 10%|█         | 1058/10519 [14:17<2:21:38,  1.11it/s][NeMo W 2026-06-19 07:23:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 10%|█         | 1059/10519 [14:18<2:22:42,  1.10it/s][NeMo W 2026-06-19 07:23:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:23:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 10%|█         | 1060/10519 [14:19<2:23:41,  1.10it/s][NeMo W 2026-06-19 07:24:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 10%|█         | 1061/10519 [14:20<2:24:25,  1.09it/s][NeMo W 2026-06-19 07:24:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.51it/s]
 10%|█         | 1062/10519 [14:20<2:24:15,  1.09it/s][NeMo W 2026-06-19 07:24:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.57it/s]
 10%|█         | 1063/10519 [14:22<2:36:54,  1.00it/s][NeMo W 2026-06-19 07:24:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
 10%|█         | 1064/10519 [14:22<2:28:58,  1.06it/s][NeMo W 2026-06-19 07:24:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 10%|█         | 1065/10519 [14:23<2:28:32,  1.06it/s][NeMo W 2026-06-19 07:24:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 10%|█         | 1066/10519 [14:24<2:30:17,  1.05it/s][NeMo W 2026-06-19 07:24:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 10%|█         | 1067/10519 [14:25<2:28:43,  1.06it/s][NeMo W 2026-06-19 07:24:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 10%|█         | 1068/10519 [14:26<2:23:49,  1.10it/s][NeMo W 2026-06-19 07:24:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.89it/s]
 10%|█         | 1069/10519 [14:27<2:26:51,  1.07it/s][NeMo W 2026-06-19 07:24:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 10%|█         | 1070/10519 [14:28<2:29:50,  1.05it/s][NeMo W 2026-06-19 07:24:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 10%|█         | 1071/10519 [14:29<2:35:56,  1.01it/s][NeMo W 2026-06-19 07:24:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 10%|█         | 1072/10519 [14:30<2:33:08,  1.03it/s][NeMo W 2026-06-19 07:24:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 10%|█         | 1073/10519 [14:31<2:34:06,  1.02it/s][NeMo W 2026-06-19 07:24:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 10%|█         | 1074/10519 [14:32<2:39:32,  1.01s/it][NeMo W 2026-06-19 07:24:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 10%|█         | 1075/10519 [14:33<2:28:07,  1.06it/s][NeMo W 2026-06-19 07:24:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.02it/s]
 10%|█         | 1076/10519 [14:34<2:37:14,  1.00it/s][NeMo W 2026-06-19 07:24:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 10%|█         | 1077/10519 [14:35<2:29:11,  1.05it/s][NeMo W 2026-06-19 07:24:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.59it/s]
 10%|█         | 1078/10519 [14:36<2:20:28,  1.12it/s][NeMo W 2026-06-19 07:24:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 10%|█         | 1079/10519 [14:37<2:14:37,  1.17it/s][NeMo W 2026-06-19 07:24:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 10%|█         | 1080/10519 [14:38<2:29:41,  1.05it/s][NeMo W 2026-06-19 07:24:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1100 samples

[NeMo W 2026-06-19 07:24:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
 10%|█         | 1101/10519 [14:57<2:37:33,  1.00s/it][NeMo W 2026-06-19 07:24:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 10%|█         | 1102/10519 [14:58<2:33:56,  1.02it/s][NeMo W 2026-06-19 07:24:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 10%|█         | 1103/10519 [14:59<2:39:28,  1.02s/it][NeMo W 2026-06-19 07:24:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 10%|█         | 1104/10519 [15:00<2:35:45,  1.01it/s][NeMo W 2026-06-19 07:24:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 11%|█         | 1105/10519 [15:01<2:32:14,  1.03it/s][NeMo W 2026-06-19 07:24:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 11%|█         | 1106/10519 [15:02<2:23:22,  1.09it/s][NeMo W 2026-06-19 07:24:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 11%|█         | 1107/10519 [15:03<2:29:43,  1.05it/s][NeMo W 2026-06-19 07:24:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.17it/s]
 11%|█         | 1108/10519 [15:04<2:32:07,  1.03it/s][NeMo W 2026-06-19 07:24:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.00it/s]
 11%|█         | 1109/10519 [15:05<2:31:42,  1.03it/s][NeMo W 2026-06-19 07:24:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.69it/s]
 11%|█         | 1110/10519 [15:06<2:30:42,  1.04it/s][NeMo W 2026-06-19 07:24:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 11%|█         | 1111/10519 [15:07<2:20:36,  1.12it/s][NeMo W 2026-06-19 07:24:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 11%|█         | 1112/10519 [15:07<2:19:09,  1.13it/s][NeMo W 2026-06-19 07:24:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 11%|█         | 1113/10519 [15:08<2:17:27,  1.14it/s][NeMo W 2026-06-19 07:24:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.12it/s]
 11%|█         | 1114/10519 [15:09<2:17:55,  1.14it/s][NeMo W 2026-06-19 07:24:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.27it/s]
 11%|█         | 1115/10519 [15:10<2:21:13,  1.11it/s][NeMo W 2026-06-19 07:24:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 11%|█         | 1116/10519 [15:12<2:51:56,  1.10s/it][NeMo W 2026-06-19 07:24:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 11%|█         | 1117/10519 [15:13<2:45:02,  1.05s/it][NeMo W 2026-06-19 07:24:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.22it/s]
 11%|█         | 1118/10519 [15:14<2:38:51,  1.01s/it][NeMo W 2026-06-19 07:24:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 11%|█         | 1119/10519 [15:15<2:37:31,  1.01s/it][NeMo W 2026-06-19 07:24:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 11%|█         | 1120/10519 [15:16<2:36:49,  1.00s/it][NeMo W 2026-06-19 07:24:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 11%|█         | 1121/10519 [15:16<2:35:12,  1.01it/s][NeMo W 2026-06-19 07:24:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 11%|█         | 1122/10519 [15:17<2:35:15,  1.01it/s][NeMo W 2026-06-19 07:24:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:24:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 11%|█         | 1123/10519 [15:19<2:45:41,  1.06s/it][NeMo W 2026-06-19 07:25:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 11%|█         | 1124/10519 [15:20<2:41:06,  1.03s/it][NeMo W 2026-06-19 07:25:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 11%|█         | 1125/10519 [15:21<2:44:37,  1.05s/it][NeMo W 2026-06-19 07:25:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 11%|█         | 1126/10519 [15:22<2:41:11,  1.03s/it][NeMo W 2026-06-19 07:25:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 11%|█         | 1127/10519 [15:23<2:30:17,  1.04it/s][NeMo W 2026-06-19 07:25:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 11%|█         | 1128/10519 [15:23<2:28:15,  1.06it/s][NeMo W 2026-06-19 07:25:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
 11%|█         | 1129/10519 [15:24<2:31:18,  1.03it/s][NeMo W 2026-06-19 07:25:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 11%|█         | 1130/10519 [15:25<2:33:07,  1.02it/s][NeMo W 2026-06-19 07:25:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1150 samples

[NeMo W 2026-06-19 07:25:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 11%|█         | 1151/10519 [15:46<2:42:36,  1.04s/it][NeMo W 2026-06-19 07:25:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 11%|█         | 1152/10519 [15:47<2:36:20,  1.00s/it][NeMo W 2026-06-19 07:25:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 11%|█         | 1153/10519 [15:48<2:26:59,  1.06it/s][NeMo W 2026-06-19 07:25:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 11%|█         | 1154/10519 [15:48<2:25:15,  1.07it/s][NeMo W 2026-06-19 07:25:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.56it/s]
 11%|█         | 1155/10519 [15:49<2:24:17,  1.08it/s][NeMo W 2026-06-19 07:25:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 11%|█         | 1156/10519 [15:50<2:20:04,  1.11it/s][NeMo W 2026-06-19 07:25:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.77it/s]
 11%|█         | 1157/10519 [15:51<2:21:42,  1.10it/s][NeMo W 2026-06-19 07:25:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 11%|█         | 1158/10519 [15:52<2:25:43,  1.07it/s][NeMo W 2026-06-19 07:25:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 11%|█         | 1159/10519 [15:53<2:39:15,  1.02s/it][NeMo W 2026-06-19 07:25:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 11%|█         | 1160/10519 [15:54<2:41:51,  1.04s/it][NeMo W 2026-06-19 07:25:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 11%|█         | 1161/10519 [15:56<3:03:12,  1.17s/it][NeMo W 2026-06-19 07:25:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 11%|█         | 1162/10519 [15:57<2:48:27,  1.08s/it][NeMo W 2026-06-19 07:25:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 11%|█         | 1163/10519 [15:58<2:43:22,  1.05s/it][NeMo W 2026-06-19 07:25:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 11%|█         | 1164/10519 [15:59<2:39:43,  1.02s/it][NeMo W 2026-06-19 07:25:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 11%|█         | 1165/10519 [15:59<2:27:32,  1.06it/s][NeMo W 2026-06-19 07:25:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 11%|█         | 1166/10519 [16:00<2:25:29,  1.07it/s][NeMo W 2026-06-19 07:25:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 11%|█         | 1167/10519 [16:02<2:34:29,  1.01it/s][NeMo W 2026-06-19 07:25:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 11%|█         | 1168/10519 [16:02<2:25:08,  1.07it/s][NeMo W 2026-06-19 07:25:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 11%|█         | 1169/10519 [16:03<2:26:07,  1.07it/s][NeMo W 2026-06-19 07:25:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 11%|█         | 1170/10519 [16:04<2:16:22,  1.14it/s][NeMo W 2026-06-19 07:25:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 11%|█         | 1171/10519 [16:05<2:20:41,  1.11it/s][NeMo W 2026-06-19 07:25:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.39it/s]
 11%|█         | 1172/10519 [16:06<2:28:04,  1.05it/s][NeMo W 2026-06-19 07:25:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.03it/s]
 11%|█         | 1173/10519 [16:07<2:21:08,  1.10it/s][NeMo W 2026-06-19 07:25:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 11%|█         | 1174/10519 [16:08<2:25:41,  1.07it/s][NeMo W 2026-06-19 07:25:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 11%|█         | 1175/10519 [16:09<2:26:39,  1.06it/s][NeMo W 2026-06-19 07:25:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 11%|█         | 1176/10519 [16:10<2:28:58,  1.05it/s][NeMo W 2026-06-19 07:25:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 11%|█         | 1177/10519 [16:11<2:28:41,  1.05it/s][NeMo W 2026-06-19 07:25:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 11%|█         | 1178/10519 [16:12<2:29:08,  1.04it/s][NeMo W 2026-06-19 07:25:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.86it/s]
 11%|█         | 1179/10519 [16:13<2:27:26,  1.06it/s][NeMo W 2026-06-19 07:25:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:25:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]

Checkpoint saved: 1200 samples

[NeMo W 2026-06-19 07:26:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 11%|█▏        | 1201/10519 [16:33<2:30:44,  1.03it/s][NeMo W 2026-06-19 07:26:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 11%|█▏        | 1202/10519 [16:34<2:31:49,  1.02it/s][NeMo W 2026-06-19 07:26:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
 11%|█▏        | 1203/10519 [16:35<2:27:02,  1.06it/s][NeMo W 2026-06-19 07:26:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 11%|█▏        | 1204/10519 [16:36<2:25:39,  1.07it/s][NeMo W 2026-06-19 07:26:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 11%|█▏        | 1205/10519 [16:37<2:19:37,  1.11it/s][NeMo W 2026-06-19 07:26:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 11%|█▏        | 1206/10519 [16:38<2:22:55,  1.09it/s][NeMo W 2026-06-19 07:26:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 11%|█▏        | 1207/10519 [16:39<2:26:54,  1.06it/s][NeMo W 2026-06-19 07:26:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 11%|█▏        | 1208/10519 [16:40<2:26:42,  1.06it/s][NeMo W 2026-06-19 07:26:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 11%|█▏        | 1209/10519 [16:41<2:38:27,  1.02s/it][NeMo W 2026-06-19 07:26:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 12%|█▏        | 1210/10519 [16:42<2:34:16,  1.01it/s][NeMo W 2026-06-19 07:26:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 12%|█▏        | 1211/10519 [16:43<2:29:44,  1.04it/s][NeMo W 2026-06-19 07:26:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 12%|█▏        | 1212/10519 [16:44<2:29:06,  1.04it/s][NeMo W 2026-06-19 07:26:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 12%|█▏        | 1213/10519 [16:45<2:30:08,  1.03it/s][NeMo W 2026-06-19 07:26:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 12%|█▏        | 1214/10519 [16:46<2:29:54,  1.03it/s][NeMo W 2026-06-19 07:26:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
 12%|█▏        | 1215/10519 [16:47<2:29:20,  1.04it/s][NeMo W 2026-06-19 07:26:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 12%|█▏        | 1216/10519 [16:47<2:20:15,  1.11it/s][NeMo W 2026-06-19 07:26:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 12%|█▏        | 1217/10519 [16:48<2:14:21,  1.15it/s][NeMo W 2026-06-19 07:26:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 12%|█▏        | 1218/10519 [16:49<2:08:20,  1.21it/s][NeMo W 2026-06-19 07:26:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.68it/s]
 12%|█▏        | 1219/10519 [16:50<2:02:37,  1.26it/s][NeMo W 2026-06-19 07:26:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 12%|█▏        | 1220/10519 [16:51<2:09:53,  1.19it/s][NeMo W 2026-06-19 07:26:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 12%|█▏        | 1221/10519 [16:51<2:14:18,  1.15it/s][NeMo W 2026-06-19 07:26:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.81it/s]
 12%|█▏        | 1222/10519 [16:52<2:17:27,  1.13it/s][NeMo W 2026-06-19 07:26:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 12%|█▏        | 1223/10519 [16:53<2:24:24,  1.07it/s][NeMo W 2026-06-19 07:26:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
 12%|█▏        | 1224/10519 [16:54<2:27:11,  1.05it/s][NeMo W 2026-06-19 07:26:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.84it/s]
 12%|█▏        | 1225/10519 [16:55<2:19:22,  1.11it/s][NeMo W 2026-06-19 07:26:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 12%|█▏        | 1226/10519 [16:59<4:22:23,  1.69s/it][NeMo W 2026-06-19 07:26:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 12%|█▏        | 1227/10519 [17:00<3:48:59,  1.48s/it][NeMo W 2026-06-19 07:26:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 12%|█▏        | 1228/10519 [17:01<3:30:36,  1.36s/it][NeMo W 2026-06-19 07:26:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 12%|█▏        | 1229/10519 [17:02<3:12:14,  1.24s/it][NeMo W 2026-06-19 07:26:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:26:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 12%|█▏        | 1230/10519 [17:03<3:00:22,  1.17s/it][NeMo W 2026-06-19 07:26:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1250 samples

[NeMo W 2026-06-19 07:27:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 12%|█▏        | 1251/10519 [17:24<2:33:36,  1.01it/s][NeMo W 2026-06-19 07:27:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 12%|█▏        | 1252/10519 [17:25<2:31:30,  1.02it/s][NeMo W 2026-06-19 07:27:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.64it/s]
 12%|█▏        | 1253/10519 [17:26<2:29:37,  1.03it/s][NeMo W 2026-06-19 07:27:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 12%|█▏        | 1254/10519 [17:27<2:29:30,  1.03it/s][NeMo W 2026-06-19 07:27:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 12%|█▏        | 1255/10519 [17:28<2:22:15,  1.09it/s][NeMo W 2026-06-19 07:27:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 12%|█▏        | 1256/10519 [17:29<2:33:04,  1.01it/s][NeMo W 2026-06-19 07:27:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 12%|█▏        | 1257/10519 [17:30<2:30:50,  1.02it/s][NeMo W 2026-06-19 07:27:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 12%|█▏        | 1258/10519 [17:31<2:31:45,  1.02it/s][NeMo W 2026-06-19 07:27:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.21it/s]
 12%|█▏        | 1259/10519 [17:32<2:38:07,  1.02s/it][NeMo W 2026-06-19 07:27:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 12%|█▏        | 1260/10519 [17:33<2:41:22,  1.05s/it][NeMo W 2026-06-19 07:27:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 12%|█▏        | 1261/10519 [17:34<2:37:26,  1.02s/it][NeMo W 2026-06-19 07:27:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 12%|█▏        | 1262/10519 [17:35<2:45:30,  1.07s/it][NeMo W 2026-06-19 07:27:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.62it/s]
 12%|█▏        | 1263/10519 [17:36<2:38:19,  1.03s/it][NeMo W 2026-06-19 07:27:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 12%|█▏        | 1264/10519 [17:37<2:33:38,  1.00it/s][NeMo W 2026-06-19 07:27:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 12%|█▏        | 1265/10519 [17:38<2:32:20,  1.01it/s][NeMo W 2026-06-19 07:27:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 12%|█▏        | 1266/10519 [17:39<2:37:44,  1.02s/it][NeMo W 2026-06-19 07:27:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 12%|█▏        | 1267/10519 [17:40<2:39:27,  1.03s/it][NeMo W 2026-06-19 07:27:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.02it/s]
 12%|█▏        | 1268/10519 [17:41<2:35:03,  1.01s/it][NeMo W 2026-06-19 07:27:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 12%|█▏        | 1269/10519 [17:42<2:27:02,  1.05it/s][NeMo W 2026-06-19 07:27:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 12%|█▏        | 1270/10519 [17:43<2:27:53,  1.04it/s][NeMo W 2026-06-19 07:27:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 12%|█▏        | 1271/10519 [17:44<2:21:03,  1.09it/s][NeMo W 2026-06-19 07:27:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.96it/s]
 12%|█▏        | 1272/10519 [17:45<2:24:14,  1.07it/s][NeMo W 2026-06-19 07:27:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.10it/s]
 12%|█▏        | 1273/10519 [17:46<2:30:34,  1.02it/s][NeMo W 2026-06-19 07:27:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 12%|█▏        | 1274/10519 [17:47<2:36:43,  1.02s/it][NeMo W 2026-06-19 07:27:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 12%|█▏        | 1275/10519 [17:48<2:32:53,  1.01it/s][NeMo W 2026-06-19 07:27:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 12%|█▏        | 1276/10519 [17:49<2:25:58,  1.06it/s][NeMo W 2026-06-19 07:27:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 12%|█▏        | 1277/10519 [17:50<2:34:11,  1.00s/it][NeMo W 2026-06-19 07:27:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 12%|█▏        | 1278/10519 [17:51<2:31:24,  1.02it/s][NeMo W 2026-06-19 07:27:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
 12%|█▏        | 1279/10519 [17:52<2:45:11,  1.07s/it][NeMo W 2026-06-19 07:27:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 12%|█▏        | 1280/10519 [17:54<2:58:08,  1.16s/it][NeMo W 2026-06-19 07:27:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1300 samples

[NeMo W 2026-06-19 07:27:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 12%|█▏        | 1301/10519 [18:14<2:37:02,  1.02s/it][NeMo W 2026-06-19 07:27:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 12%|█▏        | 1302/10519 [18:15<2:32:39,  1.01it/s][NeMo W 2026-06-19 07:27:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 12%|█▏        | 1303/10519 [18:16<2:31:00,  1.02it/s][NeMo W 2026-06-19 07:27:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 12%|█▏        | 1304/10519 [18:17<2:30:03,  1.02it/s][NeMo W 2026-06-19 07:27:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:27:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 12%|█▏        | 1305/10519 [18:18<2:36:07,  1.02s/it][NeMo W 2026-06-19 07:28:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 12%|█▏        | 1306/10519 [18:19<2:31:46,  1.01it/s][NeMo W 2026-06-19 07:28:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 12%|█▏        | 1307/10519 [18:20<2:28:52,  1.03it/s][NeMo W 2026-06-19 07:28:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 12%|█▏        | 1308/10519 [18:21<2:27:05,  1.04it/s][NeMo W 2026-06-19 07:28:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 12%|█▏        | 1309/10519 [18:22<2:19:40,  1.10it/s][NeMo W 2026-06-19 07:28:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 12%|█▏        | 1310/10519 [18:22<2:12:27,  1.16it/s][NeMo W 2026-06-19 07:28:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 12%|█▏        | 1311/10519 [18:24<2:22:27,  1.08it/s][NeMo W 2026-06-19 07:28:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.85it/s]
 12%|█▏        | 1312/10519 [18:25<2:26:00,  1.05it/s][NeMo W 2026-06-19 07:28:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 12%|█▏        | 1313/10519 [18:26<2:51:19,  1.12s/it][NeMo W 2026-06-19 07:28:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 12%|█▏        | 1314/10519 [18:27<2:44:59,  1.08s/it][NeMo W 2026-06-19 07:28:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 13%|█▎        | 1315/10519 [18:28<2:34:14,  1.01s/it][NeMo W 2026-06-19 07:28:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 13%|█▎        | 1316/10519 [18:29<2:31:47,  1.01it/s][NeMo W 2026-06-19 07:28:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.04it/s]
 13%|█▎        | 1317/10519 [18:30<2:30:11,  1.02it/s][NeMo W 2026-06-19 07:28:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 13%|█▎        | 1318/10519 [18:31<2:31:27,  1.01it/s][NeMo W 2026-06-19 07:28:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 13%|█▎        | 1319/10519 [18:32<2:28:22,  1.03it/s][NeMo W 2026-06-19 07:28:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 13%|█▎        | 1320/10519 [18:33<2:24:34,  1.06it/s][NeMo W 2026-06-19 07:28:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.83it/s]
 13%|█▎        | 1321/10519 [18:33<2:22:57,  1.07it/s][NeMo W 2026-06-19 07:28:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 13%|█▎        | 1322/10519 [18:34<2:20:05,  1.09it/s][NeMo W 2026-06-19 07:28:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 13%|█▎        | 1323/10519 [18:35<2:22:16,  1.08it/s][NeMo W 2026-06-19 07:28:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 13%|█▎        | 1324/10519 [18:36<2:23:27,  1.07it/s][NeMo W 2026-06-19 07:28:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.96it/s]
 13%|█▎        | 1325/10519 [18:37<2:31:01,  1.01it/s][NeMo W 2026-06-19 07:28:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 13%|█▎        | 1326/10519 [18:38<2:34:32,  1.01s/it][NeMo W 2026-06-19 07:28:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 13%|█▎        | 1327/10519 [18:40<2:38:17,  1.03s/it][NeMo W 2026-06-19 07:28:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 13%|█▎        | 1328/10519 [18:41<2:37:30,  1.03s/it][NeMo W 2026-06-19 07:28:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 13%|█▎        | 1329/10519 [18:41<2:34:22,  1.01s/it][NeMo W 2026-06-19 07:28:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 13%|█▎        | 1330/10519 [18:42<2:33:19,  1.00s/it][NeMo W 2026-06-19 07:28:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1350 samples

[NeMo W 2026-06-19 07:28:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 13%|█▎        | 1351/10519 [19:04<2:33:43,  1.01s/it][NeMo W 2026-06-19 07:28:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 13%|█▎        | 1352/10519 [19:05<2:31:48,  1.01it/s][NeMo W 2026-06-19 07:28:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 13%|█▎        | 1353/10519 [19:06<2:29:13,  1.02it/s][NeMo W 2026-06-19 07:28:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 13%|█▎        | 1354/10519 [19:07<2:27:34,  1.04it/s][NeMo W 2026-06-19 07:28:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 13%|█▎        | 1355/10519 [19:08<2:18:30,  1.10it/s][NeMo W 2026-06-19 07:28:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 13%|█▎        | 1356/10519 [19:09<2:19:31,  1.09it/s][NeMo W 2026-06-19 07:28:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 13%|█▎        | 1357/10519 [19:09<2:15:42,  1.13it/s][NeMo W 2026-06-19 07:28:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 13%|█▎        | 1358/10519 [19:10<2:23:19,  1.07it/s][NeMo W 2026-06-19 07:28:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 13%|█▎        | 1359/10519 [19:11<2:23:12,  1.07it/s][NeMo W 2026-06-19 07:28:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 13%|█▎        | 1360/10519 [19:12<2:15:58,  1.12it/s][NeMo W 2026-06-19 07:28:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 13%|█▎        | 1361/10519 [19:13<2:11:19,  1.16it/s][NeMo W 2026-06-19 07:28:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 13%|█▎        | 1362/10519 [19:14<2:08:51,  1.18it/s][NeMo W 2026-06-19 07:28:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.91it/s]
 13%|█▎        | 1363/10519 [19:15<2:22:06,  1.07it/s][NeMo W 2026-06-19 07:28:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 13%|█▎        | 1364/10519 [19:16<2:21:41,  1.08it/s][NeMo W 2026-06-19 07:28:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 13%|█▎        | 1365/10519 [19:17<2:19:42,  1.09it/s][NeMo W 2026-06-19 07:28:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]
 13%|█▎        | 1366/10519 [19:18<2:21:14,  1.08it/s][NeMo W 2026-06-19 07:28:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:28:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 13%|█▎        | 1367/10519 [19:19<2:22:49,  1.07it/s][NeMo W 2026-06-19 07:29:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 13%|█▎        | 1368/10519 [19:20<2:24:25,  1.06it/s][NeMo W 2026-06-19 07:29:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.64it/s]
 13%|█▎        | 1369/10519 [19:21<2:32:45,  1.00s/it][NeMo W 2026-06-19 07:29:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 13%|█▎        | 1370/10519 [19:22<2:29:50,  1.02it/s][NeMo W 2026-06-19 07:29:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 13%|█▎        | 1371/10519 [19:23<2:27:52,  1.03it/s][NeMo W 2026-06-19 07:29:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 13%|█▎        | 1372/10519 [19:23<2:19:28,  1.09it/s][NeMo W 2026-06-19 07:29:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 13%|█▎        | 1373/10519 [19:24<2:12:13,  1.15it/s][NeMo W 2026-06-19 07:29:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.05it/s]
 13%|█▎        | 1374/10519 [19:25<2:05:12,  1.22it/s][NeMo W 2026-06-19 07:29:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 13%|█▎        | 1375/10519 [19:26<2:16:55,  1.11it/s][NeMo W 2026-06-19 07:29:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 13%|█▎        | 1376/10519 [19:27<2:19:53,  1.09it/s][NeMo W 2026-06-19 07:29:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 13%|█▎        | 1377/10519 [19:28<2:19:33,  1.09it/s][NeMo W 2026-06-19 07:29:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 13%|█▎        | 1378/10519 [19:29<2:21:30,  1.08it/s][NeMo W 2026-06-19 07:29:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 13%|█▎        | 1379/10519 [19:30<2:22:02,  1.07it/s][NeMo W 2026-06-19 07:29:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 13%|█▎        | 1380/10519 [19:31<2:22:43,  1.07it/s][NeMo W 2026-06-19 07:29:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1400 samples

[NeMo W 2026-06-19 07:29:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 13%|█▎        | 1401/10519 [19:51<2:31:44,  1.00it/s][NeMo W 2026-06-19 07:29:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 13%|█▎        | 1402/10519 [19:52<2:28:46,  1.02it/s][NeMo W 2026-06-19 07:29:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 13%|█▎        | 1403/10519 [19:53<2:27:00,  1.03it/s][NeMo W 2026-06-19 07:29:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 13%|█▎        | 1404/10519 [19:54<2:26:30,  1.04it/s][NeMo W 2026-06-19 07:29:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 13%|█▎        | 1405/10519 [19:55<2:26:12,  1.04it/s][NeMo W 2026-06-19 07:29:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 13%|█▎        | 1406/10519 [19:56<2:23:29,  1.06it/s][NeMo W 2026-06-19 07:29:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 13%|█▎        | 1407/10519 [19:57<2:23:43,  1.06it/s][NeMo W 2026-06-19 07:29:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.20it/s]
 13%|█▎        | 1408/10519 [19:57<2:14:39,  1.13it/s][NeMo W 2026-06-19 07:29:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 13%|█▎        | 1409/10519 [19:58<2:06:00,  1.20it/s][NeMo W 2026-06-19 07:29:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 13%|█▎        | 1410/10519 [19:59<2:01:18,  1.25it/s][NeMo W 2026-06-19 07:29:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 13%|█▎        | 1411/10519 [20:00<2:06:37,  1.20it/s][NeMo W 2026-06-19 07:29:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 13%|█▎        | 1412/10519 [20:00<2:04:46,  1.22it/s][NeMo W 2026-06-19 07:29:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 13%|█▎        | 1413/10519 [20:01<2:08:44,  1.18it/s][NeMo W 2026-06-19 07:29:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 13%|█▎        | 1414/10519 [20:02<2:14:01,  1.13it/s][NeMo W 2026-06-19 07:29:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 13%|█▎        | 1415/10519 [20:03<2:10:43,  1.16it/s][NeMo W 2026-06-19 07:29:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 13%|█▎        | 1416/10519 [20:04<2:19:08,  1.09it/s][NeMo W 2026-06-19 07:29:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 16.24it/s]
 13%|█▎        | 1417/10519 [20:08<4:43:14,  1.87s/it][NeMo W 2026-06-19 07:29:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 13%|█▎        | 1418/10519 [20:09<4:02:09,  1.60s/it][NeMo W 2026-06-19 07:29:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 13%|█▎        | 1419/10519 [20:10<3:31:54,  1.40s/it][NeMo W 2026-06-19 07:29:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 13%|█▎        | 1420/10519 [20:11<3:09:27,  1.25s/it][NeMo W 2026-06-19 07:29:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 14%|█▎        | 1421/10519 [20:12<2:57:27,  1.17s/it][NeMo W 2026-06-19 07:29:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 14%|█▎        | 1422/10519 [20:13<2:46:11,  1.10s/it][NeMo W 2026-06-19 07:29:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 14%|█▎        | 1423/10519 [20:14<2:38:09,  1.04s/it][NeMo W 2026-06-19 07:29:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 14%|█▎        | 1424/10519 [20:15<2:34:05,  1.02s/it][NeMo W 2026-06-19 07:29:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.02it/s]
 14%|█▎        | 1425/10519 [20:16<2:39:35,  1.05s/it][NeMo W 2026-06-19 07:29:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 14%|█▎        | 1426/10519 [20:17<2:38:55,  1.05s/it][NeMo W 2026-06-19 07:29:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:29:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 14%|█▎        | 1427/10519 [20:18<2:35:44,  1.03s/it][NeMo W 2026-06-19 07:30:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 14%|█▎        | 1428/10519 [20:19<2:32:39,  1.01s/it][NeMo W 2026-06-19 07:30:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 14%|█▎        | 1429/10519 [20:20<2:30:13,  1.01it/s][NeMo W 2026-06-19 07:30:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 14%|█▎        | 1430/10519 [20:21<2:32:03,  1.00s/it][NeMo W 2026-06-19 07:30:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1450 samples

[NeMo W 2026-06-19 07:30:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 14%|█▍        | 1451/10519 [20:41<2:42:21,  1.07s/it][NeMo W 2026-06-19 07:30:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 14%|█▍        | 1452/10519 [20:42<2:39:46,  1.06s/it][NeMo W 2026-06-19 07:30:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.32it/s]
 14%|█▍        | 1453/10519 [20:43<2:35:30,  1.03s/it][NeMo W 2026-06-19 07:30:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 14%|█▍        | 1454/10519 [20:44<2:37:54,  1.05s/it][NeMo W 2026-06-19 07:30:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 14%|█▍        | 1455/10519 [20:45<2:22:43,  1.06it/s][NeMo W 2026-06-19 07:30:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 14%|█▍        | 1456/10519 [20:46<2:25:25,  1.04it/s][NeMo W 2026-06-19 07:30:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.17it/s]
 14%|█▍        | 1457/10519 [20:47<2:15:06,  1.12it/s][NeMo W 2026-06-19 07:30:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.31it/s]
 14%|█▍        | 1458/10519 [20:48<2:19:10,  1.09it/s][NeMo W 2026-06-19 07:30:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 14%|█▍        | 1459/10519 [20:49<2:12:15,  1.14it/s][NeMo W 2026-06-19 07:30:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 14%|█▍        | 1460/10519 [20:50<2:14:53,  1.12it/s][NeMo W 2026-06-19 07:30:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 14%|█▍        | 1461/10519 [20:51<2:17:48,  1.10it/s][NeMo W 2026-06-19 07:30:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 14%|█▍        | 1462/10519 [20:52<2:23:40,  1.05it/s][NeMo W 2026-06-19 07:30:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 14%|█▍        | 1463/10519 [20:53<2:26:30,  1.03it/s][NeMo W 2026-06-19 07:30:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.88it/s]
 14%|█▍        | 1464/10519 [20:54<2:27:43,  1.02it/s][NeMo W 2026-06-19 07:30:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 14%|█▍        | 1465/10519 [20:55<2:26:07,  1.03it/s][NeMo W 2026-06-19 07:30:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 14%|█▍        | 1466/10519 [20:55<2:14:25,  1.12it/s][NeMo W 2026-06-19 07:30:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 14%|█▍        | 1467/10519 [20:56<2:26:43,  1.03it/s][NeMo W 2026-06-19 07:30:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 14%|█▍        | 1468/10519 [20:57<2:27:51,  1.02it/s][NeMo W 2026-06-19 07:30:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 14%|█▍        | 1469/10519 [20:58<2:26:09,  1.03it/s][NeMo W 2026-06-19 07:30:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 14%|█▍        | 1470/10519 [20:59<2:23:25,  1.05it/s][NeMo W 2026-06-19 07:30:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 14%|█▍        | 1471/10519 [21:00<2:23:18,  1.05it/s][NeMo W 2026-06-19 07:30:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 14%|█▍        | 1472/10519 [21:01<2:24:03,  1.05it/s][NeMo W 2026-06-19 07:30:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 14%|█▍        | 1473/10519 [21:02<2:23:34,  1.05it/s][NeMo W 2026-06-19 07:30:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 14%|█▍        | 1474/10519 [21:07<5:25:26,  2.16s/it][NeMo W 2026-06-19 07:30:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 14%|█▍        | 1475/10519 [21:08<4:31:56,  1.80s/it][NeMo W 2026-06-19 07:30:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.64it/s]
 14%|█▍        | 1476/10519 [21:09<3:52:05,  1.54s/it][NeMo W 2026-06-19 07:30:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 14%|█▍        | 1477/10519 [21:10<3:18:29,  1.32s/it][NeMo W 2026-06-19 07:30:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 14%|█▍        | 1478/10519 [21:11<2:53:28,  1.15s/it][NeMo W 2026-06-19 07:30:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 14%|█▍        | 1479/10519 [21:12<2:46:07,  1.10s/it][NeMo W 2026-06-19 07:30:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:30:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]

Checkpoint saved: 1500 samples

[NeMo W 2026-06-19 07:31:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.60it/s]
 14%|█▍        | 1501/10519 [21:33<2:36:30,  1.04s/it][NeMo W 2026-06-19 07:31:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 14%|█▍        | 1502/10519 [21:34<2:33:22,  1.02s/it][NeMo W 2026-06-19 07:31:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 14%|█▍        | 1503/10519 [21:35<2:28:24,  1.01it/s][NeMo W 2026-06-19 07:31:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 14%|█▍        | 1504/10519 [21:35<2:26:06,  1.03it/s][NeMo W 2026-06-19 07:31:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 14%|█▍        | 1505/10519 [21:36<2:27:11,  1.02it/s][NeMo W 2026-06-19 07:31:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 14%|█▍        | 1506/10519 [21:37<2:24:20,  1.04it/s][NeMo W 2026-06-19 07:31:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 14%|█▍        | 1507/10519 [21:39<3:12:39,  1.28s/it][NeMo W 2026-06-19 07:31:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 14%|█▍        | 1508/10519 [21:40<2:57:35,  1.18s/it][NeMo W 2026-06-19 07:31:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 14%|█▍        | 1509/10519 [21:41<2:47:21,  1.11s/it][NeMo W 2026-06-19 07:31:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 14%|█▍        | 1510/10519 [21:42<2:47:33,  1.12s/it][NeMo W 2026-06-19 07:31:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 14%|█▍        | 1511/10519 [21:43<2:34:21,  1.03s/it][NeMo W 2026-06-19 07:31:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 14%|█▍        | 1512/10519 [21:44<2:30:36,  1.00s/it][NeMo W 2026-06-19 07:31:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 14%|█▍        | 1513/10519 [21:45<2:21:42,  1.06it/s][NeMo W 2026-06-19 07:31:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 14%|█▍        | 1514/10519 [21:46<2:19:24,  1.08it/s][NeMo W 2026-06-19 07:31:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 14%|█▍        | 1515/10519 [21:47<2:13:40,  1.12it/s][NeMo W 2026-06-19 07:31:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 14%|█▍        | 1516/10519 [21:48<2:15:46,  1.11it/s][NeMo W 2026-06-19 07:31:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 14%|█▍        | 1517/10519 [21:49<2:30:39,  1.00s/it][NeMo W 2026-06-19 07:31:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 14%|█▍        | 1518/10519 [21:50<2:27:55,  1.01it/s][NeMo W 2026-06-19 07:31:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 14%|█▍        | 1519/10519 [21:51<2:25:18,  1.03it/s][NeMo W 2026-06-19 07:31:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 14%|█▍        | 1520/10519 [21:51<2:13:36,  1.12it/s][NeMo W 2026-06-19 07:31:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 14%|█▍        | 1521/10519 [21:52<2:17:54,  1.09it/s][NeMo W 2026-06-19 07:31:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 14%|█▍        | 1522/10519 [21:53<2:17:54,  1.09it/s][NeMo W 2026-06-19 07:31:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 14%|█▍        | 1523/10519 [21:54<2:23:51,  1.04it/s][NeMo W 2026-06-19 07:31:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 14%|█▍        | 1524/10519 [21:55<2:14:24,  1.12it/s][NeMo W 2026-06-19 07:31:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 14%|█▍        | 1525/10519 [21:56<2:06:56,  1.18it/s][NeMo W 2026-06-19 07:31:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 15%|█▍        | 1526/10519 [21:57<2:15:29,  1.11it/s][NeMo W 2026-06-19 07:31:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 15%|█▍        | 1527/10519 [21:58<2:19:21,  1.08it/s][NeMo W 2026-06-19 07:31:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 15%|█▍        | 1528/10519 [21:59<2:20:27,  1.07it/s][NeMo W 2026-06-19 07:31:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 15%|█▍        | 1529/10519 [22:00<2:12:26,  1.13it/s][NeMo W 2026-06-19 07:31:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:31:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 15%|█▍        | 1530/10519 [22:01<2:15:40,  1.10it/s][NeMo W 2026-06-19 07:31:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1550 samples

[NeMo W 2026-06-19 07:32:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 15%|█▍        | 1551/10519 [22:21<2:32:00,  1.02s/it][NeMo W 2026-06-19 07:32:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 15%|█▍        | 1552/10519 [22:22<2:30:52,  1.01s/it][NeMo W 2026-06-19 07:32:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 15%|█▍        | 1553/10519 [22:23<2:20:51,  1.06it/s][NeMo W 2026-06-19 07:32:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 15%|█▍        | 1554/10519 [22:24<2:18:49,  1.08it/s][NeMo W 2026-06-19 07:32:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 15%|█▍        | 1555/10519 [22:25<2:14:55,  1.11it/s][NeMo W 2026-06-19 07:32:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 15%|█▍        | 1556/10519 [22:26<2:16:15,  1.10it/s][NeMo W 2026-06-19 07:32:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 15%|█▍        | 1557/10519 [22:27<2:19:43,  1.07it/s][NeMo W 2026-06-19 07:32:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.30it/s]
 15%|█▍        | 1558/10519 [22:28<2:22:50,  1.05it/s][NeMo W 2026-06-19 07:32:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 15%|█▍        | 1559/10519 [22:29<2:26:24,  1.02it/s][NeMo W 2026-06-19 07:32:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 15%|█▍        | 1560/10519 [22:30<2:25:08,  1.03it/s][NeMo W 2026-06-19 07:32:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 15%|█▍        | 1561/10519 [22:31<2:23:45,  1.04it/s][NeMo W 2026-06-19 07:32:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.75it/s]
 15%|█▍        | 1562/10519 [22:32<2:24:58,  1.03it/s][NeMo W 2026-06-19 07:32:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.21it/s]
 15%|█▍        | 1563/10519 [22:33<2:26:55,  1.02it/s][NeMo W 2026-06-19 07:32:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 15%|█▍        | 1564/10519 [22:34<2:28:00,  1.01it/s][NeMo W 2026-06-19 07:32:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.54it/s]
 15%|█▍        | 1565/10519 [22:35<2:32:11,  1.02s/it][NeMo W 2026-06-19 07:32:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 15%|█▍        | 1566/10519 [22:36<2:30:26,  1.01s/it][NeMo W 2026-06-19 07:32:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 15%|█▍        | 1567/10519 [22:37<2:20:29,  1.06it/s][NeMo W 2026-06-19 07:32:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 15%|█▍        | 1568/10519 [22:38<2:20:13,  1.06it/s][NeMo W 2026-06-19 07:32:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 15%|█▍        | 1569/10519 [22:39<2:20:07,  1.06it/s][NeMo W 2026-06-19 07:32:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
 15%|█▍        | 1570/10519 [22:40<2:20:45,  1.06it/s][NeMo W 2026-06-19 07:32:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 15%|█▍        | 1571/10519 [22:41<2:25:16,  1.03it/s][NeMo W 2026-06-19 07:32:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 15%|█▍        | 1572/10519 [22:42<2:34:07,  1.03s/it][NeMo W 2026-06-19 07:32:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 15%|█▍        | 1573/10519 [22:43<2:31:06,  1.01s/it][NeMo W 2026-06-19 07:32:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 15%|█▍        | 1574/10519 [22:44<2:28:05,  1.01it/s][NeMo W 2026-06-19 07:32:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 15%|█▍        | 1575/10519 [22:45<2:27:58,  1.01it/s][NeMo W 2026-06-19 07:32:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 15%|█▍        | 1576/10519 [22:46<2:29:24,  1.00s/it][NeMo W 2026-06-19 07:32:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 15%|█▍        | 1577/10519 [22:46<2:21:09,  1.06it/s][NeMo W 2026-06-19 07:32:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 15%|█▌        | 1578/10519 [22:47<2:22:49,  1.04it/s][NeMo W 2026-06-19 07:32:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 15%|█▌        | 1579/10519 [22:48<2:23:45,  1.04it/s][NeMo W 2026-06-19 07:32:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.96it/s]

Checkpoint saved: 1600 samples

[NeMo W 2026-06-19 07:32:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 15%|█▌        | 1601/10519 [23:09<2:20:34,  1.06it/s][NeMo W 2026-06-19 07:32:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 15%|█▌        | 1602/10519 [23:10<2:11:09,  1.13it/s][NeMo W 2026-06-19 07:32:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 15%|█▌        | 1603/10519 [23:11<2:18:30,  1.07it/s][NeMo W 2026-06-19 07:32:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 15%|█▌        | 1604/10519 [23:12<2:18:36,  1.07it/s][NeMo W 2026-06-19 07:32:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 15%|█▌        | 1605/10519 [23:13<2:22:45,  1.04it/s][NeMo W 2026-06-19 07:32:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 15%|█▌        | 1606/10519 [23:14<2:20:54,  1.05it/s][NeMo W 2026-06-19 07:32:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 15%|█▌        | 1607/10519 [23:15<2:22:11,  1.04it/s][NeMo W 2026-06-19 07:32:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 15%|█▌        | 1608/10519 [23:16<2:28:46,  1.00s/it][NeMo W 2026-06-19 07:32:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 15%|█▌        | 1609/10519 [23:17<2:24:37,  1.03it/s][NeMo W 2026-06-19 07:32:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 15%|█▌        | 1610/10519 [23:18<2:15:23,  1.10it/s][NeMo W 2026-06-19 07:32:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:32:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 15%|█▌        | 1611/10519 [23:19<2:16:04,  1.09it/s][NeMo W 2026-06-19 07:33:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 15%|█▌        | 1612/10519 [23:20<2:28:00,  1.00it/s][NeMo W 2026-06-19 07:33:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 15%|█▌        | 1613/10519 [23:21<2:25:03,  1.02it/s][NeMo W 2026-06-19 07:33:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 15%|█▌        | 1614/10519 [23:22<2:26:50,  1.01it/s][NeMo W 2026-06-19 07:33:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 15%|█▌        | 1615/10519 [23:23<2:29:40,  1.01s/it][NeMo W 2026-06-19 07:33:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.30it/s]
 15%|█▌        | 1616/10519 [23:24<2:28:16,  1.00it/s][NeMo W 2026-06-19 07:33:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
 15%|█▌        | 1617/10519 [23:25<2:30:51,  1.02s/it][NeMo W 2026-06-19 07:33:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 15%|█▌        | 1618/10519 [23:26<2:28:18,  1.00it/s][NeMo W 2026-06-19 07:33:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 15%|█▌        | 1619/10519 [23:27<2:24:53,  1.02it/s][NeMo W 2026-06-19 07:33:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 15%|█▌        | 1620/10519 [23:28<2:24:58,  1.02it/s][NeMo W 2026-06-19 07:33:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 15%|█▌        | 1621/10519 [23:29<2:31:39,  1.02s/it][NeMo W 2026-06-19 07:33:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 15%|█▌        | 1622/10519 [23:30<2:30:33,  1.02s/it][NeMo W 2026-06-19 07:33:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 15%|█▌        | 1623/10519 [23:31<2:28:40,  1.00s/it][NeMo W 2026-06-19 07:33:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 15%|█▌        | 1624/10519 [23:33<3:12:05,  1.30s/it][NeMo W 2026-06-19 07:33:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 15%|█▌        | 1625/10519 [23:34<2:58:18,  1.20s/it][NeMo W 2026-06-19 07:33:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 15%|█▌        | 1626/10519 [23:35<2:39:52,  1.08s/it][NeMo W 2026-06-19 07:33:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.32it/s]
 15%|█▌        | 1627/10519 [23:36<2:39:49,  1.08s/it][NeMo W 2026-06-19 07:33:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 15%|█▌        | 1628/10519 [23:37<2:37:05,  1.06s/it][NeMo W 2026-06-19 07:33:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 15%|█▌        | 1629/10519 [23:38<2:33:34,  1.04s/it][NeMo W 2026-06-19 07:33:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]

Checkpoint saved: 1650 samples

[NeMo W 2026-06-19 07:33:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 16%|█▌        | 1651/10519 [23:58<2:17:05,  1.08it/s][NeMo W 2026-06-19 07:33:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 16%|█▌        | 1652/10519 [23:59<2:11:32,  1.12it/s][NeMo W 2026-06-19 07:33:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 16%|█▌        | 1653/10519 [24:00<2:14:50,  1.10it/s][NeMo W 2026-06-19 07:33:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.73it/s]
 16%|█▌        | 1654/10519 [24:01<2:19:01,  1.06it/s][NeMo W 2026-06-19 07:33:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.34it/s]
 16%|█▌        | 1655/10519 [24:02<2:24:03,  1.03it/s][NeMo W 2026-06-19 07:33:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 16%|█▌        | 1656/10519 [24:03<2:25:02,  1.02it/s][NeMo W 2026-06-19 07:33:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 16%|█▌        | 1657/10519 [24:04<2:23:27,  1.03it/s][NeMo W 2026-06-19 07:33:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 16%|█▌        | 1658/10519 [24:05<2:21:36,  1.04it/s][NeMo W 2026-06-19 07:33:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 16%|█▌        | 1659/10519 [24:05<2:18:32,  1.07it/s][NeMo W 2026-06-19 07:33:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 16%|█▌        | 1660/10519 [24:06<2:20:37,  1.05it/s][NeMo W 2026-06-19 07:33:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 16%|█▌        | 1661/10519 [24:08<2:31:54,  1.03s/it][NeMo W 2026-06-19 07:33:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 16%|█▌        | 1662/10519 [24:09<2:29:08,  1.01s/it][NeMo W 2026-06-19 07:33:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 16%|█▌        | 1663/10519 [24:10<2:26:10,  1.01it/s][NeMo W 2026-06-19 07:33:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 16%|█▌        | 1664/10519 [24:11<2:26:22,  1.01it/s][NeMo W 2026-06-19 07:33:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.11it/s]
 16%|█▌        | 1665/10519 [24:12<2:29:22,  1.01s/it][NeMo W 2026-06-19 07:33:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 16%|█▌        | 1666/10519 [24:13<2:31:25,  1.03s/it][NeMo W 2026-06-19 07:33:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 16%|█▌        | 1667/10519 [24:14<2:30:45,  1.02s/it][NeMo W 2026-06-19 07:33:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 16%|█▌        | 1668/10519 [24:15<2:28:02,  1.00s/it][NeMo W 2026-06-19 07:33:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 16%|█▌        | 1669/10519 [24:16<2:25:24,  1.01it/s][NeMo W 2026-06-19 07:33:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 16%|█▌        | 1670/10519 [24:17<2:23:20,  1.03it/s][NeMo W 2026-06-19 07:33:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 16%|█▌        | 1671/10519 [24:17<2:22:37,  1.03it/s][NeMo W 2026-06-19 07:33:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:33:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]
 16%|█▌        | 1672/10519 [24:19<2:25:31,  1.01it/s][NeMo W 2026-06-19 07:34:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 16%|█▌        | 1673/10519 [24:19<2:20:07,  1.05it/s][NeMo W 2026-06-19 07:34:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 16%|█▌        | 1674/10519 [24:20<2:21:04,  1.04it/s][NeMo W 2026-06-19 07:34:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 16%|█▌        | 1675/10519 [24:21<2:20:05,  1.05it/s][NeMo W 2026-06-19 07:34:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 16%|█▌        | 1676/10519 [24:22<2:09:56,  1.13it/s][NeMo W 2026-06-19 07:34:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 16%|█▌        | 1677/10519 [24:23<2:17:03,  1.08it/s][NeMo W 2026-06-19 07:34:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 16%|█▌        | 1678/10519 [24:24<2:18:49,  1.06it/s][NeMo W 2026-06-19 07:34:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 16%|█▌        | 1679/10519 [24:25<2:21:01,  1.04it/s][NeMo W 2026-06-19 07:34:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]

Checkpoint saved: 1700 samples

[NeMo W 2026-06-19 07:34:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 16%|█▌        | 1701/10519 [24:47<2:33:02,  1.04s/it][NeMo W 2026-06-19 07:34:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 16%|█▌        | 1702/10519 [24:48<2:30:14,  1.02s/it][NeMo W 2026-06-19 07:34:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 16%|█▌        | 1703/10519 [24:49<2:27:30,  1.00s/it][NeMo W 2026-06-19 07:34:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 16%|█▌        | 1704/10519 [24:50<2:25:55,  1.01it/s][NeMo W 2026-06-19 07:34:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 16%|█▌        | 1705/10519 [24:51<2:22:46,  1.03it/s][NeMo W 2026-06-19 07:34:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.28it/s]
 16%|█▌        | 1706/10519 [24:51<2:13:40,  1.10it/s][NeMo W 2026-06-19 07:34:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 16%|█▌        | 1707/10519 [24:52<2:15:17,  1.09it/s][NeMo W 2026-06-19 07:34:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 16%|█▌        | 1708/10519 [24:53<2:16:44,  1.07it/s][NeMo W 2026-06-19 07:34:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 16%|█▌        | 1709/10519 [24:54<2:19:55,  1.05it/s][NeMo W 2026-06-19 07:34:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 16%|█▋        | 1710/10519 [24:55<2:20:42,  1.04it/s][NeMo W 2026-06-19 07:34:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 16%|█▋        | 1711/10519 [24:56<2:21:48,  1.04it/s][NeMo W 2026-06-19 07:34:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 16%|█▋        | 1712/10519 [24:57<2:14:01,  1.10it/s][NeMo W 2026-06-19 07:34:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 16%|█▋        | 1713/10519 [24:58<2:18:43,  1.06it/s][NeMo W 2026-06-19 07:34:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 16%|█▋        | 1714/10519 [24:59<2:18:29,  1.06it/s][NeMo W 2026-06-19 07:34:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 16%|█▋        | 1715/10519 [25:00<2:18:40,  1.06it/s][NeMo W 2026-06-19 07:34:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 16%|█▋        | 1716/10519 [25:01<2:07:04,  1.15it/s][NeMo W 2026-06-19 07:34:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 16%|█▋        | 1717/10519 [25:02<2:06:10,  1.16it/s][NeMo W 2026-06-19 07:34:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 16%|█▋        | 1718/10519 [25:03<2:10:45,  1.12it/s][NeMo W 2026-06-19 07:34:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 16%|█▋        | 1719/10519 [25:03<2:13:03,  1.10it/s][NeMo W 2026-06-19 07:34:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.72it/s]
 16%|█▋        | 1720/10519 [25:05<2:18:46,  1.06it/s][NeMo W 2026-06-19 07:34:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.99it/s]
 16%|█▋        | 1721/10519 [25:06<2:22:59,  1.03it/s][NeMo W 2026-06-19 07:34:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 16%|█▋        | 1722/10519 [25:06<2:19:13,  1.05it/s][NeMo W 2026-06-19 07:34:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 16%|█▋        | 1723/10519 [25:07<2:17:49,  1.06it/s][NeMo W 2026-06-19 07:34:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 16%|█▋        | 1724/10519 [25:08<2:10:13,  1.13it/s][NeMo W 2026-06-19 07:34:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 16%|█▋        | 1725/10519 [25:09<2:05:44,  1.17it/s][NeMo W 2026-06-19 07:34:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 16%|█▋        | 1726/10519 [25:10<2:29:46,  1.02s/it][NeMo W 2026-06-19 07:34:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 16%|█▋        | 1727/10519 [25:11<2:22:55,  1.03it/s][NeMo W 2026-06-19 07:34:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 16%|█▋        | 1728/10519 [25:12<2:21:58,  1.03it/s][NeMo W 2026-06-19 07:34:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 16%|█▋        | 1729/10519 [25:13<2:19:30,  1.05it/s][NeMo W 2026-06-19 07:34:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:34:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 16%|█▋        | 1730/10519 [25:14<2:18:01,  1.06it/s][NeMo W 2026-06-19 07:34:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1750 samples

[NeMo W 2026-06-19 07:35:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 17%|█▋        | 1751/10519 [25:34<2:19:07,  1.05it/s][NeMo W 2026-06-19 07:35:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 17%|█▋        | 1752/10519 [25:35<2:24:41,  1.01it/s][NeMo W 2026-06-19 07:35:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.97it/s]
 17%|█▋        | 1753/10519 [25:36<2:20:56,  1.04it/s][NeMo W 2026-06-19 07:35:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.57it/s]
 17%|█▋        | 1754/10519 [25:37<2:18:43,  1.05it/s][NeMo W 2026-06-19 07:35:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 17%|█▋        | 1755/10519 [25:38<2:17:58,  1.06it/s][NeMo W 2026-06-19 07:35:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 17%|█▋        | 1756/10519 [25:39<2:09:37,  1.13it/s][NeMo W 2026-06-19 07:35:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 17%|█▋        | 1757/10519 [25:40<2:13:05,  1.10it/s][NeMo W 2026-06-19 07:35:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 17%|█▋        | 1758/10519 [25:40<2:14:15,  1.09it/s][NeMo W 2026-06-19 07:35:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 17%|█▋        | 1759/10519 [25:41<2:16:59,  1.07it/s][NeMo W 2026-06-19 07:35:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 17%|█▋        | 1760/10519 [25:42<2:17:09,  1.06it/s][NeMo W 2026-06-19 07:35:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 17%|█▋        | 1761/10519 [25:43<2:16:21,  1.07it/s][NeMo W 2026-06-19 07:35:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 17%|█▋        | 1762/10519 [25:44<2:17:02,  1.07it/s][NeMo W 2026-06-19 07:35:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 17%|█▋        | 1763/10519 [25:45<2:19:51,  1.04it/s][NeMo W 2026-06-19 07:35:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 17%|█▋        | 1764/10519 [25:46<2:23:21,  1.02it/s][NeMo W 2026-06-19 07:35:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 17%|█▋        | 1765/10519 [25:47<2:23:29,  1.02it/s][NeMo W 2026-06-19 07:35:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 17%|█▋        | 1766/10519 [25:48<2:21:25,  1.03it/s][NeMo W 2026-06-19 07:35:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 17%|█▋        | 1767/10519 [25:49<2:28:08,  1.02s/it][NeMo W 2026-06-19 07:35:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 17%|█▋        | 1768/10519 [25:50<2:13:45,  1.09it/s][NeMo W 2026-06-19 07:35:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 17%|█▋        | 1769/10519 [25:51<2:17:36,  1.06it/s][NeMo W 2026-06-19 07:35:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 17%|█▋        | 1770/10519 [25:52<2:18:06,  1.06it/s][NeMo W 2026-06-19 07:35:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 17%|█▋        | 1771/10519 [25:53<2:18:10,  1.06it/s][NeMo W 2026-06-19 07:35:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 17%|█▋        | 1772/10519 [25:54<2:22:09,  1.03it/s][NeMo W 2026-06-19 07:35:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 17%|█▋        | 1773/10519 [25:55<2:23:05,  1.02it/s][NeMo W 2026-06-19 07:35:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 17%|█▋        | 1774/10519 [25:56<2:11:17,  1.11it/s][NeMo W 2026-06-19 07:35:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 17%|█▋        | 1775/10519 [25:57<2:25:41,  1.00it/s][NeMo W 2026-06-19 07:35:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 17%|█▋        | 1776/10519 [25:58<2:23:16,  1.02it/s][NeMo W 2026-06-19 07:35:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 17%|█▋        | 1777/10519 [25:59<2:21:40,  1.03it/s][NeMo W 2026-06-19 07:35:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 17%|█▋        | 1778/10519 [26:00<2:23:08,  1.02it/s][NeMo W 2026-06-19 07:35:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 17%|█▋        | 1779/10519 [26:01<2:21:50,  1.03it/s][NeMo W 2026-06-19 07:35:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:35:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 17%|█▋        | 1780/10519 [26:02<2:33:01,  1.05s/it][NeMo W 2026-06-19 07:35:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 1800 samples

[NeMo W 2026-06-19 07:36:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.43it/s]
 17%|█▋        | 1801/10519 [26:22<2:17:36,  1.06it/s][NeMo W 2026-06-19 07:36:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 17%|█▋        | 1802/10519 [26:23<2:16:06,  1.07it/s][NeMo W 2026-06-19 07:36:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 17%|█▋        | 1803/10519 [26:24<2:18:07,  1.05it/s][NeMo W 2026-06-19 07:36:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 17%|█▋        | 1804/10519 [26:25<2:19:20,  1.04it/s][NeMo W 2026-06-19 07:36:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 17%|█▋        | 1805/10519 [26:26<2:14:15,  1.08it/s][NeMo W 2026-06-19 07:36:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.01it/s]
 17%|█▋        | 1806/10519 [26:27<2:14:23,  1.08it/s][NeMo W 2026-06-19 07:36:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
 17%|█▋        | 1807/10519 [26:28<2:16:21,  1.06it/s][NeMo W 2026-06-19 07:36:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.38it/s]
 17%|█▋        | 1808/10519 [26:29<2:20:44,  1.03it/s][NeMo W 2026-06-19 07:36:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 17%|█▋        | 1809/10519 [26:31<2:43:44,  1.13s/it][NeMo W 2026-06-19 07:36:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 17%|█▋        | 1810/10519 [26:32<2:44:46,  1.14s/it][NeMo W 2026-06-19 07:36:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.20it/s]
 17%|█▋        | 1811/10519 [26:32<2:29:17,  1.03s/it][NeMo W 2026-06-19 07:36:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.31it/s]
 17%|█▋        | 1812/10519 [26:33<2:19:52,  1.04it/s][NeMo W 2026-06-19 07:36:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 17%|█▋        | 1813/10519 [26:34<2:20:05,  1.04it/s][NeMo W 2026-06-19 07:36:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 17%|█▋        | 1814/10519 [26:35<2:18:01,  1.05it/s][NeMo W 2026-06-19 07:36:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.06it/s]
 17%|█▋        | 1815/10519 [26:36<2:19:38,  1.04it/s][NeMo W 2026-06-19 07:36:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 17%|█▋        | 1816/10519 [26:37<2:27:24,  1.02s/it][NeMo W 2026-06-19 07:36:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 17%|█▋        | 1817/10519 [26:38<2:24:27,  1.00it/s][NeMo W 2026-06-19 07:36:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 17%|█▋        | 1818/10519 [26:39<2:22:46,  1.02it/s][NeMo W 2026-06-19 07:36:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 17%|█▋        | 1819/10519 [26:40<2:20:26,  1.03it/s][NeMo W 2026-06-19 07:36:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 17%|█▋        | 1820/10519 [26:41<2:21:11,  1.03it/s][NeMo W 2026-06-19 07:36:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 17%|█▋        | 1821/10519 [26:42<2:21:26,  1.02it/s][NeMo W 2026-06-19 07:36:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 17%|█▋        | 1822/10519 [26:43<2:14:03,  1.08it/s][NeMo W 2026-06-19 07:36:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 17%|█▋        | 1823/10519 [26:44<2:34:18,  1.06s/it][NeMo W 2026-06-19 07:36:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 17%|█▋        | 1824/10519 [26:46<2:47:59,  1.16s/it][NeMo W 2026-06-19 07:36:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 17%|█▋        | 1825/10519 [26:47<2:41:29,  1.11s/it][NeMo W 2026-06-19 07:36:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 17%|█▋        | 1826/10519 [26:48<2:36:11,  1.08s/it][NeMo W 2026-06-19 07:36:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 17%|█▋        | 1827/10519 [26:49<2:30:15,  1.04s/it][NeMo W 2026-06-19 07:36:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 17%|█▋        | 1828/10519 [26:49<2:20:56,  1.03it/s][NeMo W 2026-06-19 07:36:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
 17%|█▋        | 1829/10519 [26:51<2:26:19,  1.01s/it][NeMo W 2026-06-19 07:36:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]

Checkpoint saved: 1850 samples

[NeMo W 2026-06-19 07:36:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 18%|█▊        | 1851/10519 [27:12<2:33:04,  1.06s/it][NeMo W 2026-06-19 07:36:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 18%|█▊        | 1852/10519 [27:13<2:28:15,  1.03s/it][NeMo W 2026-06-19 07:36:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 18%|█▊        | 1853/10519 [27:14<2:24:48,  1.00s/it][NeMo W 2026-06-19 07:36:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 18%|█▊        | 1854/10519 [27:15<2:22:42,  1.01it/s][NeMo W 2026-06-19 07:36:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 18%|█▊        | 1855/10519 [27:16<2:22:23,  1.01it/s][NeMo W 2026-06-19 07:36:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 18%|█▊        | 1856/10519 [27:17<2:21:38,  1.02it/s][NeMo W 2026-06-19 07:36:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:36:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 18%|█▊        | 1857/10519 [27:18<2:20:23,  1.03it/s][NeMo W 2026-06-19 07:37:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 18%|█▊        | 1858/10519 [27:19<2:19:26,  1.04it/s][NeMo W 2026-06-19 07:37:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 18%|█▊        | 1859/10519 [27:20<2:28:43,  1.03s/it][NeMo W 2026-06-19 07:37:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.54it/s]
 18%|█▊        | 1860/10519 [27:21<2:25:13,  1.01s/it][NeMo W 2026-06-19 07:37:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.54it/s]
 18%|█▊        | 1861/10519 [27:22<2:26:53,  1.02s/it][NeMo W 2026-06-19 07:37:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.80it/s]
 18%|█▊        | 1862/10519 [27:23<2:22:49,  1.01it/s][NeMo W 2026-06-19 07:37:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 18%|█▊        | 1863/10519 [27:24<2:15:25,  1.07it/s][NeMo W 2026-06-19 07:37:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 18%|█▊        | 1864/10519 [27:25<2:17:42,  1.05it/s][NeMo W 2026-06-19 07:37:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 18%|█▊        | 1865/10519 [27:26<2:18:38,  1.04it/s][NeMo W 2026-06-19 07:37:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.72it/s]
 18%|█▊        | 1866/10519 [27:26<2:14:39,  1.07it/s][NeMo W 2026-06-19 07:37:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 18%|█▊        | 1867/10519 [27:27<2:14:45,  1.07it/s][NeMo W 2026-06-19 07:37:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 18%|█▊        | 1868/10519 [27:28<2:14:28,  1.07it/s][NeMo W 2026-06-19 07:37:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 18%|█▊        | 1869/10519 [27:29<2:18:49,  1.04it/s][NeMo W 2026-06-19 07:37:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 18%|█▊        | 1870/10519 [27:30<2:20:55,  1.02it/s][NeMo W 2026-06-19 07:37:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 18%|█▊        | 1871/10519 [27:31<2:19:22,  1.03it/s][NeMo W 2026-06-19 07:37:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 18%|█▊        | 1872/10519 [27:32<2:23:46,  1.00it/s][NeMo W 2026-06-19 07:37:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 18%|█▊        | 1873/10519 [27:33<2:23:13,  1.01it/s][NeMo W 2026-06-19 07:37:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 18%|█▊        | 1874/10519 [27:34<2:18:24,  1.04it/s][NeMo W 2026-06-19 07:37:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.39it/s]
 18%|█▊        | 1875/10519 [27:35<2:21:32,  1.02it/s][NeMo W 2026-06-19 07:37:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 18%|█▊        | 1876/10519 [27:36<2:22:11,  1.01it/s][NeMo W 2026-06-19 07:37:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 18%|█▊        | 1877/10519 [27:37<2:21:04,  1.02it/s][NeMo W 2026-06-19 07:37:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 18%|█▊        | 1878/10519 [27:38<2:19:22,  1.03it/s][NeMo W 2026-06-19 07:37:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.40it/s]
 18%|█▊        | 1879/10519 [27:39<2:19:31,  1.03it/s][NeMo W 2026-06-19 07:37:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]

Checkpoint saved: 1900 samples

[NeMo W 2026-06-19 07:37:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 18%|█▊        | 1901/10519 [28:00<2:28:59,  1.04s/it][NeMo W 2026-06-19 07:37:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 18%|█▊        | 1902/10519 [28:01<2:26:19,  1.02s/it][NeMo W 2026-06-19 07:37:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 18%|█▊        | 1903/10519 [28:02<2:28:07,  1.03s/it][NeMo W 2026-06-19 07:37:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 18%|█▊        | 1904/10519 [28:03<2:24:19,  1.01s/it][NeMo W 2026-06-19 07:37:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 18%|█▊        | 1905/10519 [28:04<2:22:15,  1.01it/s][NeMo W 2026-06-19 07:37:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 18%|█▊        | 1906/10519 [28:05<2:22:23,  1.01it/s][NeMo W 2026-06-19 07:37:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 18%|█▊        | 1907/10519 [28:06<2:20:15,  1.02it/s][NeMo W 2026-06-19 07:37:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 18%|█▊        | 1908/10519 [28:07<2:15:50,  1.06it/s][NeMo W 2026-06-19 07:37:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 18%|█▊        | 1909/10519 [28:08<2:18:30,  1.04it/s][NeMo W 2026-06-19 07:37:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 18%|█▊        | 1910/10519 [28:09<2:17:31,  1.04it/s][NeMo W 2026-06-19 07:37:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 18%|█▊        | 1911/10519 [28:10<2:17:23,  1.04it/s][NeMo W 2026-06-19 07:37:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 18%|█▊        | 1912/10519 [28:11<2:09:54,  1.10it/s][NeMo W 2026-06-19 07:37:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.24it/s]
 18%|█▊        | 1913/10519 [28:12<2:14:07,  1.07it/s][NeMo W 2026-06-19 07:37:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 18%|█▊        | 1914/10519 [28:13<2:18:58,  1.03it/s][NeMo W 2026-06-19 07:37:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 18%|█▊        | 1915/10519 [28:14<2:18:08,  1.04it/s][NeMo W 2026-06-19 07:37:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 18%|█▊        | 1916/10519 [28:15<2:17:00,  1.05it/s][NeMo W 2026-06-19 07:37:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.44it/s]
 18%|█▊        | 1917/10519 [28:16<2:17:27,  1.04it/s][NeMo W 2026-06-19 07:37:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 18%|█▊        | 1918/10519 [28:16<2:10:38,  1.10it/s][NeMo W 2026-06-19 07:37:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 18%|█▊        | 1919/10519 [28:17<2:13:56,  1.07it/s][NeMo W 2026-06-19 07:37:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:37:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 18%|█▊        | 1920/10519 [28:18<2:21:51,  1.01it/s][NeMo W 2026-06-19 07:38:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 18%|█▊        | 1921/10519 [28:19<2:22:28,  1.01it/s][NeMo W 2026-06-19 07:38:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 18%|█▊        | 1922/10519 [28:22<3:41:04,  1.54s/it][NeMo W 2026-06-19 07:38:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 18%|█▊        | 1923/10519 [28:23<3:08:10,  1.31s/it][NeMo W 2026-06-19 07:38:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 18%|█▊        | 1924/10519 [28:24<2:50:38,  1.19s/it][NeMo W 2026-06-19 07:38:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 18%|█▊        | 1925/10519 [28:25<2:43:30,  1.14s/it][NeMo W 2026-06-19 07:38:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 18%|█▊        | 1926/10519 [28:26<2:35:40,  1.09s/it][NeMo W 2026-06-19 07:38:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.03it/s]
 18%|█▊        | 1927/10519 [28:27<2:31:51,  1.06s/it][NeMo W 2026-06-19 07:38:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 18%|█▊        | 1928/10519 [28:28<2:30:03,  1.05s/it][NeMo W 2026-06-19 07:38:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 18%|█▊        | 1929/10519 [28:29<2:16:47,  1.05it/s][NeMo W 2026-06-19 07:38:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]

Checkpoint saved: 1950 samples

[NeMo W 2026-06-19 07:38:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 19%|█▊        | 1951/10519 [28:50<2:23:56,  1.01s/it][NeMo W 2026-06-19 07:38:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 19%|█▊        | 1952/10519 [28:51<2:22:14,  1.00it/s][NeMo W 2026-06-19 07:38:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 19%|█▊        | 1953/10519 [28:52<2:25:02,  1.02s/it][NeMo W 2026-06-19 07:38:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.14it/s]
 19%|█▊        | 1954/10519 [28:53<2:24:26,  1.01s/it][NeMo W 2026-06-19 07:38:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 19%|█▊        | 1955/10519 [28:54<2:20:49,  1.01it/s][NeMo W 2026-06-19 07:38:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 19%|█▊        | 1956/10519 [28:55<2:25:55,  1.02s/it][NeMo W 2026-06-19 07:38:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 19%|█▊        | 1957/10519 [28:56<2:22:55,  1.00s/it][NeMo W 2026-06-19 07:38:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 19%|█▊        | 1958/10519 [28:57<2:21:35,  1.01it/s][NeMo W 2026-06-19 07:38:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 19%|█▊        | 1959/10519 [29:01<4:12:28,  1.77s/it][NeMo W 2026-06-19 07:38:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 19%|█▊        | 1960/10519 [29:02<3:38:49,  1.53s/it][NeMo W 2026-06-19 07:38:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 19%|█▊        | 1961/10519 [29:03<3:15:56,  1.37s/it][NeMo W 2026-06-19 07:38:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 19%|█▊        | 1962/10519 [29:04<2:48:59,  1.18s/it][NeMo W 2026-06-19 07:38:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
 19%|█▊        | 1963/10519 [29:05<2:40:17,  1.12s/it][NeMo W 2026-06-19 07:38:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 19%|█▊        | 1964/10519 [29:06<2:32:48,  1.07s/it][NeMo W 2026-06-19 07:38:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 19%|█▊        | 1965/10519 [29:07<2:25:57,  1.02s/it][NeMo W 2026-06-19 07:38:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 19%|█▊        | 1966/10519 [29:07<2:14:11,  1.06it/s][NeMo W 2026-06-19 07:38:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 19%|█▊        | 1967/10519 [29:08<2:13:03,  1.07it/s][NeMo W 2026-06-19 07:38:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 19%|█▊        | 1968/10519 [29:09<2:16:56,  1.04it/s][NeMo W 2026-06-19 07:38:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 19%|█▊        | 1969/10519 [29:10<2:18:14,  1.03it/s][NeMo W 2026-06-19 07:38:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 19%|█▊        | 1970/10519 [29:11<2:13:47,  1.06it/s][NeMo W 2026-06-19 07:38:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 19%|█▊        | 1971/10519 [29:12<2:13:44,  1.07it/s][NeMo W 2026-06-19 07:38:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 19%|█▊        | 1972/10519 [29:13<2:13:10,  1.07it/s][NeMo W 2026-06-19 07:38:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 19%|█▉        | 1973/10519 [29:14<2:22:31,  1.00s/it][NeMo W 2026-06-19 07:38:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 19%|█▉        | 1974/10519 [29:15<2:21:04,  1.01it/s][NeMo W 2026-06-19 07:38:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 19%|█▉        | 1975/10519 [29:16<2:24:24,  1.01s/it][NeMo W 2026-06-19 07:38:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.41it/s]
 19%|█▉        | 1976/10519 [29:17<2:22:43,  1.00s/it][NeMo W 2026-06-19 07:38:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:38:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.09it/s]
 19%|█▉        | 1977/10519 [29:18<2:16:52,  1.04it/s][NeMo W 2026-06-19 07:39:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 19%|█▉        | 1978/10519 [29:19<2:10:26,  1.09it/s][NeMo W 2026-06-19 07:39:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 19%|█▉        | 1979/10519 [29:20<2:10:26,  1.09it/s][NeMo W 2026-06-19 07:39:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]

Checkpoint saved: 2000 samples

[NeMo W 2026-06-19 07:39:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 19%|█▉        | 2001/10519 [29:48<2:53:32,  1.22s/it][NeMo W 2026-06-19 07:39:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.43it/s]
 19%|█▉        | 2002/10519 [29:48<2:41:01,  1.13s/it][NeMo W 2026-06-19 07:39:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 19%|█▉        | 2003/10519 [29:50<2:42:03,  1.14s/it][NeMo W 2026-06-19 07:39:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.58it/s]
 19%|█▉        | 2004/10519 [29:51<2:34:49,  1.09s/it][NeMo W 2026-06-19 07:39:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.87it/s]
 19%|█▉        | 2005/10519 [29:52<2:29:13,  1.05s/it][NeMo W 2026-06-19 07:39:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 19%|█▉        | 2006/10519 [29:52<2:18:58,  1.02it/s][NeMo W 2026-06-19 07:39:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.69it/s]
 19%|█▉        | 2007/10519 [29:53<2:19:16,  1.02it/s][NeMo W 2026-06-19 07:39:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 19%|█▉        | 2008/10519 [29:54<2:18:57,  1.02it/s][NeMo W 2026-06-19 07:39:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 19%|█▉        | 2009/10519 [29:55<2:18:17,  1.03it/s][NeMo W 2026-06-19 07:39:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 19%|█▉        | 2010/10519 [29:56<2:13:51,  1.06it/s][NeMo W 2026-06-19 07:39:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 19%|█▉        | 2011/10519 [29:57<2:10:05,  1.09it/s][NeMo W 2026-06-19 07:39:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 19%|█▉        | 2012/10519 [29:58<2:12:53,  1.07it/s][NeMo W 2026-06-19 07:39:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 19%|█▉        | 2013/10519 [29:59<2:14:23,  1.05it/s][NeMo W 2026-06-19 07:39:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 19%|█▉        | 2014/10519 [30:00<2:16:26,  1.04it/s][NeMo W 2026-06-19 07:39:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 19%|█▉        | 2015/10519 [30:01<2:15:23,  1.05it/s][NeMo W 2026-06-19 07:39:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 19%|█▉        | 2016/10519 [30:02<2:04:22,  1.14it/s][NeMo W 2026-06-19 07:39:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 19%|█▉        | 2017/10519 [30:03<2:09:15,  1.10it/s][NeMo W 2026-06-19 07:39:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 19%|█▉        | 2018/10519 [30:04<2:11:41,  1.08it/s][NeMo W 2026-06-19 07:39:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 19%|█▉        | 2019/10519 [30:04<2:10:23,  1.09it/s][NeMo W 2026-06-19 07:39:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.84it/s]
 19%|█▉        | 2020/10519 [30:05<2:13:35,  1.06it/s][NeMo W 2026-06-19 07:39:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 19%|█▉        | 2021/10519 [30:06<2:12:37,  1.07it/s][NeMo W 2026-06-19 07:39:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 19%|█▉        | 2022/10519 [30:07<2:14:17,  1.05it/s][NeMo W 2026-06-19 07:39:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 19%|█▉        | 2023/10519 [30:08<2:13:19,  1.06it/s][NeMo W 2026-06-19 07:39:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 19%|█▉        | 2024/10519 [30:09<2:10:16,  1.09it/s][NeMo W 2026-06-19 07:39:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 19%|█▉        | 2025/10519 [30:10<2:12:27,  1.07it/s][NeMo W 2026-06-19 07:39:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 19%|█▉        | 2026/10519 [30:11<2:15:04,  1.05it/s][NeMo W 2026-06-19 07:39:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 19%|█▉        | 2027/10519 [30:12<2:16:09,  1.04it/s][NeMo W 2026-06-19 07:39:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 19%|█▉        | 2028/10519 [30:13<2:16:37,  1.04it/s][NeMo W 2026-06-19 07:39:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 19%|█▉        | 2029/10519 [30:14<2:13:19,  1.06it/s][NeMo W 2026-06-19 07:39:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:39:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]

Checkpoint saved: 2050 samples

[NeMo W 2026-06-19 07:40:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 19%|█▉        | 2051/10519 [30:36<2:55:39,  1.24s/it][NeMo W 2026-06-19 07:40:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 20%|█▉        | 2052/10519 [30:37<2:43:01,  1.16s/it][NeMo W 2026-06-19 07:40:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 20%|█▉        | 2053/10519 [30:38<2:33:26,  1.09s/it][NeMo W 2026-06-19 07:40:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 20%|█▉        | 2054/10519 [30:39<2:35:56,  1.11s/it][NeMo W 2026-06-19 07:40:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 20%|█▉        | 2055/10519 [30:40<2:29:00,  1.06s/it][NeMo W 2026-06-19 07:40:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 20%|█▉        | 2056/10519 [30:41<2:23:13,  1.02s/it][NeMo W 2026-06-19 07:40:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
 20%|█▉        | 2057/10519 [30:42<2:14:13,  1.05it/s][NeMo W 2026-06-19 07:40:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 20%|█▉        | 2058/10519 [30:43<2:15:09,  1.04it/s][NeMo W 2026-06-19 07:40:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 20%|█▉        | 2059/10519 [30:44<2:14:43,  1.05it/s][NeMo W 2026-06-19 07:40:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 20%|█▉        | 2060/10519 [30:45<2:16:29,  1.03it/s][NeMo W 2026-06-19 07:40:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 20%|█▉        | 2061/10519 [30:46<2:19:01,  1.01it/s][NeMo W 2026-06-19 07:40:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 20%|█▉        | 2062/10519 [30:47<2:15:50,  1.04it/s][NeMo W 2026-06-19 07:40:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 20%|█▉        | 2063/10519 [30:48<2:15:03,  1.04it/s][NeMo W 2026-06-19 07:40:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 20%|█▉        | 2064/10519 [30:49<2:17:02,  1.03it/s][NeMo W 2026-06-19 07:40:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 20%|█▉        | 2065/10519 [30:50<2:15:14,  1.04it/s][NeMo W 2026-06-19 07:40:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 20%|█▉        | 2066/10519 [30:51<2:15:46,  1.04it/s][NeMo W 2026-06-19 07:40:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 20%|█▉        | 2067/10519 [30:52<2:20:01,  1.01it/s][NeMo W 2026-06-19 07:40:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 20%|█▉        | 2068/10519 [30:54<3:26:05,  1.46s/it][NeMo W 2026-06-19 07:40:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 20%|█▉        | 2069/10519 [30:55<2:55:41,  1.25s/it][NeMo W 2026-06-19 07:40:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 20%|█▉        | 2070/10519 [30:56<2:43:09,  1.16s/it][NeMo W 2026-06-19 07:40:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.89it/s]
 20%|█▉        | 2071/10519 [30:57<2:34:49,  1.10s/it][NeMo W 2026-06-19 07:40:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 20%|█▉        | 2072/10519 [30:58<2:31:32,  1.08s/it][NeMo W 2026-06-19 07:40:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.39it/s]
 20%|█▉        | 2073/10519 [30:59<2:42:23,  1.15s/it][NeMo W 2026-06-19 07:40:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 20%|█▉        | 2074/10519 [31:00<2:32:24,  1.08s/it][NeMo W 2026-06-19 07:40:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 20%|█▉        | 2075/10519 [31:01<2:26:53,  1.04s/it][NeMo W 2026-06-19 07:40:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 20%|█▉        | 2076/10519 [31:02<2:23:51,  1.02s/it][NeMo W 2026-06-19 07:40:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 20%|█▉        | 2077/10519 [31:03<2:28:16,  1.05s/it][NeMo W 2026-06-19 07:40:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 20%|█▉        | 2078/10519 [31:04<2:24:16,  1.03s/it][NeMo W 2026-06-19 07:40:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 20%|█▉        | 2079/10519 [31:05<2:23:51,  1.02s/it][NeMo W 2026-06-19 07:40:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:40:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 20%|█▉        | 2080/10519 [31:06<2:22:03,  1.01s/it][NeMo W 2026-06-19 07:40:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 2100 samples

[NeMo W 2026-06-19 07:41:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 20%|█▉        | 2101/10519 [31:26<2:26:56,  1.05s/it][NeMo W 2026-06-19 07:41:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 20%|█▉        | 2102/10519 [31:27<2:21:36,  1.01s/it][NeMo W 2026-06-19 07:41:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 20%|█▉        | 2103/10519 [31:28<2:11:49,  1.06it/s][NeMo W 2026-06-19 07:41:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 20%|██        | 2104/10519 [31:29<2:14:59,  1.04it/s][NeMo W 2026-06-19 07:41:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
 20%|██        | 2105/10519 [31:30<2:04:53,  1.12it/s][NeMo W 2026-06-19 07:41:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 20%|██        | 2106/10519 [31:30<1:58:01,  1.19it/s][NeMo W 2026-06-19 07:41:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 20%|██        | 2107/10519 [31:31<2:04:45,  1.12it/s][NeMo W 2026-06-19 07:41:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 20%|██        | 2108/10519 [31:32<2:11:58,  1.06it/s][NeMo W 2026-06-19 07:41:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.43it/s]
 20%|██        | 2109/10519 [31:34<2:17:19,  1.02it/s][NeMo W 2026-06-19 07:41:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.76it/s]
 20%|██        | 2110/10519 [31:35<2:17:36,  1.02it/s][NeMo W 2026-06-19 07:41:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 20%|██        | 2111/10519 [31:35<2:16:48,  1.02it/s][NeMo W 2026-06-19 07:41:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 20%|██        | 2112/10519 [31:36<2:15:14,  1.04it/s][NeMo W 2026-06-19 07:41:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 20%|██        | 2113/10519 [31:37<2:11:58,  1.06it/s][NeMo W 2026-06-19 07:41:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 20%|██        | 2114/10519 [31:38<2:11:46,  1.06it/s][NeMo W 2026-06-19 07:41:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 20%|██        | 2115/10519 [31:39<2:16:22,  1.03it/s][NeMo W 2026-06-19 07:41:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 20%|██        | 2116/10519 [31:40<2:14:46,  1.04it/s][NeMo W 2026-06-19 07:41:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 20%|██        | 2117/10519 [31:41<2:18:18,  1.01it/s][NeMo W 2026-06-19 07:41:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 20%|██        | 2118/10519 [31:42<2:17:08,  1.02it/s][NeMo W 2026-06-19 07:41:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 20%|██        | 2119/10519 [31:43<2:25:20,  1.04s/it][NeMo W 2026-06-19 07:41:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 20%|██        | 2120/10519 [31:44<2:21:58,  1.01s/it][NeMo W 2026-06-19 07:41:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 20%|██        | 2121/10519 [31:45<2:20:50,  1.01s/it][NeMo W 2026-06-19 07:41:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 20%|██        | 2122/10519 [31:46<2:26:34,  1.05s/it][NeMo W 2026-06-19 07:41:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.22it/s]
 20%|██        | 2123/10519 [31:48<2:29:02,  1.07s/it][NeMo W 2026-06-19 07:41:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 20%|██        | 2124/10519 [31:49<2:25:14,  1.04s/it][NeMo W 2026-06-19 07:41:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.52it/s]
 20%|██        | 2125/10519 [31:50<2:25:24,  1.04s/it][NeMo W 2026-06-19 07:41:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 20%|██        | 2126/10519 [31:50<2:14:29,  1.04it/s][NeMo W 2026-06-19 07:41:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 20%|██        | 2127/10519 [31:51<2:14:57,  1.04it/s][NeMo W 2026-06-19 07:41:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 20%|██        | 2128/10519 [31:52<2:16:35,  1.02it/s][NeMo W 2026-06-19 07:41:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 20%|██        | 2129/10519 [31:54<2:57:19,  1.27s/it][NeMo W 2026-06-19 07:41:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]

Checkpoint saved: 2150 samples

[NeMo W 2026-06-19 07:41:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 20%|██        | 2151/10519 [32:16<2:16:50,  1.02it/s][NeMo W 2026-06-19 07:41:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 20%|██        | 2152/10519 [32:17<2:15:14,  1.03it/s][NeMo W 2026-06-19 07:41:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:41:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 20%|██        | 2153/10519 [32:18<2:14:57,  1.03it/s][NeMo W 2026-06-19 07:42:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 20%|██        | 2154/10519 [32:19<2:12:31,  1.05it/s][NeMo W 2026-06-19 07:42:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 20%|██        | 2155/10519 [32:20<2:13:05,  1.05it/s][NeMo W 2026-06-19 07:42:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 20%|██        | 2156/10519 [32:21<2:11:51,  1.06it/s][NeMo W 2026-06-19 07:42:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 21%|██        | 2157/10519 [32:22<2:10:51,  1.07it/s][NeMo W 2026-06-19 07:42:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.24it/s]
 21%|██        | 2158/10519 [32:23<2:14:20,  1.04it/s][NeMo W 2026-06-19 07:42:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.62it/s]
 21%|██        | 2159/10519 [32:24<2:19:16,  1.00it/s][NeMo W 2026-06-19 07:42:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.71it/s]
 21%|██        | 2160/10519 [32:25<2:19:41,  1.00s/it][NeMo W 2026-06-19 07:42:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 21%|██        | 2161/10519 [32:26<2:16:56,  1.02it/s][NeMo W 2026-06-19 07:42:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 21%|██        | 2162/10519 [32:27<2:14:48,  1.03it/s][NeMo W 2026-06-19 07:42:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 21%|██        | 2163/10519 [32:28<2:20:05,  1.01s/it][NeMo W 2026-06-19 07:42:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.30it/s]
 21%|██        | 2164/10519 [32:29<2:12:50,  1.05it/s][NeMo W 2026-06-19 07:42:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 21%|██        | 2165/10519 [32:30<2:16:03,  1.02it/s][NeMo W 2026-06-19 07:42:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 21%|██        | 2166/10519 [32:31<2:16:56,  1.02it/s][NeMo W 2026-06-19 07:42:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 21%|██        | 2167/10519 [32:32<2:18:57,  1.00it/s][NeMo W 2026-06-19 07:42:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 21%|██        | 2168/10519 [32:33<2:24:03,  1.04s/it][NeMo W 2026-06-19 07:42:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 21%|██        | 2169/10519 [32:34<2:12:36,  1.05it/s][NeMo W 2026-06-19 07:42:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 21%|██        | 2170/10519 [32:35<2:13:08,  1.05it/s][NeMo W 2026-06-19 07:42:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 21%|██        | 2171/10519 [32:36<2:08:55,  1.08it/s][NeMo W 2026-06-19 07:42:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.46it/s]
 21%|██        | 2172/10519 [32:37<2:17:12,  1.01it/s][NeMo W 2026-06-19 07:42:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 21%|██        | 2173/10519 [32:38<2:12:02,  1.05it/s][NeMo W 2026-06-19 07:42:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 21%|██        | 2174/10519 [32:39<2:08:14,  1.08it/s][NeMo W 2026-06-19 07:42:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 21%|██        | 2175/10519 [32:39<2:08:57,  1.08it/s][NeMo W 2026-06-19 07:42:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 21%|██        | 2176/10519 [32:41<2:16:04,  1.02it/s][NeMo W 2026-06-19 07:42:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 21%|██        | 2177/10519 [32:42<2:19:36,  1.00s/it][NeMo W 2026-06-19 07:42:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 21%|██        | 2178/10519 [32:43<2:19:19,  1.00s/it][NeMo W 2026-06-19 07:42:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 21%|██        | 2179/10519 [32:44<2:16:00,  1.02it/s][NeMo W 2026-06-19 07:42:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 2200 samples

[NeMo W 2026-06-19 07:42:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 21%|██        | 2201/10519 [33:06<2:42:19,  1.17s/it][NeMo W 2026-06-19 07:42:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 21%|██        | 2202/10519 [33:07<2:32:47,  1.10s/it][NeMo W 2026-06-19 07:42:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 21%|██        | 2203/10519 [33:07<2:15:23,  1.02it/s][NeMo W 2026-06-19 07:42:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 21%|██        | 2204/10519 [33:08<2:11:06,  1.06it/s][NeMo W 2026-06-19 07:42:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 21%|██        | 2205/10519 [33:09<2:12:38,  1.04it/s][NeMo W 2026-06-19 07:42:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
 21%|██        | 2206/10519 [33:10<2:12:07,  1.05it/s][NeMo W 2026-06-19 07:42:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 21%|██        | 2207/10519 [33:11<2:03:10,  1.12it/s][NeMo W 2026-06-19 07:42:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 21%|██        | 2208/10519 [33:12<2:08:00,  1.08it/s][NeMo W 2026-06-19 07:42:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 21%|██        | 2209/10519 [33:13<2:10:19,  1.06it/s][NeMo W 2026-06-19 07:42:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 21%|██        | 2210/10519 [33:14<2:14:13,  1.03it/s][NeMo W 2026-06-19 07:42:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.71it/s]
 21%|██        | 2211/10519 [33:15<2:13:14,  1.04it/s][NeMo W 2026-06-19 07:42:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 21%|██        | 2212/10519 [33:16<2:15:53,  1.02it/s][NeMo W 2026-06-19 07:42:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 21%|██        | 2213/10519 [33:17<2:13:26,  1.04it/s][NeMo W 2026-06-19 07:42:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 21%|██        | 2214/10519 [33:18<2:06:06,  1.10it/s][NeMo W 2026-06-19 07:42:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:42:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 21%|██        | 2215/10519 [33:18<2:07:27,  1.09it/s][NeMo W 2026-06-19 07:43:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 21%|██        | 2216/10519 [33:19<2:08:01,  1.08it/s][NeMo W 2026-06-19 07:43:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 21%|██        | 2217/10519 [33:20<2:08:58,  1.07it/s][NeMo W 2026-06-19 07:43:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 21%|██        | 2218/10519 [33:21<2:03:27,  1.12it/s][NeMo W 2026-06-19 07:43:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 21%|██        | 2219/10519 [33:22<2:06:59,  1.09it/s][NeMo W 2026-06-19 07:43:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 21%|██        | 2220/10519 [33:23<2:00:38,  1.15it/s][NeMo W 2026-06-19 07:43:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 21%|██        | 2221/10519 [33:24<2:05:32,  1.10it/s][NeMo W 2026-06-19 07:43:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 21%|██        | 2222/10519 [33:25<2:14:29,  1.03it/s][NeMo W 2026-06-19 07:43:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 21%|██        | 2223/10519 [33:26<2:14:27,  1.03it/s][NeMo W 2026-06-19 07:43:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 21%|██        | 2224/10519 [33:27<2:08:37,  1.07it/s][NeMo W 2026-06-19 07:43:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 21%|██        | 2225/10519 [33:28<2:03:44,  1.12it/s][NeMo W 2026-06-19 07:43:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 21%|██        | 2226/10519 [33:29<2:08:49,  1.07it/s][NeMo W 2026-06-19 07:43:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 21%|██        | 2227/10519 [33:30<2:08:06,  1.08it/s][NeMo W 2026-06-19 07:43:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 21%|██        | 2228/10519 [33:31<2:09:43,  1.07it/s][NeMo W 2026-06-19 07:43:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 21%|██        | 2229/10519 [33:32<2:15:13,  1.02it/s][NeMo W 2026-06-19 07:43:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]

Checkpoint saved: 2250 samples

[NeMo W 2026-06-19 07:43:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.98it/s]
 21%|██▏       | 2251/10519 [33:54<2:36:49,  1.14s/it][NeMo W 2026-06-19 07:43:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 21%|██▏       | 2252/10519 [33:55<2:27:40,  1.07s/it][NeMo W 2026-06-19 07:43:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 21%|██▏       | 2253/10519 [33:56<2:24:13,  1.05s/it][NeMo W 2026-06-19 07:43:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.86it/s]
 21%|██▏       | 2254/10519 [33:57<2:19:56,  1.02s/it][NeMo W 2026-06-19 07:43:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 21%|██▏       | 2255/10519 [33:58<2:08:43,  1.07it/s][NeMo W 2026-06-19 07:43:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 21%|██▏       | 2256/10519 [33:58<2:08:28,  1.07it/s][NeMo W 2026-06-19 07:43:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 21%|██▏       | 2257/10519 [34:00<2:14:56,  1.02it/s][NeMo W 2026-06-19 07:43:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 21%|██▏       | 2258/10519 [34:01<2:15:50,  1.01it/s][NeMo W 2026-06-19 07:43:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 21%|██▏       | 2259/10519 [34:01<2:14:00,  1.03it/s][NeMo W 2026-06-19 07:43:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 21%|██▏       | 2260/10519 [34:02<2:14:22,  1.02it/s][NeMo W 2026-06-19 07:43:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 21%|██▏       | 2261/10519 [34:03<2:14:25,  1.02it/s][NeMo W 2026-06-19 07:43:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 22%|██▏       | 2262/10519 [34:04<2:13:21,  1.03it/s][NeMo W 2026-06-19 07:43:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 22%|██▏       | 2263/10519 [34:05<2:07:15,  1.08it/s][NeMo W 2026-06-19 07:43:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.67it/s]
 22%|██▏       | 2264/10519 [34:06<2:15:27,  1.02it/s][NeMo W 2026-06-19 07:43:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 22%|██▏       | 2265/10519 [34:07<2:13:27,  1.03it/s][NeMo W 2026-06-19 07:43:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 22%|██▏       | 2266/10519 [34:08<2:12:34,  1.04it/s][NeMo W 2026-06-19 07:43:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 22%|██▏       | 2267/10519 [34:09<2:11:46,  1.04it/s][NeMo W 2026-06-19 07:43:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.35it/s]
 22%|██▏       | 2268/10519 [34:10<2:07:35,  1.08it/s][NeMo W 2026-06-19 07:43:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.34it/s]
 22%|██▏       | 2269/10519 [34:11<2:07:49,  1.08it/s][NeMo W 2026-06-19 07:43:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 22%|██▏       | 2270/10519 [34:12<2:09:04,  1.07it/s][NeMo W 2026-06-19 07:43:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 22%|██▏       | 2271/10519 [34:13<2:14:14,  1.02it/s][NeMo W 2026-06-19 07:43:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 22%|██▏       | 2272/10519 [34:14<2:16:39,  1.01it/s][NeMo W 2026-06-19 07:43:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 22%|██▏       | 2273/10519 [34:15<2:14:44,  1.02it/s][NeMo W 2026-06-19 07:43:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 22%|██▏       | 2274/10519 [34:16<2:07:02,  1.08it/s][NeMo W 2026-06-19 07:43:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 22%|██▏       | 2275/10519 [34:17<2:02:43,  1.12it/s][NeMo W 2026-06-19 07:43:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:43:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 22%|██▏       | 2276/10519 [34:17<1:57:28,  1.17it/s][NeMo W 2026-06-19 07:44:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 22%|██▏       | 2277/10519 [34:21<3:41:31,  1.61s/it][NeMo W 2026-06-19 07:44:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 22%|██▏       | 2278/10519 [34:22<3:14:18,  1.41s/it][NeMo W 2026-06-19 07:44:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 22%|██▏       | 2279/10519 [34:23<2:56:09,  1.28s/it][NeMo W 2026-06-19 07:44:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 2300 samples

[NeMo W 2026-06-19 07:44:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.15it/s]
 22%|██▏       | 2301/10519 [34:44<2:24:57,  1.06s/it][NeMo W 2026-06-19 07:44:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.80it/s]
 22%|██▏       | 2302/10519 [34:45<2:16:32,  1.00it/s][NeMo W 2026-06-19 07:44:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 22%|██▏       | 2303/10519 [34:46<2:10:05,  1.05it/s][NeMo W 2026-06-19 07:44:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 22%|██▏       | 2304/10519 [34:46<2:08:20,  1.07it/s][NeMo W 2026-06-19 07:44:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 22%|██▏       | 2305/10519 [34:47<2:08:28,  1.07it/s][NeMo W 2026-06-19 07:44:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 22%|██▏       | 2306/10519 [34:48<2:09:28,  1.06it/s][NeMo W 2026-06-19 07:44:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 22%|██▏       | 2307/10519 [34:49<2:10:24,  1.05it/s][NeMo W 2026-06-19 07:44:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 22%|██▏       | 2308/10519 [34:50<2:10:13,  1.05it/s][NeMo W 2026-06-19 07:44:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 22%|██▏       | 2309/10519 [34:51<2:09:43,  1.05it/s][NeMo W 2026-06-19 07:44:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 22%|██▏       | 2310/10519 [34:52<2:12:12,  1.03it/s][NeMo W 2026-06-19 07:44:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 22%|██▏       | 2311/10519 [34:53<2:02:14,  1.12it/s][NeMo W 2026-06-19 07:44:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 22%|██▏       | 2312/10519 [34:54<2:06:16,  1.08it/s][NeMo W 2026-06-19 07:44:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 22%|██▏       | 2313/10519 [34:55<2:06:15,  1.08it/s][NeMo W 2026-06-19 07:44:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 22%|██▏       | 2314/10519 [34:56<2:11:06,  1.04it/s][NeMo W 2026-06-19 07:44:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 22%|██▏       | 2315/10519 [34:57<2:12:14,  1.03it/s][NeMo W 2026-06-19 07:44:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.44it/s]
 22%|██▏       | 2316/10519 [34:58<2:07:39,  1.07it/s][NeMo W 2026-06-19 07:44:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 22%|██▏       | 2317/10519 [34:59<2:09:41,  1.05it/s][NeMo W 2026-06-19 07:44:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 22%|██▏       | 2318/10519 [35:00<2:10:31,  1.05it/s][NeMo W 2026-06-19 07:44:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 22%|██▏       | 2319/10519 [35:01<2:11:06,  1.04it/s][NeMo W 2026-06-19 07:44:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 22%|██▏       | 2320/10519 [35:02<2:11:07,  1.04it/s][NeMo W 2026-06-19 07:44:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 22%|██▏       | 2321/10519 [35:02<2:03:25,  1.11it/s][NeMo W 2026-06-19 07:44:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 22%|██▏       | 2322/10519 [35:03<2:04:31,  1.10it/s][NeMo W 2026-06-19 07:44:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 22%|██▏       | 2323/10519 [35:04<1:58:02,  1.16it/s][NeMo W 2026-06-19 07:44:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 22%|██▏       | 2324/10519 [35:05<1:59:52,  1.14it/s][NeMo W 2026-06-19 07:44:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 22%|██▏       | 2325/10519 [35:06<1:59:57,  1.14it/s][NeMo W 2026-06-19 07:44:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 22%|██▏       | 2326/10519 [35:07<2:02:32,  1.11it/s][NeMo W 2026-06-19 07:44:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 22%|██▏       | 2327/10519 [35:08<1:57:22,  1.16it/s][NeMo W 2026-06-19 07:44:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 22%|██▏       | 2328/10519 [35:09<2:03:12,  1.11it/s][NeMo W 2026-06-19 07:44:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 22%|██▏       | 2329/10519 [35:10<2:13:01,  1.03it/s][NeMo W 2026-06-19 07:44:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:44:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]

Checkpoint saved: 2350 samples

[NeMo W 2026-06-19 07:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 22%|██▏       | 2351/10519 [35:32<2:28:13,  1.09s/it][NeMo W 2026-06-19 07:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 22%|██▏       | 2352/10519 [35:33<2:22:56,  1.05s/it][NeMo W 2026-06-19 07:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 22%|██▏       | 2353/10519 [35:34<2:18:30,  1.02s/it][NeMo W 2026-06-19 07:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.81it/s]
 22%|██▏       | 2354/10519 [35:35<2:18:04,  1.01s/it][NeMo W 2026-06-19 07:45:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 22%|██▏       | 2355/10519 [35:36<2:22:39,  1.05s/it][NeMo W 2026-06-19 07:45:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 22%|██▏       | 2356/10519 [35:37<2:10:11,  1.04it/s][NeMo W 2026-06-19 07:45:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 22%|██▏       | 2357/10519 [35:37<2:00:40,  1.13it/s][NeMo W 2026-06-19 07:45:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.96it/s]
 22%|██▏       | 2358/10519 [35:38<2:03:01,  1.11it/s][NeMo W 2026-06-19 07:45:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 22%|██▏       | 2359/10519 [35:39<2:05:17,  1.09it/s][NeMo W 2026-06-19 07:45:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 22%|██▏       | 2360/10519 [35:40<1:57:00,  1.16it/s][NeMo W 2026-06-19 07:45:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 22%|██▏       | 2361/10519 [35:41<2:03:34,  1.10it/s][NeMo W 2026-06-19 07:45:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 22%|██▏       | 2362/10519 [35:42<2:06:44,  1.07it/s][NeMo W 2026-06-19 07:45:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 22%|██▏       | 2363/10519 [35:43<2:11:26,  1.03it/s][NeMo W 2026-06-19 07:45:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 22%|██▏       | 2364/10519 [35:44<2:10:08,  1.04it/s][NeMo W 2026-06-19 07:45:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 22%|██▏       | 2365/10519 [35:47<3:22:45,  1.49s/it][NeMo W 2026-06-19 07:45:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 22%|██▏       | 2366/10519 [35:48<3:02:29,  1.34s/it][NeMo W 2026-06-19 07:45:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.19it/s]
 23%|██▎       | 2367/10519 [35:49<2:45:36,  1.22s/it][NeMo W 2026-06-19 07:45:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 23%|██▎       | 2368/10519 [35:49<2:34:42,  1.14s/it][NeMo W 2026-06-19 07:45:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 23%|██▎       | 2369/10519 [35:50<2:27:44,  1.09s/it][NeMo W 2026-06-19 07:45:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 23%|██▎       | 2370/10519 [35:51<2:19:54,  1.03s/it][NeMo W 2026-06-19 07:45:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 23%|██▎       | 2371/10519 [35:52<2:18:18,  1.02s/it][NeMo W 2026-06-19 07:45:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 23%|██▎       | 2372/10519 [35:53<2:13:50,  1.01it/s][NeMo W 2026-06-19 07:45:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 23%|██▎       | 2373/10519 [35:54<2:09:15,  1.05it/s][NeMo W 2026-06-19 07:45:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 23%|██▎       | 2374/10519 [35:55<2:11:42,  1.03it/s][NeMo W 2026-06-19 07:45:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 23%|██▎       | 2375/10519 [35:56<2:01:48,  1.11it/s][NeMo W 2026-06-19 07:45:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]
 23%|██▎       | 2376/10519 [35:57<1:54:45,  1.18it/s][NeMo W 2026-06-19 07:45:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 23%|██▎       | 2377/10519 [35:58<1:59:14,  1.14it/s][NeMo W 2026-06-19 07:45:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 23%|██▎       | 2378/10519 [35:58<1:58:19,  1.15it/s][NeMo W 2026-06-19 07:45:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.35it/s]
 23%|██▎       | 2379/10519 [36:00<2:08:11,  1.06it/s][NeMo W 2026-06-19 07:45:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:45:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 2400 samples

[NeMo W 2026-06-19 07:46:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 23%|██▎       | 2401/10519 [36:22<2:26:49,  1.09s/it][NeMo W 2026-06-19 07:46:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 23%|██▎       | 2402/10519 [36:23<2:27:18,  1.09s/it][NeMo W 2026-06-19 07:46:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 23%|██▎       | 2403/10519 [36:24<2:23:55,  1.06s/it][NeMo W 2026-06-19 07:46:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.52it/s]
 23%|██▎       | 2404/10519 [36:25<2:20:23,  1.04s/it][NeMo W 2026-06-19 07:46:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 23%|██▎       | 2405/10519 [36:26<2:17:09,  1.01s/it][NeMo W 2026-06-19 07:46:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 23%|██▎       | 2406/10519 [36:27<2:14:08,  1.01it/s][NeMo W 2026-06-19 07:46:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 23%|██▎       | 2407/10519 [36:28<2:14:58,  1.00it/s][NeMo W 2026-06-19 07:46:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 23%|██▎       | 2408/10519 [36:29<2:13:44,  1.01it/s][NeMo W 2026-06-19 07:46:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 23%|██▎       | 2409/10519 [36:30<2:11:36,  1.03it/s][NeMo W 2026-06-19 07:46:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 23%|██▎       | 2410/10519 [36:31<2:11:35,  1.03it/s][NeMo W 2026-06-19 07:46:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 23%|██▎       | 2411/10519 [36:32<2:11:05,  1.03it/s][NeMo W 2026-06-19 07:46:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 23%|██▎       | 2412/10519 [36:33<2:08:07,  1.05it/s][NeMo W 2026-06-19 07:46:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 23%|██▎       | 2413/10519 [36:34<2:06:49,  1.07it/s][NeMo W 2026-06-19 07:46:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 23%|██▎       | 2414/10519 [36:35<2:06:48,  1.07it/s][NeMo W 2026-06-19 07:46:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.22it/s]
 23%|██▎       | 2415/10519 [36:36<1:59:20,  1.13it/s][NeMo W 2026-06-19 07:46:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 23%|██▎       | 2416/10519 [36:37<2:00:24,  1.12it/s][NeMo W 2026-06-19 07:46:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 23%|██▎       | 2417/10519 [36:38<2:03:30,  1.09it/s][NeMo W 2026-06-19 07:46:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 23%|██▎       | 2418/10519 [36:39<2:05:07,  1.08it/s][NeMo W 2026-06-19 07:46:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 23%|██▎       | 2419/10519 [36:40<2:06:32,  1.07it/s][NeMo W 2026-06-19 07:46:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 23%|██▎       | 2420/10519 [36:40<2:08:48,  1.05it/s][NeMo W 2026-06-19 07:46:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 23%|██▎       | 2421/10519 [36:41<2:07:45,  1.06it/s][NeMo W 2026-06-19 07:46:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 23%|██▎       | 2422/10519 [36:42<2:09:44,  1.04it/s][NeMo W 2026-06-19 07:46:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 23%|██▎       | 2423/10519 [36:43<2:10:40,  1.03it/s][NeMo W 2026-06-19 07:46:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 23%|██▎       | 2424/10519 [36:44<2:04:04,  1.09it/s][NeMo W 2026-06-19 07:46:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 23%|██▎       | 2425/10519 [36:45<2:02:44,  1.10it/s][NeMo W 2026-06-19 07:46:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]
 23%|██▎       | 2426/10519 [36:46<2:04:33,  1.08it/s][NeMo W 2026-06-19 07:46:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 23%|██▎       | 2427/10519 [36:47<2:09:27,  1.04it/s][NeMo W 2026-06-19 07:46:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 23%|██▎       | 2428/10519 [36:48<2:07:49,  1.05it/s][NeMo W 2026-06-19 07:46:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 23%|██▎       | 2429/10519 [36:49<2:09:26,  1.04it/s][NeMo W 2026-06-19 07:46:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]

Checkpoint saved: 2450 samples

[NeMo W 2026-06-19 07:46:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 23%|██▎       | 2451/10519 [37:10<2:24:41,  1.08s/it][NeMo W 2026-06-19 07:46:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 23%|██▎       | 2452/10519 [37:11<2:11:33,  1.02it/s][NeMo W 2026-06-19 07:46:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 23%|██▎       | 2453/10519 [37:12<2:02:47,  1.09it/s][NeMo W 2026-06-19 07:46:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.66it/s]
 23%|██▎       | 2454/10519 [37:13<2:13:13,  1.01it/s][NeMo W 2026-06-19 07:46:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 23%|██▎       | 2455/10519 [37:14<2:11:34,  1.02it/s][NeMo W 2026-06-19 07:46:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 23%|██▎       | 2456/10519 [37:15<2:11:02,  1.03it/s][NeMo W 2026-06-19 07:46:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 23%|██▎       | 2457/10519 [37:16<2:19:05,  1.04s/it][NeMo W 2026-06-19 07:46:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 23%|██▎       | 2458/10519 [37:17<2:13:28,  1.01it/s][NeMo W 2026-06-19 07:46:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 23%|██▎       | 2459/10519 [37:18<2:03:31,  1.09it/s][NeMo W 2026-06-19 07:46:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:46:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 23%|██▎       | 2460/10519 [37:19<2:05:29,  1.07it/s][NeMo W 2026-06-19 07:47:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 23%|██▎       | 2461/10519 [37:19<2:04:53,  1.08it/s][NeMo W 2026-06-19 07:47:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 23%|██▎       | 2462/10519 [37:20<2:07:27,  1.05it/s][NeMo W 2026-06-19 07:47:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 23%|██▎       | 2463/10519 [37:21<2:01:39,  1.10it/s][NeMo W 2026-06-19 07:47:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 23%|██▎       | 2464/10519 [37:22<1:58:20,  1.13it/s][NeMo W 2026-06-19 07:47:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 23%|██▎       | 2465/10519 [37:23<2:01:53,  1.10it/s][NeMo W 2026-06-19 07:47:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 23%|██▎       | 2466/10519 [37:24<2:04:33,  1.08it/s][NeMo W 2026-06-19 07:47:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 23%|██▎       | 2467/10519 [37:25<2:04:00,  1.08it/s][NeMo W 2026-06-19 07:47:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 23%|██▎       | 2468/10519 [37:26<2:05:06,  1.07it/s][NeMo W 2026-06-19 07:47:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 23%|██▎       | 2469/10519 [37:27<2:08:59,  1.04it/s][NeMo W 2026-06-19 07:47:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 23%|██▎       | 2470/10519 [37:28<2:10:40,  1.03it/s][NeMo W 2026-06-19 07:47:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.64it/s]
 23%|██▎       | 2471/10519 [37:29<2:10:43,  1.03it/s][NeMo W 2026-06-19 07:47:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 24%|██▎       | 2472/10519 [37:30<2:09:20,  1.04it/s][NeMo W 2026-06-19 07:47:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 24%|██▎       | 2473/10519 [37:31<2:09:55,  1.03it/s][NeMo W 2026-06-19 07:47:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 24%|██▎       | 2474/10519 [37:32<2:07:02,  1.06it/s][NeMo W 2026-06-19 07:47:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 24%|██▎       | 2475/10519 [37:33<2:08:21,  1.04it/s][NeMo W 2026-06-19 07:47:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 24%|██▎       | 2476/10519 [37:34<2:10:35,  1.03it/s][NeMo W 2026-06-19 07:47:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 24%|██▎       | 2477/10519 [37:35<2:03:24,  1.09it/s][NeMo W 2026-06-19 07:47:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 24%|██▎       | 2478/10519 [37:35<2:05:33,  1.07it/s][NeMo W 2026-06-19 07:47:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.22it/s]
 24%|██▎       | 2479/10519 [37:36<2:05:17,  1.07it/s][NeMo W 2026-06-19 07:47:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]

Checkpoint saved: 2500 samples

[NeMo W 2026-06-19 07:47:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 24%|██▍       | 2501/10519 [37:58<2:19:54,  1.05s/it][NeMo W 2026-06-19 07:47:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 24%|██▍       | 2502/10519 [37:59<2:18:21,  1.04s/it][NeMo W 2026-06-19 07:47:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 24%|██▍       | 2503/10519 [38:00<2:24:24,  1.08s/it][NeMo W 2026-06-19 07:47:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 24%|██▍       | 2504/10519 [38:01<2:19:01,  1.04s/it][NeMo W 2026-06-19 07:47:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 24%|██▍       | 2505/10519 [38:02<2:16:59,  1.03s/it][NeMo W 2026-06-19 07:47:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 24%|██▍       | 2506/10519 [38:03<2:08:28,  1.04it/s][NeMo W 2026-06-19 07:47:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 24%|██▍       | 2507/10519 [38:04<2:18:27,  1.04s/it][NeMo W 2026-06-19 07:47:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.27it/s]
 24%|██▍       | 2508/10519 [38:05<2:20:50,  1.05s/it][NeMo W 2026-06-19 07:47:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 24%|██▍       | 2509/10519 [38:06<2:11:07,  1.02it/s][NeMo W 2026-06-19 07:47:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.08it/s]
 24%|██▍       | 2510/10519 [38:07<2:13:39,  1.00s/it][NeMo W 2026-06-19 07:47:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 24%|██▍       | 2511/10519 [38:08<2:03:17,  1.08it/s][NeMo W 2026-06-19 07:47:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 24%|██▍       | 2512/10519 [38:09<2:10:49,  1.02it/s][NeMo W 2026-06-19 07:47:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 24%|██▍       | 2513/10519 [38:10<2:11:45,  1.01it/s][NeMo W 2026-06-19 07:47:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 24%|██▍       | 2514/10519 [38:11<2:09:13,  1.03it/s][NeMo W 2026-06-19 07:47:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 24%|██▍       | 2515/10519 [38:12<2:00:24,  1.11it/s][NeMo W 2026-06-19 07:47:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 24%|██▍       | 2516/10519 [38:13<2:14:38,  1.01s/it][NeMo W 2026-06-19 07:47:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.60it/s]
 24%|██▍       | 2517/10519 [38:14<2:15:39,  1.02s/it][NeMo W 2026-06-19 07:47:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 24%|██▍       | 2518/10519 [38:15<2:08:02,  1.04it/s][NeMo W 2026-06-19 07:47:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
 24%|██▍       | 2519/10519 [38:16<2:06:33,  1.05it/s][NeMo W 2026-06-19 07:47:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 24%|██▍       | 2520/10519 [38:17<2:10:06,  1.02it/s][NeMo W 2026-06-19 07:47:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 24%|██▍       | 2521/10519 [38:18<2:01:59,  1.09it/s][NeMo W 2026-06-19 07:47:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:47:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 24%|██▍       | 2522/10519 [38:18<2:04:11,  1.07it/s][NeMo W 2026-06-19 07:48:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 24%|██▍       | 2523/10519 [38:19<1:59:33,  1.11it/s][NeMo W 2026-06-19 07:48:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 24%|██▍       | 2524/10519 [38:20<2:01:02,  1.10it/s][NeMo W 2026-06-19 07:48:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 24%|██▍       | 2525/10519 [38:22<2:30:31,  1.13s/it][NeMo W 2026-06-19 07:48:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 24%|██▍       | 2526/10519 [38:23<2:14:34,  1.01s/it][NeMo W 2026-06-19 07:48:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 24%|██▍       | 2527/10519 [38:23<2:07:19,  1.05it/s][NeMo W 2026-06-19 07:48:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.52it/s]
 24%|██▍       | 2528/10519 [38:24<2:10:45,  1.02it/s][NeMo W 2026-06-19 07:48:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 24%|██▍       | 2529/10519 [38:25<2:12:02,  1.01it/s][NeMo W 2026-06-19 07:48:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]

Checkpoint saved: 2550 samples

[NeMo W 2026-06-19 07:48:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 24%|██▍       | 2551/10519 [38:47<2:22:36,  1.07s/it][NeMo W 2026-06-19 07:48:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 24%|██▍       | 2552/10519 [38:48<2:11:40,  1.01it/s][NeMo W 2026-06-19 07:48:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 24%|██▍       | 2553/10519 [38:49<2:01:00,  1.10it/s][NeMo W 2026-06-19 07:48:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 24%|██▍       | 2554/10519 [38:50<2:03:16,  1.08it/s][NeMo W 2026-06-19 07:48:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 24%|██▍       | 2555/10519 [38:51<2:04:16,  1.07it/s][NeMo W 2026-06-19 07:48:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 24%|██▍       | 2556/10519 [38:52<2:05:10,  1.06it/s][NeMo W 2026-06-19 07:48:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.33it/s]
 24%|██▍       | 2557/10519 [38:53<2:14:08,  1.01s/it][NeMo W 2026-06-19 07:48:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 24%|██▍       | 2558/10519 [38:54<2:12:35,  1.00it/s][NeMo W 2026-06-19 07:48:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 24%|██▍       | 2559/10519 [38:55<2:14:53,  1.02s/it][NeMo W 2026-06-19 07:48:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 24%|██▍       | 2560/10519 [38:56<2:12:08,  1.00it/s][NeMo W 2026-06-19 07:48:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 24%|██▍       | 2561/10519 [38:57<2:14:02,  1.01s/it][NeMo W 2026-06-19 07:48:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.07it/s]
 24%|██▍       | 2562/10519 [38:58<2:17:00,  1.03s/it][NeMo W 2026-06-19 07:48:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 24%|██▍       | 2563/10519 [38:59<2:13:28,  1.01s/it][NeMo W 2026-06-19 07:48:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 24%|██▍       | 2564/10519 [39:00<2:07:28,  1.04it/s][NeMo W 2026-06-19 07:48:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
 24%|██▍       | 2565/10519 [39:00<1:58:56,  1.11it/s][NeMo W 2026-06-19 07:48:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.57it/s]
 24%|██▍       | 2566/10519 [39:01<2:00:44,  1.10it/s][NeMo W 2026-06-19 07:48:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 24%|██▍       | 2567/10519 [39:02<2:04:43,  1.06it/s][NeMo W 2026-06-19 07:48:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 24%|██▍       | 2568/10519 [39:03<2:02:43,  1.08it/s][NeMo W 2026-06-19 07:48:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 24%|██▍       | 2569/10519 [39:04<2:05:02,  1.06it/s][NeMo W 2026-06-19 07:48:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 24%|██▍       | 2570/10519 [39:05<2:05:58,  1.05it/s][NeMo W 2026-06-19 07:48:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 24%|██▍       | 2571/10519 [39:06<2:06:41,  1.05it/s][NeMo W 2026-06-19 07:48:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 24%|██▍       | 2572/10519 [39:07<2:06:58,  1.04it/s][NeMo W 2026-06-19 07:48:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 24%|██▍       | 2573/10519 [39:08<2:12:14,  1.00it/s][NeMo W 2026-06-19 07:48:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 24%|██▍       | 2574/10519 [39:09<2:11:07,  1.01it/s][NeMo W 2026-06-19 07:48:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 24%|██▍       | 2575/10519 [39:10<2:14:55,  1.02s/it][NeMo W 2026-06-19 07:48:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 24%|██▍       | 2576/10519 [39:11<2:11:58,  1.00it/s][NeMo W 2026-06-19 07:48:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.43it/s]
 24%|██▍       | 2577/10519 [39:12<2:10:53,  1.01it/s][NeMo W 2026-06-19 07:48:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 25%|██▍       | 2578/10519 [39:13<2:12:34,  1.00s/it][NeMo W 2026-06-19 07:48:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.50it/s]
 25%|██▍       | 2579/10519 [39:14<2:13:38,  1.01s/it][NeMo W 2026-06-19 07:48:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:48:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 2600 samples

[NeMo W 2026-06-19 07:49:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 25%|██▍       | 2601/10519 [39:36<2:25:44,  1.10s/it][NeMo W 2026-06-19 07:49:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 25%|██▍       | 2602/10519 [39:37<2:18:22,  1.05s/it][NeMo W 2026-06-19 07:49:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 25%|██▍       | 2603/10519 [39:38<2:05:19,  1.05it/s][NeMo W 2026-06-19 07:49:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 25%|██▍       | 2604/10519 [39:39<2:05:36,  1.05it/s][NeMo W 2026-06-19 07:49:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.70it/s]
 25%|██▍       | 2605/10519 [39:40<2:11:51,  1.00it/s][NeMo W 2026-06-19 07:49:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 25%|██▍       | 2606/10519 [39:41<2:10:18,  1.01it/s][NeMo W 2026-06-19 07:49:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 25%|██▍       | 2607/10519 [39:42<2:06:22,  1.04it/s][NeMo W 2026-06-19 07:49:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 25%|██▍       | 2608/10519 [39:43<1:58:57,  1.11it/s][NeMo W 2026-06-19 07:49:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 25%|██▍       | 2609/10519 [39:44<2:01:01,  1.09it/s][NeMo W 2026-06-19 07:49:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 25%|██▍       | 2610/10519 [39:45<2:00:15,  1.10it/s][NeMo W 2026-06-19 07:49:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 25%|██▍       | 2611/10519 [39:46<2:04:14,  1.06it/s][NeMo W 2026-06-19 07:49:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 25%|██▍       | 2612/10519 [39:46<2:04:18,  1.06it/s][NeMo W 2026-06-19 07:49:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 25%|██▍       | 2613/10519 [39:48<2:09:24,  1.02it/s][NeMo W 2026-06-19 07:49:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 25%|██▍       | 2614/10519 [39:49<2:09:58,  1.01it/s][NeMo W 2026-06-19 07:49:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 25%|██▍       | 2615/10519 [39:50<2:09:51,  1.01it/s][NeMo W 2026-06-19 07:49:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 25%|██▍       | 2616/10519 [39:51<2:10:11,  1.01it/s][NeMo W 2026-06-19 07:49:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
 25%|██▍       | 2617/10519 [39:51<2:08:15,  1.03it/s][NeMo W 2026-06-19 07:49:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 25%|██▍       | 2618/10519 [39:52<2:10:22,  1.01it/s][NeMo W 2026-06-19 07:49:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 25%|██▍       | 2619/10519 [39:53<2:08:48,  1.02it/s][NeMo W 2026-06-19 07:49:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 25%|██▍       | 2620/10519 [39:54<2:07:03,  1.04it/s][NeMo W 2026-06-19 07:49:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 25%|██▍       | 2621/10519 [39:55<2:11:17,  1.00it/s][NeMo W 2026-06-19 07:49:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 25%|██▍       | 2622/10519 [39:56<2:00:06,  1.10it/s][NeMo W 2026-06-19 07:49:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 25%|██▍       | 2623/10519 [39:57<2:03:30,  1.07it/s][NeMo W 2026-06-19 07:49:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 25%|██▍       | 2624/10519 [39:58<2:05:12,  1.05it/s][NeMo W 2026-06-19 07:49:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 25%|██▍       | 2625/10519 [39:59<1:57:15,  1.12it/s][NeMo W 2026-06-19 07:49:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 25%|██▍       | 2626/10519 [40:00<2:01:42,  1.08it/s][NeMo W 2026-06-19 07:49:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 25%|██▍       | 2627/10519 [40:01<2:06:51,  1.04it/s][NeMo W 2026-06-19 07:49:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 25%|██▍       | 2628/10519 [40:02<2:07:11,  1.03it/s][NeMo W 2026-06-19 07:49:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 25%|██▍       | 2629/10519 [40:03<2:06:13,  1.04it/s][NeMo W 2026-06-19 07:49:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:49:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]

Checkpoint saved: 2650 samples

[NeMo W 2026-06-19 07:50:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 25%|██▌       | 2651/10519 [40:25<2:18:38,  1.06s/it][NeMo W 2026-06-19 07:50:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.11it/s]
 25%|██▌       | 2652/10519 [40:26<2:20:11,  1.07s/it][NeMo W 2026-06-19 07:50:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 25%|██▌       | 2653/10519 [40:26<2:11:18,  1.00s/it][NeMo W 2026-06-19 07:50:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 25%|██▌       | 2654/10519 [40:27<2:11:03,  1.00it/s][NeMo W 2026-06-19 07:50:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 25%|██▌       | 2655/10519 [40:28<2:08:42,  1.02it/s][NeMo W 2026-06-19 07:50:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 25%|██▌       | 2656/10519 [40:29<2:07:13,  1.03it/s][NeMo W 2026-06-19 07:50:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 25%|██▌       | 2657/10519 [40:30<2:06:46,  1.03it/s][NeMo W 2026-06-19 07:50:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 25%|██▌       | 2658/10519 [40:31<2:05:07,  1.05it/s][NeMo W 2026-06-19 07:50:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 25%|██▌       | 2659/10519 [40:32<2:04:30,  1.05it/s][NeMo W 2026-06-19 07:50:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 25%|██▌       | 2660/10519 [40:33<1:57:04,  1.12it/s][NeMo W 2026-06-19 07:50:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 25%|██▌       | 2661/10519 [40:34<2:10:33,  1.00it/s][NeMo W 2026-06-19 07:50:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 25%|██▌       | 2662/10519 [40:35<2:08:47,  1.02it/s][NeMo W 2026-06-19 07:50:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.81it/s]
 25%|██▌       | 2663/10519 [40:36<2:07:38,  1.03it/s][NeMo W 2026-06-19 07:50:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 25%|██▌       | 2664/10519 [40:37<1:58:42,  1.10it/s][NeMo W 2026-06-19 07:50:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 25%|██▌       | 2665/10519 [40:38<2:04:11,  1.05it/s][NeMo W 2026-06-19 07:50:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 25%|██▌       | 2666/10519 [40:39<2:05:58,  1.04it/s][NeMo W 2026-06-19 07:50:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.04it/s]
 25%|██▌       | 2667/10519 [40:40<2:05:32,  1.04it/s][NeMo W 2026-06-19 07:50:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 25%|██▌       | 2668/10519 [40:41<2:04:31,  1.05it/s][NeMo W 2026-06-19 07:50:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 25%|██▌       | 2669/10519 [40:42<2:05:53,  1.04it/s][NeMo W 2026-06-19 07:50:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 25%|██▌       | 2670/10519 [40:43<2:07:44,  1.02it/s][NeMo W 2026-06-19 07:50:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 25%|██▌       | 2671/10519 [40:43<1:55:12,  1.14it/s][NeMo W 2026-06-19 07:50:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 25%|██▌       | 2672/10519 [40:44<2:00:57,  1.08it/s][NeMo W 2026-06-19 07:50:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 25%|██▌       | 2673/10519 [40:45<2:01:18,  1.08it/s][NeMo W 2026-06-19 07:50:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 25%|██▌       | 2674/10519 [40:46<1:55:17,  1.13it/s][NeMo W 2026-06-19 07:50:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 25%|██▌       | 2675/10519 [40:47<1:56:15,  1.12it/s][NeMo W 2026-06-19 07:50:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 25%|██▌       | 2676/10519 [40:48<1:51:09,  1.18it/s][NeMo W 2026-06-19 07:50:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 25%|██▌       | 2677/10519 [40:49<1:54:40,  1.14it/s][NeMo W 2026-06-19 07:50:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
 25%|██▌       | 2678/10519 [40:50<1:59:23,  1.09it/s][NeMo W 2026-06-19 07:50:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.08it/s]
 25%|██▌       | 2679/10519 [40:51<1:55:11,  1.13it/s][NeMo W 2026-06-19 07:50:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.17it/s]
 25%|██▌       | 2680/10519 [40:52<1:57:49,  1.11it/s][NeMo W 2026-06-19 07:50:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 2700 samples

[NeMo W 2026-06-19 07:50:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 26%|██▌       | 2701/10519 [41:11<2:07:37,  1.02it/s][NeMo W 2026-06-19 07:50:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 26%|██▌       | 2702/10519 [41:12<1:59:21,  1.09it/s][NeMo W 2026-06-19 07:50:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 26%|██▌       | 2703/10519 [41:13<1:59:51,  1.09it/s][NeMo W 2026-06-19 07:50:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 26%|██▌       | 2704/10519 [41:14<2:05:57,  1.03it/s][NeMo W 2026-06-19 07:50:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.33it/s]
 26%|██▌       | 2705/10519 [41:15<2:07:42,  1.02it/s][NeMo W 2026-06-19 07:50:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 26%|██▌       | 2706/10519 [41:16<2:07:13,  1.02it/s][NeMo W 2026-06-19 07:50:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 26%|██▌       | 2707/10519 [41:17<2:09:53,  1.00it/s][NeMo W 2026-06-19 07:50:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:50:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 26%|██▌       | 2708/10519 [41:18<2:10:08,  1.00it/s][NeMo W 2026-06-19 07:51:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 26%|██▌       | 2709/10519 [41:19<2:07:10,  1.02it/s][NeMo W 2026-06-19 07:51:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 26%|██▌       | 2710/10519 [41:20<2:00:39,  1.08it/s][NeMo W 2026-06-19 07:51:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 26%|██▌       | 2711/10519 [41:21<1:55:14,  1.13it/s][NeMo W 2026-06-19 07:51:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.16it/s]
 26%|██▌       | 2712/10519 [41:22<1:54:03,  1.14it/s][NeMo W 2026-06-19 07:51:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.11it/s]
 26%|██▌       | 2713/10519 [41:23<2:02:17,  1.06it/s][NeMo W 2026-06-19 07:51:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.18it/s]
 26%|██▌       | 2714/10519 [41:24<2:03:41,  1.05it/s][NeMo W 2026-06-19 07:51:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 26%|██▌       | 2715/10519 [41:24<1:55:15,  1.13it/s][NeMo W 2026-06-19 07:51:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
 26%|██▌       | 2716/10519 [41:25<1:57:28,  1.11it/s][NeMo W 2026-06-19 07:51:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 26%|██▌       | 2717/10519 [41:26<1:58:20,  1.10it/s][NeMo W 2026-06-19 07:51:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 26%|██▌       | 2718/10519 [41:27<2:00:12,  1.08it/s][NeMo W 2026-06-19 07:51:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.74it/s]
 26%|██▌       | 2719/10519 [41:28<2:02:16,  1.06it/s][NeMo W 2026-06-19 07:51:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 26%|██▌       | 2720/10519 [41:29<2:05:15,  1.04it/s][NeMo W 2026-06-19 07:51:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.96it/s]
 26%|██▌       | 2721/10519 [41:30<2:06:52,  1.02it/s][NeMo W 2026-06-19 07:51:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 26%|██▌       | 2722/10519 [41:31<2:05:20,  1.04it/s][NeMo W 2026-06-19 07:51:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 26%|██▌       | 2723/10519 [41:32<2:04:27,  1.04it/s][NeMo W 2026-06-19 07:51:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 26%|██▌       | 2724/10519 [41:33<2:04:19,  1.05it/s][NeMo W 2026-06-19 07:51:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 26%|██▌       | 2725/10519 [41:38<4:35:48,  2.12s/it][NeMo W 2026-06-19 07:51:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.97it/s]
 26%|██▌       | 2726/10519 [41:39<3:51:20,  1.78s/it][NeMo W 2026-06-19 07:51:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 26%|██▌       | 2727/10519 [41:40<3:20:01,  1.54s/it][NeMo W 2026-06-19 07:51:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 26%|██▌       | 2728/10519 [41:41<2:56:23,  1.36s/it][NeMo W 2026-06-19 07:51:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 26%|██▌       | 2729/10519 [41:42<2:40:17,  1.23s/it][NeMo W 2026-06-19 07:51:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.97it/s]

Checkpoint saved: 2750 samples

[NeMo W 2026-06-19 07:51:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 26%|██▌       | 2751/10519 [42:05<2:40:24,  1.24s/it][NeMo W 2026-06-19 07:51:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.90it/s]
 26%|██▌       | 2752/10519 [42:06<2:25:06,  1.12s/it][NeMo W 2026-06-19 07:51:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 26%|██▌       | 2753/10519 [42:07<2:19:15,  1.08s/it][NeMo W 2026-06-19 07:51:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.38it/s]
 26%|██▌       | 2754/10519 [42:08<2:17:08,  1.06s/it][NeMo W 2026-06-19 07:51:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 26%|██▌       | 2755/10519 [42:09<2:11:12,  1.01s/it][NeMo W 2026-06-19 07:51:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 26%|██▌       | 2756/10519 [42:10<2:13:54,  1.04s/it][NeMo W 2026-06-19 07:51:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 26%|██▌       | 2757/10519 [42:11<2:10:27,  1.01s/it][NeMo W 2026-06-19 07:51:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 26%|██▌       | 2758/10519 [42:12<2:07:56,  1.01it/s][NeMo W 2026-06-19 07:51:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 26%|██▌       | 2759/10519 [42:13<1:59:45,  1.08it/s][NeMo W 2026-06-19 07:51:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 26%|██▌       | 2760/10519 [42:14<2:01:18,  1.07it/s][NeMo W 2026-06-19 07:51:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 26%|██▌       | 2761/10519 [42:15<2:06:00,  1.03it/s][NeMo W 2026-06-19 07:51:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 26%|██▋       | 2762/10519 [42:16<2:05:06,  1.03it/s][NeMo W 2026-06-19 07:51:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 26%|██▋       | 2763/10519 [42:17<2:04:46,  1.04it/s][NeMo W 2026-06-19 07:51:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 26%|██▋       | 2764/10519 [42:18<2:05:53,  1.03it/s][NeMo W 2026-06-19 07:51:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:51:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 26%|██▋       | 2765/10519 [42:18<1:57:31,  1.10it/s][NeMo W 2026-06-19 07:52:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 26%|██▋       | 2766/10519 [42:19<2:07:01,  1.02it/s][NeMo W 2026-06-19 07:52:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 26%|██▋       | 2767/10519 [42:21<2:10:28,  1.01s/it][NeMo W 2026-06-19 07:52:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 26%|██▋       | 2768/10519 [42:22<2:13:14,  1.03s/it][NeMo W 2026-06-19 07:52:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 26%|██▋       | 2769/10519 [42:23<2:10:13,  1.01s/it][NeMo W 2026-06-19 07:52:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 26%|██▋       | 2770/10519 [42:24<2:14:38,  1.04s/it][NeMo W 2026-06-19 07:52:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 26%|██▋       | 2771/10519 [42:25<2:09:52,  1.01s/it][NeMo W 2026-06-19 07:52:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 26%|██▋       | 2772/10519 [42:25<2:01:17,  1.06it/s][NeMo W 2026-06-19 07:52:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 26%|██▋       | 2773/10519 [42:26<2:03:20,  1.05it/s][NeMo W 2026-06-19 07:52:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
 26%|██▋       | 2774/10519 [42:27<2:02:51,  1.05it/s][NeMo W 2026-06-19 07:52:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 26%|██▋       | 2775/10519 [42:28<2:11:34,  1.02s/it][NeMo W 2026-06-19 07:52:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 26%|██▋       | 2776/10519 [42:30<2:13:02,  1.03s/it][NeMo W 2026-06-19 07:52:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.77it/s]
 26%|██▋       | 2777/10519 [42:30<2:09:14,  1.00s/it][NeMo W 2026-06-19 07:52:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 26%|██▋       | 2778/10519 [42:31<2:08:01,  1.01it/s][NeMo W 2026-06-19 07:52:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 26%|██▋       | 2779/10519 [42:32<2:00:28,  1.07it/s][NeMo W 2026-06-19 07:52:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]

Checkpoint saved: 2800 samples

[NeMo W 2026-06-19 07:52:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 27%|██▋       | 2801/10519 [42:56<2:57:13,  1.38s/it][NeMo W 2026-06-19 07:52:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 27%|██▋       | 2802/10519 [42:57<2:39:39,  1.24s/it][NeMo W 2026-06-19 07:52:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 27%|██▋       | 2803/10519 [42:58<2:32:50,  1.19s/it][NeMo W 2026-06-19 07:52:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.89it/s]
 27%|██▋       | 2804/10519 [42:59<2:28:07,  1.15s/it][NeMo W 2026-06-19 07:52:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 27%|██▋       | 2805/10519 [43:00<2:31:25,  1.18s/it][NeMo W 2026-06-19 07:52:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 27%|██▋       | 2806/10519 [43:01<2:22:58,  1.11s/it][NeMo W 2026-06-19 07:52:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 27%|██▋       | 2807/10519 [43:02<2:17:51,  1.07s/it][NeMo W 2026-06-19 07:52:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
 27%|██▋       | 2808/10519 [43:03<2:10:42,  1.02s/it][NeMo W 2026-06-19 07:52:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 27%|██▋       | 2809/10519 [43:04<2:13:05,  1.04s/it][NeMo W 2026-06-19 07:52:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 27%|██▋       | 2810/10519 [43:05<2:09:47,  1.01s/it][NeMo W 2026-06-19 07:52:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 27%|██▋       | 2811/10519 [43:06<2:09:34,  1.01s/it][NeMo W 2026-06-19 07:52:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 27%|██▋       | 2812/10519 [43:07<2:10:49,  1.02s/it][NeMo W 2026-06-19 07:52:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
 27%|██▋       | 2813/10519 [43:08<2:09:21,  1.01s/it][NeMo W 2026-06-19 07:52:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 27%|██▋       | 2814/10519 [43:09<2:09:01,  1.00s/it][NeMo W 2026-06-19 07:52:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 27%|██▋       | 2815/10519 [43:10<2:10:10,  1.01s/it][NeMo W 2026-06-19 07:52:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.49it/s]
 27%|██▋       | 2816/10519 [43:11<2:13:12,  1.04s/it][NeMo W 2026-06-19 07:52:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]
 27%|██▋       | 2817/10519 [43:12<2:05:49,  1.02it/s][NeMo W 2026-06-19 07:52:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.91it/s]
 27%|██▋       | 2818/10519 [43:13<1:57:49,  1.09it/s][NeMo W 2026-06-19 07:52:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 27%|██▋       | 2819/10519 [43:14<1:59:41,  1.07it/s][NeMo W 2026-06-19 07:52:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 27%|██▋       | 2820/10519 [43:15<2:00:03,  1.07it/s][NeMo W 2026-06-19 07:52:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.23it/s]
 27%|██▋       | 2821/10519 [43:16<2:02:58,  1.04it/s][NeMo W 2026-06-19 07:52:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 27%|██▋       | 2822/10519 [43:17<2:02:15,  1.05it/s][NeMo W 2026-06-19 07:52:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 27%|██▋       | 2823/10519 [43:17<2:01:41,  1.05it/s][NeMo W 2026-06-19 07:52:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:52:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 27%|██▋       | 2824/10519 [43:18<1:55:47,  1.11it/s][NeMo W 2026-06-19 07:53:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 27%|██▋       | 2825/10519 [43:19<1:57:25,  1.09it/s][NeMo W 2026-06-19 07:53:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 27%|██▋       | 2826/10519 [43:20<2:00:22,  1.07it/s][NeMo W 2026-06-19 07:53:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.84it/s]
 27%|██▋       | 2827/10519 [43:21<2:00:25,  1.06it/s][NeMo W 2026-06-19 07:53:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.48it/s]
 27%|██▋       | 2828/10519 [43:22<2:04:50,  1.03it/s][NeMo W 2026-06-19 07:53:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.30it/s]
 27%|██▋       | 2829/10519 [43:23<2:08:17,  1.00s/it][NeMo W 2026-06-19 07:53:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 2850 samples

[NeMo W 2026-06-19 07:53:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 27%|██▋       | 2851/10519 [43:45<2:22:01,  1.11s/it][NeMo W 2026-06-19 07:53:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 27%|██▋       | 2852/10519 [43:47<2:18:02,  1.08s/it][NeMo W 2026-06-19 07:53:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 27%|██▋       | 2853/10519 [43:47<2:10:45,  1.02s/it][NeMo W 2026-06-19 07:53:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 27%|██▋       | 2854/10519 [43:48<2:08:19,  1.00s/it][NeMo W 2026-06-19 07:53:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 27%|██▋       | 2855/10519 [43:49<1:58:18,  1.08it/s][NeMo W 2026-06-19 07:53:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 27%|██▋       | 2856/10519 [43:50<2:07:01,  1.01it/s][NeMo W 2026-06-19 07:53:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 27%|██▋       | 2857/10519 [43:51<2:04:56,  1.02it/s][NeMo W 2026-06-19 07:53:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 27%|██▋       | 2858/10519 [43:53<2:25:06,  1.14s/it][NeMo W 2026-06-19 07:53:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 27%|██▋       | 2859/10519 [43:54<2:17:56,  1.08s/it][NeMo W 2026-06-19 07:53:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 27%|██▋       | 2860/10519 [43:55<2:14:34,  1.05s/it][NeMo W 2026-06-19 07:53:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 27%|██▋       | 2861/10519 [43:56<2:11:47,  1.03s/it][NeMo W 2026-06-19 07:53:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 27%|██▋       | 2862/10519 [43:57<2:09:45,  1.02s/it][NeMo W 2026-06-19 07:53:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 27%|██▋       | 2863/10519 [43:58<2:09:46,  1.02s/it][NeMo W 2026-06-19 07:53:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 27%|██▋       | 2864/10519 [43:58<2:00:46,  1.06it/s][NeMo W 2026-06-19 07:53:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 27%|██▋       | 2865/10519 [43:59<2:01:57,  1.05it/s][NeMo W 2026-06-19 07:53:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 27%|██▋       | 2866/10519 [44:00<1:56:29,  1.09it/s][NeMo W 2026-06-19 07:53:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 27%|██▋       | 2867/10519 [44:01<2:02:40,  1.04it/s][NeMo W 2026-06-19 07:53:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 27%|██▋       | 2868/10519 [44:02<1:52:57,  1.13it/s][NeMo W 2026-06-19 07:53:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 27%|██▋       | 2869/10519 [44:03<1:57:49,  1.08it/s][NeMo W 2026-06-19 07:53:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 27%|██▋       | 2870/10519 [44:04<2:01:45,  1.05it/s][NeMo W 2026-06-19 07:53:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 27%|██▋       | 2871/10519 [44:05<2:06:08,  1.01it/s][NeMo W 2026-06-19 07:53:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 27%|██▋       | 2872/10519 [44:06<2:02:48,  1.04it/s][NeMo W 2026-06-19 07:53:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 27%|██▋       | 2873/10519 [44:07<1:56:33,  1.09it/s][NeMo W 2026-06-19 07:53:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.70it/s]
 27%|██▋       | 2874/10519 [44:08<1:57:19,  1.09it/s][NeMo W 2026-06-19 07:53:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 27%|██▋       | 2875/10519 [44:09<2:07:12,  1.00it/s][NeMo W 2026-06-19 07:53:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 27%|██▋       | 2876/10519 [44:10<2:06:33,  1.01it/s][NeMo W 2026-06-19 07:53:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 27%|██▋       | 2877/10519 [44:11<2:05:33,  1.01it/s][NeMo W 2026-06-19 07:53:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 27%|██▋       | 2878/10519 [44:12<1:59:12,  1.07it/s][NeMo W 2026-06-19 07:53:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 27%|██▋       | 2879/10519 [44:13<2:00:28,  1.06it/s][NeMo W 2026-06-19 07:53:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:53:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 27%|██▋       | 2880/10519 [44:14<2:01:52,  1.04it/s][NeMo W 2026-06-19 07:53:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 2900 samples

[NeMo W 2026-06-19 07:54:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 28%|██▊       | 2901/10519 [44:34<2:20:50,  1.11s/it][NeMo W 2026-06-19 07:54:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 28%|██▊       | 2902/10519 [44:35<2:13:44,  1.05s/it][NeMo W 2026-06-19 07:54:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 28%|██▊       | 2903/10519 [44:36<2:09:29,  1.02s/it][NeMo W 2026-06-19 07:54:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 28%|██▊       | 2904/10519 [44:37<2:08:18,  1.01s/it][NeMo W 2026-06-19 07:54:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 28%|██▊       | 2905/10519 [44:38<2:05:25,  1.01it/s][NeMo W 2026-06-19 07:54:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.49it/s]
 28%|██▊       | 2906/10519 [44:39<2:14:35,  1.06s/it][NeMo W 2026-06-19 07:54:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 28%|██▊       | 2907/10519 [44:40<2:10:00,  1.02s/it][NeMo W 2026-06-19 07:54:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 28%|██▊       | 2908/10519 [44:41<2:03:54,  1.02it/s][NeMo W 2026-06-19 07:54:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 28%|██▊       | 2909/10519 [44:42<2:00:29,  1.05it/s][NeMo W 2026-06-19 07:54:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 28%|██▊       | 2910/10519 [44:42<1:52:20,  1.13it/s][NeMo W 2026-06-19 07:54:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 28%|██▊       | 2911/10519 [44:43<1:55:45,  1.10it/s][NeMo W 2026-06-19 07:54:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 28%|██▊       | 2912/10519 [44:44<1:51:32,  1.14it/s][NeMo W 2026-06-19 07:54:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 28%|██▊       | 2913/10519 [44:45<1:56:56,  1.08it/s][NeMo W 2026-06-19 07:54:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 28%|██▊       | 2914/10519 [44:46<1:59:30,  1.06it/s][NeMo W 2026-06-19 07:54:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.67it/s]
 28%|██▊       | 2915/10519 [44:47<2:01:54,  1.04it/s][NeMo W 2026-06-19 07:54:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.00it/s]
 28%|██▊       | 2916/10519 [44:48<2:15:08,  1.07s/it][NeMo W 2026-06-19 07:54:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 28%|██▊       | 2917/10519 [44:50<2:17:41,  1.09s/it][NeMo W 2026-06-19 07:54:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 28%|██▊       | 2918/10519 [44:51<2:13:22,  1.05s/it][NeMo W 2026-06-19 07:54:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 28%|██▊       | 2919/10519 [44:52<2:13:57,  1.06s/it][NeMo W 2026-06-19 07:54:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 28%|██▊       | 2920/10519 [44:52<2:05:49,  1.01it/s][NeMo W 2026-06-19 07:54:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.53it/s]
 28%|██▊       | 2921/10519 [44:53<2:06:51,  1.00s/it][NeMo W 2026-06-19 07:54:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 28%|██▊       | 2922/10519 [44:54<2:06:19,  1.00it/s][NeMo W 2026-06-19 07:54:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 28%|██▊       | 2923/10519 [44:55<2:07:03,  1.00s/it][NeMo W 2026-06-19 07:54:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 28%|██▊       | 2924/10519 [44:56<1:56:40,  1.08it/s][NeMo W 2026-06-19 07:54:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 28%|██▊       | 2925/10519 [44:57<1:48:46,  1.16it/s][NeMo W 2026-06-19 07:54:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 28%|██▊       | 2926/10519 [44:58<1:52:07,  1.13it/s][NeMo W 2026-06-19 07:54:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 28%|██▊       | 2927/10519 [44:59<1:54:35,  1.10it/s][NeMo W 2026-06-19 07:54:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 28%|██▊       | 2928/10519 [45:00<1:56:45,  1.08it/s][NeMo W 2026-06-19 07:54:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 28%|██▊       | 2929/10519 [45:01<2:04:18,  1.02it/s][NeMo W 2026-06-19 07:54:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:54:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]

Checkpoint saved: 2950 samples

[NeMo W 2026-06-19 07:55:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 28%|██▊       | 2951/10519 [45:23<2:20:20,  1.11s/it][NeMo W 2026-06-19 07:55:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 28%|██▊       | 2952/10519 [45:24<2:14:15,  1.06s/it][NeMo W 2026-06-19 07:55:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 28%|██▊       | 2953/10519 [45:25<2:02:23,  1.03it/s][NeMo W 2026-06-19 07:55:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.68it/s]
 28%|██▊       | 2954/10519 [45:26<2:04:44,  1.01it/s][NeMo W 2026-06-19 07:55:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.01it/s]
 28%|██▊       | 2955/10519 [45:27<2:08:31,  1.02s/it][NeMo W 2026-06-19 07:55:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 28%|██▊       | 2956/10519 [45:28<2:07:10,  1.01s/it][NeMo W 2026-06-19 07:55:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 28%|██▊       | 2957/10519 [45:29<2:03:17,  1.02it/s][NeMo W 2026-06-19 07:55:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 28%|██▊       | 2958/10519 [45:30<1:57:36,  1.07it/s][NeMo W 2026-06-19 07:55:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 28%|██▊       | 2959/10519 [45:31<1:57:18,  1.07it/s][NeMo W 2026-06-19 07:55:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.68it/s]
 28%|██▊       | 2960/10519 [45:32<1:57:30,  1.07it/s][NeMo W 2026-06-19 07:55:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 28%|██▊       | 2961/10519 [45:32<1:54:39,  1.10it/s][NeMo W 2026-06-19 07:55:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 28%|██▊       | 2962/10519 [45:33<1:55:48,  1.09it/s][NeMo W 2026-06-19 07:55:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 28%|██▊       | 2963/10519 [45:34<1:58:34,  1.06it/s][NeMo W 2026-06-19 07:55:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 28%|██▊       | 2964/10519 [45:35<1:58:03,  1.07it/s][NeMo W 2026-06-19 07:55:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 28%|██▊       | 2965/10519 [45:36<1:57:26,  1.07it/s][NeMo W 2026-06-19 07:55:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 28%|██▊       | 2966/10519 [45:37<2:01:13,  1.04it/s][NeMo W 2026-06-19 07:55:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 28%|██▊       | 2967/10519 [45:38<2:04:55,  1.01it/s][NeMo W 2026-06-19 07:55:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 28%|██▊       | 2968/10519 [45:39<2:04:22,  1.01it/s][NeMo W 2026-06-19 07:55:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 28%|██▊       | 2969/10519 [45:40<2:01:56,  1.03it/s][NeMo W 2026-06-19 07:55:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.23it/s]
 28%|██▊       | 2970/10519 [45:41<1:55:28,  1.09it/s][NeMo W 2026-06-19 07:55:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 28%|██▊       | 2971/10519 [45:42<1:55:48,  1.09it/s][NeMo W 2026-06-19 07:55:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.39it/s]
 28%|██▊       | 2972/10519 [45:43<1:56:08,  1.08it/s][NeMo W 2026-06-19 07:55:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 28%|██▊       | 2973/10519 [45:44<1:57:29,  1.07it/s][NeMo W 2026-06-19 07:55:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 28%|██▊       | 2974/10519 [45:45<2:01:34,  1.03it/s][NeMo W 2026-06-19 07:55:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.32it/s]
 28%|██▊       | 2975/10519 [45:46<1:59:25,  1.05it/s][NeMo W 2026-06-19 07:55:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.48it/s]
 28%|██▊       | 2976/10519 [45:47<1:59:24,  1.05it/s][NeMo W 2026-06-19 07:55:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 28%|██▊       | 2977/10519 [45:48<1:58:01,  1.07it/s][NeMo W 2026-06-19 07:55:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 28%|██▊       | 2978/10519 [45:49<1:58:25,  1.06it/s][NeMo W 2026-06-19 07:55:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 28%|██▊       | 2979/10519 [45:49<1:48:48,  1.15it/s][NeMo W 2026-06-19 07:55:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.76it/s]

Checkpoint saved: 3000 samples

[NeMo W 2026-06-19 07:55:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.49it/s]
 29%|██▊       | 3001/10519 [46:10<2:22:08,  1.13s/it][NeMo W 2026-06-19 07:55:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 29%|██▊       | 3002/10519 [46:11<2:15:47,  1.08s/it][NeMo W 2026-06-19 07:55:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 29%|██▊       | 3003/10519 [46:13<2:22:23,  1.14s/it][NeMo W 2026-06-19 07:55:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 29%|██▊       | 3004/10519 [46:13<2:10:41,  1.04s/it][NeMo W 2026-06-19 07:55:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 29%|██▊       | 3005/10519 [46:14<2:05:46,  1.00s/it][NeMo W 2026-06-19 07:55:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.70it/s]
 29%|██▊       | 3006/10519 [46:15<2:06:21,  1.01s/it][NeMo W 2026-06-19 07:55:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 29%|██▊       | 3007/10519 [46:16<2:06:38,  1.01s/it][NeMo W 2026-06-19 07:55:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:55:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.62it/s]
 29%|██▊       | 3008/10519 [46:19<2:54:06,  1.39s/it][NeMo W 2026-06-19 07:56:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 29%|██▊       | 3009/10519 [46:20<2:41:51,  1.29s/it][NeMo W 2026-06-19 07:56:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.31it/s]
 29%|██▊       | 3010/10519 [46:21<2:33:46,  1.23s/it][NeMo W 2026-06-19 07:56:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 29%|██▊       | 3011/10519 [46:22<2:29:12,  1.19s/it][NeMo W 2026-06-19 07:56:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 29%|██▊       | 3012/10519 [46:23<2:14:57,  1.08s/it][NeMo W 2026-06-19 07:56:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.22it/s]
 29%|██▊       | 3013/10519 [46:24<2:10:56,  1.05s/it][NeMo W 2026-06-19 07:56:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 29%|██▊       | 3014/10519 [46:25<2:06:29,  1.01s/it][NeMo W 2026-06-19 07:56:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 29%|██▊       | 3015/10519 [46:26<2:03:22,  1.01it/s][NeMo W 2026-06-19 07:56:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 29%|██▊       | 3016/10519 [46:27<2:01:45,  1.03it/s][NeMo W 2026-06-19 07:56:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 29%|██▊       | 3017/10519 [46:27<2:00:54,  1.03it/s][NeMo W 2026-06-19 07:56:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 29%|██▊       | 3018/10519 [46:28<1:53:34,  1.10it/s][NeMo W 2026-06-19 07:56:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 29%|██▊       | 3019/10519 [46:30<2:37:51,  1.26s/it][NeMo W 2026-06-19 07:56:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 29%|██▊       | 3020/10519 [46:31<2:25:05,  1.16s/it][NeMo W 2026-06-19 07:56:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 29%|██▊       | 3021/10519 [46:32<2:17:39,  1.10s/it][NeMo W 2026-06-19 07:56:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.44it/s]
 29%|██▊       | 3022/10519 [46:33<2:12:24,  1.06s/it][NeMo W 2026-06-19 07:56:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.83it/s]
 29%|██▊       | 3023/10519 [46:34<2:12:26,  1.06s/it][NeMo W 2026-06-19 07:56:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 29%|██▊       | 3024/10519 [46:35<2:10:49,  1.05s/it][NeMo W 2026-06-19 07:56:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 29%|██▉       | 3025/10519 [46:36<2:05:53,  1.01s/it][NeMo W 2026-06-19 07:56:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 29%|██▉       | 3026/10519 [46:37<2:06:23,  1.01s/it][NeMo W 2026-06-19 07:56:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 29%|██▉       | 3027/10519 [46:38<2:06:37,  1.01s/it][NeMo W 2026-06-19 07:56:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 29%|██▉       | 3028/10519 [46:39<2:04:02,  1.01it/s][NeMo W 2026-06-19 07:56:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 29%|██▉       | 3029/10519 [46:40<2:06:05,  1.01s/it][NeMo W 2026-06-19 07:56:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]

Checkpoint saved: 3050 samples

[NeMo W 2026-06-19 07:56:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 29%|██▉       | 3051/10519 [47:02<2:15:15,  1.09s/it][NeMo W 2026-06-19 07:56:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 29%|██▉       | 3052/10519 [47:03<2:06:22,  1.02s/it][NeMo W 2026-06-19 07:56:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 29%|██▉       | 3053/10519 [47:04<2:08:56,  1.04s/it][NeMo W 2026-06-19 07:56:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 29%|██▉       | 3054/10519 [47:05<2:06:56,  1.02s/it][NeMo W 2026-06-19 07:56:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 29%|██▉       | 3055/10519 [47:06<2:03:56,  1.00it/s][NeMo W 2026-06-19 07:56:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 29%|██▉       | 3056/10519 [47:07<2:04:57,  1.00s/it][NeMo W 2026-06-19 07:56:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 29%|██▉       | 3057/10519 [47:08<2:06:30,  1.02s/it][NeMo W 2026-06-19 07:56:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 29%|██▉       | 3058/10519 [47:09<2:05:11,  1.01s/it][NeMo W 2026-06-19 07:56:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.63it/s]
 29%|██▉       | 3059/10519 [47:14<4:29:20,  2.17s/it][NeMo W 2026-06-19 07:56:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 29%|██▉       | 3060/10519 [47:15<3:47:55,  1.83s/it][NeMo W 2026-06-19 07:56:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 29%|██▉       | 3061/10519 [47:16<3:23:10,  1.63s/it][NeMo W 2026-06-19 07:56:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 29%|██▉       | 3062/10519 [47:17<2:52:26,  1.39s/it][NeMo W 2026-06-19 07:56:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:56:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 29%|██▉       | 3063/10519 [47:18<2:38:03,  1.27s/it][NeMo W 2026-06-19 07:57:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 29%|██▉       | 3064/10519 [47:19<2:26:37,  1.18s/it][NeMo W 2026-06-19 07:57:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 29%|██▉       | 3065/10519 [47:20<2:36:32,  1.26s/it][NeMo W 2026-06-19 07:57:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 29%|██▉       | 3066/10519 [47:21<2:19:26,  1.12s/it][NeMo W 2026-06-19 07:57:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 29%|██▉       | 3067/10519 [47:22<2:12:38,  1.07s/it][NeMo W 2026-06-19 07:57:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 29%|██▉       | 3068/10519 [47:23<2:13:09,  1.07s/it][NeMo W 2026-06-19 07:57:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 29%|██▉       | 3069/10519 [47:24<2:08:56,  1.04s/it][NeMo W 2026-06-19 07:57:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 29%|██▉       | 3070/10519 [47:25<2:05:54,  1.01s/it][NeMo W 2026-06-19 07:57:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 29%|██▉       | 3071/10519 [47:26<2:04:10,  1.00s/it][NeMo W 2026-06-19 07:57:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 29%|██▉       | 3072/10519 [47:27<2:04:50,  1.01s/it][NeMo W 2026-06-19 07:57:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 29%|██▉       | 3073/10519 [47:28<2:03:07,  1.01it/s][NeMo W 2026-06-19 07:57:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.56it/s]
 29%|██▉       | 3074/10519 [47:29<1:59:06,  1.04it/s][NeMo W 2026-06-19 07:57:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 29%|██▉       | 3075/10519 [47:30<1:58:19,  1.05it/s][NeMo W 2026-06-19 07:57:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.44it/s]
 29%|██▉       | 3076/10519 [47:31<1:58:00,  1.05it/s][NeMo W 2026-06-19 07:57:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 29%|██▉       | 3077/10519 [47:32<1:55:15,  1.08it/s][NeMo W 2026-06-19 07:57:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.08it/s]
 29%|██▉       | 3078/10519 [47:33<1:57:57,  1.05it/s][NeMo W 2026-06-19 07:57:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 29%|██▉       | 3079/10519 [47:34<1:57:42,  1.05it/s][NeMo W 2026-06-19 07:57:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]

Checkpoint saved: 3100 samples

[NeMo W 2026-06-19 07:57:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 29%|██▉       | 3101/10519 [47:56<2:19:46,  1.13s/it][NeMo W 2026-06-19 07:57:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 29%|██▉       | 3102/10519 [47:57<2:13:20,  1.08s/it][NeMo W 2026-06-19 07:57:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 29%|██▉       | 3103/10519 [47:58<2:10:36,  1.06s/it][NeMo W 2026-06-19 07:57:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 30%|██▉       | 3104/10519 [47:59<2:14:53,  1.09s/it][NeMo W 2026-06-19 07:57:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 30%|██▉       | 3105/10519 [48:00<2:13:20,  1.08s/it][NeMo W 2026-06-19 07:57:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 30%|██▉       | 3106/10519 [48:01<2:08:30,  1.04s/it][NeMo W 2026-06-19 07:57:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.12it/s]
 30%|██▉       | 3107/10519 [48:02<2:05:37,  1.02s/it][NeMo W 2026-06-19 07:57:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 30%|██▉       | 3108/10519 [48:03<2:07:08,  1.03s/it][NeMo W 2026-06-19 07:57:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 30%|██▉       | 3109/10519 [48:04<2:04:37,  1.01s/it][NeMo W 2026-06-19 07:57:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 30%|██▉       | 3110/10519 [48:05<2:02:23,  1.01it/s][NeMo W 2026-06-19 07:57:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.96it/s]
 30%|██▉       | 3111/10519 [48:06<1:59:26,  1.03it/s][NeMo W 2026-06-19 07:57:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 30%|██▉       | 3112/10519 [48:07<1:59:12,  1.04it/s][NeMo W 2026-06-19 07:57:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 30%|██▉       | 3113/10519 [48:08<1:58:29,  1.04it/s][NeMo W 2026-06-19 07:57:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 30%|██▉       | 3114/10519 [48:09<2:02:18,  1.01it/s][NeMo W 2026-06-19 07:57:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 30%|██▉       | 3115/10519 [48:10<2:00:51,  1.02it/s][NeMo W 2026-06-19 07:57:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 30%|██▉       | 3116/10519 [48:11<1:58:26,  1.04it/s][NeMo W 2026-06-19 07:57:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 30%|██▉       | 3117/10519 [48:11<1:49:38,  1.13it/s][NeMo W 2026-06-19 07:57:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 30%|██▉       | 3118/10519 [48:12<1:53:43,  1.08it/s][NeMo W 2026-06-19 07:57:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 30%|██▉       | 3119/10519 [48:13<1:55:20,  1.07it/s][NeMo W 2026-06-19 07:57:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.03it/s]
 30%|██▉       | 3120/10519 [48:14<1:48:29,  1.14it/s][NeMo W 2026-06-19 07:57:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 30%|██▉       | 3121/10519 [48:15<1:48:37,  1.14it/s][NeMo W 2026-06-19 07:57:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 30%|██▉       | 3122/10519 [48:16<1:52:59,  1.09it/s][NeMo W 2026-06-19 07:57:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.12it/s]
 30%|██▉       | 3123/10519 [48:17<1:55:47,  1.06it/s][NeMo W 2026-06-19 07:57:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:57:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.32it/s]
 30%|██▉       | 3124/10519 [48:18<1:50:33,  1.11it/s][NeMo W 2026-06-19 07:58:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 30%|██▉       | 3125/10519 [48:19<1:52:13,  1.10it/s][NeMo W 2026-06-19 07:58:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.95it/s]
 30%|██▉       | 3126/10519 [48:20<1:48:16,  1.14it/s][NeMo W 2026-06-19 07:58:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.32it/s]
 30%|██▉       | 3127/10519 [48:21<1:53:04,  1.09it/s][NeMo W 2026-06-19 07:58:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 30%|██▉       | 3128/10519 [48:21<1:49:34,  1.12it/s][NeMo W 2026-06-19 07:58:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 30%|██▉       | 3129/10519 [48:22<1:52:13,  1.10it/s][NeMo W 2026-06-19 07:58:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]

Checkpoint saved: 3150 samples

[NeMo W 2026-06-19 07:58:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 30%|██▉       | 3151/10519 [48:45<2:24:25,  1.18s/it][NeMo W 2026-06-19 07:58:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 30%|██▉       | 3152/10519 [48:46<2:14:51,  1.10s/it][NeMo W 2026-06-19 07:58:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 30%|██▉       | 3153/10519 [48:47<2:14:23,  1.09s/it][NeMo W 2026-06-19 07:58:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.29it/s]
 30%|██▉       | 3154/10519 [48:48<2:07:24,  1.04s/it][NeMo W 2026-06-19 07:58:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 30%|██▉       | 3155/10519 [48:49<2:03:16,  1.00s/it][NeMo W 2026-06-19 07:58:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.56it/s]
 30%|███       | 3156/10519 [48:50<2:03:28,  1.01s/it][NeMo W 2026-06-19 07:58:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 30%|███       | 3157/10519 [48:51<2:02:31,  1.00it/s][NeMo W 2026-06-19 07:58:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 30%|███       | 3158/10519 [48:52<2:03:15,  1.00s/it][NeMo W 2026-06-19 07:58:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 30%|███       | 3159/10519 [48:53<2:09:07,  1.05s/it][NeMo W 2026-06-19 07:58:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 30%|███       | 3160/10519 [48:54<2:07:24,  1.04s/it][NeMo W 2026-06-19 07:58:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 30%|███       | 3161/10519 [48:55<2:10:29,  1.06s/it][NeMo W 2026-06-19 07:58:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 30%|███       | 3162/10519 [48:56<2:06:12,  1.03s/it][NeMo W 2026-06-19 07:58:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 30%|███       | 3163/10519 [48:57<2:05:15,  1.02s/it][NeMo W 2026-06-19 07:58:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 30%|███       | 3164/10519 [48:58<2:03:56,  1.01s/it][NeMo W 2026-06-19 07:58:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 30%|███       | 3165/10519 [48:59<1:55:17,  1.06it/s][NeMo W 2026-06-19 07:58:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 30%|███       | 3166/10519 [49:00<1:54:44,  1.07it/s][NeMo W 2026-06-19 07:58:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 30%|███       | 3167/10519 [49:01<2:03:10,  1.01s/it][NeMo W 2026-06-19 07:58:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 30%|███       | 3168/10519 [49:02<2:02:28,  1.00it/s][NeMo W 2026-06-19 07:58:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 30%|███       | 3169/10519 [49:03<2:01:10,  1.01it/s][NeMo W 2026-06-19 07:58:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 30%|███       | 3170/10519 [49:03<1:53:39,  1.08it/s][NeMo W 2026-06-19 07:58:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.86it/s]
 30%|███       | 3171/10519 [49:04<1:54:54,  1.07it/s][NeMo W 2026-06-19 07:58:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 30%|███       | 3172/10519 [49:05<1:54:47,  1.07it/s][NeMo W 2026-06-19 07:58:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 30%|███       | 3173/10519 [49:06<1:56:49,  1.05it/s][NeMo W 2026-06-19 07:58:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.16it/s]
 30%|███       | 3174/10519 [49:07<2:00:39,  1.01it/s][NeMo W 2026-06-19 07:58:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 30%|███       | 3175/10519 [49:09<2:04:22,  1.02s/it][NeMo W 2026-06-19 07:58:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 30%|███       | 3176/10519 [49:10<2:03:06,  1.01s/it][NeMo W 2026-06-19 07:58:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.57it/s]
 30%|███       | 3177/10519 [49:10<2:02:20,  1.00it/s][NeMo W 2026-06-19 07:58:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 30%|███       | 3178/10519 [49:12<2:03:05,  1.01s/it][NeMo W 2026-06-19 07:58:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.12it/s]
 30%|███       | 3179/10519 [49:12<2:01:03,  1.01it/s][NeMo W 2026-06-19 07:58:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:58:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]

Checkpoint saved: 3200 samples

[NeMo W 2026-06-19 07:59:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 30%|███       | 3201/10519 [49:34<2:21:43,  1.16s/it][NeMo W 2026-06-19 07:59:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 30%|███       | 3202/10519 [49:35<2:14:40,  1.10s/it][NeMo W 2026-06-19 07:59:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 30%|███       | 3203/10519 [49:36<2:08:49,  1.06s/it][NeMo W 2026-06-19 07:59:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.84it/s]
 30%|███       | 3204/10519 [49:37<2:06:41,  1.04s/it][NeMo W 2026-06-19 07:59:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 30%|███       | 3205/10519 [49:38<2:11:42,  1.08s/it][NeMo W 2026-06-19 07:59:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 30%|███       | 3206/10519 [49:39<2:08:03,  1.05s/it][NeMo W 2026-06-19 07:59:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 30%|███       | 3207/10519 [49:40<2:11:45,  1.08s/it][NeMo W 2026-06-19 07:59:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 30%|███       | 3208/10519 [49:41<2:08:26,  1.05s/it][NeMo W 2026-06-19 07:59:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 31%|███       | 3209/10519 [49:42<2:04:48,  1.02s/it][NeMo W 2026-06-19 07:59:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 31%|███       | 3210/10519 [49:43<2:05:33,  1.03s/it][NeMo W 2026-06-19 07:59:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 31%|███       | 3211/10519 [49:44<1:55:38,  1.05it/s][NeMo W 2026-06-19 07:59:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 31%|███       | 3212/10519 [49:45<1:47:42,  1.13it/s][NeMo W 2026-06-19 07:59:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 31%|███       | 3213/10519 [49:46<1:53:28,  1.07it/s][NeMo W 2026-06-19 07:59:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.81it/s]
 31%|███       | 3214/10519 [49:47<2:00:50,  1.01it/s][NeMo W 2026-06-19 07:59:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 31%|███       | 3215/10519 [49:48<2:01:41,  1.00it/s][NeMo W 2026-06-19 07:59:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 31%|███       | 3216/10519 [49:49<1:52:06,  1.09it/s][NeMo W 2026-06-19 07:59:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.71it/s]
 31%|███       | 3217/10519 [49:50<1:55:03,  1.06it/s][NeMo W 2026-06-19 07:59:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.30it/s]
 31%|███       | 3218/10519 [49:51<1:57:50,  1.03it/s][NeMo W 2026-06-19 07:59:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 31%|███       | 3219/10519 [49:52<1:58:24,  1.03it/s][NeMo W 2026-06-19 07:59:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 31%|███       | 3220/10519 [49:54<2:26:21,  1.20s/it][NeMo W 2026-06-19 07:59:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 31%|███       | 3221/10519 [49:55<2:21:21,  1.16s/it][NeMo W 2026-06-19 07:59:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 31%|███       | 3222/10519 [49:56<2:32:07,  1.25s/it][NeMo W 2026-06-19 07:59:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 31%|███       | 3223/10519 [49:57<2:22:48,  1.17s/it][NeMo W 2026-06-19 07:59:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 31%|███       | 3224/10519 [49:58<2:16:59,  1.13s/it][NeMo W 2026-06-19 07:59:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 31%|███       | 3225/10519 [50:01<3:17:12,  1.62s/it][NeMo W 2026-06-19 07:59:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 31%|███       | 3226/10519 [50:02<2:54:07,  1.43s/it][NeMo W 2026-06-19 07:59:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 31%|███       | 3227/10519 [50:03<2:31:52,  1.25s/it][NeMo W 2026-06-19 07:59:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 31%|███       | 3228/10519 [50:04<2:22:59,  1.18s/it][NeMo W 2026-06-19 07:59:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 31%|███       | 3229/10519 [50:05<2:16:35,  1.12s/it][NeMo W 2026-06-19 07:59:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 07:59:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]

Checkpoint saved: 3250 samples

[NeMo W 2026-06-19 08:00:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.14it/s]
 31%|███       | 3251/10519 [50:26<2:16:26,  1.13s/it][NeMo W 2026-06-19 08:00:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 31%|███       | 3252/10519 [50:28<2:14:17,  1.11s/it][NeMo W 2026-06-19 08:00:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 31%|███       | 3253/10519 [50:28<2:07:36,  1.05s/it][NeMo W 2026-06-19 08:00:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.46it/s]
 31%|███       | 3254/10519 [50:29<2:06:04,  1.04s/it][NeMo W 2026-06-19 08:00:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.08it/s]
 31%|███       | 3255/10519 [50:30<2:03:59,  1.02s/it][NeMo W 2026-06-19 08:00:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 31%|███       | 3256/10519 [50:31<2:04:06,  1.03s/it][NeMo W 2026-06-19 08:00:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 31%|███       | 3257/10519 [50:33<2:05:51,  1.04s/it][NeMo W 2026-06-19 08:00:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 31%|███       | 3258/10519 [50:34<2:04:22,  1.03s/it][NeMo W 2026-06-19 08:00:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.94it/s]
 31%|███       | 3259/10519 [50:34<1:57:29,  1.03it/s][NeMo W 2026-06-19 08:00:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 31%|███       | 3260/10519 [50:35<2:00:48,  1.00it/s][NeMo W 2026-06-19 08:00:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 31%|███       | 3261/10519 [50:36<2:00:57,  1.00it/s][NeMo W 2026-06-19 08:00:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.95it/s]
 31%|███       | 3262/10519 [50:38<2:04:51,  1.03s/it][NeMo W 2026-06-19 08:00:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.56it/s]
 31%|███       | 3263/10519 [50:38<2:01:36,  1.01s/it][NeMo W 2026-06-19 08:00:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 31%|███       | 3264/10519 [50:39<1:59:11,  1.01it/s][NeMo W 2026-06-19 08:00:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 31%|███       | 3265/10519 [50:40<1:59:25,  1.01it/s][NeMo W 2026-06-19 08:00:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 31%|███       | 3266/10519 [50:41<2:00:39,  1.00it/s][NeMo W 2026-06-19 08:00:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 31%|███       | 3267/10519 [50:42<2:00:06,  1.01it/s][NeMo W 2026-06-19 08:00:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.02it/s]
 31%|███       | 3268/10519 [50:43<2:00:03,  1.01it/s][NeMo W 2026-06-19 08:00:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 31%|███       | 3269/10519 [50:44<1:58:54,  1.02it/s][NeMo W 2026-06-19 08:00:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 31%|███       | 3270/10519 [50:45<1:53:15,  1.07it/s][NeMo W 2026-06-19 08:00:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 31%|███       | 3271/10519 [50:46<1:53:32,  1.06it/s][NeMo W 2026-06-19 08:00:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 31%|███       | 3272/10519 [50:47<1:54:44,  1.05it/s][NeMo W 2026-06-19 08:00:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 31%|███       | 3273/10519 [50:48<2:03:20,  1.02s/it][NeMo W 2026-06-19 08:00:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 31%|███       | 3274/10519 [50:49<1:58:19,  1.02it/s][NeMo W 2026-06-19 08:00:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.67it/s]
 31%|███       | 3275/10519 [50:50<1:53:10,  1.07it/s][NeMo W 2026-06-19 08:00:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 31%|███       | 3276/10519 [50:51<2:05:25,  1.04s/it][NeMo W 2026-06-19 08:00:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 31%|███       | 3277/10519 [50:52<2:02:51,  1.02s/it][NeMo W 2026-06-19 08:00:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 31%|███       | 3278/10519 [50:53<2:05:52,  1.04s/it][NeMo W 2026-06-19 08:00:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 31%|███       | 3279/10519 [50:54<2:01:11,  1.00s/it][NeMo W 2026-06-19 08:00:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 3300 samples

[NeMo W 2026-06-19 08:00:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 31%|███▏      | 3301/10519 [51:16<2:11:28,  1.09s/it][NeMo W 2026-06-19 08:00:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 31%|███▏      | 3302/10519 [51:17<2:08:48,  1.07s/it][NeMo W 2026-06-19 08:00:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 31%|███▏      | 3303/10519 [51:18<1:59:30,  1.01it/s][NeMo W 2026-06-19 08:00:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:00:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 31%|███▏      | 3304/10519 [51:19<1:58:01,  1.02it/s][NeMo W 2026-06-19 08:01:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 31%|███▏      | 3305/10519 [51:20<2:03:28,  1.03s/it][NeMo W 2026-06-19 08:01:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 31%|███▏      | 3306/10519 [51:21<1:59:51,  1.00it/s][NeMo W 2026-06-19 08:01:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 31%|███▏      | 3307/10519 [51:22<1:59:19,  1.01it/s][NeMo W 2026-06-19 08:01:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 31%|███▏      | 3308/10519 [51:23<1:52:31,  1.07it/s][NeMo W 2026-06-19 08:01:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 31%|███▏      | 3309/10519 [51:23<1:52:48,  1.07it/s][NeMo W 2026-06-19 08:01:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.31it/s]
 31%|███▏      | 3310/10519 [51:24<1:46:46,  1.13it/s][NeMo W 2026-06-19 08:01:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 31%|███▏      | 3311/10519 [51:25<1:50:30,  1.09it/s][NeMo W 2026-06-19 08:01:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 31%|███▏      | 3312/10519 [51:26<1:53:37,  1.06it/s][NeMo W 2026-06-19 08:01:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.19it/s]
 31%|███▏      | 3313/10519 [51:27<1:50:20,  1.09it/s][NeMo W 2026-06-19 08:01:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 32%|███▏      | 3314/10519 [51:28<1:53:17,  1.06it/s][NeMo W 2026-06-19 08:01:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 32%|███▏      | 3315/10519 [51:29<1:55:11,  1.04it/s][NeMo W 2026-06-19 08:01:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 32%|███▏      | 3316/10519 [51:30<1:52:35,  1.07it/s][NeMo W 2026-06-19 08:01:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 32%|███▏      | 3317/10519 [51:31<1:52:27,  1.07it/s][NeMo W 2026-06-19 08:01:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 32%|███▏      | 3318/10519 [51:32<1:53:43,  1.06it/s][NeMo W 2026-06-19 08:01:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.29it/s]
 32%|███▏      | 3319/10519 [51:33<1:56:10,  1.03it/s][NeMo W 2026-06-19 08:01:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 32%|███▏      | 3320/10519 [51:34<1:58:09,  1.02it/s][NeMo W 2026-06-19 08:01:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 32%|███▏      | 3321/10519 [51:35<1:56:48,  1.03it/s][NeMo W 2026-06-19 08:01:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 32%|███▏      | 3322/10519 [51:36<1:55:47,  1.04it/s][NeMo W 2026-06-19 08:01:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 32%|███▏      | 3323/10519 [51:37<1:55:45,  1.04it/s][NeMo W 2026-06-19 08:01:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 32%|███▏      | 3324/10519 [51:38<1:55:42,  1.04it/s][NeMo W 2026-06-19 08:01:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.21it/s]
 32%|███▏      | 3325/10519 [51:39<1:56:58,  1.02it/s][NeMo W 2026-06-19 08:01:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.41it/s]
 32%|███▏      | 3326/10519 [51:40<1:57:36,  1.02it/s][NeMo W 2026-06-19 08:01:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 32%|███▏      | 3327/10519 [51:40<1:49:53,  1.09it/s][NeMo W 2026-06-19 08:01:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.93it/s]
 32%|███▏      | 3328/10519 [51:42<1:56:18,  1.03it/s][NeMo W 2026-06-19 08:01:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.63it/s]
 32%|███▏      | 3329/10519 [51:43<1:54:14,  1.05it/s][NeMo W 2026-06-19 08:01:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]

Checkpoint saved: 3350 samples

[NeMo W 2026-06-19 08:01:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 32%|███▏      | 3351/10519 [52:04<2:07:24,  1.07s/it][NeMo W 2026-06-19 08:01:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 32%|███▏      | 3352/10519 [52:05<2:03:56,  1.04s/it][NeMo W 2026-06-19 08:01:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 32%|███▏      | 3353/10519 [52:06<2:03:18,  1.03s/it][NeMo W 2026-06-19 08:01:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 32%|███▏      | 3354/10519 [52:07<2:02:36,  1.03s/it][NeMo W 2026-06-19 08:01:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 32%|███▏      | 3355/10519 [52:08<1:54:36,  1.04it/s][NeMo W 2026-06-19 08:01:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 32%|███▏      | 3356/10519 [52:09<1:55:14,  1.04it/s][NeMo W 2026-06-19 08:01:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 32%|███▏      | 3357/10519 [52:10<1:55:37,  1.03it/s][NeMo W 2026-06-19 08:01:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 32%|███▏      | 3358/10519 [52:11<1:53:48,  1.05it/s][NeMo W 2026-06-19 08:01:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.95it/s]
 32%|███▏      | 3359/10519 [52:12<1:45:18,  1.13it/s][NeMo W 2026-06-19 08:01:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 32%|███▏      | 3360/10519 [52:12<1:47:10,  1.11it/s][NeMo W 2026-06-19 08:01:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 32%|███▏      | 3361/10519 [52:13<1:50:14,  1.08it/s][NeMo W 2026-06-19 08:01:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 32%|███▏      | 3362/10519 [52:14<1:46:02,  1.12it/s][NeMo W 2026-06-19 08:01:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.52it/s]
 32%|███▏      | 3363/10519 [52:15<1:49:07,  1.09it/s][NeMo W 2026-06-19 08:01:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 32%|███▏      | 3364/10519 [52:16<1:48:23,  1.10it/s][NeMo W 2026-06-19 08:01:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 32%|███▏      | 3365/10519 [52:17<1:52:43,  1.06it/s][NeMo W 2026-06-19 08:01:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:01:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
 32%|███▏      | 3366/10519 [52:18<1:59:36,  1.00s/it][NeMo W 2026-06-19 08:02:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 32%|███▏      | 3367/10519 [52:19<1:59:14,  1.00s/it][NeMo W 2026-06-19 08:02:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.85it/s]
 32%|███▏      | 3368/10519 [52:20<2:01:03,  1.02s/it][NeMo W 2026-06-19 08:02:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 32%|███▏      | 3369/10519 [52:21<1:56:27,  1.02it/s][NeMo W 2026-06-19 08:02:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 32%|███▏      | 3370/10519 [52:22<1:56:46,  1.02it/s][NeMo W 2026-06-19 08:02:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 32%|███▏      | 3371/10519 [52:23<1:54:17,  1.04it/s][NeMo W 2026-06-19 08:02:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 32%|███▏      | 3372/10519 [52:24<1:52:54,  1.06it/s][NeMo W 2026-06-19 08:02:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 32%|███▏      | 3373/10519 [52:25<1:53:43,  1.05it/s][NeMo W 2026-06-19 08:02:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.69it/s]
 32%|███▏      | 3374/10519 [52:26<1:53:49,  1.05it/s][NeMo W 2026-06-19 08:02:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 32%|███▏      | 3375/10519 [52:27<1:49:29,  1.09it/s][NeMo W 2026-06-19 08:02:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 32%|███▏      | 3376/10519 [52:28<1:52:11,  1.06it/s][NeMo W 2026-06-19 08:02:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 32%|███▏      | 3377/10519 [52:29<1:51:55,  1.06it/s][NeMo W 2026-06-19 08:02:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 32%|███▏      | 3378/10519 [52:30<1:53:01,  1.05it/s][NeMo W 2026-06-19 08:02:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 32%|███▏      | 3379/10519 [52:31<1:55:22,  1.03it/s][NeMo W 2026-06-19 08:02:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]

Checkpoint saved: 3400 samples

[NeMo W 2026-06-19 08:02:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.39it/s]
 32%|███▏      | 3401/10519 [52:52<2:04:21,  1.05s/it][NeMo W 2026-06-19 08:02:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.81it/s]
 32%|███▏      | 3402/10519 [52:52<1:53:45,  1.04it/s][NeMo W 2026-06-19 08:02:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 32%|███▏      | 3403/10519 [52:53<1:54:44,  1.03it/s][NeMo W 2026-06-19 08:02:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 32%|███▏      | 3404/10519 [52:55<1:57:44,  1.01it/s][NeMo W 2026-06-19 08:02:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 32%|███▏      | 3405/10519 [52:55<1:55:22,  1.03it/s][NeMo W 2026-06-19 08:02:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 32%|███▏      | 3406/10519 [52:56<1:49:48,  1.08it/s][NeMo W 2026-06-19 08:02:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 32%|███▏      | 3407/10519 [52:57<1:53:29,  1.04it/s][NeMo W 2026-06-19 08:02:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 32%|███▏      | 3408/10519 [52:58<1:48:07,  1.10it/s][NeMo W 2026-06-19 08:02:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.79it/s]
 32%|███▏      | 3409/10519 [52:59<1:49:12,  1.09it/s][NeMo W 2026-06-19 08:02:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 32%|███▏      | 3410/10519 [53:00<1:55:53,  1.02it/s][NeMo W 2026-06-19 08:02:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 32%|███▏      | 3411/10519 [53:01<1:49:08,  1.09it/s][NeMo W 2026-06-19 08:02:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 32%|███▏      | 3412/10519 [53:02<1:51:20,  1.06it/s][NeMo W 2026-06-19 08:02:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 32%|███▏      | 3413/10519 [53:03<1:45:43,  1.12it/s][NeMo W 2026-06-19 08:02:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 32%|███▏      | 3414/10519 [53:04<1:52:02,  1.06it/s][NeMo W 2026-06-19 08:02:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 32%|███▏      | 3415/10519 [53:05<1:54:03,  1.04it/s][NeMo W 2026-06-19 08:02:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 32%|███▏      | 3416/10519 [53:06<1:54:17,  1.04it/s][NeMo W 2026-06-19 08:02:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.72it/s]
 32%|███▏      | 3417/10519 [53:07<1:57:25,  1.01it/s][NeMo W 2026-06-19 08:02:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 32%|███▏      | 3418/10519 [53:08<1:56:06,  1.02it/s][NeMo W 2026-06-19 08:02:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 33%|███▎      | 3419/10519 [53:09<1:49:16,  1.08it/s][NeMo W 2026-06-19 08:02:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 33%|███▎      | 3420/10519 [53:10<1:51:37,  1.06it/s][NeMo W 2026-06-19 08:02:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.38it/s]
 33%|███▎      | 3421/10519 [53:11<1:53:13,  1.04it/s][NeMo W 2026-06-19 08:02:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.35it/s]
 33%|███▎      | 3422/10519 [53:12<1:55:01,  1.03it/s][NeMo W 2026-06-19 08:02:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 33%|███▎      | 3423/10519 [53:12<1:53:12,  1.04it/s][NeMo W 2026-06-19 08:02:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 33%|███▎      | 3424/10519 [53:13<1:49:56,  1.08it/s][NeMo W 2026-06-19 08:02:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 33%|███▎      | 3425/10519 [53:14<1:46:12,  1.11it/s][NeMo W 2026-06-19 08:02:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 33%|███▎      | 3426/10519 [53:15<1:47:13,  1.10it/s][NeMo W 2026-06-19 08:02:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 33%|███▎      | 3427/10519 [53:16<1:49:38,  1.08it/s][NeMo W 2026-06-19 08:02:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 33%|███▎      | 3428/10519 [53:17<1:53:11,  1.04it/s][NeMo W 2026-06-19 08:02:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:02:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 33%|███▎      | 3429/10519 [53:18<1:51:34,  1.06it/s][NeMo W 2026-06-19 08:03:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]

Checkpoint saved: 3450 samples

[NeMo W 2026-06-19 08:03:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 33%|███▎      | 3451/10519 [53:40<2:09:01,  1.10s/it][NeMo W 2026-06-19 08:03:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.02it/s]
 33%|███▎      | 3452/10519 [53:41<2:07:08,  1.08s/it][NeMo W 2026-06-19 08:03:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 33%|███▎      | 3453/10519 [53:42<2:02:47,  1.04s/it][NeMo W 2026-06-19 08:03:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 33%|███▎      | 3454/10519 [53:43<2:01:58,  1.04s/it][NeMo W 2026-06-19 08:03:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 33%|███▎      | 3455/10519 [53:44<1:58:22,  1.01s/it][NeMo W 2026-06-19 08:03:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 33%|███▎      | 3456/10519 [53:45<1:56:49,  1.01it/s][NeMo W 2026-06-19 08:03:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 33%|███▎      | 3457/10519 [53:45<1:50:22,  1.07it/s][NeMo W 2026-06-19 08:03:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 33%|███▎      | 3458/10519 [53:46<1:54:35,  1.03it/s][NeMo W 2026-06-19 08:03:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 33%|███▎      | 3459/10519 [53:47<1:56:31,  1.01it/s][NeMo W 2026-06-19 08:03:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 33%|███▎      | 3460/10519 [53:48<1:49:17,  1.08it/s][NeMo W 2026-06-19 08:03:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 33%|███▎      | 3461/10519 [53:49<1:57:09,  1.00it/s][NeMo W 2026-06-19 08:03:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 33%|███▎      | 3462/10519 [53:50<1:57:10,  1.00it/s][NeMo W 2026-06-19 08:03:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 33%|███▎      | 3463/10519 [53:51<1:54:55,  1.02it/s][NeMo W 2026-06-19 08:03:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 33%|███▎      | 3464/10519 [53:52<1:55:36,  1.02it/s][NeMo W 2026-06-19 08:03:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 33%|███▎      | 3465/10519 [53:53<1:54:19,  1.03it/s][NeMo W 2026-06-19 08:03:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.43it/s]
 33%|███▎      | 3466/10519 [53:54<1:48:35,  1.08it/s][NeMo W 2026-06-19 08:03:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 33%|███▎      | 3467/10519 [53:55<1:49:00,  1.08it/s][NeMo W 2026-06-19 08:03:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 33%|███▎      | 3468/10519 [53:59<3:27:41,  1.77s/it][NeMo W 2026-06-19 08:03:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 33%|███▎      | 3469/10519 [54:00<3:09:43,  1.61s/it][NeMo W 2026-06-19 08:03:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 33%|███▎      | 3470/10519 [54:01<2:42:50,  1.39s/it][NeMo W 2026-06-19 08:03:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 33%|███▎      | 3471/10519 [54:02<2:28:35,  1.26s/it][NeMo W 2026-06-19 08:03:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 33%|███▎      | 3472/10519 [54:03<2:17:05,  1.17s/it][NeMo W 2026-06-19 08:03:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 33%|███▎      | 3473/10519 [54:04<2:10:48,  1.11s/it][NeMo W 2026-06-19 08:03:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 33%|███▎      | 3474/10519 [54:05<2:03:44,  1.05s/it][NeMo W 2026-06-19 08:03:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 33%|███▎      | 3475/10519 [54:06<2:03:00,  1.05s/it][NeMo W 2026-06-19 08:03:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 33%|███▎      | 3476/10519 [54:07<1:55:25,  1.02it/s][NeMo W 2026-06-19 08:03:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 33%|███▎      | 3477/10519 [54:08<1:58:13,  1.01s/it][NeMo W 2026-06-19 08:03:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 33%|███▎      | 3478/10519 [54:09<1:58:37,  1.01s/it][NeMo W 2026-06-19 08:03:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 33%|███▎      | 3479/10519 [54:10<1:56:36,  1.01it/s][NeMo W 2026-06-19 08:03:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:03:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 33%|███▎      | 3480/10519 [54:10<1:49:45,  1.07it/s][NeMo W 2026-06-19 08:03:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 3500 samples

[NeMo W 2026-06-19 08:04:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 33%|███▎      | 3501/10519 [54:31<2:12:27,  1.13s/it][NeMo W 2026-06-19 08:04:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 33%|███▎      | 3502/10519 [54:32<2:03:27,  1.06s/it][NeMo W 2026-06-19 08:04:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 33%|███▎      | 3503/10519 [54:33<2:02:39,  1.05s/it][NeMo W 2026-06-19 08:04:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 33%|███▎      | 3504/10519 [54:34<2:00:57,  1.03s/it][NeMo W 2026-06-19 08:04:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 33%|███▎      | 3505/10519 [54:35<1:58:41,  1.02s/it][NeMo W 2026-06-19 08:04:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 33%|███▎      | 3506/10519 [54:36<1:50:41,  1.06it/s][NeMo W 2026-06-19 08:04:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 33%|███▎      | 3507/10519 [54:37<1:51:26,  1.05it/s][NeMo W 2026-06-19 08:04:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 33%|███▎      | 3508/10519 [54:37<1:41:43,  1.15it/s][NeMo W 2026-06-19 08:04:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 33%|███▎      | 3509/10519 [54:38<1:44:41,  1.12it/s][NeMo W 2026-06-19 08:04:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.77it/s]
 33%|███▎      | 3510/10519 [54:39<1:46:19,  1.10it/s][NeMo W 2026-06-19 08:04:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.57it/s]
 33%|███▎      | 3511/10519 [54:40<1:42:13,  1.14it/s][NeMo W 2026-06-19 08:04:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 33%|███▎      | 3512/10519 [54:41<1:38:11,  1.19it/s][NeMo W 2026-06-19 08:04:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 33%|███▎      | 3513/10519 [54:42<1:42:16,  1.14it/s][NeMo W 2026-06-19 08:04:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 33%|███▎      | 3514/10519 [54:42<1:37:15,  1.20it/s][NeMo W 2026-06-19 08:04:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.01it/s]
 33%|███▎      | 3515/10519 [54:43<1:44:43,  1.11it/s][NeMo W 2026-06-19 08:04:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 33%|███▎      | 3516/10519 [54:44<1:45:51,  1.10it/s][NeMo W 2026-06-19 08:04:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.58it/s]
 33%|███▎      | 3517/10519 [54:45<1:40:36,  1.16it/s][NeMo W 2026-06-19 08:04:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 33%|███▎      | 3518/10519 [54:46<1:50:43,  1.05it/s][NeMo W 2026-06-19 08:04:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.66it/s]
 33%|███▎      | 3519/10519 [54:47<1:53:14,  1.03it/s][NeMo W 2026-06-19 08:04:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 33%|███▎      | 3520/10519 [54:48<1:46:51,  1.09it/s][NeMo W 2026-06-19 08:04:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 33%|███▎      | 3521/10519 [54:49<1:47:54,  1.08it/s][NeMo W 2026-06-19 08:04:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 33%|███▎      | 3522/10519 [54:50<1:43:34,  1.13it/s][NeMo W 2026-06-19 08:04:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 33%|███▎      | 3523/10519 [54:51<1:48:00,  1.08it/s][NeMo W 2026-06-19 08:04:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.76it/s]
 34%|███▎      | 3524/10519 [54:52<1:49:21,  1.07it/s][NeMo W 2026-06-19 08:04:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 34%|███▎      | 3525/10519 [54:53<1:50:44,  1.05it/s][NeMo W 2026-06-19 08:04:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 34%|███▎      | 3526/10519 [54:54<1:51:33,  1.04it/s][NeMo W 2026-06-19 08:04:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 34%|███▎      | 3527/10519 [54:55<1:43:45,  1.12it/s][NeMo W 2026-06-19 08:04:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 34%|███▎      | 3528/10519 [54:55<1:45:13,  1.11it/s][NeMo W 2026-06-19 08:04:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 34%|███▎      | 3529/10519 [54:56<1:46:52,  1.09it/s][NeMo W 2026-06-19 08:04:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]

Checkpoint saved: 3550 samples

[NeMo W 2026-06-19 08:04:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:04:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 34%|███▍      | 3551/10519 [55:18<2:22:50,  1.23s/it][NeMo W 2026-06-19 08:05:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 34%|███▍      | 3552/10519 [55:19<2:11:32,  1.13s/it][NeMo W 2026-06-19 08:05:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 34%|███▍      | 3553/10519 [55:20<2:09:36,  1.12s/it][NeMo W 2026-06-19 08:05:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 34%|███▍      | 3554/10519 [55:21<2:06:07,  1.09s/it][NeMo W 2026-06-19 08:05:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 34%|███▍      | 3555/10519 [55:22<2:04:44,  1.07s/it][NeMo W 2026-06-19 08:05:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 34%|███▍      | 3556/10519 [55:23<2:00:48,  1.04s/it][NeMo W 2026-06-19 08:05:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 34%|███▍      | 3557/10519 [55:24<1:56:46,  1.01s/it][NeMo W 2026-06-19 08:05:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 34%|███▍      | 3558/10519 [55:25<1:54:30,  1.01it/s][NeMo W 2026-06-19 08:05:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 34%|███▍      | 3559/10519 [55:26<1:53:47,  1.02it/s][NeMo W 2026-06-19 08:05:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 34%|███▍      | 3560/10519 [55:27<1:55:33,  1.00it/s][NeMo W 2026-06-19 08:05:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 34%|███▍      | 3561/10519 [55:28<1:52:38,  1.03it/s][NeMo W 2026-06-19 08:05:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 34%|███▍      | 3562/10519 [55:29<1:51:53,  1.04it/s][NeMo W 2026-06-19 08:05:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 34%|███▍      | 3563/10519 [55:30<1:42:45,  1.13it/s][NeMo W 2026-06-19 08:05:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.43it/s]
 34%|███▍      | 3564/10519 [55:31<1:50:57,  1.04it/s][NeMo W 2026-06-19 08:05:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 34%|███▍      | 3565/10519 [55:32<1:44:59,  1.10it/s][NeMo W 2026-06-19 08:05:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 34%|███▍      | 3566/10519 [55:33<1:43:49,  1.12it/s][NeMo W 2026-06-19 08:05:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 34%|███▍      | 3567/10519 [55:33<1:44:12,  1.11it/s][NeMo W 2026-06-19 08:05:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 34%|███▍      | 3568/10519 [55:34<1:46:02,  1.09it/s][NeMo W 2026-06-19 08:05:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 34%|███▍      | 3569/10519 [55:35<1:50:27,  1.05it/s][NeMo W 2026-06-19 08:05:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.28it/s]
 34%|███▍      | 3570/10519 [55:38<2:39:58,  1.38s/it][NeMo W 2026-06-19 08:05:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 34%|███▍      | 3571/10519 [55:39<2:23:51,  1.24s/it][NeMo W 2026-06-19 08:05:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 34%|███▍      | 3572/10519 [55:40<2:12:48,  1.15s/it][NeMo W 2026-06-19 08:05:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 34%|███▍      | 3573/10519 [55:41<2:08:29,  1.11s/it][NeMo W 2026-06-19 08:05:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.82it/s]
 34%|███▍      | 3574/10519 [55:42<2:05:45,  1.09s/it][NeMo W 2026-06-19 08:05:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 34%|███▍      | 3575/10519 [55:43<2:03:30,  1.07s/it][NeMo W 2026-06-19 08:05:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 34%|███▍      | 3576/10519 [55:44<2:00:38,  1.04s/it][NeMo W 2026-06-19 08:05:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.98it/s]
 34%|███▍      | 3577/10519 [55:45<1:59:03,  1.03s/it][NeMo W 2026-06-19 08:05:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 34%|███▍      | 3578/10519 [55:46<1:55:57,  1.00s/it][NeMo W 2026-06-19 08:05:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 34%|███▍      | 3579/10519 [55:46<1:47:22,  1.08it/s][NeMo W 2026-06-19 08:05:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]

Checkpoint saved: 3600 samples

[NeMo W 2026-06-19 08:05:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 34%|███▍      | 3601/10519 [56:08<2:06:51,  1.10s/it][NeMo W 2026-06-19 08:05:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 34%|███▍      | 3602/10519 [56:09<2:01:55,  1.06s/it][NeMo W 2026-06-19 08:05:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.05it/s]
 34%|███▍      | 3603/10519 [56:10<2:00:47,  1.05s/it][NeMo W 2026-06-19 08:05:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 34%|███▍      | 3604/10519 [56:11<1:57:17,  1.02s/it][NeMo W 2026-06-19 08:05:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 34%|███▍      | 3605/10519 [56:12<1:56:03,  1.01s/it][NeMo W 2026-06-19 08:05:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.08it/s]
 34%|███▍      | 3606/10519 [56:13<1:54:07,  1.01it/s][NeMo W 2026-06-19 08:05:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 34%|███▍      | 3607/10519 [56:15<2:02:53,  1.07s/it][NeMo W 2026-06-19 08:05:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 34%|███▍      | 3608/10519 [56:16<2:00:51,  1.05s/it][NeMo W 2026-06-19 08:05:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 34%|███▍      | 3609/10519 [56:16<1:51:26,  1.03it/s][NeMo W 2026-06-19 08:05:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 34%|███▍      | 3610/10519 [56:17<1:45:52,  1.09it/s][NeMo W 2026-06-19 08:05:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:05:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 34%|███▍      | 3611/10519 [56:18<1:53:52,  1.01it/s][NeMo W 2026-06-19 08:06:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 34%|███▍      | 3612/10519 [56:19<1:52:14,  1.03it/s][NeMo W 2026-06-19 08:06:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 34%|███▍      | 3613/10519 [56:20<1:54:04,  1.01it/s][NeMo W 2026-06-19 08:06:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 34%|███▍      | 3614/10519 [56:21<1:53:44,  1.01it/s][NeMo W 2026-06-19 08:06:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 34%|███▍      | 3615/10519 [56:22<1:51:05,  1.04it/s][NeMo W 2026-06-19 08:06:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.91it/s]
 34%|███▍      | 3616/10519 [56:23<1:51:10,  1.03it/s][NeMo W 2026-06-19 08:06:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 34%|███▍      | 3617/10519 [56:24<1:43:55,  1.11it/s][NeMo W 2026-06-19 08:06:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 34%|███▍      | 3618/10519 [56:25<1:45:50,  1.09it/s][NeMo W 2026-06-19 08:06:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 34%|███▍      | 3619/10519 [56:26<1:45:59,  1.08it/s][NeMo W 2026-06-19 08:06:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.29it/s]
 34%|███▍      | 3620/10519 [56:27<1:47:14,  1.07it/s][NeMo W 2026-06-19 08:06:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 34%|███▍      | 3621/10519 [56:28<1:48:47,  1.06it/s][NeMo W 2026-06-19 08:06:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 34%|███▍      | 3622/10519 [56:29<1:49:56,  1.05it/s][NeMo W 2026-06-19 08:06:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 34%|███▍      | 3623/10519 [56:30<1:44:57,  1.10it/s][NeMo W 2026-06-19 08:06:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 34%|███▍      | 3624/10519 [56:31<1:48:23,  1.06it/s][NeMo W 2026-06-19 08:06:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 34%|███▍      | 3625/10519 [56:31<1:49:08,  1.05it/s][NeMo W 2026-06-19 08:06:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 34%|███▍      | 3626/10519 [56:32<1:49:35,  1.05it/s][NeMo W 2026-06-19 08:06:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.60it/s]
 34%|███▍      | 3627/10519 [56:33<1:50:59,  1.03it/s][NeMo W 2026-06-19 08:06:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 34%|███▍      | 3628/10519 [56:35<1:58:53,  1.04s/it][NeMo W 2026-06-19 08:06:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 34%|███▍      | 3629/10519 [56:36<1:56:46,  1.02s/it][NeMo W 2026-06-19 08:06:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 35%|███▍      | 3630/10519 [56:37<1:56:40,  1.02s/it][NeMo W 2026-06-19 08:06:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 3650 samples

[NeMo W 2026-06-19 08:06:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 35%|███▍      | 3651/10519 [56:57<1:50:30,  1.04it/s][NeMo W 2026-06-19 08:06:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 35%|███▍      | 3652/10519 [56:58<1:51:55,  1.02it/s][NeMo W 2026-06-19 08:06:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 35%|███▍      | 3653/10519 [56:58<1:45:48,  1.08it/s][NeMo W 2026-06-19 08:06:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 35%|███▍      | 3654/10519 [56:59<1:48:56,  1.05it/s][NeMo W 2026-06-19 08:06:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 35%|███▍      | 3655/10519 [57:00<1:51:40,  1.02it/s][NeMo W 2026-06-19 08:06:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 35%|███▍      | 3656/10519 [57:01<1:51:29,  1.03it/s][NeMo W 2026-06-19 08:06:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.52it/s]
 35%|███▍      | 3657/10519 [57:02<1:51:29,  1.03it/s][NeMo W 2026-06-19 08:06:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 35%|███▍      | 3658/10519 [57:03<1:49:56,  1.04it/s][NeMo W 2026-06-19 08:06:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 35%|███▍      | 3659/10519 [57:04<1:43:22,  1.11it/s][NeMo W 2026-06-19 08:06:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.55it/s]
 35%|███▍      | 3660/10519 [57:05<1:51:16,  1.03it/s][NeMo W 2026-06-19 08:06:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 35%|███▍      | 3661/10519 [57:06<1:49:42,  1.04it/s][NeMo W 2026-06-19 08:06:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 35%|███▍      | 3662/10519 [57:07<1:50:15,  1.04it/s][NeMo W 2026-06-19 08:06:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 35%|███▍      | 3663/10519 [57:08<1:43:23,  1.11it/s][NeMo W 2026-06-19 08:06:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 35%|███▍      | 3664/10519 [57:09<2:02:42,  1.07s/it][NeMo W 2026-06-19 08:06:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 35%|███▍      | 3665/10519 [57:10<2:01:22,  1.06s/it][NeMo W 2026-06-19 08:06:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.97it/s]
 35%|███▍      | 3666/10519 [57:12<2:09:43,  1.14s/it][NeMo W 2026-06-19 08:06:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 35%|███▍      | 3667/10519 [57:13<2:05:02,  1.09s/it][NeMo W 2026-06-19 08:06:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]
 35%|███▍      | 3668/10519 [57:14<2:00:15,  1.05s/it][NeMo W 2026-06-19 08:06:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 35%|███▍      | 3669/10519 [57:15<1:55:35,  1.01s/it][NeMo W 2026-06-19 08:06:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 35%|███▍      | 3670/10519 [57:15<1:53:54,  1.00it/s][NeMo W 2026-06-19 08:06:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 35%|███▍      | 3671/10519 [57:17<1:59:14,  1.04s/it][NeMo W 2026-06-19 08:06:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 35%|███▍      | 3672/10519 [57:18<1:56:28,  1.02s/it][NeMo W 2026-06-19 08:06:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:06:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 35%|███▍      | 3673/10519 [57:19<1:54:55,  1.01s/it][NeMo W 2026-06-19 08:07:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 35%|███▍      | 3674/10519 [57:20<1:52:46,  1.01it/s][NeMo W 2026-06-19 08:07:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 35%|███▍      | 3675/10519 [57:20<1:52:12,  1.02it/s][NeMo W 2026-06-19 08:07:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.95it/s]
 35%|███▍      | 3676/10519 [57:22<1:53:23,  1.01it/s][NeMo W 2026-06-19 08:07:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 35%|███▍      | 3677/10519 [57:22<1:51:35,  1.02it/s][NeMo W 2026-06-19 08:07:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 35%|███▍      | 3678/10519 [57:23<1:51:49,  1.02it/s][NeMo W 2026-06-19 08:07:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 35%|███▍      | 3679/10519 [57:24<1:45:39,  1.08it/s][NeMo W 2026-06-19 08:07:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 35%|███▍      | 3680/10519 [57:25<1:48:06,  1.05it/s][NeMo W 2026-06-19 08:07:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 3700 samples

[NeMo W 2026-06-19 08:07:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 35%|███▌      | 3701/10519 [57:45<1:59:26,  1.05s/it][NeMo W 2026-06-19 08:07:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 35%|███▌      | 3702/10519 [57:46<1:54:05,  1.00s/it][NeMo W 2026-06-19 08:07:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 35%|███▌      | 3703/10519 [57:47<1:53:13,  1.00it/s][NeMo W 2026-06-19 08:07:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 35%|███▌      | 3704/10519 [57:50<3:04:41,  1.63s/it][NeMo W 2026-06-19 08:07:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 35%|███▌      | 3705/10519 [57:51<2:42:11,  1.43s/it][NeMo W 2026-06-19 08:07:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 35%|███▌      | 3706/10519 [57:52<2:25:31,  1.28s/it][NeMo W 2026-06-19 08:07:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 35%|███▌      | 3707/10519 [57:53<2:14:36,  1.19s/it][NeMo W 2026-06-19 08:07:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 35%|███▌      | 3708/10519 [57:54<2:05:34,  1.11s/it][NeMo W 2026-06-19 08:07:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 35%|███▌      | 3709/10519 [57:55<2:04:27,  1.10s/it][NeMo W 2026-06-19 08:07:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 35%|███▌      | 3710/10519 [57:56<1:54:08,  1.01s/it][NeMo W 2026-06-19 08:07:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 35%|███▌      | 3711/10519 [57:57<1:52:42,  1.01it/s][NeMo W 2026-06-19 08:07:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 35%|███▌      | 3712/10519 [57:58<1:53:12,  1.00it/s][NeMo W 2026-06-19 08:07:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 35%|███▌      | 3713/10519 [57:59<1:58:25,  1.04s/it][NeMo W 2026-06-19 08:07:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 35%|███▌      | 3714/10519 [58:00<1:55:45,  1.02s/it][NeMo W 2026-06-19 08:07:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 35%|███▌      | 3715/10519 [58:01<1:52:31,  1.01it/s][NeMo W 2026-06-19 08:07:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 35%|███▌      | 3716/10519 [58:02<1:51:31,  1.02it/s][NeMo W 2026-06-19 08:07:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 35%|███▌      | 3717/10519 [58:05<3:00:54,  1.60s/it][NeMo W 2026-06-19 08:07:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 35%|███▌      | 3718/10519 [58:06<2:40:22,  1.41s/it][NeMo W 2026-06-19 08:07:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 35%|███▌      | 3719/10519 [58:07<2:26:04,  1.29s/it][NeMo W 2026-06-19 08:07:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 35%|███▌      | 3720/10519 [58:08<2:14:20,  1.19s/it][NeMo W 2026-06-19 08:07:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.67it/s]
 35%|███▌      | 3721/10519 [58:09<2:05:15,  1.11s/it][NeMo W 2026-06-19 08:07:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 35%|███▌      | 3722/10519 [58:10<1:58:11,  1.04s/it][NeMo W 2026-06-19 08:07:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 35%|███▌      | 3723/10519 [58:11<1:55:38,  1.02s/it][NeMo W 2026-06-19 08:07:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 35%|███▌      | 3724/10519 [58:12<1:52:38,  1.01it/s][NeMo W 2026-06-19 08:07:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 35%|███▌      | 3725/10519 [58:13<1:54:02,  1.01s/it][NeMo W 2026-06-19 08:07:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 35%|███▌      | 3726/10519 [58:14<1:59:27,  1.06s/it][NeMo W 2026-06-19 08:07:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.42it/s]
 35%|███▌      | 3727/10519 [58:15<1:58:19,  1.05s/it][NeMo W 2026-06-19 08:07:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 35%|███▌      | 3728/10519 [58:16<1:50:42,  1.02it/s][NeMo W 2026-06-19 08:07:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.36it/s]
 35%|███▌      | 3729/10519 [58:17<1:53:42,  1.00s/it][NeMo W 2026-06-19 08:07:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:07:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]

Checkpoint saved: 3750 samples

[NeMo W 2026-06-19 08:08:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.48it/s]
 36%|███▌      | 3751/10519 [58:38<1:59:46,  1.06s/it][NeMo W 2026-06-19 08:08:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 36%|███▌      | 3752/10519 [58:39<1:53:58,  1.01s/it][NeMo W 2026-06-19 08:08:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 36%|███▌      | 3753/10519 [58:40<1:50:35,  1.02it/s][NeMo W 2026-06-19 08:08:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 36%|███▌      | 3754/10519 [58:40<1:50:03,  1.02it/s][NeMo W 2026-06-19 08:08:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 36%|███▌      | 3755/10519 [58:42<1:52:31,  1.00it/s][NeMo W 2026-06-19 08:08:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 36%|███▌      | 3756/10519 [58:43<1:51:59,  1.01it/s][NeMo W 2026-06-19 08:08:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 36%|███▌      | 3757/10519 [58:44<1:52:50,  1.00s/it][NeMo W 2026-06-19 08:08:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 36%|███▌      | 3758/10519 [58:45<2:00:39,  1.07s/it][NeMo W 2026-06-19 08:08:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 36%|███▌      | 3759/10519 [58:46<1:56:08,  1.03s/it][NeMo W 2026-06-19 08:08:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 36%|███▌      | 3760/10519 [58:47<1:56:10,  1.03s/it][NeMo W 2026-06-19 08:08:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 36%|███▌      | 3761/10519 [58:48<1:55:37,  1.03s/it][NeMo W 2026-06-19 08:08:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 36%|███▌      | 3762/10519 [58:49<1:53:03,  1.00s/it][NeMo W 2026-06-19 08:08:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
 36%|███▌      | 3763/10519 [58:50<1:53:52,  1.01s/it][NeMo W 2026-06-19 08:08:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 36%|███▌      | 3764/10519 [58:51<1:46:39,  1.06it/s][NeMo W 2026-06-19 08:08:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 36%|███▌      | 3765/10519 [58:52<1:48:50,  1.03it/s][NeMo W 2026-06-19 08:08:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
 36%|███▌      | 3766/10519 [58:52<1:47:21,  1.05it/s][NeMo W 2026-06-19 08:08:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
 36%|███▌      | 3767/10519 [58:53<1:46:12,  1.06it/s][NeMo W 2026-06-19 08:08:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.74it/s]
 36%|███▌      | 3768/10519 [58:54<1:45:51,  1.06it/s][NeMo W 2026-06-19 08:08:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 36%|███▌      | 3769/10519 [58:55<1:46:41,  1.05it/s][NeMo W 2026-06-19 08:08:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 36%|███▌      | 3770/10519 [58:56<1:47:09,  1.05it/s][NeMo W 2026-06-19 08:08:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 36%|███▌      | 3771/10519 [58:57<1:46:54,  1.05it/s][NeMo W 2026-06-19 08:08:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 36%|███▌      | 3772/10519 [58:58<1:48:19,  1.04it/s][NeMo W 2026-06-19 08:08:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 36%|███▌      | 3773/10519 [58:59<1:48:39,  1.03it/s][NeMo W 2026-06-19 08:08:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 36%|███▌      | 3774/10519 [59:00<1:49:52,  1.02it/s][NeMo W 2026-06-19 08:08:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 36%|███▌      | 3775/10519 [59:01<1:51:16,  1.01it/s][NeMo W 2026-06-19 08:08:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 36%|███▌      | 3776/10519 [59:02<1:44:13,  1.08it/s][NeMo W 2026-06-19 08:08:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 36%|███▌      | 3777/10519 [59:03<1:45:36,  1.06it/s][NeMo W 2026-06-19 08:08:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 36%|███▌      | 3778/10519 [59:04<1:39:48,  1.13it/s][NeMo W 2026-06-19 08:08:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 36%|███▌      | 3779/10519 [59:05<1:42:53,  1.09it/s][NeMo W 2026-06-19 08:08:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:08:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 36%|███▌      | 3780/10519 [59:06<1:44:48,  1.07it/s][NeMo W 2026-06-19 08:08:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 3800 samples

[NeMo W 2026-06-19 08:09:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 36%|███▌      | 3801/10519 [59:26<1:57:22,  1.05s/it][NeMo W 2026-06-19 08:09:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 36%|███▌      | 3802/10519 [59:27<1:56:32,  1.04s/it][NeMo W 2026-06-19 08:09:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 36%|███▌      | 3803/10519 [59:28<1:57:09,  1.05s/it][NeMo W 2026-06-19 08:09:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 36%|███▌      | 3804/10519 [59:29<1:53:47,  1.02s/it][NeMo W 2026-06-19 08:09:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 36%|███▌      | 3805/10519 [59:30<1:51:30,  1.00it/s][NeMo W 2026-06-19 08:09:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 36%|███▌      | 3806/10519 [59:31<1:49:47,  1.02it/s][NeMo W 2026-06-19 08:09:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 36%|███▌      | 3807/10519 [59:32<1:52:12,  1.00s/it][NeMo W 2026-06-19 08:09:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 36%|███▌      | 3808/10519 [59:33<1:53:09,  1.01s/it][NeMo W 2026-06-19 08:09:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 36%|███▌      | 3809/10519 [59:34<1:51:28,  1.00it/s][NeMo W 2026-06-19 08:09:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 36%|███▌      | 3810/10519 [59:35<1:49:56,  1.02it/s][NeMo W 2026-06-19 08:09:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 36%|███▌      | 3811/10519 [59:36<1:49:30,  1.02it/s][NeMo W 2026-06-19 08:09:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 36%|███▌      | 3812/10519 [59:37<1:48:49,  1.03it/s][NeMo W 2026-06-19 08:09:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 36%|███▌      | 3813/10519 [59:38<1:54:04,  1.02s/it][NeMo W 2026-06-19 08:09:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 36%|███▋      | 3814/10519 [59:39<1:58:14,  1.06s/it][NeMo W 2026-06-19 08:09:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]
 36%|███▋      | 3815/10519 [59:40<1:55:54,  1.04s/it][NeMo W 2026-06-19 08:09:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 36%|███▋      | 3816/10519 [59:41<1:52:04,  1.00s/it][NeMo W 2026-06-19 08:09:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 36%|███▋      | 3817/10519 [59:42<1:54:01,  1.02s/it][NeMo W 2026-06-19 08:09:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 36%|███▋      | 3818/10519 [59:43<1:44:45,  1.07it/s][NeMo W 2026-06-19 08:09:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 36%|███▋      | 3819/10519 [59:44<1:48:55,  1.03it/s][NeMo W 2026-06-19 08:09:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.86it/s]
 36%|███▋      | 3820/10519 [59:45<1:55:33,  1.03s/it][NeMo W 2026-06-19 08:09:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 36%|███▋      | 3821/10519 [59:46<1:54:17,  1.02s/it][NeMo W 2026-06-19 08:09:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 36%|███▋      | 3822/10519 [59:47<1:53:24,  1.02s/it][NeMo W 2026-06-19 08:09:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 36%|███▋      | 3823/10519 [59:48<1:50:46,  1.01it/s][NeMo W 2026-06-19 08:09:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 36%|███▋      | 3824/10519 [59:49<1:50:28,  1.01it/s][NeMo W 2026-06-19 08:09:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 36%|███▋      | 3825/10519 [59:50<1:47:55,  1.03it/s][NeMo W 2026-06-19 08:09:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 36%|███▋      | 3826/10519 [59:51<1:46:52,  1.04it/s][NeMo W 2026-06-19 08:09:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 36%|███▋      | 3827/10519 [59:52<1:41:35,  1.10it/s][NeMo W 2026-06-19 08:09:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 36%|███▋      | 3828/10519 [59:53<1:44:00,  1.07it/s][NeMo W 2026-06-19 08:09:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 36%|███▋      | 3829/10519 [59:54<1:43:39,  1.08it/s][NeMo W 2026-06-19 08:09:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]

Checkpoint saved: 3850 samples

[NeMo W 2026-06-19 08:09:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 37%|███▋      | 3851/10519 [1:00:17<2:00:55,  1.09s/it][NeMo W 2026-06-19 08:09:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 37%|███▋      | 3852/10519 [1:00:18<1:57:41,  1.06s/it][NeMo W 2026-06-19 08:09:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:09:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 37%|███▋      | 3853/10519 [1:00:18<1:52:14,  1.01s/it][NeMo W 2026-06-19 08:10:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 37%|███▋      | 3854/10519 [1:00:19<1:44:53,  1.06it/s][NeMo W 2026-06-19 08:10:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.36it/s]
 37%|███▋      | 3855/10519 [1:00:20<1:44:10,  1.07it/s][NeMo W 2026-06-19 08:10:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.25it/s]
 37%|███▋      | 3856/10519 [1:00:21<1:48:52,  1.02it/s][NeMo W 2026-06-19 08:10:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 37%|███▋      | 3857/10519 [1:00:22<1:48:41,  1.02it/s][NeMo W 2026-06-19 08:10:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 37%|███▋      | 3858/10519 [1:00:23<1:47:32,  1.03it/s][NeMo W 2026-06-19 08:10:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.17it/s]
 37%|███▋      | 3859/10519 [1:00:24<1:46:41,  1.04it/s][NeMo W 2026-06-19 08:10:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.89it/s]
 37%|███▋      | 3860/10519 [1:00:25<1:47:06,  1.04it/s][NeMo W 2026-06-19 08:10:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 37%|███▋      | 3861/10519 [1:00:26<1:53:10,  1.02s/it][NeMo W 2026-06-19 08:10:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 37%|███▋      | 3862/10519 [1:00:27<1:50:58,  1.00s/it][NeMo W 2026-06-19 08:10:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 37%|███▋      | 3863/10519 [1:00:28<1:52:48,  1.02s/it][NeMo W 2026-06-19 08:10:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 37%|███▋      | 3864/10519 [1:00:29<1:54:32,  1.03s/it][NeMo W 2026-06-19 08:10:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 37%|███▋      | 3865/10519 [1:00:30<1:52:43,  1.02s/it][NeMo W 2026-06-19 08:10:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 37%|███▋      | 3866/10519 [1:00:31<1:52:30,  1.01s/it][NeMo W 2026-06-19 08:10:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 37%|███▋      | 3867/10519 [1:00:32<1:54:39,  1.03s/it][NeMo W 2026-06-19 08:10:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 37%|███▋      | 3868/10519 [1:00:33<1:56:03,  1.05s/it][NeMo W 2026-06-19 08:10:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 37%|███▋      | 3869/10519 [1:00:34<1:47:11,  1.03it/s][NeMo W 2026-06-19 08:10:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 37%|███▋      | 3870/10519 [1:00:35<1:47:29,  1.03it/s][NeMo W 2026-06-19 08:10:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 37%|███▋      | 3871/10519 [1:00:36<1:42:33,  1.08it/s][NeMo W 2026-06-19 08:10:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.00it/s]
 37%|███▋      | 3872/10519 [1:00:37<1:44:18,  1.06it/s][NeMo W 2026-06-19 08:10:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.29it/s]
 37%|███▋      | 3873/10519 [1:00:38<1:47:00,  1.04it/s][NeMo W 2026-06-19 08:10:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 37%|███▋      | 3874/10519 [1:00:39<1:53:39,  1.03s/it][NeMo W 2026-06-19 08:10:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 37%|███▋      | 3875/10519 [1:00:40<1:51:02,  1.00s/it][NeMo W 2026-06-19 08:10:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 37%|███▋      | 3876/10519 [1:00:41<1:51:31,  1.01s/it][NeMo W 2026-06-19 08:10:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 37%|███▋      | 3877/10519 [1:00:42<1:49:08,  1.01it/s][NeMo W 2026-06-19 08:10:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 37%|███▋      | 3878/10519 [1:00:43<1:47:30,  1.03it/s][NeMo W 2026-06-19 08:10:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 37%|███▋      | 3879/10519 [1:00:44<1:39:00,  1.12it/s][NeMo W 2026-06-19 08:10:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]

Checkpoint saved: 3900 samples

[NeMo W 2026-06-19 08:10:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 37%|███▋      | 3901/10519 [1:01:06<2:10:12,  1.18s/it][NeMo W 2026-06-19 08:10:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 37%|███▋      | 3902/10519 [1:01:07<2:02:01,  1.11s/it][NeMo W 2026-06-19 08:10:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.17it/s]
 37%|███▋      | 3903/10519 [1:01:08<2:00:41,  1.09s/it][NeMo W 2026-06-19 08:10:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 37%|███▋      | 3904/10519 [1:01:09<1:56:09,  1.05s/it][NeMo W 2026-06-19 08:10:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 37%|███▋      | 3905/10519 [1:01:10<1:55:08,  1.04s/it][NeMo W 2026-06-19 08:10:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 37%|███▋      | 3906/10519 [1:01:11<1:53:47,  1.03s/it][NeMo W 2026-06-19 08:10:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 37%|███▋      | 3907/10519 [1:01:12<1:50:44,  1.00s/it][NeMo W 2026-06-19 08:10:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 37%|███▋      | 3908/10519 [1:01:13<1:51:12,  1.01s/it][NeMo W 2026-06-19 08:10:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 37%|███▋      | 3909/10519 [1:01:14<1:49:44,  1.00it/s][NeMo W 2026-06-19 08:10:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 37%|███▋      | 3910/10519 [1:01:16<2:13:44,  1.21s/it][NeMo W 2026-06-19 08:10:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 37%|███▋      | 3911/10519 [1:01:17<2:05:09,  1.14s/it][NeMo W 2026-06-19 08:10:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 37%|███▋      | 3912/10519 [1:01:18<1:59:27,  1.08s/it][NeMo W 2026-06-19 08:10:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:10:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 37%|███▋      | 3913/10519 [1:01:19<1:56:15,  1.06s/it][NeMo W 2026-06-19 08:11:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 37%|███▋      | 3914/10519 [1:01:19<1:48:49,  1.01it/s][NeMo W 2026-06-19 08:11:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 37%|███▋      | 3915/10519 [1:01:20<1:46:30,  1.03it/s][NeMo W 2026-06-19 08:11:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.75it/s]
 37%|███▋      | 3916/10519 [1:01:21<1:45:12,  1.05it/s][NeMo W 2026-06-19 08:11:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 37%|███▋      | 3917/10519 [1:01:22<1:48:16,  1.02it/s][NeMo W 2026-06-19 08:11:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 37%|███▋      | 3918/10519 [1:01:23<1:46:38,  1.03it/s][NeMo W 2026-06-19 08:11:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 37%|███▋      | 3919/10519 [1:01:24<1:45:37,  1.04it/s][NeMo W 2026-06-19 08:11:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.06it/s]
 37%|███▋      | 3920/10519 [1:01:25<1:45:15,  1.04it/s][NeMo W 2026-06-19 08:11:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 37%|███▋      | 3921/10519 [1:01:26<1:45:51,  1.04it/s][NeMo W 2026-06-19 08:11:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 37%|███▋      | 3922/10519 [1:01:27<1:46:15,  1.03it/s][NeMo W 2026-06-19 08:11:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 37%|███▋      | 3923/10519 [1:01:28<1:39:09,  1.11it/s][NeMo W 2026-06-19 08:11:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 37%|███▋      | 3924/10519 [1:01:29<1:43:48,  1.06it/s][NeMo W 2026-06-19 08:11:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.73it/s]
 37%|███▋      | 3925/10519 [1:01:30<1:46:53,  1.03it/s][NeMo W 2026-06-19 08:11:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 37%|███▋      | 3926/10519 [1:01:31<1:38:09,  1.12it/s][NeMo W 2026-06-19 08:11:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 37%|███▋      | 3927/10519 [1:01:32<1:43:00,  1.07it/s][NeMo W 2026-06-19 08:11:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.74it/s]
 37%|███▋      | 3928/10519 [1:01:32<1:41:56,  1.08it/s][NeMo W 2026-06-19 08:11:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
 37%|███▋      | 3929/10519 [1:01:33<1:40:54,  1.09it/s][NeMo W 2026-06-19 08:11:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 3950 samples

[NeMo W 2026-06-19 08:11:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 38%|███▊      | 3951/10519 [1:01:55<2:00:10,  1.10s/it][NeMo W 2026-06-19 08:11:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 38%|███▊      | 3952/10519 [1:01:56<2:02:36,  1.12s/it][NeMo W 2026-06-19 08:11:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 38%|███▊      | 3953/10519 [1:01:57<1:57:24,  1.07s/it][NeMo W 2026-06-19 08:11:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 38%|███▊      | 3954/10519 [1:01:58<1:53:22,  1.04s/it][NeMo W 2026-06-19 08:11:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 38%|███▊      | 3955/10519 [1:01:59<1:49:46,  1.00s/it][NeMo W 2026-06-19 08:11:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.03it/s]
 38%|███▊      | 3956/10519 [1:02:00<1:47:12,  1.02it/s][NeMo W 2026-06-19 08:11:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 38%|███▊      | 3957/10519 [1:02:01<1:38:11,  1.11it/s][NeMo W 2026-06-19 08:11:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 38%|███▊      | 3958/10519 [1:02:02<1:42:16,  1.07it/s][NeMo W 2026-06-19 08:11:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 38%|███▊      | 3959/10519 [1:02:03<2:07:22,  1.17s/it][NeMo W 2026-06-19 08:11:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 38%|███▊      | 3960/10519 [1:02:04<1:58:02,  1.08s/it][NeMo W 2026-06-19 08:11:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 38%|███▊      | 3961/10519 [1:02:06<2:02:33,  1.12s/it][NeMo W 2026-06-19 08:11:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.44it/s]
 38%|███▊      | 3962/10519 [1:02:06<1:51:58,  1.02s/it][NeMo W 2026-06-19 08:11:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 38%|███▊      | 3963/10519 [1:02:08<2:06:05,  1.15s/it][NeMo W 2026-06-19 08:11:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 38%|███▊      | 3964/10519 [1:02:09<2:00:57,  1.11s/it][NeMo W 2026-06-19 08:11:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 38%|███▊      | 3965/10519 [1:02:10<1:57:34,  1.08s/it][NeMo W 2026-06-19 08:11:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 38%|███▊      | 3966/10519 [1:02:11<1:56:42,  1.07s/it][NeMo W 2026-06-19 08:11:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 38%|███▊      | 3967/10519 [1:02:12<1:59:28,  1.09s/it][NeMo W 2026-06-19 08:11:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 38%|███▊      | 3968/10519 [1:02:13<1:56:40,  1.07s/it][NeMo W 2026-06-19 08:11:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 38%|███▊      | 3969/10519 [1:02:14<1:52:52,  1.03s/it][NeMo W 2026-06-19 08:11:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 38%|███▊      | 3970/10519 [1:02:15<1:49:12,  1.00s/it][NeMo W 2026-06-19 08:11:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 38%|███▊      | 3971/10519 [1:02:16<1:47:12,  1.02it/s][NeMo W 2026-06-19 08:11:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 38%|███▊      | 3972/10519 [1:02:17<1:45:54,  1.03it/s][NeMo W 2026-06-19 08:11:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 38%|███▊      | 3973/10519 [1:02:18<1:46:35,  1.02it/s][NeMo W 2026-06-19 08:11:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:11:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.71it/s]
 38%|███▊      | 3974/10519 [1:02:19<1:40:25,  1.09it/s][NeMo W 2026-06-19 08:12:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.49it/s]
 38%|███▊      | 3975/10519 [1:02:20<1:50:00,  1.01s/it][NeMo W 2026-06-19 08:12:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.18it/s]
 38%|███▊      | 3976/10519 [1:02:21<1:50:50,  1.02s/it][NeMo W 2026-06-19 08:12:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 38%|███▊      | 3977/10519 [1:02:22<1:49:50,  1.01s/it][NeMo W 2026-06-19 08:12:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 38%|███▊      | 3978/10519 [1:02:23<1:47:56,  1.01it/s][NeMo W 2026-06-19 08:12:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 38%|███▊      | 3979/10519 [1:02:24<1:55:19,  1.06s/it][NeMo W 2026-06-19 08:12:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 4000 samples

[NeMo W 2026-06-19 08:12:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.30it/s]
 38%|███▊      | 4001/10519 [1:02:46<2:06:27,  1.16s/it][NeMo W 2026-06-19 08:12:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 38%|███▊      | 4002/10519 [1:02:47<2:02:28,  1.13s/it][NeMo W 2026-06-19 08:12:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 38%|███▊      | 4003/10519 [1:02:48<1:48:11,  1.00it/s][NeMo W 2026-06-19 08:12:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.43it/s]
 38%|███▊      | 4004/10519 [1:02:48<1:46:51,  1.02it/s][NeMo W 2026-06-19 08:12:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.31it/s]
 38%|███▊      | 4005/10519 [1:02:50<1:49:40,  1.01s/it][NeMo W 2026-06-19 08:12:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.24it/s]
 38%|███▊      | 4006/10519 [1:02:50<1:46:03,  1.02it/s][NeMo W 2026-06-19 08:12:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 38%|███▊      | 4007/10519 [1:02:51<1:45:00,  1.03it/s][NeMo W 2026-06-19 08:12:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 38%|███▊      | 4008/10519 [1:02:52<1:45:59,  1.02it/s][NeMo W 2026-06-19 08:12:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 38%|███▊      | 4009/10519 [1:02:53<1:48:32,  1.00s/it][NeMo W 2026-06-19 08:12:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 38%|███▊      | 4010/10519 [1:02:54<1:41:07,  1.07it/s][NeMo W 2026-06-19 08:12:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 38%|███▊      | 4011/10519 [1:02:55<1:41:49,  1.07it/s][NeMo W 2026-06-19 08:12:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.72it/s]
 38%|███▊      | 4012/10519 [1:02:56<1:44:00,  1.04it/s][NeMo W 2026-06-19 08:12:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.71it/s]
 38%|███▊      | 4013/10519 [1:02:57<1:45:20,  1.03it/s][NeMo W 2026-06-19 08:12:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.68it/s]
 38%|███▊      | 4014/10519 [1:02:58<1:49:48,  1.01s/it][NeMo W 2026-06-19 08:12:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 38%|███▊      | 4015/10519 [1:02:59<1:48:31,  1.00s/it][NeMo W 2026-06-19 08:12:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.66it/s]
 38%|███▊      | 4016/10519 [1:03:00<1:46:54,  1.01it/s][NeMo W 2026-06-19 08:12:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 38%|███▊      | 4017/10519 [1:03:01<1:47:00,  1.01it/s][NeMo W 2026-06-19 08:12:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 38%|███▊      | 4018/10519 [1:03:02<1:38:58,  1.09it/s][NeMo W 2026-06-19 08:12:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 38%|███▊      | 4019/10519 [1:03:03<1:40:50,  1.07it/s][NeMo W 2026-06-19 08:12:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.06it/s]
 38%|███▊      | 4020/10519 [1:03:04<1:35:47,  1.13it/s][NeMo W 2026-06-19 08:12:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 38%|███▊      | 4021/10519 [1:03:05<1:34:02,  1.15it/s][NeMo W 2026-06-19 08:12:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 38%|███▊      | 4022/10519 [1:03:05<1:30:57,  1.19it/s][NeMo W 2026-06-19 08:12:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 38%|███▊      | 4023/10519 [1:03:06<1:35:10,  1.14it/s][NeMo W 2026-06-19 08:12:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 38%|███▊      | 4024/10519 [1:03:07<1:42:29,  1.06it/s][NeMo W 2026-06-19 08:12:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.17it/s]
 38%|███▊      | 4025/10519 [1:03:09<1:47:46,  1.00it/s][NeMo W 2026-06-19 08:12:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.36it/s]
 38%|███▊      | 4026/10519 [1:03:09<1:47:18,  1.01it/s][NeMo W 2026-06-19 08:12:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 38%|███▊      | 4027/10519 [1:03:10<1:44:10,  1.04it/s][NeMo W 2026-06-19 08:12:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.63it/s]
 38%|███▊      | 4028/10519 [1:03:11<1:45:34,  1.02it/s][NeMo W 2026-06-19 08:12:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:12:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 38%|███▊      | 4029/10519 [1:03:12<1:45:43,  1.02it/s][NeMo W 2026-06-19 08:12:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 4050 samples

[NeMo W 2026-06-19 08:13:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 39%|███▊      | 4051/10519 [1:03:34<1:58:23,  1.10s/it][NeMo W 2026-06-19 08:13:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 39%|███▊      | 4052/10519 [1:03:35<1:45:41,  1.02it/s][NeMo W 2026-06-19 08:13:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 39%|███▊      | 4053/10519 [1:03:36<1:40:32,  1.07it/s][NeMo W 2026-06-19 08:13:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 39%|███▊      | 4054/10519 [1:03:37<1:42:31,  1.05it/s][NeMo W 2026-06-19 08:13:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 39%|███▊      | 4055/10519 [1:03:38<1:43:34,  1.04it/s][NeMo W 2026-06-19 08:13:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 39%|███▊      | 4056/10519 [1:03:39<1:43:35,  1.04it/s][NeMo W 2026-06-19 08:13:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 39%|███▊      | 4057/10519 [1:03:40<1:37:26,  1.11it/s][NeMo W 2026-06-19 08:13:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 39%|███▊      | 4058/10519 [1:03:40<1:34:14,  1.14it/s][NeMo W 2026-06-19 08:13:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 39%|███▊      | 4059/10519 [1:03:41<1:38:57,  1.09it/s][NeMo W 2026-06-19 08:13:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 39%|███▊      | 4060/10519 [1:03:42<1:32:37,  1.16it/s][NeMo W 2026-06-19 08:13:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]
 39%|███▊      | 4061/10519 [1:03:43<1:36:23,  1.12it/s][NeMo W 2026-06-19 08:13:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 39%|███▊      | 4062/10519 [1:03:44<1:39:56,  1.08it/s][NeMo W 2026-06-19 08:13:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 39%|███▊      | 4063/10519 [1:03:45<1:32:56,  1.16it/s][NeMo W 2026-06-19 08:13:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.82it/s]
 39%|███▊      | 4064/10519 [1:03:46<1:35:15,  1.13it/s][NeMo W 2026-06-19 08:13:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.25it/s]
 39%|███▊      | 4065/10519 [1:03:47<1:36:45,  1.11it/s][NeMo W 2026-06-19 08:13:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 39%|███▊      | 4066/10519 [1:03:47<1:34:21,  1.14it/s][NeMo W 2026-06-19 08:13:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 39%|███▊      | 4067/10519 [1:03:49<1:39:41,  1.08it/s][NeMo W 2026-06-19 08:13:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 39%|███▊      | 4068/10519 [1:03:49<1:36:44,  1.11it/s][NeMo W 2026-06-19 08:13:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 39%|███▊      | 4069/10519 [1:03:50<1:40:38,  1.07it/s][NeMo W 2026-06-19 08:13:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 39%|███▊      | 4070/10519 [1:03:51<1:40:40,  1.07it/s][NeMo W 2026-06-19 08:13:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 39%|███▊      | 4071/10519 [1:03:52<1:41:41,  1.06it/s][NeMo W 2026-06-19 08:13:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 39%|███▊      | 4072/10519 [1:03:53<1:44:14,  1.03it/s][NeMo W 2026-06-19 08:13:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 39%|███▊      | 4073/10519 [1:03:54<1:45:20,  1.02it/s][NeMo W 2026-06-19 08:13:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 39%|███▊      | 4074/10519 [1:03:55<1:43:43,  1.04it/s][NeMo W 2026-06-19 08:13:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 39%|███▊      | 4075/10519 [1:03:56<1:44:06,  1.03it/s][NeMo W 2026-06-19 08:13:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.07it/s]
 39%|███▊      | 4076/10519 [1:03:57<1:44:46,  1.02it/s][NeMo W 2026-06-19 08:13:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 39%|███▉      | 4077/10519 [1:03:58<1:45:09,  1.02it/s][NeMo W 2026-06-19 08:13:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 39%|███▉      | 4078/10519 [1:03:59<1:49:20,  1.02s/it][NeMo W 2026-06-19 08:13:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 39%|███▉      | 4079/10519 [1:04:00<1:46:16,  1.01it/s][NeMo W 2026-06-19 08:13:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:13:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]

Checkpoint saved: 4100 samples

[NeMo W 2026-06-19 08:14:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 39%|███▉      | 4101/10519 [1:04:23<2:14:05,  1.25s/it][NeMo W 2026-06-19 08:14:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 39%|███▉      | 4102/10519 [1:04:24<2:10:58,  1.22s/it][NeMo W 2026-06-19 08:14:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 39%|███▉      | 4103/10519 [1:04:25<2:01:40,  1.14s/it][NeMo W 2026-06-19 08:14:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 39%|███▉      | 4104/10519 [1:04:26<1:58:24,  1.11s/it][NeMo W 2026-06-19 08:14:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.59it/s]
 39%|███▉      | 4105/10519 [1:04:27<1:54:42,  1.07s/it][NeMo W 2026-06-19 08:14:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 39%|███▉      | 4106/10519 [1:04:28<1:52:12,  1.05s/it][NeMo W 2026-06-19 08:14:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 39%|███▉      | 4107/10519 [1:04:29<1:57:52,  1.10s/it][NeMo W 2026-06-19 08:14:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.00it/s]
 39%|███▉      | 4108/10519 [1:04:30<1:50:25,  1.03s/it][NeMo W 2026-06-19 08:14:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 39%|███▉      | 4109/10519 [1:04:31<1:49:47,  1.03s/it][NeMo W 2026-06-19 08:14:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 39%|███▉      | 4110/10519 [1:04:32<1:48:52,  1.02s/it][NeMo W 2026-06-19 08:14:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 39%|███▉      | 4111/10519 [1:04:33<1:47:05,  1.00s/it][NeMo W 2026-06-19 08:14:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 39%|███▉      | 4112/10519 [1:04:33<1:39:56,  1.07it/s][NeMo W 2026-06-19 08:14:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.16it/s]
 39%|███▉      | 4113/10519 [1:04:35<1:43:08,  1.04it/s][NeMo W 2026-06-19 08:14:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 39%|███▉      | 4114/10519 [1:04:35<1:40:11,  1.07it/s][NeMo W 2026-06-19 08:14:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 39%|███▉      | 4115/10519 [1:04:36<1:41:48,  1.05it/s][NeMo W 2026-06-19 08:14:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 39%|███▉      | 4116/10519 [1:04:37<1:43:27,  1.03it/s][NeMo W 2026-06-19 08:14:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 39%|███▉      | 4117/10519 [1:04:38<1:37:22,  1.10it/s][NeMo W 2026-06-19 08:14:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 39%|███▉      | 4118/10519 [1:04:39<1:40:30,  1.06it/s][NeMo W 2026-06-19 08:14:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.04it/s]
 39%|███▉      | 4119/10519 [1:04:40<1:42:58,  1.04it/s][NeMo W 2026-06-19 08:14:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 39%|███▉      | 4120/10519 [1:04:41<1:36:16,  1.11it/s][NeMo W 2026-06-19 08:14:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 39%|███▉      | 4121/10519 [1:04:42<1:34:32,  1.13it/s][NeMo W 2026-06-19 08:14:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.93it/s]
 39%|███▉      | 4122/10519 [1:04:43<1:38:32,  1.08it/s][NeMo W 2026-06-19 08:14:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 39%|███▉      | 4123/10519 [1:04:44<1:35:42,  1.11it/s][NeMo W 2026-06-19 08:14:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.12it/s]
 39%|███▉      | 4124/10519 [1:04:45<1:36:45,  1.10it/s][NeMo W 2026-06-19 08:14:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 39%|███▉      | 4125/10519 [1:04:46<1:39:16,  1.07it/s][NeMo W 2026-06-19 08:14:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 39%|███▉      | 4126/10519 [1:04:47<1:50:18,  1.04s/it][NeMo W 2026-06-19 08:14:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 39%|███▉      | 4127/10519 [1:04:48<1:44:26,  1.02it/s][NeMo W 2026-06-19 08:14:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 39%|███▉      | 4128/10519 [1:04:49<1:46:16,  1.00it/s][NeMo W 2026-06-19 08:14:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.57it/s]
 39%|███▉      | 4129/10519 [1:04:50<1:44:44,  1.02it/s][NeMo W 2026-06-19 08:14:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 4150 samples

[NeMo W 2026-06-19 08:14:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 39%|███▉      | 4151/10519 [1:05:11<1:53:42,  1.07s/it][NeMo W 2026-06-19 08:14:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.62it/s]
 39%|███▉      | 4152/10519 [1:05:12<1:51:28,  1.05s/it][NeMo W 2026-06-19 08:14:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 39%|███▉      | 4153/10519 [1:05:13<1:42:52,  1.03it/s][NeMo W 2026-06-19 08:14:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 39%|███▉      | 4154/10519 [1:05:14<1:41:58,  1.04it/s][NeMo W 2026-06-19 08:14:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 39%|███▉      | 4155/10519 [1:05:15<1:37:44,  1.09it/s][NeMo W 2026-06-19 08:14:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.00it/s]
 40%|███▉      | 4156/10519 [1:05:16<1:38:29,  1.08it/s][NeMo W 2026-06-19 08:14:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 40%|███▉      | 4157/10519 [1:05:17<1:38:45,  1.07it/s][NeMo W 2026-06-19 08:14:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 40%|███▉      | 4158/10519 [1:05:18<1:40:23,  1.06it/s][NeMo W 2026-06-19 08:14:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:14:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 40%|███▉      | 4159/10519 [1:05:19<1:39:51,  1.06it/s][NeMo W 2026-06-19 08:15:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.68it/s]
 40%|███▉      | 4160/10519 [1:05:20<1:39:22,  1.07it/s][NeMo W 2026-06-19 08:15:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.72it/s]
 40%|███▉      | 4161/10519 [1:05:21<1:40:48,  1.05it/s][NeMo W 2026-06-19 08:15:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 40%|███▉      | 4162/10519 [1:05:22<1:47:23,  1.01s/it][NeMo W 2026-06-19 08:15:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 40%|███▉      | 4163/10519 [1:05:23<1:48:31,  1.02s/it][NeMo W 2026-06-19 08:15:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 40%|███▉      | 4164/10519 [1:05:24<1:46:17,  1.00s/it][NeMo W 2026-06-19 08:15:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 40%|███▉      | 4165/10519 [1:05:25<1:46:31,  1.01s/it][NeMo W 2026-06-19 08:15:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 40%|███▉      | 4166/10519 [1:05:26<1:47:45,  1.02s/it][NeMo W 2026-06-19 08:15:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
 40%|███▉      | 4167/10519 [1:05:27<1:46:35,  1.01s/it][NeMo W 2026-06-19 08:15:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 40%|███▉      | 4168/10519 [1:05:28<1:45:34,  1.00it/s][NeMo W 2026-06-19 08:15:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.46it/s]
 40%|███▉      | 4169/10519 [1:05:29<1:44:00,  1.02it/s][NeMo W 2026-06-19 08:15:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 40%|███▉      | 4170/10519 [1:05:30<1:48:35,  1.03s/it][NeMo W 2026-06-19 08:15:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 40%|███▉      | 4171/10519 [1:05:31<1:47:01,  1.01s/it][NeMo W 2026-06-19 08:15:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 40%|███▉      | 4172/10519 [1:05:32<1:40:24,  1.05it/s][NeMo W 2026-06-19 08:15:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.66it/s]
 40%|███▉      | 4173/10519 [1:05:33<1:43:22,  1.02it/s][NeMo W 2026-06-19 08:15:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.98it/s]
 40%|███▉      | 4174/10519 [1:05:34<1:41:23,  1.04it/s][NeMo W 2026-06-19 08:15:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 40%|███▉      | 4175/10519 [1:05:35<1:41:50,  1.04it/s][NeMo W 2026-06-19 08:15:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 40%|███▉      | 4176/10519 [1:05:35<1:42:09,  1.03it/s][NeMo W 2026-06-19 08:15:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 40%|███▉      | 4177/10519 [1:05:36<1:42:01,  1.04it/s][NeMo W 2026-06-19 08:15:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 40%|███▉      | 4178/10519 [1:05:37<1:43:57,  1.02it/s][NeMo W 2026-06-19 08:15:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 40%|███▉      | 4179/10519 [1:05:38<1:42:59,  1.03it/s][NeMo W 2026-06-19 08:15:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]

Checkpoint saved: 4200 samples

[NeMo W 2026-06-19 08:15:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.41it/s]
 40%|███▉      | 4201/10519 [1:06:01<2:06:31,  1.20s/it][NeMo W 2026-06-19 08:15:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 40%|███▉      | 4202/10519 [1:06:02<1:53:26,  1.08s/it][NeMo W 2026-06-19 08:15:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 40%|███▉      | 4203/10519 [1:06:03<1:49:00,  1.04s/it][NeMo W 2026-06-19 08:15:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 40%|███▉      | 4204/10519 [1:06:04<1:45:56,  1.01s/it][NeMo W 2026-06-19 08:15:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
 40%|███▉      | 4205/10519 [1:06:05<1:43:20,  1.02it/s][NeMo W 2026-06-19 08:15:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 40%|███▉      | 4206/10519 [1:06:06<1:42:49,  1.02it/s][NeMo W 2026-06-19 08:15:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 40%|███▉      | 4207/10519 [1:06:07<1:41:21,  1.04it/s][NeMo W 2026-06-19 08:15:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.78it/s]
 40%|████      | 4208/10519 [1:06:08<1:43:20,  1.02it/s][NeMo W 2026-06-19 08:15:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.80it/s]
 40%|████      | 4209/10519 [1:06:10<2:25:07,  1.38s/it][NeMo W 2026-06-19 08:15:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 40%|████      | 4210/10519 [1:06:11<2:14:07,  1.28s/it][NeMo W 2026-06-19 08:15:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 40%|████      | 4211/10519 [1:06:12<2:01:14,  1.15s/it][NeMo W 2026-06-19 08:15:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 40%|████      | 4212/10519 [1:06:13<1:54:16,  1.09s/it][NeMo W 2026-06-19 08:15:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 40%|████      | 4213/10519 [1:06:14<1:51:57,  1.07s/it][NeMo W 2026-06-19 08:15:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 40%|████      | 4214/10519 [1:06:15<1:49:16,  1.04s/it][NeMo W 2026-06-19 08:15:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 40%|████      | 4215/10519 [1:06:16<1:48:20,  1.03s/it][NeMo W 2026-06-19 08:15:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 40%|████      | 4216/10519 [1:06:17<1:40:36,  1.04it/s][NeMo W 2026-06-19 08:15:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 40%|████      | 4217/10519 [1:06:17<1:35:44,  1.10it/s][NeMo W 2026-06-19 08:15:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:15:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 40%|████      | 4218/10519 [1:06:18<1:34:46,  1.11it/s][NeMo W 2026-06-19 08:16:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 40%|████      | 4219/10519 [1:06:19<1:40:59,  1.04it/s][NeMo W 2026-06-19 08:16:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 40%|████      | 4220/10519 [1:06:20<1:33:51,  1.12it/s][NeMo W 2026-06-19 08:16:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 40%|████      | 4221/10519 [1:06:21<1:39:33,  1.05it/s][NeMo W 2026-06-19 08:16:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 40%|████      | 4222/10519 [1:06:22<1:38:45,  1.06it/s][NeMo W 2026-06-19 08:16:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 40%|████      | 4223/10519 [1:06:23<1:48:04,  1.03s/it][NeMo W 2026-06-19 08:16:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 40%|████      | 4224/10519 [1:06:24<1:46:51,  1.02s/it][NeMo W 2026-06-19 08:16:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 40%|████      | 4225/10519 [1:06:25<1:44:41,  1.00it/s][NeMo W 2026-06-19 08:16:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 40%|████      | 4226/10519 [1:06:26<1:42:06,  1.03it/s][NeMo W 2026-06-19 08:16:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 40%|████      | 4227/10519 [1:06:27<1:40:42,  1.04it/s][NeMo W 2026-06-19 08:16:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 40%|████      | 4228/10519 [1:06:28<1:36:50,  1.08it/s][NeMo W 2026-06-19 08:16:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 40%|████      | 4229/10519 [1:06:29<1:37:18,  1.08it/s][NeMo W 2026-06-19 08:16:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]

Checkpoint saved: 4250 samples

[NeMo W 2026-06-19 08:16:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
 40%|████      | 4251/10519 [1:06:49<1:38:55,  1.06it/s][NeMo W 2026-06-19 08:16:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 40%|████      | 4252/10519 [1:06:50<1:39:24,  1.05it/s][NeMo W 2026-06-19 08:16:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.21it/s]
 40%|████      | 4253/10519 [1:06:51<1:43:14,  1.01it/s][NeMo W 2026-06-19 08:16:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 40%|████      | 4254/10519 [1:06:52<1:40:29,  1.04it/s][NeMo W 2026-06-19 08:16:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 40%|████      | 4255/10519 [1:06:53<1:41:44,  1.03it/s][NeMo W 2026-06-19 08:16:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 40%|████      | 4256/10519 [1:06:54<1:41:16,  1.03it/s][NeMo W 2026-06-19 08:16:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 40%|████      | 4257/10519 [1:06:55<1:35:48,  1.09it/s][NeMo W 2026-06-19 08:16:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 40%|████      | 4258/10519 [1:06:56<1:36:41,  1.08it/s][NeMo W 2026-06-19 08:16:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 40%|████      | 4259/10519 [1:06:57<1:35:59,  1.09it/s][NeMo W 2026-06-19 08:16:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 40%|████      | 4260/10519 [1:06:58<1:36:22,  1.08it/s][NeMo W 2026-06-19 08:16:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.96it/s]
 41%|████      | 4261/10519 [1:06:59<1:37:02,  1.07it/s][NeMo W 2026-06-19 08:16:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 41%|████      | 4262/10519 [1:07:00<1:38:27,  1.06it/s][NeMo W 2026-06-19 08:16:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 41%|████      | 4263/10519 [1:07:00<1:36:38,  1.08it/s][NeMo W 2026-06-19 08:16:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 41%|████      | 4264/10519 [1:07:01<1:38:14,  1.06it/s][NeMo W 2026-06-19 08:16:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 41%|████      | 4265/10519 [1:07:02<1:39:42,  1.05it/s][NeMo W 2026-06-19 08:16:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 41%|████      | 4266/10519 [1:07:03<1:42:18,  1.02it/s][NeMo W 2026-06-19 08:16:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
 41%|████      | 4267/10519 [1:07:05<1:44:50,  1.01s/it][NeMo W 2026-06-19 08:16:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 41%|████      | 4268/10519 [1:07:05<1:42:46,  1.01it/s][NeMo W 2026-06-19 08:16:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 41%|████      | 4269/10519 [1:07:06<1:42:35,  1.02it/s][NeMo W 2026-06-19 08:16:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.75it/s]
 41%|████      | 4270/10519 [1:07:07<1:42:02,  1.02it/s][NeMo W 2026-06-19 08:16:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.09it/s]
 41%|████      | 4271/10519 [1:07:09<1:57:43,  1.13s/it][NeMo W 2026-06-19 08:16:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 41%|████      | 4272/10519 [1:07:10<1:57:33,  1.13s/it][NeMo W 2026-06-19 08:16:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.05it/s]
 41%|████      | 4273/10519 [1:07:11<2:01:56,  1.17s/it][NeMo W 2026-06-19 08:16:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 41%|████      | 4274/10519 [1:07:12<1:49:43,  1.05s/it][NeMo W 2026-06-19 08:16:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 41%|████      | 4275/10519 [1:07:13<1:49:22,  1.05s/it][NeMo W 2026-06-19 08:16:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 41%|████      | 4276/10519 [1:07:14<1:46:44,  1.03s/it][NeMo W 2026-06-19 08:16:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 41%|████      | 4277/10519 [1:07:15<1:48:19,  1.04s/it][NeMo W 2026-06-19 08:16:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 41%|████      | 4278/10519 [1:07:16<1:41:03,  1.03it/s][NeMo W 2026-06-19 08:16:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:16:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 41%|████      | 4279/10519 [1:07:17<1:40:53,  1.03it/s][NeMo W 2026-06-19 08:16:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 4300 samples

[NeMo W 2026-06-19 08:17:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 41%|████      | 4301/10519 [1:07:40<2:00:57,  1.17s/it][NeMo W 2026-06-19 08:17:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 41%|████      | 4302/10519 [1:07:41<1:55:58,  1.12s/it][NeMo W 2026-06-19 08:17:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 41%|████      | 4303/10519 [1:07:42<1:52:38,  1.09s/it][NeMo W 2026-06-19 08:17:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 41%|████      | 4304/10519 [1:07:43<1:48:50,  1.05s/it][NeMo W 2026-06-19 08:17:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 41%|████      | 4305/10519 [1:07:43<1:41:02,  1.02it/s][NeMo W 2026-06-19 08:17:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 41%|████      | 4306/10519 [1:07:44<1:35:37,  1.08it/s][NeMo W 2026-06-19 08:17:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 41%|████      | 4307/10519 [1:07:45<1:36:59,  1.07it/s][NeMo W 2026-06-19 08:17:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 41%|████      | 4308/10519 [1:07:46<1:36:47,  1.07it/s][NeMo W 2026-06-19 08:17:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 41%|████      | 4309/10519 [1:07:47<1:37:38,  1.06it/s][NeMo W 2026-06-19 08:17:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 41%|████      | 4310/10519 [1:07:48<1:38:05,  1.05it/s][NeMo W 2026-06-19 08:17:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 41%|████      | 4311/10519 [1:07:49<1:31:09,  1.14it/s][NeMo W 2026-06-19 08:17:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 41%|████      | 4312/10519 [1:07:50<1:32:53,  1.11it/s][NeMo W 2026-06-19 08:17:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 41%|████      | 4313/10519 [1:07:51<1:39:48,  1.04it/s][NeMo W 2026-06-19 08:17:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 41%|████      | 4314/10519 [1:07:52<1:33:31,  1.11it/s][NeMo W 2026-06-19 08:17:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 41%|████      | 4315/10519 [1:07:53<1:36:38,  1.07it/s][NeMo W 2026-06-19 08:17:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.62it/s]
 41%|████      | 4316/10519 [1:07:54<1:38:10,  1.05it/s][NeMo W 2026-06-19 08:17:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 41%|████      | 4317/10519 [1:07:55<1:39:31,  1.04it/s][NeMo W 2026-06-19 08:17:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 41%|████      | 4318/10519 [1:07:56<1:39:34,  1.04it/s][NeMo W 2026-06-19 08:17:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 41%|████      | 4319/10519 [1:07:57<1:39:22,  1.04it/s][NeMo W 2026-06-19 08:17:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 41%|████      | 4320/10519 [1:07:57<1:32:30,  1.12it/s][NeMo W 2026-06-19 08:17:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 41%|████      | 4321/10519 [1:07:58<1:40:19,  1.03it/s][NeMo W 2026-06-19 08:17:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 41%|████      | 4322/10519 [1:07:59<1:41:19,  1.02it/s][NeMo W 2026-06-19 08:17:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 41%|████      | 4323/10519 [1:08:00<1:38:28,  1.05it/s][NeMo W 2026-06-19 08:17:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 41%|████      | 4324/10519 [1:08:01<1:46:02,  1.03s/it][NeMo W 2026-06-19 08:17:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 41%|████      | 4325/10519 [1:08:02<1:40:49,  1.02it/s][NeMo W 2026-06-19 08:17:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 41%|████      | 4326/10519 [1:08:03<1:39:20,  1.04it/s][NeMo W 2026-06-19 08:17:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 41%|████      | 4327/10519 [1:08:04<1:41:30,  1.02it/s][NeMo W 2026-06-19 08:17:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.31it/s]
 41%|████      | 4328/10519 [1:08:05<1:40:27,  1.03it/s][NeMo W 2026-06-19 08:17:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.62it/s]
 41%|████      | 4329/10519 [1:08:06<1:39:09,  1.04it/s][NeMo W 2026-06-19 08:17:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:17:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]

Checkpoint saved: 4350 samples

[NeMo W 2026-06-19 08:18:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 41%|████▏     | 4351/10519 [1:08:27<1:44:04,  1.01s/it][NeMo W 2026-06-19 08:18:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 41%|████▏     | 4352/10519 [1:08:28<1:39:24,  1.03it/s][NeMo W 2026-06-19 08:18:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 41%|████▏     | 4353/10519 [1:08:29<1:39:45,  1.03it/s][NeMo W 2026-06-19 08:18:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 41%|████▏     | 4354/10519 [1:08:30<1:36:32,  1.06it/s][NeMo W 2026-06-19 08:18:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.12it/s]
 41%|████▏     | 4355/10519 [1:08:31<1:38:38,  1.04it/s][NeMo W 2026-06-19 08:18:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 41%|████▏     | 4356/10519 [1:08:32<1:42:59,  1.00s/it][NeMo W 2026-06-19 08:18:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 41%|████▏     | 4357/10519 [1:08:33<1:42:48,  1.00s/it][NeMo W 2026-06-19 08:18:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 41%|████▏     | 4358/10519 [1:08:34<1:40:54,  1.02it/s][NeMo W 2026-06-19 08:18:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 41%|████▏     | 4359/10519 [1:08:35<1:40:45,  1.02it/s][NeMo W 2026-06-19 08:18:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.37it/s]
 41%|████▏     | 4360/10519 [1:08:36<1:42:08,  1.01it/s][NeMo W 2026-06-19 08:18:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 41%|████▏     | 4361/10519 [1:08:37<1:37:13,  1.06it/s][NeMo W 2026-06-19 08:18:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.83it/s]
 41%|████▏     | 4362/10519 [1:08:38<1:30:56,  1.13it/s][NeMo W 2026-06-19 08:18:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 41%|████▏     | 4363/10519 [1:08:39<1:32:46,  1.11it/s][NeMo W 2026-06-19 08:18:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.22it/s]
 41%|████▏     | 4364/10519 [1:08:39<1:29:14,  1.15it/s][NeMo W 2026-06-19 08:18:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 41%|████▏     | 4365/10519 [1:08:40<1:30:44,  1.13it/s][NeMo W 2026-06-19 08:18:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 42%|████▏     | 4366/10519 [1:08:41<1:32:45,  1.11it/s][NeMo W 2026-06-19 08:18:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.23it/s]
 42%|████▏     | 4367/10519 [1:08:42<1:29:42,  1.14it/s][NeMo W 2026-06-19 08:18:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 42%|████▏     | 4368/10519 [1:08:43<1:33:09,  1.10it/s][NeMo W 2026-06-19 08:18:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.95it/s]
 42%|████▏     | 4369/10519 [1:08:44<1:35:10,  1.08it/s][NeMo W 2026-06-19 08:18:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 42%|████▏     | 4370/10519 [1:08:45<1:36:26,  1.06it/s][NeMo W 2026-06-19 08:18:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.33it/s]
 42%|████▏     | 4371/10519 [1:08:46<1:39:30,  1.03it/s][NeMo W 2026-06-19 08:18:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.83it/s]
 42%|████▏     | 4372/10519 [1:08:47<1:36:38,  1.06it/s][NeMo W 2026-06-19 08:18:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 42%|████▏     | 4373/10519 [1:08:48<1:35:29,  1.07it/s][NeMo W 2026-06-19 08:18:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 42%|████▏     | 4374/10519 [1:08:49<1:30:51,  1.13it/s][NeMo W 2026-06-19 08:18:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 42%|████▏     | 4375/10519 [1:08:50<1:32:51,  1.10it/s][NeMo W 2026-06-19 08:18:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 42%|████▏     | 4376/10519 [1:08:50<1:27:09,  1.17it/s][NeMo W 2026-06-19 08:18:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 42%|████▏     | 4377/10519 [1:08:51<1:32:05,  1.11it/s][NeMo W 2026-06-19 08:18:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 42%|████▏     | 4378/10519 [1:08:52<1:29:33,  1.14it/s][NeMo W 2026-06-19 08:18:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 42%|████▏     | 4379/10519 [1:08:53<1:33:29,  1.09it/s][NeMo W 2026-06-19 08:18:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 4400 samples

[NeMo W 2026-06-19 08:18:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 42%|████▏     | 4401/10519 [1:09:15<1:54:32,  1.12s/it][NeMo W 2026-06-19 08:18:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 42%|████▏     | 4402/10519 [1:09:16<1:51:33,  1.09s/it][NeMo W 2026-06-19 08:18:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.11it/s]
 42%|████▏     | 4403/10519 [1:09:17<1:48:36,  1.07s/it][NeMo W 2026-06-19 08:18:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:18:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 42%|████▏     | 4404/10519 [1:09:18<1:38:21,  1.04it/s][NeMo W 2026-06-19 08:19:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 42%|████▏     | 4405/10519 [1:09:19<1:37:43,  1.04it/s][NeMo W 2026-06-19 08:19:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 42%|████▏     | 4406/10519 [1:09:20<1:37:44,  1.04it/s][NeMo W 2026-06-19 08:19:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 42%|████▏     | 4407/10519 [1:09:21<1:31:33,  1.11it/s][NeMo W 2026-06-19 08:19:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 42%|████▏     | 4408/10519 [1:09:22<1:33:31,  1.09it/s][NeMo W 2026-06-19 08:19:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 42%|████▏     | 4409/10519 [1:09:23<1:37:09,  1.05it/s][NeMo W 2026-06-19 08:19:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 42%|████▏     | 4410/10519 [1:09:24<1:38:39,  1.03it/s][NeMo W 2026-06-19 08:19:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 42%|████▏     | 4411/10519 [1:09:25<1:32:14,  1.10it/s][NeMo W 2026-06-19 08:19:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 42%|████▏     | 4412/10519 [1:09:26<1:40:08,  1.02it/s][NeMo W 2026-06-19 08:19:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 42%|████▏     | 4413/10519 [1:09:27<1:44:50,  1.03s/it][NeMo W 2026-06-19 08:19:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 42%|████▏     | 4414/10519 [1:09:28<1:45:30,  1.04s/it][NeMo W 2026-06-19 08:19:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 42%|████▏     | 4415/10519 [1:09:29<1:36:06,  1.06it/s][NeMo W 2026-06-19 08:19:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.48it/s]
 42%|████▏     | 4416/10519 [1:09:29<1:31:21,  1.11it/s][NeMo W 2026-06-19 08:19:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 42%|████▏     | 4417/10519 [1:09:30<1:28:17,  1.15it/s][NeMo W 2026-06-19 08:19:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.57it/s]
 42%|████▏     | 4418/10519 [1:09:31<1:29:25,  1.14it/s][NeMo W 2026-06-19 08:19:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.29it/s]
 42%|████▏     | 4419/10519 [1:09:32<1:32:48,  1.10it/s][NeMo W 2026-06-19 08:19:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
 42%|████▏     | 4420/10519 [1:09:33<1:32:36,  1.10it/s][NeMo W 2026-06-19 08:19:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.92it/s]
 42%|████▏     | 4421/10519 [1:09:34<1:32:15,  1.10it/s][NeMo W 2026-06-19 08:19:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 42%|████▏     | 4422/10519 [1:09:35<1:25:34,  1.19it/s][NeMo W 2026-06-19 08:19:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 42%|████▏     | 4423/10519 [1:09:36<1:25:27,  1.19it/s][NeMo W 2026-06-19 08:19:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 42%|████▏     | 4424/10519 [1:09:37<1:30:52,  1.12it/s][NeMo W 2026-06-19 08:19:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 42%|████▏     | 4425/10519 [1:09:37<1:33:21,  1.09it/s][NeMo W 2026-06-19 08:19:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.04it/s]
 42%|████▏     | 4426/10519 [1:09:38<1:34:01,  1.08it/s][NeMo W 2026-06-19 08:19:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 42%|████▏     | 4427/10519 [1:09:40<1:48:48,  1.07s/it][NeMo W 2026-06-19 08:19:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 42%|████▏     | 4428/10519 [1:09:41<1:43:28,  1.02s/it][NeMo W 2026-06-19 08:19:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 42%|████▏     | 4429/10519 [1:09:41<1:35:18,  1.06it/s][NeMo W 2026-06-19 08:19:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.55it/s]

Checkpoint saved: 4450 samples

[NeMo W 2026-06-19 08:19:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 42%|████▏     | 4451/10519 [1:10:04<2:01:16,  1.20s/it][NeMo W 2026-06-19 08:19:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 42%|████▏     | 4452/10519 [1:10:05<1:55:46,  1.15s/it][NeMo W 2026-06-19 08:19:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 42%|████▏     | 4453/10519 [1:10:06<1:48:30,  1.07s/it][NeMo W 2026-06-19 08:19:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 42%|████▏     | 4454/10519 [1:10:06<1:44:13,  1.03s/it][NeMo W 2026-06-19 08:19:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 42%|████▏     | 4455/10519 [1:10:07<1:41:15,  1.00s/it][NeMo W 2026-06-19 08:19:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 42%|████▏     | 4456/10519 [1:10:08<1:35:28,  1.06it/s][NeMo W 2026-06-19 08:19:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.81it/s]
 42%|████▏     | 4457/10519 [1:10:09<1:32:31,  1.09it/s][NeMo W 2026-06-19 08:19:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.08it/s]
 42%|████▏     | 4458/10519 [1:10:10<1:34:17,  1.07it/s][NeMo W 2026-06-19 08:19:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 42%|████▏     | 4459/10519 [1:10:11<1:35:11,  1.06it/s][NeMo W 2026-06-19 08:19:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.09it/s]
 42%|████▏     | 4460/10519 [1:10:12<1:31:52,  1.10it/s][NeMo W 2026-06-19 08:19:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 42%|████▏     | 4461/10519 [1:10:13<1:33:00,  1.09it/s][NeMo W 2026-06-19 08:19:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 42%|████▏     | 4462/10519 [1:10:14<1:34:11,  1.07it/s][NeMo W 2026-06-19 08:19:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 42%|████▏     | 4463/10519 [1:10:15<1:37:18,  1.04it/s][NeMo W 2026-06-19 08:19:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 42%|████▏     | 4464/10519 [1:10:16<1:38:05,  1.03it/s][NeMo W 2026-06-19 08:19:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 42%|████▏     | 4465/10519 [1:10:17<1:39:51,  1.01it/s][NeMo W 2026-06-19 08:19:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:19:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 42%|████▏     | 4466/10519 [1:10:18<1:38:22,  1.03it/s][NeMo W 2026-06-19 08:20:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 42%|████▏     | 4467/10519 [1:10:19<1:38:30,  1.02it/s][NeMo W 2026-06-19 08:20:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 42%|████▏     | 4468/10519 [1:10:20<1:37:50,  1.03it/s][NeMo W 2026-06-19 08:20:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 42%|████▏     | 4469/10519 [1:10:21<1:37:03,  1.04it/s][NeMo W 2026-06-19 08:20:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 42%|████▏     | 4470/10519 [1:10:22<1:35:21,  1.06it/s][NeMo W 2026-06-19 08:20:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.71it/s]
 43%|████▎     | 4471/10519 [1:10:23<1:41:46,  1.01s/it][NeMo W 2026-06-19 08:20:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 43%|████▎     | 4472/10519 [1:10:24<1:43:40,  1.03s/it][NeMo W 2026-06-19 08:20:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.91it/s]
 43%|████▎     | 4473/10519 [1:10:25<1:42:26,  1.02s/it][NeMo W 2026-06-19 08:20:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 43%|████▎     | 4474/10519 [1:10:26<1:40:40,  1.00it/s][NeMo W 2026-06-19 08:20:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 43%|████▎     | 4475/10519 [1:10:27<1:39:04,  1.02it/s][NeMo W 2026-06-19 08:20:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 43%|████▎     | 4476/10519 [1:10:27<1:31:46,  1.10it/s][NeMo W 2026-06-19 08:20:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 43%|████▎     | 4477/10519 [1:10:28<1:37:03,  1.04it/s][NeMo W 2026-06-19 08:20:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 43%|████▎     | 4478/10519 [1:10:29<1:37:25,  1.03it/s][NeMo W 2026-06-19 08:20:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 43%|████▎     | 4479/10519 [1:10:30<1:29:07,  1.13it/s][NeMo W 2026-06-19 08:20:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]

Checkpoint saved: 4500 samples

[NeMo W 2026-06-19 08:20:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 43%|████▎     | 4501/10519 [1:10:53<2:07:54,  1.28s/it][NeMo W 2026-06-19 08:20:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 43%|████▎     | 4502/10519 [1:10:54<1:58:17,  1.18s/it][NeMo W 2026-06-19 08:20:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 43%|████▎     | 4503/10519 [1:10:55<1:46:09,  1.06s/it][NeMo W 2026-06-19 08:20:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 43%|████▎     | 4504/10519 [1:10:55<1:35:48,  1.05it/s][NeMo W 2026-06-19 08:20:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 43%|████▎     | 4505/10519 [1:10:56<1:35:27,  1.05it/s][NeMo W 2026-06-19 08:20:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 43%|████▎     | 4506/10519 [1:10:57<1:36:04,  1.04it/s][NeMo W 2026-06-19 08:20:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.58it/s]
 43%|████▎     | 4507/10519 [1:10:58<1:39:01,  1.01it/s][NeMo W 2026-06-19 08:20:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 43%|████▎     | 4508/10519 [1:10:59<1:35:25,  1.05it/s][NeMo W 2026-06-19 08:20:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.42it/s]
 43%|████▎     | 4509/10519 [1:11:00<1:38:38,  1.02it/s][NeMo W 2026-06-19 08:20:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 43%|████▎     | 4510/10519 [1:11:01<1:37:59,  1.02it/s][NeMo W 2026-06-19 08:20:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 43%|████▎     | 4511/10519 [1:11:02<1:36:44,  1.04it/s][NeMo W 2026-06-19 08:20:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 43%|████▎     | 4512/10519 [1:11:03<1:36:27,  1.04it/s][NeMo W 2026-06-19 08:20:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 43%|████▎     | 4513/10519 [1:11:04<1:32:28,  1.08it/s][NeMo W 2026-06-19 08:20:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 43%|████▎     | 4514/10519 [1:11:05<1:30:28,  1.11it/s][NeMo W 2026-06-19 08:20:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.51it/s]
 43%|████▎     | 4515/10519 [1:11:06<1:33:16,  1.07it/s][NeMo W 2026-06-19 08:20:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 43%|████▎     | 4516/10519 [1:11:07<1:34:41,  1.06it/s][NeMo W 2026-06-19 08:20:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.89it/s]
 43%|████▎     | 4517/10519 [1:11:08<1:34:29,  1.06it/s][NeMo W 2026-06-19 08:20:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 43%|████▎     | 4518/10519 [1:11:09<1:37:54,  1.02it/s][NeMo W 2026-06-19 08:20:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.16it/s]
 43%|████▎     | 4519/10519 [1:11:10<1:42:36,  1.03s/it][NeMo W 2026-06-19 08:20:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 43%|████▎     | 4520/10519 [1:11:11<1:39:51,  1.00it/s][NeMo W 2026-06-19 08:20:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 43%|████▎     | 4521/10519 [1:11:12<1:33:18,  1.07it/s][NeMo W 2026-06-19 08:20:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 43%|████▎     | 4522/10519 [1:11:13<1:37:48,  1.02it/s][NeMo W 2026-06-19 08:20:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 43%|████▎     | 4523/10519 [1:11:14<1:34:57,  1.05it/s][NeMo W 2026-06-19 08:20:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 43%|████▎     | 4524/10519 [1:11:14<1:27:41,  1.14it/s][NeMo W 2026-06-19 08:20:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
 43%|████▎     | 4525/10519 [1:11:15<1:30:02,  1.11it/s][NeMo W 2026-06-19 08:20:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 43%|████▎     | 4526/10519 [1:11:16<1:25:39,  1.17it/s][NeMo W 2026-06-19 08:20:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 43%|████▎     | 4527/10519 [1:11:17<1:31:19,  1.09it/s][NeMo W 2026-06-19 08:20:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:20:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 43%|████▎     | 4528/10519 [1:11:18<1:33:17,  1.07it/s][NeMo W 2026-06-19 08:21:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 43%|████▎     | 4529/10519 [1:11:19<1:32:23,  1.08it/s][NeMo W 2026-06-19 08:21:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 4550 samples

[NeMo W 2026-06-19 08:21:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 43%|████▎     | 4551/10519 [1:11:41<1:52:15,  1.13s/it][NeMo W 2026-06-19 08:21:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.97it/s]
 43%|████▎     | 4552/10519 [1:11:42<1:42:52,  1.03s/it][NeMo W 2026-06-19 08:21:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 43%|████▎     | 4553/10519 [1:11:43<1:34:39,  1.05it/s][NeMo W 2026-06-19 08:21:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 43%|████▎     | 4554/10519 [1:11:44<1:35:26,  1.04it/s][NeMo W 2026-06-19 08:21:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.30it/s]
 43%|████▎     | 4555/10519 [1:11:45<1:36:46,  1.03it/s][NeMo W 2026-06-19 08:21:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 43%|████▎     | 4556/10519 [1:11:46<1:42:24,  1.03s/it][NeMo W 2026-06-19 08:21:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 43%|████▎     | 4557/10519 [1:11:47<1:40:50,  1.01s/it][NeMo W 2026-06-19 08:21:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 43%|████▎     | 4558/10519 [1:11:48<1:40:35,  1.01s/it][NeMo W 2026-06-19 08:21:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 43%|████▎     | 4559/10519 [1:11:49<1:39:03,  1.00it/s][NeMo W 2026-06-19 08:21:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 43%|████▎     | 4560/10519 [1:11:50<1:41:31,  1.02s/it][NeMo W 2026-06-19 08:21:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 43%|████▎     | 4561/10519 [1:11:51<1:40:40,  1.01s/it][NeMo W 2026-06-19 08:21:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 43%|████▎     | 4562/10519 [1:11:52<1:39:41,  1.00s/it][NeMo W 2026-06-19 08:21:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
 43%|████▎     | 4563/10519 [1:11:53<1:42:06,  1.03s/it][NeMo W 2026-06-19 08:21:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 43%|████▎     | 4564/10519 [1:11:54<1:40:39,  1.01s/it][NeMo W 2026-06-19 08:21:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 43%|████▎     | 4565/10519 [1:11:56<1:53:09,  1.14s/it][NeMo W 2026-06-19 08:21:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.33it/s]
 43%|████▎     | 4566/10519 [1:11:57<1:47:10,  1.08s/it][NeMo W 2026-06-19 08:21:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 43%|████▎     | 4567/10519 [1:11:58<1:43:35,  1.04s/it][NeMo W 2026-06-19 08:21:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 43%|████▎     | 4568/10519 [1:11:59<1:42:52,  1.04s/it][NeMo W 2026-06-19 08:21:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 43%|████▎     | 4569/10519 [1:11:59<1:40:54,  1.02s/it][NeMo W 2026-06-19 08:21:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 43%|████▎     | 4570/10519 [1:12:00<1:40:20,  1.01s/it][NeMo W 2026-06-19 08:21:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 43%|████▎     | 4571/10519 [1:12:02<1:45:23,  1.06s/it][NeMo W 2026-06-19 08:21:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 43%|████▎     | 4572/10519 [1:12:03<1:41:30,  1.02s/it][NeMo W 2026-06-19 08:21:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 43%|████▎     | 4573/10519 [1:12:04<1:45:27,  1.06s/it][NeMo W 2026-06-19 08:21:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 43%|████▎     | 4574/10519 [1:12:05<1:45:54,  1.07s/it][NeMo W 2026-06-19 08:21:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 43%|████▎     | 4575/10519 [1:12:06<1:42:04,  1.03s/it][NeMo W 2026-06-19 08:21:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 44%|████▎     | 4576/10519 [1:12:07<1:43:13,  1.04s/it][NeMo W 2026-06-19 08:21:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 44%|████▎     | 4577/10519 [1:12:08<1:41:11,  1.02s/it][NeMo W 2026-06-19 08:21:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 44%|████▎     | 4578/10519 [1:12:09<1:41:33,  1.03s/it][NeMo W 2026-06-19 08:21:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 44%|████▎     | 4579/10519 [1:12:10<1:40:40,  1.02s/it][NeMo W 2026-06-19 08:21:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:21:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.64it/s]

Checkpoint saved: 4600 samples

[NeMo W 2026-06-19 08:22:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.04it/s]
 44%|████▎     | 4601/10519 [1:12:34<2:11:31,  1.33s/it][NeMo W 2026-06-19 08:22:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.08it/s]
 44%|████▎     | 4602/10519 [1:12:35<1:58:21,  1.20s/it][NeMo W 2026-06-19 08:22:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.19it/s]
 44%|████▍     | 4603/10519 [1:12:35<1:49:21,  1.11s/it][NeMo W 2026-06-19 08:22:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.43it/s]
 44%|████▍     | 4604/10519 [1:12:37<1:49:16,  1.11s/it][NeMo W 2026-06-19 08:22:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  4.13it/s]
 44%|████▍     | 4605/10519 [1:12:38<1:53:06,  1.15s/it][NeMo W 2026-06-19 08:22:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  5.22it/s]
 44%|████▍     | 4606/10519 [1:12:39<2:02:10,  1.24s/it][NeMo W 2026-06-19 08:22:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  3.62it/s]
 44%|████▍     | 4607/10519 [1:12:40<2:01:36,  1.23s/it][NeMo W 2026-06-19 08:22:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  5.95it/s]
 44%|████▍     | 4608/10519 [1:12:42<1:56:26,  1.18s/it][NeMo W 2026-06-19 08:22:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  5.54it/s]
 44%|████▍     | 4609/10519 [1:12:43<1:55:41,  1.17s/it][NeMo W 2026-06-19 08:22:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  5.98it/s]
 44%|████▍     | 4610/10519 [1:12:44<2:02:43,  1.25s/it][NeMo W 2026-06-19 08:22:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  5.68it/s]
 44%|████▍     | 4611/10519 [1:12:45<1:57:54,  1.20s/it][NeMo W 2026-06-19 08:22:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  5.17it/s]
 44%|████▍     | 4612/10519 [1:12:46<1:56:12,  1.18s/it][NeMo W 2026-06-19 08:22:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.94it/s]
 44%|████▍     | 4613/10519 [1:12:47<1:52:40,  1.14s/it][NeMo W 2026-06-19 08:22:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 44%|████▍     | 4614/10519 [1:12:48<1:47:32,  1.09s/it][NeMo W 2026-06-19 08:22:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 44%|████▍     | 4615/10519 [1:12:49<1:41:29,  1.03s/it][NeMo W 2026-06-19 08:22:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 44%|████▍     | 4616/10519 [1:12:50<1:39:51,  1.02s/it][NeMo W 2026-06-19 08:22:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.48it/s]
 44%|████▍     | 4617/10519 [1:12:51<1:40:35,  1.02s/it][NeMo W 2026-06-19 08:22:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 44%|████▍     | 4618/10519 [1:12:52<1:41:36,  1.03s/it][NeMo W 2026-06-19 08:22:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 44%|████▍     | 4619/10519 [1:12:53<1:34:36,  1.04it/s][NeMo W 2026-06-19 08:22:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 44%|████▍     | 4620/10519 [1:12:54<1:35:54,  1.03it/s][NeMo W 2026-06-19 08:22:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.24it/s]
 44%|████▍     | 4621/10519 [1:12:55<1:36:00,  1.02it/s][NeMo W 2026-06-19 08:22:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 44%|████▍     | 4622/10519 [1:12:56<1:34:28,  1.04it/s][NeMo W 2026-06-19 08:22:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.48it/s]
 44%|████▍     | 4623/10519 [1:12:57<1:34:58,  1.03it/s][NeMo W 2026-06-19 08:22:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.29it/s]
 44%|████▍     | 4624/10519 [1:12:58<1:28:39,  1.11it/s][NeMo W 2026-06-19 08:22:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.55it/s]
 44%|████▍     | 4625/10519 [1:12:59<1:32:21,  1.06it/s][NeMo W 2026-06-19 08:22:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 44%|████▍     | 4626/10519 [1:13:00<1:34:38,  1.04it/s][NeMo W 2026-06-19 08:22:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 44%|████▍     | 4627/10519 [1:13:01<1:36:22,  1.02it/s][NeMo W 2026-06-19 08:22:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.49it/s]
 44%|████▍     | 4628/10519 [1:13:02<1:35:56,  1.02it/s][NeMo W 2026-06-19 08:22:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:22:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 44%|████▍     | 4629/10519 [1:13:03<1:37:05,  1.01it/s][NeMo W 2026-06-19 08:22:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 4650 samples

[NeMo W 2026-06-19 08:23:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 44%|████▍     | 4651/10519 [1:13:25<1:48:49,  1.11s/it][NeMo W 2026-06-19 08:23:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 44%|████▍     | 4652/10519 [1:13:26<1:44:36,  1.07s/it][NeMo W 2026-06-19 08:23:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 44%|████▍     | 4653/10519 [1:13:27<1:40:54,  1.03s/it][NeMo W 2026-06-19 08:23:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.36it/s]
 44%|████▍     | 4654/10519 [1:13:28<1:40:31,  1.03s/it][NeMo W 2026-06-19 08:23:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.60it/s]
 44%|████▍     | 4655/10519 [1:13:29<1:39:01,  1.01s/it][NeMo W 2026-06-19 08:23:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 44%|████▍     | 4656/10519 [1:13:30<1:37:24,  1.00it/s][NeMo W 2026-06-19 08:23:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 44%|████▍     | 4657/10519 [1:13:30<1:29:07,  1.10it/s][NeMo W 2026-06-19 08:23:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 44%|████▍     | 4658/10519 [1:13:31<1:31:11,  1.07it/s][NeMo W 2026-06-19 08:23:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 44%|████▍     | 4659/10519 [1:13:32<1:27:27,  1.12it/s][NeMo W 2026-06-19 08:23:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 44%|████▍     | 4660/10519 [1:13:33<1:21:07,  1.20it/s][NeMo W 2026-06-19 08:23:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 44%|████▍     | 4661/10519 [1:13:34<1:20:32,  1.21it/s][NeMo W 2026-06-19 08:23:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.95it/s]
 44%|████▍     | 4662/10519 [1:13:35<1:25:23,  1.14it/s][NeMo W 2026-06-19 08:23:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 44%|████▍     | 4663/10519 [1:13:35<1:25:30,  1.14it/s][NeMo W 2026-06-19 08:23:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 44%|████▍     | 4664/10519 [1:13:36<1:30:01,  1.08it/s][NeMo W 2026-06-19 08:23:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 44%|████▍     | 4665/10519 [1:13:37<1:30:01,  1.08it/s][NeMo W 2026-06-19 08:23:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 44%|████▍     | 4666/10519 [1:13:38<1:31:10,  1.07it/s][NeMo W 2026-06-19 08:23:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 44%|████▍     | 4667/10519 [1:13:39<1:29:41,  1.09it/s][NeMo W 2026-06-19 08:23:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 44%|████▍     | 4668/10519 [1:13:40<1:29:54,  1.08it/s][NeMo W 2026-06-19 08:23:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  3.52it/s]
 44%|████▍     | 4669/10519 [1:13:42<2:11:24,  1.35s/it][NeMo W 2026-06-19 08:23:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  2.96it/s]
 44%|████▍     | 4670/10519 [1:13:44<2:07:06,  1.30s/it][NeMo W 2026-06-19 08:23:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  3.31it/s]
 44%|████▍     | 4671/10519 [1:13:45<2:07:47,  1.31s/it][NeMo W 2026-06-19 08:23:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  4.75it/s]
 44%|████▍     | 4672/10519 [1:13:46<2:02:48,  1.26s/it][NeMo W 2026-06-19 08:23:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.87it/s]
 44%|████▍     | 4673/10519 [1:13:47<1:57:21,  1.20s/it][NeMo W 2026-06-19 08:23:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  3.78it/s]
 44%|████▍     | 4674/10519 [1:13:48<1:51:16,  1.14s/it][NeMo W 2026-06-19 08:23:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  4.81it/s]
 44%|████▍     | 4675/10519 [1:13:49<1:47:56,  1.11s/it][NeMo W 2026-06-19 08:23:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  4.56it/s]
 44%|████▍     | 4676/10519 [1:13:50<1:48:16,  1.11s/it][NeMo W 2026-06-19 08:23:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.11it/s]
 44%|████▍     | 4677/10519 [1:13:51<1:45:48,  1.09s/it][NeMo W 2026-06-19 08:23:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.24it/s]
 44%|████▍     | 4678/10519 [1:13:52<1:42:01,  1.05s/it][NeMo W 2026-06-19 08:23:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.43it/s]
 44%|████▍     | 4679/10519 [1:13:53<1:36:09,  1.01it/s][NeMo W 2026-06-19 08:23:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 4700 samples

[NeMo W 2026-06-19 08:23:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.66it/s]
 45%|████▍     | 4701/10519 [1:14:16<1:52:25,  1.16s/it][NeMo W 2026-06-19 08:23:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 45%|████▍     | 4702/10519 [1:14:17<1:44:29,  1.08s/it][NeMo W 2026-06-19 08:23:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:23:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 45%|████▍     | 4703/10519 [1:14:18<1:39:42,  1.03s/it][NeMo W 2026-06-19 08:24:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 45%|████▍     | 4704/10519 [1:14:19<1:36:50,  1.00it/s][NeMo W 2026-06-19 08:24:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 45%|████▍     | 4705/10519 [1:14:20<1:29:32,  1.08it/s][NeMo W 2026-06-19 08:24:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 45%|████▍     | 4706/10519 [1:14:21<1:30:11,  1.07it/s][NeMo W 2026-06-19 08:24:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 45%|████▍     | 4707/10519 [1:14:22<1:28:31,  1.09it/s][NeMo W 2026-06-19 08:24:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 45%|████▍     | 4708/10519 [1:14:23<1:27:21,  1.11it/s][NeMo W 2026-06-19 08:24:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 45%|████▍     | 4709/10519 [1:14:24<1:27:15,  1.11it/s][NeMo W 2026-06-19 08:24:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 45%|████▍     | 4710/10519 [1:14:25<1:30:34,  1.07it/s][NeMo W 2026-06-19 08:24:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 45%|████▍     | 4711/10519 [1:14:26<1:34:30,  1.02it/s][NeMo W 2026-06-19 08:24:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 45%|████▍     | 4712/10519 [1:14:27<1:33:55,  1.03it/s][NeMo W 2026-06-19 08:24:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.38it/s]
 45%|████▍     | 4713/10519 [1:14:28<1:38:52,  1.02s/it][NeMo W 2026-06-19 08:24:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 45%|████▍     | 4714/10519 [1:14:29<1:34:37,  1.02it/s][NeMo W 2026-06-19 08:24:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.09it/s]
 45%|████▍     | 4715/10519 [1:14:30<1:36:53,  1.00s/it][NeMo W 2026-06-19 08:24:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 45%|████▍     | 4716/10519 [1:14:31<1:36:46,  1.00s/it][NeMo W 2026-06-19 08:24:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 45%|████▍     | 4717/10519 [1:14:32<1:35:15,  1.02it/s][NeMo W 2026-06-19 08:24:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 45%|████▍     | 4718/10519 [1:14:33<1:36:39,  1.00it/s][NeMo W 2026-06-19 08:24:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 45%|████▍     | 4719/10519 [1:14:34<1:34:35,  1.02it/s][NeMo W 2026-06-19 08:24:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 45%|████▍     | 4720/10519 [1:14:34<1:33:22,  1.04it/s][NeMo W 2026-06-19 08:24:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 45%|████▍     | 4721/10519 [1:14:35<1:28:51,  1.09it/s][NeMo W 2026-06-19 08:24:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 45%|████▍     | 4722/10519 [1:14:36<1:28:21,  1.09it/s][NeMo W 2026-06-19 08:24:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.85it/s]
 45%|████▍     | 4723/10519 [1:14:37<1:27:13,  1.11it/s][NeMo W 2026-06-19 08:24:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 45%|████▍     | 4724/10519 [1:14:38<1:22:03,  1.18it/s][NeMo W 2026-06-19 08:24:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.88it/s]
 45%|████▍     | 4725/10519 [1:14:39<1:24:58,  1.14it/s][NeMo W 2026-06-19 08:24:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 45%|████▍     | 4726/10519 [1:14:39<1:19:43,  1.21it/s][NeMo W 2026-06-19 08:24:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 45%|████▍     | 4727/10519 [1:14:40<1:23:39,  1.15it/s][NeMo W 2026-06-19 08:24:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 45%|████▍     | 4728/10519 [1:14:41<1:27:06,  1.11it/s][NeMo W 2026-06-19 08:24:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 45%|████▍     | 4729/10519 [1:14:42<1:28:29,  1.09it/s][NeMo W 2026-06-19 08:24:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.64it/s]

Checkpoint saved: 4750 samples

[NeMo W 2026-06-19 08:24:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 45%|████▌     | 4751/10519 [1:15:03<1:48:15,  1.13s/it][NeMo W 2026-06-19 08:24:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.16it/s]
 45%|████▌     | 4752/10519 [1:15:04<1:44:45,  1.09s/it][NeMo W 2026-06-19 08:24:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.67it/s]
 45%|████▌     | 4753/10519 [1:15:05<1:44:39,  1.09s/it][NeMo W 2026-06-19 08:24:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 45%|████▌     | 4754/10519 [1:15:07<1:51:45,  1.16s/it][NeMo W 2026-06-19 08:24:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 45%|████▌     | 4755/10519 [1:15:08<1:45:44,  1.10s/it][NeMo W 2026-06-19 08:24:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 45%|████▌     | 4756/10519 [1:15:08<1:41:15,  1.05s/it][NeMo W 2026-06-19 08:24:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 45%|████▌     | 4757/10519 [1:15:09<1:36:49,  1.01s/it][NeMo W 2026-06-19 08:24:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 45%|████▌     | 4758/10519 [1:15:11<1:41:13,  1.05s/it][NeMo W 2026-06-19 08:24:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 45%|████▌     | 4759/10519 [1:15:11<1:33:16,  1.03it/s][NeMo W 2026-06-19 08:24:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 45%|████▌     | 4760/10519 [1:15:12<1:31:43,  1.05it/s][NeMo W 2026-06-19 08:24:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 45%|████▌     | 4761/10519 [1:15:13<1:36:41,  1.01s/it][NeMo W 2026-06-19 08:24:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 45%|████▌     | 4762/10519 [1:15:14<1:35:58,  1.00s/it][NeMo W 2026-06-19 08:24:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 45%|████▌     | 4763/10519 [1:15:15<1:33:59,  1.02it/s][NeMo W 2026-06-19 08:24:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 45%|████▌     | 4764/10519 [1:15:16<1:33:28,  1.03it/s][NeMo W 2026-06-19 08:24:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 45%|████▌     | 4765/10519 [1:15:17<1:33:12,  1.03it/s][NeMo W 2026-06-19 08:24:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:24:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 45%|████▌     | 4766/10519 [1:15:18<1:32:26,  1.04it/s][NeMo W 2026-06-19 08:25:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 45%|████▌     | 4767/10519 [1:15:19<1:26:03,  1.11it/s][NeMo W 2026-06-19 08:25:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 45%|████▌     | 4768/10519 [1:15:20<1:29:09,  1.08it/s][NeMo W 2026-06-19 08:25:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 45%|████▌     | 4769/10519 [1:15:21<1:28:54,  1.08it/s][NeMo W 2026-06-19 08:25:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 45%|████▌     | 4770/10519 [1:15:22<1:27:38,  1.09it/s][NeMo W 2026-06-19 08:25:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.61it/s]
 45%|████▌     | 4771/10519 [1:15:23<1:34:12,  1.02it/s][NeMo W 2026-06-19 08:25:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 45%|████▌     | 4772/10519 [1:15:24<1:34:04,  1.02it/s][NeMo W 2026-06-19 08:25:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.63it/s]
 45%|████▌     | 4773/10519 [1:15:25<1:43:13,  1.08s/it][NeMo W 2026-06-19 08:25:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 45%|████▌     | 4774/10519 [1:15:26<1:33:23,  1.03it/s][NeMo W 2026-06-19 08:25:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 45%|████▌     | 4775/10519 [1:15:27<1:34:15,  1.02it/s][NeMo W 2026-06-19 08:25:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 45%|████▌     | 4776/10519 [1:15:28<1:26:48,  1.10it/s][NeMo W 2026-06-19 08:25:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 45%|████▌     | 4777/10519 [1:15:29<1:29:02,  1.07it/s][NeMo W 2026-06-19 08:25:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 45%|████▌     | 4778/10519 [1:15:30<1:29:06,  1.07it/s][NeMo W 2026-06-19 08:25:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 45%|████▌     | 4779/10519 [1:15:30<1:30:37,  1.06it/s][NeMo W 2026-06-19 08:25:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]

Checkpoint saved: 4800 samples

[NeMo W 2026-06-19 08:25:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 46%|████▌     | 4801/10519 [1:15:52<1:55:48,  1.22s/it][NeMo W 2026-06-19 08:25:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 46%|████▌     | 4802/10519 [1:15:53<1:48:21,  1.14s/it][NeMo W 2026-06-19 08:25:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 46%|████▌     | 4803/10519 [1:15:54<1:43:03,  1.08s/it][NeMo W 2026-06-19 08:25:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 46%|████▌     | 4804/10519 [1:15:55<1:35:24,  1.00s/it][NeMo W 2026-06-19 08:25:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 46%|████▌     | 4805/10519 [1:15:56<1:32:40,  1.03it/s][NeMo W 2026-06-19 08:25:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 46%|████▌     | 4806/10519 [1:15:56<1:31:17,  1.04it/s][NeMo W 2026-06-19 08:25:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 46%|████▌     | 4807/10519 [1:15:57<1:30:35,  1.05it/s][NeMo W 2026-06-19 08:25:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 46%|████▌     | 4808/10519 [1:15:58<1:32:27,  1.03it/s][NeMo W 2026-06-19 08:25:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 46%|████▌     | 4809/10519 [1:15:59<1:32:35,  1.03it/s][NeMo W 2026-06-19 08:25:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 46%|████▌     | 4810/10519 [1:16:00<1:33:29,  1.02it/s][NeMo W 2026-06-19 08:25:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 46%|████▌     | 4811/10519 [1:16:01<1:32:23,  1.03it/s][NeMo W 2026-06-19 08:25:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 46%|████▌     | 4812/10519 [1:16:02<1:31:30,  1.04it/s][NeMo W 2026-06-19 08:25:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 46%|████▌     | 4813/10519 [1:16:03<1:30:49,  1.05it/s][NeMo W 2026-06-19 08:25:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 46%|████▌     | 4814/10519 [1:16:04<1:35:51,  1.01s/it][NeMo W 2026-06-19 08:25:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.66it/s]
 46%|████▌     | 4815/10519 [1:16:05<1:32:10,  1.03it/s][NeMo W 2026-06-19 08:25:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 46%|████▌     | 4816/10519 [1:16:06<1:31:06,  1.04it/s][NeMo W 2026-06-19 08:25:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 46%|████▌     | 4817/10519 [1:16:07<1:29:55,  1.06it/s][NeMo W 2026-06-19 08:25:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
 46%|████▌     | 4818/10519 [1:16:08<1:25:15,  1.11it/s][NeMo W 2026-06-19 08:25:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.43it/s]
 46%|████▌     | 4819/10519 [1:16:09<1:27:44,  1.08it/s][NeMo W 2026-06-19 08:25:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 46%|████▌     | 4820/10519 [1:16:10<1:28:49,  1.07it/s][NeMo W 2026-06-19 08:25:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 46%|████▌     | 4821/10519 [1:16:11<1:30:32,  1.05it/s][NeMo W 2026-06-19 08:25:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 46%|████▌     | 4822/10519 [1:16:12<1:29:52,  1.06it/s][NeMo W 2026-06-19 08:25:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 46%|████▌     | 4823/10519 [1:16:13<1:33:40,  1.01it/s][NeMo W 2026-06-19 08:25:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.40it/s]
 46%|████▌     | 4824/10519 [1:16:14<1:34:14,  1.01it/s][NeMo W 2026-06-19 08:25:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 46%|████▌     | 4825/10519 [1:16:15<1:33:58,  1.01it/s][NeMo W 2026-06-19 08:25:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 46%|████▌     | 4826/10519 [1:16:16<1:32:20,  1.03it/s][NeMo W 2026-06-19 08:25:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 46%|████▌     | 4827/10519 [1:16:17<1:31:45,  1.03it/s][NeMo W 2026-06-19 08:25:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.41it/s]
 46%|████▌     | 4828/10519 [1:16:17<1:26:20,  1.10it/s][NeMo W 2026-06-19 08:25:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:25:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.15it/s]
 46%|████▌     | 4829/10519 [1:16:18<1:26:53,  1.09it/s][NeMo W 2026-06-19 08:26:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]

Checkpoint saved: 4850 samples

[NeMo W 2026-06-19 08:26:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 46%|████▌     | 4851/10519 [1:16:42<1:58:54,  1.26s/it][NeMo W 2026-06-19 08:26:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.61it/s]
 46%|████▌     | 4852/10519 [1:16:43<1:49:57,  1.16s/it][NeMo W 2026-06-19 08:26:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 46%|████▌     | 4853/10519 [1:16:43<1:41:52,  1.08s/it][NeMo W 2026-06-19 08:26:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.24it/s]
 46%|████▌     | 4854/10519 [1:16:44<1:37:18,  1.03s/it][NeMo W 2026-06-19 08:26:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 46%|████▌     | 4855/10519 [1:16:45<1:40:48,  1.07s/it][NeMo W 2026-06-19 08:26:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 46%|████▌     | 4856/10519 [1:16:46<1:36:49,  1.03s/it][NeMo W 2026-06-19 08:26:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 46%|████▌     | 4857/10519 [1:16:47<1:33:17,  1.01it/s][NeMo W 2026-06-19 08:26:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 46%|████▌     | 4858/10519 [1:16:48<1:33:12,  1.01it/s][NeMo W 2026-06-19 08:26:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 46%|████▌     | 4859/10519 [1:16:49<1:33:51,  1.01it/s][NeMo W 2026-06-19 08:26:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 46%|████▌     | 4860/10519 [1:16:50<1:33:42,  1.01it/s][NeMo W 2026-06-19 08:26:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.52it/s]
 46%|████▌     | 4861/10519 [1:16:51<1:32:23,  1.02it/s][NeMo W 2026-06-19 08:26:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.40it/s]
 46%|████▌     | 4862/10519 [1:16:52<1:30:55,  1.04it/s][NeMo W 2026-06-19 08:26:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 46%|████▌     | 4863/10519 [1:16:53<1:32:20,  1.02it/s][NeMo W 2026-06-19 08:26:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 46%|████▌     | 4864/10519 [1:16:54<1:35:02,  1.01s/it][NeMo W 2026-06-19 08:26:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 46%|████▌     | 4865/10519 [1:16:55<1:26:07,  1.09it/s][NeMo W 2026-06-19 08:26:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 46%|████▋     | 4866/10519 [1:16:56<1:29:20,  1.05it/s][NeMo W 2026-06-19 08:26:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 46%|████▋     | 4867/10519 [1:16:57<1:30:04,  1.05it/s][NeMo W 2026-06-19 08:26:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.05it/s]
 46%|████▋     | 4868/10519 [1:16:58<1:23:38,  1.13it/s][NeMo W 2026-06-19 08:26:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 46%|████▋     | 4869/10519 [1:16:59<1:21:42,  1.15it/s][NeMo W 2026-06-19 08:26:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.08it/s]
 46%|████▋     | 4870/10519 [1:16:59<1:22:07,  1.15it/s][NeMo W 2026-06-19 08:26:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 46%|████▋     | 4871/10519 [1:17:01<1:31:38,  1.03it/s][NeMo W 2026-06-19 08:26:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 46%|████▋     | 4872/10519 [1:17:02<1:30:14,  1.04it/s][NeMo W 2026-06-19 08:26:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.84it/s]
 46%|████▋     | 4873/10519 [1:17:02<1:24:32,  1.11it/s][NeMo W 2026-06-19 08:26:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 46%|████▋     | 4874/10519 [1:17:03<1:26:26,  1.09it/s][NeMo W 2026-06-19 08:26:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.74it/s]
 46%|████▋     | 4875/10519 [1:17:04<1:31:16,  1.03it/s][NeMo W 2026-06-19 08:26:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 46%|████▋     | 4876/10519 [1:17:05<1:25:35,  1.10it/s][NeMo W 2026-06-19 08:26:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
 46%|████▋     | 4877/10519 [1:17:06<1:20:00,  1.18it/s][NeMo W 2026-06-19 08:26:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 46%|████▋     | 4878/10519 [1:17:07<1:23:08,  1.13it/s][NeMo W 2026-06-19 08:26:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 46%|████▋     | 4879/10519 [1:17:08<1:30:34,  1.04it/s][NeMo W 2026-06-19 08:26:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:26:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]

Checkpoint saved: 4900 samples

[NeMo W 2026-06-19 08:27:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 47%|████▋     | 4901/10519 [1:17:30<1:49:41,  1.17s/it][NeMo W 2026-06-19 08:27:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.29it/s]
 47%|████▋     | 4902/10519 [1:17:31<1:37:49,  1.05s/it][NeMo W 2026-06-19 08:27:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 47%|████▋     | 4903/10519 [1:17:32<1:34:09,  1.01s/it][NeMo W 2026-06-19 08:27:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 47%|████▋     | 4904/10519 [1:17:33<1:31:33,  1.02it/s][NeMo W 2026-06-19 08:27:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 47%|████▋     | 4905/10519 [1:17:34<1:30:37,  1.03it/s][NeMo W 2026-06-19 08:27:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 47%|████▋     | 4906/10519 [1:17:35<1:33:15,  1.00it/s][NeMo W 2026-06-19 08:27:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 47%|████▋     | 4907/10519 [1:17:36<1:31:55,  1.02it/s][NeMo W 2026-06-19 08:27:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 47%|████▋     | 4908/10519 [1:17:37<1:31:06,  1.03it/s][NeMo W 2026-06-19 08:27:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 47%|████▋     | 4909/10519 [1:17:38<1:26:05,  1.09it/s][NeMo W 2026-06-19 08:27:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.91it/s]
 47%|████▋     | 4910/10519 [1:17:39<1:22:52,  1.13it/s][NeMo W 2026-06-19 08:27:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 47%|████▋     | 4911/10519 [1:17:40<1:25:57,  1.09it/s][NeMo W 2026-06-19 08:27:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.52it/s]
 47%|████▋     | 4912/10519 [1:17:40<1:26:21,  1.08it/s][NeMo W 2026-06-19 08:27:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 47%|████▋     | 4913/10519 [1:17:41<1:22:57,  1.13it/s][NeMo W 2026-06-19 08:27:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 47%|████▋     | 4914/10519 [1:17:42<1:24:02,  1.11it/s][NeMo W 2026-06-19 08:27:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 47%|████▋     | 4915/10519 [1:17:43<1:27:28,  1.07it/s][NeMo W 2026-06-19 08:27:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 47%|████▋     | 4916/10519 [1:17:45<1:40:27,  1.08s/it][NeMo W 2026-06-19 08:27:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 47%|████▋     | 4917/10519 [1:17:46<1:36:09,  1.03s/it][NeMo W 2026-06-19 08:27:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 47%|████▋     | 4918/10519 [1:17:46<1:31:02,  1.03it/s][NeMo W 2026-06-19 08:27:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.96it/s]
 47%|████▋     | 4919/10519 [1:17:47<1:29:58,  1.04it/s][NeMo W 2026-06-19 08:27:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 47%|████▋     | 4920/10519 [1:17:48<1:29:26,  1.04it/s][NeMo W 2026-06-19 08:27:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 47%|████▋     | 4921/10519 [1:17:49<1:32:18,  1.01it/s][NeMo W 2026-06-19 08:27:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 47%|████▋     | 4922/10519 [1:17:50<1:28:30,  1.05it/s][NeMo W 2026-06-19 08:27:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 47%|████▋     | 4923/10519 [1:17:51<1:22:43,  1.13it/s][NeMo W 2026-06-19 08:27:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 47%|████▋     | 4924/10519 [1:17:52<1:25:44,  1.09it/s][NeMo W 2026-06-19 08:27:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 47%|████▋     | 4925/10519 [1:17:53<1:26:52,  1.07it/s][NeMo W 2026-06-19 08:27:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 47%|████▋     | 4926/10519 [1:17:54<1:22:46,  1.13it/s][NeMo W 2026-06-19 08:27:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 47%|████▋     | 4927/10519 [1:17:55<1:24:29,  1.10it/s][NeMo W 2026-06-19 08:27:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.66it/s]
 47%|████▋     | 4928/10519 [1:17:56<1:27:45,  1.06it/s][NeMo W 2026-06-19 08:27:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 47%|████▋     | 4929/10519 [1:17:56<1:21:29,  1.14it/s][NeMo W 2026-06-19 08:27:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]

Checkpoint saved: 4950 samples

[NeMo W 2026-06-19 08:27:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 47%|████▋     | 4951/10519 [1:18:18<1:42:07,  1.10s/it][NeMo W 2026-06-19 08:27:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:27:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.97it/s]
 47%|████▋     | 4952/10519 [1:18:18<1:34:41,  1.02s/it][NeMo W 2026-06-19 08:28:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 47%|████▋     | 4953/10519 [1:18:19<1:34:12,  1.02s/it][NeMo W 2026-06-19 08:28:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 47%|████▋     | 4954/10519 [1:18:20<1:31:49,  1.01it/s][NeMo W 2026-06-19 08:28:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 47%|████▋     | 4955/10519 [1:18:21<1:30:08,  1.03it/s][NeMo W 2026-06-19 08:28:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.66it/s]
 47%|████▋     | 4956/10519 [1:18:22<1:31:06,  1.02it/s][NeMo W 2026-06-19 08:28:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 47%|████▋     | 4957/10519 [1:18:23<1:35:06,  1.03s/it][NeMo W 2026-06-19 08:28:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 47%|████▋     | 4958/10519 [1:18:24<1:32:03,  1.01it/s][NeMo W 2026-06-19 08:28:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 47%|████▋     | 4959/10519 [1:18:25<1:30:14,  1.03it/s][NeMo W 2026-06-19 08:28:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.88it/s]
 47%|████▋     | 4960/10519 [1:18:26<1:30:37,  1.02it/s][NeMo W 2026-06-19 08:28:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 47%|████▋     | 4961/10519 [1:18:27<1:32:41,  1.00s/it][NeMo W 2026-06-19 08:28:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 47%|████▋     | 4962/10519 [1:18:28<1:33:34,  1.01s/it][NeMo W 2026-06-19 08:28:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 47%|████▋     | 4963/10519 [1:18:29<1:33:12,  1.01s/it][NeMo W 2026-06-19 08:28:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 47%|████▋     | 4964/10519 [1:18:30<1:32:07,  1.00it/s][NeMo W 2026-06-19 08:28:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 47%|████▋     | 4965/10519 [1:18:31<1:33:23,  1.01s/it][NeMo W 2026-06-19 08:28:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 47%|████▋     | 4966/10519 [1:18:32<1:32:31,  1.00it/s][NeMo W 2026-06-19 08:28:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.77it/s]
 47%|████▋     | 4967/10519 [1:18:33<1:31:27,  1.01it/s][NeMo W 2026-06-19 08:28:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 47%|████▋     | 4968/10519 [1:18:34<1:31:14,  1.01it/s][NeMo W 2026-06-19 08:28:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 47%|████▋     | 4969/10519 [1:18:35<1:32:37,  1.00s/it][NeMo W 2026-06-19 08:28:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 47%|████▋     | 4970/10519 [1:18:36<1:31:34,  1.01it/s][NeMo W 2026-06-19 08:28:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.35it/s]
 47%|████▋     | 4971/10519 [1:18:37<1:30:34,  1.02it/s][NeMo W 2026-06-19 08:28:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 47%|████▋     | 4972/10519 [1:18:38<1:29:24,  1.03it/s][NeMo W 2026-06-19 08:28:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 47%|████▋     | 4973/10519 [1:18:39<1:35:04,  1.03s/it][NeMo W 2026-06-19 08:28:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 47%|████▋     | 4974/10519 [1:18:41<1:39:41,  1.08s/it][NeMo W 2026-06-19 08:28:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 47%|████▋     | 4975/10519 [1:18:41<1:34:02,  1.02s/it][NeMo W 2026-06-19 08:28:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 47%|████▋     | 4976/10519 [1:18:42<1:31:39,  1.01it/s][NeMo W 2026-06-19 08:28:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 47%|████▋     | 4977/10519 [1:18:43<1:30:45,  1.02it/s][NeMo W 2026-06-19 08:28:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 47%|████▋     | 4978/10519 [1:18:44<1:30:23,  1.02it/s][NeMo W 2026-06-19 08:28:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 47%|████▋     | 4979/10519 [1:18:46<1:41:06,  1.10s/it][NeMo W 2026-06-19 08:28:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 5000 samples

[NeMo W 2026-06-19 08:28:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 48%|████▊     | 5001/10519 [1:19:08<1:43:24,  1.12s/it][NeMo W 2026-06-19 08:28:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 48%|████▊     | 5002/10519 [1:19:08<1:32:56,  1.01s/it][NeMo W 2026-06-19 08:28:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 48%|████▊     | 5003/10519 [1:19:09<1:29:33,  1.03it/s][NeMo W 2026-06-19 08:28:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 48%|████▊     | 5004/10519 [1:19:10<1:29:09,  1.03it/s][NeMo W 2026-06-19 08:28:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 48%|████▊     | 5005/10519 [1:19:11<1:26:03,  1.07it/s][NeMo W 2026-06-19 08:28:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 48%|████▊     | 5006/10519 [1:19:12<1:30:26,  1.02it/s][NeMo W 2026-06-19 08:28:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 48%|████▊     | 5007/10519 [1:19:13<1:28:56,  1.03it/s][NeMo W 2026-06-19 08:28:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 48%|████▊     | 5008/10519 [1:19:14<1:29:06,  1.03it/s][NeMo W 2026-06-19 08:28:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 48%|████▊     | 5009/10519 [1:19:15<1:27:35,  1.05it/s][NeMo W 2026-06-19 08:28:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 48%|████▊     | 5010/10519 [1:19:16<1:22:33,  1.11it/s][NeMo W 2026-06-19 08:28:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 48%|████▊     | 5011/10519 [1:19:17<1:22:40,  1.11it/s][NeMo W 2026-06-19 08:28:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:28:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 48%|████▊     | 5012/10519 [1:19:18<1:25:43,  1.07it/s][NeMo W 2026-06-19 08:29:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 48%|████▊     | 5013/10519 [1:19:19<1:39:07,  1.08s/it][NeMo W 2026-06-19 08:29:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
 48%|████▊     | 5014/10519 [1:19:20<1:34:30,  1.03s/it][NeMo W 2026-06-19 08:29:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 48%|████▊     | 5015/10519 [1:19:21<1:32:35,  1.01s/it][NeMo W 2026-06-19 08:29:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.95it/s]
 48%|████▊     | 5016/10519 [1:19:22<1:30:29,  1.01it/s][NeMo W 2026-06-19 08:29:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 48%|████▊     | 5017/10519 [1:19:23<1:29:36,  1.02it/s][NeMo W 2026-06-19 08:29:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 48%|████▊     | 5018/10519 [1:19:24<1:25:12,  1.08it/s][NeMo W 2026-06-19 08:29:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 48%|████▊     | 5019/10519 [1:19:24<1:24:56,  1.08it/s][NeMo W 2026-06-19 08:29:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 48%|████▊     | 5020/10519 [1:19:25<1:26:30,  1.06it/s][NeMo W 2026-06-19 08:29:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 48%|████▊     | 5021/10519 [1:19:26<1:26:44,  1.06it/s][NeMo W 2026-06-19 08:29:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 48%|████▊     | 5022/10519 [1:19:27<1:21:38,  1.12it/s][NeMo W 2026-06-19 08:29:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 48%|████▊     | 5023/10519 [1:19:28<1:24:31,  1.08it/s][NeMo W 2026-06-19 08:29:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 48%|████▊     | 5024/10519 [1:19:29<1:26:32,  1.06it/s][NeMo W 2026-06-19 08:29:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 48%|████▊     | 5025/10519 [1:19:30<1:24:41,  1.08it/s][NeMo W 2026-06-19 08:29:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 48%|████▊     | 5026/10519 [1:19:31<1:23:03,  1.10it/s][NeMo W 2026-06-19 08:29:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 48%|████▊     | 5027/10519 [1:19:32<1:24:35,  1.08it/s][NeMo W 2026-06-19 08:29:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 48%|████▊     | 5028/10519 [1:19:33<1:25:10,  1.07it/s][NeMo W 2026-06-19 08:29:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 48%|████▊     | 5029/10519 [1:19:34<1:22:40,  1.11it/s][NeMo W 2026-06-19 08:29:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]

Checkpoint saved: 5050 samples

[NeMo W 2026-06-19 08:29:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 48%|████▊     | 5051/10519 [1:19:55<1:40:19,  1.10s/it][NeMo W 2026-06-19 08:29:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 48%|████▊     | 5052/10519 [1:19:56<1:35:59,  1.05s/it][NeMo W 2026-06-19 08:29:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 48%|████▊     | 5053/10519 [1:19:57<1:32:44,  1.02s/it][NeMo W 2026-06-19 08:29:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.54it/s]
 48%|████▊     | 5054/10519 [1:19:58<1:32:45,  1.02s/it][NeMo W 2026-06-19 08:29:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 48%|████▊     | 5055/10519 [1:19:59<1:29:42,  1.02it/s][NeMo W 2026-06-19 08:29:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 48%|████▊     | 5056/10519 [1:20:00<1:29:27,  1.02it/s][NeMo W 2026-06-19 08:29:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 48%|████▊     | 5057/10519 [1:20:01<1:34:39,  1.04s/it][NeMo W 2026-06-19 08:29:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 48%|████▊     | 5058/10519 [1:20:02<1:32:49,  1.02s/it][NeMo W 2026-06-19 08:29:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 48%|████▊     | 5059/10519 [1:20:03<1:30:37,  1.00it/s][NeMo W 2026-06-19 08:29:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 48%|████▊     | 5060/10519 [1:20:04<1:27:52,  1.04it/s][NeMo W 2026-06-19 08:29:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.12it/s]
 48%|████▊     | 5061/10519 [1:20:05<1:29:45,  1.01it/s][NeMo W 2026-06-19 08:29:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 48%|████▊     | 5062/10519 [1:20:06<1:32:28,  1.02s/it][NeMo W 2026-06-19 08:29:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 48%|████▊     | 5063/10519 [1:20:07<1:29:49,  1.01it/s][NeMo W 2026-06-19 08:29:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 48%|████▊     | 5064/10519 [1:20:08<1:29:24,  1.02it/s][NeMo W 2026-06-19 08:29:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 48%|████▊     | 5065/10519 [1:20:09<1:28:20,  1.03it/s][NeMo W 2026-06-19 08:29:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.30it/s]
 48%|████▊     | 5066/10519 [1:20:09<1:27:22,  1.04it/s][NeMo W 2026-06-19 08:29:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.30it/s]
 48%|████▊     | 5067/10519 [1:20:11<1:30:47,  1.00it/s][NeMo W 2026-06-19 08:29:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 48%|████▊     | 5068/10519 [1:20:11<1:28:06,  1.03it/s][NeMo W 2026-06-19 08:29:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 48%|████▊     | 5069/10519 [1:20:12<1:28:20,  1.03it/s][NeMo W 2026-06-19 08:29:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.91it/s]
 48%|████▊     | 5070/10519 [1:20:14<1:32:26,  1.02s/it][NeMo W 2026-06-19 08:29:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 48%|████▊     | 5071/10519 [1:20:14<1:29:57,  1.01it/s][NeMo W 2026-06-19 08:29:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 48%|████▊     | 5072/10519 [1:20:15<1:27:26,  1.04it/s][NeMo W 2026-06-19 08:29:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 48%|████▊     | 5073/10519 [1:20:16<1:27:25,  1.04it/s][NeMo W 2026-06-19 08:29:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.65it/s]
 48%|████▊     | 5074/10519 [1:20:17<1:25:53,  1.06it/s][NeMo W 2026-06-19 08:29:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:29:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 48%|████▊     | 5075/10519 [1:20:18<1:21:34,  1.11it/s][NeMo W 2026-06-19 08:30:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 48%|████▊     | 5076/10519 [1:20:19<1:23:49,  1.08it/s][NeMo W 2026-06-19 08:30:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.52it/s]
 48%|████▊     | 5077/10519 [1:20:20<1:21:06,  1.12it/s][NeMo W 2026-06-19 08:30:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 48%|████▊     | 5078/10519 [1:20:21<1:28:12,  1.03it/s][NeMo W 2026-06-19 08:30:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
 48%|████▊     | 5079/10519 [1:20:22<1:19:35,  1.14it/s][NeMo W 2026-06-19 08:30:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 5100 samples

[NeMo W 2026-06-19 08:30:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 48%|████▊     | 5101/10519 [1:20:45<1:50:17,  1.22s/it][NeMo W 2026-06-19 08:30:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 49%|████▊     | 5102/10519 [1:20:46<1:41:04,  1.12s/it][NeMo W 2026-06-19 08:30:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 49%|████▊     | 5103/10519 [1:20:47<1:38:35,  1.09s/it][NeMo W 2026-06-19 08:30:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 49%|████▊     | 5104/10519 [1:20:48<1:40:57,  1.12s/it][NeMo W 2026-06-19 08:30:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 49%|████▊     | 5105/10519 [1:20:49<1:37:09,  1.08s/it][NeMo W 2026-06-19 08:30:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 49%|████▊     | 5106/10519 [1:20:50<1:34:19,  1.05s/it][NeMo W 2026-06-19 08:30:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 49%|████▊     | 5107/10519 [1:20:51<1:32:40,  1.03s/it][NeMo W 2026-06-19 08:30:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 49%|████▊     | 5108/10519 [1:20:52<1:29:04,  1.01it/s][NeMo W 2026-06-19 08:30:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 49%|████▊     | 5109/10519 [1:20:53<1:33:03,  1.03s/it][NeMo W 2026-06-19 08:30:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]
 49%|████▊     | 5110/10519 [1:20:54<1:30:57,  1.01s/it][NeMo W 2026-06-19 08:30:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.37it/s]
 49%|████▊     | 5111/10519 [1:20:55<1:31:29,  1.02s/it][NeMo W 2026-06-19 08:30:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
 49%|████▊     | 5112/10519 [1:20:56<1:31:56,  1.02s/it][NeMo W 2026-06-19 08:30:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
 49%|████▊     | 5113/10519 [1:20:57<1:26:14,  1.04it/s][NeMo W 2026-06-19 08:30:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.98it/s]
 49%|████▊     | 5114/10519 [1:20:58<1:28:00,  1.02it/s][NeMo W 2026-06-19 08:30:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 49%|████▊     | 5115/10519 [1:21:00<2:00:26,  1.34s/it][NeMo W 2026-06-19 08:30:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 49%|████▊     | 5116/10519 [1:21:01<1:50:33,  1.23s/it][NeMo W 2026-06-19 08:30:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 49%|████▊     | 5117/10519 [1:21:02<1:37:39,  1.08s/it][NeMo W 2026-06-19 08:30:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.29it/s]
 49%|████▊     | 5118/10519 [1:21:03<1:33:35,  1.04s/it][NeMo W 2026-06-19 08:30:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
 49%|████▊     | 5119/10519 [1:21:04<1:31:28,  1.02s/it][NeMo W 2026-06-19 08:30:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 49%|████▊     | 5120/10519 [1:21:04<1:24:59,  1.06it/s][NeMo W 2026-06-19 08:30:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 49%|████▊     | 5121/10519 [1:21:05<1:22:40,  1.09it/s][NeMo W 2026-06-19 08:30:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 49%|████▊     | 5122/10519 [1:21:06<1:23:40,  1.07it/s][NeMo W 2026-06-19 08:30:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 49%|████▊     | 5123/10519 [1:21:07<1:23:55,  1.07it/s][NeMo W 2026-06-19 08:30:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.71it/s]
 49%|████▊     | 5124/10519 [1:21:08<1:25:55,  1.05it/s][NeMo W 2026-06-19 08:30:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 49%|████▊     | 5125/10519 [1:21:09<1:28:28,  1.02it/s][NeMo W 2026-06-19 08:30:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 49%|████▊     | 5126/10519 [1:21:10<1:28:24,  1.02it/s][NeMo W 2026-06-19 08:30:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 49%|████▊     | 5127/10519 [1:21:11<1:27:26,  1.03it/s][NeMo W 2026-06-19 08:30:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 49%|████▊     | 5128/10519 [1:21:12<1:25:06,  1.06it/s][NeMo W 2026-06-19 08:30:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 49%|████▉     | 5129/10519 [1:21:13<1:23:59,  1.07it/s][NeMo W 2026-06-19 08:30:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:30:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 5150 samples

[NeMo W 2026-06-19 08:31:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 49%|████▉     | 5151/10519 [1:21:35<1:42:53,  1.15s/it][NeMo W 2026-06-19 08:31:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 49%|████▉     | 5152/10519 [1:21:35<1:33:07,  1.04s/it][NeMo W 2026-06-19 08:31:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 49%|████▉     | 5153/10519 [1:21:36<1:30:57,  1.02s/it][NeMo W 2026-06-19 08:31:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 49%|████▉     | 5154/10519 [1:21:37<1:29:20,  1.00it/s][NeMo W 2026-06-19 08:31:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.78it/s]
 49%|████▉     | 5155/10519 [1:21:38<1:29:10,  1.00it/s][NeMo W 2026-06-19 08:31:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 49%|████▉     | 5156/10519 [1:21:39<1:29:12,  1.00it/s][NeMo W 2026-06-19 08:31:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 49%|████▉     | 5157/10519 [1:21:40<1:27:55,  1.02it/s][NeMo W 2026-06-19 08:31:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 49%|████▉     | 5158/10519 [1:21:41<1:27:22,  1.02it/s][NeMo W 2026-06-19 08:31:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 49%|████▉     | 5159/10519 [1:21:42<1:28:44,  1.01it/s][NeMo W 2026-06-19 08:31:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 49%|████▉     | 5160/10519 [1:21:43<1:30:40,  1.02s/it][NeMo W 2026-06-19 08:31:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 49%|████▉     | 5161/10519 [1:21:44<1:27:54,  1.02it/s][NeMo W 2026-06-19 08:31:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 49%|████▉     | 5162/10519 [1:21:45<1:22:31,  1.08it/s][NeMo W 2026-06-19 08:31:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 49%|████▉     | 5163/10519 [1:21:46<1:21:52,  1.09it/s][NeMo W 2026-06-19 08:31:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 49%|████▉     | 5164/10519 [1:21:47<1:22:46,  1.08it/s][NeMo W 2026-06-19 08:31:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 49%|████▉     | 5165/10519 [1:21:48<1:18:16,  1.14it/s][NeMo W 2026-06-19 08:31:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 49%|████▉     | 5166/10519 [1:21:48<1:16:35,  1.16it/s][NeMo W 2026-06-19 08:31:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
 49%|████▉     | 5167/10519 [1:21:49<1:19:00,  1.13it/s][NeMo W 2026-06-19 08:31:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.27it/s]
 49%|████▉     | 5168/10519 [1:21:50<1:20:25,  1.11it/s][NeMo W 2026-06-19 08:31:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 49%|████▉     | 5169/10519 [1:21:51<1:26:55,  1.03it/s][NeMo W 2026-06-19 08:31:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 49%|████▉     | 5170/10519 [1:21:52<1:26:00,  1.04it/s][NeMo W 2026-06-19 08:31:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 49%|████▉     | 5171/10519 [1:21:54<1:29:31,  1.00s/it][NeMo W 2026-06-19 08:31:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 49%|████▉     | 5172/10519 [1:21:54<1:27:32,  1.02it/s][NeMo W 2026-06-19 08:31:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 49%|████▉     | 5173/10519 [1:21:56<1:29:26,  1.00s/it][NeMo W 2026-06-19 08:31:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.92it/s]
 49%|████▉     | 5174/10519 [1:21:56<1:26:59,  1.02it/s][NeMo W 2026-06-19 08:31:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 49%|████▉     | 5175/10519 [1:21:57<1:26:07,  1.03it/s][NeMo W 2026-06-19 08:31:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 49%|████▉     | 5176/10519 [1:21:58<1:25:39,  1.04it/s][NeMo W 2026-06-19 08:31:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 49%|████▉     | 5177/10519 [1:21:59<1:26:34,  1.03it/s][NeMo W 2026-06-19 08:31:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 49%|████▉     | 5178/10519 [1:22:00<1:30:07,  1.01s/it][NeMo W 2026-06-19 08:31:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 49%|████▉     | 5179/10519 [1:22:01<1:31:27,  1.03s/it][NeMo W 2026-06-19 08:31:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:31:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]

Checkpoint saved: 5200 samples

[NeMo W 2026-06-19 08:32:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 49%|████▉     | 5201/10519 [1:22:23<1:35:39,  1.08s/it][NeMo W 2026-06-19 08:32:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 49%|████▉     | 5202/10519 [1:22:24<1:37:31,  1.10s/it][NeMo W 2026-06-19 08:32:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.11it/s]
 49%|████▉     | 5203/10519 [1:22:25<1:34:14,  1.06s/it][NeMo W 2026-06-19 08:32:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.17it/s]
 49%|████▉     | 5204/10519 [1:22:26<1:33:11,  1.05s/it][NeMo W 2026-06-19 08:32:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.20it/s]
 49%|████▉     | 5205/10519 [1:22:27<1:37:35,  1.10s/it][NeMo W 2026-06-19 08:32:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 49%|████▉     | 5206/10519 [1:22:28<1:33:39,  1.06s/it][NeMo W 2026-06-19 08:32:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 50%|████▉     | 5207/10519 [1:22:29<1:27:10,  1.02it/s][NeMo W 2026-06-19 08:32:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 50%|████▉     | 5208/10519 [1:22:30<1:27:08,  1.02it/s][NeMo W 2026-06-19 08:32:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 50%|████▉     | 5209/10519 [1:22:31<1:27:03,  1.02it/s][NeMo W 2026-06-19 08:32:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 50%|████▉     | 5210/10519 [1:22:32<1:30:38,  1.02s/it][NeMo W 2026-06-19 08:32:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 50%|████▉     | 5211/10519 [1:22:33<1:27:51,  1.01it/s][NeMo W 2026-06-19 08:32:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 50%|████▉     | 5212/10519 [1:22:34<1:29:27,  1.01s/it][NeMo W 2026-06-19 08:32:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 50%|████▉     | 5213/10519 [1:22:35<1:26:25,  1.02it/s][NeMo W 2026-06-19 08:32:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 50%|████▉     | 5214/10519 [1:22:36<1:25:08,  1.04it/s][NeMo W 2026-06-19 08:32:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 50%|████▉     | 5215/10519 [1:22:37<1:25:33,  1.03it/s][NeMo W 2026-06-19 08:32:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]
 50%|████▉     | 5216/10519 [1:22:38<1:24:50,  1.04it/s][NeMo W 2026-06-19 08:32:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.72it/s]
 50%|████▉     | 5217/10519 [1:22:39<1:27:24,  1.01it/s][NeMo W 2026-06-19 08:32:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.19it/s]
 50%|████▉     | 5218/10519 [1:22:40<1:30:39,  1.03s/it][NeMo W 2026-06-19 08:32:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 50%|████▉     | 5219/10519 [1:22:41<1:28:38,  1.00s/it][NeMo W 2026-06-19 08:32:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
 50%|████▉     | 5220/10519 [1:22:42<1:25:03,  1.04it/s][NeMo W 2026-06-19 08:32:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 50%|████▉     | 5221/10519 [1:22:43<1:25:25,  1.03it/s][NeMo W 2026-06-19 08:32:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 50%|████▉     | 5222/10519 [1:22:44<1:25:56,  1.03it/s][NeMo W 2026-06-19 08:32:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 50%|████▉     | 5223/10519 [1:22:44<1:22:29,  1.07it/s][NeMo W 2026-06-19 08:32:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 50%|████▉     | 5224/10519 [1:22:46<1:24:59,  1.04it/s][NeMo W 2026-06-19 08:32:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 50%|████▉     | 5225/10519 [1:22:46<1:24:28,  1.04it/s][NeMo W 2026-06-19 08:32:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 50%|████▉     | 5226/10519 [1:22:47<1:25:03,  1.04it/s][NeMo W 2026-06-19 08:32:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 50%|████▉     | 5227/10519 [1:22:48<1:24:29,  1.04it/s][NeMo W 2026-06-19 08:32:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 50%|████▉     | 5228/10519 [1:22:49<1:25:46,  1.03it/s][NeMo W 2026-06-19 08:32:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 50%|████▉     | 5229/10519 [1:22:50<1:25:53,  1.03it/s][NeMo W 2026-06-19 08:32:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 5250 samples

[NeMo W 2026-06-19 08:32:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 50%|████▉     | 5251/10519 [1:23:14<1:39:35,  1.13s/it][NeMo W 2026-06-19 08:32:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 50%|████▉     | 5252/10519 [1:23:15<1:38:44,  1.12s/it][NeMo W 2026-06-19 08:32:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 50%|████▉     | 5253/10519 [1:23:16<1:35:01,  1.08s/it][NeMo W 2026-06-19 08:32:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 50%|████▉     | 5254/10519 [1:23:17<1:32:03,  1.05s/it][NeMo W 2026-06-19 08:32:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:32:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 50%|████▉     | 5255/10519 [1:23:18<1:34:45,  1.08s/it][NeMo W 2026-06-19 08:33:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.69it/s]
 50%|████▉     | 5256/10519 [1:23:20<1:51:21,  1.27s/it][NeMo W 2026-06-19 08:33:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 50%|████▉     | 5257/10519 [1:23:21<1:42:56,  1.17s/it][NeMo W 2026-06-19 08:33:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 50%|████▉     | 5258/10519 [1:23:22<1:37:40,  1.11s/it][NeMo W 2026-06-19 08:33:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 50%|████▉     | 5259/10519 [1:23:23<1:32:22,  1.05s/it][NeMo W 2026-06-19 08:33:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 50%|█████     | 5260/10519 [1:23:24<1:29:20,  1.02s/it][NeMo W 2026-06-19 08:33:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 50%|█████     | 5261/10519 [1:23:25<1:27:52,  1.00s/it][NeMo W 2026-06-19 08:33:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 50%|█████     | 5262/10519 [1:23:26<1:29:39,  1.02s/it][NeMo W 2026-06-19 08:33:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 50%|█████     | 5263/10519 [1:23:27<1:27:26,  1.00it/s][NeMo W 2026-06-19 08:33:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 50%|█████     | 5264/10519 [1:23:28<1:27:47,  1.00s/it][NeMo W 2026-06-19 08:33:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 50%|█████     | 5265/10519 [1:23:29<1:26:43,  1.01it/s][NeMo W 2026-06-19 08:33:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.18it/s]
 50%|█████     | 5266/10519 [1:23:30<1:28:35,  1.01s/it][NeMo W 2026-06-19 08:33:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 50%|█████     | 5267/10519 [1:23:31<1:27:23,  1.00it/s][NeMo W 2026-06-19 08:33:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 50%|█████     | 5268/10519 [1:23:32<1:28:17,  1.01s/it][NeMo W 2026-06-19 08:33:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.25it/s]
 50%|█████     | 5269/10519 [1:23:33<1:23:10,  1.05it/s][NeMo W 2026-06-19 08:33:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 50%|█████     | 5270/10519 [1:23:34<1:25:27,  1.02it/s][NeMo W 2026-06-19 08:33:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.44it/s]
 50%|█████     | 5271/10519 [1:23:35<1:24:52,  1.03it/s][NeMo W 2026-06-19 08:33:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 50%|█████     | 5272/10519 [1:23:36<1:26:11,  1.01it/s][NeMo W 2026-06-19 08:33:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 50%|█████     | 5273/10519 [1:23:37<1:28:22,  1.01s/it][NeMo W 2026-06-19 08:33:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 50%|█████     | 5274/10519 [1:23:38<1:25:55,  1.02it/s][NeMo W 2026-06-19 08:33:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 50%|█████     | 5275/10519 [1:23:39<1:19:38,  1.10it/s][NeMo W 2026-06-19 08:33:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 50%|█████     | 5276/10519 [1:23:39<1:20:00,  1.09it/s][NeMo W 2026-06-19 08:33:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 50%|█████     | 5277/10519 [1:23:40<1:19:48,  1.09it/s][NeMo W 2026-06-19 08:33:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 50%|█████     | 5278/10519 [1:23:41<1:16:32,  1.14it/s][NeMo W 2026-06-19 08:33:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.37it/s]
 50%|█████     | 5279/10519 [1:23:42<1:17:10,  1.13it/s][NeMo W 2026-06-19 08:33:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]

Checkpoint saved: 5300 samples

[NeMo W 2026-06-19 08:33:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 50%|█████     | 5301/10519 [1:24:03<1:38:11,  1.13s/it][NeMo W 2026-06-19 08:33:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 50%|█████     | 5302/10519 [1:24:04<1:32:49,  1.07s/it][NeMo W 2026-06-19 08:33:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 50%|█████     | 5303/10519 [1:24:05<1:30:21,  1.04s/it][NeMo W 2026-06-19 08:33:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 50%|█████     | 5304/10519 [1:24:06<1:21:39,  1.06it/s][NeMo W 2026-06-19 08:33:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 50%|█████     | 5305/10519 [1:24:07<1:21:18,  1.07it/s][NeMo W 2026-06-19 08:33:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 50%|█████     | 5306/10519 [1:24:08<1:23:44,  1.04it/s][NeMo W 2026-06-19 08:33:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 50%|█████     | 5307/10519 [1:24:09<1:24:40,  1.03it/s][NeMo W 2026-06-19 08:33:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 50%|█████     | 5308/10519 [1:24:10<1:23:21,  1.04it/s][NeMo W 2026-06-19 08:33:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 50%|█████     | 5309/10519 [1:24:11<1:28:48,  1.02s/it][NeMo W 2026-06-19 08:33:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.17it/s]
 50%|█████     | 5310/10519 [1:24:12<1:34:27,  1.09s/it][NeMo W 2026-06-19 08:33:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 50%|█████     | 5311/10519 [1:24:13<1:30:07,  1.04s/it][NeMo W 2026-06-19 08:33:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 50%|█████     | 5312/10519 [1:24:14<1:27:27,  1.01s/it][NeMo W 2026-06-19 08:33:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 51%|█████     | 5313/10519 [1:24:15<1:26:09,  1.01it/s][NeMo W 2026-06-19 08:33:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
 51%|█████     | 5314/10519 [1:24:16<1:23:43,  1.04it/s][NeMo W 2026-06-19 08:33:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 51%|█████     | 5315/10519 [1:24:17<1:23:08,  1.04it/s][NeMo W 2026-06-19 08:33:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 51%|█████     | 5316/10519 [1:24:18<1:22:34,  1.05it/s][NeMo W 2026-06-19 08:33:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:33:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 51%|█████     | 5317/10519 [1:24:19<1:23:50,  1.03it/s][NeMo W 2026-06-19 08:34:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 51%|█████     | 5318/10519 [1:24:19<1:18:29,  1.10it/s][NeMo W 2026-06-19 08:34:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 51%|█████     | 5319/10519 [1:24:20<1:21:41,  1.06it/s][NeMo W 2026-06-19 08:34:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 51%|█████     | 5320/10519 [1:24:21<1:22:37,  1.05it/s][NeMo W 2026-06-19 08:34:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 51%|█████     | 5321/10519 [1:24:22<1:23:05,  1.04it/s][NeMo W 2026-06-19 08:34:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.51it/s]
 51%|█████     | 5322/10519 [1:24:23<1:20:58,  1.07it/s][NeMo W 2026-06-19 08:34:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 51%|█████     | 5323/10519 [1:24:24<1:23:30,  1.04it/s][NeMo W 2026-06-19 08:34:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 51%|█████     | 5324/10519 [1:24:25<1:23:07,  1.04it/s][NeMo W 2026-06-19 08:34:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 51%|█████     | 5325/10519 [1:24:26<1:16:51,  1.13it/s][NeMo W 2026-06-19 08:34:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 51%|█████     | 5326/10519 [1:24:27<1:24:12,  1.03it/s][NeMo W 2026-06-19 08:34:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 51%|█████     | 5327/10519 [1:24:28<1:24:50,  1.02it/s][NeMo W 2026-06-19 08:34:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 51%|█████     | 5328/10519 [1:24:29<1:25:36,  1.01it/s][NeMo W 2026-06-19 08:34:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.74it/s]
 51%|█████     | 5329/10519 [1:24:30<1:25:18,  1.01it/s][NeMo W 2026-06-19 08:34:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]

Checkpoint saved: 5350 samples

[NeMo W 2026-06-19 08:34:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.62it/s]
 51%|█████     | 5351/10519 [1:24:52<1:44:32,  1.21s/it][NeMo W 2026-06-19 08:34:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.27it/s]
 51%|█████     | 5352/10519 [1:24:54<1:40:51,  1.17s/it][NeMo W 2026-06-19 08:34:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 51%|█████     | 5353/10519 [1:24:55<1:35:57,  1.11s/it][NeMo W 2026-06-19 08:34:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 51%|█████     | 5354/10519 [1:24:56<1:33:51,  1.09s/it][NeMo W 2026-06-19 08:34:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 51%|█████     | 5355/10519 [1:24:57<1:31:58,  1.07s/it][NeMo W 2026-06-19 08:34:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 51%|█████     | 5356/10519 [1:24:58<1:29:57,  1.05s/it][NeMo W 2026-06-19 08:34:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 51%|█████     | 5357/10519 [1:24:58<1:26:41,  1.01s/it][NeMo W 2026-06-19 08:34:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 51%|█████     | 5358/10519 [1:24:59<1:24:38,  1.02it/s][NeMo W 2026-06-19 08:34:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.45it/s]
 51%|█████     | 5359/10519 [1:25:01<1:29:30,  1.04s/it][NeMo W 2026-06-19 08:34:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 51%|█████     | 5360/10519 [1:25:01<1:25:12,  1.01it/s][NeMo W 2026-06-19 08:34:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 51%|█████     | 5361/10519 [1:25:02<1:25:23,  1.01it/s][NeMo W 2026-06-19 08:34:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 51%|█████     | 5362/10519 [1:25:04<1:29:38,  1.04s/it][NeMo W 2026-06-19 08:34:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 51%|█████     | 5363/10519 [1:25:04<1:24:26,  1.02it/s][NeMo W 2026-06-19 08:34:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 51%|█████     | 5364/10519 [1:25:06<1:26:50,  1.01s/it][NeMo W 2026-06-19 08:34:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 51%|█████     | 5365/10519 [1:25:07<1:26:52,  1.01s/it][NeMo W 2026-06-19 08:34:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 51%|█████     | 5366/10519 [1:25:07<1:20:19,  1.07it/s][NeMo W 2026-06-19 08:34:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
 51%|█████     | 5367/10519 [1:25:08<1:19:50,  1.08it/s][NeMo W 2026-06-19 08:34:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 51%|█████     | 5368/10519 [1:25:09<1:19:56,  1.07it/s][NeMo W 2026-06-19 08:34:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.48it/s]
 51%|█████     | 5369/10519 [1:25:10<1:22:15,  1.04it/s][NeMo W 2026-06-19 08:34:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 51%|█████     | 5370/10519 [1:25:11<1:16:19,  1.12it/s][NeMo W 2026-06-19 08:34:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 51%|█████     | 5371/10519 [1:25:12<1:19:13,  1.08it/s][NeMo W 2026-06-19 08:34:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 51%|█████     | 5372/10519 [1:25:13<1:19:57,  1.07it/s][NeMo W 2026-06-19 08:34:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 51%|█████     | 5373/10519 [1:25:14<1:15:23,  1.14it/s][NeMo W 2026-06-19 08:34:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 51%|█████     | 5374/10519 [1:25:14<1:10:16,  1.22it/s][NeMo W 2026-06-19 08:34:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 51%|█████     | 5375/10519 [1:25:15<1:09:51,  1.23it/s][NeMo W 2026-06-19 08:34:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.50it/s]
 51%|█████     | 5376/10519 [1:25:16<1:09:39,  1.23it/s][NeMo W 2026-06-19 08:34:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 51%|█████     | 5377/10519 [1:25:17<1:13:24,  1.17it/s][NeMo W 2026-06-19 08:34:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 51%|█████     | 5378/10519 [1:25:18<1:11:58,  1.19it/s][NeMo W 2026-06-19 08:34:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:34:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 51%|█████     | 5379/10519 [1:25:19<1:14:03,  1.16it/s][NeMo W 2026-06-19 08:35:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]

Checkpoint saved: 5400 samples

[NeMo W 2026-06-19 08:35:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 51%|█████▏    | 5401/10519 [1:25:40<1:32:56,  1.09s/it][NeMo W 2026-06-19 08:35:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 51%|█████▏    | 5402/10519 [1:25:41<1:30:29,  1.06s/it][NeMo W 2026-06-19 08:35:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 51%|█████▏    | 5403/10519 [1:25:42<1:24:04,  1.01it/s][NeMo W 2026-06-19 08:35:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 51%|█████▏    | 5404/10519 [1:25:43<1:19:50,  1.07it/s][NeMo W 2026-06-19 08:35:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 51%|█████▏    | 5405/10519 [1:25:43<1:13:48,  1.15it/s][NeMo W 2026-06-19 08:35:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 51%|█████▏    | 5406/10519 [1:25:44<1:17:51,  1.09it/s][NeMo W 2026-06-19 08:35:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 51%|█████▏    | 5407/10519 [1:25:45<1:19:03,  1.08it/s][NeMo W 2026-06-19 08:35:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 51%|█████▏    | 5408/10519 [1:25:46<1:19:57,  1.07it/s][NeMo W 2026-06-19 08:35:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.66it/s]
 51%|█████▏    | 5409/10519 [1:25:47<1:16:01,  1.12it/s][NeMo W 2026-06-19 08:35:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 51%|█████▏    | 5410/10519 [1:25:48<1:14:59,  1.14it/s][NeMo W 2026-06-19 08:35:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 51%|█████▏    | 5411/10519 [1:25:49<1:15:28,  1.13it/s][NeMo W 2026-06-19 08:35:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 51%|█████▏    | 5412/10519 [1:25:50<1:16:35,  1.11it/s][NeMo W 2026-06-19 08:35:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 51%|█████▏    | 5413/10519 [1:25:51<1:17:59,  1.09it/s][NeMo W 2026-06-19 08:35:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 51%|█████▏    | 5414/10519 [1:25:52<1:19:12,  1.07it/s][NeMo W 2026-06-19 08:35:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 51%|█████▏    | 5415/10519 [1:25:53<1:22:24,  1.03it/s][NeMo W 2026-06-19 08:35:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.16it/s]
 51%|█████▏    | 5416/10519 [1:25:54<1:25:12,  1.00s/it][NeMo W 2026-06-19 08:35:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 51%|█████▏    | 5417/10519 [1:25:55<1:23:31,  1.02it/s][NeMo W 2026-06-19 08:35:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.35it/s]
 52%|█████▏    | 5418/10519 [1:25:56<1:19:00,  1.08it/s][NeMo W 2026-06-19 08:35:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 52%|█████▏    | 5419/10519 [1:25:57<1:18:44,  1.08it/s][NeMo W 2026-06-19 08:35:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 52%|█████▏    | 5420/10519 [1:25:57<1:18:22,  1.08it/s][NeMo W 2026-06-19 08:35:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 52%|█████▏    | 5421/10519 [1:25:58<1:20:18,  1.06it/s][NeMo W 2026-06-19 08:35:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.88it/s]
 52%|█████▏    | 5422/10519 [1:25:59<1:14:13,  1.14it/s][NeMo W 2026-06-19 08:35:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 52%|█████▏    | 5423/10519 [1:26:00<1:11:28,  1.19it/s][NeMo W 2026-06-19 08:35:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 52%|█████▏    | 5424/10519 [1:26:01<1:14:57,  1.13it/s][NeMo W 2026-06-19 08:35:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.98it/s]
 52%|█████▏    | 5425/10519 [1:26:02<1:19:20,  1.07it/s][NeMo W 2026-06-19 08:35:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 52%|█████▏    | 5426/10519 [1:26:03<1:13:40,  1.15it/s][NeMo W 2026-06-19 08:35:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.18it/s]
 52%|█████▏    | 5427/10519 [1:26:03<1:11:19,  1.19it/s][NeMo W 2026-06-19 08:35:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 52%|█████▏    | 5428/10519 [1:26:04<1:14:51,  1.13it/s][NeMo W 2026-06-19 08:35:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 52%|█████▏    | 5429/10519 [1:26:05<1:17:30,  1.09it/s][NeMo W 2026-06-19 08:35:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:35:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]

Checkpoint saved: 5450 samples

[NeMo W 2026-06-19 08:36:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 52%|█████▏    | 5451/10519 [1:26:28<1:35:23,  1.13s/it][NeMo W 2026-06-19 08:36:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.10it/s]
 52%|█████▏    | 5452/10519 [1:26:29<1:31:08,  1.08s/it][NeMo W 2026-06-19 08:36:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 52%|█████▏    | 5453/10519 [1:26:29<1:27:47,  1.04s/it][NeMo W 2026-06-19 08:36:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 52%|█████▏    | 5454/10519 [1:26:30<1:27:02,  1.03s/it][NeMo W 2026-06-19 08:36:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 52%|█████▏    | 5455/10519 [1:26:31<1:25:02,  1.01s/it][NeMo W 2026-06-19 08:36:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 52%|█████▏    | 5456/10519 [1:26:33<1:28:25,  1.05s/it][NeMo W 2026-06-19 08:36:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.30it/s]
 52%|█████▏    | 5457/10519 [1:26:34<1:26:45,  1.03s/it][NeMo W 2026-06-19 08:36:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 52%|█████▏    | 5458/10519 [1:26:34<1:21:38,  1.03it/s][NeMo W 2026-06-19 08:36:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 52%|█████▏    | 5459/10519 [1:26:35<1:21:03,  1.04it/s][NeMo W 2026-06-19 08:36:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 52%|█████▏    | 5460/10519 [1:26:36<1:25:35,  1.02s/it][NeMo W 2026-06-19 08:36:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.69it/s]
 52%|█████▏    | 5461/10519 [1:26:37<1:23:44,  1.01it/s][NeMo W 2026-06-19 08:36:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 52%|█████▏    | 5462/10519 [1:26:38<1:23:26,  1.01it/s][NeMo W 2026-06-19 08:36:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 52%|█████▏    | 5463/10519 [1:26:39<1:17:51,  1.08it/s][NeMo W 2026-06-19 08:36:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 52%|█████▏    | 5464/10519 [1:26:40<1:18:43,  1.07it/s][NeMo W 2026-06-19 08:36:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 52%|█████▏    | 5465/10519 [1:26:41<1:12:48,  1.16it/s][NeMo W 2026-06-19 08:36:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 52%|█████▏    | 5466/10519 [1:26:42<1:15:18,  1.12it/s][NeMo W 2026-06-19 08:36:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 52%|█████▏    | 5467/10519 [1:26:43<1:11:29,  1.18it/s][NeMo W 2026-06-19 08:36:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 52%|█████▏    | 5468/10519 [1:26:44<1:18:35,  1.07it/s][NeMo W 2026-06-19 08:36:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 52%|█████▏    | 5469/10519 [1:26:45<1:19:11,  1.06it/s][NeMo W 2026-06-19 08:36:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 52%|█████▏    | 5470/10519 [1:26:46<1:18:37,  1.07it/s][NeMo W 2026-06-19 08:36:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.60it/s]
 52%|█████▏    | 5471/10519 [1:26:47<1:20:19,  1.05it/s][NeMo W 2026-06-19 08:36:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 52%|█████▏    | 5472/10519 [1:26:47<1:19:46,  1.05it/s][NeMo W 2026-06-19 08:36:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 52%|█████▏    | 5473/10519 [1:26:48<1:21:30,  1.03it/s][NeMo W 2026-06-19 08:36:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 52%|█████▏    | 5474/10519 [1:26:49<1:20:09,  1.05it/s][NeMo W 2026-06-19 08:36:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 52%|█████▏    | 5475/10519 [1:26:50<1:19:31,  1.06it/s][NeMo W 2026-06-19 08:36:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 52%|█████▏    | 5476/10519 [1:26:51<1:18:28,  1.07it/s][NeMo W 2026-06-19 08:36:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 52%|█████▏    | 5477/10519 [1:26:52<1:18:09,  1.08it/s][NeMo W 2026-06-19 08:36:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 52%|█████▏    | 5478/10519 [1:26:53<1:17:24,  1.09it/s][NeMo W 2026-06-19 08:36:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 52%|█████▏    | 5479/10519 [1:26:54<1:13:31,  1.14it/s][NeMo W 2026-06-19 08:36:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]

Checkpoint saved: 5500 samples

[NeMo W 2026-06-19 08:36:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 52%|█████▏    | 5501/10519 [1:27:16<1:38:32,  1.18s/it][NeMo W 2026-06-19 08:36:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 52%|█████▏    | 5502/10519 [1:27:17<1:32:30,  1.11s/it][NeMo W 2026-06-19 08:36:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:36:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 52%|█████▏    | 5503/10519 [1:27:18<1:28:59,  1.06s/it][NeMo W 2026-06-19 08:37:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 52%|█████▏    | 5504/10519 [1:27:19<1:25:38,  1.02s/it][NeMo W 2026-06-19 08:37:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 52%|█████▏    | 5505/10519 [1:27:20<1:16:34,  1.09it/s][NeMo W 2026-06-19 08:37:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 52%|█████▏    | 5506/10519 [1:27:21<1:18:26,  1.07it/s][NeMo W 2026-06-19 08:37:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 52%|█████▏    | 5507/10519 [1:27:21<1:17:41,  1.08it/s][NeMo W 2026-06-19 08:37:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 52%|█████▏    | 5508/10519 [1:27:22<1:18:20,  1.07it/s][NeMo W 2026-06-19 08:37:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 52%|█████▏    | 5509/10519 [1:27:23<1:19:28,  1.05it/s][NeMo W 2026-06-19 08:37:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.66it/s]
 52%|█████▏    | 5510/10519 [1:27:25<1:29:33,  1.07s/it][NeMo W 2026-06-19 08:37:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 52%|█████▏    | 5511/10519 [1:27:26<1:26:59,  1.04s/it][NeMo W 2026-06-19 08:37:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 52%|█████▏    | 5512/10519 [1:27:27<1:25:44,  1.03s/it][NeMo W 2026-06-19 08:37:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 52%|█████▏    | 5513/10519 [1:27:27<1:17:34,  1.08it/s][NeMo W 2026-06-19 08:37:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 52%|█████▏    | 5514/10519 [1:27:28<1:18:27,  1.06it/s][NeMo W 2026-06-19 08:37:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 52%|█████▏    | 5515/10519 [1:27:29<1:18:25,  1.06it/s][NeMo W 2026-06-19 08:37:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 52%|█████▏    | 5516/10519 [1:27:30<1:20:53,  1.03it/s][NeMo W 2026-06-19 08:37:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 52%|█████▏    | 5517/10519 [1:27:31<1:15:48,  1.10it/s][NeMo W 2026-06-19 08:37:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 52%|█████▏    | 5518/10519 [1:27:32<1:17:54,  1.07it/s][NeMo W 2026-06-19 08:37:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 52%|█████▏    | 5519/10519 [1:27:33<1:13:42,  1.13it/s][NeMo W 2026-06-19 08:37:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 52%|█████▏    | 5520/10519 [1:27:34<1:11:56,  1.16it/s][NeMo W 2026-06-19 08:37:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 52%|█████▏    | 5521/10519 [1:27:35<1:15:10,  1.11it/s][NeMo W 2026-06-19 08:37:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.84it/s]
 52%|█████▏    | 5522/10519 [1:27:35<1:11:31,  1.16it/s][NeMo W 2026-06-19 08:37:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 53%|█████▎    | 5523/10519 [1:27:37<1:32:40,  1.11s/it][NeMo W 2026-06-19 08:37:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 53%|█████▎    | 5524/10519 [1:27:38<1:33:14,  1.12s/it][NeMo W 2026-06-19 08:37:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 53%|█████▎    | 5525/10519 [1:27:39<1:29:57,  1.08s/it][NeMo W 2026-06-19 08:37:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 53%|█████▎    | 5526/10519 [1:27:40<1:23:38,  1.01s/it][NeMo W 2026-06-19 08:37:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 53%|█████▎    | 5527/10519 [1:27:41<1:21:57,  1.02it/s][NeMo W 2026-06-19 08:37:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 53%|█████▎    | 5528/10519 [1:27:42<1:27:12,  1.05s/it][NeMo W 2026-06-19 08:37:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 53%|█████▎    | 5529/10519 [1:27:43<1:22:04,  1.01it/s][NeMo W 2026-06-19 08:37:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]

Checkpoint saved: 5550 samples

[NeMo W 2026-06-19 08:37:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.19it/s]
 53%|█████▎    | 5551/10519 [1:28:05<1:32:26,  1.12s/it][NeMo W 2026-06-19 08:37:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.67it/s]
 53%|█████▎    | 5552/10519 [1:28:06<1:32:16,  1.11s/it][NeMo W 2026-06-19 08:37:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 53%|█████▎    | 5553/10519 [1:28:07<1:36:48,  1.17s/it][NeMo W 2026-06-19 08:37:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.04it/s]
 53%|█████▎    | 5554/10519 [1:28:08<1:31:03,  1.10s/it][NeMo W 2026-06-19 08:37:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 53%|█████▎    | 5555/10519 [1:28:09<1:22:11,  1.01it/s][NeMo W 2026-06-19 08:37:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 53%|█████▎    | 5556/10519 [1:28:10<1:19:38,  1.04it/s][NeMo W 2026-06-19 08:37:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.21it/s]
 53%|█████▎    | 5557/10519 [1:28:11<1:13:54,  1.12it/s][NeMo W 2026-06-19 08:37:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 53%|█████▎    | 5558/10519 [1:28:12<1:15:38,  1.09it/s][NeMo W 2026-06-19 08:37:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 53%|█████▎    | 5559/10519 [1:28:13<1:15:36,  1.09it/s][NeMo W 2026-06-19 08:37:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.46it/s]
 53%|█████▎    | 5560/10519 [1:28:14<1:19:32,  1.04it/s][NeMo W 2026-06-19 08:37:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.94it/s]
 53%|█████▎    | 5561/10519 [1:28:15<1:16:22,  1.08it/s][NeMo W 2026-06-19 08:37:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 53%|█████▎    | 5562/10519 [1:28:15<1:12:37,  1.14it/s][NeMo W 2026-06-19 08:37:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 53%|█████▎    | 5563/10519 [1:28:16<1:16:41,  1.08it/s][NeMo W 2026-06-19 08:37:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.22it/s]
 53%|█████▎    | 5564/10519 [1:28:17<1:18:25,  1.05it/s][NeMo W 2026-06-19 08:37:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:37:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.42it/s]
 53%|█████▎    | 5565/10519 [1:28:18<1:14:33,  1.11it/s][NeMo W 2026-06-19 08:38:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.57it/s]
 53%|█████▎    | 5566/10519 [1:28:19<1:21:29,  1.01it/s][NeMo W 2026-06-19 08:38:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 53%|█████▎    | 5567/10519 [1:28:20<1:21:39,  1.01it/s][NeMo W 2026-06-19 08:38:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 53%|█████▎    | 5568/10519 [1:28:21<1:20:42,  1.02it/s][NeMo W 2026-06-19 08:38:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 53%|█████▎    | 5569/10519 [1:28:22<1:22:46,  1.00s/it][NeMo W 2026-06-19 08:38:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.54it/s]
 53%|█████▎    | 5570/10519 [1:28:23<1:22:03,  1.01it/s][NeMo W 2026-06-19 08:38:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 53%|█████▎    | 5571/10519 [1:28:24<1:20:38,  1.02it/s][NeMo W 2026-06-19 08:38:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 53%|█████▎    | 5572/10519 [1:28:25<1:19:35,  1.04it/s][NeMo W 2026-06-19 08:38:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 53%|█████▎    | 5573/10519 [1:28:26<1:18:54,  1.04it/s][NeMo W 2026-06-19 08:38:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 53%|█████▎    | 5574/10519 [1:28:27<1:18:29,  1.05it/s][NeMo W 2026-06-19 08:38:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 53%|█████▎    | 5575/10519 [1:28:28<1:14:17,  1.11it/s][NeMo W 2026-06-19 08:38:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 53%|█████▎    | 5576/10519 [1:28:29<1:16:21,  1.08it/s][NeMo W 2026-06-19 08:38:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.19it/s]
 53%|█████▎    | 5577/10519 [1:28:30<1:18:47,  1.05it/s][NeMo W 2026-06-19 08:38:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 53%|█████▎    | 5578/10519 [1:28:31<1:20:20,  1.02it/s][NeMo W 2026-06-19 08:38:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 53%|█████▎    | 5579/10519 [1:28:32<1:19:26,  1.04it/s][NeMo W 2026-06-19 08:38:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 5600 samples

[NeMo W 2026-06-19 08:38:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.55it/s]
 53%|█████▎    | 5601/10519 [1:28:54<1:33:04,  1.14s/it][NeMo W 2026-06-19 08:38:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 53%|█████▎    | 5602/10519 [1:28:55<1:31:34,  1.12s/it][NeMo W 2026-06-19 08:38:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 53%|█████▎    | 5603/10519 [1:28:56<1:28:49,  1.08s/it][NeMo W 2026-06-19 08:38:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 53%|█████▎    | 5604/10519 [1:28:57<1:22:26,  1.01s/it][NeMo W 2026-06-19 08:38:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.76it/s]
 53%|█████▎    | 5605/10519 [1:28:58<1:22:22,  1.01s/it][NeMo W 2026-06-19 08:38:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.09it/s]
 53%|█████▎    | 5606/10519 [1:28:59<1:23:29,  1.02s/it][NeMo W 2026-06-19 08:38:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 53%|█████▎    | 5607/10519 [1:29:00<1:24:06,  1.03s/it][NeMo W 2026-06-19 08:38:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.51it/s]
 53%|█████▎    | 5608/10519 [1:29:01<1:23:30,  1.02s/it][NeMo W 2026-06-19 08:38:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 53%|█████▎    | 5609/10519 [1:29:04<2:13:58,  1.64s/it][NeMo W 2026-06-19 08:38:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 53%|█████▎    | 5610/10519 [1:29:05<2:00:19,  1.47s/it][NeMo W 2026-06-19 08:38:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 53%|█████▎    | 5611/10519 [1:29:06<1:46:29,  1.30s/it][NeMo W 2026-06-19 08:38:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 53%|█████▎    | 5612/10519 [1:29:07<1:39:57,  1.22s/it][NeMo W 2026-06-19 08:38:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 53%|█████▎    | 5613/10519 [1:29:08<1:29:03,  1.09s/it][NeMo W 2026-06-19 08:38:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 53%|█████▎    | 5614/10519 [1:29:09<1:24:08,  1.03s/it][NeMo W 2026-06-19 08:38:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 53%|█████▎    | 5615/10519 [1:29:10<1:16:40,  1.07it/s][NeMo W 2026-06-19 08:38:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 53%|█████▎    | 5616/10519 [1:29:11<1:18:24,  1.04it/s][NeMo W 2026-06-19 08:38:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 53%|█████▎    | 5617/10519 [1:29:12<1:20:43,  1.01it/s][NeMo W 2026-06-19 08:38:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 53%|█████▎    | 5618/10519 [1:29:13<1:17:59,  1.05it/s][NeMo W 2026-06-19 08:38:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 53%|█████▎    | 5619/10519 [1:29:14<1:17:35,  1.05it/s][NeMo W 2026-06-19 08:38:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 53%|█████▎    | 5620/10519 [1:29:14<1:17:04,  1.06it/s][NeMo W 2026-06-19 08:38:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 53%|█████▎    | 5621/10519 [1:29:16<1:21:23,  1.00it/s][NeMo W 2026-06-19 08:38:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 53%|█████▎    | 5622/10519 [1:29:17<1:20:18,  1.02it/s][NeMo W 2026-06-19 08:38:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 53%|█████▎    | 5623/10519 [1:29:17<1:18:23,  1.04it/s][NeMo W 2026-06-19 08:38:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:38:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 53%|█████▎    | 5624/10519 [1:29:18<1:17:18,  1.06it/s][NeMo W 2026-06-19 08:39:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 53%|█████▎    | 5625/10519 [1:29:19<1:12:15,  1.13it/s][NeMo W 2026-06-19 08:39:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 53%|█████▎    | 5626/10519 [1:29:20<1:14:17,  1.10it/s][NeMo W 2026-06-19 08:39:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 53%|█████▎    | 5627/10519 [1:29:21<1:15:02,  1.09it/s][NeMo W 2026-06-19 08:39:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.18it/s]
 54%|█████▎    | 5628/10519 [1:29:22<1:15:25,  1.08it/s][NeMo W 2026-06-19 08:39:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.41it/s]
 54%|█████▎    | 5629/10519 [1:29:23<1:24:05,  1.03s/it][NeMo W 2026-06-19 08:39:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]

Checkpoint saved: 5650 samples

[NeMo W 2026-06-19 08:39:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 54%|█████▎    | 5651/10519 [1:29:46<1:32:57,  1.15s/it][NeMo W 2026-06-19 08:39:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 54%|█████▎    | 5652/10519 [1:29:47<1:27:29,  1.08s/it][NeMo W 2026-06-19 08:39:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 54%|█████▎    | 5653/10519 [1:29:47<1:22:55,  1.02s/it][NeMo W 2026-06-19 08:39:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 54%|█████▍    | 5654/10519 [1:29:48<1:20:52,  1.00it/s][NeMo W 2026-06-19 08:39:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 54%|█████▍    | 5655/10519 [1:29:49<1:20:12,  1.01it/s][NeMo W 2026-06-19 08:39:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 54%|█████▍    | 5656/10519 [1:29:50<1:21:27,  1.01s/it][NeMo W 2026-06-19 08:39:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 54%|█████▍    | 5657/10519 [1:29:51<1:21:07,  1.00s/it][NeMo W 2026-06-19 08:39:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 54%|█████▍    | 5658/10519 [1:29:52<1:19:45,  1.02it/s][NeMo W 2026-06-19 08:39:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 54%|█████▍    | 5659/10519 [1:29:53<1:19:15,  1.02it/s][NeMo W 2026-06-19 08:39:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 54%|█████▍    | 5660/10519 [1:29:54<1:19:02,  1.02it/s][NeMo W 2026-06-19 08:39:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 54%|█████▍    | 5661/10519 [1:29:55<1:17:56,  1.04it/s][NeMo W 2026-06-19 08:39:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 54%|█████▍    | 5662/10519 [1:29:56<1:12:35,  1.12it/s][NeMo W 2026-06-19 08:39:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 54%|█████▍    | 5663/10519 [1:29:57<1:14:03,  1.09it/s][NeMo W 2026-06-19 08:39:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 54%|█████▍    | 5664/10519 [1:29:58<1:17:33,  1.04it/s][NeMo W 2026-06-19 08:39:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 54%|█████▍    | 5665/10519 [1:29:59<1:18:18,  1.03it/s][NeMo W 2026-06-19 08:39:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 54%|█████▍    | 5666/10519 [1:30:00<1:14:21,  1.09it/s][NeMo W 2026-06-19 08:39:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 54%|█████▍    | 5667/10519 [1:30:01<1:15:44,  1.07it/s][NeMo W 2026-06-19 08:39:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 54%|█████▍    | 5668/10519 [1:30:02<1:17:38,  1.04it/s][NeMo W 2026-06-19 08:39:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 54%|█████▍    | 5669/10519 [1:30:03<1:17:52,  1.04it/s][NeMo W 2026-06-19 08:39:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 54%|█████▍    | 5670/10519 [1:30:04<1:19:26,  1.02it/s][NeMo W 2026-06-19 08:39:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 54%|█████▍    | 5671/10519 [1:30:05<1:14:51,  1.08it/s][NeMo W 2026-06-19 08:39:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 54%|█████▍    | 5672/10519 [1:30:05<1:12:52,  1.11it/s][NeMo W 2026-06-19 08:39:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.36it/s]
 54%|█████▍    | 5673/10519 [1:30:06<1:07:56,  1.19it/s][NeMo W 2026-06-19 08:39:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 54%|█████▍    | 5674/10519 [1:30:07<1:09:50,  1.16it/s][NeMo W 2026-06-19 08:39:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 54%|█████▍    | 5675/10519 [1:30:08<1:11:23,  1.13it/s][NeMo W 2026-06-19 08:39:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 54%|█████▍    | 5676/10519 [1:30:09<1:09:00,  1.17it/s][NeMo W 2026-06-19 08:39:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.77it/s]
 54%|█████▍    | 5677/10519 [1:30:10<1:10:23,  1.15it/s][NeMo W 2026-06-19 08:39:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 54%|█████▍    | 5678/10519 [1:30:12<1:39:19,  1.23s/it][NeMo W 2026-06-19 08:39:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 54%|█████▍    | 5679/10519 [1:30:12<1:28:22,  1.10s/it][NeMo W 2026-06-19 08:39:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:39:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]

Checkpoint saved: 5700 samples

[NeMo W 2026-06-19 08:40:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 54%|█████▍    | 5701/10519 [1:30:34<1:30:05,  1.12s/it][NeMo W 2026-06-19 08:40:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 54%|█████▍    | 5702/10519 [1:30:35<1:27:00,  1.08s/it][NeMo W 2026-06-19 08:40:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 54%|█████▍    | 5703/10519 [1:30:36<1:25:22,  1.06s/it][NeMo W 2026-06-19 08:40:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 54%|█████▍    | 5704/10519 [1:30:37<1:21:59,  1.02s/it][NeMo W 2026-06-19 08:40:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 54%|█████▍    | 5705/10519 [1:30:38<1:24:10,  1.05s/it][NeMo W 2026-06-19 08:40:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 54%|█████▍    | 5706/10519 [1:30:39<1:20:57,  1.01s/it][NeMo W 2026-06-19 08:40:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 54%|█████▍    | 5707/10519 [1:30:40<1:17:35,  1.03it/s][NeMo W 2026-06-19 08:40:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 54%|█████▍    | 5708/10519 [1:30:41<1:18:34,  1.02it/s][NeMo W 2026-06-19 08:40:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.95it/s]
 54%|█████▍    | 5709/10519 [1:30:42<1:18:23,  1.02it/s][NeMo W 2026-06-19 08:40:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.22it/s]
 54%|█████▍    | 5710/10519 [1:30:43<1:15:46,  1.06it/s][NeMo W 2026-06-19 08:40:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 54%|█████▍    | 5711/10519 [1:30:44<1:16:09,  1.05it/s][NeMo W 2026-06-19 08:40:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 54%|█████▍    | 5712/10519 [1:30:44<1:11:58,  1.11it/s][NeMo W 2026-06-19 08:40:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 54%|█████▍    | 5713/10519 [1:30:46<1:32:54,  1.16s/it][NeMo W 2026-06-19 08:40:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 54%|█████▍    | 5714/10519 [1:30:47<1:28:58,  1.11s/it][NeMo W 2026-06-19 08:40:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 54%|█████▍    | 5715/10519 [1:30:48<1:24:59,  1.06s/it][NeMo W 2026-06-19 08:40:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 54%|█████▍    | 5716/10519 [1:30:49<1:21:37,  1.02s/it][NeMo W 2026-06-19 08:40:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 54%|█████▍    | 5717/10519 [1:30:50<1:20:59,  1.01s/it][NeMo W 2026-06-19 08:40:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 54%|█████▍    | 5718/10519 [1:30:51<1:21:53,  1.02s/it][NeMo W 2026-06-19 08:40:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 54%|█████▍    | 5719/10519 [1:30:53<1:37:13,  1.22s/it][NeMo W 2026-06-19 08:40:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 54%|█████▍    | 5720/10519 [1:30:54<1:32:35,  1.16s/it][NeMo W 2026-06-19 08:40:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 54%|█████▍    | 5721/10519 [1:30:55<1:27:54,  1.10s/it][NeMo W 2026-06-19 08:40:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
 54%|█████▍    | 5722/10519 [1:30:56<1:28:03,  1.10s/it][NeMo W 2026-06-19 08:40:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 54%|█████▍    | 5723/10519 [1:30:57<1:23:45,  1.05s/it][NeMo W 2026-06-19 08:40:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 54%|█████▍    | 5724/10519 [1:30:58<1:20:57,  1.01s/it][NeMo W 2026-06-19 08:40:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 54%|█████▍    | 5725/10519 [1:30:59<1:20:11,  1.00s/it][NeMo W 2026-06-19 08:40:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.49it/s]
 54%|█████▍    | 5726/10519 [1:31:00<1:20:42,  1.01s/it][NeMo W 2026-06-19 08:40:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 54%|█████▍    | 5727/10519 [1:31:01<1:18:47,  1.01it/s][NeMo W 2026-06-19 08:40:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 54%|█████▍    | 5728/10519 [1:31:02<1:17:55,  1.02it/s][NeMo W 2026-06-19 08:40:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.29it/s]
 54%|█████▍    | 5729/10519 [1:31:03<1:22:50,  1.04s/it][NeMo W 2026-06-19 08:40:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:40:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]

Checkpoint saved: 5750 samples

[NeMo W 2026-06-19 08:41:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 55%|█████▍    | 5751/10519 [1:31:25<1:29:38,  1.13s/it][NeMo W 2026-06-19 08:41:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 55%|█████▍    | 5752/10519 [1:31:26<1:25:49,  1.08s/it][NeMo W 2026-06-19 08:41:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 55%|█████▍    | 5753/10519 [1:31:27<1:22:23,  1.04s/it][NeMo W 2026-06-19 08:41:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 55%|█████▍    | 5754/10519 [1:31:28<1:20:33,  1.01s/it][NeMo W 2026-06-19 08:41:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 55%|█████▍    | 5755/10519 [1:31:29<1:19:29,  1.00s/it][NeMo W 2026-06-19 08:41:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 55%|█████▍    | 5756/10519 [1:31:29<1:18:01,  1.02it/s][NeMo W 2026-06-19 08:41:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 55%|█████▍    | 5757/10519 [1:31:30<1:11:25,  1.11it/s][NeMo W 2026-06-19 08:41:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 55%|█████▍    | 5758/10519 [1:31:31<1:17:43,  1.02it/s][NeMo W 2026-06-19 08:41:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.49it/s]
 55%|█████▍    | 5759/10519 [1:31:32<1:17:48,  1.02it/s][NeMo W 2026-06-19 08:41:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 55%|█████▍    | 5760/10519 [1:31:33<1:13:30,  1.08it/s][NeMo W 2026-06-19 08:41:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.96it/s]
 55%|█████▍    | 5761/10519 [1:31:34<1:20:55,  1.02s/it][NeMo W 2026-06-19 08:41:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.49it/s]
 55%|█████▍    | 5762/10519 [1:31:35<1:23:30,  1.05s/it][NeMo W 2026-06-19 08:41:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 55%|█████▍    | 5763/10519 [1:31:36<1:22:03,  1.04s/it][NeMo W 2026-06-19 08:41:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 55%|█████▍    | 5764/10519 [1:31:37<1:16:38,  1.03it/s][NeMo W 2026-06-19 08:41:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 55%|█████▍    | 5765/10519 [1:31:38<1:17:22,  1.02it/s][NeMo W 2026-06-19 08:41:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.37it/s]
 55%|█████▍    | 5766/10519 [1:31:39<1:17:44,  1.02it/s][NeMo W 2026-06-19 08:41:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.60it/s]
 55%|█████▍    | 5767/10519 [1:31:40<1:14:09,  1.07it/s][NeMo W 2026-06-19 08:41:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.43it/s]
 55%|█████▍    | 5768/10519 [1:31:41<1:12:18,  1.10it/s][NeMo W 2026-06-19 08:41:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 55%|█████▍    | 5769/10519 [1:31:42<1:16:07,  1.04it/s][NeMo W 2026-06-19 08:41:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 55%|█████▍    | 5770/10519 [1:31:43<1:14:42,  1.06it/s][NeMo W 2026-06-19 08:41:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 55%|█████▍    | 5771/10519 [1:31:44<1:15:05,  1.05it/s][NeMo W 2026-06-19 08:41:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 55%|█████▍    | 5772/10519 [1:31:45<1:14:28,  1.06it/s][NeMo W 2026-06-19 08:41:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.60it/s]
 55%|█████▍    | 5773/10519 [1:31:46<1:16:45,  1.03it/s][NeMo W 2026-06-19 08:41:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.02it/s]
 55%|█████▍    | 5774/10519 [1:31:47<1:17:58,  1.01it/s][NeMo W 2026-06-19 08:41:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 55%|█████▍    | 5775/10519 [1:31:48<1:18:17,  1.01it/s][NeMo W 2026-06-19 08:41:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 55%|█████▍    | 5776/10519 [1:31:49<1:11:35,  1.10it/s][NeMo W 2026-06-19 08:41:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 55%|█████▍    | 5777/10519 [1:31:50<1:13:46,  1.07it/s][NeMo W 2026-06-19 08:41:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 55%|█████▍    | 5778/10519 [1:31:51<1:20:42,  1.02s/it][NeMo W 2026-06-19 08:41:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 55%|█████▍    | 5779/10519 [1:31:52<1:18:33,  1.01it/s][NeMo W 2026-06-19 08:41:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 5800 samples

[NeMo W 2026-06-19 08:41:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 55%|█████▌    | 5801/10519 [1:32:13<1:33:58,  1.20s/it][NeMo W 2026-06-19 08:41:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 55%|█████▌    | 5802/10519 [1:32:14<1:26:14,  1.10s/it][NeMo W 2026-06-19 08:41:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 55%|█████▌    | 5803/10519 [1:32:15<1:20:25,  1.02s/it][NeMo W 2026-06-19 08:41:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 55%|█████▌    | 5804/10519 [1:32:16<1:20:28,  1.02s/it][NeMo W 2026-06-19 08:41:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 55%|█████▌    | 5805/10519 [1:32:17<1:18:15,  1.00it/s][NeMo W 2026-06-19 08:41:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:41:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 55%|█████▌    | 5806/10519 [1:32:18<1:16:36,  1.03it/s][NeMo W 2026-06-19 08:42:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 55%|█████▌    | 5807/10519 [1:32:19<1:14:33,  1.05it/s][NeMo W 2026-06-19 08:42:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 55%|█████▌    | 5808/10519 [1:32:20<1:11:21,  1.10it/s][NeMo W 2026-06-19 08:42:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 55%|█████▌    | 5809/10519 [1:32:21<1:11:47,  1.09it/s][NeMo W 2026-06-19 08:42:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 55%|█████▌    | 5810/10519 [1:32:21<1:08:20,  1.15it/s][NeMo W 2026-06-19 08:42:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.91it/s]
 55%|█████▌    | 5811/10519 [1:32:22<1:09:04,  1.14it/s][NeMo W 2026-06-19 08:42:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 55%|█████▌    | 5812/10519 [1:32:23<1:12:37,  1.08it/s][NeMo W 2026-06-19 08:42:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 55%|█████▌    | 5813/10519 [1:32:24<1:13:32,  1.07it/s][NeMo W 2026-06-19 08:42:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 55%|█████▌    | 5814/10519 [1:32:28<2:21:39,  1.81s/it][NeMo W 2026-06-19 08:42:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 55%|█████▌    | 5815/10519 [1:32:29<1:55:52,  1.48s/it][NeMo W 2026-06-19 08:42:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 55%|█████▌    | 5816/10519 [1:32:30<1:43:08,  1.32s/it][NeMo W 2026-06-19 08:42:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.66it/s]
 55%|█████▌    | 5817/10519 [1:32:31<1:33:41,  1.20s/it][NeMo W 2026-06-19 08:42:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 55%|█████▌    | 5818/10519 [1:32:31<1:22:36,  1.05s/it][NeMo W 2026-06-19 08:42:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 55%|█████▌    | 5819/10519 [1:32:32<1:20:37,  1.03s/it][NeMo W 2026-06-19 08:42:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 55%|█████▌    | 5820/10519 [1:32:33<1:18:29,  1.00s/it][NeMo W 2026-06-19 08:42:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 55%|█████▌    | 5821/10519 [1:32:34<1:12:14,  1.08it/s][NeMo W 2026-06-19 08:42:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 55%|█████▌    | 5822/10519 [1:32:35<1:13:22,  1.07it/s][NeMo W 2026-06-19 08:42:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
 55%|█████▌    | 5823/10519 [1:32:36<1:12:34,  1.08it/s][NeMo W 2026-06-19 08:42:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 55%|█████▌    | 5824/10519 [1:32:37<1:12:28,  1.08it/s][NeMo W 2026-06-19 08:42:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 55%|█████▌    | 5825/10519 [1:32:38<1:13:29,  1.06it/s][NeMo W 2026-06-19 08:42:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 55%|█████▌    | 5826/10519 [1:32:39<1:13:02,  1.07it/s][NeMo W 2026-06-19 08:42:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 55%|█████▌    | 5827/10519 [1:32:40<1:15:47,  1.03it/s][NeMo W 2026-06-19 08:42:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 55%|█████▌    | 5828/10519 [1:32:41<1:15:20,  1.04it/s][NeMo W 2026-06-19 08:42:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 55%|█████▌    | 5829/10519 [1:32:42<1:14:44,  1.05it/s][NeMo W 2026-06-19 08:42:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]

Checkpoint saved: 5850 samples

[NeMo W 2026-06-19 08:42:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 56%|█████▌    | 5851/10519 [1:33:03<1:27:16,  1.12s/it][NeMo W 2026-06-19 08:42:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 56%|█████▌    | 5852/10519 [1:33:04<1:25:47,  1.10s/it][NeMo W 2026-06-19 08:42:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 56%|█████▌    | 5853/10519 [1:33:05<1:25:00,  1.09s/it][NeMo W 2026-06-19 08:42:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.27it/s]
 56%|█████▌    | 5854/10519 [1:33:06<1:22:35,  1.06s/it][NeMo W 2026-06-19 08:42:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 56%|█████▌    | 5855/10519 [1:33:07<1:15:49,  1.03it/s][NeMo W 2026-06-19 08:42:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 56%|█████▌    | 5856/10519 [1:33:08<1:14:25,  1.04it/s][NeMo W 2026-06-19 08:42:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 56%|█████▌    | 5857/10519 [1:33:09<1:14:16,  1.05it/s][NeMo W 2026-06-19 08:42:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.88it/s]
 56%|█████▌    | 5858/10519 [1:33:10<1:12:37,  1.07it/s][NeMo W 2026-06-19 08:42:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 56%|█████▌    | 5859/10519 [1:33:11<1:12:28,  1.07it/s][NeMo W 2026-06-19 08:42:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 56%|█████▌    | 5860/10519 [1:33:12<1:12:37,  1.07it/s][NeMo W 2026-06-19 08:42:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 56%|█████▌    | 5861/10519 [1:33:12<1:13:19,  1.06it/s][NeMo W 2026-06-19 08:42:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 56%|█████▌    | 5862/10519 [1:33:13<1:14:22,  1.04it/s][NeMo W 2026-06-19 08:42:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 56%|█████▌    | 5863/10519 [1:33:14<1:13:27,  1.06it/s][NeMo W 2026-06-19 08:42:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 56%|█████▌    | 5864/10519 [1:33:15<1:16:42,  1.01it/s][NeMo W 2026-06-19 08:42:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.57it/s]
 56%|█████▌    | 5865/10519 [1:33:16<1:14:23,  1.04it/s][NeMo W 2026-06-19 08:42:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 56%|█████▌    | 5866/10519 [1:33:17<1:14:12,  1.05it/s][NeMo W 2026-06-19 08:42:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:42:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 56%|█████▌    | 5867/10519 [1:33:18<1:13:49,  1.05it/s][NeMo W 2026-06-19 08:43:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 56%|█████▌    | 5868/10519 [1:33:19<1:14:50,  1.04it/s][NeMo W 2026-06-19 08:43:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 56%|█████▌    | 5869/10519 [1:33:20<1:14:16,  1.04it/s][NeMo W 2026-06-19 08:43:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 56%|█████▌    | 5870/10519 [1:33:21<1:14:43,  1.04it/s][NeMo W 2026-06-19 08:43:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 56%|█████▌    | 5871/10519 [1:33:22<1:14:56,  1.03it/s][NeMo W 2026-06-19 08:43:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 56%|█████▌    | 5872/10519 [1:33:23<1:15:18,  1.03it/s][NeMo W 2026-06-19 08:43:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 56%|█████▌    | 5873/10519 [1:33:24<1:14:36,  1.04it/s][NeMo W 2026-06-19 08:43:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 56%|█████▌    | 5874/10519 [1:33:26<1:27:38,  1.13s/it][NeMo W 2026-06-19 08:43:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 56%|█████▌    | 5875/10519 [1:33:26<1:19:32,  1.03s/it][NeMo W 2026-06-19 08:43:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 56%|█████▌    | 5876/10519 [1:33:27<1:14:31,  1.04it/s][NeMo W 2026-06-19 08:43:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 56%|█████▌    | 5877/10519 [1:33:28<1:09:20,  1.12it/s][NeMo W 2026-06-19 08:43:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.18it/s]
 56%|█████▌    | 5878/10519 [1:33:29<1:06:27,  1.16it/s][NeMo W 2026-06-19 08:43:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 56%|█████▌    | 5879/10519 [1:33:30<1:08:27,  1.13it/s][NeMo W 2026-06-19 08:43:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 56%|█████▌    | 5880/10519 [1:33:31<1:08:17,  1.13it/s][NeMo W 2026-06-19 08:43:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 5900 samples

[NeMo W 2026-06-19 08:43:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 56%|█████▌    | 5901/10519 [1:33:52<1:29:32,  1.16s/it][NeMo W 2026-06-19 08:43:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 56%|█████▌    | 5902/10519 [1:33:53<1:23:47,  1.09s/it][NeMo W 2026-06-19 08:43:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 56%|█████▌    | 5903/10519 [1:33:54<1:19:58,  1.04s/it][NeMo W 2026-06-19 08:43:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 56%|█████▌    | 5904/10519 [1:33:55<1:17:32,  1.01s/it][NeMo W 2026-06-19 08:43:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 56%|█████▌    | 5905/10519 [1:33:56<1:16:11,  1.01it/s][NeMo W 2026-06-19 08:43:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 56%|█████▌    | 5906/10519 [1:33:57<1:15:26,  1.02it/s][NeMo W 2026-06-19 08:43:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.73it/s]
 56%|█████▌    | 5907/10519 [1:33:58<1:17:11,  1.00s/it][NeMo W 2026-06-19 08:43:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.84it/s]
 56%|█████▌    | 5908/10519 [1:33:59<1:20:30,  1.05s/it][NeMo W 2026-06-19 08:43:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 56%|█████▌    | 5909/10519 [1:34:00<1:19:17,  1.03s/it][NeMo W 2026-06-19 08:43:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 56%|█████▌    | 5910/10519 [1:34:01<1:17:37,  1.01s/it][NeMo W 2026-06-19 08:43:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 56%|█████▌    | 5911/10519 [1:34:02<1:12:47,  1.06it/s][NeMo W 2026-06-19 08:43:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 56%|█████▌    | 5912/10519 [1:34:03<1:12:46,  1.06it/s][NeMo W 2026-06-19 08:43:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 56%|█████▌    | 5913/10519 [1:34:04<1:14:33,  1.03it/s][NeMo W 2026-06-19 08:43:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 56%|█████▌    | 5914/10519 [1:34:05<1:14:24,  1.03it/s][NeMo W 2026-06-19 08:43:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 56%|█████▌    | 5915/10519 [1:34:06<1:14:44,  1.03it/s][NeMo W 2026-06-19 08:43:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 56%|█████▌    | 5916/10519 [1:34:07<1:15:35,  1.01it/s][NeMo W 2026-06-19 08:43:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 56%|█████▋    | 5917/10519 [1:34:07<1:13:01,  1.05it/s][NeMo W 2026-06-19 08:43:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 56%|█████▋    | 5918/10519 [1:34:08<1:12:31,  1.06it/s][NeMo W 2026-06-19 08:43:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 56%|█████▋    | 5919/10519 [1:34:09<1:13:01,  1.05it/s][NeMo W 2026-06-19 08:43:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 56%|█████▋    | 5920/10519 [1:34:10<1:14:12,  1.03it/s][NeMo W 2026-06-19 08:43:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 56%|█████▋    | 5921/10519 [1:34:11<1:13:23,  1.04it/s][NeMo W 2026-06-19 08:43:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.71it/s]
 56%|█████▋    | 5922/10519 [1:34:12<1:14:47,  1.02it/s][NeMo W 2026-06-19 08:43:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 56%|█████▋    | 5923/10519 [1:34:13<1:14:04,  1.03it/s][NeMo W 2026-06-19 08:43:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 56%|█████▋    | 5924/10519 [1:34:14<1:12:51,  1.05it/s][NeMo W 2026-06-19 08:43:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.04it/s]
 56%|█████▋    | 5925/10519 [1:34:15<1:08:46,  1.11it/s][NeMo W 2026-06-19 08:43:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 56%|█████▋    | 5926/10519 [1:34:16<1:09:13,  1.11it/s][NeMo W 2026-06-19 08:43:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 56%|█████▋    | 5927/10519 [1:34:17<1:11:12,  1.07it/s][NeMo W 2026-06-19 08:43:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:43:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 56%|█████▋    | 5928/10519 [1:34:18<1:12:08,  1.06it/s][NeMo W 2026-06-19 08:44:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 56%|█████▋    | 5929/10519 [1:34:19<1:27:19,  1.14s/it][NeMo W 2026-06-19 08:44:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]

Checkpoint saved: 5950 samples

[NeMo W 2026-06-19 08:44:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 57%|█████▋    | 5951/10519 [1:34:46<1:24:38,  1.11s/it][NeMo W 2026-06-19 08:44:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 57%|█████▋    | 5952/10519 [1:34:46<1:20:39,  1.06s/it][NeMo W 2026-06-19 08:44:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 57%|█████▋    | 5953/10519 [1:34:47<1:19:08,  1.04s/it][NeMo W 2026-06-19 08:44:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 57%|█████▋    | 5954/10519 [1:34:48<1:17:57,  1.02s/it][NeMo W 2026-06-19 08:44:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 57%|█████▋    | 5955/10519 [1:34:49<1:16:14,  1.00s/it][NeMo W 2026-06-19 08:44:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 57%|█████▋    | 5956/10519 [1:34:50<1:14:58,  1.01it/s][NeMo W 2026-06-19 08:44:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 57%|█████▋    | 5957/10519 [1:34:54<2:12:04,  1.74s/it][NeMo W 2026-06-19 08:44:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 57%|█████▋    | 5958/10519 [1:34:54<1:46:56,  1.41s/it][NeMo W 2026-06-19 08:44:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.98it/s]
 57%|█████▋    | 5959/10519 [1:34:55<1:33:45,  1.23s/it][NeMo W 2026-06-19 08:44:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 57%|█████▋    | 5960/10519 [1:34:56<1:27:02,  1.15s/it][NeMo W 2026-06-19 08:44:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 57%|█████▋    | 5961/10519 [1:34:57<1:25:03,  1.12s/it][NeMo W 2026-06-19 08:44:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.37it/s]
 57%|█████▋    | 5962/10519 [1:34:58<1:23:02,  1.09s/it][NeMo W 2026-06-19 08:44:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.94it/s]
 57%|█████▋    | 5963/10519 [1:34:59<1:19:51,  1.05s/it][NeMo W 2026-06-19 08:44:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 57%|█████▋    | 5964/10519 [1:35:00<1:15:51,  1.00it/s][NeMo W 2026-06-19 08:44:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 57%|█████▋    | 5965/10519 [1:35:01<1:13:53,  1.03it/s][NeMo W 2026-06-19 08:44:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 57%|█████▋    | 5966/10519 [1:35:02<1:11:55,  1.06it/s][NeMo W 2026-06-19 08:44:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 57%|█████▋    | 5967/10519 [1:35:03<1:12:47,  1.04it/s][NeMo W 2026-06-19 08:44:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 57%|█████▋    | 5968/10519 [1:35:04<1:12:13,  1.05it/s][NeMo W 2026-06-19 08:44:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.33it/s]
 57%|█████▋    | 5969/10519 [1:35:05<1:17:04,  1.02s/it][NeMo W 2026-06-19 08:44:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.15it/s]
 57%|█████▋    | 5970/10519 [1:35:06<1:16:44,  1.01s/it][NeMo W 2026-06-19 08:44:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 57%|█████▋    | 5971/10519 [1:35:07<1:15:54,  1.00s/it][NeMo W 2026-06-19 08:44:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.10it/s]
 57%|█████▋    | 5972/10519 [1:35:08<1:11:28,  1.06it/s][NeMo W 2026-06-19 08:44:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 57%|█████▋    | 5973/10519 [1:35:09<1:05:56,  1.15it/s][NeMo W 2026-06-19 08:44:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 57%|█████▋    | 5974/10519 [1:35:09<1:02:21,  1.21it/s][NeMo W 2026-06-19 08:44:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 57%|█████▋    | 5975/10519 [1:35:10<1:04:03,  1.18it/s][NeMo W 2026-06-19 08:44:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 57%|█████▋    | 5976/10519 [1:35:11<1:05:08,  1.16it/s][NeMo W 2026-06-19 08:44:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 57%|█████▋    | 5977/10519 [1:35:12<1:06:33,  1.14it/s][NeMo W 2026-06-19 08:44:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.14it/s]
 57%|█████▋    | 5978/10519 [1:35:13<1:11:22,  1.06it/s][NeMo W 2026-06-19 08:44:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 57%|█████▋    | 5979/10519 [1:35:14<1:11:45,  1.05it/s][NeMo W 2026-06-19 08:44:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:44:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]

Checkpoint saved: 6000 samples

[NeMo W 2026-06-19 08:45:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.78it/s]
 57%|█████▋    | 6001/10519 [1:35:44<2:34:24,  2.05s/it][NeMo W 2026-06-19 08:45:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 57%|█████▋    | 6002/10519 [1:35:45<2:07:05,  1.69s/it][NeMo W 2026-06-19 08:45:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 57%|█████▋    | 6003/10519 [1:35:46<1:49:47,  1.46s/it][NeMo W 2026-06-19 08:45:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 57%|█████▋    | 6004/10519 [1:35:47<1:36:22,  1.28s/it][NeMo W 2026-06-19 08:45:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 57%|█████▋    | 6005/10519 [1:35:48<1:30:15,  1.20s/it][NeMo W 2026-06-19 08:45:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 57%|█████▋    | 6006/10519 [1:35:49<1:23:12,  1.11s/it][NeMo W 2026-06-19 08:45:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 57%|█████▋    | 6007/10519 [1:35:50<1:18:01,  1.04s/it][NeMo W 2026-06-19 08:45:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 57%|█████▋    | 6008/10519 [1:35:51<1:17:59,  1.04s/it][NeMo W 2026-06-19 08:45:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 57%|█████▋    | 6009/10519 [1:35:52<1:17:22,  1.03s/it][NeMo W 2026-06-19 08:45:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 57%|█████▋    | 6010/10519 [1:35:53<1:15:53,  1.01s/it][NeMo W 2026-06-19 08:45:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 57%|█████▋    | 6011/10519 [1:35:54<1:13:55,  1.02it/s][NeMo W 2026-06-19 08:45:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 57%|█████▋    | 6012/10519 [1:35:55<1:15:14,  1.00s/it][NeMo W 2026-06-19 08:45:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 57%|█████▋    | 6013/10519 [1:35:56<1:09:52,  1.07it/s][NeMo W 2026-06-19 08:45:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.24it/s]
 57%|█████▋    | 6014/10519 [1:35:56<1:10:14,  1.07it/s][NeMo W 2026-06-19 08:45:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 57%|█████▋    | 6015/10519 [1:35:58<1:14:47,  1.00it/s][NeMo W 2026-06-19 08:45:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 57%|█████▋    | 6016/10519 [1:35:59<1:13:33,  1.02it/s][NeMo W 2026-06-19 08:45:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.31it/s]
 57%|█████▋    | 6017/10519 [1:36:00<1:12:42,  1.03it/s][NeMo W 2026-06-19 08:45:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 57%|█████▋    | 6018/10519 [1:36:01<1:19:30,  1.06s/it][NeMo W 2026-06-19 08:45:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 57%|█████▋    | 6019/10519 [1:36:02<1:15:27,  1.01s/it][NeMo W 2026-06-19 08:45:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 57%|█████▋    | 6020/10519 [1:36:02<1:10:25,  1.06it/s][NeMo W 2026-06-19 08:45:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.48it/s]
 57%|█████▋    | 6021/10519 [1:36:03<1:04:45,  1.16it/s][NeMo W 2026-06-19 08:45:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 57%|█████▋    | 6022/10519 [1:36:04<1:06:03,  1.13it/s][NeMo W 2026-06-19 08:45:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 57%|█████▋    | 6023/10519 [1:36:05<1:07:55,  1.10it/s][NeMo W 2026-06-19 08:45:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 57%|█████▋    | 6024/10519 [1:36:06<1:09:12,  1.08it/s][NeMo W 2026-06-19 08:45:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 57%|█████▋    | 6025/10519 [1:36:07<1:10:00,  1.07it/s][NeMo W 2026-06-19 08:45:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 57%|█████▋    | 6026/10519 [1:36:08<1:10:34,  1.06it/s][NeMo W 2026-06-19 08:45:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 57%|█████▋    | 6027/10519 [1:36:09<1:07:11,  1.11it/s][NeMo W 2026-06-19 08:45:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 57%|█████▋    | 6028/10519 [1:36:10<1:08:31,  1.09it/s][NeMo W 2026-06-19 08:45:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 57%|█████▋    | 6029/10519 [1:36:11<1:09:09,  1.08it/s][NeMo W 2026-06-19 08:45:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:45:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]

Checkpoint saved: 6050 samples

[NeMo W 2026-06-19 08:46:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.62it/s]
 58%|█████▊    | 6051/10519 [1:36:32<1:25:57,  1.15s/it][NeMo W 2026-06-19 08:46:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 58%|█████▊    | 6052/10519 [1:36:33<1:21:10,  1.09s/it][NeMo W 2026-06-19 08:46:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 58%|█████▊    | 6053/10519 [1:36:34<1:17:55,  1.05s/it][NeMo W 2026-06-19 08:46:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 58%|█████▊    | 6054/10519 [1:36:35<1:16:46,  1.03s/it][NeMo W 2026-06-19 08:46:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 58%|█████▊    | 6055/10519 [1:36:36<1:16:16,  1.03s/it][NeMo W 2026-06-19 08:46:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 58%|█████▊    | 6056/10519 [1:36:37<1:13:24,  1.01it/s][NeMo W 2026-06-19 08:46:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 58%|█████▊    | 6057/10519 [1:36:38<1:07:36,  1.10it/s][NeMo W 2026-06-19 08:46:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 58%|█████▊    | 6058/10519 [1:36:39<1:09:22,  1.07it/s][NeMo W 2026-06-19 08:46:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 58%|█████▊    | 6059/10519 [1:36:40<1:10:11,  1.06it/s][NeMo W 2026-06-19 08:46:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 58%|█████▊    | 6060/10519 [1:36:41<1:05:49,  1.13it/s][NeMo W 2026-06-19 08:46:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.06it/s]
 58%|█████▊    | 6061/10519 [1:36:42<1:06:07,  1.12it/s][NeMo W 2026-06-19 08:46:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 58%|█████▊    | 6062/10519 [1:36:43<1:20:08,  1.08s/it][NeMo W 2026-06-19 08:46:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
 58%|█████▊    | 6063/10519 [1:36:44<1:11:47,  1.03it/s][NeMo W 2026-06-19 08:46:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 58%|█████▊    | 6064/10519 [1:36:45<1:10:26,  1.05it/s][NeMo W 2026-06-19 08:46:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 58%|█████▊    | 6065/10519 [1:36:46<1:08:19,  1.09it/s][NeMo W 2026-06-19 08:46:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.58it/s]
 58%|█████▊    | 6066/10519 [1:36:47<1:10:15,  1.06it/s][NeMo W 2026-06-19 08:46:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.65it/s]
 58%|█████▊    | 6067/10519 [1:36:48<1:13:02,  1.02it/s][NeMo W 2026-06-19 08:46:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 58%|█████▊    | 6068/10519 [1:36:49<1:13:24,  1.01it/s][NeMo W 2026-06-19 08:46:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 58%|█████▊    | 6069/10519 [1:36:50<1:19:40,  1.07s/it][NeMo W 2026-06-19 08:46:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 58%|█████▊    | 6070/10519 [1:36:51<1:13:53,  1.00it/s][NeMo W 2026-06-19 08:46:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.21it/s]
 58%|█████▊    | 6071/10519 [1:36:52<1:18:25,  1.06s/it][NeMo W 2026-06-19 08:46:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 58%|█████▊    | 6072/10519 [1:36:53<1:12:24,  1.02it/s][NeMo W 2026-06-19 08:46:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 58%|█████▊    | 6073/10519 [1:36:54<1:12:21,  1.02it/s][NeMo W 2026-06-19 08:46:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.70it/s]
 58%|█████▊    | 6074/10519 [1:36:55<1:10:57,  1.04it/s][NeMo W 2026-06-19 08:46:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 58%|█████▊    | 6075/10519 [1:36:56<1:11:29,  1.04it/s][NeMo W 2026-06-19 08:46:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 58%|█████▊    | 6076/10519 [1:36:57<1:13:24,  1.01it/s][NeMo W 2026-06-19 08:46:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 58%|█████▊    | 6077/10519 [1:36:57<1:10:42,  1.05it/s][NeMo W 2026-06-19 08:46:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.71it/s]
 58%|█████▊    | 6078/10519 [1:36:58<1:10:13,  1.05it/s][NeMo W 2026-06-19 08:46:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 58%|█████▊    | 6079/10519 [1:36:59<1:09:55,  1.06it/s][NeMo W 2026-06-19 08:46:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:46:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]

Checkpoint saved: 6100 samples

[NeMo W 2026-06-19 08:47:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 58%|█████▊    | 6101/10519 [1:37:20<1:24:08,  1.14s/it][NeMo W 2026-06-19 08:47:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 58%|█████▊    | 6102/10519 [1:37:21<1:13:48,  1.00s/it][NeMo W 2026-06-19 08:47:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 58%|█████▊    | 6103/10519 [1:37:22<1:12:55,  1.01it/s][NeMo W 2026-06-19 08:47:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 58%|█████▊    | 6104/10519 [1:37:23<1:15:24,  1.02s/it][NeMo W 2026-06-19 08:47:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 58%|█████▊    | 6105/10519 [1:37:24<1:13:46,  1.00s/it][NeMo W 2026-06-19 08:47:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 58%|█████▊    | 6106/10519 [1:37:25<1:12:41,  1.01it/s][NeMo W 2026-06-19 08:47:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 58%|█████▊    | 6107/10519 [1:37:26<1:12:54,  1.01it/s][NeMo W 2026-06-19 08:47:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 58%|█████▊    | 6108/10519 [1:37:27<1:11:24,  1.03it/s][NeMo W 2026-06-19 08:47:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
 58%|█████▊    | 6109/10519 [1:37:28<1:11:15,  1.03it/s][NeMo W 2026-06-19 08:47:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 58%|█████▊    | 6110/10519 [1:37:29<1:10:46,  1.04it/s][NeMo W 2026-06-19 08:47:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 58%|█████▊    | 6111/10519 [1:37:30<1:13:09,  1.00it/s][NeMo W 2026-06-19 08:47:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 58%|█████▊    | 6112/10519 [1:37:31<1:11:26,  1.03it/s][NeMo W 2026-06-19 08:47:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
 58%|█████▊    | 6113/10519 [1:37:32<1:11:20,  1.03it/s][NeMo W 2026-06-19 08:47:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.60it/s]
 58%|█████▊    | 6114/10519 [1:37:33<1:09:37,  1.05it/s][NeMo W 2026-06-19 08:47:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 58%|█████▊    | 6115/10519 [1:37:34<1:05:28,  1.12it/s][NeMo W 2026-06-19 08:47:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.04it/s]
 58%|█████▊    | 6116/10519 [1:37:34<1:06:23,  1.11it/s][NeMo W 2026-06-19 08:47:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 58%|█████▊    | 6117/10519 [1:37:35<1:07:07,  1.09it/s][NeMo W 2026-06-19 08:47:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 58%|█████▊    | 6118/10519 [1:37:36<1:04:06,  1.14it/s][NeMo W 2026-06-19 08:47:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 58%|█████▊    | 6119/10519 [1:37:37<1:04:45,  1.13it/s][NeMo W 2026-06-19 08:47:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
 58%|█████▊    | 6120/10519 [1:37:38<1:04:52,  1.13it/s][NeMo W 2026-06-19 08:47:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 58%|█████▊    | 6121/10519 [1:37:39<1:02:46,  1.17it/s][NeMo W 2026-06-19 08:47:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.97it/s]
 58%|█████▊    | 6122/10519 [1:37:40<1:03:58,  1.15it/s][NeMo W 2026-06-19 08:47:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 58%|█████▊    | 6123/10519 [1:37:41<1:06:14,  1.11it/s][NeMo W 2026-06-19 08:47:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 58%|█████▊    | 6124/10519 [1:37:42<1:08:17,  1.07it/s][NeMo W 2026-06-19 08:47:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.59it/s]
 58%|█████▊    | 6125/10519 [1:37:43<1:10:22,  1.04it/s][NeMo W 2026-06-19 08:47:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 58%|█████▊    | 6126/10519 [1:37:44<1:10:40,  1.04it/s][NeMo W 2026-06-19 08:47:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 58%|█████▊    | 6127/10519 [1:37:45<1:14:42,  1.02s/it][NeMo W 2026-06-19 08:47:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 58%|█████▊    | 6128/10519 [1:37:46<1:11:58,  1.02it/s][NeMo W 2026-06-19 08:47:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 58%|█████▊    | 6129/10519 [1:37:47<1:09:52,  1.05it/s][NeMo W 2026-06-19 08:47:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]

Checkpoint saved: 6150 samples

[NeMo W 2026-06-19 08:47:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 58%|█████▊    | 6151/10519 [1:38:07<1:17:15,  1.06s/it][NeMo W 2026-06-19 08:47:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 58%|█████▊    | 6152/10519 [1:38:08<1:10:58,  1.03it/s][NeMo W 2026-06-19 08:47:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 58%|█████▊    | 6153/10519 [1:38:09<1:09:36,  1.05it/s][NeMo W 2026-06-19 08:47:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.96it/s]
 59%|█████▊    | 6154/10519 [1:38:10<1:10:21,  1.03it/s][NeMo W 2026-06-19 08:47:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 59%|█████▊    | 6155/10519 [1:38:11<1:09:06,  1.05it/s][NeMo W 2026-06-19 08:47:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 59%|█████▊    | 6156/10519 [1:38:12<1:07:45,  1.07it/s][NeMo W 2026-06-19 08:47:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 59%|█████▊    | 6157/10519 [1:38:13<1:08:47,  1.06it/s][NeMo W 2026-06-19 08:47:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 59%|█████▊    | 6158/10519 [1:38:14<1:10:19,  1.03it/s][NeMo W 2026-06-19 08:47:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 59%|█████▊    | 6159/10519 [1:38:15<1:09:40,  1.04it/s][NeMo W 2026-06-19 08:47:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.48it/s]
 59%|█████▊    | 6160/10519 [1:38:16<1:07:41,  1.07it/s][NeMo W 2026-06-19 08:47:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 59%|█████▊    | 6161/10519 [1:38:17<1:09:25,  1.05it/s][NeMo W 2026-06-19 08:47:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 59%|█████▊    | 6162/10519 [1:38:17<1:08:58,  1.05it/s][NeMo W 2026-06-19 08:47:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:47:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 59%|█████▊    | 6163/10519 [1:38:18<1:09:49,  1.04it/s][NeMo W 2026-06-19 08:48:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 59%|█████▊    | 6164/10519 [1:38:19<1:05:32,  1.11it/s][NeMo W 2026-06-19 08:48:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.19it/s]
 59%|█████▊    | 6165/10519 [1:38:20<1:09:45,  1.04it/s][NeMo W 2026-06-19 08:48:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 59%|█████▊    | 6166/10519 [1:38:21<1:08:20,  1.06it/s][NeMo W 2026-06-19 08:48:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 59%|█████▊    | 6167/10519 [1:38:22<1:04:41,  1.12it/s][NeMo W 2026-06-19 08:48:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 59%|█████▊    | 6168/10519 [1:38:23<1:05:38,  1.10it/s][NeMo W 2026-06-19 08:48:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 59%|█████▊    | 6169/10519 [1:38:24<1:09:18,  1.05it/s][NeMo W 2026-06-19 08:48:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]
 59%|█████▊    | 6170/10519 [1:38:25<1:04:46,  1.12it/s][NeMo W 2026-06-19 08:48:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 59%|█████▊    | 6171/10519 [1:38:26<1:09:48,  1.04it/s][NeMo W 2026-06-19 08:48:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 59%|█████▊    | 6172/10519 [1:38:27<1:04:31,  1.12it/s][NeMo W 2026-06-19 08:48:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 59%|█████▊    | 6173/10519 [1:38:27<1:02:48,  1.15it/s][NeMo W 2026-06-19 08:48:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 59%|█████▊    | 6174/10519 [1:38:28<1:03:56,  1.13it/s][NeMo W 2026-06-19 08:48:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 59%|█████▊    | 6175/10519 [1:38:30<1:10:21,  1.03it/s][NeMo W 2026-06-19 08:48:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.48it/s]
 59%|█████▊    | 6176/10519 [1:38:30<1:08:44,  1.05it/s][NeMo W 2026-06-19 08:48:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 59%|█████▊    | 6177/10519 [1:38:31<1:08:12,  1.06it/s][NeMo W 2026-06-19 08:48:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 59%|█████▊    | 6178/10519 [1:38:32<1:07:56,  1.06it/s][NeMo W 2026-06-19 08:48:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 59%|█████▊    | 6179/10519 [1:38:33<1:03:57,  1.13it/s][NeMo W 2026-06-19 08:48:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]

Checkpoint saved: 6200 samples

[NeMo W 2026-06-19 08:48:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 59%|█████▉    | 6201/10519 [1:38:57<1:22:53,  1.15s/it][NeMo W 2026-06-19 08:48:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 59%|█████▉    | 6202/10519 [1:38:58<1:13:31,  1.02s/it][NeMo W 2026-06-19 08:48:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 59%|█████▉    | 6203/10519 [1:38:59<1:15:34,  1.05s/it][NeMo W 2026-06-19 08:48:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 59%|█████▉    | 6204/10519 [1:39:00<1:13:52,  1.03s/it][NeMo W 2026-06-19 08:48:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 59%|█████▉    | 6205/10519 [1:39:01<1:11:58,  1.00s/it][NeMo W 2026-06-19 08:48:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
 59%|█████▉    | 6206/10519 [1:39:02<1:09:52,  1.03it/s][NeMo W 2026-06-19 08:48:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 59%|█████▉    | 6207/10519 [1:39:03<1:12:35,  1.01s/it][NeMo W 2026-06-19 08:48:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.04it/s]
 59%|█████▉    | 6208/10519 [1:39:04<1:10:25,  1.02it/s][NeMo W 2026-06-19 08:48:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 59%|█████▉    | 6209/10519 [1:39:05<1:10:40,  1.02it/s][NeMo W 2026-06-19 08:48:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 59%|█████▉    | 6210/10519 [1:39:06<1:10:47,  1.01it/s][NeMo W 2026-06-19 08:48:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.77it/s]
 59%|█████▉    | 6211/10519 [1:39:07<1:09:17,  1.04it/s][NeMo W 2026-06-19 08:48:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 59%|█████▉    | 6212/10519 [1:39:07<1:04:58,  1.10it/s][NeMo W 2026-06-19 08:48:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 59%|█████▉    | 6213/10519 [1:39:08<1:05:10,  1.10it/s][NeMo W 2026-06-19 08:48:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 59%|█████▉    | 6214/10519 [1:39:09<1:05:07,  1.10it/s][NeMo W 2026-06-19 08:48:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 59%|█████▉    | 6215/10519 [1:39:10<1:04:39,  1.11it/s][NeMo W 2026-06-19 08:48:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.46it/s]
 59%|█████▉    | 6216/10519 [1:39:11<1:04:42,  1.11it/s][NeMo W 2026-06-19 08:48:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 59%|█████▉    | 6217/10519 [1:39:12<1:05:33,  1.09it/s][NeMo W 2026-06-19 08:48:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 59%|█████▉    | 6218/10519 [1:39:13<1:06:41,  1.07it/s][NeMo W 2026-06-19 08:48:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 59%|█████▉    | 6219/10519 [1:39:14<1:06:27,  1.08it/s][NeMo W 2026-06-19 08:48:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 59%|█████▉    | 6220/10519 [1:39:15<1:03:50,  1.12it/s][NeMo W 2026-06-19 08:48:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
 59%|█████▉    | 6221/10519 [1:39:16<1:07:47,  1.06it/s][NeMo W 2026-06-19 08:48:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 59%|█████▉    | 6222/10519 [1:39:17<1:07:01,  1.07it/s][NeMo W 2026-06-19 08:48:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 59%|█████▉    | 6223/10519 [1:39:18<1:07:19,  1.06it/s][NeMo W 2026-06-19 08:48:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:48:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 59%|█████▉    | 6224/10519 [1:39:19<1:07:08,  1.07it/s][NeMo W 2026-06-19 08:49:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 59%|█████▉    | 6225/10519 [1:39:20<1:08:51,  1.04it/s][NeMo W 2026-06-19 08:49:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 59%|█████▉    | 6226/10519 [1:39:21<1:10:09,  1.02it/s][NeMo W 2026-06-19 08:49:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 59%|█████▉    | 6227/10519 [1:39:22<1:10:21,  1.02it/s][NeMo W 2026-06-19 08:49:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.27it/s]
 59%|█████▉    | 6228/10519 [1:39:23<1:10:17,  1.02it/s][NeMo W 2026-06-19 08:49:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 59%|█████▉    | 6229/10519 [1:39:23<1:08:15,  1.05it/s][NeMo W 2026-06-19 08:49:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]

Checkpoint saved: 6250 samples

[NeMo W 2026-06-19 08:49:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 59%|█████▉    | 6251/10519 [1:39:45<1:23:26,  1.17s/it][NeMo W 2026-06-19 08:49:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.08it/s]
 59%|█████▉    | 6252/10519 [1:39:46<1:19:57,  1.12s/it][NeMo W 2026-06-19 08:49:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 59%|█████▉    | 6253/10519 [1:39:47<1:15:43,  1.07s/it][NeMo W 2026-06-19 08:49:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
 59%|█████▉    | 6254/10519 [1:39:48<1:11:52,  1.01s/it][NeMo W 2026-06-19 08:49:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.80it/s]
 59%|█████▉    | 6255/10519 [1:39:49<1:06:25,  1.07it/s][NeMo W 2026-06-19 08:49:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 59%|█████▉    | 6256/10519 [1:39:50<1:07:05,  1.06it/s][NeMo W 2026-06-19 08:49:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 59%|█████▉    | 6257/10519 [1:39:51<1:05:44,  1.08it/s][NeMo W 2026-06-19 08:49:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 59%|█████▉    | 6258/10519 [1:39:52<1:08:51,  1.03it/s][NeMo W 2026-06-19 08:49:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 60%|█████▉    | 6259/10519 [1:39:53<1:10:32,  1.01it/s][NeMo W 2026-06-19 08:49:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 60%|█████▉    | 6260/10519 [1:39:53<1:06:10,  1.07it/s][NeMo W 2026-06-19 08:49:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.88it/s]
 60%|█████▉    | 6261/10519 [1:39:54<1:04:05,  1.11it/s][NeMo W 2026-06-19 08:49:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 60%|█████▉    | 6262/10519 [1:39:55<1:04:23,  1.10it/s][NeMo W 2026-06-19 08:49:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.01it/s]
 60%|█████▉    | 6263/10519 [1:39:57<1:12:25,  1.02s/it][NeMo W 2026-06-19 08:49:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 60%|█████▉    | 6264/10519 [1:39:57<1:10:32,  1.01it/s][NeMo W 2026-06-19 08:49:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.00it/s]
 60%|█████▉    | 6265/10519 [1:39:58<1:07:48,  1.05it/s][NeMo W 2026-06-19 08:49:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 60%|█████▉    | 6266/10519 [1:39:59<1:09:22,  1.02it/s][NeMo W 2026-06-19 08:49:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 60%|█████▉    | 6267/10519 [1:40:00<1:10:10,  1.01it/s][NeMo W 2026-06-19 08:49:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 60%|█████▉    | 6268/10519 [1:40:01<1:02:32,  1.13it/s][NeMo W 2026-06-19 08:49:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.80it/s]
 60%|█████▉    | 6269/10519 [1:40:02<1:02:52,  1.13it/s][NeMo W 2026-06-19 08:49:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 60%|█████▉    | 6270/10519 [1:40:03<1:03:14,  1.12it/s][NeMo W 2026-06-19 08:49:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.47it/s]
 60%|█████▉    | 6271/10519 [1:40:04<1:05:06,  1.09it/s][NeMo W 2026-06-19 08:49:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 60%|█████▉    | 6272/10519 [1:40:05<1:03:42,  1.11it/s][NeMo W 2026-06-19 08:49:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 60%|█████▉    | 6273/10519 [1:40:06<1:05:10,  1.09it/s][NeMo W 2026-06-19 08:49:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 60%|█████▉    | 6274/10519 [1:40:07<1:05:20,  1.08it/s][NeMo W 2026-06-19 08:49:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
 60%|█████▉    | 6275/10519 [1:40:08<1:07:28,  1.05it/s][NeMo W 2026-06-19 08:49:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 60%|█████▉    | 6276/10519 [1:40:08<1:06:23,  1.07it/s][NeMo W 2026-06-19 08:49:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 60%|█████▉    | 6277/10519 [1:40:10<1:09:54,  1.01it/s][NeMo W 2026-06-19 08:49:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 60%|█████▉    | 6278/10519 [1:40:11<1:08:14,  1.04it/s][NeMo W 2026-06-19 08:49:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]
 60%|█████▉    | 6279/10519 [1:40:11<1:08:52,  1.03it/s][NeMo W 2026-06-19 08:49:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:49:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]

Checkpoint saved: 6300 samples

[NeMo W 2026-06-19 08:50:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 60%|█████▉    | 6301/10519 [1:40:33<1:28:57,  1.27s/it][NeMo W 2026-06-19 08:50:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.65it/s]
 60%|█████▉    | 6302/10519 [1:40:34<1:24:19,  1.20s/it][NeMo W 2026-06-19 08:50:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 60%|█████▉    | 6303/10519 [1:40:35<1:18:34,  1.12s/it][NeMo W 2026-06-19 08:50:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 60%|█████▉    | 6304/10519 [1:40:36<1:21:22,  1.16s/it][NeMo W 2026-06-19 08:50:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 60%|█████▉    | 6305/10519 [1:40:37<1:17:35,  1.10s/it][NeMo W 2026-06-19 08:50:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 60%|█████▉    | 6306/10519 [1:40:38<1:13:39,  1.05s/it][NeMo W 2026-06-19 08:50:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 60%|█████▉    | 6307/10519 [1:40:39<1:10:33,  1.00s/it][NeMo W 2026-06-19 08:50:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 60%|█████▉    | 6308/10519 [1:40:40<1:08:00,  1.03it/s][NeMo W 2026-06-19 08:50:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 60%|█████▉    | 6309/10519 [1:40:41<1:07:01,  1.05it/s][NeMo W 2026-06-19 08:50:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 60%|█████▉    | 6310/10519 [1:40:42<1:06:20,  1.06it/s][NeMo W 2026-06-19 08:50:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 60%|█████▉    | 6311/10519 [1:40:43<1:05:44,  1.07it/s][NeMo W 2026-06-19 08:50:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.07it/s]
 60%|██████    | 6312/10519 [1:40:44<1:06:51,  1.05it/s][NeMo W 2026-06-19 08:50:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 60%|██████    | 6313/10519 [1:40:45<1:06:17,  1.06it/s][NeMo W 2026-06-19 08:50:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 60%|██████    | 6314/10519 [1:40:46<1:05:56,  1.06it/s][NeMo W 2026-06-19 08:50:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 60%|██████    | 6315/10519 [1:40:47<1:06:01,  1.06it/s][NeMo W 2026-06-19 08:50:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.12it/s]
 60%|██████    | 6316/10519 [1:40:48<1:04:13,  1.09it/s][NeMo W 2026-06-19 08:50:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.30it/s]
 60%|██████    | 6317/10519 [1:40:49<1:04:58,  1.08it/s][NeMo W 2026-06-19 08:50:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 60%|██████    | 6318/10519 [1:40:49<1:04:52,  1.08it/s][NeMo W 2026-06-19 08:50:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.29it/s]
 60%|██████    | 6319/10519 [1:40:50<1:05:40,  1.07it/s][NeMo W 2026-06-19 08:50:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 60%|██████    | 6320/10519 [1:40:51<1:04:38,  1.08it/s][NeMo W 2026-06-19 08:50:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 60%|██████    | 6321/10519 [1:40:52<1:00:10,  1.16it/s][NeMo W 2026-06-19 08:50:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 60%|██████    | 6322/10519 [1:40:53<1:02:38,  1.12it/s][NeMo W 2026-06-19 08:50:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.76it/s]
 60%|██████    | 6323/10519 [1:40:55<1:28:04,  1.26s/it][NeMo W 2026-06-19 08:50:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 60%|██████    | 6324/10519 [1:40:56<1:20:25,  1.15s/it][NeMo W 2026-06-19 08:50:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
 60%|██████    | 6325/10519 [1:40:57<1:12:49,  1.04s/it][NeMo W 2026-06-19 08:50:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 60%|██████    | 6326/10519 [1:40:58<1:12:24,  1.04s/it][NeMo W 2026-06-19 08:50:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 60%|██████    | 6327/10519 [1:40:59<1:07:25,  1.04it/s][NeMo W 2026-06-19 08:50:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 60%|██████    | 6328/10519 [1:41:00<1:07:00,  1.04it/s][NeMo W 2026-06-19 08:50:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:50:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.29it/s]
 60%|██████    | 6329/10519 [1:41:00<1:03:57,  1.09it/s][NeMo W 2026-06-19 08:50:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 6350 samples

[NeMo W 2026-06-19 08:51:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 60%|██████    | 6351/10519 [1:41:22<1:14:36,  1.07s/it][NeMo W 2026-06-19 08:51:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 60%|██████    | 6352/10519 [1:41:23<1:10:59,  1.02s/it][NeMo W 2026-06-19 08:51:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 60%|██████    | 6353/10519 [1:41:24<1:15:42,  1.09s/it][NeMo W 2026-06-19 08:51:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 60%|██████    | 6354/10519 [1:41:25<1:13:32,  1.06s/it][NeMo W 2026-06-19 08:51:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.19it/s]
 60%|██████    | 6355/10519 [1:41:26<1:18:51,  1.14s/it][NeMo W 2026-06-19 08:51:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 60%|██████    | 6356/10519 [1:41:27<1:15:19,  1.09s/it][NeMo W 2026-06-19 08:51:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 60%|██████    | 6357/10519 [1:41:28<1:10:49,  1.02s/it][NeMo W 2026-06-19 08:51:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 60%|██████    | 6358/10519 [1:41:29<1:09:29,  1.00s/it][NeMo W 2026-06-19 08:51:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 60%|██████    | 6359/10519 [1:41:30<1:07:45,  1.02it/s][NeMo W 2026-06-19 08:51:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 60%|██████    | 6360/10519 [1:41:31<1:02:28,  1.11it/s][NeMo W 2026-06-19 08:51:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 60%|██████    | 6361/10519 [1:41:32<1:04:51,  1.07it/s][NeMo W 2026-06-19 08:51:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 60%|██████    | 6362/10519 [1:41:33<1:05:10,  1.06it/s][NeMo W 2026-06-19 08:51:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 60%|██████    | 6363/10519 [1:41:33<1:04:57,  1.07it/s][NeMo W 2026-06-19 08:51:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 61%|██████    | 6364/10519 [1:41:34<1:04:40,  1.07it/s][NeMo W 2026-06-19 08:51:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 61%|██████    | 6365/10519 [1:41:35<1:00:16,  1.15it/s][NeMo W 2026-06-19 08:51:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 61%|██████    | 6366/10519 [1:41:36<1:09:12,  1.00it/s][NeMo W 2026-06-19 08:51:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
 61%|██████    | 6367/10519 [1:41:38<1:12:48,  1.05s/it][NeMo W 2026-06-19 08:51:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 61%|██████    | 6368/10519 [1:41:39<1:10:19,  1.02s/it][NeMo W 2026-06-19 08:51:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 61%|██████    | 6369/10519 [1:41:40<1:09:37,  1.01s/it][NeMo W 2026-06-19 08:51:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 61%|██████    | 6370/10519 [1:41:40<1:07:21,  1.03it/s][NeMo W 2026-06-19 08:51:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 61%|██████    | 6371/10519 [1:41:41<1:03:23,  1.09it/s][NeMo W 2026-06-19 08:51:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 61%|██████    | 6372/10519 [1:41:42<1:03:37,  1.09it/s][NeMo W 2026-06-19 08:51:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.57it/s]
 61%|██████    | 6373/10519 [1:41:43<1:02:53,  1.10it/s][NeMo W 2026-06-19 08:51:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 61%|██████    | 6374/10519 [1:41:44<1:06:04,  1.05it/s][NeMo W 2026-06-19 08:51:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 61%|██████    | 6375/10519 [1:41:45<1:05:42,  1.05it/s][NeMo W 2026-06-19 08:51:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.47it/s]
 61%|██████    | 6376/10519 [1:41:46<1:04:45,  1.07it/s][NeMo W 2026-06-19 08:51:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 61%|██████    | 6377/10519 [1:41:47<1:04:05,  1.08it/s][NeMo W 2026-06-19 08:51:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.03it/s]
 61%|██████    | 6378/10519 [1:41:48<1:02:52,  1.10it/s][NeMo W 2026-06-19 08:51:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 61%|██████    | 6379/10519 [1:41:49<1:02:11,  1.11it/s][NeMo W 2026-06-19 08:51:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.91it/s]

Checkpoint saved: 6400 samples

[NeMo W 2026-06-19 08:51:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 61%|██████    | 6401/10519 [1:42:10<1:17:04,  1.12s/it][NeMo W 2026-06-19 08:51:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 61%|██████    | 6402/10519 [1:42:11<1:13:16,  1.07s/it][NeMo W 2026-06-19 08:51:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 61%|██████    | 6403/10519 [1:42:12<1:10:23,  1.03s/it][NeMo W 2026-06-19 08:51:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.06it/s]
 61%|██████    | 6404/10519 [1:42:13<1:08:12,  1.01it/s][NeMo W 2026-06-19 08:51:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 61%|██████    | 6405/10519 [1:42:13<1:03:28,  1.08it/s][NeMo W 2026-06-19 08:51:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.69it/s]
 61%|██████    | 6406/10519 [1:42:14<1:04:12,  1.07it/s][NeMo W 2026-06-19 08:51:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 61%|██████    | 6407/10519 [1:42:15<1:05:38,  1.04it/s][NeMo W 2026-06-19 08:51:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 61%|██████    | 6408/10519 [1:42:16<1:07:18,  1.02it/s][NeMo W 2026-06-19 08:51:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 61%|██████    | 6409/10519 [1:42:17<1:06:02,  1.04it/s][NeMo W 2026-06-19 08:51:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:51:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 61%|██████    | 6410/10519 [1:42:18<1:02:38,  1.09it/s][NeMo W 2026-06-19 08:52:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 61%|██████    | 6411/10519 [1:42:19<1:00:46,  1.13it/s][NeMo W 2026-06-19 08:52:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 61%|██████    | 6412/10519 [1:42:20<1:07:17,  1.02it/s][NeMo W 2026-06-19 08:52:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 61%|██████    | 6413/10519 [1:42:21<1:07:50,  1.01it/s][NeMo W 2026-06-19 08:52:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.56it/s]
 61%|██████    | 6414/10519 [1:42:22<1:06:54,  1.02it/s][NeMo W 2026-06-19 08:52:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 61%|██████    | 6415/10519 [1:42:23<1:06:56,  1.02it/s][NeMo W 2026-06-19 08:52:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 61%|██████    | 6416/10519 [1:42:24<1:02:42,  1.09it/s][NeMo W 2026-06-19 08:52:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 61%|██████    | 6417/10519 [1:42:25<59:50,  1.14it/s]  [NeMo W 2026-06-19 08:52:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 61%|██████    | 6418/10519 [1:42:26<1:01:11,  1.12it/s][NeMo W 2026-06-19 08:52:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 61%|██████    | 6419/10519 [1:42:26<1:01:41,  1.11it/s][NeMo W 2026-06-19 08:52:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 61%|██████    | 6420/10519 [1:42:28<1:05:38,  1.04it/s][NeMo W 2026-06-19 08:52:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
 61%|██████    | 6421/10519 [1:42:28<1:01:55,  1.10it/s][NeMo W 2026-06-19 08:52:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 61%|██████    | 6422/10519 [1:42:29<1:03:35,  1.07it/s][NeMo W 2026-06-19 08:52:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 61%|██████    | 6423/10519 [1:42:30<1:08:06,  1.00it/s][NeMo W 2026-06-19 08:52:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 61%|██████    | 6424/10519 [1:42:31<1:07:11,  1.02it/s][NeMo W 2026-06-19 08:52:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 61%|██████    | 6425/10519 [1:42:32<1:06:30,  1.03it/s][NeMo W 2026-06-19 08:52:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.31it/s]
 61%|██████    | 6426/10519 [1:42:33<1:03:23,  1.08it/s][NeMo W 2026-06-19 08:52:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 61%|██████    | 6427/10519 [1:42:34<1:03:29,  1.07it/s][NeMo W 2026-06-19 08:52:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 61%|██████    | 6428/10519 [1:42:35<1:05:20,  1.04it/s][NeMo W 2026-06-19 08:52:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
 61%|██████    | 6429/10519 [1:42:36<1:04:41,  1.05it/s][NeMo W 2026-06-19 08:52:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.04it/s]

Checkpoint saved: 6450 samples

[NeMo W 2026-06-19 08:52:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 61%|██████▏   | 6451/10519 [1:42:59<1:30:02,  1.33s/it][NeMo W 2026-06-19 08:52:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 61%|██████▏   | 6452/10519 [1:43:00<1:23:34,  1.23s/it][NeMo W 2026-06-19 08:52:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 61%|██████▏   | 6453/10519 [1:43:01<1:19:14,  1.17s/it][NeMo W 2026-06-19 08:52:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 61%|██████▏   | 6454/10519 [1:43:02<1:15:24,  1.11s/it][NeMo W 2026-06-19 08:52:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 61%|██████▏   | 6455/10519 [1:43:03<1:11:45,  1.06s/it][NeMo W 2026-06-19 08:52:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 61%|██████▏   | 6456/10519 [1:43:04<1:06:00,  1.03it/s][NeMo W 2026-06-19 08:52:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.75it/s]
 61%|██████▏   | 6457/10519 [1:43:05<1:06:41,  1.02it/s][NeMo W 2026-06-19 08:52:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 61%|██████▏   | 6458/10519 [1:43:06<1:05:43,  1.03it/s][NeMo W 2026-06-19 08:52:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 61%|██████▏   | 6459/10519 [1:43:06<1:01:11,  1.11it/s][NeMo W 2026-06-19 08:52:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 61%|██████▏   | 6460/10519 [1:43:07<57:35,  1.17it/s]  [NeMo W 2026-06-19 08:52:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 61%|██████▏   | 6461/10519 [1:43:08<58:05,  1.16it/s][NeMo W 2026-06-19 08:52:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 61%|██████▏   | 6462/10519 [1:43:09<59:56,  1.13it/s][NeMo W 2026-06-19 08:52:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.43it/s]
 61%|██████▏   | 6463/10519 [1:43:10<1:00:04,  1.13it/s][NeMo W 2026-06-19 08:52:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 61%|██████▏   | 6464/10519 [1:43:11<59:05,  1.14it/s]  [NeMo W 2026-06-19 08:52:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 61%|██████▏   | 6465/10519 [1:43:12<1:01:31,  1.10it/s][NeMo W 2026-06-19 08:52:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 61%|██████▏   | 6466/10519 [1:43:13<1:03:12,  1.07it/s][NeMo W 2026-06-19 08:52:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 61%|██████▏   | 6467/10519 [1:43:14<1:02:49,  1.08it/s][NeMo W 2026-06-19 08:52:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 61%|██████▏   | 6468/10519 [1:43:15<1:03:23,  1.07it/s][NeMo W 2026-06-19 08:52:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 61%|██████▏   | 6469/10519 [1:43:16<1:06:57,  1.01it/s][NeMo W 2026-06-19 08:52:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.46it/s]
 62%|██████▏   | 6470/10519 [1:43:17<1:06:11,  1.02it/s][NeMo W 2026-06-19 08:52:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 62%|██████▏   | 6471/10519 [1:43:18<1:04:00,  1.05it/s][NeMo W 2026-06-19 08:52:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:52:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 62%|██████▏   | 6472/10519 [1:43:18<1:00:27,  1.12it/s][NeMo W 2026-06-19 08:53:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 62%|██████▏   | 6473/10519 [1:43:19<1:01:35,  1.09it/s][NeMo W 2026-06-19 08:53:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 62%|██████▏   | 6474/10519 [1:43:20<1:03:23,  1.06it/s][NeMo W 2026-06-19 08:53:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 62%|██████▏   | 6475/10519 [1:43:21<1:05:32,  1.03it/s][NeMo W 2026-06-19 08:53:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 62%|██████▏   | 6476/10519 [1:43:22<1:05:26,  1.03it/s][NeMo W 2026-06-19 08:53:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.51it/s]
 62%|██████▏   | 6477/10519 [1:43:23<1:06:07,  1.02it/s][NeMo W 2026-06-19 08:53:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 62%|██████▏   | 6478/10519 [1:43:24<1:05:46,  1.02it/s][NeMo W 2026-06-19 08:53:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.55it/s]
 62%|██████▏   | 6479/10519 [1:43:25<1:06:37,  1.01it/s][NeMo W 2026-06-19 08:53:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.80it/s]

Checkpoint saved: 6500 samples

[NeMo W 2026-06-19 08:53:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
 62%|██████▏   | 6501/10519 [1:43:47<1:15:54,  1.13s/it][NeMo W 2026-06-19 08:53:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 62%|██████▏   | 6502/10519 [1:43:48<1:11:30,  1.07s/it][NeMo W 2026-06-19 08:53:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.26it/s]
 62%|██████▏   | 6503/10519 [1:43:49<1:08:59,  1.03s/it][NeMo W 2026-06-19 08:53:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 62%|██████▏   | 6504/10519 [1:43:50<1:08:06,  1.02s/it][NeMo W 2026-06-19 08:53:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.72it/s]
 62%|██████▏   | 6505/10519 [1:43:51<1:08:20,  1.02s/it][NeMo W 2026-06-19 08:53:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 62%|██████▏   | 6506/10519 [1:43:52<1:02:45,  1.07it/s][NeMo W 2026-06-19 08:53:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 62%|██████▏   | 6507/10519 [1:43:53<1:03:31,  1.05it/s][NeMo W 2026-06-19 08:53:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 62%|██████▏   | 6508/10519 [1:43:54<1:00:18,  1.11it/s][NeMo W 2026-06-19 08:53:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 62%|██████▏   | 6509/10519 [1:43:55<1:01:07,  1.09it/s][NeMo W 2026-06-19 08:53:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 62%|██████▏   | 6510/10519 [1:43:56<1:02:59,  1.06it/s][NeMo W 2026-06-19 08:53:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 62%|██████▏   | 6511/10519 [1:43:57<1:03:07,  1.06it/s][NeMo W 2026-06-19 08:53:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 62%|██████▏   | 6512/10519 [1:43:57<1:00:28,  1.10it/s][NeMo W 2026-06-19 08:53:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 62%|██████▏   | 6513/10519 [1:43:58<1:01:40,  1.08it/s][NeMo W 2026-06-19 08:53:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 62%|██████▏   | 6514/10519 [1:43:59<1:02:40,  1.06it/s][NeMo W 2026-06-19 08:53:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 62%|██████▏   | 6515/10519 [1:44:00<1:02:41,  1.06it/s][NeMo W 2026-06-19 08:53:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 62%|██████▏   | 6516/10519 [1:44:01<1:03:08,  1.06it/s][NeMo W 2026-06-19 08:53:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 62%|██████▏   | 6517/10519 [1:44:02<1:02:45,  1.06it/s][NeMo W 2026-06-19 08:53:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 62%|██████▏   | 6518/10519 [1:44:03<1:02:51,  1.06it/s][NeMo W 2026-06-19 08:53:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 62%|██████▏   | 6519/10519 [1:44:04<1:03:02,  1.06it/s][NeMo W 2026-06-19 08:53:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 62%|██████▏   | 6520/10519 [1:44:05<1:03:32,  1.05it/s][NeMo W 2026-06-19 08:53:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 62%|██████▏   | 6521/10519 [1:44:06<1:04:46,  1.03it/s][NeMo W 2026-06-19 08:53:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 62%|██████▏   | 6522/10519 [1:44:07<1:04:23,  1.03it/s][NeMo W 2026-06-19 08:53:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 62%|██████▏   | 6523/10519 [1:44:08<1:03:49,  1.04it/s][NeMo W 2026-06-19 08:53:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 62%|██████▏   | 6524/10519 [1:44:09<59:47,  1.11it/s]  [NeMo W 2026-06-19 08:53:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 62%|██████▏   | 6525/10519 [1:44:10<1:04:58,  1.02it/s][NeMo W 2026-06-19 08:53:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 62%|██████▏   | 6526/10519 [1:44:11<1:04:24,  1.03it/s][NeMo W 2026-06-19 08:53:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 62%|██████▏   | 6527/10519 [1:44:12<1:04:14,  1.04it/s][NeMo W 2026-06-19 08:53:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 62%|██████▏   | 6528/10519 [1:44:13<1:08:02,  1.02s/it][NeMo W 2026-06-19 08:53:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.04it/s]
 62%|██████▏   | 6529/10519 [1:44:14<1:06:08,  1.01it/s][NeMo W 2026-06-19 08:53:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:53:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]

Checkpoint saved: 6550 samples

[NeMo W 2026-06-19 08:54:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 62%|██████▏   | 6551/10519 [1:44:35<1:17:54,  1.18s/it][NeMo W 2026-06-19 08:54:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 62%|██████▏   | 6552/10519 [1:44:36<1:18:51,  1.19s/it][NeMo W 2026-06-19 08:54:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 62%|██████▏   | 6553/10519 [1:44:37<1:17:59,  1.18s/it][NeMo W 2026-06-19 08:54:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 62%|██████▏   | 6554/10519 [1:44:38<1:14:06,  1.12s/it][NeMo W 2026-06-19 08:54:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 62%|██████▏   | 6555/10519 [1:44:39<1:05:55,  1.00it/s][NeMo W 2026-06-19 08:54:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 62%|██████▏   | 6556/10519 [1:44:40<1:05:13,  1.01it/s][NeMo W 2026-06-19 08:54:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 62%|██████▏   | 6557/10519 [1:44:41<1:06:01,  1.00it/s][NeMo W 2026-06-19 08:54:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 62%|██████▏   | 6558/10519 [1:44:42<1:03:43,  1.04it/s][NeMo W 2026-06-19 08:54:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 62%|██████▏   | 6559/10519 [1:44:43<1:03:17,  1.04it/s][NeMo W 2026-06-19 08:54:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 62%|██████▏   | 6560/10519 [1:44:44<1:01:35,  1.07it/s][NeMo W 2026-06-19 08:54:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 62%|██████▏   | 6561/10519 [1:44:45<1:02:43,  1.05it/s][NeMo W 2026-06-19 08:54:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 62%|██████▏   | 6562/10519 [1:44:46<1:03:09,  1.04it/s][NeMo W 2026-06-19 08:54:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 62%|██████▏   | 6563/10519 [1:44:47<1:02:39,  1.05it/s][NeMo W 2026-06-19 08:54:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 62%|██████▏   | 6564/10519 [1:44:48<1:01:40,  1.07it/s][NeMo W 2026-06-19 08:54:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 62%|██████▏   | 6565/10519 [1:44:49<1:01:06,  1.08it/s][NeMo W 2026-06-19 08:54:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 62%|██████▏   | 6566/10519 [1:44:50<1:01:58,  1.06it/s][NeMo W 2026-06-19 08:54:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 62%|██████▏   | 6567/10519 [1:44:51<1:02:33,  1.05it/s][NeMo W 2026-06-19 08:54:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 62%|██████▏   | 6568/10519 [1:44:52<1:04:10,  1.03it/s][NeMo W 2026-06-19 08:54:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 62%|██████▏   | 6569/10519 [1:44:52<1:03:13,  1.04it/s][NeMo W 2026-06-19 08:54:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 62%|██████▏   | 6570/10519 [1:44:53<1:03:59,  1.03it/s][NeMo W 2026-06-19 08:54:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 62%|██████▏   | 6571/10519 [1:44:54<1:04:11,  1.03it/s][NeMo W 2026-06-19 08:54:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 62%|██████▏   | 6572/10519 [1:44:55<59:23,  1.11it/s]  [NeMo W 2026-06-19 08:54:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 62%|██████▏   | 6573/10519 [1:44:56<1:00:33,  1.09it/s][NeMo W 2026-06-19 08:54:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 62%|██████▏   | 6574/10519 [1:44:57<1:00:25,  1.09it/s][NeMo W 2026-06-19 08:54:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 63%|██████▎   | 6575/10519 [1:44:58<1:00:57,  1.08it/s][NeMo W 2026-06-19 08:54:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 63%|██████▎   | 6576/10519 [1:44:59<1:01:51,  1.06it/s][NeMo W 2026-06-19 08:54:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 63%|██████▎   | 6577/10519 [1:45:00<1:02:49,  1.05it/s][NeMo W 2026-06-19 08:54:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 63%|██████▎   | 6578/10519 [1:45:01<1:01:49,  1.06it/s][NeMo W 2026-06-19 08:54:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 63%|██████▎   | 6579/10519 [1:45:02<1:01:14,  1.07it/s][NeMo W 2026-06-19 08:54:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:54:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]

Checkpoint saved: 6600 samples

[NeMo W 2026-06-19 08:55:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 63%|██████▎   | 6601/10519 [1:45:24<1:26:50,  1.33s/it][NeMo W 2026-06-19 08:55:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 63%|██████▎   | 6602/10519 [1:45:25<1:19:34,  1.22s/it][NeMo W 2026-06-19 08:55:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.36it/s]
 63%|██████▎   | 6603/10519 [1:45:26<1:15:57,  1.16s/it][NeMo W 2026-06-19 08:55:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.51it/s]
 63%|██████▎   | 6604/10519 [1:45:27<1:11:06,  1.09s/it][NeMo W 2026-06-19 08:55:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 63%|██████▎   | 6605/10519 [1:45:28<1:08:04,  1.04s/it][NeMo W 2026-06-19 08:55:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
 63%|██████▎   | 6606/10519 [1:45:29<1:06:16,  1.02s/it][NeMo W 2026-06-19 08:55:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 63%|██████▎   | 6607/10519 [1:45:30<1:04:12,  1.02it/s][NeMo W 2026-06-19 08:55:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 63%|██████▎   | 6608/10519 [1:45:31<58:16,  1.12it/s]  [NeMo W 2026-06-19 08:55:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 63%|██████▎   | 6609/10519 [1:45:32<58:08,  1.12it/s][NeMo W 2026-06-19 08:55:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 63%|██████▎   | 6610/10519 [1:45:33<59:30,  1.09it/s][NeMo W 2026-06-19 08:55:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
 63%|██████▎   | 6611/10519 [1:45:34<1:04:32,  1.01it/s][NeMo W 2026-06-19 08:55:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 63%|██████▎   | 6612/10519 [1:45:35<1:02:37,  1.04it/s][NeMo W 2026-06-19 08:55:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 63%|██████▎   | 6613/10519 [1:45:36<1:02:39,  1.04it/s][NeMo W 2026-06-19 08:55:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 63%|██████▎   | 6614/10519 [1:45:37<59:27,  1.09it/s]  [NeMo W 2026-06-19 08:55:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 63%|██████▎   | 6615/10519 [1:45:38<1:00:59,  1.07it/s][NeMo W 2026-06-19 08:55:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 63%|██████▎   | 6616/10519 [1:45:39<1:01:54,  1.05it/s][NeMo W 2026-06-19 08:55:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 63%|██████▎   | 6617/10519 [1:45:39<1:00:52,  1.07it/s][NeMo W 2026-06-19 08:55:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 63%|██████▎   | 6618/10519 [1:45:40<1:01:17,  1.06it/s][NeMo W 2026-06-19 08:55:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
 63%|██████▎   | 6619/10519 [1:45:41<1:03:13,  1.03it/s][NeMo W 2026-06-19 08:55:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 63%|██████▎   | 6620/10519 [1:45:42<1:02:49,  1.03it/s][NeMo W 2026-06-19 08:55:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.65it/s]
 63%|██████▎   | 6621/10519 [1:45:43<1:02:59,  1.03it/s][NeMo W 2026-06-19 08:55:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.99it/s]
 63%|██████▎   | 6622/10519 [1:45:44<1:04:08,  1.01it/s][NeMo W 2026-06-19 08:55:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 63%|██████▎   | 6623/10519 [1:45:45<1:02:48,  1.03it/s][NeMo W 2026-06-19 08:55:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 63%|██████▎   | 6624/10519 [1:45:46<1:02:00,  1.05it/s][NeMo W 2026-06-19 08:55:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.74it/s]
 63%|██████▎   | 6625/10519 [1:45:47<1:01:38,  1.05it/s][NeMo W 2026-06-19 08:55:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.67it/s]
 63%|██████▎   | 6626/10519 [1:45:48<1:00:20,  1.08it/s][NeMo W 2026-06-19 08:55:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 63%|██████▎   | 6627/10519 [1:45:49<59:41,  1.09it/s]  [NeMo W 2026-06-19 08:55:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.00it/s]
 63%|██████▎   | 6628/10519 [1:45:50<1:01:33,  1.05it/s][NeMo W 2026-06-19 08:55:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 63%|██████▎   | 6629/10519 [1:45:51<1:01:36,  1.05it/s][NeMo W 2026-06-19 08:55:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.35it/s]

Checkpoint saved: 6650 samples

[NeMo W 2026-06-19 08:55:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 63%|██████▎   | 6651/10519 [1:46:13<1:15:19,  1.17s/it][NeMo W 2026-06-19 08:55:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 63%|██████▎   | 6652/10519 [1:46:15<1:25:04,  1.32s/it][NeMo W 2026-06-19 08:55:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]
 63%|██████▎   | 6653/10519 [1:46:16<1:18:46,  1.22s/it][NeMo W 2026-06-19 08:55:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.57it/s]
 63%|██████▎   | 6654/10519 [1:46:17<1:11:41,  1.11s/it][NeMo W 2026-06-19 08:55:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 63%|██████▎   | 6655/10519 [1:46:18<1:09:05,  1.07s/it][NeMo W 2026-06-19 08:55:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:55:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 63%|██████▎   | 6656/10519 [1:46:19<1:07:09,  1.04s/it][NeMo W 2026-06-19 08:56:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 63%|██████▎   | 6657/10519 [1:46:19<1:02:36,  1.03it/s][NeMo W 2026-06-19 08:56:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 63%|██████▎   | 6658/10519 [1:46:20<1:01:48,  1.04it/s][NeMo W 2026-06-19 08:56:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 63%|██████▎   | 6659/10519 [1:46:21<1:01:28,  1.05it/s][NeMo W 2026-06-19 08:56:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 63%|██████▎   | 6660/10519 [1:46:22<1:01:36,  1.04it/s][NeMo W 2026-06-19 08:56:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.91it/s]
 63%|██████▎   | 6661/10519 [1:46:23<1:01:47,  1.04it/s][NeMo W 2026-06-19 08:56:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 63%|██████▎   | 6662/10519 [1:46:24<1:04:35,  1.00s/it][NeMo W 2026-06-19 08:56:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 63%|██████▎   | 6663/10519 [1:46:25<1:02:56,  1.02it/s][NeMo W 2026-06-19 08:56:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 63%|██████▎   | 6664/10519 [1:46:26<57:16,  1.12it/s]  [NeMo W 2026-06-19 08:56:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 63%|██████▎   | 6665/10519 [1:46:27<57:38,  1.11it/s][NeMo W 2026-06-19 08:56:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 63%|██████▎   | 6666/10519 [1:46:28<59:11,  1.08it/s][NeMo W 2026-06-19 08:56:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 63%|██████▎   | 6667/10519 [1:46:29<58:27,  1.10it/s][NeMo W 2026-06-19 08:56:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.59it/s]
 63%|██████▎   | 6668/10519 [1:46:30<1:05:52,  1.03s/it][NeMo W 2026-06-19 08:56:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 63%|██████▎   | 6669/10519 [1:46:31<1:05:37,  1.02s/it][NeMo W 2026-06-19 08:56:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 63%|██████▎   | 6670/10519 [1:46:32<1:04:50,  1.01s/it][NeMo W 2026-06-19 08:56:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 63%|██████▎   | 6671/10519 [1:46:33<1:04:01,  1.00it/s][NeMo W 2026-06-19 08:56:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 63%|██████▎   | 6672/10519 [1:46:34<1:03:28,  1.01it/s][NeMo W 2026-06-19 08:56:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 63%|██████▎   | 6673/10519 [1:46:35<1:02:39,  1.02it/s][NeMo W 2026-06-19 08:56:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 63%|██████▎   | 6674/10519 [1:46:36<1:01:37,  1.04it/s][NeMo W 2026-06-19 08:56:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 63%|██████▎   | 6675/10519 [1:46:37<1:05:34,  1.02s/it][NeMo W 2026-06-19 08:56:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 63%|██████▎   | 6676/10519 [1:46:38<1:04:20,  1.00s/it][NeMo W 2026-06-19 08:56:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 63%|██████▎   | 6677/10519 [1:46:39<1:02:32,  1.02it/s][NeMo W 2026-06-19 08:56:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 63%|██████▎   | 6678/10519 [1:46:40<1:06:15,  1.04s/it][NeMo W 2026-06-19 08:56:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 63%|██████▎   | 6679/10519 [1:46:41<1:04:59,  1.02s/it][NeMo W 2026-06-19 08:56:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.12it/s]

Checkpoint saved: 6700 samples

[NeMo W 2026-06-19 08:56:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.04it/s]
 64%|██████▎   | 6701/10519 [1:47:03<1:11:57,  1.13s/it][NeMo W 2026-06-19 08:56:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.98it/s]
 64%|██████▎   | 6702/10519 [1:47:04<1:08:27,  1.08s/it][NeMo W 2026-06-19 08:56:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.62it/s]
 64%|██████▎   | 6703/10519 [1:47:05<1:05:25,  1.03s/it][NeMo W 2026-06-19 08:56:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 64%|██████▎   | 6704/10519 [1:47:06<1:03:34,  1.00it/s][NeMo W 2026-06-19 08:56:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.04it/s]
 64%|██████▎   | 6705/10519 [1:47:07<1:04:03,  1.01s/it][NeMo W 2026-06-19 08:56:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 64%|██████▍   | 6706/10519 [1:47:08<1:04:13,  1.01s/it][NeMo W 2026-06-19 08:56:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 64%|██████▍   | 6707/10519 [1:47:09<1:03:30,  1.00it/s][NeMo W 2026-06-19 08:56:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 64%|██████▍   | 6708/10519 [1:47:10<58:53,  1.08it/s]  [NeMo W 2026-06-19 08:56:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 64%|██████▍   | 6709/10519 [1:47:11<1:00:21,  1.05it/s][NeMo W 2026-06-19 08:56:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.10it/s]
 64%|██████▍   | 6710/10519 [1:47:12<1:03:02,  1.01it/s][NeMo W 2026-06-19 08:56:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 64%|██████▍   | 6711/10519 [1:47:13<1:07:17,  1.06s/it][NeMo W 2026-06-19 08:56:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 64%|██████▍   | 6712/10519 [1:47:14<1:03:55,  1.01s/it][NeMo W 2026-06-19 08:56:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.83it/s]
 64%|██████▍   | 6713/10519 [1:47:15<1:06:08,  1.04s/it][NeMo W 2026-06-19 08:56:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 64%|██████▍   | 6714/10519 [1:47:16<1:04:55,  1.02s/it][NeMo W 2026-06-19 08:56:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 64%|██████▍   | 6715/10519 [1:47:17<1:02:45,  1.01it/s][NeMo W 2026-06-19 08:56:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:56:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 64%|██████▍   | 6716/10519 [1:47:18<1:01:31,  1.03it/s][NeMo W 2026-06-19 08:57:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 64%|██████▍   | 6717/10519 [1:47:19<1:00:50,  1.04it/s][NeMo W 2026-06-19 08:57:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 64%|██████▍   | 6718/10519 [1:47:20<1:08:07,  1.08s/it][NeMo W 2026-06-19 08:57:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 64%|██████▍   | 6719/10519 [1:47:21<1:07:30,  1.07s/it][NeMo W 2026-06-19 08:57:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 64%|██████▍   | 6720/10519 [1:47:22<1:08:15,  1.08s/it][NeMo W 2026-06-19 08:57:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 64%|██████▍   | 6721/10519 [1:47:23<1:05:05,  1.03s/it][NeMo W 2026-06-19 08:57:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.04it/s]
 64%|██████▍   | 6722/10519 [1:47:24<1:04:31,  1.02s/it][NeMo W 2026-06-19 08:57:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 64%|██████▍   | 6723/10519 [1:47:25<1:03:05,  1.00it/s][NeMo W 2026-06-19 08:57:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 64%|██████▍   | 6724/10519 [1:47:26<1:01:54,  1.02it/s][NeMo W 2026-06-19 08:57:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 64%|██████▍   | 6725/10519 [1:47:27<1:01:24,  1.03it/s][NeMo W 2026-06-19 08:57:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 64%|██████▍   | 6726/10519 [1:47:29<1:12:13,  1.14s/it][NeMo W 2026-06-19 08:57:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 64%|██████▍   | 6727/10519 [1:47:29<1:05:22,  1.03s/it][NeMo W 2026-06-19 08:57:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.88it/s]
 64%|██████▍   | 6728/10519 [1:47:30<1:03:36,  1.01s/it][NeMo W 2026-06-19 08:57:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 64%|██████▍   | 6729/10519 [1:47:31<1:01:19,  1.03it/s][NeMo W 2026-06-19 08:57:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 6750 samples

[NeMo W 2026-06-19 08:57:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 64%|██████▍   | 6751/10519 [1:47:54<1:18:34,  1.25s/it][NeMo W 2026-06-19 08:57:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 64%|██████▍   | 6752/10519 [1:47:55<1:10:26,  1.12s/it][NeMo W 2026-06-19 08:57:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.91it/s]
 64%|██████▍   | 6753/10519 [1:47:56<1:08:09,  1.09s/it][NeMo W 2026-06-19 08:57:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 64%|██████▍   | 6754/10519 [1:47:57<1:05:33,  1.04s/it][NeMo W 2026-06-19 08:57:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 64%|██████▍   | 6755/10519 [1:47:58<1:03:34,  1.01s/it][NeMo W 2026-06-19 08:57:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 64%|██████▍   | 6756/10519 [1:47:59<1:00:57,  1.03it/s][NeMo W 2026-06-19 08:57:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 64%|██████▍   | 6757/10519 [1:48:00<59:48,  1.05it/s]  [NeMo W 2026-06-19 08:57:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 64%|██████▍   | 6758/10519 [1:48:01<58:11,  1.08it/s][NeMo W 2026-06-19 08:57:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 64%|██████▍   | 6759/10519 [1:48:01<56:51,  1.10it/s][NeMo W 2026-06-19 08:57:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 64%|██████▍   | 6760/10519 [1:48:02<57:32,  1.09it/s][NeMo W 2026-06-19 08:57:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]
 64%|██████▍   | 6761/10519 [1:48:03<58:42,  1.07it/s][NeMo W 2026-06-19 08:57:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 64%|██████▍   | 6762/10519 [1:48:05<1:02:43,  1.00s/it][NeMo W 2026-06-19 08:57:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.62it/s]
 64%|██████▍   | 6763/10519 [1:48:06<1:02:28,  1.00it/s][NeMo W 2026-06-19 08:57:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.27it/s]
 64%|██████▍   | 6764/10519 [1:48:06<57:20,  1.09it/s]  [NeMo W 2026-06-19 08:57:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 64%|██████▍   | 6765/10519 [1:48:07<57:54,  1.08it/s][NeMo W 2026-06-19 08:57:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 64%|██████▍   | 6766/10519 [1:48:08<58:44,  1.06it/s][NeMo W 2026-06-19 08:57:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.96it/s]
 64%|██████▍   | 6767/10519 [1:48:09<54:53,  1.14it/s][NeMo W 2026-06-19 08:57:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.89it/s]
 64%|██████▍   | 6768/10519 [1:48:10<52:59,  1.18it/s][NeMo W 2026-06-19 08:57:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 64%|██████▍   | 6769/10519 [1:48:11<1:04:16,  1.03s/it][NeMo W 2026-06-19 08:57:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 64%|██████▍   | 6770/10519 [1:48:12<1:02:35,  1.00s/it][NeMo W 2026-06-19 08:57:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 64%|██████▍   | 6771/10519 [1:48:13<1:02:03,  1.01it/s][NeMo W 2026-06-19 08:57:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 64%|██████▍   | 6772/10519 [1:48:14<58:45,  1.06it/s]  [NeMo W 2026-06-19 08:57:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 64%|██████▍   | 6773/10519 [1:48:15<55:38,  1.12it/s][NeMo W 2026-06-19 08:57:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.02it/s]
 64%|██████▍   | 6774/10519 [1:48:16<55:59,  1.11it/s][NeMo W 2026-06-19 08:57:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 64%|██████▍   | 6775/10519 [1:48:17<57:45,  1.08it/s][NeMo W 2026-06-19 08:57:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 64%|██████▍   | 6776/10519 [1:48:17<57:57,  1.08it/s][NeMo W 2026-06-19 08:57:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:57:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 64%|██████▍   | 6777/10519 [1:48:18<57:07,  1.09it/s][NeMo W 2026-06-19 08:58:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.09it/s]
 64%|██████▍   | 6778/10519 [1:48:19<57:06,  1.09it/s][NeMo W 2026-06-19 08:58:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.06it/s]
 64%|██████▍   | 6779/10519 [1:48:20<57:04,  1.09it/s][NeMo W 2026-06-19 08:58:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]

Checkpoint saved: 6800 samples

[NeMo W 2026-06-19 08:58:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 65%|██████▍   | 6801/10519 [1:48:41<1:07:38,  1.09s/it][NeMo W 2026-06-19 08:58:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 65%|██████▍   | 6802/10519 [1:48:42<1:08:22,  1.10s/it][NeMo W 2026-06-19 08:58:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 65%|██████▍   | 6803/10519 [1:48:43<1:01:36,  1.01it/s][NeMo W 2026-06-19 08:58:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 65%|██████▍   | 6804/10519 [1:48:43<1:00:26,  1.02it/s][NeMo W 2026-06-19 08:58:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.11it/s]
 65%|██████▍   | 6805/10519 [1:48:44<59:57,  1.03it/s]  [NeMo W 2026-06-19 08:58:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 65%|██████▍   | 6806/10519 [1:48:45<59:44,  1.04it/s][NeMo W 2026-06-19 08:58:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 65%|██████▍   | 6807/10519 [1:48:46<57:38,  1.07it/s][NeMo W 2026-06-19 08:58:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 65%|██████▍   | 6808/10519 [1:48:47<53:04,  1.17it/s][NeMo W 2026-06-19 08:58:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.94it/s]
 65%|██████▍   | 6809/10519 [1:48:48<50:23,  1.23it/s][NeMo W 2026-06-19 08:58:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 65%|██████▍   | 6810/10519 [1:48:49<52:36,  1.18it/s][NeMo W 2026-06-19 08:58:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.84it/s]
 65%|██████▍   | 6811/10519 [1:48:50<55:55,  1.11it/s][NeMo W 2026-06-19 08:58:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 65%|██████▍   | 6812/10519 [1:48:50<53:05,  1.16it/s][NeMo W 2026-06-19 08:58:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 65%|██████▍   | 6813/10519 [1:48:51<50:35,  1.22it/s][NeMo W 2026-06-19 08:58:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 65%|██████▍   | 6814/10519 [1:48:52<1:00:10,  1.03it/s][NeMo W 2026-06-19 08:58:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 65%|██████▍   | 6815/10519 [1:48:53<1:00:00,  1.03it/s][NeMo W 2026-06-19 08:58:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.29it/s]
 65%|██████▍   | 6816/10519 [1:48:54<59:24,  1.04it/s]  [NeMo W 2026-06-19 08:58:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 65%|██████▍   | 6817/10519 [1:48:55<58:14,  1.06it/s][NeMo W 2026-06-19 08:58:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.17it/s]
 65%|██████▍   | 6818/10519 [1:48:56<59:05,  1.04it/s][NeMo W 2026-06-19 08:58:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 65%|██████▍   | 6819/10519 [1:48:57<55:43,  1.11it/s][NeMo W 2026-06-19 08:58:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.58it/s]
 65%|██████▍   | 6820/10519 [1:48:58<57:13,  1.08it/s][NeMo W 2026-06-19 08:58:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 65%|██████▍   | 6821/10519 [1:48:59<57:34,  1.07it/s][NeMo W 2026-06-19 08:58:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 65%|██████▍   | 6822/10519 [1:49:00<57:38,  1.07it/s][NeMo W 2026-06-19 08:58:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 65%|██████▍   | 6823/10519 [1:49:01<57:13,  1.08it/s][NeMo W 2026-06-19 08:58:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 65%|██████▍   | 6824/10519 [1:49:01<53:27,  1.15it/s][NeMo W 2026-06-19 08:58:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.54it/s]
 65%|██████▍   | 6825/10519 [1:49:02<54:06,  1.14it/s][NeMo W 2026-06-19 08:58:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 65%|██████▍   | 6826/10519 [1:49:03<58:00,  1.06it/s][NeMo W 2026-06-19 08:58:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.53it/s]
 65%|██████▍   | 6827/10519 [1:49:04<53:34,  1.15it/s][NeMo W 2026-06-19 08:58:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 65%|██████▍   | 6828/10519 [1:49:05<52:14,  1.18it/s][NeMo W 2026-06-19 08:58:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 65%|██████▍   | 6829/10519 [1:49:06<53:34,  1.15it/s][NeMo W 2026-06-19 08:58:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:58:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]

Checkpoint saved: 6850 samples

[NeMo W 2026-06-19 08:59:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 65%|██████▌   | 6851/10519 [1:49:28<1:10:16,  1.15s/it][NeMo W 2026-06-19 08:59:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 65%|██████▌   | 6852/10519 [1:49:29<1:08:06,  1.11s/it][NeMo W 2026-06-19 08:59:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 65%|██████▌   | 6853/10519 [1:49:30<1:03:49,  1.04s/it][NeMo W 2026-06-19 08:59:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.12it/s]
 65%|██████▌   | 6854/10519 [1:49:31<1:01:49,  1.01s/it][NeMo W 2026-06-19 08:59:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 65%|██████▌   | 6855/10519 [1:49:32<57:23,  1.06it/s]  [NeMo W 2026-06-19 08:59:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 65%|██████▌   | 6856/10519 [1:49:33<57:03,  1.07it/s][NeMo W 2026-06-19 08:59:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 65%|██████▌   | 6857/10519 [1:49:34<57:04,  1.07it/s][NeMo W 2026-06-19 08:59:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 65%|██████▌   | 6858/10519 [1:49:35<57:01,  1.07it/s][NeMo W 2026-06-19 08:59:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 65%|██████▌   | 6859/10519 [1:49:36<56:30,  1.08it/s][NeMo W 2026-06-19 08:59:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 65%|██████▌   | 6860/10519 [1:49:36<57:43,  1.06it/s][NeMo W 2026-06-19 08:59:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 65%|██████▌   | 6861/10519 [1:49:37<56:44,  1.07it/s][NeMo W 2026-06-19 08:59:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 65%|██████▌   | 6862/10519 [1:49:38<53:58,  1.13it/s][NeMo W 2026-06-19 08:59:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 65%|██████▌   | 6863/10519 [1:49:39<50:18,  1.21it/s][NeMo W 2026-06-19 08:59:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 65%|██████▌   | 6864/10519 [1:49:40<50:59,  1.19it/s][NeMo W 2026-06-19 08:59:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 65%|██████▌   | 6865/10519 [1:49:41<51:29,  1.18it/s][NeMo W 2026-06-19 08:59:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 65%|██████▌   | 6866/10519 [1:49:41<52:15,  1.16it/s][NeMo W 2026-06-19 08:59:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 65%|██████▌   | 6867/10519 [1:49:42<54:05,  1.13it/s][NeMo W 2026-06-19 08:59:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 65%|██████▌   | 6868/10519 [1:49:43<55:02,  1.11it/s][NeMo W 2026-06-19 08:59:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 65%|██████▌   | 6869/10519 [1:49:44<54:33,  1.12it/s][NeMo W 2026-06-19 08:59:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 65%|██████▌   | 6870/10519 [1:49:45<56:32,  1.08it/s][NeMo W 2026-06-19 08:59:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 65%|██████▌   | 6871/10519 [1:49:46<1:00:51,  1.00s/it][NeMo W 2026-06-19 08:59:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 65%|██████▌   | 6872/10519 [1:49:47<56:10,  1.08it/s]  [NeMo W 2026-06-19 08:59:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 65%|██████▌   | 6873/10519 [1:49:48<53:13,  1.14it/s][NeMo W 2026-06-19 08:59:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 65%|██████▌   | 6874/10519 [1:49:49<54:41,  1.11it/s][NeMo W 2026-06-19 08:59:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.35it/s]
 65%|██████▌   | 6875/10519 [1:49:50<55:05,  1.10it/s][NeMo W 2026-06-19 08:59:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 65%|██████▌   | 6876/10519 [1:49:51<56:14,  1.08it/s][NeMo W 2026-06-19 08:59:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 65%|██████▌   | 6877/10519 [1:49:52<56:41,  1.07it/s][NeMo W 2026-06-19 08:59:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 65%|██████▌   | 6878/10519 [1:49:53<54:09,  1.12it/s][NeMo W 2026-06-19 08:59:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 65%|██████▌   | 6879/10519 [1:49:53<54:59,  1.10it/s][NeMo W 2026-06-19 08:59:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]

Checkpoint saved: 6900 samples

[NeMo W 2026-06-19 08:59:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.00it/s]
 66%|██████▌   | 6901/10519 [1:50:15<1:12:27,  1.20s/it][NeMo W 2026-06-19 08:59:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 66%|██████▌   | 6902/10519 [1:50:16<1:07:45,  1.12s/it][NeMo W 2026-06-19 08:59:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 66%|██████▌   | 6903/10519 [1:50:17<1:05:26,  1.09s/it][NeMo W 2026-06-19 08:59:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 66%|██████▌   | 6904/10519 [1:50:18<1:02:51,  1.04s/it][NeMo W 2026-06-19 08:59:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 08:59:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 66%|██████▌   | 6905/10519 [1:50:19<1:01:32,  1.02s/it][NeMo W 2026-06-19 09:00:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.64it/s]
 66%|██████▌   | 6906/10519 [1:50:20<59:41,  1.01it/s]  [NeMo W 2026-06-19 09:00:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 66%|██████▌   | 6907/10519 [1:50:21<58:40,  1.03it/s][NeMo W 2026-06-19 09:00:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
 66%|██████▌   | 6908/10519 [1:50:22<58:59,  1.02it/s][NeMo W 2026-06-19 09:00:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 66%|██████▌   | 6909/10519 [1:50:22<57:37,  1.04it/s][NeMo W 2026-06-19 09:00:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 66%|██████▌   | 6910/10519 [1:50:23<56:00,  1.07it/s][NeMo W 2026-06-19 09:00:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 66%|██████▌   | 6911/10519 [1:50:24<52:12,  1.15it/s][NeMo W 2026-06-19 09:00:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 66%|██████▌   | 6912/10519 [1:50:25<53:42,  1.12it/s][NeMo W 2026-06-19 09:00:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.43it/s]
 66%|██████▌   | 6913/10519 [1:50:26<57:08,  1.05it/s][NeMo W 2026-06-19 09:00:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 66%|██████▌   | 6914/10519 [1:50:27<57:28,  1.05it/s][NeMo W 2026-06-19 09:00:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 66%|██████▌   | 6915/10519 [1:50:28<57:18,  1.05it/s][NeMo W 2026-06-19 09:00:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 66%|██████▌   | 6916/10519 [1:50:29<57:00,  1.05it/s][NeMo W 2026-06-19 09:00:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.25it/s]
 66%|██████▌   | 6917/10519 [1:50:30<57:42,  1.04it/s][NeMo W 2026-06-19 09:00:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.82it/s]
 66%|██████▌   | 6918/10519 [1:50:31<58:59,  1.02it/s][NeMo W 2026-06-19 09:00:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 66%|██████▌   | 6919/10519 [1:50:32<58:02,  1.03it/s][NeMo W 2026-06-19 09:00:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 66%|██████▌   | 6920/10519 [1:50:33<57:42,  1.04it/s][NeMo W 2026-06-19 09:00:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 66%|██████▌   | 6921/10519 [1:50:34<57:29,  1.04it/s][NeMo W 2026-06-19 09:00:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.18it/s]
 66%|██████▌   | 6922/10519 [1:50:35<1:01:33,  1.03s/it][NeMo W 2026-06-19 09:00:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 66%|██████▌   | 6923/10519 [1:50:36<56:44,  1.06it/s]  [NeMo W 2026-06-19 09:00:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 66%|██████▌   | 6924/10519 [1:50:37<56:47,  1.06it/s][NeMo W 2026-06-19 09:00:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.57it/s]
 66%|██████▌   | 6925/10519 [1:50:38<59:42,  1.00it/s][NeMo W 2026-06-19 09:00:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 66%|██████▌   | 6926/10519 [1:50:39<59:31,  1.01it/s][NeMo W 2026-06-19 09:00:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 66%|██████▌   | 6927/10519 [1:50:40<58:09,  1.03it/s][NeMo W 2026-06-19 09:00:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 66%|██████▌   | 6928/10519 [1:50:41<57:19,  1.04it/s][NeMo W 2026-06-19 09:00:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 66%|██████▌   | 6929/10519 [1:50:42<56:30,  1.06it/s][NeMo W 2026-06-19 09:00:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]

Checkpoint saved: 6950 samples

[NeMo W 2026-06-19 09:00:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 66%|██████▌   | 6951/10519 [1:51:04<1:13:46,  1.24s/it][NeMo W 2026-06-19 09:00:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 66%|██████▌   | 6952/10519 [1:51:05<1:08:23,  1.15s/it][NeMo W 2026-06-19 09:00:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.25it/s]
 66%|██████▌   | 6953/10519 [1:51:06<1:05:00,  1.09s/it][NeMo W 2026-06-19 09:00:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 66%|██████▌   | 6954/10519 [1:51:07<59:54,  1.01s/it]  [NeMo W 2026-06-19 09:00:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.11it/s]
 66%|██████▌   | 6955/10519 [1:51:08<58:12,  1.02it/s][NeMo W 2026-06-19 09:00:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 66%|██████▌   | 6956/10519 [1:51:09<57:34,  1.03it/s][NeMo W 2026-06-19 09:00:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 66%|██████▌   | 6957/10519 [1:51:09<53:38,  1.11it/s][NeMo W 2026-06-19 09:00:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 66%|██████▌   | 6958/10519 [1:51:10<51:59,  1.14it/s][NeMo W 2026-06-19 09:00:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
 66%|██████▌   | 6959/10519 [1:51:11<54:02,  1.10it/s][NeMo W 2026-06-19 09:00:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 66%|██████▌   | 6960/10519 [1:51:12<55:39,  1.07it/s][NeMo W 2026-06-19 09:00:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.12it/s]
 66%|██████▌   | 6961/10519 [1:51:13<56:11,  1.06it/s][NeMo W 2026-06-19 09:00:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 66%|██████▌   | 6962/10519 [1:51:14<56:23,  1.05it/s][NeMo W 2026-06-19 09:00:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 66%|██████▌   | 6963/10519 [1:51:15<56:53,  1.04it/s][NeMo W 2026-06-19 09:00:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 66%|██████▌   | 6964/10519 [1:51:16<54:35,  1.09it/s][NeMo W 2026-06-19 09:00:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 66%|██████▌   | 6965/10519 [1:51:17<51:25,  1.15it/s][NeMo W 2026-06-19 09:00:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:00:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.22it/s]
 66%|██████▌   | 6966/10519 [1:51:18<57:24,  1.03it/s][NeMo W 2026-06-19 09:01:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 66%|██████▌   | 6967/10519 [1:51:19<57:25,  1.03it/s][NeMo W 2026-06-19 09:01:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 66%|██████▌   | 6968/10519 [1:51:20<57:05,  1.04it/s][NeMo W 2026-06-19 09:01:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 66%|██████▋   | 6969/10519 [1:51:21<56:58,  1.04it/s][NeMo W 2026-06-19 09:01:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.00it/s]
 66%|██████▋   | 6970/10519 [1:51:22<1:00:09,  1.02s/it][NeMo W 2026-06-19 09:01:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 66%|██████▋   | 6971/10519 [1:51:23<59:03,  1.00it/s]  [NeMo W 2026-06-19 09:01:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 66%|██████▋   | 6972/10519 [1:51:24<58:12,  1.02it/s][NeMo W 2026-06-19 09:01:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.86it/s]
 66%|██████▋   | 6973/10519 [1:51:25<58:22,  1.01it/s][NeMo W 2026-06-19 09:01:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 66%|██████▋   | 6974/10519 [1:51:26<57:40,  1.02it/s][NeMo W 2026-06-19 09:01:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.99it/s]
 66%|██████▋   | 6975/10519 [1:51:27<58:48,  1.00it/s][NeMo W 2026-06-19 09:01:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 66%|██████▋   | 6976/10519 [1:51:28<57:44,  1.02it/s][NeMo W 2026-06-19 09:01:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 66%|██████▋   | 6977/10519 [1:51:29<57:38,  1.02it/s][NeMo W 2026-06-19 09:01:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 66%|██████▋   | 6978/10519 [1:51:30<57:36,  1.02it/s][NeMo W 2026-06-19 09:01:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.04it/s]
 66%|██████▋   | 6979/10519 [1:51:31<57:28,  1.03it/s][NeMo W 2026-06-19 09:01:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.71it/s]

Checkpoint saved: 7000 samples

[NeMo W 2026-06-19 09:01:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 67%|██████▋   | 7001/10519 [1:51:53<1:18:51,  1.34s/it][NeMo W 2026-06-19 09:01:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.35it/s]
 67%|██████▋   | 7002/10519 [1:51:54<1:09:46,  1.19s/it][NeMo W 2026-06-19 09:01:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 67%|██████▋   | 7003/10519 [1:51:55<1:05:29,  1.12s/it][NeMo W 2026-06-19 09:01:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 67%|██████▋   | 7004/10519 [1:51:56<1:02:17,  1.06s/it][NeMo W 2026-06-19 09:01:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 67%|██████▋   | 7005/10519 [1:51:57<57:51,  1.01it/s]  [NeMo W 2026-06-19 09:01:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 67%|██████▋   | 7006/10519 [1:51:57<54:31,  1.07it/s][NeMo W 2026-06-19 09:01:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 67%|██████▋   | 7007/10519 [1:51:58<56:48,  1.03it/s][NeMo W 2026-06-19 09:01:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 67%|██████▋   | 7008/10519 [1:51:59<56:42,  1.03it/s][NeMo W 2026-06-19 09:01:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.11it/s]
 67%|██████▋   | 7009/10519 [1:52:00<56:23,  1.04it/s][NeMo W 2026-06-19 09:01:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 67%|██████▋   | 7010/10519 [1:52:01<52:53,  1.11it/s][NeMo W 2026-06-19 09:01:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 67%|██████▋   | 7011/10519 [1:52:02<57:34,  1.02it/s][NeMo W 2026-06-19 09:01:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 67%|██████▋   | 7012/10519 [1:52:03<56:35,  1.03it/s][NeMo W 2026-06-19 09:01:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.91it/s]
 67%|██████▋   | 7013/10519 [1:52:04<56:51,  1.03it/s][NeMo W 2026-06-19 09:01:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 67%|██████▋   | 7014/10519 [1:52:05<56:40,  1.03it/s][NeMo W 2026-06-19 09:01:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 67%|██████▋   | 7015/10519 [1:52:06<59:22,  1.02s/it][NeMo W 2026-06-19 09:01:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.49it/s]
 67%|██████▋   | 7016/10519 [1:52:07<58:24,  1.00s/it][NeMo W 2026-06-19 09:01:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 67%|██████▋   | 7017/10519 [1:52:08<53:53,  1.08it/s][NeMo W 2026-06-19 09:01:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 67%|██████▋   | 7018/10519 [1:52:09<52:52,  1.10it/s][NeMo W 2026-06-19 09:01:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 67%|██████▋   | 7019/10519 [1:52:10<49:13,  1.18it/s][NeMo W 2026-06-19 09:01:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 67%|██████▋   | 7020/10519 [1:52:10<49:43,  1.17it/s][NeMo W 2026-06-19 09:01:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 67%|██████▋   | 7021/10519 [1:52:11<51:18,  1.14it/s][NeMo W 2026-06-19 09:01:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 67%|██████▋   | 7022/10519 [1:52:12<48:39,  1.20it/s][NeMo W 2026-06-19 09:01:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.01it/s]
 67%|██████▋   | 7023/10519 [1:52:13<52:26,  1.11it/s][NeMo W 2026-06-19 09:01:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.28it/s]
 67%|██████▋   | 7024/10519 [1:52:14<52:35,  1.11it/s][NeMo W 2026-06-19 09:01:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 67%|██████▋   | 7025/10519 [1:52:15<53:45,  1.08it/s][NeMo W 2026-06-19 09:01:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 67%|██████▋   | 7026/10519 [1:52:16<54:27,  1.07it/s][NeMo W 2026-06-19 09:01:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 67%|██████▋   | 7027/10519 [1:52:17<56:43,  1.03it/s][NeMo W 2026-06-19 09:01:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:01:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.67it/s]
 67%|██████▋   | 7028/10519 [1:52:18<57:33,  1.01it/s][NeMo W 2026-06-19 09:02:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 67%|██████▋   | 7029/10519 [1:52:19<56:26,  1.03it/s][NeMo W 2026-06-19 09:02:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]

Checkpoint saved: 7050 samples

[NeMo W 2026-06-19 09:02:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 67%|██████▋   | 7051/10519 [1:52:41<1:14:24,  1.29s/it][NeMo W 2026-06-19 09:02:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 67%|██████▋   | 7052/10519 [1:52:42<1:08:01,  1.18s/it][NeMo W 2026-06-19 09:02:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.68it/s]
 67%|██████▋   | 7053/10519 [1:52:43<1:06:38,  1.15s/it][NeMo W 2026-06-19 09:02:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 67%|██████▋   | 7054/10519 [1:52:44<1:08:12,  1.18s/it][NeMo W 2026-06-19 09:02:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 67%|██████▋   | 7055/10519 [1:52:45<1:04:30,  1.12s/it][NeMo W 2026-06-19 09:02:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 67%|██████▋   | 7056/10519 [1:52:46<1:01:49,  1.07s/it][NeMo W 2026-06-19 09:02:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 67%|██████▋   | 7057/10519 [1:52:47<1:00:26,  1.05s/it][NeMo W 2026-06-19 09:02:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 67%|██████▋   | 7058/10519 [1:52:48<58:43,  1.02s/it]  [NeMo W 2026-06-19 09:02:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 67%|██████▋   | 7059/10519 [1:52:49<57:00,  1.01it/s][NeMo W 2026-06-19 09:02:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 67%|██████▋   | 7060/10519 [1:52:50<52:49,  1.09it/s][NeMo W 2026-06-19 09:02:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 67%|██████▋   | 7061/10519 [1:52:51<53:13,  1.08it/s][NeMo W 2026-06-19 09:02:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.09it/s]
 67%|██████▋   | 7062/10519 [1:52:52<56:16,  1.02it/s][NeMo W 2026-06-19 09:02:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 67%|██████▋   | 7063/10519 [1:52:53<55:28,  1.04it/s][NeMo W 2026-06-19 09:02:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 67%|██████▋   | 7064/10519 [1:52:54<56:07,  1.03it/s][NeMo W 2026-06-19 09:02:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.44it/s]
 67%|██████▋   | 7065/10519 [1:52:55<56:51,  1.01it/s][NeMo W 2026-06-19 09:02:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 67%|██████▋   | 7066/10519 [1:52:56<55:53,  1.03it/s][NeMo W 2026-06-19 09:02:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 67%|██████▋   | 7067/10519 [1:52:57<54:48,  1.05it/s][NeMo W 2026-06-19 09:02:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 67%|██████▋   | 7068/10519 [1:52:58<54:35,  1.05it/s][NeMo W 2026-06-19 09:02:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 67%|██████▋   | 7069/10519 [1:52:59<54:12,  1.06it/s][NeMo W 2026-06-19 09:02:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 67%|██████▋   | 7070/10519 [1:52:59<54:15,  1.06it/s][NeMo W 2026-06-19 09:02:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 67%|██████▋   | 7071/10519 [1:53:01<55:18,  1.04it/s][NeMo W 2026-06-19 09:02:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 67%|██████▋   | 7072/10519 [1:53:01<55:04,  1.04it/s][NeMo W 2026-06-19 09:02:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 67%|██████▋   | 7073/10519 [1:53:02<51:21,  1.12it/s][NeMo W 2026-06-19 09:02:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 67%|██████▋   | 7074/10519 [1:53:03<52:07,  1.10it/s][NeMo W 2026-06-19 09:02:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.74it/s]
 67%|██████▋   | 7075/10519 [1:53:04<48:43,  1.18it/s][NeMo W 2026-06-19 09:02:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 67%|██████▋   | 7076/10519 [1:53:05<48:35,  1.18it/s][NeMo W 2026-06-19 09:02:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 67%|██████▋   | 7077/10519 [1:53:06<49:31,  1.16it/s][NeMo W 2026-06-19 09:02:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
 67%|██████▋   | 7078/10519 [1:53:06<50:15,  1.14it/s][NeMo W 2026-06-19 09:02:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 67%|██████▋   | 7079/10519 [1:53:07<51:29,  1.11it/s][NeMo W 2026-06-19 09:02:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:02:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]

Checkpoint saved: 7100 samples

[NeMo W 2026-06-19 09:03:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.66it/s]
 68%|██████▊   | 7101/10519 [1:53:30<1:11:59,  1.26s/it][NeMo W 2026-06-19 09:03:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 68%|██████▊   | 7102/10519 [1:53:31<1:07:15,  1.18s/it][NeMo W 2026-06-19 09:03:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 68%|██████▊   | 7103/10519 [1:53:31<1:03:09,  1.11s/it][NeMo W 2026-06-19 09:03:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 68%|██████▊   | 7104/10519 [1:53:32<57:58,  1.02s/it]  [NeMo W 2026-06-19 09:03:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 68%|██████▊   | 7105/10519 [1:53:33<59:09,  1.04s/it][NeMo W 2026-06-19 09:03:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 68%|██████▊   | 7106/10519 [1:53:34<57:58,  1.02s/it][NeMo W 2026-06-19 09:03:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 68%|██████▊   | 7107/10519 [1:53:35<56:28,  1.01it/s][NeMo W 2026-06-19 09:03:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 68%|██████▊   | 7108/10519 [1:53:36<54:42,  1.04it/s][NeMo W 2026-06-19 09:03:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 68%|██████▊   | 7109/10519 [1:53:37<54:52,  1.04it/s][NeMo W 2026-06-19 09:03:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 68%|██████▊   | 7110/10519 [1:53:38<54:17,  1.05it/s][NeMo W 2026-06-19 09:03:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 68%|██████▊   | 7111/10519 [1:53:39<53:28,  1.06it/s][NeMo W 2026-06-19 09:03:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 68%|██████▊   | 7112/10519 [1:53:40<54:38,  1.04it/s][NeMo W 2026-06-19 09:03:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 68%|██████▊   | 7113/10519 [1:53:41<54:33,  1.04it/s][NeMo W 2026-06-19 09:03:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 68%|██████▊   | 7114/10519 [1:53:42<53:46,  1.06it/s][NeMo W 2026-06-19 09:03:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 68%|██████▊   | 7115/10519 [1:53:43<53:05,  1.07it/s][NeMo W 2026-06-19 09:03:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 68%|██████▊   | 7116/10519 [1:53:44<55:59,  1.01it/s][NeMo W 2026-06-19 09:03:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 68%|██████▊   | 7117/10519 [1:53:45<54:32,  1.04it/s][NeMo W 2026-06-19 09:03:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.35it/s]
 68%|██████▊   | 7118/10519 [1:53:46<55:06,  1.03it/s][NeMo W 2026-06-19 09:03:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 68%|██████▊   | 7119/10519 [1:53:47<54:47,  1.03it/s][NeMo W 2026-06-19 09:03:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 68%|██████▊   | 7120/10519 [1:53:48<54:24,  1.04it/s][NeMo W 2026-06-19 09:03:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.69it/s]
 68%|██████▊   | 7121/10519 [1:53:49<54:14,  1.04it/s][NeMo W 2026-06-19 09:03:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 68%|██████▊   | 7122/10519 [1:53:50<53:40,  1.05it/s][NeMo W 2026-06-19 09:03:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 68%|██████▊   | 7123/10519 [1:53:50<53:50,  1.05it/s][NeMo W 2026-06-19 09:03:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 68%|██████▊   | 7124/10519 [1:53:51<52:19,  1.08it/s][NeMo W 2026-06-19 09:03:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 68%|██████▊   | 7125/10519 [1:53:52<52:48,  1.07it/s][NeMo W 2026-06-19 09:03:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 68%|██████▊   | 7126/10519 [1:53:53<50:30,  1.12it/s][NeMo W 2026-06-19 09:03:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 68%|██████▊   | 7127/10519 [1:53:54<48:36,  1.16it/s][NeMo W 2026-06-19 09:03:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.79it/s]
 68%|██████▊   | 7128/10519 [1:53:55<51:12,  1.10it/s][NeMo W 2026-06-19 09:03:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.64it/s]
 68%|██████▊   | 7129/10519 [1:53:56<53:04,  1.06it/s][NeMo W 2026-06-19 09:03:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]

Checkpoint saved: 7150 samples

[NeMo W 2026-06-19 09:03:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 68%|██████▊   | 7151/10519 [1:54:18<1:06:06,  1.18s/it][NeMo W 2026-06-19 09:03:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:03:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 68%|██████▊   | 7152/10519 [1:54:19<59:33,  1.06s/it]  [NeMo W 2026-06-19 09:04:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 68%|██████▊   | 7153/10519 [1:54:20<57:39,  1.03s/it][NeMo W 2026-06-19 09:04:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 68%|██████▊   | 7154/10519 [1:54:21<56:42,  1.01s/it][NeMo W 2026-06-19 09:04:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.52it/s]
 68%|██████▊   | 7155/10519 [1:54:22<58:31,  1.04s/it][NeMo W 2026-06-19 09:04:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.52it/s]
 68%|██████▊   | 7156/10519 [1:54:23<58:30,  1.04s/it][NeMo W 2026-06-19 09:04:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.44it/s]
 68%|██████▊   | 7157/10519 [1:54:24<58:24,  1.04s/it][NeMo W 2026-06-19 09:04:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 68%|██████▊   | 7158/10519 [1:54:25<57:05,  1.02s/it][NeMo W 2026-06-19 09:04:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 68%|██████▊   | 7159/10519 [1:54:26<52:26,  1.07it/s][NeMo W 2026-06-19 09:04:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.96it/s]
 68%|██████▊   | 7160/10519 [1:54:26<48:55,  1.14it/s][NeMo W 2026-06-19 09:04:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 68%|██████▊   | 7161/10519 [1:54:27<49:54,  1.12it/s][NeMo W 2026-06-19 09:04:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 68%|██████▊   | 7162/10519 [1:54:28<51:57,  1.08it/s][NeMo W 2026-06-19 09:04:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 68%|██████▊   | 7163/10519 [1:54:29<52:24,  1.07it/s][NeMo W 2026-06-19 09:04:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 68%|██████▊   | 7164/10519 [1:54:30<52:51,  1.06it/s][NeMo W 2026-06-19 09:04:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 68%|██████▊   | 7165/10519 [1:54:31<51:46,  1.08it/s][NeMo W 2026-06-19 09:04:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 68%|██████▊   | 7166/10519 [1:54:32<55:49,  1.00it/s][NeMo W 2026-06-19 09:04:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.48it/s]
 68%|██████▊   | 7167/10519 [1:54:33<56:48,  1.02s/it][NeMo W 2026-06-19 09:04:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.82it/s]
 68%|██████▊   | 7168/10519 [1:54:34<55:51,  1.00s/it][NeMo W 2026-06-19 09:04:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 68%|██████▊   | 7169/10519 [1:54:35<55:24,  1.01it/s][NeMo W 2026-06-19 09:04:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.77it/s]
 68%|██████▊   | 7170/10519 [1:54:36<54:59,  1.01it/s][NeMo W 2026-06-19 09:04:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 68%|██████▊   | 7171/10519 [1:54:37<53:36,  1.04it/s][NeMo W 2026-06-19 09:04:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 68%|██████▊   | 7172/10519 [1:54:38<52:11,  1.07it/s][NeMo W 2026-06-19 09:04:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 68%|██████▊   | 7173/10519 [1:54:39<51:42,  1.08it/s][NeMo W 2026-06-19 09:04:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 68%|██████▊   | 7174/10519 [1:54:40<51:16,  1.09it/s][NeMo W 2026-06-19 09:04:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 68%|██████▊   | 7175/10519 [1:54:41<51:03,  1.09it/s][NeMo W 2026-06-19 09:04:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 68%|██████▊   | 7176/10519 [1:54:42<51:20,  1.09it/s][NeMo W 2026-06-19 09:04:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 68%|██████▊   | 7177/10519 [1:54:43<52:06,  1.07it/s][NeMo W 2026-06-19 09:04:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 68%|██████▊   | 7178/10519 [1:54:43<51:40,  1.08it/s][NeMo W 2026-06-19 09:04:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 68%|██████▊   | 7179/10519 [1:54:44<52:13,  1.07it/s][NeMo W 2026-06-19 09:04:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]

Checkpoint saved: 7200 samples

[NeMo W 2026-06-19 09:04:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 68%|██████▊   | 7201/10519 [1:55:06<1:08:21,  1.24s/it][NeMo W 2026-06-19 09:04:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.31it/s]
 68%|██████▊   | 7202/10519 [1:55:07<1:03:41,  1.15s/it][NeMo W 2026-06-19 09:04:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 68%|██████▊   | 7203/10519 [1:55:08<59:54,  1.08s/it]  [NeMo W 2026-06-19 09:04:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 68%|██████▊   | 7204/10519 [1:55:09<58:19,  1.06s/it][NeMo W 2026-06-19 09:04:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.19it/s]
 68%|██████▊   | 7205/10519 [1:55:10<56:27,  1.02s/it][NeMo W 2026-06-19 09:04:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 69%|██████▊   | 7206/10519 [1:55:11<53:55,  1.02it/s][NeMo W 2026-06-19 09:04:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 69%|██████▊   | 7207/10519 [1:55:12<54:38,  1.01it/s][NeMo W 2026-06-19 09:04:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 69%|██████▊   | 7208/10519 [1:55:13<54:34,  1.01it/s][NeMo W 2026-06-19 09:04:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.63it/s]
 69%|██████▊   | 7209/10519 [1:55:14<54:27,  1.01it/s][NeMo W 2026-06-19 09:04:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 69%|██████▊   | 7210/10519 [1:55:15<54:56,  1.00it/s][NeMo W 2026-06-19 09:04:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 69%|██████▊   | 7211/10519 [1:55:16<55:09,  1.00s/it][NeMo W 2026-06-19 09:04:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 69%|██████▊   | 7212/10519 [1:55:17<56:01,  1.02s/it][NeMo W 2026-06-19 09:04:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
 69%|██████▊   | 7213/10519 [1:55:18<54:59,  1.00it/s][NeMo W 2026-06-19 09:04:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:04:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 69%|██████▊   | 7214/10519 [1:55:19<54:38,  1.01it/s][NeMo W 2026-06-19 09:05:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.28it/s]
 69%|██████▊   | 7215/10519 [1:55:20<54:48,  1.00it/s][NeMo W 2026-06-19 09:05:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 69%|██████▊   | 7216/10519 [1:55:21<54:26,  1.01it/s][NeMo W 2026-06-19 09:05:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 69%|██████▊   | 7217/10519 [1:55:21<51:01,  1.08it/s][NeMo W 2026-06-19 09:05:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.26it/s]
 69%|██████▊   | 7218/10519 [1:55:22<51:25,  1.07it/s][NeMo W 2026-06-19 09:05:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 69%|██████▊   | 7219/10519 [1:55:23<52:51,  1.04it/s][NeMo W 2026-06-19 09:05:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.48it/s]
 69%|██████▊   | 7220/10519 [1:55:24<52:59,  1.04it/s][NeMo W 2026-06-19 09:05:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 69%|██████▊   | 7221/10519 [1:55:25<48:39,  1.13it/s][NeMo W 2026-06-19 09:05:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 69%|██████▊   | 7222/10519 [1:55:26<49:06,  1.12it/s][NeMo W 2026-06-19 09:05:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 69%|██████▊   | 7223/10519 [1:55:27<47:04,  1.17it/s][NeMo W 2026-06-19 09:05:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 69%|██████▊   | 7224/10519 [1:55:28<48:24,  1.13it/s][NeMo W 2026-06-19 09:05:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.60it/s]
 69%|██████▊   | 7225/10519 [1:55:29<49:44,  1.10it/s][NeMo W 2026-06-19 09:05:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.61it/s]
 69%|██████▊   | 7226/10519 [1:55:29<48:26,  1.13it/s][NeMo W 2026-06-19 09:05:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.09it/s]
 69%|██████▊   | 7227/10519 [1:55:30<46:32,  1.18it/s][NeMo W 2026-06-19 09:05:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 69%|██████▊   | 7228/10519 [1:55:31<47:29,  1.15it/s][NeMo W 2026-06-19 09:05:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 69%|██████▊   | 7229/10519 [1:55:32<48:39,  1.13it/s][NeMo W 2026-06-19 09:05:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]

Checkpoint saved: 7250 samples

[NeMo W 2026-06-19 09:05:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.36it/s]
 69%|██████▉   | 7251/10519 [1:55:54<1:07:30,  1.24s/it][NeMo W 2026-06-19 09:05:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 69%|██████▉   | 7252/10519 [1:55:55<1:03:14,  1.16s/it][NeMo W 2026-06-19 09:05:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 69%|██████▉   | 7253/10519 [1:55:56<1:00:40,  1.11s/it][NeMo W 2026-06-19 09:05:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 69%|██████▉   | 7254/10519 [1:55:57<58:07,  1.07s/it]  [NeMo W 2026-06-19 09:05:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 69%|██████▉   | 7255/10519 [1:55:58<55:05,  1.01s/it][NeMo W 2026-06-19 09:05:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 69%|██████▉   | 7256/10519 [1:55:59<53:20,  1.02it/s][NeMo W 2026-06-19 09:05:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 69%|██████▉   | 7257/10519 [1:56:02<1:32:34,  1.70s/it][NeMo W 2026-06-19 09:05:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.04it/s]
 69%|██████▉   | 7258/10519 [1:56:03<1:19:48,  1.47s/it][NeMo W 2026-06-19 09:05:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 69%|██████▉   | 7259/10519 [1:56:04<1:13:00,  1.34s/it][NeMo W 2026-06-19 09:05:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 69%|██████▉   | 7260/10519 [1:56:05<1:08:18,  1.26s/it][NeMo W 2026-06-19 09:05:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 69%|██████▉   | 7261/10519 [1:56:06<1:04:18,  1.18s/it][NeMo W 2026-06-19 09:05:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 69%|██████▉   | 7262/10519 [1:56:07<56:32,  1.04s/it]  [NeMo W 2026-06-19 09:05:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 69%|██████▉   | 7263/10519 [1:56:08<57:50,  1.07s/it][NeMo W 2026-06-19 09:05:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.88it/s]
 69%|██████▉   | 7264/10519 [1:56:09<55:23,  1.02s/it][NeMo W 2026-06-19 09:05:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 69%|██████▉   | 7265/10519 [1:56:10<51:34,  1.05it/s][NeMo W 2026-06-19 09:05:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 69%|██████▉   | 7266/10519 [1:56:11<48:07,  1.13it/s][NeMo W 2026-06-19 09:05:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 69%|██████▉   | 7267/10519 [1:56:12<48:11,  1.12it/s][NeMo W 2026-06-19 09:05:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 69%|██████▉   | 7268/10519 [1:56:13<50:19,  1.08it/s][NeMo W 2026-06-19 09:05:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 69%|██████▉   | 7269/10519 [1:56:14<50:33,  1.07it/s][NeMo W 2026-06-19 09:05:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 69%|██████▉   | 7270/10519 [1:56:14<49:45,  1.09it/s][NeMo W 2026-06-19 09:05:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 69%|██████▉   | 7271/10519 [1:56:15<49:49,  1.09it/s][NeMo W 2026-06-19 09:05:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 69%|██████▉   | 7272/10519 [1:56:16<46:58,  1.15it/s][NeMo W 2026-06-19 09:05:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 69%|██████▉   | 7273/10519 [1:56:17<48:54,  1.11it/s][NeMo W 2026-06-19 09:05:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:05:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
 69%|██████▉   | 7274/10519 [1:56:18<48:52,  1.11it/s][NeMo W 2026-06-19 09:06:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.27it/s]
 69%|██████▉   | 7275/10519 [1:56:19<50:20,  1.07it/s][NeMo W 2026-06-19 09:06:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
 69%|██████▉   | 7276/10519 [1:56:20<50:35,  1.07it/s][NeMo W 2026-06-19 09:06:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.46it/s]
 69%|██████▉   | 7277/10519 [1:56:21<49:33,  1.09it/s][NeMo W 2026-06-19 09:06:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 69%|██████▉   | 7278/10519 [1:56:22<47:43,  1.13it/s][NeMo W 2026-06-19 09:06:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 69%|██████▉   | 7279/10519 [1:56:23<50:45,  1.06it/s][NeMo W 2026-06-19 09:06:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]

Checkpoint saved: 7300 samples

[NeMo W 2026-06-19 09:06:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 69%|██████▉   | 7301/10519 [1:56:44<58:58,  1.10s/it]  [NeMo W 2026-06-19 09:06:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.54it/s]
 69%|██████▉   | 7302/10519 [1:56:45<56:58,  1.06s/it][NeMo W 2026-06-19 09:06:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 69%|██████▉   | 7303/10519 [1:56:45<51:29,  1.04it/s][NeMo W 2026-06-19 09:06:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 69%|██████▉   | 7304/10519 [1:56:46<50:43,  1.06it/s][NeMo W 2026-06-19 09:06:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 69%|██████▉   | 7305/10519 [1:56:47<47:14,  1.13it/s][NeMo W 2026-06-19 09:06:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
 69%|██████▉   | 7306/10519 [1:56:48<45:25,  1.18it/s][NeMo W 2026-06-19 09:06:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 69%|██████▉   | 7307/10519 [1:56:49<47:11,  1.13it/s][NeMo W 2026-06-19 09:06:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 69%|██████▉   | 7308/10519 [1:56:50<49:21,  1.08it/s][NeMo W 2026-06-19 09:06:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.52it/s]
 69%|██████▉   | 7309/10519 [1:56:51<49:36,  1.08it/s][NeMo W 2026-06-19 09:06:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 69%|██████▉   | 7310/10519 [1:56:52<49:26,  1.08it/s][NeMo W 2026-06-19 09:06:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 70%|██████▉   | 7311/10519 [1:56:52<49:09,  1.09it/s][NeMo W 2026-06-19 09:06:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.02it/s]
 70%|██████▉   | 7312/10519 [1:56:54<51:27,  1.04it/s][NeMo W 2026-06-19 09:06:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 70%|██████▉   | 7313/10519 [1:56:54<49:54,  1.07it/s][NeMo W 2026-06-19 09:06:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 70%|██████▉   | 7314/10519 [1:56:55<48:22,  1.10it/s][NeMo W 2026-06-19 09:06:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 70%|██████▉   | 7315/10519 [1:56:56<48:17,  1.11it/s][NeMo W 2026-06-19 09:06:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 70%|██████▉   | 7316/10519 [1:56:57<49:51,  1.07it/s][NeMo W 2026-06-19 09:06:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 70%|██████▉   | 7317/10519 [1:56:58<48:12,  1.11it/s][NeMo W 2026-06-19 09:06:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]
 70%|██████▉   | 7318/10519 [1:56:59<50:21,  1.06it/s][NeMo W 2026-06-19 09:06:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.31it/s]
 70%|██████▉   | 7319/10519 [1:57:00<50:21,  1.06it/s][NeMo W 2026-06-19 09:06:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 70%|██████▉   | 7320/10519 [1:57:01<46:57,  1.14it/s][NeMo W 2026-06-19 09:06:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 70%|██████▉   | 7321/10519 [1:57:02<48:44,  1.09it/s][NeMo W 2026-06-19 09:06:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 70%|██████▉   | 7322/10519 [1:57:03<48:38,  1.10it/s][NeMo W 2026-06-19 09:06:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.77it/s]
 70%|██████▉   | 7323/10519 [1:57:04<49:19,  1.08it/s][NeMo W 2026-06-19 09:06:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 70%|██████▉   | 7324/10519 [1:57:05<49:44,  1.07it/s][NeMo W 2026-06-19 09:06:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 70%|██████▉   | 7325/10519 [1:57:05<49:16,  1.08it/s][NeMo W 2026-06-19 09:06:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 70%|██████▉   | 7326/10519 [1:57:06<47:25,  1.12it/s][NeMo W 2026-06-19 09:06:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 70%|██████▉   | 7327/10519 [1:57:07<48:14,  1.10it/s][NeMo W 2026-06-19 09:06:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 70%|██████▉   | 7328/10519 [1:57:08<48:37,  1.09it/s][NeMo W 2026-06-19 09:06:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 70%|██████▉   | 7329/10519 [1:57:09<48:25,  1.10it/s][NeMo W 2026-06-19 09:06:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:06:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.54it/s]

Checkpoint saved: 7350 samples

[NeMo W 2026-06-19 09:07:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 70%|██████▉   | 7351/10519 [1:57:31<1:06:57,  1.27s/it][NeMo W 2026-06-19 09:07:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 70%|██████▉   | 7352/10519 [1:57:32<59:04,  1.12s/it]  [NeMo W 2026-06-19 09:07:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.58it/s]
 70%|██████▉   | 7353/10519 [1:57:33<56:08,  1.06s/it][NeMo W 2026-06-19 09:07:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 70%|██████▉   | 7354/10519 [1:57:34<54:15,  1.03s/it][NeMo W 2026-06-19 09:07:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.55it/s]
 70%|██████▉   | 7355/10519 [1:57:35<52:49,  1.00s/it][NeMo W 2026-06-19 09:07:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 70%|██████▉   | 7356/10519 [1:57:36<51:37,  1.02it/s][NeMo W 2026-06-19 09:07:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.83it/s]
 70%|██████▉   | 7357/10519 [1:57:36<46:55,  1.12it/s][NeMo W 2026-06-19 09:07:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 70%|██████▉   | 7358/10519 [1:57:37<44:00,  1.20it/s][NeMo W 2026-06-19 09:07:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.75it/s]
 70%|██████▉   | 7359/10519 [1:57:38<47:32,  1.11it/s][NeMo W 2026-06-19 09:07:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 70%|██████▉   | 7360/10519 [1:57:39<47:55,  1.10it/s][NeMo W 2026-06-19 09:07:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 70%|██████▉   | 7361/10519 [1:57:40<47:48,  1.10it/s][NeMo W 2026-06-19 09:07:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 70%|██████▉   | 7362/10519 [1:57:41<49:08,  1.07it/s][NeMo W 2026-06-19 09:07:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.65it/s]
 70%|██████▉   | 7363/10519 [1:57:42<50:17,  1.05it/s][NeMo W 2026-06-19 09:07:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 70%|███████   | 7364/10519 [1:57:43<49:56,  1.05it/s][NeMo W 2026-06-19 09:07:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 70%|███████   | 7365/10519 [1:57:44<48:40,  1.08it/s][NeMo W 2026-06-19 09:07:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 70%|███████   | 7366/10519 [1:57:45<48:46,  1.08it/s][NeMo W 2026-06-19 09:07:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 70%|███████   | 7367/10519 [1:57:45<49:24,  1.06it/s][NeMo W 2026-06-19 09:07:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 70%|███████   | 7368/10519 [1:57:46<48:48,  1.08it/s][NeMo W 2026-06-19 09:07:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.52it/s]
 70%|███████   | 7369/10519 [1:57:48<53:03,  1.01s/it][NeMo W 2026-06-19 09:07:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 70%|███████   | 7370/10519 [1:57:49<53:53,  1.03s/it][NeMo W 2026-06-19 09:07:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 70%|███████   | 7371/10519 [1:57:50<52:31,  1.00s/it][NeMo W 2026-06-19 09:07:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 70%|███████   | 7372/10519 [1:57:50<49:36,  1.06it/s][NeMo W 2026-06-19 09:07:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.02it/s]
 70%|███████   | 7373/10519 [1:57:51<50:18,  1.04it/s][NeMo W 2026-06-19 09:07:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 70%|███████   | 7374/10519 [1:57:52<49:57,  1.05it/s][NeMo W 2026-06-19 09:07:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 70%|███████   | 7375/10519 [1:57:53<49:32,  1.06it/s][NeMo W 2026-06-19 09:07:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 70%|███████   | 7376/10519 [1:57:54<49:05,  1.07it/s][NeMo W 2026-06-19 09:07:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 70%|███████   | 7377/10519 [1:57:55<49:30,  1.06it/s][NeMo W 2026-06-19 09:07:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
 70%|███████   | 7378/10519 [1:57:56<47:14,  1.11it/s][NeMo W 2026-06-19 09:07:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
 70%|███████   | 7379/10519 [1:57:57<49:14,  1.06it/s][NeMo W 2026-06-19 09:07:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.12it/s]

Checkpoint saved: 7400 samples

[NeMo W 2026-06-19 09:07:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:07:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 70%|███████   | 7401/10519 [1:58:18<1:00:23,  1.16s/it][NeMo W 2026-06-19 09:08:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 70%|███████   | 7402/10519 [1:58:19<56:03,  1.08s/it]  [NeMo W 2026-06-19 09:08:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 70%|███████   | 7403/10519 [1:58:20<57:10,  1.10s/it][NeMo W 2026-06-19 09:08:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 70%|███████   | 7404/10519 [1:58:21<56:12,  1.08s/it][NeMo W 2026-06-19 09:08:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 70%|███████   | 7405/10519 [1:58:22<53:52,  1.04s/it][NeMo W 2026-06-19 09:08:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.78it/s]
 70%|███████   | 7406/10519 [1:58:23<53:07,  1.02s/it][NeMo W 2026-06-19 09:08:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 70%|███████   | 7407/10519 [1:58:24<52:35,  1.01s/it][NeMo W 2026-06-19 09:08:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 70%|███████   | 7408/10519 [1:58:25<52:47,  1.02s/it][NeMo W 2026-06-19 09:08:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.76it/s]
 70%|███████   | 7409/10519 [1:58:26<52:33,  1.01s/it][NeMo W 2026-06-19 09:08:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 70%|███████   | 7410/10519 [1:58:27<48:29,  1.07it/s][NeMo W 2026-06-19 09:08:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 70%|███████   | 7411/10519 [1:58:28<50:32,  1.02it/s][NeMo W 2026-06-19 09:08:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 70%|███████   | 7412/10519 [1:58:29<49:59,  1.04it/s][NeMo W 2026-06-19 09:08:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 70%|███████   | 7413/10519 [1:58:30<46:37,  1.11it/s][NeMo W 2026-06-19 09:08:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 70%|███████   | 7414/10519 [1:58:30<44:31,  1.16it/s][NeMo W 2026-06-19 09:08:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 70%|███████   | 7415/10519 [1:58:31<42:36,  1.21it/s][NeMo W 2026-06-19 09:08:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 71%|███████   | 7416/10519 [1:58:32<43:42,  1.18it/s][NeMo W 2026-06-19 09:08:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 71%|███████   | 7417/10519 [1:58:33<46:00,  1.12it/s][NeMo W 2026-06-19 09:08:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
 71%|███████   | 7418/10519 [1:58:34<46:43,  1.11it/s][NeMo W 2026-06-19 09:08:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 71%|███████   | 7419/10519 [1:58:35<48:25,  1.07it/s][NeMo W 2026-06-19 09:08:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 71%|███████   | 7420/10519 [1:58:36<49:09,  1.05it/s][NeMo W 2026-06-19 09:08:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 71%|███████   | 7421/10519 [1:58:37<50:28,  1.02it/s][NeMo W 2026-06-19 09:08:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.17it/s]
 71%|███████   | 7422/10519 [1:58:38<50:43,  1.02it/s][NeMo W 2026-06-19 09:08:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 71%|███████   | 7423/10519 [1:58:39<50:45,  1.02it/s][NeMo W 2026-06-19 09:08:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 71%|███████   | 7424/10519 [1:58:40<49:22,  1.04it/s][NeMo W 2026-06-19 09:08:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 71%|███████   | 7425/10519 [1:58:41<52:26,  1.02s/it][NeMo W 2026-06-19 09:08:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 71%|███████   | 7426/10519 [1:58:42<51:33,  1.00s/it][NeMo W 2026-06-19 09:08:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 71%|███████   | 7427/10519 [1:58:43<49:45,  1.04it/s][NeMo W 2026-06-19 09:08:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 71%|███████   | 7428/10519 [1:58:44<48:53,  1.05it/s][NeMo W 2026-06-19 09:08:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 71%|███████   | 7429/10519 [1:58:45<50:08,  1.03it/s][NeMo W 2026-06-19 09:08:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]

Checkpoint saved: 7450 samples

[NeMo W 2026-06-19 09:08:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 71%|███████   | 7451/10519 [1:59:06<1:02:18,  1.22s/it][NeMo W 2026-06-19 09:08:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.26it/s]
 71%|███████   | 7452/10519 [1:59:08<1:00:27,  1.18s/it][NeMo W 2026-06-19 09:08:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 71%|███████   | 7453/10519 [1:59:08<57:13,  1.12s/it]  [NeMo W 2026-06-19 09:08:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.08it/s]
 71%|███████   | 7454/10519 [1:59:09<54:10,  1.06s/it][NeMo W 2026-06-19 09:08:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 71%|███████   | 7455/10519 [1:59:10<52:06,  1.02s/it][NeMo W 2026-06-19 09:08:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 71%|███████   | 7456/10519 [1:59:11<47:57,  1.06it/s][NeMo W 2026-06-19 09:08:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.87it/s]
 71%|███████   | 7457/10519 [1:59:12<48:07,  1.06it/s][NeMo W 2026-06-19 09:08:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 71%|███████   | 7458/10519 [1:59:13<51:19,  1.01s/it][NeMo W 2026-06-19 09:08:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 71%|███████   | 7459/10519 [1:59:14<50:06,  1.02it/s][NeMo W 2026-06-19 09:08:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 71%|███████   | 7460/10519 [1:59:15<45:56,  1.11it/s][NeMo W 2026-06-19 09:08:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 71%|███████   | 7461/10519 [1:59:16<47:33,  1.07it/s][NeMo W 2026-06-19 09:08:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.97it/s]
 71%|███████   | 7462/10519 [1:59:17<47:23,  1.08it/s][NeMo W 2026-06-19 09:08:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:08:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.57it/s]
 71%|███████   | 7463/10519 [1:59:18<46:17,  1.10it/s][NeMo W 2026-06-19 09:08:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 71%|███████   | 7464/10519 [1:59:19<48:35,  1.05it/s][NeMo W 2026-06-19 09:09:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 71%|███████   | 7465/10519 [1:59:20<46:24,  1.10it/s][NeMo W 2026-06-19 09:09:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.78it/s]
 71%|███████   | 7466/10519 [1:59:20<47:28,  1.07it/s][NeMo W 2026-06-19 09:09:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 71%|███████   | 7467/10519 [1:59:21<47:03,  1.08it/s][NeMo W 2026-06-19 09:09:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.93it/s]
 71%|███████   | 7468/10519 [1:59:22<47:22,  1.07it/s][NeMo W 2026-06-19 09:09:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 71%|███████   | 7469/10519 [1:59:23<47:17,  1.07it/s][NeMo W 2026-06-19 09:09:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.15it/s]
 71%|███████   | 7470/10519 [1:59:24<46:59,  1.08it/s][NeMo W 2026-06-19 09:09:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 71%|███████   | 7471/10519 [1:59:25<44:22,  1.14it/s][NeMo W 2026-06-19 09:09:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 71%|███████   | 7472/10519 [1:59:26<47:51,  1.06it/s][NeMo W 2026-06-19 09:09:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 71%|███████   | 7473/10519 [1:59:27<49:21,  1.03it/s][NeMo W 2026-06-19 09:09:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 71%|███████   | 7474/10519 [1:59:28<45:31,  1.11it/s][NeMo W 2026-06-19 09:09:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.77it/s]
 71%|███████   | 7475/10519 [1:59:29<46:21,  1.09it/s][NeMo W 2026-06-19 09:09:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 71%|███████   | 7476/10519 [1:59:30<47:14,  1.07it/s][NeMo W 2026-06-19 09:09:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.53it/s]
 71%|███████   | 7477/10519 [1:59:31<48:44,  1.04it/s][NeMo W 2026-06-19 09:09:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 71%|███████   | 7478/10519 [1:59:32<48:55,  1.04it/s][NeMo W 2026-06-19 09:09:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 71%|███████   | 7479/10519 [1:59:33<51:50,  1.02s/it][NeMo W 2026-06-19 09:09:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]

Checkpoint saved: 7500 samples

[NeMo W 2026-06-19 09:09:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 71%|███████▏  | 7501/10519 [1:59:54<58:31,  1.16s/it]  [NeMo W 2026-06-19 09:09:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  4.71it/s]
 71%|███████▏  | 7502/10519 [1:59:55<56:36,  1.13s/it][NeMo W 2026-06-19 09:09:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 71%|███████▏  | 7503/10519 [1:59:56<53:45,  1.07s/it][NeMo W 2026-06-19 09:09:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 71%|███████▏  | 7504/10519 [1:59:57<51:48,  1.03s/it][NeMo W 2026-06-19 09:09:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.79it/s]
 71%|███████▏  | 7505/10519 [1:59:58<49:57,  1.01it/s][NeMo W 2026-06-19 09:09:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.05it/s]
 71%|███████▏  | 7506/10519 [1:59:59<48:42,  1.03it/s][NeMo W 2026-06-19 09:09:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 71%|███████▏  | 7507/10519 [1:59:59<44:41,  1.12it/s][NeMo W 2026-06-19 09:09:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 71%|███████▏  | 7508/10519 [2:00:00<46:03,  1.09it/s][NeMo W 2026-06-19 09:09:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.64it/s]
 71%|███████▏  | 7509/10519 [2:00:01<46:18,  1.08it/s][NeMo W 2026-06-19 09:09:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 71%|███████▏  | 7510/10519 [2:00:03<57:17,  1.14s/it][NeMo W 2026-06-19 09:09:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 71%|███████▏  | 7511/10519 [2:00:04<53:40,  1.07s/it][NeMo W 2026-06-19 09:09:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 71%|███████▏  | 7512/10519 [2:00:05<52:42,  1.05s/it][NeMo W 2026-06-19 09:09:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 71%|███████▏  | 7513/10519 [2:00:06<51:27,  1.03s/it][NeMo W 2026-06-19 09:09:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 71%|███████▏  | 7514/10519 [2:00:07<51:12,  1.02s/it][NeMo W 2026-06-19 09:09:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 71%|███████▏  | 7515/10519 [2:00:08<48:55,  1.02it/s][NeMo W 2026-06-19 09:09:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]
 71%|███████▏  | 7516/10519 [2:00:09<48:18,  1.04it/s][NeMo W 2026-06-19 09:09:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.02it/s]
 71%|███████▏  | 7517/10519 [2:00:10<49:59,  1.00it/s][NeMo W 2026-06-19 09:09:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 71%|███████▏  | 7518/10519 [2:00:11<49:46,  1.00it/s][NeMo W 2026-06-19 09:09:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 71%|███████▏  | 7519/10519 [2:00:12<49:08,  1.02it/s][NeMo W 2026-06-19 09:09:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 71%|███████▏  | 7520/10519 [2:00:13<48:39,  1.03it/s][NeMo W 2026-06-19 09:09:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.75it/s]
 71%|███████▏  | 7521/10519 [2:00:14<48:10,  1.04it/s][NeMo W 2026-06-19 09:09:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.14it/s]
 72%|███████▏  | 7522/10519 [2:00:15<48:03,  1.04it/s][NeMo W 2026-06-19 09:09:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 72%|███████▏  | 7523/10519 [2:00:15<47:49,  1.04it/s][NeMo W 2026-06-19 09:09:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 72%|███████▏  | 7524/10519 [2:00:16<47:04,  1.06it/s][NeMo W 2026-06-19 09:09:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 72%|███████▏  | 7525/10519 [2:00:17<46:32,  1.07it/s][NeMo W 2026-06-19 09:09:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:09:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 72%|███████▏  | 7526/10519 [2:00:18<48:46,  1.02it/s][NeMo W 2026-06-19 09:10:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 72%|███████▏  | 7527/10519 [2:00:19<47:58,  1.04it/s][NeMo W 2026-06-19 09:10:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.32it/s]
 72%|███████▏  | 7528/10519 [2:00:20<46:14,  1.08it/s][NeMo W 2026-06-19 09:10:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 72%|███████▏  | 7529/10519 [2:00:21<46:43,  1.07it/s][NeMo W 2026-06-19 09:10:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]

Checkpoint saved: 7550 samples

[NeMo W 2026-06-19 09:10:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 72%|███████▏  | 7551/10519 [2:00:44<1:01:42,  1.25s/it][NeMo W 2026-06-19 09:10:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 72%|███████▏  | 7552/10519 [2:00:45<58:32,  1.18s/it]  [NeMo W 2026-06-19 09:10:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 72%|███████▏  | 7553/10519 [2:00:46<52:41,  1.07s/it][NeMo W 2026-06-19 09:10:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 72%|███████▏  | 7554/10519 [2:00:47<50:43,  1.03s/it][NeMo W 2026-06-19 09:10:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 72%|███████▏  | 7555/10519 [2:00:48<45:58,  1.07it/s][NeMo W 2026-06-19 09:10:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
 72%|███████▏  | 7556/10519 [2:00:49<46:28,  1.06it/s][NeMo W 2026-06-19 09:10:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 72%|███████▏  | 7557/10519 [2:00:49<46:37,  1.06it/s][NeMo W 2026-06-19 09:10:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 72%|███████▏  | 7558/10519 [2:00:50<46:59,  1.05it/s][NeMo W 2026-06-19 09:10:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 72%|███████▏  | 7559/10519 [2:00:52<49:36,  1.01s/it][NeMo W 2026-06-19 09:10:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.22it/s]
 72%|███████▏  | 7560/10519 [2:00:52<45:18,  1.09it/s][NeMo W 2026-06-19 09:10:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 72%|███████▏  | 7561/10519 [2:00:53<43:34,  1.13it/s][NeMo W 2026-06-19 09:10:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.73it/s]
 72%|███████▏  | 7562/10519 [2:00:54<42:07,  1.17it/s][NeMo W 2026-06-19 09:10:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 72%|███████▏  | 7563/10519 [2:00:55<42:58,  1.15it/s][NeMo W 2026-06-19 09:10:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 72%|███████▏  | 7564/10519 [2:00:56<41:12,  1.19it/s][NeMo W 2026-06-19 09:10:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 72%|███████▏  | 7565/10519 [2:00:57<43:17,  1.14it/s][NeMo W 2026-06-19 09:10:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 72%|███████▏  | 7566/10519 [2:00:57<44:03,  1.12it/s][NeMo W 2026-06-19 09:10:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 72%|███████▏  | 7567/10519 [2:00:58<44:45,  1.10it/s][NeMo W 2026-06-19 09:10:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 72%|███████▏  | 7568/10519 [2:00:59<46:28,  1.06it/s][NeMo W 2026-06-19 09:10:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.36it/s]
 72%|███████▏  | 7569/10519 [2:01:00<44:05,  1.12it/s][NeMo W 2026-06-19 09:10:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 72%|███████▏  | 7570/10519 [2:01:01<45:00,  1.09it/s][NeMo W 2026-06-19 09:10:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 72%|███████▏  | 7571/10519 [2:01:02<45:36,  1.08it/s][NeMo W 2026-06-19 09:10:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 72%|███████▏  | 7572/10519 [2:01:03<45:29,  1.08it/s][NeMo W 2026-06-19 09:10:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.02it/s]
 72%|███████▏  | 7573/10519 [2:01:04<45:48,  1.07it/s][NeMo W 2026-06-19 09:10:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 72%|███████▏  | 7574/10519 [2:01:05<46:31,  1.06it/s][NeMo W 2026-06-19 09:10:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 72%|███████▏  | 7575/10519 [2:01:06<45:55,  1.07it/s][NeMo W 2026-06-19 09:10:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 72%|███████▏  | 7576/10519 [2:01:07<45:59,  1.07it/s][NeMo W 2026-06-19 09:10:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 72%|███████▏  | 7577/10519 [2:01:08<47:35,  1.03it/s][NeMo W 2026-06-19 09:10:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 72%|███████▏  | 7578/10519 [2:01:09<46:39,  1.05it/s][NeMo W 2026-06-19 09:10:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 72%|███████▏  | 7579/10519 [2:01:10<47:44,  1.03it/s][NeMo W 2026-06-19 09:10:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:10:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 72%|███████▏  | 7580/10519 [2:01:11<48:53,  1.00it/s][NeMo W 2026-06-19 09:10:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 7600 samples

[NeMo W 2026-06-19 09:11:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 72%|███████▏  | 7601/10519 [2:01:34<1:18:49,  1.62s/it][NeMo W 2026-06-19 09:11:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 72%|███████▏  | 7602/10519 [2:01:35<1:08:55,  1.42s/it][NeMo W 2026-06-19 09:11:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 72%|███████▏  | 7603/10519 [2:01:36<1:02:16,  1.28s/it][NeMo W 2026-06-19 09:11:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
 72%|███████▏  | 7604/10519 [2:01:36<56:31,  1.16s/it]  [NeMo W 2026-06-19 09:11:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 72%|███████▏  | 7605/10519 [2:01:38<56:22,  1.16s/it][NeMo W 2026-06-19 09:11:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.64it/s]
 72%|███████▏  | 7606/10519 [2:01:38<50:10,  1.03s/it][NeMo W 2026-06-19 09:11:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 72%|███████▏  | 7607/10519 [2:01:39<47:59,  1.01it/s][NeMo W 2026-06-19 09:11:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 72%|███████▏  | 7608/10519 [2:01:40<46:52,  1.04it/s][NeMo W 2026-06-19 09:11:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 72%|███████▏  | 7609/10519 [2:01:41<46:38,  1.04it/s][NeMo W 2026-06-19 09:11:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 72%|███████▏  | 7610/10519 [2:01:42<46:21,  1.05it/s][NeMo W 2026-06-19 09:11:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 72%|███████▏  | 7611/10519 [2:01:43<46:44,  1.04it/s][NeMo W 2026-06-19 09:11:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.41it/s]
 72%|███████▏  | 7612/10519 [2:01:44<46:05,  1.05it/s][NeMo W 2026-06-19 09:11:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.64it/s]
 72%|███████▏  | 7613/10519 [2:01:45<46:04,  1.05it/s][NeMo W 2026-06-19 09:11:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 72%|███████▏  | 7614/10519 [2:01:46<43:17,  1.12it/s][NeMo W 2026-06-19 09:11:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.01it/s]
 72%|███████▏  | 7615/10519 [2:01:46<40:28,  1.20it/s][NeMo W 2026-06-19 09:11:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 72%|███████▏  | 7616/10519 [2:01:47<41:45,  1.16it/s][NeMo W 2026-06-19 09:11:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 72%|███████▏  | 7617/10519 [2:01:48<42:22,  1.14it/s][NeMo W 2026-06-19 09:11:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]
 72%|███████▏  | 7618/10519 [2:01:49<43:40,  1.11it/s][NeMo W 2026-06-19 09:11:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 72%|███████▏  | 7619/10519 [2:01:51<50:36,  1.05s/it][NeMo W 2026-06-19 09:11:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
 72%|███████▏  | 7620/10519 [2:01:52<49:08,  1.02s/it][NeMo W 2026-06-19 09:11:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 72%|███████▏  | 7621/10519 [2:01:52<47:37,  1.01it/s][NeMo W 2026-06-19 09:11:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 72%|███████▏  | 7622/10519 [2:01:53<46:07,  1.05it/s][NeMo W 2026-06-19 09:11:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 72%|███████▏  | 7623/10519 [2:01:54<46:30,  1.04it/s][NeMo W 2026-06-19 09:11:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 72%|███████▏  | 7624/10519 [2:01:55<46:27,  1.04it/s][NeMo W 2026-06-19 09:11:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 72%|███████▏  | 7625/10519 [2:01:56<47:14,  1.02it/s][NeMo W 2026-06-19 09:11:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 72%|███████▏  | 7626/10519 [2:01:57<47:39,  1.01it/s][NeMo W 2026-06-19 09:11:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 73%|███████▎  | 7627/10519 [2:01:58<46:04,  1.05it/s][NeMo W 2026-06-19 09:11:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 73%|███████▎  | 7628/10519 [2:01:59<42:52,  1.12it/s][NeMo W 2026-06-19 09:11:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 73%|███████▎  | 7629/10519 [2:02:00<44:39,  1.08it/s][NeMo W 2026-06-19 09:11:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:11:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 73%|███████▎  | 7630/10519 [2:02:01<43:37,  1.10it/s][NeMo W 2026-06-19 09:11:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 7650 samples

[NeMo W 2026-06-19 09:12:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.65it/s]
 73%|███████▎  | 7651/10519 [2:02:24<1:07:42,  1.42s/it][NeMo W 2026-06-19 09:12:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.06it/s]
 73%|███████▎  | 7652/10519 [2:02:25<1:01:16,  1.28s/it][NeMo W 2026-06-19 09:12:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 73%|███████▎  | 7653/10519 [2:02:26<52:59,  1.11s/it]  [NeMo W 2026-06-19 09:12:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 73%|███████▎  | 7654/10519 [2:02:26<50:13,  1.05s/it][NeMo W 2026-06-19 09:12:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 73%|███████▎  | 7655/10519 [2:02:27<48:07,  1.01s/it][NeMo W 2026-06-19 09:12:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.82it/s]
 73%|███████▎  | 7656/10519 [2:02:28<47:25,  1.01it/s][NeMo W 2026-06-19 09:12:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.03it/s]
 73%|███████▎  | 7657/10519 [2:02:29<47:24,  1.01it/s][NeMo W 2026-06-19 09:12:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 73%|███████▎  | 7658/10519 [2:02:30<46:09,  1.03it/s][NeMo W 2026-06-19 09:12:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.85it/s]
 73%|███████▎  | 7659/10519 [2:02:31<46:28,  1.03it/s][NeMo W 2026-06-19 09:12:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 73%|███████▎  | 7660/10519 [2:02:32<45:28,  1.05it/s][NeMo W 2026-06-19 09:12:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 73%|███████▎  | 7661/10519 [2:02:33<45:35,  1.04it/s][NeMo W 2026-06-19 09:12:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.66it/s]
 73%|███████▎  | 7662/10519 [2:02:34<44:25,  1.07it/s][NeMo W 2026-06-19 09:12:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 73%|███████▎  | 7663/10519 [2:02:35<44:34,  1.07it/s][NeMo W 2026-06-19 09:12:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 73%|███████▎  | 7664/10519 [2:02:36<46:46,  1.02it/s][NeMo W 2026-06-19 09:12:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.16it/s]
 73%|███████▎  | 7665/10519 [2:02:37<44:36,  1.07it/s][NeMo W 2026-06-19 09:12:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 73%|███████▎  | 7666/10519 [2:02:38<44:30,  1.07it/s][NeMo W 2026-06-19 09:12:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 73%|███████▎  | 7667/10519 [2:02:39<44:36,  1.07it/s][NeMo W 2026-06-19 09:12:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 73%|███████▎  | 7668/10519 [2:02:40<45:35,  1.04it/s][NeMo W 2026-06-19 09:12:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 73%|███████▎  | 7669/10519 [2:02:41<46:10,  1.03it/s][NeMo W 2026-06-19 09:12:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 73%|███████▎  | 7670/10519 [2:02:42<44:47,  1.06it/s][NeMo W 2026-06-19 09:12:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.57it/s]
 73%|███████▎  | 7671/10519 [2:02:43<44:26,  1.07it/s][NeMo W 2026-06-19 09:12:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.84it/s]
 73%|███████▎  | 7672/10519 [2:02:43<44:35,  1.06it/s][NeMo W 2026-06-19 09:12:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 73%|███████▎  | 7673/10519 [2:02:44<40:18,  1.18it/s][NeMo W 2026-06-19 09:12:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 73%|███████▎  | 7674/10519 [2:02:46<49:12,  1.04s/it][NeMo W 2026-06-19 09:12:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 73%|███████▎  | 7675/10519 [2:02:47<47:37,  1.00s/it][NeMo W 2026-06-19 09:12:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
 73%|███████▎  | 7676/10519 [2:02:48<47:28,  1.00s/it][NeMo W 2026-06-19 09:12:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.23it/s]
 73%|███████▎  | 7677/10519 [2:02:49<47:26,  1.00s/it][NeMo W 2026-06-19 09:12:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.50it/s]
 73%|███████▎  | 7678/10519 [2:02:50<47:32,  1.00s/it][NeMo W 2026-06-19 09:12:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 73%|███████▎  | 7679/10519 [2:02:50<46:29,  1.02it/s][NeMo W 2026-06-19 09:12:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]

Checkpoint saved: 7700 samples

[NeMo W 2026-06-19 09:12:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 73%|███████▎  | 7701/10519 [2:03:12<55:17,  1.18s/it]  [NeMo W 2026-06-19 09:12:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.47it/s]
 73%|███████▎  | 7702/10519 [2:03:13<51:20,  1.09s/it][NeMo W 2026-06-19 09:12:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 73%|███████▎  | 7703/10519 [2:03:13<48:15,  1.03s/it][NeMo W 2026-06-19 09:12:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.03it/s]
 73%|███████▎  | 7704/10519 [2:03:14<47:47,  1.02s/it][NeMo W 2026-06-19 09:12:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.02it/s]
 73%|███████▎  | 7705/10519 [2:03:15<47:29,  1.01s/it][NeMo W 2026-06-19 09:12:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.04it/s]
 73%|███████▎  | 7706/10519 [2:03:16<47:35,  1.02s/it][NeMo W 2026-06-19 09:12:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.86it/s]
 73%|███████▎  | 7707/10519 [2:03:17<47:23,  1.01s/it][NeMo W 2026-06-19 09:12:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:12:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.56it/s]
 73%|███████▎  | 7708/10519 [2:03:18<46:55,  1.00s/it][NeMo W 2026-06-19 09:13:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 73%|███████▎  | 7709/10519 [2:03:20<50:35,  1.08s/it][NeMo W 2026-06-19 09:13:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 73%|███████▎  | 7710/10519 [2:03:21<58:24,  1.25s/it][NeMo W 2026-06-19 09:13:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 73%|███████▎  | 7711/10519 [2:03:22<51:40,  1.10s/it][NeMo W 2026-06-19 09:13:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 73%|███████▎  | 7712/10519 [2:03:23<49:03,  1.05s/it][NeMo W 2026-06-19 09:13:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 73%|███████▎  | 7713/10519 [2:03:24<46:48,  1.00s/it][NeMo W 2026-06-19 09:13:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 73%|███████▎  | 7714/10519 [2:03:25<46:07,  1.01it/s][NeMo W 2026-06-19 09:13:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 73%|███████▎  | 7715/10519 [2:03:26<44:55,  1.04it/s][NeMo W 2026-06-19 09:13:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
 73%|███████▎  | 7716/10519 [2:03:27<43:17,  1.08it/s][NeMo W 2026-06-19 09:13:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 73%|███████▎  | 7717/10519 [2:03:28<42:37,  1.10it/s][NeMo W 2026-06-19 09:13:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 73%|███████▎  | 7718/10519 [2:03:28<40:38,  1.15it/s][NeMo W 2026-06-19 09:13:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 73%|███████▎  | 7719/10519 [2:03:29<42:09,  1.11it/s][NeMo W 2026-06-19 09:13:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 73%|███████▎  | 7720/10519 [2:03:30<43:06,  1.08it/s][NeMo W 2026-06-19 09:13:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 73%|███████▎  | 7721/10519 [2:03:31<43:21,  1.08it/s][NeMo W 2026-06-19 09:13:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.29it/s]
 73%|███████▎  | 7722/10519 [2:03:32<44:29,  1.05it/s][NeMo W 2026-06-19 09:13:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 73%|███████▎  | 7723/10519 [2:03:33<45:29,  1.02it/s][NeMo W 2026-06-19 09:13:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 73%|███████▎  | 7724/10519 [2:03:34<44:32,  1.05it/s][NeMo W 2026-06-19 09:13:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 73%|███████▎  | 7725/10519 [2:03:35<43:32,  1.07it/s][NeMo W 2026-06-19 09:13:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 73%|███████▎  | 7726/10519 [2:03:36<43:47,  1.06it/s][NeMo W 2026-06-19 09:13:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 73%|███████▎  | 7727/10519 [2:03:37<41:28,  1.12it/s][NeMo W 2026-06-19 09:13:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.65it/s]
 73%|███████▎  | 7728/10519 [2:03:38<41:26,  1.12it/s][NeMo W 2026-06-19 09:13:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 73%|███████▎  | 7729/10519 [2:03:38<38:54,  1.20it/s][NeMo W 2026-06-19 09:13:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]

Checkpoint saved: 7750 samples

[NeMo W 2026-06-19 09:13:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 74%|███████▎  | 7751/10519 [2:04:00<54:09,  1.17s/it]  [NeMo W 2026-06-19 09:13:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 74%|███████▎  | 7752/10519 [2:04:01<48:55,  1.06s/it][NeMo W 2026-06-19 09:13:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 74%|███████▎  | 7753/10519 [2:04:02<45:35,  1.01it/s][NeMo W 2026-06-19 09:13:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 74%|███████▎  | 7754/10519 [2:04:03<44:25,  1.04it/s][NeMo W 2026-06-19 09:13:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 74%|███████▎  | 7755/10519 [2:04:04<45:29,  1.01it/s][NeMo W 2026-06-19 09:13:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 74%|███████▎  | 7756/10519 [2:04:04<44:06,  1.04it/s][NeMo W 2026-06-19 09:13:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 74%|███████▎  | 7757/10519 [2:04:05<40:48,  1.13it/s][NeMo W 2026-06-19 09:13:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 74%|███████▍  | 7758/10519 [2:04:06<41:48,  1.10it/s][NeMo W 2026-06-19 09:13:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 74%|███████▍  | 7759/10519 [2:04:07<38:39,  1.19it/s][NeMo W 2026-06-19 09:13:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 74%|███████▍  | 7760/10519 [2:04:08<39:21,  1.17it/s][NeMo W 2026-06-19 09:13:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 74%|███████▍  | 7761/10519 [2:04:09<41:52,  1.10it/s][NeMo W 2026-06-19 09:13:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 74%|███████▍  | 7762/10519 [2:04:10<39:46,  1.16it/s][NeMo W 2026-06-19 09:13:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 74%|███████▍  | 7763/10519 [2:04:11<41:09,  1.12it/s][NeMo W 2026-06-19 09:13:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.48it/s]
 74%|███████▍  | 7764/10519 [2:04:11<41:22,  1.11it/s][NeMo W 2026-06-19 09:13:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 74%|███████▍  | 7765/10519 [2:04:13<47:08,  1.03s/it][NeMo W 2026-06-19 09:13:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 74%|███████▍  | 7766/10519 [2:04:14<45:40,  1.00it/s][NeMo W 2026-06-19 09:13:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.37it/s]
 74%|███████▍  | 7767/10519 [2:04:15<44:40,  1.03it/s][NeMo W 2026-06-19 09:13:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 74%|███████▍  | 7768/10519 [2:04:16<43:42,  1.05it/s][NeMo W 2026-06-19 09:13:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.65it/s]
 74%|███████▍  | 7769/10519 [2:04:16<43:16,  1.06it/s][NeMo W 2026-06-19 09:13:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 74%|███████▍  | 7770/10519 [2:04:17<42:19,  1.08it/s][NeMo W 2026-06-19 09:13:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:13:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 74%|███████▍  | 7771/10519 [2:04:18<42:48,  1.07it/s][NeMo W 2026-06-19 09:14:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
 74%|███████▍  | 7772/10519 [2:04:19<45:50,  1.00s/it][NeMo W 2026-06-19 09:14:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 74%|███████▍  | 7773/10519 [2:04:20<44:50,  1.02it/s][NeMo W 2026-06-19 09:14:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 74%|███████▍  | 7774/10519 [2:04:21<45:33,  1.00it/s][NeMo W 2026-06-19 09:14:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.29it/s]
 74%|███████▍  | 7775/10519 [2:04:22<44:49,  1.02it/s][NeMo W 2026-06-19 09:14:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 74%|███████▍  | 7776/10519 [2:04:23<44:18,  1.03it/s][NeMo W 2026-06-19 09:14:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.70it/s]
 74%|███████▍  | 7777/10519 [2:04:24<42:37,  1.07it/s][NeMo W 2026-06-19 09:14:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 74%|███████▍  | 7778/10519 [2:04:25<42:44,  1.07it/s][NeMo W 2026-06-19 09:14:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 74%|███████▍  | 7779/10519 [2:04:26<42:32,  1.07it/s][NeMo W 2026-06-19 09:14:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]

Checkpoint saved: 7800 samples

[NeMo W 2026-06-19 09:14:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 74%|███████▍  | 7801/10519 [2:04:48<54:38,  1.21s/it][NeMo W 2026-06-19 09:14:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 74%|███████▍  | 7802/10519 [2:04:49<52:11,  1.15s/it][NeMo W 2026-06-19 09:14:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 74%|███████▍  | 7803/10519 [2:04:50<50:21,  1.11s/it][NeMo W 2026-06-19 09:14:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.26it/s]
 74%|███████▍  | 7804/10519 [2:04:51<49:08,  1.09s/it][NeMo W 2026-06-19 09:14:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 74%|███████▍  | 7805/10519 [2:04:52<47:18,  1.05s/it][NeMo W 2026-06-19 09:14:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.42it/s]
 74%|███████▍  | 7806/10519 [2:04:52<44:09,  1.02it/s][NeMo W 2026-06-19 09:14:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 74%|███████▍  | 7807/10519 [2:04:53<43:56,  1.03it/s][NeMo W 2026-06-19 09:14:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.15it/s]
 74%|███████▍  | 7808/10519 [2:04:54<43:22,  1.04it/s][NeMo W 2026-06-19 09:14:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 74%|███████▍  | 7809/10519 [2:04:55<43:32,  1.04it/s][NeMo W 2026-06-19 09:14:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 74%|███████▍  | 7810/10519 [2:04:56<42:23,  1.07it/s][NeMo W 2026-06-19 09:14:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.83it/s]
 74%|███████▍  | 7811/10519 [2:04:57<42:09,  1.07it/s][NeMo W 2026-06-19 09:14:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 74%|███████▍  | 7812/10519 [2:04:58<44:33,  1.01it/s][NeMo W 2026-06-19 09:14:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 74%|███████▍  | 7813/10519 [2:04:59<44:55,  1.00it/s][NeMo W 2026-06-19 09:14:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 74%|███████▍  | 7814/10519 [2:05:00<44:06,  1.02it/s][NeMo W 2026-06-19 09:14:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.96it/s]
 74%|███████▍  | 7815/10519 [2:05:01<43:10,  1.04it/s][NeMo W 2026-06-19 09:14:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.69it/s]
 74%|███████▍  | 7816/10519 [2:05:03<59:14,  1.32s/it][NeMo W 2026-06-19 09:14:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 74%|███████▍  | 7817/10519 [2:05:04<53:54,  1.20s/it][NeMo W 2026-06-19 09:14:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 74%|███████▍  | 7818/10519 [2:05:05<48:25,  1.08s/it][NeMo W 2026-06-19 09:14:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 74%|███████▍  | 7819/10519 [2:05:06<48:40,  1.08s/it][NeMo W 2026-06-19 09:14:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 74%|███████▍  | 7820/10519 [2:05:07<46:14,  1.03s/it][NeMo W 2026-06-19 09:14:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 74%|███████▍  | 7821/10519 [2:05:08<44:26,  1.01it/s][NeMo W 2026-06-19 09:14:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 74%|███████▍  | 7822/10519 [2:05:09<43:30,  1.03it/s][NeMo W 2026-06-19 09:14:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 74%|███████▍  | 7823/10519 [2:05:10<42:37,  1.05it/s][NeMo W 2026-06-19 09:14:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 74%|███████▍  | 7824/10519 [2:05:11<43:57,  1.02it/s][NeMo W 2026-06-19 09:14:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 74%|███████▍  | 7825/10519 [2:05:12<43:06,  1.04it/s][NeMo W 2026-06-19 09:14:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 74%|███████▍  | 7826/10519 [2:05:12<40:46,  1.10it/s][NeMo W 2026-06-19 09:14:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.74it/s]
 74%|███████▍  | 7827/10519 [2:05:13<41:19,  1.09it/s][NeMo W 2026-06-19 09:14:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.24it/s]
 74%|███████▍  | 7828/10519 [2:05:14<41:42,  1.08it/s][NeMo W 2026-06-19 09:14:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 74%|███████▍  | 7829/10519 [2:05:15<42:06,  1.06it/s][NeMo W 2026-06-19 09:14:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:14:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 74%|███████▍  | 7830/10519 [2:05:16<42:36,  1.05it/s][NeMo W 2026-06-19 09:14:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 7850 samples

[NeMo W 2026-06-19 09:15:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.68it/s]
 75%|███████▍  | 7851/10519 [2:05:37<54:55,  1.24s/it][NeMo W 2026-06-19 09:15:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 75%|███████▍  | 7852/10519 [2:05:38<52:32,  1.18s/it][NeMo W 2026-06-19 09:15:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 75%|███████▍  | 7853/10519 [2:05:39<49:06,  1.11s/it][NeMo W 2026-06-19 09:15:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 75%|███████▍  | 7854/10519 [2:05:40<46:57,  1.06s/it][NeMo W 2026-06-19 09:15:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 75%|███████▍  | 7855/10519 [2:05:41<46:14,  1.04s/it][NeMo W 2026-06-19 09:15:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.29it/s]
 75%|███████▍  | 7856/10519 [2:05:42<44:12,  1.00it/s][NeMo W 2026-06-19 09:15:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 75%|███████▍  | 7857/10519 [2:05:43<45:44,  1.03s/it][NeMo W 2026-06-19 09:15:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 75%|███████▍  | 7858/10519 [2:05:44<44:27,  1.00s/it][NeMo W 2026-06-19 09:15:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 75%|███████▍  | 7859/10519 [2:05:45<41:26,  1.07it/s][NeMo W 2026-06-19 09:15:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.63it/s]
 75%|███████▍  | 7860/10519 [2:05:46<41:44,  1.06it/s][NeMo W 2026-06-19 09:15:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 75%|███████▍  | 7861/10519 [2:05:47<41:25,  1.07it/s][NeMo W 2026-06-19 09:15:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 75%|███████▍  | 7862/10519 [2:05:48<42:18,  1.05it/s][NeMo W 2026-06-19 09:15:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 75%|███████▍  | 7863/10519 [2:05:49<41:44,  1.06it/s][NeMo W 2026-06-19 09:15:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 75%|███████▍  | 7864/10519 [2:05:50<42:09,  1.05it/s][NeMo W 2026-06-19 09:15:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 75%|███████▍  | 7865/10519 [2:05:51<40:05,  1.10it/s][NeMo W 2026-06-19 09:15:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 75%|███████▍  | 7866/10519 [2:05:51<39:55,  1.11it/s][NeMo W 2026-06-19 09:15:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 75%|███████▍  | 7867/10519 [2:05:52<40:30,  1.09it/s][NeMo W 2026-06-19 09:15:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 75%|███████▍  | 7868/10519 [2:05:53<40:37,  1.09it/s][NeMo W 2026-06-19 09:15:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 75%|███████▍  | 7869/10519 [2:05:54<41:14,  1.07it/s][NeMo W 2026-06-19 09:15:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 75%|███████▍  | 7870/10519 [2:05:55<42:01,  1.05it/s][NeMo W 2026-06-19 09:15:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 75%|███████▍  | 7871/10519 [2:05:56<42:13,  1.05it/s][NeMo W 2026-06-19 09:15:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 75%|███████▍  | 7872/10519 [2:05:57<40:44,  1.08it/s][NeMo W 2026-06-19 09:15:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 75%|███████▍  | 7873/10519 [2:05:58<40:54,  1.08it/s][NeMo W 2026-06-19 09:15:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 75%|███████▍  | 7874/10519 [2:05:59<40:17,  1.09it/s][NeMo W 2026-06-19 09:15:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 75%|███████▍  | 7875/10519 [2:06:00<40:15,  1.09it/s][NeMo W 2026-06-19 09:15:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
 75%|███████▍  | 7876/10519 [2:06:01<40:21,  1.09it/s][NeMo W 2026-06-19 09:15:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.26it/s]
 75%|███████▍  | 7877/10519 [2:06:02<37:57,  1.16it/s][NeMo W 2026-06-19 09:15:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 75%|███████▍  | 7878/10519 [2:06:02<38:44,  1.14it/s][NeMo W 2026-06-19 09:15:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 75%|███████▍  | 7879/10519 [2:06:03<37:38,  1.17it/s][NeMo W 2026-06-19 09:15:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:15:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]

Checkpoint saved: 7900 samples

[NeMo W 2026-06-19 09:16:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 75%|███████▌  | 7901/10519 [2:06:25<56:22,  1.29s/it]  [NeMo W 2026-06-19 09:16:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 75%|███████▌  | 7902/10519 [2:06:27<59:37,  1.37s/it][NeMo W 2026-06-19 09:16:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 75%|███████▌  | 7903/10519 [2:06:28<54:21,  1.25s/it][NeMo W 2026-06-19 09:16:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 75%|███████▌  | 7904/10519 [2:06:29<51:15,  1.18s/it][NeMo W 2026-06-19 09:16:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 75%|███████▌  | 7905/10519 [2:06:30<47:53,  1.10s/it][NeMo W 2026-06-19 09:16:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 75%|███████▌  | 7906/10519 [2:06:31<44:49,  1.03s/it][NeMo W 2026-06-19 09:16:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.56it/s]
 75%|███████▌  | 7907/10519 [2:06:32<44:31,  1.02s/it][NeMo W 2026-06-19 09:16:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 75%|███████▌  | 7908/10519 [2:06:33<45:49,  1.05s/it][NeMo W 2026-06-19 09:16:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 75%|███████▌  | 7909/10519 [2:06:34<44:47,  1.03s/it][NeMo W 2026-06-19 09:16:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 75%|███████▌  | 7910/10519 [2:06:35<43:12,  1.01it/s][NeMo W 2026-06-19 09:16:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 75%|███████▌  | 7911/10519 [2:06:36<43:33,  1.00s/it][NeMo W 2026-06-19 09:16:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 75%|███████▌  | 7912/10519 [2:06:37<42:48,  1.01it/s][NeMo W 2026-06-19 09:16:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.08it/s]
 75%|███████▌  | 7913/10519 [2:06:38<42:41,  1.02it/s][NeMo W 2026-06-19 09:16:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 75%|███████▌  | 7914/10519 [2:06:38<40:47,  1.06it/s][NeMo W 2026-06-19 09:16:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.98it/s]
 75%|███████▌  | 7915/10519 [2:06:39<38:23,  1.13it/s][NeMo W 2026-06-19 09:16:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 75%|███████▌  | 7916/10519 [2:06:40<38:50,  1.12it/s][NeMo W 2026-06-19 09:16:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 75%|███████▌  | 7917/10519 [2:06:41<39:53,  1.09it/s][NeMo W 2026-06-19 09:16:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 75%|███████▌  | 7918/10519 [2:06:42<40:16,  1.08it/s][NeMo W 2026-06-19 09:16:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 75%|███████▌  | 7919/10519 [2:06:43<40:21,  1.07it/s][NeMo W 2026-06-19 09:16:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 75%|███████▌  | 7920/10519 [2:06:44<40:17,  1.08it/s][NeMo W 2026-06-19 09:16:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 75%|███████▌  | 7921/10519 [2:06:45<40:25,  1.07it/s][NeMo W 2026-06-19 09:16:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 75%|███████▌  | 7922/10519 [2:06:46<38:01,  1.14it/s][NeMo W 2026-06-19 09:16:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 75%|███████▌  | 7923/10519 [2:06:46<35:35,  1.22it/s][NeMo W 2026-06-19 09:16:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 75%|███████▌  | 7924/10519 [2:06:47<35:22,  1.22it/s][NeMo W 2026-06-19 09:16:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 75%|███████▌  | 7925/10519 [2:06:48<36:47,  1.18it/s][NeMo W 2026-06-19 09:16:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 75%|███████▌  | 7926/10519 [2:06:49<38:24,  1.13it/s][NeMo W 2026-06-19 09:16:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 75%|███████▌  | 7927/10519 [2:06:50<38:56,  1.11it/s][NeMo W 2026-06-19 09:16:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 75%|███████▌  | 7928/10519 [2:06:51<39:38,  1.09it/s][NeMo W 2026-06-19 09:16:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 75%|███████▌  | 7929/10519 [2:06:52<40:13,  1.07it/s][NeMo W 2026-06-19 09:16:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]

Checkpoint saved: 7950 samples

[NeMo W 2026-06-19 09:16:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 76%|███████▌  | 7951/10519 [2:07:15<52:34,  1.23s/it][NeMo W 2026-06-19 09:16:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 76%|███████▌  | 7952/10519 [2:07:16<48:43,  1.14s/it][NeMo W 2026-06-19 09:16:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 76%|███████▌  | 7953/10519 [2:07:17<44:11,  1.03s/it][NeMo W 2026-06-19 09:16:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 76%|███████▌  | 7954/10519 [2:07:18<40:30,  1.06it/s][NeMo W 2026-06-19 09:16:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:16:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 76%|███████▌  | 7955/10519 [2:07:19<40:10,  1.06it/s][NeMo W 2026-06-19 09:17:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 76%|███████▌  | 7956/10519 [2:07:20<42:59,  1.01s/it][NeMo W 2026-06-19 09:17:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.49it/s]
 76%|███████▌  | 7957/10519 [2:07:21<41:32,  1.03it/s][NeMo W 2026-06-19 09:17:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 76%|███████▌  | 7958/10519 [2:07:22<41:02,  1.04it/s][NeMo W 2026-06-19 09:17:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 76%|███████▌  | 7959/10519 [2:07:23<45:12,  1.06s/it][NeMo W 2026-06-19 09:17:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.22it/s]
 76%|███████▌  | 7960/10519 [2:07:24<41:37,  1.02it/s][NeMo W 2026-06-19 09:17:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 76%|███████▌  | 7961/10519 [2:07:25<41:31,  1.03it/s][NeMo W 2026-06-19 09:17:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 76%|███████▌  | 7962/10519 [2:07:26<41:28,  1.03it/s][NeMo W 2026-06-19 09:17:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 76%|███████▌  | 7963/10519 [2:07:27<40:28,  1.05it/s][NeMo W 2026-06-19 09:17:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 76%|███████▌  | 7964/10519 [2:07:27<38:07,  1.12it/s][NeMo W 2026-06-19 09:17:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 76%|███████▌  | 7965/10519 [2:07:29<42:05,  1.01it/s][NeMo W 2026-06-19 09:17:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.54it/s]
 76%|███████▌  | 7966/10519 [2:07:29<41:31,  1.02it/s][NeMo W 2026-06-19 09:17:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.08it/s]
 76%|███████▌  | 7967/10519 [2:07:31<42:27,  1.00it/s][NeMo W 2026-06-19 09:17:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 76%|███████▌  | 7968/10519 [2:07:32<43:59,  1.03s/it][NeMo W 2026-06-19 09:17:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 76%|███████▌  | 7969/10519 [2:07:33<42:54,  1.01s/it][NeMo W 2026-06-19 09:17:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 76%|███████▌  | 7970/10519 [2:07:34<41:58,  1.01it/s][NeMo W 2026-06-19 09:17:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 76%|███████▌  | 7971/10519 [2:07:34<40:52,  1.04it/s][NeMo W 2026-06-19 09:17:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.82it/s]
 76%|███████▌  | 7972/10519 [2:07:35<40:55,  1.04it/s][NeMo W 2026-06-19 09:17:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 76%|███████▌  | 7973/10519 [2:07:36<40:16,  1.05it/s][NeMo W 2026-06-19 09:17:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 76%|███████▌  | 7974/10519 [2:07:37<40:19,  1.05it/s][NeMo W 2026-06-19 09:17:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 76%|███████▌  | 7975/10519 [2:07:38<37:41,  1.12it/s][NeMo W 2026-06-19 09:17:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 76%|███████▌  | 7976/10519 [2:07:39<39:48,  1.06it/s][NeMo W 2026-06-19 09:17:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 76%|███████▌  | 7977/10519 [2:07:40<41:01,  1.03it/s][NeMo W 2026-06-19 09:17:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 76%|███████▌  | 7978/10519 [2:07:41<40:28,  1.05it/s][NeMo W 2026-06-19 09:17:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 76%|███████▌  | 7979/10519 [2:07:42<42:45,  1.01s/it][NeMo W 2026-06-19 09:17:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.91it/s]

Checkpoint saved: 8000 samples

[NeMo W 2026-06-19 09:17:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 76%|███████▌  | 8001/10519 [2:08:04<49:44,  1.19s/it][NeMo W 2026-06-19 09:17:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 76%|███████▌  | 8002/10519 [2:08:05<46:10,  1.10s/it][NeMo W 2026-06-19 09:17:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 76%|███████▌  | 8003/10519 [2:08:06<44:58,  1.07s/it][NeMo W 2026-06-19 09:17:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 76%|███████▌  | 8004/10519 [2:08:07<42:55,  1.02s/it][NeMo W 2026-06-19 09:17:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 76%|███████▌  | 8005/10519 [2:08:08<41:05,  1.02it/s][NeMo W 2026-06-19 09:17:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.11it/s]
 76%|███████▌  | 8006/10519 [2:08:08<38:33,  1.09it/s][NeMo W 2026-06-19 09:17:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 76%|███████▌  | 8007/10519 [2:08:09<39:07,  1.07it/s][NeMo W 2026-06-19 09:17:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 76%|███████▌  | 8008/10519 [2:08:10<38:38,  1.08it/s][NeMo W 2026-06-19 09:17:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 76%|███████▌  | 8009/10519 [2:08:11<38:47,  1.08it/s][NeMo W 2026-06-19 09:17:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 76%|███████▌  | 8010/10519 [2:08:12<36:30,  1.15it/s][NeMo W 2026-06-19 09:17:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.55it/s]
 76%|███████▌  | 8011/10519 [2:08:13<43:07,  1.03s/it][NeMo W 2026-06-19 09:17:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 76%|███████▌  | 8012/10519 [2:08:14<42:01,  1.01s/it][NeMo W 2026-06-19 09:17:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:17:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 76%|███████▌  | 8013/10519 [2:08:18<1:22:14,  1.97s/it][NeMo W 2026-06-19 09:18:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 76%|███████▌  | 8014/10519 [2:08:19<1:08:59,  1.65s/it][NeMo W 2026-06-19 09:18:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.38it/s]
 76%|███████▌  | 8015/10519 [2:08:20<59:50,  1.43s/it]  [NeMo W 2026-06-19 09:18:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 76%|███████▌  | 8016/10519 [2:08:21<50:40,  1.21s/it][NeMo W 2026-06-19 09:18:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 76%|███████▌  | 8017/10519 [2:08:22<47:46,  1.15s/it][NeMo W 2026-06-19 09:18:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 76%|███████▌  | 8018/10519 [2:08:25<1:05:06,  1.56s/it][NeMo W 2026-06-19 09:18:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 76%|███████▌  | 8019/10519 [2:08:25<57:05,  1.37s/it]  [NeMo W 2026-06-19 09:18:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.54it/s]
 76%|███████▌  | 8020/10519 [2:08:26<50:54,  1.22s/it][NeMo W 2026-06-19 09:18:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.37it/s]
 76%|███████▋  | 8021/10519 [2:08:27<46:56,  1.13s/it][NeMo W 2026-06-19 09:18:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 76%|███████▋  | 8022/10519 [2:08:28<44:14,  1.06s/it][NeMo W 2026-06-19 09:18:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 76%|███████▋  | 8023/10519 [2:08:29<42:58,  1.03s/it][NeMo W 2026-06-19 09:18:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 76%|███████▋  | 8024/10519 [2:08:30<42:43,  1.03s/it][NeMo W 2026-06-19 09:18:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 76%|███████▋  | 8025/10519 [2:08:31<41:22,  1.00it/s][NeMo W 2026-06-19 09:18:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 76%|███████▋  | 8026/10519 [2:08:32<42:03,  1.01s/it][NeMo W 2026-06-19 09:18:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 76%|███████▋  | 8027/10519 [2:08:33<40:55,  1.01it/s][NeMo W 2026-06-19 09:18:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.26it/s]
 76%|███████▋  | 8028/10519 [2:08:34<40:54,  1.01it/s][NeMo W 2026-06-19 09:18:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 76%|███████▋  | 8029/10519 [2:08:35<39:50,  1.04it/s][NeMo W 2026-06-19 09:18:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 76%|███████▋  | 8030/10519 [2:08:36<37:28,  1.11it/s][NeMo W 2026-06-19 09:18:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8050 samples

[NeMo W 2026-06-19 09:18:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 77%|███████▋  | 8051/10519 [2:08:56<51:04,  1.24s/it][NeMo W 2026-06-19 09:18:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.09it/s]
 77%|███████▋  | 8052/10519 [2:08:57<49:02,  1.19s/it][NeMo W 2026-06-19 09:18:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 77%|███████▋  | 8053/10519 [2:08:58<48:18,  1.18s/it][NeMo W 2026-06-19 09:18:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 77%|███████▋  | 8054/10519 [2:08:59<43:09,  1.05s/it][NeMo W 2026-06-19 09:18:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 77%|███████▋  | 8055/10519 [2:09:00<41:37,  1.01s/it][NeMo W 2026-06-19 09:18:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.39it/s]
 77%|███████▋  | 8056/10519 [2:09:01<41:19,  1.01s/it][NeMo W 2026-06-19 09:18:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.97it/s]
 77%|███████▋  | 8057/10519 [2:09:02<40:11,  1.02it/s][NeMo W 2026-06-19 09:18:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 77%|███████▋  | 8058/10519 [2:09:03<40:18,  1.02it/s][NeMo W 2026-06-19 09:18:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.92it/s]
 77%|███████▋  | 8059/10519 [2:09:04<39:51,  1.03it/s][NeMo W 2026-06-19 09:18:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 77%|███████▋  | 8060/10519 [2:09:05<37:22,  1.10it/s][NeMo W 2026-06-19 09:18:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 77%|███████▋  | 8061/10519 [2:09:06<39:06,  1.05it/s][NeMo W 2026-06-19 09:18:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 77%|███████▋  | 8062/10519 [2:09:07<36:31,  1.12it/s][NeMo W 2026-06-19 09:18:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 77%|███████▋  | 8063/10519 [2:09:07<36:52,  1.11it/s][NeMo W 2026-06-19 09:18:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.83it/s]
 77%|███████▋  | 8064/10519 [2:09:08<37:19,  1.10it/s][NeMo W 2026-06-19 09:18:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 77%|███████▋  | 8065/10519 [2:09:09<34:51,  1.17it/s][NeMo W 2026-06-19 09:18:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 77%|███████▋  | 8066/10519 [2:09:10<34:35,  1.18it/s][NeMo W 2026-06-19 09:18:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 77%|███████▋  | 8067/10519 [2:09:11<33:39,  1.21it/s][NeMo W 2026-06-19 09:18:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 77%|███████▋  | 8068/10519 [2:09:12<35:15,  1.16it/s][NeMo W 2026-06-19 09:18:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 77%|███████▋  | 8069/10519 [2:09:13<36:37,  1.11it/s][NeMo W 2026-06-19 09:18:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.23it/s]
 77%|███████▋  | 8070/10519 [2:09:14<37:26,  1.09it/s][NeMo W 2026-06-19 09:18:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 77%|███████▋  | 8071/10519 [2:09:15<37:49,  1.08it/s][NeMo W 2026-06-19 09:18:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 77%|███████▋  | 8072/10519 [2:09:15<35:36,  1.15it/s][NeMo W 2026-06-19 09:18:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 77%|███████▋  | 8073/10519 [2:09:16<36:21,  1.12it/s][NeMo W 2026-06-19 09:18:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.32it/s]
 77%|███████▋  | 8074/10519 [2:09:17<36:33,  1.11it/s][NeMo W 2026-06-19 09:18:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:18:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 77%|███████▋  | 8075/10519 [2:09:18<33:53,  1.20it/s][NeMo W 2026-06-19 09:19:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 77%|███████▋  | 8076/10519 [2:09:19<35:14,  1.16it/s][NeMo W 2026-06-19 09:19:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 77%|███████▋  | 8077/10519 [2:09:20<37:04,  1.10it/s][NeMo W 2026-06-19 09:19:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 77%|███████▋  | 8078/10519 [2:09:21<37:34,  1.08it/s][NeMo W 2026-06-19 09:19:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 77%|███████▋  | 8079/10519 [2:09:22<37:03,  1.10it/s][NeMo W 2026-06-19 09:19:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]

Checkpoint saved: 8100 samples

[NeMo W 2026-06-19 09:19:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 77%|███████▋  | 8101/10519 [2:09:44<49:34,  1.23s/it][NeMo W 2026-06-19 09:19:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.30it/s]
 77%|███████▋  | 8102/10519 [2:09:45<49:22,  1.23s/it][NeMo W 2026-06-19 09:19:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.81it/s]
 77%|███████▋  | 8103/10519 [2:09:46<45:05,  1.12s/it][NeMo W 2026-06-19 09:19:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 77%|███████▋  | 8104/10519 [2:09:46<40:42,  1.01s/it][NeMo W 2026-06-19 09:19:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 77%|███████▋  | 8105/10519 [2:09:47<39:29,  1.02it/s][NeMo W 2026-06-19 09:19:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 77%|███████▋  | 8106/10519 [2:09:48<39:20,  1.02it/s][NeMo W 2026-06-19 09:19:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 77%|███████▋  | 8107/10519 [2:09:49<38:25,  1.05it/s][NeMo W 2026-06-19 09:19:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 77%|███████▋  | 8108/10519 [2:09:50<38:09,  1.05it/s][NeMo W 2026-06-19 09:19:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 77%|███████▋  | 8109/10519 [2:09:51<37:52,  1.06it/s][NeMo W 2026-06-19 09:19:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 77%|███████▋  | 8110/10519 [2:09:52<37:45,  1.06it/s][NeMo W 2026-06-19 09:19:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 77%|███████▋  | 8111/10519 [2:09:53<38:31,  1.04it/s][NeMo W 2026-06-19 09:19:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 77%|███████▋  | 8112/10519 [2:09:54<38:07,  1.05it/s][NeMo W 2026-06-19 09:19:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 77%|███████▋  | 8113/10519 [2:09:55<37:31,  1.07it/s][NeMo W 2026-06-19 09:19:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.38it/s]
 77%|███████▋  | 8114/10519 [2:09:56<38:26,  1.04it/s][NeMo W 2026-06-19 09:19:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 77%|███████▋  | 8115/10519 [2:09:57<38:10,  1.05it/s][NeMo W 2026-06-19 09:19:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.39it/s]
 77%|███████▋  | 8116/10519 [2:09:58<39:18,  1.02it/s][NeMo W 2026-06-19 09:19:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 77%|███████▋  | 8117/10519 [2:09:59<38:58,  1.03it/s][NeMo W 2026-06-19 09:19:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.02it/s]
 77%|███████▋  | 8118/10519 [2:10:00<38:12,  1.05it/s][NeMo W 2026-06-19 09:19:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 77%|███████▋  | 8119/10519 [2:10:01<38:11,  1.05it/s][NeMo W 2026-06-19 09:19:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 77%|███████▋  | 8120/10519 [2:10:02<37:59,  1.05it/s][NeMo W 2026-06-19 09:19:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 77%|███████▋  | 8121/10519 [2:10:02<35:39,  1.12it/s][NeMo W 2026-06-19 09:19:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 77%|███████▋  | 8122/10519 [2:10:03<36:09,  1.10it/s][NeMo W 2026-06-19 09:19:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 77%|███████▋  | 8123/10519 [2:10:04<35:47,  1.12it/s][NeMo W 2026-06-19 09:19:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 77%|███████▋  | 8124/10519 [2:10:05<35:26,  1.13it/s][NeMo W 2026-06-19 09:19:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 77%|███████▋  | 8125/10519 [2:10:06<32:53,  1.21it/s][NeMo W 2026-06-19 09:19:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.19it/s]
 77%|███████▋  | 8126/10519 [2:10:07<34:38,  1.15it/s][NeMo W 2026-06-19 09:19:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 77%|███████▋  | 8127/10519 [2:10:08<35:28,  1.12it/s][NeMo W 2026-06-19 09:19:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 77%|███████▋  | 8128/10519 [2:10:09<34:36,  1.15it/s][NeMo W 2026-06-19 09:19:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 77%|███████▋  | 8129/10519 [2:10:09<35:40,  1.12it/s][NeMo W 2026-06-19 09:19:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:19:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]

Checkpoint saved: 8150 samples

[NeMo W 2026-06-19 09:20:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 77%|███████▋  | 8151/10519 [2:10:32<47:19,  1.20s/it][NeMo W 2026-06-19 09:20:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.72it/s]
 77%|███████▋  | 8152/10519 [2:10:33<44:32,  1.13s/it][NeMo W 2026-06-19 09:20:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 78%|███████▊  | 8153/10519 [2:10:34<42:25,  1.08s/it][NeMo W 2026-06-19 09:20:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 78%|███████▊  | 8154/10519 [2:10:35<38:42,  1.02it/s][NeMo W 2026-06-19 09:20:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 78%|███████▊  | 8155/10519 [2:10:36<40:02,  1.02s/it][NeMo W 2026-06-19 09:20:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 78%|███████▊  | 8156/10519 [2:10:37<39:19,  1.00it/s][NeMo W 2026-06-19 09:20:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 78%|███████▊  | 8157/10519 [2:10:38<36:31,  1.08it/s][NeMo W 2026-06-19 09:20:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 78%|███████▊  | 8158/10519 [2:10:38<35:05,  1.12it/s][NeMo W 2026-06-19 09:20:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 78%|███████▊  | 8159/10519 [2:10:39<35:51,  1.10it/s][NeMo W 2026-06-19 09:20:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 78%|███████▊  | 8160/10519 [2:10:40<36:19,  1.08it/s][NeMo W 2026-06-19 09:20:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 78%|███████▊  | 8161/10519 [2:10:41<36:33,  1.07it/s][NeMo W 2026-06-19 09:20:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 78%|███████▊  | 8162/10519 [2:10:42<37:25,  1.05it/s][NeMo W 2026-06-19 09:20:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 78%|███████▊  | 8163/10519 [2:10:43<37:28,  1.05it/s][NeMo W 2026-06-19 09:20:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.75it/s]
 78%|███████▊  | 8164/10519 [2:10:44<34:15,  1.15it/s][NeMo W 2026-06-19 09:20:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 78%|███████▊  | 8165/10519 [2:10:45<34:54,  1.12it/s][NeMo W 2026-06-19 09:20:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 78%|███████▊  | 8166/10519 [2:10:46<34:28,  1.14it/s][NeMo W 2026-06-19 09:20:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 78%|███████▊  | 8167/10519 [2:10:47<35:29,  1.10it/s][NeMo W 2026-06-19 09:20:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 78%|███████▊  | 8168/10519 [2:10:48<36:30,  1.07it/s][NeMo W 2026-06-19 09:20:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.25it/s]
 78%|███████▊  | 8169/10519 [2:10:49<36:29,  1.07it/s][NeMo W 2026-06-19 09:20:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.93it/s]
 78%|███████▊  | 8170/10519 [2:10:50<37:02,  1.06it/s][NeMo W 2026-06-19 09:20:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 78%|███████▊  | 8171/10519 [2:10:51<37:08,  1.05it/s][NeMo W 2026-06-19 09:20:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 78%|███████▊  | 8172/10519 [2:10:51<36:43,  1.07it/s][NeMo W 2026-06-19 09:20:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.73it/s]
 78%|███████▊  | 8173/10519 [2:10:52<37:36,  1.04it/s][NeMo W 2026-06-19 09:20:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.55it/s]
 78%|███████▊  | 8174/10519 [2:10:53<35:57,  1.09it/s][NeMo W 2026-06-19 09:20:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 78%|███████▊  | 8175/10519 [2:10:54<36:23,  1.07it/s][NeMo W 2026-06-19 09:20:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 78%|███████▊  | 8176/10519 [2:10:55<34:29,  1.13it/s][NeMo W 2026-06-19 09:20:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 78%|███████▊  | 8177/10519 [2:10:56<35:35,  1.10it/s][NeMo W 2026-06-19 09:20:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 78%|███████▊  | 8178/10519 [2:10:57<33:41,  1.16it/s][NeMo W 2026-06-19 09:20:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 78%|███████▊  | 8179/10519 [2:10:58<34:14,  1.14it/s][NeMo W 2026-06-19 09:20:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:20:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.08it/s]

Checkpoint saved: 8200 samples

[NeMo W 2026-06-19 09:21:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.54it/s]
 78%|███████▊  | 8201/10519 [2:11:20<50:43,  1.31s/it][NeMo W 2026-06-19 09:21:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 78%|███████▊  | 8202/10519 [2:11:21<46:50,  1.21s/it][NeMo W 2026-06-19 09:21:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 78%|███████▊  | 8203/10519 [2:11:22<43:48,  1.13s/it][NeMo W 2026-06-19 09:21:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 78%|███████▊  | 8204/10519 [2:11:23<41:48,  1.08s/it][NeMo W 2026-06-19 09:21:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 78%|███████▊  | 8205/10519 [2:11:24<40:50,  1.06s/it][NeMo W 2026-06-19 09:21:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 78%|███████▊  | 8206/10519 [2:11:24<39:28,  1.02s/it][NeMo W 2026-06-19 09:21:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 78%|███████▊  | 8207/10519 [2:11:25<38:29,  1.00it/s][NeMo W 2026-06-19 09:21:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 78%|███████▊  | 8208/10519 [2:11:26<34:59,  1.10it/s][NeMo W 2026-06-19 09:21:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 78%|███████▊  | 8209/10519 [2:11:27<37:05,  1.04it/s][NeMo W 2026-06-19 09:21:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]
 78%|███████▊  | 8210/10519 [2:11:28<37:05,  1.04it/s][NeMo W 2026-06-19 09:21:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 78%|███████▊  | 8211/10519 [2:11:29<36:10,  1.06it/s][NeMo W 2026-06-19 09:21:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 78%|███████▊  | 8212/10519 [2:11:30<35:27,  1.08it/s][NeMo W 2026-06-19 09:21:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 78%|███████▊  | 8213/10519 [2:11:31<35:54,  1.07it/s][NeMo W 2026-06-19 09:21:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 78%|███████▊  | 8214/10519 [2:11:32<38:38,  1.01s/it][NeMo W 2026-06-19 09:21:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.86it/s]
 78%|███████▊  | 8215/10519 [2:11:33<38:21,  1.00it/s][NeMo W 2026-06-19 09:21:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.23it/s]
 78%|███████▊  | 8216/10519 [2:11:34<37:35,  1.02it/s][NeMo W 2026-06-19 09:21:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.57it/s]
 78%|███████▊  | 8217/10519 [2:11:35<36:35,  1.05it/s][NeMo W 2026-06-19 09:21:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 78%|███████▊  | 8218/10519 [2:11:36<36:29,  1.05it/s][NeMo W 2026-06-19 09:21:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 78%|███████▊  | 8219/10519 [2:11:37<37:01,  1.04it/s][NeMo W 2026-06-19 09:21:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 78%|███████▊  | 8220/10519 [2:11:38<36:15,  1.06it/s][NeMo W 2026-06-19 09:21:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 78%|███████▊  | 8221/10519 [2:11:39<37:35,  1.02it/s][NeMo W 2026-06-19 09:21:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 78%|███████▊  | 8222/10519 [2:11:40<36:49,  1.04it/s][NeMo W 2026-06-19 09:21:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 78%|███████▊  | 8223/10519 [2:11:41<36:17,  1.05it/s][NeMo W 2026-06-19 09:21:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]
 78%|███████▊  | 8224/10519 [2:11:42<41:11,  1.08s/it][NeMo W 2026-06-19 09:21:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 78%|███████▊  | 8225/10519 [2:11:43<39:25,  1.03s/it][NeMo W 2026-06-19 09:21:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 78%|███████▊  | 8226/10519 [2:11:44<38:41,  1.01s/it][NeMo W 2026-06-19 09:21:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.85it/s]
 78%|███████▊  | 8227/10519 [2:11:45<38:29,  1.01s/it][NeMo W 2026-06-19 09:21:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.57it/s]
 78%|███████▊  | 8228/10519 [2:11:46<38:08,  1.00it/s][NeMo W 2026-06-19 09:21:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 78%|███████▊  | 8229/10519 [2:11:47<37:55,  1.01it/s][NeMo W 2026-06-19 09:21:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]

Checkpoint saved: 8250 samples

[NeMo W 2026-06-19 09:21:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.57it/s]
 78%|███████▊  | 8251/10519 [2:12:09<46:08,  1.22s/it][NeMo W 2026-06-19 09:21:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
 78%|███████▊  | 8252/10519 [2:12:09<40:33,  1.07s/it][NeMo W 2026-06-19 09:21:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.51it/s]
 78%|███████▊  | 8253/10519 [2:12:10<38:51,  1.03s/it][NeMo W 2026-06-19 09:21:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 78%|███████▊  | 8254/10519 [2:12:11<36:13,  1.04it/s][NeMo W 2026-06-19 09:21:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 78%|███████▊  | 8255/10519 [2:12:12<37:28,  1.01it/s][NeMo W 2026-06-19 09:21:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 78%|███████▊  | 8256/10519 [2:12:13<36:53,  1.02it/s][NeMo W 2026-06-19 09:21:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 78%|███████▊  | 8257/10519 [2:12:14<37:56,  1.01s/it][NeMo W 2026-06-19 09:21:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 79%|███████▊  | 8258/10519 [2:12:15<37:09,  1.01it/s][NeMo W 2026-06-19 09:21:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 79%|███████▊  | 8259/10519 [2:12:16<34:19,  1.10it/s][NeMo W 2026-06-19 09:21:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 79%|███████▊  | 8260/10519 [2:12:17<34:40,  1.09it/s][NeMo W 2026-06-19 09:21:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:21:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 79%|███████▊  | 8261/10519 [2:12:18<34:26,  1.09it/s][NeMo W 2026-06-19 09:22:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 79%|███████▊  | 8262/10519 [2:12:19<35:32,  1.06it/s][NeMo W 2026-06-19 09:22:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 79%|███████▊  | 8263/10519 [2:12:20<35:01,  1.07it/s][NeMo W 2026-06-19 09:22:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 79%|███████▊  | 8264/10519 [2:12:20<32:18,  1.16it/s][NeMo W 2026-06-19 09:22:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 79%|███████▊  | 8265/10519 [2:12:21<30:24,  1.24it/s][NeMo W 2026-06-19 09:22:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 79%|███████▊  | 8266/10519 [2:12:22<31:38,  1.19it/s][NeMo W 2026-06-19 09:22:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.81it/s]
 79%|███████▊  | 8267/10519 [2:12:23<35:03,  1.07it/s][NeMo W 2026-06-19 09:22:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 79%|███████▊  | 8268/10519 [2:12:24<35:08,  1.07it/s][NeMo W 2026-06-19 09:22:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 79%|███████▊  | 8269/10519 [2:12:25<35:04,  1.07it/s][NeMo W 2026-06-19 09:22:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.28it/s]
 79%|███████▊  | 8270/10519 [2:12:26<35:27,  1.06it/s][NeMo W 2026-06-19 09:22:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 79%|███████▊  | 8271/10519 [2:12:27<35:53,  1.04it/s][NeMo W 2026-06-19 09:22:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 79%|███████▊  | 8272/10519 [2:12:28<35:34,  1.05it/s][NeMo W 2026-06-19 09:22:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 79%|███████▊  | 8273/10519 [2:12:29<35:30,  1.05it/s][NeMo W 2026-06-19 09:22:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 79%|███████▊  | 8274/10519 [2:12:30<35:18,  1.06it/s][NeMo W 2026-06-19 09:22:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 79%|███████▊  | 8275/10519 [2:12:31<35:29,  1.05it/s][NeMo W 2026-06-19 09:22:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.39it/s]
 79%|███████▊  | 8276/10519 [2:12:32<34:30,  1.08it/s][NeMo W 2026-06-19 09:22:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.84it/s]
 79%|███████▊  | 8277/10519 [2:12:32<32:50,  1.14it/s][NeMo W 2026-06-19 09:22:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 79%|███████▊  | 8278/10519 [2:12:33<33:32,  1.11it/s][NeMo W 2026-06-19 09:22:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 79%|███████▊  | 8279/10519 [2:12:34<33:40,  1.11it/s][NeMo W 2026-06-19 09:22:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.45it/s]
 79%|███████▊  | 8280/10519 [2:12:35<31:33,  1.18it/s][NeMo W 2026-06-19 09:22:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8300 samples

[NeMo W 2026-06-19 09:22:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 79%|███████▉  | 8301/10519 [2:12:56<47:31,  1.29s/it][NeMo W 2026-06-19 09:22:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 79%|███████▉  | 8302/10519 [2:12:57<43:47,  1.19s/it][NeMo W 2026-06-19 09:22:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 79%|███████▉  | 8303/10519 [2:12:58<40:53,  1.11s/it][NeMo W 2026-06-19 09:22:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 79%|███████▉  | 8304/10519 [2:12:59<39:43,  1.08s/it][NeMo W 2026-06-19 09:22:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.44it/s]
 79%|███████▉  | 8305/10519 [2:13:00<38:09,  1.03s/it][NeMo W 2026-06-19 09:22:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.29it/s]
 79%|███████▉  | 8306/10519 [2:13:00<36:12,  1.02it/s][NeMo W 2026-06-19 09:22:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 79%|███████▉  | 8307/10519 [2:13:01<35:07,  1.05it/s][NeMo W 2026-06-19 09:22:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 79%|███████▉  | 8308/10519 [2:13:02<33:03,  1.11it/s][NeMo W 2026-06-19 09:22:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 79%|███████▉  | 8309/10519 [2:13:03<33:49,  1.09it/s][NeMo W 2026-06-19 09:22:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 79%|███████▉  | 8310/10519 [2:13:04<34:24,  1.07it/s][NeMo W 2026-06-19 09:22:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 79%|███████▉  | 8311/10519 [2:13:05<34:18,  1.07it/s][NeMo W 2026-06-19 09:22:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 79%|███████▉  | 8312/10519 [2:13:06<36:01,  1.02it/s][NeMo W 2026-06-19 09:22:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.09it/s]
 79%|███████▉  | 8313/10519 [2:13:07<35:48,  1.03it/s][NeMo W 2026-06-19 09:22:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 79%|███████▉  | 8314/10519 [2:13:08<35:19,  1.04it/s][NeMo W 2026-06-19 09:22:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 79%|███████▉  | 8315/10519 [2:13:09<32:36,  1.13it/s][NeMo W 2026-06-19 09:22:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 79%|███████▉  | 8316/10519 [2:13:10<33:21,  1.10it/s][NeMo W 2026-06-19 09:22:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 79%|███████▉  | 8317/10519 [2:13:10<31:35,  1.16it/s][NeMo W 2026-06-19 09:22:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 79%|███████▉  | 8318/10519 [2:13:11<33:22,  1.10it/s][NeMo W 2026-06-19 09:22:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 79%|███████▉  | 8319/10519 [2:13:12<33:40,  1.09it/s][NeMo W 2026-06-19 09:22:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 79%|███████▉  | 8320/10519 [2:13:13<34:17,  1.07it/s][NeMo W 2026-06-19 09:22:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 79%|███████▉  | 8321/10519 [2:13:14<35:54,  1.02it/s][NeMo W 2026-06-19 09:22:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 79%|███████▉  | 8322/10519 [2:13:15<35:17,  1.04it/s][NeMo W 2026-06-19 09:22:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 79%|███████▉  | 8323/10519 [2:13:16<33:27,  1.09it/s][NeMo W 2026-06-19 09:22:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 79%|███████▉  | 8324/10519 [2:13:17<31:19,  1.17it/s][NeMo W 2026-06-19 09:22:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 79%|███████▉  | 8325/10519 [2:13:17<29:41,  1.23it/s][NeMo W 2026-06-19 09:22:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:22:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.58it/s]
 79%|███████▉  | 8326/10519 [2:13:18<30:30,  1.20it/s][NeMo W 2026-06-19 09:23:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 79%|███████▉  | 8327/10519 [2:13:19<32:03,  1.14it/s][NeMo W 2026-06-19 09:23:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 79%|███████▉  | 8328/10519 [2:13:20<33:08,  1.10it/s][NeMo W 2026-06-19 09:23:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.18it/s]
 79%|███████▉  | 8329/10519 [2:13:21<31:17,  1.17it/s][NeMo W 2026-06-19 09:23:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 79%|███████▉  | 8330/10519 [2:13:22<31:09,  1.17it/s][NeMo W 2026-06-19 09:23:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8350 samples

[NeMo W 2026-06-19 09:23:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 79%|███████▉  | 8351/10519 [2:13:42<40:10,  1.11s/it][NeMo W 2026-06-19 09:23:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 79%|███████▉  | 8352/10519 [2:13:43<38:10,  1.06s/it][NeMo W 2026-06-19 09:23:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 79%|███████▉  | 8353/10519 [2:13:44<37:15,  1.03s/it][NeMo W 2026-06-19 09:23:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 79%|███████▉  | 8354/10519 [2:13:44<35:58,  1.00it/s][NeMo W 2026-06-19 09:23:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.74it/s]
 79%|███████▉  | 8355/10519 [2:13:45<36:00,  1.00it/s][NeMo W 2026-06-19 09:23:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 79%|███████▉  | 8356/10519 [2:13:46<36:02,  1.00it/s][NeMo W 2026-06-19 09:23:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.55it/s]
 79%|███████▉  | 8357/10519 [2:13:47<35:47,  1.01it/s][NeMo W 2026-06-19 09:23:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.17it/s]
 79%|███████▉  | 8358/10519 [2:13:48<35:49,  1.01it/s][NeMo W 2026-06-19 09:23:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 79%|███████▉  | 8359/10519 [2:13:49<35:21,  1.02it/s][NeMo W 2026-06-19 09:23:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 79%|███████▉  | 8360/10519 [2:13:51<38:28,  1.07s/it][NeMo W 2026-06-19 09:23:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 79%|███████▉  | 8361/10519 [2:13:52<37:43,  1.05s/it][NeMo W 2026-06-19 09:23:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 79%|███████▉  | 8362/10519 [2:13:53<36:36,  1.02s/it][NeMo W 2026-06-19 09:23:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 80%|███████▉  | 8363/10519 [2:13:54<35:31,  1.01it/s][NeMo W 2026-06-19 09:23:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 80%|███████▉  | 8364/10519 [2:13:55<35:57,  1.00s/it][NeMo W 2026-06-19 09:23:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 80%|███████▉  | 8365/10519 [2:13:55<35:10,  1.02it/s][NeMo W 2026-06-19 09:23:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 80%|███████▉  | 8366/10519 [2:13:56<32:17,  1.11it/s][NeMo W 2026-06-19 09:23:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 80%|███████▉  | 8367/10519 [2:13:57<32:28,  1.10it/s][NeMo W 2026-06-19 09:23:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 80%|███████▉  | 8368/10519 [2:13:58<32:46,  1.09it/s][NeMo W 2026-06-19 09:23:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 80%|███████▉  | 8369/10519 [2:13:59<30:44,  1.17it/s][NeMo W 2026-06-19 09:23:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.39it/s]
 80%|███████▉  | 8370/10519 [2:14:00<31:34,  1.13it/s][NeMo W 2026-06-19 09:23:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 80%|███████▉  | 8371/10519 [2:14:01<32:34,  1.10it/s][NeMo W 2026-06-19 09:23:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 80%|███████▉  | 8372/10519 [2:14:02<31:27,  1.14it/s][NeMo W 2026-06-19 09:23:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 80%|███████▉  | 8373/10519 [2:14:02<31:26,  1.14it/s][NeMo W 2026-06-19 09:23:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 80%|███████▉  | 8374/10519 [2:14:03<31:43,  1.13it/s][NeMo W 2026-06-19 09:23:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 80%|███████▉  | 8375/10519 [2:14:04<29:42,  1.20it/s][NeMo W 2026-06-19 09:23:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.97it/s]
 80%|███████▉  | 8376/10519 [2:14:05<31:03,  1.15it/s][NeMo W 2026-06-19 09:23:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 80%|███████▉  | 8377/10519 [2:14:06<31:44,  1.12it/s][NeMo W 2026-06-19 09:23:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 80%|███████▉  | 8378/10519 [2:14:07<30:26,  1.17it/s][NeMo W 2026-06-19 09:23:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 80%|███████▉  | 8379/10519 [2:14:08<31:13,  1.14it/s][NeMo W 2026-06-19 09:23:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:23:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]

Checkpoint saved: 8400 samples

[NeMo W 2026-06-19 09:24:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 80%|███████▉  | 8401/10519 [2:14:30<48:30,  1.37s/it][NeMo W 2026-06-19 09:24:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 80%|███████▉  | 8402/10519 [2:14:31<43:41,  1.24s/it][NeMo W 2026-06-19 09:24:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 80%|███████▉  | 8403/10519 [2:14:32<40:28,  1.15s/it][NeMo W 2026-06-19 09:24:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 80%|███████▉  | 8404/10519 [2:14:33<39:08,  1.11s/it][NeMo W 2026-06-19 09:24:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 80%|███████▉  | 8405/10519 [2:14:34<37:04,  1.05s/it][NeMo W 2026-06-19 09:24:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.77it/s]
 80%|███████▉  | 8406/10519 [2:14:35<36:19,  1.03s/it][NeMo W 2026-06-19 09:24:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.19it/s]
 80%|███████▉  | 8407/10519 [2:14:36<34:57,  1.01it/s][NeMo W 2026-06-19 09:24:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.75it/s]
 80%|███████▉  | 8408/10519 [2:14:37<38:14,  1.09s/it][NeMo W 2026-06-19 09:24:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 80%|███████▉  | 8409/10519 [2:14:38<35:22,  1.01s/it][NeMo W 2026-06-19 09:24:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 80%|███████▉  | 8410/10519 [2:14:39<36:36,  1.04s/it][NeMo W 2026-06-19 09:24:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.59it/s]
 80%|███████▉  | 8411/10519 [2:14:40<33:33,  1.05it/s][NeMo W 2026-06-19 09:24:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 80%|███████▉  | 8412/10519 [2:14:41<36:10,  1.03s/it][NeMo W 2026-06-19 09:24:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 80%|███████▉  | 8413/10519 [2:14:42<35:24,  1.01s/it][NeMo W 2026-06-19 09:24:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 80%|███████▉  | 8414/10519 [2:14:43<36:02,  1.03s/it][NeMo W 2026-06-19 09:24:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 80%|███████▉  | 8415/10519 [2:14:44<35:45,  1.02s/it][NeMo W 2026-06-19 09:24:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 80%|████████  | 8416/10519 [2:14:45<34:43,  1.01it/s][NeMo W 2026-06-19 09:24:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 80%|████████  | 8417/10519 [2:14:46<34:09,  1.03it/s][NeMo W 2026-06-19 09:24:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 80%|████████  | 8418/10519 [2:14:47<32:44,  1.07it/s][NeMo W 2026-06-19 09:24:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 80%|████████  | 8419/10519 [2:14:48<31:40,  1.10it/s][NeMo W 2026-06-19 09:24:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 80%|████████  | 8420/10519 [2:14:49<31:38,  1.11it/s][NeMo W 2026-06-19 09:24:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 80%|████████  | 8421/10519 [2:14:50<31:22,  1.11it/s][NeMo W 2026-06-19 09:24:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 80%|████████  | 8422/10519 [2:14:50<30:12,  1.16it/s][NeMo W 2026-06-19 09:24:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 80%|████████  | 8423/10519 [2:14:51<29:04,  1.20it/s][NeMo W 2026-06-19 09:24:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.32it/s]
 80%|████████  | 8424/10519 [2:14:52<30:43,  1.14it/s][NeMo W 2026-06-19 09:24:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.18it/s]
 80%|████████  | 8425/10519 [2:14:53<32:12,  1.08it/s][NeMo W 2026-06-19 09:24:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 80%|████████  | 8426/10519 [2:14:54<31:35,  1.10it/s][NeMo W 2026-06-19 09:24:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.70it/s]
 80%|████████  | 8427/10519 [2:14:55<32:16,  1.08it/s][NeMo W 2026-06-19 09:24:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 80%|████████  | 8428/10519 [2:14:56<32:36,  1.07it/s][NeMo W 2026-06-19 09:24:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.96it/s]
 80%|████████  | 8429/10519 [2:14:57<32:35,  1.07it/s][NeMo W 2026-06-19 09:24:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]

Checkpoint saved: 8450 samples

[NeMo W 2026-06-19 09:24:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:24:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 80%|████████  | 8451/10519 [2:15:19<39:30,  1.15s/it][NeMo W 2026-06-19 09:25:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 80%|████████  | 8452/10519 [2:15:20<37:13,  1.08s/it][NeMo W 2026-06-19 09:25:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 80%|████████  | 8453/10519 [2:15:21<36:02,  1.05s/it][NeMo W 2026-06-19 09:25:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 80%|████████  | 8454/10519 [2:15:22<34:58,  1.02s/it][NeMo W 2026-06-19 09:25:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 80%|████████  | 8455/10519 [2:15:22<31:58,  1.08it/s][NeMo W 2026-06-19 09:25:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.01it/s]
 80%|████████  | 8456/10519 [2:15:23<32:42,  1.05it/s][NeMo W 2026-06-19 09:25:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.74it/s]
 80%|████████  | 8457/10519 [2:15:24<31:52,  1.08it/s][NeMo W 2026-06-19 09:25:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 80%|████████  | 8458/10519 [2:15:25<31:41,  1.08it/s][NeMo W 2026-06-19 09:25:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 80%|████████  | 8459/10519 [2:15:26<31:36,  1.09it/s][NeMo W 2026-06-19 09:25:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 80%|████████  | 8460/10519 [2:15:27<31:48,  1.08it/s][NeMo W 2026-06-19 09:25:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 80%|████████  | 8461/10519 [2:15:28<31:38,  1.08it/s][NeMo W 2026-06-19 09:25:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 80%|████████  | 8462/10519 [2:15:29<32:23,  1.06it/s][NeMo W 2026-06-19 09:25:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.68it/s]
 80%|████████  | 8463/10519 [2:15:30<30:09,  1.14it/s][NeMo W 2026-06-19 09:25:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.46it/s]
 80%|████████  | 8464/10519 [2:15:30<30:37,  1.12it/s][NeMo W 2026-06-19 09:25:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 80%|████████  | 8465/10519 [2:15:31<30:51,  1.11it/s][NeMo W 2026-06-19 09:25:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.74it/s]
 80%|████████  | 8466/10519 [2:15:32<31:40,  1.08it/s][NeMo W 2026-06-19 09:25:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 80%|████████  | 8467/10519 [2:15:33<31:26,  1.09it/s][NeMo W 2026-06-19 09:25:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 81%|████████  | 8468/10519 [2:15:34<31:44,  1.08it/s][NeMo W 2026-06-19 09:25:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 81%|████████  | 8469/10519 [2:15:35<30:40,  1.11it/s][NeMo W 2026-06-19 09:25:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.21it/s]
 81%|████████  | 8470/10519 [2:15:36<31:05,  1.10it/s][NeMo W 2026-06-19 09:25:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.18it/s]
 81%|████████  | 8471/10519 [2:15:37<30:15,  1.13it/s][NeMo W 2026-06-19 09:25:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.40it/s]
 81%|████████  | 8472/10519 [2:15:38<37:19,  1.09s/it][NeMo W 2026-06-19 09:25:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.52it/s]
 81%|████████  | 8473/10519 [2:15:39<34:24,  1.01s/it][NeMo W 2026-06-19 09:25:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 81%|████████  | 8474/10519 [2:15:41<40:14,  1.18s/it][NeMo W 2026-06-19 09:25:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 81%|████████  | 8475/10519 [2:15:43<47:08,  1.38s/it][NeMo W 2026-06-19 09:25:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 81%|████████  | 8476/10519 [2:15:43<40:53,  1.20s/it][NeMo W 2026-06-19 09:25:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 81%|████████  | 8477/10519 [2:15:45<49:42,  1.46s/it][NeMo W 2026-06-19 09:25:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 81%|████████  | 8478/10519 [2:15:46<44:10,  1.30s/it][NeMo W 2026-06-19 09:25:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 81%|████████  | 8479/10519 [2:15:47<40:52,  1.20s/it][NeMo W 2026-06-19 09:25:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.58it/s]
 81%|████████  | 8480/10519 [2:15:48<38:51,  1.14s/it][NeMo W 2026-06-19 09:25:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8500 samples

[NeMo W 2026-06-19 09:25:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 81%|████████  | 8501/10519 [2:16:09<40:15,  1.20s/it][NeMo W 2026-06-19 09:25:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 81%|████████  | 8502/10519 [2:16:10<37:58,  1.13s/it][NeMo W 2026-06-19 09:25:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 81%|████████  | 8503/10519 [2:16:11<38:15,  1.14s/it][NeMo W 2026-06-19 09:25:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 81%|████████  | 8504/10519 [2:16:12<36:21,  1.08s/it][NeMo W 2026-06-19 09:25:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 81%|████████  | 8505/10519 [2:16:13<36:07,  1.08s/it][NeMo W 2026-06-19 09:25:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 81%|████████  | 8506/10519 [2:16:14<34:59,  1.04s/it][NeMo W 2026-06-19 09:25:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.70it/s]
 81%|████████  | 8507/10519 [2:16:15<34:03,  1.02s/it][NeMo W 2026-06-19 09:25:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.76it/s]
 81%|████████  | 8508/10519 [2:16:16<32:08,  1.04it/s][NeMo W 2026-06-19 09:25:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 81%|████████  | 8509/10519 [2:16:17<33:02,  1.01it/s][NeMo W 2026-06-19 09:25:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:25:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 81%|████████  | 8510/10519 [2:16:18<32:11,  1.04it/s][NeMo W 2026-06-19 09:26:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 81%|████████  | 8511/10519 [2:16:19<29:41,  1.13it/s][NeMo W 2026-06-19 09:26:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.18it/s]
 81%|████████  | 8512/10519 [2:16:20<31:05,  1.08it/s][NeMo W 2026-06-19 09:26:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 81%|████████  | 8513/10519 [2:16:21<31:00,  1.08it/s][NeMo W 2026-06-19 09:26:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 81%|████████  | 8514/10519 [2:16:22<32:01,  1.04it/s][NeMo W 2026-06-19 09:26:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 81%|████████  | 8515/10519 [2:16:23<30:12,  1.11it/s][NeMo W 2026-06-19 09:26:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.56it/s]
 81%|████████  | 8516/10519 [2:16:24<30:16,  1.10it/s][NeMo W 2026-06-19 09:26:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 81%|████████  | 8517/10519 [2:16:24<29:11,  1.14it/s][NeMo W 2026-06-19 09:26:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 81%|████████  | 8518/10519 [2:16:25<29:33,  1.13it/s][NeMo W 2026-06-19 09:26:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 81%|████████  | 8519/10519 [2:16:26<30:24,  1.10it/s][NeMo W 2026-06-19 09:26:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 81%|████████  | 8520/10519 [2:16:27<31:28,  1.06it/s][NeMo W 2026-06-19 09:26:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 81%|████████  | 8521/10519 [2:16:28<31:53,  1.04it/s][NeMo W 2026-06-19 09:26:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.74it/s]
 81%|████████  | 8522/10519 [2:16:29<31:39,  1.05it/s][NeMo W 2026-06-19 09:26:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 81%|████████  | 8523/10519 [2:16:30<31:07,  1.07it/s][NeMo W 2026-06-19 09:26:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 81%|████████  | 8524/10519 [2:16:31<32:11,  1.03it/s][NeMo W 2026-06-19 09:26:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 81%|████████  | 8525/10519 [2:16:32<31:38,  1.05it/s][NeMo W 2026-06-19 09:26:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 81%|████████  | 8526/10519 [2:16:33<31:42,  1.05it/s][NeMo W 2026-06-19 09:26:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 81%|████████  | 8527/10519 [2:16:34<33:20,  1.00s/it][NeMo W 2026-06-19 09:26:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 81%|████████  | 8528/10519 [2:16:35<34:34,  1.04s/it][NeMo W 2026-06-19 09:26:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 81%|████████  | 8529/10519 [2:16:36<33:04,  1.00it/s][NeMo W 2026-06-19 09:26:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 81%|████████  | 8530/10519 [2:16:37<35:21,  1.07s/it][NeMo W 2026-06-19 09:26:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8550 samples

[NeMo W 2026-06-19 09:26:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.42it/s]
 81%|████████▏ | 8551/10519 [2:16:59<42:52,  1.31s/it][NeMo W 2026-06-19 09:26:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
 81%|████████▏ | 8552/10519 [2:17:00<39:29,  1.20s/it][NeMo W 2026-06-19 09:26:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 81%|████████▏ | 8553/10519 [2:17:01<38:20,  1.17s/it][NeMo W 2026-06-19 09:26:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 81%|████████▏ | 8554/10519 [2:17:02<35:36,  1.09s/it][NeMo W 2026-06-19 09:26:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 81%|████████▏ | 8555/10519 [2:17:02<32:38,  1.00it/s][NeMo W 2026-06-19 09:26:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 81%|████████▏ | 8556/10519 [2:17:03<30:08,  1.09it/s][NeMo W 2026-06-19 09:26:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 81%|████████▏ | 8557/10519 [2:17:04<28:14,  1.16it/s][NeMo W 2026-06-19 09:26:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.30it/s]
 81%|████████▏ | 8558/10519 [2:17:05<27:12,  1.20it/s][NeMo W 2026-06-19 09:26:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 81%|████████▏ | 8559/10519 [2:17:06<29:29,  1.11it/s][NeMo W 2026-06-19 09:26:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 81%|████████▏ | 8560/10519 [2:17:07<28:15,  1.16it/s][NeMo W 2026-06-19 09:26:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 81%|████████▏ | 8561/10519 [2:17:07<28:35,  1.14it/s][NeMo W 2026-06-19 09:26:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 81%|████████▏ | 8562/10519 [2:17:08<29:25,  1.11it/s][NeMo W 2026-06-19 09:26:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 81%|████████▏ | 8563/10519 [2:17:09<30:01,  1.09it/s][NeMo W 2026-06-19 09:26:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.21it/s]
 81%|████████▏ | 8564/10519 [2:17:11<32:03,  1.02it/s][NeMo W 2026-06-19 09:26:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 81%|████████▏ | 8565/10519 [2:17:11<31:31,  1.03it/s][NeMo W 2026-06-19 09:26:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.04it/s]
 81%|████████▏ | 8566/10519 [2:17:12<31:21,  1.04it/s][NeMo W 2026-06-19 09:26:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 81%|████████▏ | 8567/10519 [2:17:13<31:19,  1.04it/s][NeMo W 2026-06-19 09:26:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 81%|████████▏ | 8568/10519 [2:17:14<31:34,  1.03it/s][NeMo W 2026-06-19 09:26:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.33it/s]
 81%|████████▏ | 8569/10519 [2:17:15<30:26,  1.07it/s][NeMo W 2026-06-19 09:26:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 81%|████████▏ | 8570/10519 [2:17:16<28:17,  1.15it/s][NeMo W 2026-06-19 09:26:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 81%|████████▏ | 8571/10519 [2:17:17<28:24,  1.14it/s][NeMo W 2026-06-19 09:26:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:26:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 81%|████████▏ | 8572/10519 [2:17:18<28:36,  1.13it/s][NeMo W 2026-06-19 09:27:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 82%|████████▏ | 8573/10519 [2:17:19<30:02,  1.08it/s][NeMo W 2026-06-19 09:27:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 82%|████████▏ | 8574/10519 [2:17:20<29:52,  1.08it/s][NeMo W 2026-06-19 09:27:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 82%|████████▏ | 8575/10519 [2:17:21<30:01,  1.08it/s][NeMo W 2026-06-19 09:27:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 82%|████████▏ | 8576/10519 [2:17:21<29:53,  1.08it/s][NeMo W 2026-06-19 09:27:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 82%|████████▏ | 8577/10519 [2:17:23<31:36,  1.02it/s][NeMo W 2026-06-19 09:27:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.30it/s]
 82%|████████▏ | 8578/10519 [2:17:24<36:30,  1.13s/it][NeMo W 2026-06-19 09:27:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 82%|████████▏ | 8579/10519 [2:17:25<35:14,  1.09s/it][NeMo W 2026-06-19 09:27:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 82%|████████▏ | 8580/10519 [2:17:26<32:05,  1.01it/s][NeMo W 2026-06-19 09:27:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8600 samples

[NeMo W 2026-06-19 09:27:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 82%|████████▏ | 8601/10519 [2:17:47<38:17,  1.20s/it][NeMo W 2026-06-19 09:27:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 82%|████████▏ | 8602/10519 [2:17:48<36:02,  1.13s/it][NeMo W 2026-06-19 09:27:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]
 82%|████████▏ | 8603/10519 [2:17:48<34:01,  1.07s/it][NeMo W 2026-06-19 09:27:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 82%|████████▏ | 8604/10519 [2:17:49<33:01,  1.03s/it][NeMo W 2026-06-19 09:27:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 82%|████████▏ | 8605/10519 [2:17:50<32:22,  1.01s/it][NeMo W 2026-06-19 09:27:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 82%|████████▏ | 8606/10519 [2:17:51<32:42,  1.03s/it][NeMo W 2026-06-19 09:27:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.28it/s]
 82%|████████▏ | 8607/10519 [2:17:52<31:21,  1.02it/s][NeMo W 2026-06-19 09:27:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 82%|████████▏ | 8608/10519 [2:17:53<30:33,  1.04it/s][NeMo W 2026-06-19 09:27:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 82%|████████▏ | 8609/10519 [2:17:54<29:56,  1.06it/s][NeMo W 2026-06-19 09:27:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 82%|████████▏ | 8610/10519 [2:17:55<30:38,  1.04it/s][NeMo W 2026-06-19 09:27:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 82%|████████▏ | 8611/10519 [2:17:56<30:34,  1.04it/s][NeMo W 2026-06-19 09:27:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 82%|████████▏ | 8612/10519 [2:17:57<31:50,  1.00s/it][NeMo W 2026-06-19 09:27:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 82%|████████▏ | 8613/10519 [2:17:58<31:10,  1.02it/s][NeMo W 2026-06-19 09:27:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 82%|████████▏ | 8614/10519 [2:17:59<30:41,  1.03it/s][NeMo W 2026-06-19 09:27:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.58it/s]
 82%|████████▏ | 8615/10519 [2:18:00<30:37,  1.04it/s][NeMo W 2026-06-19 09:27:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.15it/s]
 82%|████████▏ | 8616/10519 [2:18:01<30:21,  1.04it/s][NeMo W 2026-06-19 09:27:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 82%|████████▏ | 8617/10519 [2:18:02<30:20,  1.04it/s][NeMo W 2026-06-19 09:27:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 82%|████████▏ | 8618/10519 [2:18:03<28:26,  1.11it/s][NeMo W 2026-06-19 09:27:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 82%|████████▏ | 8619/10519 [2:18:04<28:28,  1.11it/s][NeMo W 2026-06-19 09:27:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 82%|████████▏ | 8620/10519 [2:18:05<29:07,  1.09it/s][NeMo W 2026-06-19 09:27:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 82%|████████▏ | 8621/10519 [2:18:06<30:08,  1.05it/s][NeMo W 2026-06-19 09:27:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.39it/s]
 82%|████████▏ | 8622/10519 [2:18:07<30:06,  1.05it/s][NeMo W 2026-06-19 09:27:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 82%|████████▏ | 8623/10519 [2:18:08<31:58,  1.01s/it][NeMo W 2026-06-19 09:27:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 82%|████████▏ | 8624/10519 [2:18:09<31:26,  1.00it/s][NeMo W 2026-06-19 09:27:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 82%|████████▏ | 8625/10519 [2:18:09<28:45,  1.10it/s][NeMo W 2026-06-19 09:27:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 82%|████████▏ | 8626/10519 [2:18:10<28:39,  1.10it/s][NeMo W 2026-06-19 09:27:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 82%|████████▏ | 8627/10519 [2:18:11<28:48,  1.09it/s][NeMo W 2026-06-19 09:27:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.48it/s]
 82%|████████▏ | 8628/10519 [2:18:12<30:03,  1.05it/s][NeMo W 2026-06-19 09:27:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.02it/s]
 82%|████████▏ | 8629/10519 [2:18:13<30:10,  1.04it/s][NeMo W 2026-06-19 09:27:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:27:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 82%|████████▏ | 8630/10519 [2:18:14<29:48,  1.06it/s][NeMo W 2026-06-19 09:27:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8650 samples

[NeMo W 2026-06-19 09:28:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 82%|████████▏ | 8651/10519 [2:18:36<39:42,  1.28s/it][NeMo W 2026-06-19 09:28:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 82%|████████▏ | 8652/10519 [2:18:37<35:37,  1.14s/it][NeMo W 2026-06-19 09:28:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.71it/s]
 82%|████████▏ | 8653/10519 [2:18:38<33:12,  1.07s/it][NeMo W 2026-06-19 09:28:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.17it/s]
 82%|████████▏ | 8654/10519 [2:18:39<32:20,  1.04s/it][NeMo W 2026-06-19 09:28:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 82%|████████▏ | 8655/10519 [2:18:40<29:07,  1.07it/s][NeMo W 2026-06-19 09:28:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 82%|████████▏ | 8656/10519 [2:18:40<29:10,  1.06it/s][NeMo W 2026-06-19 09:28:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 82%|████████▏ | 8657/10519 [2:18:42<30:36,  1.01it/s][NeMo W 2026-06-19 09:28:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.94it/s]
 82%|████████▏ | 8658/10519 [2:18:42<28:49,  1.08it/s][NeMo W 2026-06-19 09:28:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 82%|████████▏ | 8659/10519 [2:18:43<29:14,  1.06it/s][NeMo W 2026-06-19 09:28:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 82%|████████▏ | 8660/10519 [2:18:44<30:30,  1.02it/s][NeMo W 2026-06-19 09:28:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 82%|████████▏ | 8661/10519 [2:18:45<30:47,  1.01it/s][NeMo W 2026-06-19 09:28:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 82%|████████▏ | 8662/10519 [2:18:46<30:50,  1.00it/s][NeMo W 2026-06-19 09:28:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 82%|████████▏ | 8663/10519 [2:18:47<30:53,  1.00it/s][NeMo W 2026-06-19 09:28:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 82%|████████▏ | 8664/10519 [2:18:48<30:20,  1.02it/s][NeMo W 2026-06-19 09:28:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.68it/s]
 82%|████████▏ | 8665/10519 [2:18:49<27:50,  1.11it/s][NeMo W 2026-06-19 09:28:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 82%|████████▏ | 8666/10519 [2:18:50<27:59,  1.10it/s][NeMo W 2026-06-19 09:28:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.96it/s]
 82%|████████▏ | 8667/10519 [2:18:51<28:31,  1.08it/s][NeMo W 2026-06-19 09:28:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 82%|████████▏ | 8668/10519 [2:18:52<28:49,  1.07it/s][NeMo W 2026-06-19 09:28:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 82%|████████▏ | 8669/10519 [2:18:53<28:36,  1.08it/s][NeMo W 2026-06-19 09:28:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.28it/s]
 82%|████████▏ | 8670/10519 [2:18:54<28:09,  1.09it/s][NeMo W 2026-06-19 09:28:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.11it/s]
 82%|████████▏ | 8671/10519 [2:18:55<27:42,  1.11it/s][NeMo W 2026-06-19 09:28:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.03it/s]
 82%|████████▏ | 8672/10519 [2:18:56<28:06,  1.10it/s][NeMo W 2026-06-19 09:28:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 82%|████████▏ | 8673/10519 [2:18:57<28:35,  1.08it/s][NeMo W 2026-06-19 09:28:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 82%|████████▏ | 8674/10519 [2:18:57<28:48,  1.07it/s][NeMo W 2026-06-19 09:28:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 82%|████████▏ | 8675/10519 [2:18:59<29:36,  1.04it/s][NeMo W 2026-06-19 09:28:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.18it/s]
 82%|████████▏ | 8676/10519 [2:19:00<30:55,  1.01s/it][NeMo W 2026-06-19 09:28:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 82%|████████▏ | 8677/10519 [2:19:01<31:14,  1.02s/it][NeMo W 2026-06-19 09:28:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.39it/s]
 82%|████████▏ | 8678/10519 [2:19:02<30:03,  1.02it/s][NeMo W 2026-06-19 09:28:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 83%|████████▎ | 8679/10519 [2:19:02<29:14,  1.05it/s][NeMo W 2026-06-19 09:28:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:28:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 83%|████████▎ | 8680/10519 [2:19:03<29:07,  1.05it/s][NeMo W 2026-06-19 09:28:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8700 samples

[NeMo W 2026-06-19 09:29:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.38it/s]
 83%|████████▎ | 8701/10519 [2:19:26<50:08,  1.65s/it][NeMo W 2026-06-19 09:29:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 83%|████████▎ | 8702/10519 [2:19:27<44:22,  1.47s/it][NeMo W 2026-06-19 09:29:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 83%|████████▎ | 8703/10519 [2:19:28<39:20,  1.30s/it][NeMo W 2026-06-19 09:29:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 83%|████████▎ | 8704/10519 [2:19:29<36:37,  1.21s/it][NeMo W 2026-06-19 09:29:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 83%|████████▎ | 8705/10519 [2:19:30<35:45,  1.18s/it][NeMo W 2026-06-19 09:29:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 83%|████████▎ | 8706/10519 [2:19:31<33:30,  1.11s/it][NeMo W 2026-06-19 09:29:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 83%|████████▎ | 8707/10519 [2:19:32<31:53,  1.06s/it][NeMo W 2026-06-19 09:29:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 83%|████████▎ | 8708/10519 [2:19:33<30:42,  1.02s/it][NeMo W 2026-06-19 09:29:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 83%|████████▎ | 8709/10519 [2:19:34<30:33,  1.01s/it][NeMo W 2026-06-19 09:29:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 83%|████████▎ | 8710/10519 [2:19:35<30:30,  1.01s/it][NeMo W 2026-06-19 09:29:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 83%|████████▎ | 8711/10519 [2:19:35<29:38,  1.02it/s][NeMo W 2026-06-19 09:29:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 83%|████████▎ | 8712/10519 [2:19:36<28:47,  1.05it/s][NeMo W 2026-06-19 09:29:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.43it/s]
 83%|████████▎ | 8713/10519 [2:19:37<28:32,  1.05it/s][NeMo W 2026-06-19 09:29:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.21it/s]
 83%|████████▎ | 8714/10519 [2:19:38<29:44,  1.01it/s][NeMo W 2026-06-19 09:29:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.91it/s]
 83%|████████▎ | 8715/10519 [2:19:39<29:33,  1.02it/s][NeMo W 2026-06-19 09:29:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.41it/s]
 83%|████████▎ | 8716/10519 [2:19:40<30:28,  1.01s/it][NeMo W 2026-06-19 09:29:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 83%|████████▎ | 8717/10519 [2:19:41<30:01,  1.00it/s][NeMo W 2026-06-19 09:29:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 83%|████████▎ | 8718/10519 [2:19:42<29:13,  1.03it/s][NeMo W 2026-06-19 09:29:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 83%|████████▎ | 8719/10519 [2:19:43<29:00,  1.03it/s][NeMo W 2026-06-19 09:29:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 83%|████████▎ | 8720/10519 [2:19:44<27:08,  1.10it/s][NeMo W 2026-06-19 09:29:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 83%|████████▎ | 8721/10519 [2:19:45<28:02,  1.07it/s][NeMo W 2026-06-19 09:29:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
 83%|████████▎ | 8722/10519 [2:19:46<28:18,  1.06it/s][NeMo W 2026-06-19 09:29:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 83%|████████▎ | 8723/10519 [2:19:47<28:04,  1.07it/s][NeMo W 2026-06-19 09:29:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 83%|████████▎ | 8724/10519 [2:19:48<27:50,  1.07it/s][NeMo W 2026-06-19 09:29:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 83%|████████▎ | 8725/10519 [2:19:49<26:19,  1.14it/s][NeMo W 2026-06-19 09:29:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 83%|████████▎ | 8726/10519 [2:19:49<24:53,  1.20it/s][NeMo W 2026-06-19 09:29:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 83%|████████▎ | 8727/10519 [2:19:50<25:52,  1.15it/s][NeMo W 2026-06-19 09:29:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.13it/s]
 83%|████████▎ | 8728/10519 [2:19:51<27:01,  1.10it/s][NeMo W 2026-06-19 09:29:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.58it/s]
 83%|████████▎ | 8729/10519 [2:19:52<27:41,  1.08it/s][NeMo W 2026-06-19 09:29:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]

Checkpoint saved: 8750 samples

[NeMo W 2026-06-19 09:29:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 83%|████████▎ | 8751/10519 [2:20:15<36:49,  1.25s/it][NeMo W 2026-06-19 09:29:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 83%|████████▎ | 8752/10519 [2:20:16<34:16,  1.16s/it][NeMo W 2026-06-19 09:29:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 83%|████████▎ | 8753/10519 [2:20:16<31:26,  1.07s/it][NeMo W 2026-06-19 09:29:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 83%|████████▎ | 8754/10519 [2:20:17<30:47,  1.05s/it][NeMo W 2026-06-19 09:29:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:29:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.77it/s]
 83%|████████▎ | 8755/10519 [2:20:18<31:23,  1.07s/it][NeMo W 2026-06-19 09:30:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 83%|████████▎ | 8756/10519 [2:20:19<30:08,  1.03s/it][NeMo W 2026-06-19 09:30:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.00it/s]
 83%|████████▎ | 8757/10519 [2:20:21<30:56,  1.05s/it][NeMo W 2026-06-19 09:30:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 83%|████████▎ | 8758/10519 [2:20:21<28:42,  1.02it/s][NeMo W 2026-06-19 09:30:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 83%|████████▎ | 8759/10519 [2:20:22<26:21,  1.11it/s][NeMo W 2026-06-19 09:30:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 83%|████████▎ | 8760/10519 [2:20:23<27:18,  1.07it/s][NeMo W 2026-06-19 09:30:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 83%|████████▎ | 8761/10519 [2:20:24<25:54,  1.13it/s][NeMo W 2026-06-19 09:30:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 83%|████████▎ | 8762/10519 [2:20:25<24:55,  1.17it/s][NeMo W 2026-06-19 09:30:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 83%|████████▎ | 8763/10519 [2:20:26<25:44,  1.14it/s][NeMo W 2026-06-19 09:30:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 83%|████████▎ | 8764/10519 [2:20:27<26:35,  1.10it/s][NeMo W 2026-06-19 09:30:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.40it/s]
 83%|████████▎ | 8765/10519 [2:20:28<27:45,  1.05it/s][NeMo W 2026-06-19 09:30:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 83%|████████▎ | 8766/10519 [2:20:28<26:19,  1.11it/s][NeMo W 2026-06-19 09:30:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 83%|████████▎ | 8767/10519 [2:20:29<26:37,  1.10it/s][NeMo W 2026-06-19 09:30:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 83%|████████▎ | 8768/10519 [2:20:30<26:15,  1.11it/s][NeMo W 2026-06-19 09:30:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 83%|████████▎ | 8769/10519 [2:20:31<26:33,  1.10it/s][NeMo W 2026-06-19 09:30:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 83%|████████▎ | 8770/10519 [2:20:32<27:14,  1.07it/s][NeMo W 2026-06-19 09:30:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.18it/s]
 83%|████████▎ | 8771/10519 [2:20:33<26:18,  1.11it/s][NeMo W 2026-06-19 09:30:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 83%|████████▎ | 8772/10519 [2:20:34<26:35,  1.09it/s][NeMo W 2026-06-19 09:30:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 83%|████████▎ | 8773/10519 [2:20:37<44:59,  1.55s/it][NeMo W 2026-06-19 09:30:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 83%|████████▎ | 8774/10519 [2:20:38<39:29,  1.36s/it][NeMo W 2026-06-19 09:30:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 83%|████████▎ | 8775/10519 [2:20:39<36:02,  1.24s/it][NeMo W 2026-06-19 09:30:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 83%|████████▎ | 8776/10519 [2:20:39<31:37,  1.09s/it][NeMo W 2026-06-19 09:30:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 83%|████████▎ | 8777/10519 [2:20:40<30:42,  1.06s/it][NeMo W 2026-06-19 09:30:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 83%|████████▎ | 8778/10519 [2:20:41<29:32,  1.02s/it][NeMo W 2026-06-19 09:30:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 83%|████████▎ | 8779/10519 [2:20:42<28:43,  1.01it/s][NeMo W 2026-06-19 09:30:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]

Checkpoint saved: 8800 samples

[NeMo W 2026-06-19 09:30:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 84%|████████▎ | 8801/10519 [2:21:04<33:14,  1.16s/it][NeMo W 2026-06-19 09:30:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.55it/s]
 84%|████████▎ | 8802/10519 [2:21:05<34:19,  1.20s/it][NeMo W 2026-06-19 09:30:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.73it/s]
 84%|████████▎ | 8803/10519 [2:21:07<35:12,  1.23s/it][NeMo W 2026-06-19 09:30:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 84%|████████▎ | 8804/10519 [2:21:08<33:31,  1.17s/it][NeMo W 2026-06-19 09:30:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 84%|████████▎ | 8805/10519 [2:21:09<31:30,  1.10s/it][NeMo W 2026-06-19 09:30:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 84%|████████▎ | 8806/10519 [2:21:10<29:40,  1.04s/it][NeMo W 2026-06-19 09:30:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 84%|████████▎ | 8807/10519 [2:21:10<27:12,  1.05it/s][NeMo W 2026-06-19 09:30:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 84%|████████▎ | 8808/10519 [2:21:11<25:44,  1.11it/s][NeMo W 2026-06-19 09:30:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.47it/s]
 84%|████████▎ | 8809/10519 [2:21:12<27:09,  1.05it/s][NeMo W 2026-06-19 09:30:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.01it/s]
 84%|████████▍ | 8810/10519 [2:21:13<27:57,  1.02it/s][NeMo W 2026-06-19 09:30:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 84%|████████▍ | 8811/10519 [2:21:14<28:05,  1.01it/s][NeMo W 2026-06-19 09:30:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 84%|████████▍ | 8812/10519 [2:21:15<28:15,  1.01it/s][NeMo W 2026-06-19 09:30:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.92it/s]
 84%|████████▍ | 8813/10519 [2:21:16<28:34,  1.00s/it][NeMo W 2026-06-19 09:30:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
 84%|████████▍ | 8814/10519 [2:21:17<27:37,  1.03it/s][NeMo W 2026-06-19 09:30:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:30:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.20it/s]
 84%|████████▍ | 8815/10519 [2:21:18<27:42,  1.03it/s][NeMo W 2026-06-19 09:31:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 84%|████████▍ | 8816/10519 [2:21:19<27:55,  1.02it/s][NeMo W 2026-06-19 09:31:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 84%|████████▍ | 8817/10519 [2:21:20<26:59,  1.05it/s][NeMo W 2026-06-19 09:31:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 84%|████████▍ | 8818/10519 [2:21:21<27:22,  1.04it/s][NeMo W 2026-06-19 09:31:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 84%|████████▍ | 8819/10519 [2:21:22<27:22,  1.04it/s][NeMo W 2026-06-19 09:31:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 84%|████████▍ | 8820/10519 [2:21:23<28:38,  1.01s/it][NeMo W 2026-06-19 09:31:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 84%|████████▍ | 8821/10519 [2:21:24<27:38,  1.02it/s][NeMo W 2026-06-19 09:31:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 84%|████████▍ | 8822/10519 [2:21:25<27:02,  1.05it/s][NeMo W 2026-06-19 09:31:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 84%|████████▍ | 8823/10519 [2:21:26<27:11,  1.04it/s][NeMo W 2026-06-19 09:31:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.03it/s]
 84%|████████▍ | 8824/10519 [2:21:27<26:29,  1.07it/s][NeMo W 2026-06-19 09:31:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 84%|████████▍ | 8825/10519 [2:21:28<26:46,  1.05it/s][NeMo W 2026-06-19 09:31:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 84%|████████▍ | 8826/10519 [2:21:29<25:44,  1.10it/s][NeMo W 2026-06-19 09:31:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 84%|████████▍ | 8827/10519 [2:21:30<27:09,  1.04it/s][NeMo W 2026-06-19 09:31:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 84%|████████▍ | 8828/10519 [2:21:31<26:51,  1.05it/s][NeMo W 2026-06-19 09:31:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 84%|████████▍ | 8829/10519 [2:21:31<25:26,  1.11it/s][NeMo W 2026-06-19 09:31:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]

Checkpoint saved: 8850 samples

[NeMo W 2026-06-19 09:31:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.53it/s]
 84%|████████▍ | 8851/10519 [2:21:54<35:24,  1.27s/it][NeMo W 2026-06-19 09:31:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.02it/s]
 84%|████████▍ | 8852/10519 [2:21:55<33:07,  1.19s/it][NeMo W 2026-06-19 09:31:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 84%|████████▍ | 8853/10519 [2:21:56<29:31,  1.06s/it][NeMo W 2026-06-19 09:31:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.85it/s]
 84%|████████▍ | 8854/10519 [2:21:57<29:28,  1.06s/it][NeMo W 2026-06-19 09:31:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.80it/s]
 84%|████████▍ | 8855/10519 [2:21:58<29:06,  1.05s/it][NeMo W 2026-06-19 09:31:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 84%|████████▍ | 8856/10519 [2:21:59<28:05,  1.01s/it][NeMo W 2026-06-19 09:31:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 84%|████████▍ | 8857/10519 [2:22:00<27:44,  1.00s/it][NeMo W 2026-06-19 09:31:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 84%|████████▍ | 8858/10519 [2:22:01<27:59,  1.01s/it][NeMo W 2026-06-19 09:31:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 84%|████████▍ | 8859/10519 [2:22:02<28:16,  1.02s/it][NeMo W 2026-06-19 09:31:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 84%|████████▍ | 8860/10519 [2:22:03<27:22,  1.01it/s][NeMo W 2026-06-19 09:31:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 84%|████████▍ | 8861/10519 [2:22:04<26:06,  1.06it/s][NeMo W 2026-06-19 09:31:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 84%|████████▍ | 8862/10519 [2:22:05<25:26,  1.09it/s][NeMo W 2026-06-19 09:31:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 84%|████████▍ | 8863/10519 [2:22:06<25:29,  1.08it/s][NeMo W 2026-06-19 09:31:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.21it/s]
 84%|████████▍ | 8864/10519 [2:22:06<25:12,  1.09it/s][NeMo W 2026-06-19 09:31:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.01it/s]
 84%|████████▍ | 8865/10519 [2:22:07<25:33,  1.08it/s][NeMo W 2026-06-19 09:31:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 84%|████████▍ | 8866/10519 [2:22:08<25:54,  1.06it/s][NeMo W 2026-06-19 09:31:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 84%|████████▍ | 8867/10519 [2:22:10<27:24,  1.00it/s][NeMo W 2026-06-19 09:31:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
 84%|████████▍ | 8868/10519 [2:22:11<27:30,  1.00it/s][NeMo W 2026-06-19 09:31:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.48it/s]
 84%|████████▍ | 8869/10519 [2:22:12<27:43,  1.01s/it][NeMo W 2026-06-19 09:31:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
 84%|████████▍ | 8870/10519 [2:22:13<27:11,  1.01it/s][NeMo W 2026-06-19 09:31:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 84%|████████▍ | 8871/10519 [2:22:13<26:39,  1.03it/s][NeMo W 2026-06-19 09:31:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 84%|████████▍ | 8872/10519 [2:22:14<26:14,  1.05it/s][NeMo W 2026-06-19 09:31:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
 84%|████████▍ | 8873/10519 [2:22:15<25:58,  1.06it/s][NeMo W 2026-06-19 09:31:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.70it/s]
 84%|████████▍ | 8874/10519 [2:22:16<25:51,  1.06it/s][NeMo W 2026-06-19 09:31:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 84%|████████▍ | 8875/10519 [2:22:17<25:46,  1.06it/s][NeMo W 2026-06-19 09:31:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:31:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 84%|████████▍ | 8876/10519 [2:22:18<27:17,  1.00it/s][NeMo W 2026-06-19 09:32:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 84%|████████▍ | 8877/10519 [2:22:19<28:01,  1.02s/it][NeMo W 2026-06-19 09:32:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 84%|████████▍ | 8878/10519 [2:22:20<27:12,  1.00it/s][NeMo W 2026-06-19 09:32:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 84%|████████▍ | 8879/10519 [2:22:21<26:47,  1.02it/s][NeMo W 2026-06-19 09:32:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]

Checkpoint saved: 8900 samples

[NeMo W 2026-06-19 09:32:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 85%|████████▍ | 8901/10519 [2:22:44<35:37,  1.32s/it][NeMo W 2026-06-19 09:32:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 85%|████████▍ | 8902/10519 [2:22:45<32:41,  1.21s/it][NeMo W 2026-06-19 09:32:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 85%|████████▍ | 8903/10519 [2:22:46<30:35,  1.14s/it][NeMo W 2026-06-19 09:32:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 85%|████████▍ | 8904/10519 [2:22:47<29:56,  1.11s/it][NeMo W 2026-06-19 09:32:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 85%|████████▍ | 8905/10519 [2:22:48<28:16,  1.05s/it][NeMo W 2026-06-19 09:32:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 85%|████████▍ | 8906/10519 [2:22:49<27:17,  1.02s/it][NeMo W 2026-06-19 09:32:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 85%|████████▍ | 8907/10519 [2:22:50<27:04,  1.01s/it][NeMo W 2026-06-19 09:32:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 85%|████████▍ | 8908/10519 [2:22:51<26:11,  1.02it/s][NeMo W 2026-06-19 09:32:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.18it/s]
 85%|████████▍ | 8909/10519 [2:22:52<26:43,  1.00it/s][NeMo W 2026-06-19 09:32:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 85%|████████▍ | 8910/10519 [2:22:53<25:51,  1.04it/s][NeMo W 2026-06-19 09:32:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 85%|████████▍ | 8911/10519 [2:22:54<24:28,  1.09it/s][NeMo W 2026-06-19 09:32:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 85%|████████▍ | 8912/10519 [2:22:55<25:04,  1.07it/s][NeMo W 2026-06-19 09:32:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.02it/s]
 85%|████████▍ | 8913/10519 [2:22:56<25:13,  1.06it/s][NeMo W 2026-06-19 09:32:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 85%|████████▍ | 8914/10519 [2:22:57<25:47,  1.04it/s][NeMo W 2026-06-19 09:32:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]
 85%|████████▍ | 8915/10519 [2:22:58<25:31,  1.05it/s][NeMo W 2026-06-19 09:32:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
 85%|████████▍ | 8916/10519 [2:22:59<25:16,  1.06it/s][NeMo W 2026-06-19 09:32:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.90it/s]
 85%|████████▍ | 8917/10519 [2:23:00<24:56,  1.07it/s][NeMo W 2026-06-19 09:32:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.88it/s]
 85%|████████▍ | 8918/10519 [2:23:01<25:05,  1.06it/s][NeMo W 2026-06-19 09:32:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 85%|████████▍ | 8919/10519 [2:23:02<26:47,  1.00s/it][NeMo W 2026-06-19 09:32:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.52it/s]
 85%|████████▍ | 8920/10519 [2:23:03<28:00,  1.05s/it][NeMo W 2026-06-19 09:32:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 85%|████████▍ | 8921/10519 [2:23:04<27:51,  1.05s/it][NeMo W 2026-06-19 09:32:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 85%|████████▍ | 8922/10519 [2:23:05<27:31,  1.03s/it][NeMo W 2026-06-19 09:32:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.79it/s]
 85%|████████▍ | 8923/10519 [2:23:06<27:42,  1.04s/it][NeMo W 2026-06-19 09:32:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 85%|████████▍ | 8924/10519 [2:23:07<26:07,  1.02it/s][NeMo W 2026-06-19 09:32:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 85%|████████▍ | 8925/10519 [2:23:08<28:25,  1.07s/it][NeMo W 2026-06-19 09:32:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 85%|████████▍ | 8926/10519 [2:23:09<25:59,  1.02it/s][NeMo W 2026-06-19 09:32:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 85%|████████▍ | 8927/10519 [2:23:10<24:22,  1.09it/s][NeMo W 2026-06-19 09:32:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 85%|████████▍ | 8928/10519 [2:23:11<27:31,  1.04s/it][NeMo W 2026-06-19 09:32:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.67it/s]
 85%|████████▍ | 8929/10519 [2:23:12<27:59,  1.06s/it][NeMo W 2026-06-19 09:32:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:32:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 85%|████████▍ | 8930/10519 [2:23:13<27:55,  1.05s/it][NeMo W 2026-06-19 09:32:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 8950 samples

[NeMo W 2026-06-19 09:33:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 85%|████████▌ | 8951/10519 [2:23:35<33:46,  1.29s/it][NeMo W 2026-06-19 09:33:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 85%|████████▌ | 8952/10519 [2:23:36<31:01,  1.19s/it][NeMo W 2026-06-19 09:33:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 85%|████████▌ | 8953/10519 [2:23:37<29:34,  1.13s/it][NeMo W 2026-06-19 09:33:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 85%|████████▌ | 8954/10519 [2:23:38<29:56,  1.15s/it][NeMo W 2026-06-19 09:33:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 85%|████████▌ | 8955/10519 [2:23:39<28:42,  1.10s/it][NeMo W 2026-06-19 09:33:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 85%|████████▌ | 8956/10519 [2:23:40<27:24,  1.05s/it][NeMo W 2026-06-19 09:33:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 85%|████████▌ | 8957/10519 [2:23:41<26:44,  1.03s/it][NeMo W 2026-06-19 09:33:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 85%|████████▌ | 8958/10519 [2:23:42<26:46,  1.03s/it][NeMo W 2026-06-19 09:33:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 85%|████████▌ | 8959/10519 [2:23:43<26:32,  1.02s/it][NeMo W 2026-06-19 09:33:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.55it/s]
 85%|████████▌ | 8960/10519 [2:23:44<26:28,  1.02s/it][NeMo W 2026-06-19 09:33:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 85%|████████▌ | 8961/10519 [2:23:45<26:09,  1.01s/it][NeMo W 2026-06-19 09:33:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 85%|████████▌ | 8962/10519 [2:23:46<25:59,  1.00s/it][NeMo W 2026-06-19 09:33:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.65it/s]
 85%|████████▌ | 8963/10519 [2:23:47<27:42,  1.07s/it][NeMo W 2026-06-19 09:33:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
 85%|████████▌ | 8964/10519 [2:23:48<26:17,  1.01s/it][NeMo W 2026-06-19 09:33:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 85%|████████▌ | 8965/10519 [2:23:49<25:36,  1.01it/s][NeMo W 2026-06-19 09:33:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 85%|████████▌ | 8966/10519 [2:23:50<25:21,  1.02it/s][NeMo W 2026-06-19 09:33:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.08it/s]
 85%|████████▌ | 8967/10519 [2:23:51<25:11,  1.03it/s][NeMo W 2026-06-19 09:33:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 85%|████████▌ | 8968/10519 [2:23:52<25:43,  1.00it/s][NeMo W 2026-06-19 09:33:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.85it/s]
 85%|████████▌ | 8969/10519 [2:23:53<26:59,  1.05s/it][NeMo W 2026-06-19 09:33:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 85%|████████▌ | 8970/10519 [2:23:54<25:08,  1.03it/s][NeMo W 2026-06-19 09:33:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 85%|████████▌ | 8971/10519 [2:23:55<25:10,  1.02it/s][NeMo W 2026-06-19 09:33:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 85%|████████▌ | 8972/10519 [2:23:56<25:07,  1.03it/s][NeMo W 2026-06-19 09:33:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 85%|████████▌ | 8973/10519 [2:23:57<23:59,  1.07it/s][NeMo W 2026-06-19 09:33:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.95it/s]
 85%|████████▌ | 8974/10519 [2:23:58<24:46,  1.04it/s][NeMo W 2026-06-19 09:33:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 85%|████████▌ | 8975/10519 [2:23:58<23:45,  1.08it/s][NeMo W 2026-06-19 09:33:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.15it/s]
 85%|████████▌ | 8976/10519 [2:23:59<22:37,  1.14it/s][NeMo W 2026-06-19 09:33:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 85%|████████▌ | 8977/10519 [2:24:00<23:07,  1.11it/s][NeMo W 2026-06-19 09:33:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 85%|████████▌ | 8978/10519 [2:24:01<23:01,  1.12it/s][NeMo W 2026-06-19 09:33:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 85%|████████▌ | 8979/10519 [2:24:02<21:52,  1.17it/s][NeMo W 2026-06-19 09:33:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:33:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 85%|████████▌ | 8980/10519 [2:24:03<22:28,  1.14it/s][NeMo W 2026-06-19 09:33:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9000 samples

[NeMo W 2026-06-19 09:34:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 86%|████████▌ | 9001/10519 [2:24:23<28:42,  1.13s/it][NeMo W 2026-06-19 09:34:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.99it/s]
 86%|████████▌ | 9002/10519 [2:24:24<27:00,  1.07s/it][NeMo W 2026-06-19 09:34:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.36it/s]
 86%|████████▌ | 9003/10519 [2:24:25<26:35,  1.05s/it][NeMo W 2026-06-19 09:34:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 86%|████████▌ | 9004/10519 [2:24:26<26:12,  1.04s/it][NeMo W 2026-06-19 09:34:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 86%|████████▌ | 9005/10519 [2:24:27<25:19,  1.00s/it][NeMo W 2026-06-19 09:34:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 86%|████████▌ | 9006/10519 [2:24:28<24:28,  1.03it/s][NeMo W 2026-06-19 09:34:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 86%|████████▌ | 9007/10519 [2:24:29<23:01,  1.09it/s][NeMo W 2026-06-19 09:34:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 86%|████████▌ | 9008/10519 [2:24:30<23:39,  1.06it/s][NeMo W 2026-06-19 09:34:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 86%|████████▌ | 9009/10519 [2:24:31<23:51,  1.05it/s][NeMo W 2026-06-19 09:34:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 86%|████████▌ | 9010/10519 [2:24:32<24:02,  1.05it/s][NeMo W 2026-06-19 09:34:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 86%|████████▌ | 9011/10519 [2:24:33<23:33,  1.07it/s][NeMo W 2026-06-19 09:34:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 86%|████████▌ | 9012/10519 [2:24:33<23:27,  1.07it/s][NeMo W 2026-06-19 09:34:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 86%|████████▌ | 9013/10519 [2:24:35<24:39,  1.02it/s][NeMo W 2026-06-19 09:34:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 86%|████████▌ | 9014/10519 [2:24:36<24:38,  1.02it/s][NeMo W 2026-06-19 09:34:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 86%|████████▌ | 9015/10519 [2:24:36<24:05,  1.04it/s][NeMo W 2026-06-19 09:34:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.53it/s]
 86%|████████▌ | 9016/10519 [2:24:37<23:47,  1.05it/s][NeMo W 2026-06-19 09:34:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
 86%|████████▌ | 9017/10519 [2:24:38<23:47,  1.05it/s][NeMo W 2026-06-19 09:34:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 86%|████████▌ | 9018/10519 [2:24:39<23:45,  1.05it/s][NeMo W 2026-06-19 09:34:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 86%|████████▌ | 9019/10519 [2:24:40<24:21,  1.03it/s][NeMo W 2026-06-19 09:34:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 86%|████████▌ | 9020/10519 [2:24:41<23:42,  1.05it/s][NeMo W 2026-06-19 09:34:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 86%|████████▌ | 9021/10519 [2:24:42<23:23,  1.07it/s][NeMo W 2026-06-19 09:34:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 86%|████████▌ | 9022/10519 [2:24:43<23:17,  1.07it/s][NeMo W 2026-06-19 09:34:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 86%|████████▌ | 9023/10519 [2:24:44<23:18,  1.07it/s][NeMo W 2026-06-19 09:34:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 86%|████████▌ | 9024/10519 [2:24:45<23:13,  1.07it/s][NeMo W 2026-06-19 09:34:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 86%|████████▌ | 9025/10519 [2:24:46<23:03,  1.08it/s][NeMo W 2026-06-19 09:34:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 86%|████████▌ | 9026/10519 [2:24:47<23:26,  1.06it/s][NeMo W 2026-06-19 09:34:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.78it/s]
 86%|████████▌ | 9027/10519 [2:24:48<23:30,  1.06it/s][NeMo W 2026-06-19 09:34:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.82it/s]
 86%|████████▌ | 9028/10519 [2:24:49<23:22,  1.06it/s][NeMo W 2026-06-19 09:34:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 86%|████████▌ | 9029/10519 [2:24:50<23:15,  1.07it/s][NeMo W 2026-06-19 09:34:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.48it/s]
 86%|████████▌ | 9030/10519 [2:24:51<23:27,  1.06it/s][NeMo W 2026-06-19 09:34:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9050 samples

[NeMo W 2026-06-19 09:34:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 86%|████████▌ | 9051/10519 [2:25:12<30:31,  1.25s/it][NeMo W 2026-06-19 09:34:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.26it/s]
 86%|████████▌ | 9052/10519 [2:25:13<28:51,  1.18s/it][NeMo W 2026-06-19 09:34:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 86%|████████▌ | 9053/10519 [2:25:14<26:54,  1.10s/it][NeMo W 2026-06-19 09:34:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 86%|████████▌ | 9054/10519 [2:25:15<25:46,  1.06s/it][NeMo W 2026-06-19 09:34:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 86%|████████▌ | 9055/10519 [2:25:16<26:48,  1.10s/it][NeMo W 2026-06-19 09:34:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 86%|████████▌ | 9056/10519 [2:25:17<25:48,  1.06s/it][NeMo W 2026-06-19 09:34:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:34:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 86%|████████▌ | 9057/10519 [2:25:18<25:04,  1.03s/it][NeMo W 2026-06-19 09:35:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.71it/s]
 86%|████████▌ | 9058/10519 [2:25:19<24:33,  1.01s/it][NeMo W 2026-06-19 09:35:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.92it/s]
 86%|████████▌ | 9059/10519 [2:25:20<25:29,  1.05s/it][NeMo W 2026-06-19 09:35:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.59it/s]
 86%|████████▌ | 9060/10519 [2:25:21<25:06,  1.03s/it][NeMo W 2026-06-19 09:35:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.37it/s]
 86%|████████▌ | 9061/10519 [2:25:22<24:34,  1.01s/it][NeMo W 2026-06-19 09:35:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 86%|████████▌ | 9062/10519 [2:25:23<25:35,  1.05s/it][NeMo W 2026-06-19 09:35:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 86%|████████▌ | 9063/10519 [2:25:25<26:17,  1.08s/it][NeMo W 2026-06-19 09:35:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.07it/s]
 86%|████████▌ | 9064/10519 [2:25:25<23:45,  1.02it/s][NeMo W 2026-06-19 09:35:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 86%|████████▌ | 9065/10519 [2:25:26<23:38,  1.02it/s][NeMo W 2026-06-19 09:35:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 86%|████████▌ | 9066/10519 [2:25:27<23:04,  1.05it/s][NeMo W 2026-06-19 09:35:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 86%|████████▌ | 9067/10519 [2:25:28<22:50,  1.06it/s][NeMo W 2026-06-19 09:35:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 86%|████████▌ | 9068/10519 [2:25:29<22:32,  1.07it/s][NeMo W 2026-06-19 09:35:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.79it/s]
 86%|████████▌ | 9069/10519 [2:25:30<22:49,  1.06it/s][NeMo W 2026-06-19 09:35:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 86%|████████▌ | 9070/10519 [2:25:31<23:02,  1.05it/s][NeMo W 2026-06-19 09:35:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 86%|████████▌ | 9071/10519 [2:25:32<23:34,  1.02it/s][NeMo W 2026-06-19 09:35:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 86%|████████▌ | 9072/10519 [2:25:33<23:05,  1.04it/s][NeMo W 2026-06-19 09:35:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.35it/s]
 86%|████████▋ | 9073/10519 [2:25:34<23:32,  1.02it/s][NeMo W 2026-06-19 09:35:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 86%|████████▋ | 9074/10519 [2:25:35<23:17,  1.03it/s][NeMo W 2026-06-19 09:35:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 86%|████████▋ | 9075/10519 [2:25:36<22:53,  1.05it/s][NeMo W 2026-06-19 09:35:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 86%|████████▋ | 9076/10519 [2:25:37<23:28,  1.02it/s][NeMo W 2026-06-19 09:35:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 86%|████████▋ | 9077/10519 [2:25:38<23:04,  1.04it/s][NeMo W 2026-06-19 09:35:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.71it/s]
 86%|████████▋ | 9078/10519 [2:25:39<22:48,  1.05it/s][NeMo W 2026-06-19 09:35:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 86%|████████▋ | 9079/10519 [2:25:40<22:31,  1.07it/s][NeMo W 2026-06-19 09:35:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]

Checkpoint saved: 9100 samples

[NeMo W 2026-06-19 09:35:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 87%|████████▋ | 9101/10519 [2:26:03<34:28,  1.46s/it][NeMo W 2026-06-19 09:35:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 87%|████████▋ | 9102/10519 [2:26:04<31:00,  1.31s/it][NeMo W 2026-06-19 09:35:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.19it/s]
 87%|████████▋ | 9103/10519 [2:26:05<28:22,  1.20s/it][NeMo W 2026-06-19 09:35:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 87%|████████▋ | 9104/10519 [2:26:06<26:10,  1.11s/it][NeMo W 2026-06-19 09:35:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 87%|████████▋ | 9105/10519 [2:26:06<24:50,  1.05s/it][NeMo W 2026-06-19 09:35:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 87%|████████▋ | 9106/10519 [2:26:07<23:54,  1.02s/it][NeMo W 2026-06-19 09:35:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 87%|████████▋ | 9107/10519 [2:26:08<23:34,  1.00s/it][NeMo W 2026-06-19 09:35:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 87%|████████▋ | 9108/10519 [2:26:09<23:15,  1.01it/s][NeMo W 2026-06-19 09:35:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 87%|████████▋ | 9109/10519 [2:26:10<22:46,  1.03it/s][NeMo W 2026-06-19 09:35:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 87%|████████▋ | 9110/10519 [2:26:11<22:09,  1.06it/s][NeMo W 2026-06-19 09:35:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.16it/s]
 87%|████████▋ | 9111/10519 [2:26:12<22:08,  1.06it/s][NeMo W 2026-06-19 09:35:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.65it/s]
 87%|████████▋ | 9112/10519 [2:26:13<22:25,  1.05it/s][NeMo W 2026-06-19 09:35:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.09it/s]
 87%|████████▋ | 9113/10519 [2:26:14<23:33,  1.01s/it][NeMo W 2026-06-19 09:35:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.15it/s]
 87%|████████▋ | 9114/10519 [2:26:15<23:13,  1.01it/s][NeMo W 2026-06-19 09:35:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 87%|████████▋ | 9115/10519 [2:26:16<22:45,  1.03it/s][NeMo W 2026-06-19 09:35:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 87%|████████▋ | 9116/10519 [2:26:17<22:26,  1.04it/s][NeMo W 2026-06-19 09:35:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:35:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 87%|████████▋ | 9117/10519 [2:26:18<21:58,  1.06it/s][NeMo W 2026-06-19 09:36:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.08it/s]
 87%|████████▋ | 9118/10519 [2:26:19<21:36,  1.08it/s][NeMo W 2026-06-19 09:36:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 87%|████████▋ | 9119/10519 [2:26:20<21:54,  1.07it/s][NeMo W 2026-06-19 09:36:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 87%|████████▋ | 9120/10519 [2:26:21<22:07,  1.05it/s][NeMo W 2026-06-19 09:36:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 87%|████████▋ | 9121/10519 [2:26:21<20:30,  1.14it/s][NeMo W 2026-06-19 09:36:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.10it/s]
 87%|████████▋ | 9122/10519 [2:26:22<21:17,  1.09it/s][NeMo W 2026-06-19 09:36:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 87%|████████▋ | 9123/10519 [2:26:23<21:30,  1.08it/s][NeMo W 2026-06-19 09:36:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 87%|████████▋ | 9124/10519 [2:26:24<21:22,  1.09it/s][NeMo W 2026-06-19 09:36:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.94it/s]
 87%|████████▋ | 9125/10519 [2:26:25<21:52,  1.06it/s][NeMo W 2026-06-19 09:36:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 87%|████████▋ | 9126/10519 [2:26:26<22:07,  1.05it/s][NeMo W 2026-06-19 09:36:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 87%|████████▋ | 9127/10519 [2:26:27<22:20,  1.04it/s][NeMo W 2026-06-19 09:36:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.75it/s]
 87%|████████▋ | 9128/10519 [2:26:28<21:10,  1.09it/s][NeMo W 2026-06-19 09:36:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.59it/s]
 87%|████████▋ | 9129/10519 [2:26:29<21:54,  1.06it/s][NeMo W 2026-06-19 09:36:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]

Checkpoint saved: 9150 samples

[NeMo W 2026-06-19 09:36:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.23it/s]
 87%|████████▋ | 9151/10519 [2:26:52<30:08,  1.32s/it][NeMo W 2026-06-19 09:36:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 87%|████████▋ | 9152/10519 [2:26:53<27:57,  1.23s/it][NeMo W 2026-06-19 09:36:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.64it/s]
 87%|████████▋ | 9153/10519 [2:26:54<26:42,  1.17s/it][NeMo W 2026-06-19 09:36:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 87%|████████▋ | 9154/10519 [2:26:55<25:06,  1.10s/it][NeMo W 2026-06-19 09:36:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 87%|████████▋ | 9155/10519 [2:26:56<23:26,  1.03s/it][NeMo W 2026-06-19 09:36:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 87%|████████▋ | 9156/10519 [2:26:57<21:05,  1.08it/s][NeMo W 2026-06-19 09:36:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 87%|████████▋ | 9157/10519 [2:26:58<21:14,  1.07it/s][NeMo W 2026-06-19 09:36:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.52it/s]
 87%|████████▋ | 9158/10519 [2:26:59<21:01,  1.08it/s][NeMo W 2026-06-19 09:36:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 87%|████████▋ | 9159/10519 [2:26:59<20:54,  1.08it/s][NeMo W 2026-06-19 09:36:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 87%|████████▋ | 9160/10519 [2:27:00<20:40,  1.10it/s][NeMo W 2026-06-19 09:36:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 87%|████████▋ | 9161/10519 [2:27:01<21:38,  1.05it/s][NeMo W 2026-06-19 09:36:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 87%|████████▋ | 9162/10519 [2:27:02<21:02,  1.07it/s][NeMo W 2026-06-19 09:36:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 87%|████████▋ | 9163/10519 [2:27:03<19:45,  1.14it/s][NeMo W 2026-06-19 09:36:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 87%|████████▋ | 9164/10519 [2:27:04<20:08,  1.12it/s][NeMo W 2026-06-19 09:36:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.21it/s]
 87%|████████▋ | 9165/10519 [2:27:05<18:47,  1.20it/s][NeMo W 2026-06-19 09:36:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 87%|████████▋ | 9166/10519 [2:27:06<19:16,  1.17it/s][NeMo W 2026-06-19 09:36:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.58it/s]
 87%|████████▋ | 9167/10519 [2:27:07<20:10,  1.12it/s][NeMo W 2026-06-19 09:36:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 87%|████████▋ | 9168/10519 [2:27:08<21:06,  1.07it/s][NeMo W 2026-06-19 09:36:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.40it/s]
 87%|████████▋ | 9169/10519 [2:27:09<21:22,  1.05it/s][NeMo W 2026-06-19 09:36:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 87%|████████▋ | 9170/10519 [2:27:10<21:33,  1.04it/s][NeMo W 2026-06-19 09:36:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 87%|████████▋ | 9171/10519 [2:27:11<21:47,  1.03it/s][NeMo W 2026-06-19 09:36:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 87%|████████▋ | 9172/10519 [2:27:11<21:28,  1.05it/s][NeMo W 2026-06-19 09:36:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.24it/s]
 87%|████████▋ | 9173/10519 [2:27:12<20:03,  1.12it/s][NeMo W 2026-06-19 09:36:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 87%|████████▋ | 9174/10519 [2:27:13<19:06,  1.17it/s][NeMo W 2026-06-19 09:36:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.22it/s]
 87%|████████▋ | 9175/10519 [2:27:14<19:30,  1.15it/s][NeMo W 2026-06-19 09:36:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 87%|████████▋ | 9176/10519 [2:27:15<20:00,  1.12it/s][NeMo W 2026-06-19 09:36:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.72it/s]
 87%|████████▋ | 9177/10519 [2:27:16<20:42,  1.08it/s][NeMo W 2026-06-19 09:36:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 87%|████████▋ | 9178/10519 [2:27:17<19:11,  1.16it/s][NeMo W 2026-06-19 09:36:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 87%|████████▋ | 9179/10519 [2:27:17<19:15,  1.16it/s][NeMo W 2026-06-19 09:36:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:36:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 87%|████████▋ | 9180/10519 [2:27:18<19:49,  1.13it/s][NeMo W 2026-06-19 09:37:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9200 samples

[NeMo W 2026-06-19 09:37:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 87%|████████▋ | 9201/10519 [2:27:40<27:56,  1.27s/it][NeMo W 2026-06-19 09:37:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 87%|████████▋ | 9202/10519 [2:27:41<25:44,  1.17s/it][NeMo W 2026-06-19 09:37:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 87%|████████▋ | 9203/10519 [2:27:42<22:36,  1.03s/it][NeMo W 2026-06-19 09:37:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.29it/s]
 87%|████████▋ | 9204/10519 [2:27:43<21:43,  1.01it/s][NeMo W 2026-06-19 09:37:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 88%|████████▊ | 9205/10519 [2:27:44<22:00,  1.00s/it][NeMo W 2026-06-19 09:37:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 88%|████████▊ | 9206/10519 [2:27:45<21:55,  1.00s/it][NeMo W 2026-06-19 09:37:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 88%|████████▊ | 9207/10519 [2:27:46<22:34,  1.03s/it][NeMo W 2026-06-19 09:37:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.09it/s]
 88%|████████▊ | 9208/10519 [2:27:47<21:52,  1.00s/it][NeMo W 2026-06-19 09:37:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.12it/s]
 88%|████████▊ | 9209/10519 [2:27:48<22:52,  1.05s/it][NeMo W 2026-06-19 09:37:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 88%|████████▊ | 9210/10519 [2:27:49<22:26,  1.03s/it][NeMo W 2026-06-19 09:37:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 88%|████████▊ | 9211/10519 [2:27:50<22:06,  1.01s/it][NeMo W 2026-06-19 09:37:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.06it/s]
 88%|████████▊ | 9212/10519 [2:27:51<21:52,  1.00s/it][NeMo W 2026-06-19 09:37:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 88%|████████▊ | 9213/10519 [2:27:52<19:49,  1.10it/s][NeMo W 2026-06-19 09:37:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 88%|████████▊ | 9214/10519 [2:27:52<19:32,  1.11it/s][NeMo W 2026-06-19 09:37:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 88%|████████▊ | 9215/10519 [2:27:53<20:00,  1.09it/s][NeMo W 2026-06-19 09:37:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 88%|████████▊ | 9216/10519 [2:27:54<20:22,  1.07it/s][NeMo W 2026-06-19 09:37:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 88%|████████▊ | 9217/10519 [2:27:55<21:02,  1.03it/s][NeMo W 2026-06-19 09:37:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.32it/s]
 88%|████████▊ | 9218/10519 [2:27:56<20:53,  1.04it/s][NeMo W 2026-06-19 09:37:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 88%|████████▊ | 9219/10519 [2:27:57<20:50,  1.04it/s][NeMo W 2026-06-19 09:37:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 88%|████████▊ | 9220/10519 [2:27:58<21:29,  1.01it/s][NeMo W 2026-06-19 09:37:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.52it/s]
 88%|████████▊ | 9221/10519 [2:28:00<24:54,  1.15s/it][NeMo W 2026-06-19 09:37:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 88%|████████▊ | 9222/10519 [2:28:01<21:48,  1.01s/it][NeMo W 2026-06-19 09:37:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 88%|████████▊ | 9223/10519 [2:28:02<21:22,  1.01it/s][NeMo W 2026-06-19 09:37:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 88%|████████▊ | 9224/10519 [2:28:02<20:12,  1.07it/s][NeMo W 2026-06-19 09:37:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 88%|████████▊ | 9225/10519 [2:28:03<20:51,  1.03it/s][NeMo W 2026-06-19 09:37:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.94it/s]
 88%|████████▊ | 9226/10519 [2:28:04<20:47,  1.04it/s][NeMo W 2026-06-19 09:37:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 88%|████████▊ | 9227/10519 [2:28:05<19:54,  1.08it/s][NeMo W 2026-06-19 09:37:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.71it/s]
 88%|████████▊ | 9228/10519 [2:28:06<19:43,  1.09it/s][NeMo W 2026-06-19 09:37:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.20it/s]
 88%|████████▊ | 9229/10519 [2:28:07<19:50,  1.08it/s][NeMo W 2026-06-19 09:37:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:37:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]

Checkpoint saved: 9250 samples

[NeMo W 2026-06-19 09:38:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 88%|████████▊ | 9251/10519 [2:28:30<27:23,  1.30s/it][NeMo W 2026-06-19 09:38:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.10it/s]
 88%|████████▊ | 9252/10519 [2:28:31<25:14,  1.20s/it][NeMo W 2026-06-19 09:38:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.50it/s]
 88%|████████▊ | 9253/10519 [2:28:32<23:24,  1.11s/it][NeMo W 2026-06-19 09:38:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 88%|████████▊ | 9254/10519 [2:28:33<22:35,  1.07s/it][NeMo W 2026-06-19 09:38:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.45it/s]
 88%|████████▊ | 9255/10519 [2:28:33<20:27,  1.03it/s][NeMo W 2026-06-19 09:38:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.14it/s]
 88%|████████▊ | 9256/10519 [2:28:34<20:12,  1.04it/s][NeMo W 2026-06-19 09:38:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.42it/s]
 88%|████████▊ | 9257/10519 [2:28:35<19:53,  1.06it/s][NeMo W 2026-06-19 09:38:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 88%|████████▊ | 9258/10519 [2:28:36<18:15,  1.15it/s][NeMo W 2026-06-19 09:38:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.02it/s]
 88%|████████▊ | 9259/10519 [2:28:37<18:37,  1.13it/s][NeMo W 2026-06-19 09:38:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 88%|████████▊ | 9260/10519 [2:28:38<18:50,  1.11it/s][NeMo W 2026-06-19 09:38:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.84it/s]
 88%|████████▊ | 9261/10519 [2:28:39<19:16,  1.09it/s][NeMo W 2026-06-19 09:38:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 88%|████████▊ | 9262/10519 [2:28:40<18:15,  1.15it/s][NeMo W 2026-06-19 09:38:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 88%|████████▊ | 9263/10519 [2:28:41<18:55,  1.11it/s][NeMo W 2026-06-19 09:38:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 88%|████████▊ | 9264/10519 [2:28:42<20:58,  1.00s/it][NeMo W 2026-06-19 09:38:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.34it/s]
 88%|████████▊ | 9265/10519 [2:28:43<20:29,  1.02it/s][NeMo W 2026-06-19 09:38:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.82it/s]
 88%|████████▊ | 9266/10519 [2:28:44<21:31,  1.03s/it][NeMo W 2026-06-19 09:38:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 88%|████████▊ | 9267/10519 [2:28:45<21:09,  1.01s/it][NeMo W 2026-06-19 09:38:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 88%|████████▊ | 9268/10519 [2:28:46<20:47,  1.00it/s][NeMo W 2026-06-19 09:38:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 88%|████████▊ | 9269/10519 [2:28:47<19:44,  1.05it/s][NeMo W 2026-06-19 09:38:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 88%|████████▊ | 9270/10519 [2:28:48<19:50,  1.05it/s][NeMo W 2026-06-19 09:38:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 88%|████████▊ | 9271/10519 [2:28:49<19:53,  1.05it/s][NeMo W 2026-06-19 09:38:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 88%|████████▊ | 9272/10519 [2:28:50<20:06,  1.03it/s][NeMo W 2026-06-19 09:38:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 88%|████████▊ | 9273/10519 [2:28:51<20:06,  1.03it/s][NeMo W 2026-06-19 09:38:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 88%|████████▊ | 9274/10519 [2:28:51<18:35,  1.12it/s][NeMo W 2026-06-19 09:38:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.70it/s]
 88%|████████▊ | 9275/10519 [2:28:52<19:13,  1.08it/s][NeMo W 2026-06-19 09:38:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.45it/s]
 88%|████████▊ | 9276/10519 [2:28:53<19:31,  1.06it/s][NeMo W 2026-06-19 09:38:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.80it/s]
 88%|████████▊ | 9277/10519 [2:28:54<20:42,  1.00s/it][NeMo W 2026-06-19 09:38:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 88%|████████▊ | 9278/10519 [2:28:55<19:10,  1.08it/s][NeMo W 2026-06-19 09:38:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 88%|████████▊ | 9279/10519 [2:28:56<19:50,  1.04it/s][NeMo W 2026-06-19 09:38:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.71it/s]
 88%|████████▊ | 9280/10519 [2:28:57<20:19,  1.02it/s][NeMo W 2026-06-19 09:38:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9300 samples

[NeMo W 2026-06-19 09:38:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.48it/s]
 88%|████████▊ | 9301/10519 [2:29:17<23:42,  1.17s/it][NeMo W 2026-06-19 09:38:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:38:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 88%|████████▊ | 9302/10519 [2:29:18<20:50,  1.03s/it][NeMo W 2026-06-19 09:39:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 88%|████████▊ | 9303/10519 [2:29:19<20:12,  1.00it/s][NeMo W 2026-06-19 09:39:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 88%|████████▊ | 9304/10519 [2:29:20<19:50,  1.02it/s][NeMo W 2026-06-19 09:39:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 88%|████████▊ | 9305/10519 [2:29:21<19:44,  1.03it/s][NeMo W 2026-06-19 09:39:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 88%|████████▊ | 9306/10519 [2:29:22<19:22,  1.04it/s][NeMo W 2026-06-19 09:39:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 88%|████████▊ | 9307/10519 [2:29:23<19:57,  1.01it/s][NeMo W 2026-06-19 09:39:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.56it/s]
 88%|████████▊ | 9308/10519 [2:29:24<20:38,  1.02s/it][NeMo W 2026-06-19 09:39:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.57it/s]
 88%|████████▊ | 9309/10519 [2:29:25<20:20,  1.01s/it][NeMo W 2026-06-19 09:39:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 89%|████████▊ | 9310/10519 [2:29:26<20:11,  1.00s/it][NeMo W 2026-06-19 09:39:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.95it/s]
 89%|████████▊ | 9311/10519 [2:29:27<20:08,  1.00s/it][NeMo W 2026-06-19 09:39:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.78it/s]
 89%|████████▊ | 9312/10519 [2:29:28<19:42,  1.02it/s][NeMo W 2026-06-19 09:39:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.06it/s]
 89%|████████▊ | 9313/10519 [2:29:29<19:17,  1.04it/s][NeMo W 2026-06-19 09:39:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 89%|████████▊ | 9314/10519 [2:29:30<19:14,  1.04it/s][NeMo W 2026-06-19 09:39:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 89%|████████▊ | 9315/10519 [2:29:31<19:30,  1.03it/s][NeMo W 2026-06-19 09:39:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 89%|████████▊ | 9316/10519 [2:29:32<18:07,  1.11it/s][NeMo W 2026-06-19 09:39:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.88it/s]
 89%|████████▊ | 9317/10519 [2:29:33<18:33,  1.08it/s][NeMo W 2026-06-19 09:39:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 89%|████████▊ | 9318/10519 [2:29:33<18:39,  1.07it/s][NeMo W 2026-06-19 09:39:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 89%|████████▊ | 9319/10519 [2:29:34<18:38,  1.07it/s][NeMo W 2026-06-19 09:39:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 89%|████████▊ | 9320/10519 [2:29:35<18:36,  1.07it/s][NeMo W 2026-06-19 09:39:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 89%|████████▊ | 9321/10519 [2:29:36<18:49,  1.06it/s][NeMo W 2026-06-19 09:39:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 89%|████████▊ | 9322/10519 [2:29:37<19:22,  1.03it/s][NeMo W 2026-06-19 09:39:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.51it/s]
 89%|████████▊ | 9323/10519 [2:29:38<19:47,  1.01it/s][NeMo W 2026-06-19 09:39:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
 89%|████████▊ | 9324/10519 [2:29:39<19:46,  1.01it/s][NeMo W 2026-06-19 09:39:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 89%|████████▊ | 9325/10519 [2:29:40<18:16,  1.09it/s][NeMo W 2026-06-19 09:39:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.68it/s]
 89%|████████▊ | 9326/10519 [2:29:41<18:30,  1.07it/s][NeMo W 2026-06-19 09:39:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 89%|████████▊ | 9327/10519 [2:29:42<18:26,  1.08it/s][NeMo W 2026-06-19 09:39:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.77it/s]
 89%|████████▊ | 9328/10519 [2:29:43<18:45,  1.06it/s][NeMo W 2026-06-19 09:39:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 89%|████████▊ | 9329/10519 [2:29:44<18:45,  1.06it/s][NeMo W 2026-06-19 09:39:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]

Checkpoint saved: 9350 samples

[NeMo W 2026-06-19 09:39:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 89%|████████▉ | 9351/10519 [2:30:06<26:55,  1.38s/it][NeMo W 2026-06-19 09:39:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 89%|████████▉ | 9352/10519 [2:30:07<24:14,  1.25s/it][NeMo W 2026-06-19 09:39:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 89%|████████▉ | 9353/10519 [2:30:08<22:21,  1.15s/it][NeMo W 2026-06-19 09:39:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.89it/s]
 89%|████████▉ | 9354/10519 [2:30:09<21:06,  1.09s/it][NeMo W 2026-06-19 09:39:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.44it/s]
 89%|████████▉ | 9355/10519 [2:30:10<20:21,  1.05s/it][NeMo W 2026-06-19 09:39:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 89%|████████▉ | 9356/10519 [2:30:11<21:05,  1.09s/it][NeMo W 2026-06-19 09:39:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 89%|████████▉ | 9357/10519 [2:30:12<20:12,  1.04s/it][NeMo W 2026-06-19 09:39:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 89%|████████▉ | 9358/10519 [2:30:13<19:35,  1.01s/it][NeMo W 2026-06-19 09:39:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.30it/s]
 89%|████████▉ | 9359/10519 [2:30:14<19:47,  1.02s/it][NeMo W 2026-06-19 09:39:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 89%|████████▉ | 9360/10519 [2:30:15<19:07,  1.01it/s][NeMo W 2026-06-19 09:39:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 89%|████████▉ | 9361/10519 [2:30:16<18:45,  1.03it/s][NeMo W 2026-06-19 09:39:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 89%|████████▉ | 9362/10519 [2:30:17<18:23,  1.05it/s][NeMo W 2026-06-19 09:39:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:39:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 89%|████████▉ | 9363/10519 [2:30:18<18:15,  1.06it/s][NeMo W 2026-06-19 09:40:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 89%|████████▉ | 9364/10519 [2:30:19<18:15,  1.05it/s][NeMo W 2026-06-19 09:40:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.81it/s]
 89%|████████▉ | 9365/10519 [2:30:20<18:42,  1.03it/s][NeMo W 2026-06-19 09:40:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 89%|████████▉ | 9366/10519 [2:30:21<18:37,  1.03it/s][NeMo W 2026-06-19 09:40:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 89%|████████▉ | 9367/10519 [2:30:22<18:30,  1.04it/s][NeMo W 2026-06-19 09:40:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.30it/s]
 89%|████████▉ | 9368/10519 [2:30:23<17:15,  1.11it/s][NeMo W 2026-06-19 09:40:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 89%|████████▉ | 9369/10519 [2:30:23<17:25,  1.10it/s][NeMo W 2026-06-19 09:40:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 89%|████████▉ | 9370/10519 [2:30:24<17:22,  1.10it/s][NeMo W 2026-06-19 09:40:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.92it/s]
 89%|████████▉ | 9371/10519 [2:30:25<18:15,  1.05it/s][NeMo W 2026-06-19 09:40:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 89%|████████▉ | 9372/10519 [2:30:26<17:57,  1.06it/s][NeMo W 2026-06-19 09:40:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.33it/s]
 89%|████████▉ | 9373/10519 [2:30:27<17:52,  1.07it/s][NeMo W 2026-06-19 09:40:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 89%|████████▉ | 9374/10519 [2:30:28<18:33,  1.03it/s][NeMo W 2026-06-19 09:40:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 89%|████████▉ | 9375/10519 [2:30:29<18:54,  1.01it/s][NeMo W 2026-06-19 09:40:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 89%|████████▉ | 9376/10519 [2:30:30<18:26,  1.03it/s][NeMo W 2026-06-19 09:40:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.83it/s]
 89%|████████▉ | 9377/10519 [2:30:31<18:39,  1.02it/s][NeMo W 2026-06-19 09:40:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.30it/s]
 89%|████████▉ | 9378/10519 [2:30:32<18:48,  1.01it/s][NeMo W 2026-06-19 09:40:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 89%|████████▉ | 9379/10519 [2:30:33<19:00,  1.00s/it][NeMo W 2026-06-19 09:40:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.24it/s]
 89%|████████▉ | 9380/10519 [2:30:34<18:13,  1.04it/s][NeMo W 2026-06-19 09:40:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9400 samples

[NeMo W 2026-06-19 09:40:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 89%|████████▉ | 9401/10519 [2:30:56<24:22,  1.31s/it][NeMo W 2026-06-19 09:40:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 89%|████████▉ | 9402/10519 [2:30:57<21:21,  1.15s/it][NeMo W 2026-06-19 09:40:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.80it/s]
 89%|████████▉ | 9403/10519 [2:30:58<21:02,  1.13s/it][NeMo W 2026-06-19 09:40:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.01it/s]
 89%|████████▉ | 9404/10519 [2:30:59<20:33,  1.11s/it][NeMo W 2026-06-19 09:40:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.21it/s]
 89%|████████▉ | 9405/10519 [2:31:00<20:09,  1.09s/it][NeMo W 2026-06-19 09:40:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.12it/s]
 89%|████████▉ | 9406/10519 [2:31:01<20:23,  1.10s/it][NeMo W 2026-06-19 09:40:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.84it/s]
 89%|████████▉ | 9407/10519 [2:31:03<20:25,  1.10s/it][NeMo W 2026-06-19 09:40:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 89%|████████▉ | 9408/10519 [2:31:04<20:33,  1.11s/it][NeMo W 2026-06-19 09:40:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.80it/s]
 89%|████████▉ | 9409/10519 [2:31:04<18:25,  1.00it/s][NeMo W 2026-06-19 09:40:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 89%|████████▉ | 9410/10519 [2:31:05<18:17,  1.01it/s][NeMo W 2026-06-19 09:40:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.75it/s]
 89%|████████▉ | 9411/10519 [2:31:06<16:30,  1.12it/s][NeMo W 2026-06-19 09:40:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 89%|████████▉ | 9412/10519 [2:31:07<16:53,  1.09it/s][NeMo W 2026-06-19 09:40:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 89%|████████▉ | 9413/10519 [2:31:08<17:07,  1.08it/s][NeMo W 2026-06-19 09:40:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.78it/s]
 89%|████████▉ | 9414/10519 [2:31:09<16:11,  1.14it/s][NeMo W 2026-06-19 09:40:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 90%|████████▉ | 9415/10519 [2:31:10<15:43,  1.17it/s][NeMo W 2026-06-19 09:40:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.48it/s]
 90%|████████▉ | 9416/10519 [2:31:11<16:38,  1.10it/s][NeMo W 2026-06-19 09:40:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 90%|████████▉ | 9417/10519 [2:31:12<17:09,  1.07it/s][NeMo W 2026-06-19 09:40:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 90%|████████▉ | 9418/10519 [2:31:13<16:58,  1.08it/s][NeMo W 2026-06-19 09:40:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.03it/s]
 90%|████████▉ | 9419/10519 [2:31:13<17:02,  1.08it/s][NeMo W 2026-06-19 09:40:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 90%|████████▉ | 9420/10519 [2:31:14<16:46,  1.09it/s][NeMo W 2026-06-19 09:40:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 90%|████████▉ | 9421/10519 [2:31:15<17:33,  1.04it/s][NeMo W 2026-06-19 09:40:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 90%|████████▉ | 9422/10519 [2:31:16<17:30,  1.04it/s][NeMo W 2026-06-19 09:40:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 90%|████████▉ | 9423/10519 [2:31:17<17:40,  1.03it/s][NeMo W 2026-06-19 09:40:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:40:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 90%|████████▉ | 9424/10519 [2:31:18<17:39,  1.03it/s][NeMo W 2026-06-19 09:41:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 90%|████████▉ | 9425/10519 [2:31:19<17:38,  1.03it/s][NeMo W 2026-06-19 09:41:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 90%|████████▉ | 9426/10519 [2:31:20<17:32,  1.04it/s][NeMo W 2026-06-19 09:41:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 90%|████████▉ | 9427/10519 [2:31:21<17:14,  1.06it/s][NeMo W 2026-06-19 09:41:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 90%|████████▉ | 9428/10519 [2:31:22<18:03,  1.01it/s][NeMo W 2026-06-19 09:41:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 90%|████████▉ | 9429/10519 [2:31:23<18:08,  1.00it/s][NeMo W 2026-06-19 09:41:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.40it/s]

Checkpoint saved: 9450 samples

[NeMo W 2026-06-19 09:41:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.96it/s]
 90%|████████▉ | 9451/10519 [2:31:45<23:58,  1.35s/it][NeMo W 2026-06-19 09:41:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.51it/s]
 90%|████████▉ | 9452/10519 [2:31:46<20:58,  1.18s/it][NeMo W 2026-06-19 09:41:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 90%|████████▉ | 9453/10519 [2:31:47<18:25,  1.04s/it][NeMo W 2026-06-19 09:41:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 90%|████████▉ | 9454/10519 [2:31:48<18:05,  1.02s/it][NeMo W 2026-06-19 09:41:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 90%|████████▉ | 9455/10519 [2:31:49<17:40,  1.00it/s][NeMo W 2026-06-19 09:41:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 90%|████████▉ | 9456/10519 [2:31:50<17:45,  1.00s/it][NeMo W 2026-06-19 09:41:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 90%|████████▉ | 9457/10519 [2:31:50<17:34,  1.01it/s][NeMo W 2026-06-19 09:41:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 90%|████████▉ | 9458/10519 [2:31:51<17:32,  1.01it/s][NeMo W 2026-06-19 09:41:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 90%|████████▉ | 9459/10519 [2:31:52<17:19,  1.02it/s][NeMo W 2026-06-19 09:41:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.34it/s]
 90%|████████▉ | 9460/10519 [2:31:53<16:45,  1.05it/s][NeMo W 2026-06-19 09:41:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 90%|████████▉ | 9461/10519 [2:31:54<16:36,  1.06it/s][NeMo W 2026-06-19 09:41:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 90%|████████▉ | 9462/10519 [2:31:55<16:40,  1.06it/s][NeMo W 2026-06-19 09:41:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 90%|████████▉ | 9463/10519 [2:31:56<16:04,  1.10it/s][NeMo W 2026-06-19 09:41:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 90%|████████▉ | 9464/10519 [2:31:57<16:30,  1.06it/s][NeMo W 2026-06-19 09:41:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.69it/s]
 90%|████████▉ | 9465/10519 [2:31:58<16:11,  1.09it/s][NeMo W 2026-06-19 09:41:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 90%|████████▉ | 9466/10519 [2:31:59<16:33,  1.06it/s][NeMo W 2026-06-19 09:41:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.30it/s]
 90%|████████▉ | 9467/10519 [2:32:00<16:43,  1.05it/s][NeMo W 2026-06-19 09:41:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 90%|█████████ | 9468/10519 [2:32:01<16:41,  1.05it/s][NeMo W 2026-06-19 09:41:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 90%|█████████ | 9469/10519 [2:32:02<16:45,  1.04it/s][NeMo W 2026-06-19 09:41:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.49it/s]
 90%|█████████ | 9470/10519 [2:32:03<16:32,  1.06it/s][NeMo W 2026-06-19 09:41:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 90%|█████████ | 9471/10519 [2:32:04<16:38,  1.05it/s][NeMo W 2026-06-19 09:41:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.01it/s]
 90%|█████████ | 9472/10519 [2:32:05<16:37,  1.05it/s][NeMo W 2026-06-19 09:41:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.26it/s]
 90%|█████████ | 9473/10519 [2:32:06<16:36,  1.05it/s][NeMo W 2026-06-19 09:41:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.17it/s]
 90%|█████████ | 9474/10519 [2:32:07<16:29,  1.06it/s][NeMo W 2026-06-19 09:41:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 90%|█████████ | 9475/10519 [2:32:07<16:30,  1.05it/s][NeMo W 2026-06-19 09:41:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 90%|█████████ | 9476/10519 [2:32:09<17:00,  1.02it/s][NeMo W 2026-06-19 09:41:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 90%|█████████ | 9477/10519 [2:32:10<17:01,  1.02it/s][NeMo W 2026-06-19 09:41:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 90%|█████████ | 9478/10519 [2:32:10<16:59,  1.02it/s][NeMo W 2026-06-19 09:41:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.46it/s]
 90%|█████████ | 9479/10519 [2:32:11<16:17,  1.06it/s][NeMo W 2026-06-19 09:41:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:41:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 90%|█████████ | 9480/10519 [2:32:12<16:17,  1.06it/s][NeMo W 2026-06-19 09:41:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9500 samples

[NeMo W 2026-06-19 09:42:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.10it/s]
 90%|█████████ | 9501/10519 [2:32:34<19:34,  1.15s/it][NeMo W 2026-06-19 09:42:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.20it/s]
 90%|█████████ | 9502/10519 [2:32:35<18:51,  1.11s/it][NeMo W 2026-06-19 09:42:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.30it/s]
 90%|█████████ | 9503/10519 [2:32:36<17:15,  1.02s/it][NeMo W 2026-06-19 09:42:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.19it/s]
 90%|█████████ | 9504/10519 [2:32:37<17:31,  1.04s/it][NeMo W 2026-06-19 09:42:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.51it/s]
 90%|█████████ | 9505/10519 [2:32:38<17:48,  1.05s/it][NeMo W 2026-06-19 09:42:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.62it/s]
 90%|█████████ | 9506/10519 [2:32:39<16:12,  1.04it/s][NeMo W 2026-06-19 09:42:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.87it/s]
 90%|█████████ | 9507/10519 [2:32:39<16:04,  1.05it/s][NeMo W 2026-06-19 09:42:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
 90%|█████████ | 9508/10519 [2:32:41<16:52,  1.00s/it][NeMo W 2026-06-19 09:42:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 90%|█████████ | 9509/10519 [2:32:41<16:14,  1.04it/s][NeMo W 2026-06-19 09:42:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 90%|█████████ | 9510/10519 [2:32:42<15:00,  1.12it/s][NeMo W 2026-06-19 09:42:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 90%|█████████ | 9511/10519 [2:32:43<15:55,  1.06it/s][NeMo W 2026-06-19 09:42:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.22it/s]
 90%|█████████ | 9512/10519 [2:32:44<14:49,  1.13it/s][NeMo W 2026-06-19 09:42:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 90%|█████████ | 9513/10519 [2:32:45<15:24,  1.09it/s][NeMo W 2026-06-19 09:42:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 90%|█████████ | 9514/10519 [2:32:46<14:50,  1.13it/s][NeMo W 2026-06-19 09:42:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.05it/s]
 90%|█████████ | 9515/10519 [2:32:47<15:06,  1.11it/s][NeMo W 2026-06-19 09:42:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 90%|█████████ | 9516/10519 [2:32:48<14:22,  1.16it/s][NeMo W 2026-06-19 09:42:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 90%|█████████ | 9517/10519 [2:32:48<14:57,  1.12it/s][NeMo W 2026-06-19 09:42:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 90%|█████████ | 9518/10519 [2:32:49<15:22,  1.08it/s][NeMo W 2026-06-19 09:42:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 90%|█████████ | 9519/10519 [2:32:50<15:17,  1.09it/s][NeMo W 2026-06-19 09:42:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 91%|█████████ | 9520/10519 [2:32:51<15:12,  1.10it/s][NeMo W 2026-06-19 09:42:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.90it/s]
 91%|█████████ | 9521/10519 [2:32:52<15:20,  1.08it/s][NeMo W 2026-06-19 09:42:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.91it/s]
 91%|█████████ | 9522/10519 [2:32:53<14:46,  1.12it/s][NeMo W 2026-06-19 09:42:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.37it/s]
 91%|█████████ | 9523/10519 [2:32:54<14:49,  1.12it/s][NeMo W 2026-06-19 09:42:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 91%|█████████ | 9524/10519 [2:32:55<15:13,  1.09it/s][NeMo W 2026-06-19 09:42:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 91%|█████████ | 9525/10519 [2:32:56<15:22,  1.08it/s][NeMo W 2026-06-19 09:42:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 91%|█████████ | 9526/10519 [2:32:57<15:28,  1.07it/s][NeMo W 2026-06-19 09:42:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.33it/s]
 91%|█████████ | 9527/10519 [2:32:58<14:39,  1.13it/s][NeMo W 2026-06-19 09:42:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 91%|█████████ | 9528/10519 [2:32:59<14:55,  1.11it/s][NeMo W 2026-06-19 09:42:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.37it/s]
 91%|█████████ | 9529/10519 [2:32:59<14:50,  1.11it/s][NeMo W 2026-06-19 09:42:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:42:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 91%|█████████ | 9530/10519 [2:33:00<14:59,  1.10it/s][NeMo W 2026-06-19 09:42:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9550 samples

[NeMo W 2026-06-19 09:43:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 91%|█████████ | 9551/10519 [2:33:22<21:00,  1.30s/it][NeMo W 2026-06-19 09:43:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.22it/s]
 91%|█████████ | 9552/10519 [2:33:23<19:42,  1.22s/it][NeMo W 2026-06-19 09:43:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.87it/s]
 91%|█████████ | 9553/10519 [2:33:24<18:00,  1.12s/it][NeMo W 2026-06-19 09:43:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 91%|█████████ | 9554/10519 [2:33:25<16:12,  1.01s/it][NeMo W 2026-06-19 09:43:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 91%|█████████ | 9555/10519 [2:33:26<15:46,  1.02it/s][NeMo W 2026-06-19 09:43:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.49it/s]
 91%|█████████ | 9556/10519 [2:33:27<15:39,  1.03it/s][NeMo W 2026-06-19 09:43:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.01it/s]
 91%|█████████ | 9557/10519 [2:33:27<15:08,  1.06it/s][NeMo W 2026-06-19 09:43:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.17it/s]
 91%|█████████ | 9558/10519 [2:33:28<15:31,  1.03it/s][NeMo W 2026-06-19 09:43:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 91%|█████████ | 9559/10519 [2:33:29<15:19,  1.04it/s][NeMo W 2026-06-19 09:43:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 91%|█████████ | 9560/10519 [2:33:30<14:37,  1.09it/s][NeMo W 2026-06-19 09:43:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.94it/s]
 91%|█████████ | 9561/10519 [2:33:31<14:24,  1.11it/s][NeMo W 2026-06-19 09:43:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.83it/s]
 91%|█████████ | 9562/10519 [2:33:32<13:42,  1.16it/s][NeMo W 2026-06-19 09:43:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 91%|█████████ | 9563/10519 [2:33:33<13:54,  1.15it/s][NeMo W 2026-06-19 09:43:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 91%|█████████ | 9564/10519 [2:33:34<14:02,  1.13it/s][NeMo W 2026-06-19 09:43:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 91%|█████████ | 9565/10519 [2:33:35<14:18,  1.11it/s][NeMo W 2026-06-19 09:43:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 91%|█████████ | 9566/10519 [2:33:36<14:30,  1.10it/s][NeMo W 2026-06-19 09:43:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.15it/s]
 91%|█████████ | 9567/10519 [2:33:37<14:41,  1.08it/s][NeMo W 2026-06-19 09:43:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 91%|█████████ | 9568/10519 [2:33:37<13:48,  1.15it/s][NeMo W 2026-06-19 09:43:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 91%|█████████ | 9569/10519 [2:33:38<14:54,  1.06it/s][NeMo W 2026-06-19 09:43:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 91%|█████████ | 9570/10519 [2:33:39<14:03,  1.12it/s][NeMo W 2026-06-19 09:43:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 91%|█████████ | 9571/10519 [2:33:40<14:21,  1.10it/s][NeMo W 2026-06-19 09:43:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.27it/s]
 91%|█████████ | 9572/10519 [2:33:41<13:19,  1.18it/s][NeMo W 2026-06-19 09:43:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 91%|█████████ | 9573/10519 [2:33:42<13:14,  1.19it/s][NeMo W 2026-06-19 09:43:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 91%|█████████ | 9574/10519 [2:33:43<13:57,  1.13it/s][NeMo W 2026-06-19 09:43:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.94it/s]
 91%|█████████ | 9575/10519 [2:33:43<13:05,  1.20it/s][NeMo W 2026-06-19 09:43:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.47it/s]
 91%|█████████ | 9576/10519 [2:33:44<14:01,  1.12it/s][NeMo W 2026-06-19 09:43:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 91%|█████████ | 9577/10519 [2:33:45<14:26,  1.09it/s][NeMo W 2026-06-19 09:43:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 91%|█████████ | 9578/10519 [2:33:46<14:38,  1.07it/s][NeMo W 2026-06-19 09:43:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.81it/s]
 91%|█████████ | 9579/10519 [2:33:47<14:54,  1.05it/s][NeMo W 2026-06-19 09:43:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 91%|█████████ | 9580/10519 [2:33:48<14:50,  1.06it/s][NeMo W 2026-06-19 09:43:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9600 samples

[NeMo W 2026-06-19 09:43:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.94it/s]
 91%|█████████▏| 9601/10519 [2:34:10<19:50,  1.30s/it][NeMo W 2026-06-19 09:43:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 91%|█████████▏| 9602/10519 [2:34:11<18:16,  1.20s/it][NeMo W 2026-06-19 09:43:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 91%|█████████▏| 9603/10519 [2:34:12<17:17,  1.13s/it][NeMo W 2026-06-19 09:43:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 91%|█████████▏| 9604/10519 [2:34:13<16:19,  1.07s/it][NeMo W 2026-06-19 09:43:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.69it/s]
 91%|█████████▏| 9605/10519 [2:34:14<16:37,  1.09s/it][NeMo W 2026-06-19 09:43:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.20it/s]
 91%|█████████▏| 9606/10519 [2:34:15<16:40,  1.10s/it][NeMo W 2026-06-19 09:43:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 91%|█████████▏| 9607/10519 [2:34:16<15:59,  1.05s/it][NeMo W 2026-06-19 09:43:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 91%|█████████▏| 9608/10519 [2:34:17<15:29,  1.02s/it][NeMo W 2026-06-19 09:43:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.05it/s]
 91%|█████████▏| 9609/10519 [2:34:18<15:07,  1.00it/s][NeMo W 2026-06-19 09:43:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:43:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.89it/s]
 91%|█████████▏| 9610/10519 [2:34:19<14:48,  1.02it/s][NeMo W 2026-06-19 09:44:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 91%|█████████▏| 9611/10519 [2:34:19<14:32,  1.04it/s][NeMo W 2026-06-19 09:44:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.92it/s]
 91%|█████████▏| 9612/10519 [2:34:20<14:20,  1.05it/s][NeMo W 2026-06-19 09:44:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 91%|█████████▏| 9613/10519 [2:34:21<14:11,  1.06it/s][NeMo W 2026-06-19 09:44:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.14it/s]
 91%|█████████▏| 9614/10519 [2:34:22<14:28,  1.04it/s][NeMo W 2026-06-19 09:44:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 91%|█████████▏| 9615/10519 [2:34:23<14:15,  1.06it/s][NeMo W 2026-06-19 09:44:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 91%|█████████▏| 9616/10519 [2:34:24<13:05,  1.15it/s][NeMo W 2026-06-19 09:44:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.41it/s]
 91%|█████████▏| 9617/10519 [2:34:25<13:10,  1.14it/s][NeMo W 2026-06-19 09:44:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.91it/s]
 91%|█████████▏| 9618/10519 [2:34:26<13:18,  1.13it/s][NeMo W 2026-06-19 09:44:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 91%|█████████▏| 9619/10519 [2:34:27<13:41,  1.10it/s][NeMo W 2026-06-19 09:44:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 91%|█████████▏| 9620/10519 [2:34:28<14:29,  1.03it/s][NeMo W 2026-06-19 09:44:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 91%|█████████▏| 9621/10519 [2:34:29<14:46,  1.01it/s][NeMo W 2026-06-19 09:44:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 91%|█████████▏| 9622/10519 [2:34:30<14:23,  1.04it/s][NeMo W 2026-06-19 09:44:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.64it/s]
 91%|█████████▏| 9623/10519 [2:34:31<13:55,  1.07it/s][NeMo W 2026-06-19 09:44:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 91%|█████████▏| 9624/10519 [2:34:32<14:37,  1.02it/s][NeMo W 2026-06-19 09:44:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.44it/s]
 92%|█████████▏| 9625/10519 [2:34:33<15:12,  1.02s/it][NeMo W 2026-06-19 09:44:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 92%|█████████▏| 9626/10519 [2:34:34<14:38,  1.02it/s][NeMo W 2026-06-19 09:44:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.76it/s]
 92%|█████████▏| 9627/10519 [2:34:35<14:16,  1.04it/s][NeMo W 2026-06-19 09:44:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.94it/s]
 92%|█████████▏| 9628/10519 [2:34:36<14:05,  1.05it/s][NeMo W 2026-06-19 09:44:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.16it/s]
 92%|█████████▏| 9629/10519 [2:34:36<13:52,  1.07it/s][NeMo W 2026-06-19 09:44:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.61it/s]
 92%|█████████▏| 9630/10519 [2:34:37<13:49,  1.07it/s][NeMo W 2026-06-19 09:44:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9650 samples

[NeMo W 2026-06-19 09:44:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
 92%|█████████▏| 9651/10519 [2:34:59<20:49,  1.44s/it][NeMo W 2026-06-19 09:44:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.17it/s]
 92%|█████████▏| 9652/10519 [2:35:00<18:55,  1.31s/it][NeMo W 2026-06-19 09:44:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 92%|█████████▏| 9653/10519 [2:35:01<17:37,  1.22s/it][NeMo W 2026-06-19 09:44:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 92%|█████████▏| 9654/10519 [2:35:02<16:14,  1.13s/it][NeMo W 2026-06-19 09:44:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 92%|█████████▏| 9655/10519 [2:35:03<14:41,  1.02s/it][NeMo W 2026-06-19 09:44:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 92%|█████████▏| 9656/10519 [2:35:04<14:09,  1.02it/s][NeMo W 2026-06-19 09:44:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 92%|█████████▏| 9657/10519 [2:35:05<13:53,  1.03it/s][NeMo W 2026-06-19 09:44:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.46it/s]
 92%|█████████▏| 9658/10519 [2:35:06<12:47,  1.12it/s][NeMo W 2026-06-19 09:44:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.62it/s]
 92%|█████████▏| 9659/10519 [2:35:07<12:55,  1.11it/s][NeMo W 2026-06-19 09:44:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 92%|█████████▏| 9660/10519 [2:35:08<12:51,  1.11it/s][NeMo W 2026-06-19 09:44:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 92%|█████████▏| 9661/10519 [2:35:08<12:16,  1.16it/s][NeMo W 2026-06-19 09:44:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 92%|█████████▏| 9662/10519 [2:35:09<12:05,  1.18it/s][NeMo W 2026-06-19 09:44:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.98it/s]
 92%|█████████▏| 9663/10519 [2:35:10<11:51,  1.20it/s][NeMo W 2026-06-19 09:44:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 92%|█████████▏| 9664/10519 [2:35:11<12:19,  1.16it/s][NeMo W 2026-06-19 09:44:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 92%|█████████▏| 9665/10519 [2:35:12<12:39,  1.12it/s][NeMo W 2026-06-19 09:44:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 92%|█████████▏| 9666/10519 [2:35:13<12:46,  1.11it/s][NeMo W 2026-06-19 09:44:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 92%|█████████▏| 9667/10519 [2:35:14<12:34,  1.13it/s][NeMo W 2026-06-19 09:44:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.66it/s]
 92%|█████████▏| 9668/10519 [2:35:14<12:28,  1.14it/s][NeMo W 2026-06-19 09:44:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 92%|█████████▏| 9669/10519 [2:35:15<12:21,  1.15it/s][NeMo W 2026-06-19 09:44:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.41it/s]
 92%|█████████▏| 9670/10519 [2:35:16<12:33,  1.13it/s][NeMo W 2026-06-19 09:44:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 92%|█████████▏| 9671/10519 [2:35:17<12:49,  1.10it/s][NeMo W 2026-06-19 09:44:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:44:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.80it/s]
 92%|█████████▏| 9672/10519 [2:35:18<12:57,  1.09it/s][NeMo W 2026-06-19 09:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 92%|█████████▏| 9673/10519 [2:35:19<12:54,  1.09it/s][NeMo W 2026-06-19 09:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.89it/s]
 92%|█████████▏| 9674/10519 [2:35:20<12:11,  1.16it/s][NeMo W 2026-06-19 09:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.32it/s]
 92%|█████████▏| 9675/10519 [2:35:21<11:41,  1.20it/s][NeMo W 2026-06-19 09:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.99it/s]
 92%|█████████▏| 9676/10519 [2:35:21<12:09,  1.16it/s][NeMo W 2026-06-19 09:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 92%|█████████▏| 9677/10519 [2:35:22<12:28,  1.13it/s][NeMo W 2026-06-19 09:45:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 92%|█████████▏| 9678/10519 [2:35:23<12:32,  1.12it/s][NeMo W 2026-06-19 09:45:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 92%|█████████▏| 9679/10519 [2:35:24<12:43,  1.10it/s][NeMo W 2026-06-19 09:45:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.16it/s]

Checkpoint saved: 9700 samples

[NeMo W 2026-06-19 09:45:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 92%|█████████▏| 9701/10519 [2:35:46<15:27,  1.13s/it][NeMo W 2026-06-19 09:45:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.18it/s]
 92%|█████████▏| 9702/10519 [2:35:47<14:30,  1.07s/it][NeMo W 2026-06-19 09:45:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.38it/s]
 92%|█████████▏| 9703/10519 [2:35:48<13:58,  1.03s/it][NeMo W 2026-06-19 09:45:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 92%|█████████▏| 9704/10519 [2:35:49<13:34,  1.00it/s][NeMo W 2026-06-19 09:45:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 92%|█████████▏| 9705/10519 [2:35:50<13:05,  1.04it/s][NeMo W 2026-06-19 09:45:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 92%|█████████▏| 9706/10519 [2:35:51<13:13,  1.02it/s][NeMo W 2026-06-19 09:45:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.24it/s]
 92%|█████████▏| 9707/10519 [2:35:52<13:06,  1.03it/s][NeMo W 2026-06-19 09:45:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 92%|█████████▏| 9708/10519 [2:35:53<14:38,  1.08s/it][NeMo W 2026-06-19 09:45:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.94it/s]
 92%|█████████▏| 9709/10519 [2:35:54<13:40,  1.01s/it][NeMo W 2026-06-19 09:45:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 92%|█████████▏| 9710/10519 [2:35:55<14:07,  1.05s/it][NeMo W 2026-06-19 09:45:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 92%|█████████▏| 9711/10519 [2:35:56<13:50,  1.03s/it][NeMo W 2026-06-19 09:45:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 92%|█████████▏| 9712/10519 [2:35:57<12:59,  1.04it/s][NeMo W 2026-06-19 09:45:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.12it/s]
 92%|█████████▏| 9713/10519 [2:35:58<13:12,  1.02it/s][NeMo W 2026-06-19 09:45:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.58it/s]
 92%|█████████▏| 9714/10519 [2:35:59<12:18,  1.09it/s][NeMo W 2026-06-19 09:45:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 92%|█████████▏| 9715/10519 [2:35:59<11:23,  1.18it/s][NeMo W 2026-06-19 09:45:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.33it/s]
 92%|█████████▏| 9716/10519 [2:36:00<11:43,  1.14it/s][NeMo W 2026-06-19 09:45:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.41it/s]
 92%|█████████▏| 9717/10519 [2:36:01<11:55,  1.12it/s][NeMo W 2026-06-19 09:45:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.03it/s]
 92%|█████████▏| 9718/10519 [2:36:02<11:59,  1.11it/s][NeMo W 2026-06-19 09:45:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 92%|█████████▏| 9719/10519 [2:36:03<12:01,  1.11it/s][NeMo W 2026-06-19 09:45:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.28it/s]
 92%|█████████▏| 9720/10519 [2:36:04<12:18,  1.08it/s][NeMo W 2026-06-19 09:45:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.31it/s]
 92%|█████████▏| 9721/10519 [2:36:05<12:35,  1.06it/s][NeMo W 2026-06-19 09:45:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.64it/s]
 92%|█████████▏| 9722/10519 [2:36:06<13:03,  1.02it/s][NeMo W 2026-06-19 09:45:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 92%|█████████▏| 9723/10519 [2:36:07<12:16,  1.08it/s][NeMo W 2026-06-19 09:45:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.70it/s]
 92%|█████████▏| 9724/10519 [2:36:08<12:13,  1.08it/s][NeMo W 2026-06-19 09:45:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.93it/s]
 92%|█████████▏| 9725/10519 [2:36:09<11:58,  1.11it/s][NeMo W 2026-06-19 09:45:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 92%|█████████▏| 9726/10519 [2:36:09<11:24,  1.16it/s][NeMo W 2026-06-19 09:45:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.02it/s]
 92%|█████████▏| 9727/10519 [2:36:10<10:58,  1.20it/s][NeMo W 2026-06-19 09:45:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 92%|█████████▏| 9728/10519 [2:36:11<11:59,  1.10it/s][NeMo W 2026-06-19 09:45:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.68it/s]
 92%|█████████▏| 9729/10519 [2:36:12<12:00,  1.10it/s][NeMo W 2026-06-19 09:45:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:45:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]

Checkpoint saved: 9750 samples

[NeMo W 2026-06-19 09:46:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 93%|█████████▎| 9751/10519 [2:36:35<18:32,  1.45s/it][NeMo W 2026-06-19 09:46:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 93%|█████████▎| 9752/10519 [2:36:36<17:06,  1.34s/it][NeMo W 2026-06-19 09:46:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 93%|█████████▎| 9753/10519 [2:36:37<15:25,  1.21s/it][NeMo W 2026-06-19 09:46:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.54it/s]
 93%|█████████▎| 9754/10519 [2:36:38<14:28,  1.14s/it][NeMo W 2026-06-19 09:46:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 93%|█████████▎| 9755/10519 [2:36:39<13:39,  1.07s/it][NeMo W 2026-06-19 09:46:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 93%|█████████▎| 9756/10519 [2:36:40<13:10,  1.04s/it][NeMo W 2026-06-19 09:46:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.42it/s]
 93%|█████████▎| 9757/10519 [2:36:41<12:41,  1.00it/s][NeMo W 2026-06-19 09:46:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 93%|█████████▎| 9758/10519 [2:36:42<12:24,  1.02it/s][NeMo W 2026-06-19 09:46:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 93%|█████████▎| 9759/10519 [2:36:43<11:17,  1.12it/s][NeMo W 2026-06-19 09:46:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
 93%|█████████▎| 9760/10519 [2:36:43<11:27,  1.10it/s][NeMo W 2026-06-19 09:46:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.57it/s]
 93%|█████████▎| 9761/10519 [2:36:44<11:36,  1.09it/s][NeMo W 2026-06-19 09:46:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.13it/s]
 93%|█████████▎| 9762/10519 [2:36:45<11:45,  1.07it/s][NeMo W 2026-06-19 09:46:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.31it/s]
 93%|█████████▎| 9763/10519 [2:36:46<11:55,  1.06it/s][NeMo W 2026-06-19 09:46:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 93%|█████████▎| 9764/10519 [2:36:47<11:43,  1.07it/s][NeMo W 2026-06-19 09:46:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.38it/s]
 93%|█████████▎| 9765/10519 [2:36:48<11:20,  1.11it/s][NeMo W 2026-06-19 09:46:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.23it/s]
 93%|█████████▎| 9766/10519 [2:36:49<11:23,  1.10it/s][NeMo W 2026-06-19 09:46:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 93%|█████████▎| 9767/10519 [2:36:50<12:07,  1.03it/s][NeMo W 2026-06-19 09:46:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.41it/s]
 93%|█████████▎| 9768/10519 [2:36:51<12:14,  1.02it/s][NeMo W 2026-06-19 09:46:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 93%|█████████▎| 9769/10519 [2:36:52<12:08,  1.03it/s][NeMo W 2026-06-19 09:46:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.92it/s]
 93%|█████████▎| 9770/10519 [2:36:53<12:00,  1.04it/s][NeMo W 2026-06-19 09:46:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 93%|█████████▎| 9771/10519 [2:36:54<12:55,  1.04s/it][NeMo W 2026-06-19 09:46:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 93%|█████████▎| 9772/10519 [2:36:55<12:13,  1.02it/s][NeMo W 2026-06-19 09:46:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.14it/s]
 93%|█████████▎| 9773/10519 [2:36:56<12:00,  1.04it/s][NeMo W 2026-06-19 09:46:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.43it/s]
 93%|█████████▎| 9774/10519 [2:36:57<11:52,  1.05it/s][NeMo W 2026-06-19 09:46:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 93%|█████████▎| 9775/10519 [2:36:58<11:42,  1.06it/s][NeMo W 2026-06-19 09:46:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.58it/s]
 93%|█████████▎| 9776/10519 [2:36:59<11:39,  1.06it/s][NeMo W 2026-06-19 09:46:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.85it/s]
 93%|█████████▎| 9777/10519 [2:37:00<11:26,  1.08it/s][NeMo W 2026-06-19 09:46:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.74it/s]
 93%|█████████▎| 9778/10519 [2:37:01<11:31,  1.07it/s][NeMo W 2026-06-19 09:46:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 93%|█████████▎| 9779/10519 [2:37:02<11:28,  1.08it/s][NeMo W 2026-06-19 09:46:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:46:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 93%|█████████▎| 9780/10519 [2:37:03<11:29,  1.07it/s][NeMo W 2026-06-19 09:46:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 9800 samples

[NeMo W 2026-06-19 09:47:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
 93%|█████████▎| 9801/10519 [2:37:23<14:21,  1.20s/it][NeMo W 2026-06-19 09:47:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 93%|█████████▎| 9802/10519 [2:37:24<13:39,  1.14s/it][NeMo W 2026-06-19 09:47:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.83it/s]
 93%|█████████▎| 9803/10519 [2:37:25<13:31,  1.13s/it][NeMo W 2026-06-19 09:47:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.79it/s]
 93%|█████████▎| 9804/10519 [2:37:26<13:01,  1.09s/it][NeMo W 2026-06-19 09:47:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 93%|█████████▎| 9805/10519 [2:37:27<12:09,  1.02s/it][NeMo W 2026-06-19 09:47:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 93%|█████████▎| 9806/10519 [2:37:28<11:43,  1.01it/s][NeMo W 2026-06-19 09:47:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 93%|█████████▎| 9807/10519 [2:37:29<12:27,  1.05s/it][NeMo W 2026-06-19 09:47:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.12it/s]
 93%|█████████▎| 9808/10519 [2:37:30<12:08,  1.02s/it][NeMo W 2026-06-19 09:47:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.86it/s]
 93%|█████████▎| 9809/10519 [2:37:31<11:13,  1.05it/s][NeMo W 2026-06-19 09:47:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.27it/s]
 93%|█████████▎| 9810/10519 [2:37:32<11:14,  1.05it/s][NeMo W 2026-06-19 09:47:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 93%|█████████▎| 9811/10519 [2:37:33<10:59,  1.07it/s][NeMo W 2026-06-19 09:47:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 93%|█████████▎| 9812/10519 [2:37:34<11:00,  1.07it/s][NeMo W 2026-06-19 09:47:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 93%|█████████▎| 9813/10519 [2:37:35<11:31,  1.02it/s][NeMo W 2026-06-19 09:47:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 93%|█████████▎| 9814/10519 [2:37:36<10:56,  1.07it/s][NeMo W 2026-06-19 09:47:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 93%|█████████▎| 9815/10519 [2:37:37<10:15,  1.14it/s][NeMo W 2026-06-19 09:47:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.93it/s]
 93%|█████████▎| 9816/10519 [2:37:38<10:26,  1.12it/s][NeMo W 2026-06-19 09:47:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 93%|█████████▎| 9817/10519 [2:37:38<10:36,  1.10it/s][NeMo W 2026-06-19 09:47:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.61it/s]
 93%|█████████▎| 9818/10519 [2:37:39<10:09,  1.15it/s][NeMo W 2026-06-19 09:47:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.33it/s]
 93%|█████████▎| 9819/10519 [2:37:40<10:25,  1.12it/s][NeMo W 2026-06-19 09:47:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.60it/s]
 93%|█████████▎| 9820/10519 [2:37:41<10:22,  1.12it/s][NeMo W 2026-06-19 09:47:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.58it/s]
 93%|█████████▎| 9821/10519 [2:37:42<10:33,  1.10it/s][NeMo W 2026-06-19 09:47:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 93%|█████████▎| 9822/10519 [2:37:43<10:41,  1.09it/s][NeMo W 2026-06-19 09:47:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.28it/s]
 93%|█████████▎| 9823/10519 [2:37:44<10:33,  1.10it/s][NeMo W 2026-06-19 09:47:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 93%|█████████▎| 9824/10519 [2:37:45<10:37,  1.09it/s][NeMo W 2026-06-19 09:47:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.59it/s]
 93%|█████████▎| 9825/10519 [2:37:46<10:52,  1.06it/s][NeMo W 2026-06-19 09:47:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 93%|█████████▎| 9826/10519 [2:37:47<10:46,  1.07it/s][NeMo W 2026-06-19 09:47:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.37it/s]
 93%|█████████▎| 9827/10519 [2:37:48<10:54,  1.06it/s][NeMo W 2026-06-19 09:47:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.56it/s]
 93%|█████████▎| 9828/10519 [2:37:49<11:04,  1.04it/s][NeMo W 2026-06-19 09:47:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.63it/s]
 93%|█████████▎| 9829/10519 [2:37:50<10:56,  1.05it/s][NeMo W 2026-06-19 09:47:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.19it/s]

Checkpoint saved: 9850 samples

[NeMo W 2026-06-19 09:47:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.73it/s]
 94%|█████████▎| 9851/10519 [2:38:12<16:17,  1.46s/it][NeMo W 2026-06-19 09:47:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.93it/s]
 94%|█████████▎| 9852/10519 [2:38:13<14:04,  1.27s/it][NeMo W 2026-06-19 09:47:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 94%|█████████▎| 9853/10519 [2:38:14<13:07,  1.18s/it][NeMo W 2026-06-19 09:47:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.19it/s]
 94%|█████████▎| 9854/10519 [2:38:15<12:17,  1.11s/it][NeMo W 2026-06-19 09:47:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 94%|█████████▎| 9855/10519 [2:38:16<11:36,  1.05s/it][NeMo W 2026-06-19 09:47:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.46it/s]
 94%|█████████▎| 9856/10519 [2:38:16<10:30,  1.05it/s][NeMo W 2026-06-19 09:47:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 94%|█████████▎| 9857/10519 [2:38:18<11:06,  1.01s/it][NeMo W 2026-06-19 09:47:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:47:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 94%|█████████▎| 9858/10519 [2:38:18<10:44,  1.03it/s][NeMo W 2026-06-19 09:48:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.70it/s]
 94%|█████████▎| 9859/10519 [2:38:19<10:01,  1.10it/s][NeMo W 2026-06-19 09:48:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.79it/s]
 94%|█████████▎| 9860/10519 [2:38:20<10:06,  1.09it/s][NeMo W 2026-06-19 09:48:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 94%|█████████▎| 9861/10519 [2:38:21<10:21,  1.06it/s][NeMo W 2026-06-19 09:48:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.04it/s]
 94%|█████████▍| 9862/10519 [2:38:22<10:50,  1.01it/s][NeMo W 2026-06-19 09:48:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.42it/s]
 94%|█████████▍| 9863/10519 [2:38:23<10:40,  1.02it/s][NeMo W 2026-06-19 09:48:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.71it/s]
 94%|█████████▍| 9864/10519 [2:38:24<10:41,  1.02it/s][NeMo W 2026-06-19 09:48:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.06it/s]
 94%|█████████▍| 9865/10519 [2:38:25<10:25,  1.05it/s][NeMo W 2026-06-19 09:48:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.64it/s]
 94%|█████████▍| 9866/10519 [2:38:26<10:20,  1.05it/s][NeMo W 2026-06-19 09:48:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 94%|█████████▍| 9867/10519 [2:38:27<10:20,  1.05it/s][NeMo W 2026-06-19 09:48:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.17it/s]
 94%|█████████▍| 9868/10519 [2:38:28<10:04,  1.08it/s][NeMo W 2026-06-19 09:48:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 94%|█████████▍| 9869/10519 [2:38:29<10:19,  1.05it/s][NeMo W 2026-06-19 09:48:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.71it/s]
 94%|█████████▍| 9870/10519 [2:38:30<10:29,  1.03it/s][NeMo W 2026-06-19 09:48:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.36it/s]
 94%|█████████▍| 9871/10519 [2:38:31<10:15,  1.05it/s][NeMo W 2026-06-19 09:48:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.58it/s]
 94%|█████████▍| 9872/10519 [2:38:32<10:13,  1.05it/s][NeMo W 2026-06-19 09:48:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 94%|█████████▍| 9873/10519 [2:38:33<10:15,  1.05it/s][NeMo W 2026-06-19 09:48:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 94%|█████████▍| 9874/10519 [2:38:34<10:13,  1.05it/s][NeMo W 2026-06-19 09:48:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.54it/s]
 94%|█████████▍| 9875/10519 [2:38:35<10:37,  1.01it/s][NeMo W 2026-06-19 09:48:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.82it/s]
 94%|█████████▍| 9876/10519 [2:38:36<10:37,  1.01it/s][NeMo W 2026-06-19 09:48:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 94%|█████████▍| 9877/10519 [2:38:37<10:45,  1.01s/it][NeMo W 2026-06-19 09:48:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 94%|█████████▍| 9878/10519 [2:38:38<11:28,  1.07s/it][NeMo W 2026-06-19 09:48:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 94%|█████████▍| 9879/10519 [2:38:39<11:21,  1.07s/it][NeMo W 2026-06-19 09:48:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]

Checkpoint saved: 9900 samples

[NeMo W 2026-06-19 09:48:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.24it/s]
 94%|█████████▍| 9901/10519 [2:39:02<13:04,  1.27s/it][NeMo W 2026-06-19 09:48:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.63it/s]
 94%|█████████▍| 9902/10519 [2:39:02<11:36,  1.13s/it][NeMo W 2026-06-19 09:48:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.66it/s]
 94%|█████████▍| 9903/10519 [2:39:03<11:03,  1.08s/it][NeMo W 2026-06-19 09:48:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.40it/s]
 94%|█████████▍| 9904/10519 [2:39:04<10:33,  1.03s/it][NeMo W 2026-06-19 09:48:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.44it/s]
 94%|█████████▍| 9905/10519 [2:39:05<09:59,  1.02it/s][NeMo W 2026-06-19 09:48:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.67it/s]
 94%|█████████▍| 9906/10519 [2:39:06<10:05,  1.01it/s][NeMo W 2026-06-19 09:48:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.50it/s]
 94%|█████████▍| 9907/10519 [2:39:07<10:15,  1.00s/it][NeMo W 2026-06-19 09:48:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 94%|█████████▍| 9908/10519 [2:39:08<10:01,  1.02it/s][NeMo W 2026-06-19 09:48:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.96it/s]
 94%|█████████▍| 9909/10519 [2:39:09<10:12,  1.00s/it][NeMo W 2026-06-19 09:48:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.39it/s]
 94%|█████████▍| 9910/10519 [2:39:10<09:57,  1.02it/s][NeMo W 2026-06-19 09:48:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 94%|█████████▍| 9911/10519 [2:39:11<10:14,  1.01s/it][NeMo W 2026-06-19 09:48:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 94%|█████████▍| 9912/10519 [2:39:12<10:08,  1.00s/it][NeMo W 2026-06-19 09:48:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 94%|█████████▍| 9913/10519 [2:39:13<09:55,  1.02it/s][NeMo W 2026-06-19 09:48:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.81it/s]
 94%|█████████▍| 9914/10519 [2:39:14<10:01,  1.01it/s][NeMo W 2026-06-19 09:48:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.85it/s]
 94%|█████████▍| 9915/10519 [2:39:15<09:44,  1.03it/s][NeMo W 2026-06-19 09:48:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.07it/s]
 94%|█████████▍| 9916/10519 [2:39:16<09:41,  1.04it/s][NeMo W 2026-06-19 09:48:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.97it/s]
 94%|█████████▍| 9917/10519 [2:39:17<09:30,  1.05it/s][NeMo W 2026-06-19 09:48:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.90it/s]
 94%|█████████▍| 9918/10519 [2:39:18<08:56,  1.12it/s][NeMo W 2026-06-19 09:48:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:48:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 94%|█████████▍| 9919/10519 [2:39:19<09:11,  1.09it/s][NeMo W 2026-06-19 09:49:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.35it/s]
 94%|█████████▍| 9920/10519 [2:39:19<08:39,  1.15it/s][NeMo W 2026-06-19 09:49:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.26it/s]
 94%|█████████▍| 9921/10519 [2:39:20<09:13,  1.08it/s][NeMo W 2026-06-19 09:49:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 94%|█████████▍| 9922/10519 [2:39:21<09:23,  1.06it/s][NeMo W 2026-06-19 09:49:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 94%|█████████▍| 9923/10519 [2:39:22<09:19,  1.07it/s][NeMo W 2026-06-19 09:49:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.06it/s]
 94%|█████████▍| 9924/10519 [2:39:23<08:50,  1.12it/s][NeMo W 2026-06-19 09:49:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 94%|█████████▍| 9925/10519 [2:39:24<08:18,  1.19it/s][NeMo W 2026-06-19 09:49:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.62it/s]
 94%|█████████▍| 9926/10519 [2:39:25<08:35,  1.15it/s][NeMo W 2026-06-19 09:49:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.96it/s]
 94%|█████████▍| 9927/10519 [2:39:26<09:02,  1.09it/s][NeMo W 2026-06-19 09:49:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 94%|█████████▍| 9928/10519 [2:39:27<09:01,  1.09it/s][NeMo W 2026-06-19 09:49:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.13it/s]
 94%|█████████▍| 9929/10519 [2:39:28<08:56,  1.10it/s][NeMo W 2026-06-19 09:49:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]

Checkpoint saved: 9950 samples

[NeMo W 2026-06-19 09:49:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.84it/s]
 95%|█████████▍| 9951/10519 [2:39:51<12:45,  1.35s/it][NeMo W 2026-06-19 09:49:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 95%|█████████▍| 9952/10519 [2:39:52<11:35,  1.23s/it][NeMo W 2026-06-19 09:49:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.16it/s]
 95%|█████████▍| 9953/10519 [2:39:53<10:47,  1.14s/it][NeMo W 2026-06-19 09:49:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 95%|█████████▍| 9954/10519 [2:39:54<10:24,  1.11s/it][NeMo W 2026-06-19 09:49:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.36it/s]
 95%|█████████▍| 9955/10519 [2:39:55<09:57,  1.06s/it][NeMo W 2026-06-19 09:49:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.91it/s]
 95%|█████████▍| 9956/10519 [2:39:55<09:16,  1.01it/s][NeMo W 2026-06-19 09:49:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
 95%|█████████▍| 9957/10519 [2:39:56<08:35,  1.09it/s][NeMo W 2026-06-19 09:49:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 95%|█████████▍| 9958/10519 [2:39:57<08:34,  1.09it/s][NeMo W 2026-06-19 09:49:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.57it/s]
 95%|█████████▍| 9959/10519 [2:39:58<08:42,  1.07it/s][NeMo W 2026-06-19 09:49:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 95%|█████████▍| 9960/10519 [2:39:59<08:58,  1.04it/s][NeMo W 2026-06-19 09:49:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.94it/s]
 95%|█████████▍| 9961/10519 [2:40:00<08:55,  1.04it/s][NeMo W 2026-06-19 09:49:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 95%|█████████▍| 9962/10519 [2:40:01<08:54,  1.04it/s][NeMo W 2026-06-19 09:49:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
 95%|█████████▍| 9963/10519 [2:40:02<08:58,  1.03it/s][NeMo W 2026-06-19 09:49:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 95%|█████████▍| 9964/10519 [2:40:03<09:03,  1.02it/s][NeMo W 2026-06-19 09:49:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.22it/s]
 95%|█████████▍| 9965/10519 [2:40:04<08:22,  1.10it/s][NeMo W 2026-06-19 09:49:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 95%|█████████▍| 9966/10519 [2:40:05<08:40,  1.06it/s][NeMo W 2026-06-19 09:49:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.53it/s]
 95%|█████████▍| 9967/10519 [2:40:06<08:22,  1.10it/s][NeMo W 2026-06-19 09:49:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.51it/s]
 95%|█████████▍| 9968/10519 [2:40:07<08:27,  1.08it/s][NeMo W 2026-06-19 09:49:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.45it/s]
 95%|█████████▍| 9969/10519 [2:40:07<08:21,  1.10it/s][NeMo W 2026-06-19 09:49:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.15it/s]
 95%|█████████▍| 9970/10519 [2:40:08<07:45,  1.18it/s][NeMo W 2026-06-19 09:49:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.95it/s]
 95%|█████████▍| 9971/10519 [2:40:09<08:01,  1.14it/s][NeMo W 2026-06-19 09:49:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.52it/s]
 95%|█████████▍| 9972/10519 [2:40:10<08:10,  1.12it/s][NeMo W 2026-06-19 09:49:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.47it/s]
 95%|█████████▍| 9973/10519 [2:40:11<08:15,  1.10it/s][NeMo W 2026-06-19 09:49:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 95%|█████████▍| 9974/10519 [2:40:12<07:52,  1.15it/s][NeMo W 2026-06-19 09:49:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.08it/s]
 95%|█████████▍| 9975/10519 [2:40:13<08:03,  1.13it/s][NeMo W 2026-06-19 09:49:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.02it/s]
 95%|█████████▍| 9976/10519 [2:40:14<08:42,  1.04it/s][NeMo W 2026-06-19 09:49:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.43it/s]
 95%|█████████▍| 9977/10519 [2:40:15<09:57,  1.10s/it][NeMo W 2026-06-19 09:49:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.54it/s]
 95%|█████████▍| 9978/10519 [2:40:16<09:54,  1.10s/it][NeMo W 2026-06-19 09:49:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 95%|█████████▍| 9979/10519 [2:40:17<09:37,  1.07s/it][NeMo W 2026-06-19 09:49:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:49:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.02it/s]
 95%|█████████▍| 9980/10519 [2:40:18<09:11,  1.02s/it][NeMo W 2026-06-19 09:50:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 10000 samples

[NeMo W 2026-06-19 09:50:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 95%|█████████▌| 10001/10519 [2:40:40<11:13,  1.30s/it][NeMo W 2026-06-19 09:50:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.07it/s]
 95%|█████████▌| 10002/10519 [2:40:41<10:26,  1.21s/it][NeMo W 2026-06-19 09:50:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.16it/s]
 95%|█████████▌| 10003/10519 [2:40:42<09:54,  1.15s/it][NeMo W 2026-06-19 09:50:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.36it/s]
 95%|█████████▌| 10004/10519 [2:40:43<09:27,  1.10s/it][NeMo W 2026-06-19 09:50:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 95%|█████████▌| 10005/10519 [2:40:44<08:51,  1.03s/it][NeMo W 2026-06-19 09:50:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.97it/s]
 95%|█████████▌| 10006/10519 [2:40:45<08:32,  1.00it/s][NeMo W 2026-06-19 09:50:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.86it/s]
 95%|█████████▌| 10007/10519 [2:40:45<07:45,  1.10it/s][NeMo W 2026-06-19 09:50:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 95%|█████████▌| 10008/10519 [2:40:46<07:41,  1.11it/s][NeMo W 2026-06-19 09:50:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 95%|█████████▌| 10009/10519 [2:40:47<07:54,  1.07it/s][NeMo W 2026-06-19 09:50:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 95%|█████████▌| 10010/10519 [2:40:48<08:01,  1.06it/s][NeMo W 2026-06-19 09:50:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.56it/s]
 95%|█████████▌| 10011/10519 [2:40:49<08:03,  1.05it/s][NeMo W 2026-06-19 09:50:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.61it/s]
 95%|█████████▌| 10012/10519 [2:40:50<08:19,  1.01it/s][NeMo W 2026-06-19 09:50:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 95%|█████████▌| 10013/10519 [2:40:51<08:16,  1.02it/s][NeMo W 2026-06-19 09:50:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 95%|█████████▌| 10014/10519 [2:40:52<08:12,  1.03it/s][NeMo W 2026-06-19 09:50:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.90it/s]
 95%|█████████▌| 10015/10519 [2:40:53<08:09,  1.03it/s][NeMo W 2026-06-19 09:50:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.10it/s]
 95%|█████████▌| 10016/10519 [2:40:54<08:05,  1.04it/s][NeMo W 2026-06-19 09:50:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
 95%|█████████▌| 10017/10519 [2:40:55<09:11,  1.10s/it][NeMo W 2026-06-19 09:50:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.67it/s]
 95%|█████████▌| 10018/10519 [2:40:56<08:47,  1.05s/it][NeMo W 2026-06-19 09:50:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.77it/s]
 95%|█████████▌| 10019/10519 [2:40:57<08:35,  1.03s/it][NeMo W 2026-06-19 09:50:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.42it/s]
 95%|█████████▌| 10020/10519 [2:40:58<07:56,  1.05it/s][NeMo W 2026-06-19 09:50:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.16it/s]
 95%|█████████▌| 10021/10519 [2:40:59<07:59,  1.04it/s][NeMo W 2026-06-19 09:50:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 95%|█████████▌| 10022/10519 [2:41:00<07:33,  1.10it/s][NeMo W 2026-06-19 09:50:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 95%|█████████▌| 10023/10519 [2:41:01<07:33,  1.09it/s][NeMo W 2026-06-19 09:50:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 95%|█████████▌| 10024/10519 [2:41:02<07:36,  1.08it/s][NeMo W 2026-06-19 09:50:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.32it/s]
 95%|█████████▌| 10025/10519 [2:41:03<07:39,  1.07it/s][NeMo W 2026-06-19 09:50:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 95%|█████████▌| 10026/10519 [2:41:04<07:13,  1.14it/s][NeMo W 2026-06-19 09:50:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 95%|█████████▌| 10027/10519 [2:41:04<07:20,  1.12it/s][NeMo W 2026-06-19 09:50:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.97it/s]
 95%|█████████▌| 10028/10519 [2:41:05<07:33,  1.08it/s][NeMo W 2026-06-19 09:50:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
 95%|█████████▌| 10029/10519 [2:41:06<07:33,  1.08it/s][NeMo W 2026-06-19 09:50:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:50:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.51it/s]

Checkpoint saved: 10050 samples

[NeMo W 2026-06-19 09:51:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.64it/s]
 96%|█████████▌| 10051/10519 [2:41:29<09:55,  1.27s/it][NeMo W 2026-06-19 09:51:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 96%|█████████▌| 10052/10519 [2:41:30<08:43,  1.12s/it][NeMo W 2026-06-19 09:51:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.29it/s]
 96%|█████████▌| 10053/10519 [2:41:31<08:12,  1.06s/it][NeMo W 2026-06-19 09:51:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.76it/s]
 96%|█████████▌| 10054/10519 [2:41:32<07:54,  1.02s/it][NeMo W 2026-06-19 09:51:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 96%|█████████▌| 10055/10519 [2:41:32<07:43,  1.00it/s][NeMo W 2026-06-19 09:51:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.07it/s]
 96%|█████████▌| 10056/10519 [2:41:33<07:36,  1.02it/s][NeMo W 2026-06-19 09:51:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.27it/s]
 96%|█████████▌| 10057/10519 [2:41:34<06:56,  1.11it/s][NeMo W 2026-06-19 09:51:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.03it/s]
 96%|█████████▌| 10058/10519 [2:41:35<07:00,  1.10it/s][NeMo W 2026-06-19 09:51:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 96%|█████████▌| 10059/10519 [2:41:36<07:04,  1.08it/s][NeMo W 2026-06-19 09:51:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 96%|█████████▌| 10060/10519 [2:41:37<07:08,  1.07it/s][NeMo W 2026-06-19 09:51:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
 96%|█████████▌| 10061/10519 [2:41:38<07:10,  1.06it/s][NeMo W 2026-06-19 09:51:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.56it/s]
 96%|█████████▌| 10062/10519 [2:41:39<06:52,  1.11it/s][NeMo W 2026-06-19 09:51:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.99it/s]
 96%|█████████▌| 10063/10519 [2:41:40<07:02,  1.08it/s][NeMo W 2026-06-19 09:51:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.36it/s]
 96%|█████████▌| 10064/10519 [2:41:41<07:05,  1.07it/s][NeMo W 2026-06-19 09:51:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 96%|█████████▌| 10065/10519 [2:41:42<07:19,  1.03it/s][NeMo W 2026-06-19 09:51:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 96%|█████████▌| 10066/10519 [2:41:43<07:14,  1.04it/s][NeMo W 2026-06-19 09:51:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.60it/s]
 96%|█████████▌| 10067/10519 [2:41:44<07:13,  1.04it/s][NeMo W 2026-06-19 09:51:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 96%|█████████▌| 10068/10519 [2:41:44<06:51,  1.10it/s][NeMo W 2026-06-19 09:51:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 96%|█████████▌| 10069/10519 [2:41:45<06:53,  1.09it/s][NeMo W 2026-06-19 09:51:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.43it/s]
 96%|█████████▌| 10070/10519 [2:41:46<06:58,  1.07it/s][NeMo W 2026-06-19 09:51:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 96%|█████████▌| 10071/10519 [2:41:47<07:14,  1.03it/s][NeMo W 2026-06-19 09:51:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.65it/s]
 96%|█████████▌| 10072/10519 [2:41:48<06:55,  1.08it/s][NeMo W 2026-06-19 09:51:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
 96%|█████████▌| 10073/10519 [2:41:49<06:23,  1.16it/s][NeMo W 2026-06-19 09:51:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.40it/s]
 96%|█████████▌| 10074/10519 [2:41:50<06:08,  1.21it/s][NeMo W 2026-06-19 09:51:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.45it/s]
 96%|█████████▌| 10075/10519 [2:41:51<06:37,  1.12it/s][NeMo W 2026-06-19 09:51:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.00it/s]
 96%|█████████▌| 10076/10519 [2:41:52<06:43,  1.10it/s][NeMo W 2026-06-19 09:51:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.08it/s]
 96%|█████████▌| 10077/10519 [2:41:53<07:02,  1.05it/s][NeMo W 2026-06-19 09:51:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.62it/s]
 96%|█████████▌| 10078/10519 [2:41:54<07:00,  1.05it/s][NeMo W 2026-06-19 09:51:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.67it/s]
 96%|█████████▌| 10079/10519 [2:41:55<07:13,  1.02it/s][NeMo W 2026-06-19 09:51:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]

Checkpoint saved: 10100 samples

[NeMo W 2026-06-19 09:51:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 96%|█████████▌| 10101/10519 [2:42:17<08:49,  1.27s/it][NeMo W 2026-06-19 09:51:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.99it/s]
 96%|█████████▌| 10102/10519 [2:42:18<08:13,  1.18s/it][NeMo W 2026-06-19 09:51:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:51:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  6.91it/s]
 96%|█████████▌| 10103/10519 [2:42:18<07:35,  1.09s/it][NeMo W 2026-06-19 09:52:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.78it/s]
 96%|█████████▌| 10104/10519 [2:42:19<07:24,  1.07s/it][NeMo W 2026-06-19 09:52:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.55it/s]
 96%|█████████▌| 10105/10519 [2:42:20<06:48,  1.01it/s][NeMo W 2026-06-19 09:52:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.76it/s]
 96%|█████████▌| 10106/10519 [2:42:21<06:37,  1.04it/s][NeMo W 2026-06-19 09:52:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 96%|█████████▌| 10107/10519 [2:42:22<06:37,  1.04it/s][NeMo W 2026-06-19 09:52:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.03it/s]
 96%|█████████▌| 10108/10519 [2:42:23<06:40,  1.03it/s][NeMo W 2026-06-19 09:52:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.81it/s]
 96%|█████████▌| 10109/10519 [2:42:24<06:21,  1.08it/s][NeMo W 2026-06-19 09:52:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.02it/s]
 96%|█████████▌| 10110/10519 [2:42:25<06:00,  1.13it/s][NeMo W 2026-06-19 09:52:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 96%|█████████▌| 10111/10519 [2:42:25<05:37,  1.21it/s][NeMo W 2026-06-19 09:52:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 96%|█████████▌| 10112/10519 [2:42:26<05:48,  1.17it/s][NeMo W 2026-06-19 09:52:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 96%|█████████▌| 10113/10519 [2:42:27<06:02,  1.12it/s][NeMo W 2026-06-19 09:52:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 96%|█████████▌| 10114/10519 [2:42:28<06:02,  1.12it/s][NeMo W 2026-06-19 09:52:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
 96%|█████████▌| 10115/10519 [2:42:29<06:05,  1.10it/s][NeMo W 2026-06-19 09:52:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.17it/s]
 96%|█████████▌| 10116/10519 [2:42:30<06:04,  1.10it/s][NeMo W 2026-06-19 09:52:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.31it/s]
 96%|█████████▌| 10117/10519 [2:42:31<06:13,  1.08it/s][NeMo W 2026-06-19 09:52:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.51it/s]
 96%|█████████▌| 10118/10519 [2:42:32<06:30,  1.03it/s][NeMo W 2026-06-19 09:52:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.92it/s]
 96%|█████████▌| 10119/10519 [2:42:33<06:26,  1.03it/s][NeMo W 2026-06-19 09:52:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.19it/s]
 96%|█████████▌| 10120/10519 [2:42:34<06:35,  1.01it/s][NeMo W 2026-06-19 09:52:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.70it/s]
 96%|█████████▌| 10121/10519 [2:42:35<06:41,  1.01s/it][NeMo W 2026-06-19 09:52:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 96%|█████████▌| 10122/10519 [2:42:36<06:37,  1.00s/it][NeMo W 2026-06-19 09:52:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.69it/s]
 96%|█████████▌| 10123/10519 [2:42:37<06:09,  1.07it/s][NeMo W 2026-06-19 09:52:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 96%|█████████▌| 10124/10519 [2:42:38<06:08,  1.07it/s][NeMo W 2026-06-19 09:52:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.38it/s]
 96%|█████████▋| 10125/10519 [2:42:39<06:06,  1.08it/s][NeMo W 2026-06-19 09:52:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.27it/s]
 96%|█████████▋| 10126/10519 [2:42:40<06:24,  1.02it/s][NeMo W 2026-06-19 09:52:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 96%|█████████▋| 10127/10519 [2:42:41<06:13,  1.05it/s][NeMo W 2026-06-19 09:52:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 96%|█████████▋| 10128/10519 [2:42:42<06:09,  1.06it/s][NeMo W 2026-06-19 09:52:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.46it/s]
 96%|█████████▋| 10129/10519 [2:42:43<06:05,  1.07it/s][NeMo W 2026-06-19 09:52:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]

Checkpoint saved: 10150 samples

[NeMo W 2026-06-19 09:52:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.85it/s]
 97%|█████████▋| 10151/10519 [2:43:06<08:35,  1.40s/it][NeMo W 2026-06-19 09:52:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.82it/s]
 97%|█████████▋| 10152/10519 [2:43:07<07:35,  1.24s/it][NeMo W 2026-06-19 09:52:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.09it/s]
 97%|█████████▋| 10153/10519 [2:43:08<06:45,  1.11s/it][NeMo W 2026-06-19 09:52:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.60it/s]
 97%|█████████▋| 10154/10519 [2:43:09<06:28,  1.06s/it][NeMo W 2026-06-19 09:52:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.06it/s]
 97%|█████████▋| 10155/10519 [2:43:10<07:52,  1.30s/it][NeMo W 2026-06-19 09:52:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.63it/s]
 97%|█████████▋| 10156/10519 [2:43:11<06:53,  1.14s/it][NeMo W 2026-06-19 09:52:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 97%|█████████▋| 10157/10519 [2:43:12<06:05,  1.01s/it][NeMo W 2026-06-19 09:52:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.06it/s]
 97%|█████████▋| 10158/10519 [2:43:13<06:02,  1.00s/it][NeMo W 2026-06-19 09:52:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.24it/s]
 97%|█████████▋| 10159/10519 [2:43:14<05:54,  1.01it/s][NeMo W 2026-06-19 09:52:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 97%|█████████▋| 10160/10519 [2:43:15<05:51,  1.02it/s][NeMo W 2026-06-19 09:52:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.39it/s]
 97%|█████████▋| 10161/10519 [2:43:16<05:31,  1.08it/s][NeMo W 2026-06-19 09:52:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.18it/s]
 97%|█████████▋| 10162/10519 [2:43:17<05:43,  1.04it/s][NeMo W 2026-06-19 09:52:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:52:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.31it/s]
 97%|█████████▋| 10163/10519 [2:43:18<05:58,  1.01s/it][NeMo W 2026-06-19 09:53:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.99it/s]
 97%|█████████▋| 10164/10519 [2:43:19<05:52,  1.01it/s][NeMo W 2026-06-19 09:53:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.13it/s]
 97%|█████████▋| 10165/10519 [2:43:20<06:12,  1.05s/it][NeMo W 2026-06-19 09:53:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
 97%|█████████▋| 10166/10519 [2:43:21<05:45,  1.02it/s][NeMo W 2026-06-19 09:53:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.07it/s]
 97%|█████████▋| 10167/10519 [2:43:22<05:48,  1.01it/s][NeMo W 2026-06-19 09:53:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.05it/s]
 97%|█████████▋| 10168/10519 [2:43:23<05:24,  1.08it/s][NeMo W 2026-06-19 09:53:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.11it/s]
 97%|█████████▋| 10169/10519 [2:43:24<05:26,  1.07it/s][NeMo W 2026-06-19 09:53:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.94it/s]
 97%|█████████▋| 10170/10519 [2:43:25<05:35,  1.04it/s][NeMo W 2026-06-19 09:53:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.00it/s]
 97%|█████████▋| 10171/10519 [2:43:25<05:32,  1.05it/s][NeMo W 2026-06-19 09:53:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.92it/s]
 97%|█████████▋| 10172/10519 [2:43:26<05:07,  1.13it/s][NeMo W 2026-06-19 09:53:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 97%|█████████▋| 10173/10519 [2:43:27<05:09,  1.12it/s][NeMo W 2026-06-19 09:53:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 97%|█████████▋| 10174/10519 [2:43:28<05:14,  1.10it/s][NeMo W 2026-06-19 09:53:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.21it/s]
 97%|█████████▋| 10175/10519 [2:43:29<05:02,  1.14it/s][NeMo W 2026-06-19 09:53:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.84it/s]
 97%|█████████▋| 10176/10519 [2:43:30<05:11,  1.10it/s][NeMo W 2026-06-19 09:53:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.65it/s]
 97%|█████████▋| 10177/10519 [2:43:31<04:56,  1.15it/s][NeMo W 2026-06-19 09:53:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.22it/s]
 97%|█████████▋| 10178/10519 [2:43:31<04:44,  1.20it/s][NeMo W 2026-06-19 09:53:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.06it/s]
 97%|█████████▋| 10179/10519 [2:43:32<04:58,  1.14it/s][NeMo W 2026-06-19 09:53:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]

Checkpoint saved: 10200 samples

[NeMo W 2026-06-19 09:53:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.73it/s]
 97%|█████████▋| 10201/10519 [2:43:55<06:34,  1.24s/it][NeMo W 2026-06-19 09:53:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.59it/s]
 97%|█████████▋| 10202/10519 [2:43:56<06:06,  1.16s/it][NeMo W 2026-06-19 09:53:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 97%|█████████▋| 10203/10519 [2:43:57<06:11,  1.17s/it][NeMo W 2026-06-19 09:53:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 97%|█████████▋| 10204/10519 [2:43:58<05:32,  1.06s/it][NeMo W 2026-06-19 09:53:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
 97%|█████████▋| 10205/10519 [2:43:59<05:21,  1.03s/it][NeMo W 2026-06-19 09:53:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.10it/s]
 97%|█████████▋| 10206/10519 [2:44:00<05:14,  1.01s/it][NeMo W 2026-06-19 09:53:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.50it/s]
 97%|█████████▋| 10207/10519 [2:44:00<04:50,  1.08it/s][NeMo W 2026-06-19 09:53:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.18it/s]
 97%|█████████▋| 10208/10519 [2:44:01<04:45,  1.09it/s][NeMo W 2026-06-19 09:53:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
 97%|█████████▋| 10209/10519 [2:44:02<04:51,  1.06it/s][NeMo W 2026-06-19 09:53:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.38it/s]
 97%|█████████▋| 10210/10519 [2:44:03<04:47,  1.08it/s][NeMo W 2026-06-19 09:53:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 97%|█████████▋| 10211/10519 [2:44:04<04:37,  1.11it/s][NeMo W 2026-06-19 09:53:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.88it/s]
 97%|█████████▋| 10212/10519 [2:44:05<04:48,  1.06it/s][NeMo W 2026-06-19 09:53:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.11it/s]
 97%|█████████▋| 10213/10519 [2:44:06<04:59,  1.02it/s][NeMo W 2026-06-19 09:53:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.78it/s]
 97%|█████████▋| 10214/10519 [2:44:07<04:55,  1.03it/s][NeMo W 2026-06-19 09:53:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.86it/s]
 97%|█████████▋| 10215/10519 [2:44:08<04:49,  1.05it/s][NeMo W 2026-06-19 09:53:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
 97%|█████████▋| 10216/10519 [2:44:09<04:45,  1.06it/s][NeMo W 2026-06-19 09:53:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.52it/s]
 97%|█████████▋| 10217/10519 [2:44:10<04:50,  1.04it/s][NeMo W 2026-06-19 09:53:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.25it/s]
 97%|█████████▋| 10218/10519 [2:44:11<04:56,  1.02it/s][NeMo W 2026-06-19 09:53:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.88it/s]
 97%|█████████▋| 10219/10519 [2:44:12<04:57,  1.01it/s][NeMo W 2026-06-19 09:53:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.12it/s]
 97%|█████████▋| 10220/10519 [2:44:13<05:11,  1.04s/it][NeMo W 2026-06-19 09:53:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.60it/s]
 97%|█████████▋| 10221/10519 [2:44:14<04:58,  1.00s/it][NeMo W 2026-06-19 09:53:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
 97%|█████████▋| 10222/10519 [2:44:15<04:58,  1.00s/it][NeMo W 2026-06-19 09:53:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.33it/s]
 97%|█████████▋| 10223/10519 [2:44:16<04:48,  1.03it/s][NeMo W 2026-06-19 09:53:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 97%|█████████▋| 10224/10519 [2:44:17<04:43,  1.04it/s][NeMo W 2026-06-19 09:53:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:53:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.95it/s]
 97%|█████████▋| 10225/10519 [2:44:18<04:40,  1.05it/s][NeMo W 2026-06-19 09:54:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.59it/s]
 97%|█████████▋| 10226/10519 [2:44:19<04:37,  1.06it/s][NeMo W 2026-06-19 09:54:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.46it/s]
 97%|█████████▋| 10227/10519 [2:44:20<04:34,  1.06it/s][NeMo W 2026-06-19 09:54:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
 97%|█████████▋| 10228/10519 [2:44:20<04:14,  1.14it/s][NeMo W 2026-06-19 09:54:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 97%|█████████▋| 10229/10519 [2:44:21<03:55,  1.23it/s][NeMo W 2026-06-19 09:54:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.57it/s]

Checkpoint saved: 10250 samples

[NeMo W 2026-06-19 09:54:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.24it/s]
 97%|█████████▋| 10251/10519 [2:44:44<06:28,  1.45s/it][NeMo W 2026-06-19 09:54:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
 97%|█████████▋| 10252/10519 [2:44:45<05:59,  1.35s/it][NeMo W 2026-06-19 09:54:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.56it/s]
 97%|█████████▋| 10253/10519 [2:44:46<05:32,  1.25s/it][NeMo W 2026-06-19 09:54:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 97%|█████████▋| 10254/10519 [2:44:47<05:05,  1.15s/it][NeMo W 2026-06-19 09:54:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 97%|█████████▋| 10255/10519 [2:44:48<04:45,  1.08s/it][NeMo W 2026-06-19 09:54:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.12it/s]
 97%|█████████▋| 10256/10519 [2:44:49<04:53,  1.12s/it][NeMo W 2026-06-19 09:54:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.00it/s]
 98%|█████████▊| 10257/10519 [2:44:50<04:36,  1.05s/it][NeMo W 2026-06-19 09:54:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.34it/s]
 98%|█████████▊| 10258/10519 [2:44:51<04:21,  1.00s/it][NeMo W 2026-06-19 09:54:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.68it/s]
 98%|█████████▊| 10259/10519 [2:44:52<04:12,  1.03it/s][NeMo W 2026-06-19 09:54:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 98%|█████████▊| 10260/10519 [2:44:53<04:09,  1.04it/s][NeMo W 2026-06-19 09:54:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.47it/s]
 98%|█████████▊| 10261/10519 [2:44:54<04:07,  1.04it/s][NeMo W 2026-06-19 09:54:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.70it/s]
 98%|█████████▊| 10262/10519 [2:44:55<04:08,  1.04it/s][NeMo W 2026-06-19 09:54:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 98%|█████████▊| 10263/10519 [2:44:56<04:09,  1.03it/s][NeMo W 2026-06-19 09:54:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.18it/s]
 98%|█████████▊| 10264/10519 [2:44:57<04:12,  1.01it/s][NeMo W 2026-06-19 09:54:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.01it/s]
 98%|█████████▊| 10265/10519 [2:44:58<04:22,  1.03s/it][NeMo W 2026-06-19 09:54:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.41it/s]
 98%|█████████▊| 10266/10519 [2:44:59<04:19,  1.03s/it][NeMo W 2026-06-19 09:54:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.68it/s]
 98%|█████████▊| 10267/10519 [2:45:00<04:10,  1.01it/s][NeMo W 2026-06-19 09:54:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.17it/s]
 98%|█████████▊| 10268/10519 [2:45:01<04:05,  1.02it/s][NeMo W 2026-06-19 09:54:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.09it/s]
 98%|█████████▊| 10269/10519 [2:45:02<04:05,  1.02it/s][NeMo W 2026-06-19 09:54:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 98%|█████████▊| 10270/10519 [2:45:03<04:08,  1.00it/s][NeMo W 2026-06-19 09:54:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 98%|█████████▊| 10271/10519 [2:45:04<03:49,  1.08it/s][NeMo W 2026-06-19 09:54:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.72it/s]
 98%|█████████▊| 10272/10519 [2:45:05<03:57,  1.04it/s][NeMo W 2026-06-19 09:54:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.78it/s]
 98%|█████████▊| 10273/10519 [2:45:06<04:02,  1.01it/s][NeMo W 2026-06-19 09:54:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.96it/s]
 98%|█████████▊| 10274/10519 [2:45:07<03:58,  1.03it/s][NeMo W 2026-06-19 09:54:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.63it/s]
 98%|█████████▊| 10275/10519 [2:45:08<04:02,  1.01it/s][NeMo W 2026-06-19 09:54:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.73it/s]
 98%|█████████▊| 10276/10519 [2:45:08<03:47,  1.07it/s][NeMo W 2026-06-19 09:54:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.43it/s]
 98%|█████████▊| 10277/10519 [2:45:09<03:51,  1.05it/s][NeMo W 2026-06-19 09:54:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.93it/s]
 98%|█████████▊| 10278/10519 [2:45:11<04:03,  1.01s/it][NeMo W 2026-06-19 09:54:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.05it/s]
 98%|█████████▊| 10279/10519 [2:45:11<03:45,  1.07it/s][NeMo W 2026-06-19 09:54:53 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:54:53 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]

Checkpoint saved: 10300 samples

[NeMo W 2026-06-19 09:55:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.72it/s]
 98%|█████████▊| 10301/10519 [2:45:34<04:28,  1.23s/it][NeMo W 2026-06-19 09:55:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.81it/s]
 98%|█████████▊| 10302/10519 [2:45:35<04:07,  1.14s/it][NeMo W 2026-06-19 09:55:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.64it/s]
 98%|█████████▊| 10303/10519 [2:45:36<03:57,  1.10s/it][NeMo W 2026-06-19 09:55:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.00it/s]
 98%|█████████▊| 10304/10519 [2:45:36<03:47,  1.06s/it][NeMo W 2026-06-19 09:55:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.80it/s]
 98%|█████████▊| 10305/10519 [2:45:38<03:42,  1.04s/it][NeMo W 2026-06-19 09:55:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 98%|█████████▊| 10306/10519 [2:45:38<03:37,  1.02s/it][NeMo W 2026-06-19 09:55:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 98%|█████████▊| 10307/10519 [2:45:39<03:31,  1.00it/s][NeMo W 2026-06-19 09:55:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.48it/s]
 98%|█████████▊| 10308/10519 [2:45:40<03:21,  1.05it/s][NeMo W 2026-06-19 09:55:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 98%|█████████▊| 10309/10519 [2:45:41<03:06,  1.13it/s][NeMo W 2026-06-19 09:55:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.19it/s]
 98%|█████████▊| 10310/10519 [2:45:42<02:58,  1.17it/s][NeMo W 2026-06-19 09:55:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 98%|█████████▊| 10311/10519 [2:45:43<03:01,  1.14it/s][NeMo W 2026-06-19 09:55:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.87it/s]
 98%|█████████▊| 10312/10519 [2:45:44<03:10,  1.09it/s][NeMo W 2026-06-19 09:55:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.88it/s]
 98%|█████████▊| 10313/10519 [2:45:45<03:14,  1.06it/s][NeMo W 2026-06-19 09:55:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.46it/s]
 98%|█████████▊| 10314/10519 [2:45:46<03:09,  1.08it/s][NeMo W 2026-06-19 09:55:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.20it/s]
 98%|█████████▊| 10315/10519 [2:45:47<03:13,  1.05it/s][NeMo W 2026-06-19 09:55:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.11it/s]
 98%|█████████▊| 10316/10519 [2:45:48<03:21,  1.01it/s][NeMo W 2026-06-19 09:55:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.37it/s]
 98%|█████████▊| 10317/10519 [2:45:48<03:03,  1.10it/s][NeMo W 2026-06-19 09:55:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.28it/s]
 98%|█████████▊| 10318/10519 [2:45:49<03:03,  1.09it/s][NeMo W 2026-06-19 09:55:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.27it/s]
 98%|█████████▊| 10319/10519 [2:45:50<03:08,  1.06it/s][NeMo W 2026-06-19 09:55:32 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:32 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.82it/s]
 98%|█████████▊| 10320/10519 [2:45:51<03:07,  1.06it/s][NeMo W 2026-06-19 09:55:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.38it/s]
 98%|█████████▊| 10321/10519 [2:45:52<03:01,  1.09it/s][NeMo W 2026-06-19 09:55:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.21it/s]
 98%|█████████▊| 10322/10519 [2:45:53<03:05,  1.06it/s][NeMo W 2026-06-19 09:55:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.56it/s]
 98%|█████████▊| 10323/10519 [2:45:54<03:06,  1.05it/s][NeMo W 2026-06-19 09:55:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.93it/s]
 98%|█████████▊| 10324/10519 [2:45:55<03:14,  1.00it/s][NeMo W 2026-06-19 09:55:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.35it/s]
 98%|█████████▊| 10325/10519 [2:45:56<02:59,  1.08it/s][NeMo W 2026-06-19 09:55:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.31it/s]
 98%|█████████▊| 10326/10519 [2:45:57<02:50,  1.13it/s][NeMo W 2026-06-19 09:55:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 98%|█████████▊| 10327/10519 [2:45:58<02:47,  1.14it/s][NeMo W 2026-06-19 09:55:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.25it/s]
 98%|█████████▊| 10328/10519 [2:45:59<02:50,  1.12it/s][NeMo W 2026-06-19 09:55:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
 98%|█████████▊| 10329/10519 [2:45:59<02:39,  1.19it/s][NeMo W 2026-06-19 09:55:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:55:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.99it/s]

Checkpoint saved: 10350 samples

[NeMo W 2026-06-19 09:56:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.40it/s]
 98%|█████████▊| 10351/10519 [2:46:23<04:00,  1.43s/it][NeMo W 2026-06-19 09:56:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.85it/s]
 98%|█████████▊| 10352/10519 [2:46:24<03:34,  1.28s/it][NeMo W 2026-06-19 09:56:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.05it/s]
 98%|█████████▊| 10353/10519 [2:46:25<03:19,  1.20s/it][NeMo W 2026-06-19 09:56:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
 98%|█████████▊| 10354/10519 [2:46:26<03:05,  1.12s/it][NeMo W 2026-06-19 09:56:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.02it/s]
 98%|█████████▊| 10355/10519 [2:46:27<02:54,  1.07s/it][NeMo W 2026-06-19 09:56:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.81it/s]
 98%|█████████▊| 10356/10519 [2:46:28<02:55,  1.07s/it][NeMo W 2026-06-19 09:56:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.13it/s]
 98%|█████████▊| 10357/10519 [2:46:29<02:40,  1.01it/s][NeMo W 2026-06-19 09:56:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.14it/s]
 98%|█████████▊| 10358/10519 [2:46:29<02:30,  1.07it/s][NeMo W 2026-06-19 09:56:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.60it/s]
 98%|█████████▊| 10359/10519 [2:46:31<02:36,  1.02it/s][NeMo W 2026-06-19 09:56:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 98%|█████████▊| 10360/10519 [2:46:32<02:34,  1.03it/s][NeMo W 2026-06-19 09:56:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.90it/s]
 98%|█████████▊| 10361/10519 [2:46:33<02:37,  1.00it/s][NeMo W 2026-06-19 09:56:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.94it/s]
 99%|█████████▊| 10362/10519 [2:46:34<02:59,  1.14s/it][NeMo W 2026-06-19 09:56:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.22it/s]
 99%|█████████▊| 10363/10519 [2:46:35<02:49,  1.09s/it][NeMo W 2026-06-19 09:56:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.03it/s]
 99%|█████████▊| 10364/10519 [2:46:36<02:43,  1.05s/it][NeMo W 2026-06-19 09:56:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.15it/s]
 99%|█████████▊| 10365/10519 [2:46:37<02:36,  1.02s/it][NeMo W 2026-06-19 09:56:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.69it/s]
 99%|█████████▊| 10366/10519 [2:46:38<02:29,  1.02it/s][NeMo W 2026-06-19 09:56:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.23it/s]
 99%|█████████▊| 10367/10519 [2:46:39<02:28,  1.02it/s][NeMo W 2026-06-19 09:56:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.07it/s]
 99%|█████████▊| 10368/10519 [2:46:40<02:26,  1.03it/s][NeMo W 2026-06-19 09:56:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.44it/s]
 99%|█████████▊| 10369/10519 [2:46:41<02:22,  1.05it/s][NeMo W 2026-06-19 09:56:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.50it/s]
 99%|█████████▊| 10370/10519 [2:46:42<02:21,  1.05it/s][NeMo W 2026-06-19 09:56:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.13it/s]
 99%|█████████▊| 10371/10519 [2:46:42<02:18,  1.07it/s][NeMo W 2026-06-19 09:56:24 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.31it/s]
 99%|█████████▊| 10372/10519 [2:46:43<02:17,  1.07it/s][NeMo W 2026-06-19 09:56:25 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:25 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.32it/s]
 99%|█████████▊| 10373/10519 [2:46:44<02:13,  1.09it/s][NeMo W 2026-06-19 09:56:26 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:26 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.43it/s]
 99%|█████████▊| 10374/10519 [2:46:45<02:18,  1.04it/s][NeMo W 2026-06-19 09:56:27 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:27 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.28it/s]
 99%|█████████▊| 10375/10519 [2:46:46<02:18,  1.04it/s][NeMo W 2026-06-19 09:56:28 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:28 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.09it/s]
 99%|█████████▊| 10376/10519 [2:46:47<02:17,  1.04it/s][NeMo W 2026-06-19 09:56:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 99%|█████████▊| 10377/10519 [2:46:48<02:05,  1.13it/s][NeMo W 2026-06-19 09:56:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 99%|█████████▊| 10378/10519 [2:46:49<02:00,  1.17it/s][NeMo W 2026-06-19 09:56:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.28it/s]
 99%|█████████▊| 10379/10519 [2:46:50<02:01,  1.15it/s][NeMo W 2026-06-19 09:56:31 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:31 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.39it/s]
 99%|█████████▊| 10380/10519 [2:46:51<02:04,  1.11it/s][NeMo W 2026-06-19 09:56:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Checkpoint saved: 10400 samples

[NeMo W 2026-06-19 09:56:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.49it/s]
 99%|█████████▉| 10401/10519 [2:47:13<02:43,  1.38s/it][NeMo W 2026-06-19 09:56:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.54it/s]
 99%|█████████▉| 10402/10519 [2:47:14<02:26,  1.25s/it][NeMo W 2026-06-19 09:56:56 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:56 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.69it/s]
 99%|█████████▉| 10403/10519 [2:47:15<02:08,  1.11s/it][NeMo W 2026-06-19 09:56:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.60it/s]
 99%|█████████▉| 10404/10519 [2:47:16<02:03,  1.07s/it][NeMo W 2026-06-19 09:56:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.08it/s]
 99%|█████████▉| 10405/10519 [2:47:17<02:09,  1.13s/it][NeMo W 2026-06-19 09:56:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 99%|█████████▉| 10406/10519 [2:47:18<01:55,  1.02s/it][NeMo W 2026-06-19 09:56:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:56:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.08it/s]
 99%|█████████▉| 10407/10519 [2:47:19<01:45,  1.06it/s][NeMo W 2026-06-19 09:57:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.31it/s]
 99%|█████████▉| 10408/10519 [2:47:20<01:46,  1.04it/s][NeMo W 2026-06-19 09:57:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.95it/s]
 99%|█████████▉| 10409/10519 [2:47:21<01:45,  1.04it/s][NeMo W 2026-06-19 09:57:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.67it/s]
 99%|█████████▉| 10410/10519 [2:47:22<01:44,  1.04it/s][NeMo W 2026-06-19 09:57:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.53it/s]
 99%|█████████▉| 10411/10519 [2:47:23<01:46,  1.01it/s][NeMo W 2026-06-19 09:57:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 99%|█████████▉| 10412/10519 [2:47:24<01:46,  1.01it/s][NeMo W 2026-06-19 09:57:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.87it/s]
 99%|█████████▉| 10413/10519 [2:47:24<01:38,  1.07it/s][NeMo W 2026-06-19 09:57:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00,  9.98it/s]
 99%|█████████▉| 10414/10519 [2:47:26<01:44,  1.01it/s][NeMo W 2026-06-19 09:57:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.55it/s]
 99%|█████████▉| 10415/10519 [2:47:27<01:42,  1.02it/s][NeMo W 2026-06-19 09:57:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.23it/s]
 99%|█████████▉| 10416/10519 [2:47:27<01:39,  1.04it/s][NeMo W 2026-06-19 09:57:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.86it/s]
 99%|█████████▉| 10417/10519 [2:47:28<01:38,  1.03it/s][NeMo W 2026-06-19 09:57:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.66it/s]
 99%|█████████▉| 10418/10519 [2:47:29<01:33,  1.08it/s][NeMo W 2026-06-19 09:57:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.21it/s]
 99%|█████████▉| 10419/10519 [2:47:30<01:35,  1.04it/s][NeMo W 2026-06-19 09:57:12 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:12 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.55it/s]
 99%|█████████▉| 10420/10519 [2:47:31<01:37,  1.01it/s][NeMo W 2026-06-19 09:57:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.39it/s]
 99%|█████████▉| 10421/10519 [2:47:33<01:45,  1.07s/it][NeMo W 2026-06-19 09:57:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.59it/s]
 99%|█████████▉| 10422/10519 [2:47:34<01:40,  1.04s/it][NeMo W 2026-06-19 09:57:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.89it/s]
 99%|█████████▉| 10423/10519 [2:47:35<01:41,  1.06s/it][NeMo W 2026-06-19 09:57:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.35it/s]
 99%|█████████▉| 10424/10519 [2:47:36<01:39,  1.05s/it][NeMo W 2026-06-19 09:57:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.66it/s]
 99%|█████████▉| 10425/10519 [2:47:37<01:31,  1.02it/s][NeMo W 2026-06-19 09:57:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.77it/s]
 99%|█████████▉| 10426/10519 [2:47:37<01:25,  1.09it/s][NeMo W 2026-06-19 09:57:19 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:19 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.98it/s]
 99%|█████████▉| 10427/10519 [2:47:38<01:26,  1.07it/s][NeMo W 2026-06-19 09:57:20 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:20 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.25it/s]
 99%|█████████▉| 10428/10519 [2:47:39<01:24,  1.08it/s][NeMo W 2026-06-19 09:57:21 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:21 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.72it/s]
 99%|█████████▉| 10429/10519 [2:47:40<01:23,  1.08it/s][NeMo W 2026-06-19 09:57:22 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:22 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)


Checkpoint saved: 10450 samples

[NeMo W 2026-06-19 09:57:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.74it/s]
 99%|█████████▉| 10451/10519 [2:48:03<01:31,  1.34s/it][NeMo W 2026-06-19 09:57:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.34it/s]
 99%|█████████▉| 10452/10519 [2:48:04<01:17,  1.16s/it][NeMo W 2026-06-19 09:57:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.73it/s]
 99%|█████████▉| 10453/10519 [2:48:04<01:08,  1.04s/it][NeMo W 2026-06-19 09:57:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.01it/s]
 99%|█████████▉| 10454/10519 [2:48:05<01:05,  1.00s/it][NeMo W 2026-06-19 09:57:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.51it/s]
 99%|█████████▉| 10455/10519 [2:48:06<01:02,  1.03it/s][NeMo W 2026-06-19 09:57:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.82it/s]
 99%|█████████▉| 10456/10519 [2:48:07<01:00,  1.04it/s][NeMo W 2026-06-19 09:57:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.98it/s]
 99%|█████████▉| 10457/10519 [2:48:08<00:54,  1.14it/s][NeMo W 2026-06-19 09:57:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.29it/s]
 99%|█████████▉| 10458/10519 [2:48:09<00:55,  1.10it/s][NeMo W 2026-06-19 09:57:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.35it/s]
 99%|█████████▉| 10459/10519 [2:48:10<00:55,  1.09it/s][NeMo W 2026-06-19 09:57:51 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:51 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.47it/s]
 99%|█████████▉| 10460/10519 [2:48:11<00:51,  1.14it/s][NeMo W 2026-06-19 09:57:52 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:52 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.37it/s]
 99%|█████████▉| 10461/10519 [2:48:11<00:51,  1.12it/s][NeMo W 2026-06-19 09:57:54 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:54 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.01it/s]
 99%|█████████▉| 10462/10519 [2:48:13<00:57,  1.02s/it][NeMo W 2026-06-19 09:57:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.12it/s]
 99%|█████████▉| 10463/10519 [2:48:14<00:57,  1.02s/it][NeMo W 2026-06-19 09:57:55 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:55 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
 99%|█████████▉| 10464/10519 [2:48:15<00:52,  1.06it/s][NeMo W 2026-06-19 09:57:57 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:57 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.57it/s]
 99%|█████████▉| 10465/10519 [2:48:17<01:08,  1.27s/it][NeMo W 2026-06-19 09:57:58 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:58 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.69it/s]
 99%|█████████▉| 10466/10519 [2:48:18<01:01,  1.15s/it][NeMo W 2026-06-19 09:57:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:57:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.69it/s]
100%|█████████▉| 10467/10519 [2:48:18<00:56,  1.08s/it][NeMo W 2026-06-19 09:58:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.37it/s]
100%|█████████▉| 10468/10519 [2:48:19<00:49,  1.03it/s][NeMo W 2026-06-19 09:58:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.25it/s]
100%|█████████▉| 10469/10519 [2:48:20<00:50,  1.01s/it][NeMo W 2026-06-19 09:58:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.51it/s]
100%|█████████▉| 10470/10519 [2:48:21<00:48,  1.02it/s][NeMo W 2026-06-19 09:58:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.14it/s]
100%|█████████▉| 10471/10519 [2:48:22<00:47,  1.01it/s][NeMo W 2026-06-19 09:58:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.04it/s]
100%|█████████▉| 10472/10519 [2:48:23<00:44,  1.05it/s][NeMo W 2026-06-19 09:58:05 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:05 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.13it/s]
100%|█████████▉| 10473/10519 [2:48:24<00:44,  1.04it/s][NeMo W 2026-06-19 09:58:06 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:06 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.75it/s]
100%|█████████▉| 10474/10519 [2:48:25<00:43,  1.04it/s][NeMo W 2026-06-19 09:58:07 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:07 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.38it/s]
100%|█████████▉| 10475/10519 [2:48:26<00:45,  1.03s/it][NeMo W 2026-06-19 09:58:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.27it/s]
100%|█████████▉| 10476/10519 [2:48:27<00:41,  1.03it/s][NeMo W 2026-06-19 09:58:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.45it/s]
100%|█████████▉| 10477/10519 [2:48:28<00:41,  1.02it/s][NeMo W 2026-06-19 09:58:10 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:10 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.89it/s]
100%|█████████▉| 10478/10519 [2:48:29<00:40,  1.01it/s][NeMo W 2026-06-19 09:58:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.61it/s]
100%|█████████▉| 10479/10519 [2:48:30<00:36,  1.11it/s][NeMo W 2026-06-19 09:58:11 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:11 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 14.04it/s]

Checkpoint saved: 10500 samples

[NeMo W 2026-06-19 09:58:33 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:33 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.16it/s]
100%|█████████▉| 10501/10519 [2:48:52<00:21,  1.21s/it][NeMo W 2026-06-19 09:58:34 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:34 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.57it/s]
100%|█████████▉| 10502/10519 [2:48:53<00:19,  1.13s/it][NeMo W 2026-06-19 09:58:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  8.89it/s]
100%|█████████▉| 10503/10519 [2:48:54<00:17,  1.08s/it][NeMo W 2026-06-19 09:58:36 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:36 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.86it/s]
100%|█████████▉| 10504/10519 [2:48:55<00:16,  1.09s/it][NeMo W 2026-06-19 09:58:37 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:37 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  7.60it/s]
100%|█████████▉| 10505/10519 [2:48:56<00:15,  1.12s/it][NeMo W 2026-06-19 09:58:38 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:38 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.91it/s]
100%|█████████▉| 10506/10519 [2:48:57<00:13,  1.07s/it][NeMo W 2026-06-19 09:58:39 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:39 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 13.10it/s]
100%|█████████▉| 10507/10519 [2:48:58<00:12,  1.04s/it][NeMo W 2026-06-19 09:58:40 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:40 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
100%|█████████▉| 10508/10519 [2:48:59<00:11,  1.02s/it][NeMo W 2026-06-19 09:58:41 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:41 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.45it/s]
100%|█████████▉| 10509/10519 [2:49:00<00:09,  1.02it/s][NeMo W 2026-06-19 09:58:42 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:42 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.47it/s]
100%|█████████▉| 10510/10519 [2:49:01<00:08,  1.05it/s][NeMo W 2026-06-19 09:58:43 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:43 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 11.76it/s]
100%|█████████▉| 10511/10519 [2:49:02<00:07,  1.06it/s][NeMo W 2026-06-19 09:58:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.47it/s]
100%|█████████▉| 10512/10519 [2:49:03<00:06,  1.04it/s][NeMo W 2026-06-19 09:58:44 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:44 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.34it/s]
100%|█████████▉| 10513/10519 [2:49:04<00:05,  1.10it/s][NeMo W 2026-06-19 09:58:45 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:45 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 15.37it/s]
100%|█████████▉| 10514/10519 [2:49:04<00:04,  1.16it/s][NeMo W 2026-06-19 09:58:46 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:46 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.97it/s]
100%|█████████▉| 10515/10519 [2:49:05<00:03,  1.05it/s][NeMo W 2026-06-19 09:58:47 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:47 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 0it [00:00, ?it/s]
Transcribing: 1it [00:00,  9.23it/s]
100%|█████████▉| 10516/10519 [2:49:06<00:02,  1.03it/s][NeMo W 2026-06-19 09:58:48 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:48 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.06it/s]
100%|█████████▉| 10517/10519 [2:49:08<00:02,  1.03s/it][NeMo W 2026-06-19 09:58:49 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:49 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 12.90it/s]
100%|█████████▉| 10518/10519 [2:49:09<00:01,  1.04s/it][NeMo W 2026-06-19 09:58:50 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-06-19 09:58:50 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Transcribing: 1it [00:00, 10.96it/s]
100%|██████████| 10519/10519 [2:49:10<00:00,  1.04it/s]

In [ ]:
results_df.to_csv(CHECKPOINT_PATH, index=False)
print("Final checkpoint saved.")

In [ ]:
# normalize AFTER full run
results_df["ref_norm"] = results_df["reference_raw"].apply(normalize_persian)
results_df["hyp_norm"] = results_df["prediction_raw"].apply(normalize_persian)

refs = results_df["ref_norm"].tolist()
hyps = results_df["hyp_norm"].tolist()

wer_score = wer(refs, hyps)
cer_score = cer(refs, hyps)

In [ ]:
if device == "cuda":
    peak_memory = torch.cuda.max_memory_allocated() / 1024**3
else:
    peak_memory = 0

In [ ]:
print("\n=========== FINAL RESULTS ===========\n")

print(f"Samples: {len(results_df)}")
print(f"WER: {wer_score:.4f}")
print(f"CER: {cer_score:.4f}")
print(f"RTF: {rtf:.4f}")
print(f"Avg latency (s): {avg_latency:.4f}")
print(f"Total inference time (s): {total_inference_time:.2f}")
print(f"Total audio duration (s): {total_audio_duration:.2f}")
print(f"Peak GPU memory (GB): {peak_memory:.2f}")

print("\n====================================\n")

In [ ]:
import pandas as pd
import re
import unicodedata
from jiwer import wer, cer

CHECKPOINT_PATH = "/content/drive/MyDrive/asr_project/nemo_checkpoint.csv"

df = pd.read_csv(CHECKPOINT_PATH)

df = df.dropna(subset=["reference_raw", "prediction_raw"]).reset_index(drop=True)

In [ ]:
def extract_nemo_text(x):
    if pd.isna(x):
        return None
    x = str(x)

    # strict extraction of "text='...'"
    match = re.search(r"text='(.*?)'", x)
    if match:
        return match.group(1)

    return None


df["hyp"] = df["prediction_raw"].apply(extract_nemo_text)
df["ref"] = df["reference_raw"].astype(str)

In [ ]:
df_sub = df[['hyp', 'ref']]
df_sub.head()

                      hyp                     ref
0  از مهمونداری کنار بکشم  از مهمونداری کنار بکشم
1                   داغان                دعا خوان
2              اعتماد کرد              اعتماد کرد
3      خب تو چیکار می کنی   خب ، تو چیكار می كنی؟
4              آه نه اصلا           آه، نه اصلاُ!

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:
    if text is None:
        return ""

    text = str(text)

    # Unicode normalization FIRST (important)
    text = unicodedata.normalize("NFKC", text)

    # remove hashtags (NeMo-style filtering)
    text = " ".join(w for w in text.split() if not w.startswith("#"))

    # character replacements
    for k, v in REPLACEMENTS.items():
        text = text.replace(k, v)

    # remove punctuation tokens
    for tok in DISCARD:
        text = text.replace(tok, " ")

    # remove Arabic letter variations like hamza
    text = text.replace("ء", "")

    # collapse whitespace
    text = " ".join(text.split())

    return text

In [ ]:
df_sub["hyp_norm"] = df_sub["hyp"].apply(nemo_paper_normalize)
df_sub["ref_norm"] = df_sub["ref"].apply(nemo_paper_normalize)

/tmp/ipykernel_931/3243310558.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["hyp_norm"] = df_sub["hyp"].apply(nemo_paper_normalize)
/tmp/ipykernel_931/3243310558.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["ref_norm"] = df_sub["ref"].apply(nemo_paper_normalize)

In [ ]:
df_sub.head()

,hyp,ref,hyp_norm,ref_norm
0,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم
1,داغان,دعا خوان,داغان,دعا خوان
2,اعتماد کرد,اعتماد کرد,اعتماد کرد,اعتماد کرد
3,خب تو چیکار می کنی,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,خب تو چیکار می کنی
4,آه نه اصلا,آه، نه اصلاُ!,آه نه اصلا,آه نه اصلا

In [ ]:
df_sub.loc[df_sub["hyp_norm"] == "", "hyp_norm"] = " "
df_sub.loc[df_sub["ref_norm"] == "", "ref_norm"] = " "

In [ ]:
df_sub.head()

,hyp,ref,hyp_norm,ref_norm
0,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم
1,داغان,دعا خوان,داغان,دعا خوان
2,اعتماد کرد,اعتماد کرد,اعتماد کرد,اعتماد کرد
3,خب تو چیکار می کنی,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,خب تو چیکار می کنی
4,آه نه اصلا,آه، نه اصلاُ!,آه نه اصلا,آه نه اصلا

In [ ]:
wer_score = wer(df_sub["ref_norm"].tolist(), df_sub["hyp_norm"].tolist())
cer_score = cer(df_sub["ref_norm"].tolist(), df_sub["hyp_norm"].tolist())

print("NeMo-replicated WER:", wer_score)
print("NeMo-replicated CER:", cer_score)
print("Samples:", len(df_sub))

NeMo-replicated WER: 0.07659851993824203
NeMo-replicated CER: 0.14771397451809823
Samples: 10519

In [ ]:
df_sub.head()

,hyp,ref,hyp_norm,ref_norm
0,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم
1,داغان,دعا خوان,داغان,دعا خوان
2,اعتماد کرد,اعتماد کرد,اعتماد کرد,اعتماد کرد
3,خب تو چیکار می کنی,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,خب تو چیکار می کنی
4,آه نه اصلا,آه، نه اصلاُ!,آه نه اصلا,آه نه اصلا

In [ ]:
pip install kaldialign

Collecting kaldialign
  Downloading kaldialign-0.12.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Downloading kaldialign-0.12.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (110 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 8.5 MB/s eta 0:00:00
Installing collected packages: kaldialign
Successfully installed kaldialign-0.12.0

In [ ]:
import pandas as pd
import kaldialign


def _alignment_error_rate(ref_tokens, hyp_tokens):
    """
    Compute error rate using Kaldi/Icefall alignment.

    Returns:
        error_rate, substitutions, deletions, insertions, reference_length
    """
    ali = kaldialign.align(ref_tokens, hyp_tokens, "*")

    subs = dels = ins = 0

    for r, h in ali:
        if r == "*":
            ins += 1
        elif h == "*":
            dels += 1
        elif r != h:
            subs += 1

    n_ref = len(ref_tokens)
    err = (subs + dels + ins) / max(1, n_ref)

    return err, subs, dels, ins, n_ref


def add_wer_cer_columns(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Adds per-sample WER and CER columns to a dataframe.

    Returns
    -------
    DataFrame
        Copy of dataframe with:
            wer
            cer
            wer_sub
            wer_del
            wer_ins
            cer_sub
            cer_del
            cer_ins
    """

    df = df.copy()

    wers = []
    cers = []

    wer_subs = []
    wer_dels = []
    wer_inss = []

    cer_subs = []
    cer_dels = []
    cer_inss = []

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        # ---------- WER ----------
        wer, s, d, i, _ = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        wers.append(wer)
        wer_subs.append(s)
        wer_dels.append(d)
        wer_inss.append(i)

        # ---------- CER ----------
        cer, s, d, i, _ = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        cers.append(cer)
        cer_subs.append(s)
        cer_dels.append(d)
        cer_inss.append(i)

    df["wer"] = wers
    df["cer"] = cers

    df["wer_sub"] = wer_subs
    df["wer_del"] = wer_dels
    df["wer_ins"] = wer_inss

    df["cer_sub"] = cer_subs
    df["cer_del"] = cer_dels
    df["cer_ins"] = cer_inss

    return df


def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
# Add per-utterance metrics
df_sub = add_wer_cer_columns(df_sub)

# Inspect individual utterances
df_sub[["hyp_norm", "ref_norm", "wer", "cer"]].head()

                 hyp_norm                ref_norm  wer       cer
0  از مهمونداری کنار بکشم  از مهمونداری کنار بکشم  0.0  0.000000
1                   داغان                دعا خوان  1.0  0.428571
2              اعتماد کرد              اعتماد کرد  0.0  0.000000
3      خب تو چیکار می کنی      خب تو چیکار می کنی  0.0  0.000000
4              آه نه اصلا              آه نه اصلا  0.0  0.000000

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref",
    hyp_col="hyp",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

compute_dataset_wer_cer(df_sub)

{'WER': 0.12325255967967635,
 'CER': 0.03793886462882096,
 'word_sub': 7659,
 'word_del': 1006,
 'word_ins': 231,
 'char_sub': 1382,
 'char_del': 9152,
 'char_ins': 326,
 'total_words': 72177,
 'total_chars': 286250}

### results

In [ ]:
results = compute_dataset_wer_cer(df_sub)

print(f"WER: {results['WER']:.4f}")
print(f"CER: {results['CER']:.4f}")
print(results)

WER: 0.1233
CER: 0.0379
{'WER': 0.12325255967967635, 'CER': 0.03793886462882096, 'word_sub': 7659, 'word_del': 1006, 'word_ins': 231, 'char_sub': 1382, 'char_del': 9152, 'char_ins': 326, 'total_words': 72177, 'total_chars': 286250}

In [ ]:
df_sub

,hyp,ref,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
0,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,0.000000,0.000000,0,0,0,0,0,0
1,داغان,دعا خوان,داغان,دعا خوان,1.000000,0.428571,1,1,0,1,2,0
2,اعتماد کرد,اعتماد کرد,اعتماد کرد,اعتماد کرد,0.000000,0.000000,0,0,0,0,0,0
3,خب تو چیکار می کنی,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,خب تو چیکار می کنی,0.000000,0.000000,0,0,0,0,0,0
4,آه نه اصلا,آه، نه اصلاُ!,آه نه اصلا,آه نه اصلا,0.000000,0.000000,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10514,بخورن گوشت قرمز پروتئین توی این گرما اور می پوشه,بخورن، گوشت قرمز، پروتئین توی این گرما اُور می...,بخورن گوشت قرمز پروتئین توی این گرما اور می پوشه,بخورن گوشت قرمز پروتئین توی این گرما ا ور می پوشه,0.181818,0.000000,1,1,0,0,0,0
10515,خود را از وان بیرون می کشد و کنار وان مینشیند,خود را از وان بیرون می کشد و کنار وان مینشیند,خود را از وان بیرون می کشد و کنار وان مینشیند,خود را از وان بیرون می کشد و کنار وان مینشیند,0.000000,0.000000,0,0,0,0,0,0
10516,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,0.000000,0.000000,0,0,0,0,0,0
10517,پدر از تخت پایین میآید عصا را باز میکند,پدر از تخت پایین میآید عصا را باز میکند,پدر از تخت پایین میآید عصا را باز میکند,پدر از تخت پایین میآید عصا را باز میکند,0.000000,0.000000,0,0,0,0,0,0
10518,خدا ازشون نگذره پوست مونده و استخون ازشاب شده بچم,خدا ازشون نگذره پوست مونده و استخون ازش.اب شده...,خدا ازشون نگذره پوست مونده و استخون ازشاب شده بچم,خدا ازشون نگذره پوست مونده و استخون ازش اب شده...,0.181818,0.000000,1,1,0,0,0,0

In [ ]:
df_sub[df_sub["ref_norm"].str.match(r"^(?=.*\d)(?=.*[^\d]).+", na=False)]

Empty DataFrame
Columns: [hyp, ref, hyp_norm, ref_norm, wer, cer, wer_sub, wer_del, wer_ins, cer_sub, cer_del, cer_ins]
Index: []

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df_sub)

https://docs.google.com/spreadsheets/d/1Q8zqVEME9yd3XcX58O9CDV2WcWhvVLzvqaU79xxA7-s/edit#gid=0

In [ ]:
df_sub

,hyp,ref,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
0,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,0.000000,0.000000,0,0,0,0,0,0
1,داغان,دعا خوان,داغان,دعا خوان,1.000000,0.428571,1,1,0,1,2,0
2,اعتماد کرد,اعتماد کرد,اعتماد کرد,اعتماد کرد,0.000000,0.000000,0,0,0,0,0,0
3,خب تو چیکار می کنی,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,خب تو چیکار می کنی,0.000000,0.000000,0,0,0,0,0,0
4,آه نه اصلا,آه، نه اصلاُ!,آه نه اصلا,آه نه اصلا,0.000000,0.000000,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10514,بخورن گوشت قرمز پروتئین توی این گرما اور می پوشه,بخورن، گوشت قرمز، پروتئین توی این گرما اُور می...,بخورن گوشت قرمز پروتئین توی این گرما اور می پوشه,بخورن گوشت قرمز پروتئین توی این گرما ا ور می پوشه,0.181818,0.000000,1,1,0,0,0,0
10515,خود را از وان بیرون می کشد و کنار وان مینشیند,خود را از وان بیرون می کشد و کنار وان مینشیند,خود را از وان بیرون می کشد و کنار وان مینشیند,خود را از وان بیرون می کشد و کنار وان مینشیند,0.000000,0.000000,0,0,0,0,0,0
10516,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,هیچ وقت زیر قولت نزن من از آدمای بدقول بدم مییاد,0.000000,0.000000,0,0,0,0,0,0
10517,پدر از تخت پایین میآید عصا را باز میکند,پدر از تخت پایین میآید عصا را باز میکند,پدر از تخت پایین میآید عصا را باز میکند,پدر از تخت پایین میآید عصا را باز میکند,0.000000,0.000000,0,0,0,0,0,0
10518,خدا ازشون نگذره پوست مونده و استخون ازشاب شده بچم,خدا ازشون نگذره پوست مونده و استخون ازش.اب شده...,خدا ازشون نگذره پوست مونده و استخون ازشاب شده بچم,خدا ازشون نگذره پوست مونده و استخون ازش اب شده...,0.181818,0.000000,1,1,0,0,0,0

In [ ]:
df_sub_1 = df_sub[df_sub['cer'] > df_sub['wer']]
df_sub_1

,hyp,ref,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
108,فقط رفتن تو بزرگراه و گشت زدن,(خنده) فقط، رفتن تو بزرگراه و گشت زدن,فقط رفتن تو بزرگراه و گشت زدن,خنده فقط رفتن تو بزرگراه و گشت زدن,0.125000,0.148148,0,1,0,0,4,0
688,در این نزدیکی چشمه آبی هست و من مرتب نوک خود ر...,پاسخ داد : در این نزدیکی چشمه آبی هست و من مرت...,در این نزدیکی چشمه آبی هست و من مرتب نوک خود ر...,پاسخ داد در این نزدیکی چشمه آبی هست و من مرتب ...,0.076923,0.098592,0,2,0,0,7,0
1006,ترامپ گفته بن سلمان بیشتر از من از جنایت نفرت ...,ترامپ گفته بن سلمان بیشتر از من از جنایت نفرت ...,ترامپ گفته بن سلمان بیشتر از من از جنایت نفرت ...,ترامپ گفته بن سلمان بیشتر از من از جنایت نفرت ...,0.090909,0.100000,0,0,1,0,0,4
1495,حالا نمیدونم حکایت این آیه ست که میگه ان مع ال...,حالا نمیدونم حکایت این آیه ست که میگه ان مع ال...,حالا نمیدونم حکایت این آیه ست که میگه ان مع ال...,حالا نمیدونم حکایت این آیه ست که میگه ان مع ال...,0.052632,0.056338,0,1,0,0,4,0
1699,بنابراین در جلسات اغلب کنار دست من مینشست تا ب...,بنابراین در جلسات اغلب کنار دست من مینشست تا ب...,بنابراین در جلسات اغلب کنار دست من مینشست تا ب...,بنابراین در جلسات اغلب کنار دست من مینشست تا ب...,0.285714,0.311475,0,4,0,0,19,0
3096,فکر می کنم بعضی از عکس ها کم نور دیده اند,فکر می کنم بعضی از این عکس ها کم نور دیده اند.,فکر می کنم بعضی از عکس ها کم نور دیده اند,فکر می کنم بعضی از این عکس ها کم نور دیده اند,0.083333,0.088235,0,1,0,0,3,0
3431,احساس مرموزی به من دست داده بود که کسی دارد مر...,احساس مرموزی به من دست داده بود که کسی دارد مر...,احساس مرموزی به من دست داده بود که کسی دارد مر...,احساس مرموزی به من دست داده بود که کسی دارد مر...,0.083333,0.093023,1,0,0,0,4,0
3727,این که همش شد موش فکر کردم اسمت دیو سه سره,با خنده این که همش شد موش. فکر کردم اسمت دیو س...,این که همش شد موش فکر کردم اسمت دیو سه سره,با خنده این که همش شد موش فکر کردم اسمت دیو سه...,0.153846,0.157895,0,2,0,0,6,0
4078,از خودم,از خودم در نمیآورم,از خودم,از خودم در نمیآورم,0.500000,0.600000,0,2,0,0,9,0
4355,تاچشم به آخر اسفندماه شد و باز یه سال بزرگتر ش...,تاچشم به هم بزنی میبینی آخر اسفندماه شد و باز ...,تاچشم به آخر اسفندماه شد و باز یه سال بزرگتر ش...,تاچشم به هم بزنی میبینی آخر اسفندماه شد و باز ...,0.166667,0.171429,0,3,0,0,12,0
4468,داری قرار نمیدی,برنامه داری قرار نمیدی,داری قرار نمیدی,برنامه داری قرار نمیدی,0.250000,0.315789,0,1,0,0,6,0
5704,او اسرار خود را با خود به گور,او اسرار خود را با خود به گور برد.,او اسرار خود را با خود به گور,او اسرار خود را با خود به گور برد,0.111111,0.120000,0,1,0,0,3,0
5987,روزنهی امیدی که شاید او نیز شفا,روزنهی امیدی که شاید او نیز شفا یابد,روزنهی امیدی که شاید او نیز شفا,روزنهی امیدی که شاید او نیز شفا یابد,0.125000,0.137931,0,1,0,0,4,0
6825,رفتار او با زندانیان بیرحمانه و حقانی بود,رفتار او با زندانیان بیرحمانه و غیرانسانی بود.,رفتار او با زندانیان بیرحمانه و حقانی بود,رفتار او با زندانیان بیرحمانه و غیرانسانی بود,0.125000,0.157895,1,0,0,2,4,0
7796,وقتی بزرگ شدم می خوام اون داره میره,وقتی بزرگ شدم می خوام همونجایی که اون داره میر...,وقتی بزرگ شدم می خوام اون داره میره,وقتی بزرگ شدم می خوام همونجایی که اون داره میر...,0.272727,0.317073,0,3,0,0,13,0
8222,واقعا خیلی باشعوری این رفتار بشر نمی کنم,واقعاً خیلی باشعوری. این رفتار بشر دوستانتو فر...,واقعا خیلی باشعوری این رفتار بشر نمی کنم,واقعا خیلی باشعوری این رفتار بشر دوستانتو فرام...,0.200000,0.297872,0,2,0,0,14,0
8550,کدام طرف گرفت,کدام طرف امتیاز گرفت؟,کدام طرف گرفت,کدام طرف امتیاز گرفت,0.250000,0.352941,0,1,0,0,6,0
9725,بیا بحث را در سطح دوستانه نگه,بیا بحث را در سطح دوستانه نگهداریم.,بیا بحث را در سطح دوستانه نگه,بیا بحث را در سطح دوستانه نگهداریم,0.142857,0.178571,1,0,0,0,5,0
9852,من فهمیدم که تشکر از مردم به اشتراک گذاری اعتب...,من فهمیدم که تشکر از مردم، به اشتراک گذاری اعت...,من فهمیدم که تشکر از مردم به اشتراک گذاری اعتب...,من فهمیدم که تشکر از مردم به اشتراک گذاری اعتب...,0.130435,0.135417,1,2,0,1,12,0
10316,برای من هیچ چی,برای من هیچ چیزی، متشکرم.,برای من هیچ چی,برای من هیچ چیزی متشکرم,0.400000,0.421053,1,1,0,0,8,0

In [ ]:
df_sub.count()

hyp         10519
ref         10519
hyp_norm    10519
ref_norm    10519
wer         10519
cer         10519
wer_sub     10519
wer_del     10519
wer_ins     10519
cer_sub     10519
cer_del     10519
cer_ins     10519
dtype: int64

In [ ]:
df_sub = df_sub.drop(index=1701)
df_sub.count()

hyp         10518
ref         10518
hyp_norm    10518
ref_norm    10518
wer         10518
cer         10518
wer_sub     10518
wer_del     10518
wer_ins     10518
cer_sub     10518
cer_del     10518
cer_ins     10518
dtype: int64

In [ ]:
df_sub[df_sub["ref"].str.contains(r"\f", na=False)]

Empty DataFrame
Columns: [hyp, ref, hyp_norm, ref_norm, wer, cer, wer_sub, wer_del, wer_ins, cer_sub, cer_del, cer_ins]
Index: []

# w2v

In [ ]:
!pip install -q transformers datasets evaluate jiwer
!pip install -q torchaudio librosa soundfile
!pip install -q hazm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 39.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 72.4 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
import zipfile
import os

ZIP_PATH = "/content/drive/MyDrive/asr_project/fa_test_only.zip"
EXTRACT_PATH = "/content/drive/MyDrive/asr_project/asr_data/"
with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
      zip_ref.extractall(EXTRACT_PATH)
      print("Dataset extracted to:", EXTRACT_PATH)

Dataset extracted to: /content/drive/MyDrive/asr_project/asr_data/

In [ ]:
import os
import time
import random
import numpy as np
import pandas as pd
import torch
import librosa
import soundfile as sf
from tqdm import tqdm

from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC

In [ ]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

In [ ]:
DATA_ROOT = "/content/drive/MyDrive/asr_project/asr_data/fa_test_only"

TSV_PATH = os.path.join(DATA_ROOT, "test.tsv")
AUDIO_ROOT = os.path.join(DATA_ROOT, "clips")

df = pd.read_csv(TSV_PATH, sep="\t")
df = df.dropna(subset=["path", "sentence"]).reset_index(drop=True)

df["audio_path"] = df["path"].apply(
    lambda x: os.path.join(AUDIO_ROOT, x)
)

print("Samples:", len(df))

Samples: 10519

In [ ]:
MODEL_NAME = "m3hrdadfi/wav2vec2-large-xlsr-persian-v3"

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = Wav2Vec2Processor.from_pretrained(MODEL_NAME)
model = Wav2Vec2ForCTC.from_pretrained(MODEL_NAME).to(device)

print("Device:", device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/307 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Device: cuda

In [ ]:
CHECKPOINT_PATH = (
    "/content/drive/MyDrive/asr_project/w2v_persian_checkpoint.csv"
)

if os.path.exists(CHECKPOINT_PATH):

    results_df = pd.read_csv(CHECKPOINT_PATH)
    processed = set(results_df["audio_path"].tolist())
    print("Resuming from:", len(results_df))

else:

    results_df = pd.DataFrame(columns=[
        "audio_path",
        "reference_raw",
        "prediction_raw",
        "audio_duration",
        "inference_time"
    ])

    processed = set()

In [ ]:
torch.cuda.empty_cache()

if device == "cuda":
    torch.cuda.reset_peak_memory_stats()

start_time = time.time()

for idx in tqdm(range(len(df))):

    row = df.iloc[idx]
    audio_path = row["audio_path"]

    if audio_path in processed:
        continue

    try:

        info = sf.info(audio_path)
        duration = info.frames / info.samplerate

        audio, sr = librosa.load(audio_path, sr=16000)

        inputs = processor(
            audio,
            sampling_rate=16000,
            return_tensors="pt"
        )

        input_values = inputs.input_values.to(device)

        t0 = time.time()

        with torch.no_grad():
            logits = model(input_values).logits

        pred_ids = torch.argmax(logits, dim=-1)
        pred_text = processor.batch_decode(pred_ids)[0]

        t1 = time.time()

        inference_time = t1 - t0

        new_row = {
            "audio_path": audio_path,
            "reference_raw": row["sentence"],
            "prediction_raw": pred_text,
            "audio_duration": duration,
            "inference_time": inference_time
        }

        results_df = pd.concat(
            [results_df, pd.DataFrame([new_row])],
            ignore_index=True
        )

        processed.add(audio_path)

        if len(results_df) % 50 == 0:
            results_df.to_csv(CHECKPOINT_PATH, index=False)
            print(f"Checkpoint saved: {len(results_df)}")

    except Exception as e:
        print("FAILED:", audio_path)
        print(e)

# final save
results_df.to_csv(CHECKPOINT_PATH, index=False)
print("Final checkpoint saved")

  0%|          | 0/10519 [00:00<?, ?it/s]/tmp/ipykernel_1966/1071912746.py:51: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat(
  0%|          | 52/10519 [00:04<16:03, 10.86it/s]

Checkpoint saved: 50

  1%|          | 102/10519 [00:08<15:43, 11.04it/s]

Checkpoint saved: 100

  1%|▏         | 152/10519 [00:12<12:14, 14.12it/s]

Checkpoint saved: 150

  2%|▏         | 201/10519 [00:16<12:09, 14.15it/s]

Checkpoint saved: 200

  2%|▏         | 250/10519 [00:20<24:41,  6.93it/s]

Checkpoint saved: 250

  3%|▎         | 301/10519 [00:26<13:35, 12.53it/s]

Checkpoint saved: 300

  3%|▎         | 351/10519 [00:30<13:36, 12.46it/s]

Checkpoint saved: 350

  4%|▍         | 401/10519 [00:34<12:56, 13.02it/s]

Checkpoint saved: 400

  4%|▍         | 452/10519 [00:38<14:29, 11.58it/s]

Checkpoint saved: 450

  5%|▍         | 501/10519 [00:44<27:23,  6.09it/s]

Checkpoint saved: 500

  5%|▌         | 553/10519 [00:49<11:26, 14.52it/s]

Checkpoint saved: 550

  6%|▌         | 601/10519 [00:53<16:16, 10.16it/s]

Checkpoint saved: 600

  6%|▌         | 651/10519 [00:57<18:39,  8.81it/s]

Checkpoint saved: 650

  7%|▋         | 701/10519 [01:02<14:07, 11.58it/s]

Checkpoint saved: 700

  7%|▋         | 751/10519 [01:06<16:51,  9.66it/s]

Checkpoint saved: 750

  8%|▊         | 802/10519 [01:11<12:35, 12.86it/s]

Checkpoint saved: 800

  8%|▊         | 852/10519 [01:15<14:40, 10.98it/s]

Checkpoint saved: 850

  9%|▊         | 902/10519 [01:20<15:30, 10.33it/s]

Checkpoint saved: 900

  9%|▉         | 952/10519 [01:24<12:01, 13.26it/s]

Checkpoint saved: 950

 10%|▉         | 1002/10519 [01:28<13:38, 11.63it/s]

Checkpoint saved: 1000

 10%|█         | 1052/10519 [01:33<14:21, 11.00it/s]

Checkpoint saved: 1050

 10%|█         | 1102/10519 [01:37<13:36, 11.53it/s]

Checkpoint saved: 1100

 11%|█         | 1152/10519 [01:42<13:43, 11.37it/s]

Checkpoint saved: 1150

 11%|█▏        | 1202/10519 [01:52<15:39,  9.91it/s]

Checkpoint saved: 1200

 12%|█▏        | 1252/10519 [01:56<13:41, 11.28it/s]

Checkpoint saved: 1250

 12%|█▏        | 1302/10519 [02:01<16:05,  9.55it/s]

Checkpoint saved: 1300

 13%|█▎        | 1352/10519 [02:05<13:44, 11.12it/s]

Checkpoint saved: 1350

 13%|█▎        | 1402/10519 [02:10<12:55, 11.75it/s]

Checkpoint saved: 1400

 14%|█▍        | 1452/10519 [02:14<14:15, 10.60it/s]

Checkpoint saved: 1450

 14%|█▍        | 1502/10519 [02:19<15:46,  9.53it/s]

Checkpoint saved: 1500

 15%|█▍        | 1552/10519 [02:24<14:19, 10.43it/s]

Checkpoint saved: 1550

 15%|█▌        | 1602/10519 [02:28<13:31, 10.98it/s]

Checkpoint saved: 1600

 16%|█▌        | 1651/10519 [02:33<12:28, 11.84it/s]

Checkpoint saved: 1650

 16%|█▌        | 1702/10519 [02:38<17:35,  8.35it/s]

Checkpoint saved: 1700

 17%|█▋        | 1751/10519 [02:43<19:09,  7.63it/s]

Checkpoint saved: 1750

 17%|█▋        | 1801/10519 [02:47<12:13, 11.89it/s]

Checkpoint saved: 1800

 18%|█▊        | 1852/10519 [02:52<13:57, 10.35it/s]

Checkpoint saved: 1850

 18%|█▊        | 1902/10519 [02:57<13:12, 10.88it/s]

Checkpoint saved: 1900

 19%|█▊        | 1952/10519 [03:02<13:51, 10.31it/s]

Checkpoint saved: 1950

 19%|█▉        | 2001/10519 [03:06<10:19, 13.76it/s]

Checkpoint saved: 2000

 20%|█▉        | 2053/10519 [03:11<11:16, 12.52it/s]

Checkpoint saved: 2050

 20%|█▉        | 2102/10519 [03:16<12:01, 11.66it/s]

Checkpoint saved: 2100

 20%|██        | 2150/10519 [03:20<13:23, 10.41it/s]

Checkpoint saved: 2150

 21%|██        | 2202/10519 [03:26<15:26,  8.98it/s]

Checkpoint saved: 2200

 21%|██▏       | 2250/10519 [03:31<13:11, 10.44it/s]

Checkpoint saved: 2250

 22%|██▏       | 2302/10519 [03:36<13:13, 10.35it/s]

Checkpoint saved: 2300

 22%|██▏       | 2350/10519 [03:40<15:27,  8.81it/s]

Checkpoint saved: 2350

 23%|██▎       | 2402/10519 [03:46<12:19, 10.98it/s]

Checkpoint saved: 2400

 23%|██▎       | 2451/10519 [03:51<12:54, 10.42it/s]

Checkpoint saved: 2450

 24%|██▍       | 2502/10519 [03:56<12:14, 10.92it/s]

Checkpoint saved: 2500

 24%|██▍       | 2552/10519 [04:00<11:12, 11.85it/s]

Checkpoint saved: 2550

 25%|██▍       | 2602/10519 [04:05<10:27, 12.61it/s]

Checkpoint saved: 2600

 25%|██▌       | 2650/10519 [04:09<13:17,  9.87it/s]

Checkpoint saved: 2650

 26%|██▌       | 2702/10519 [04:14<12:19, 10.56it/s]

Checkpoint saved: 2700

 26%|██▌       | 2751/10519 [04:19<14:20,  9.03it/s]

Checkpoint saved: 2750

 27%|██▋       | 2801/10519 [04:24<11:59, 10.73it/s]

Checkpoint saved: 2800

 27%|██▋       | 2851/10519 [04:28<10:22, 12.31it/s]

Checkpoint saved: 2850

 28%|██▊       | 2901/10519 [04:32<13:37,  9.32it/s]

Checkpoint saved: 2900

 28%|██▊       | 2951/10519 [04:38<12:30, 10.08it/s]

Checkpoint saved: 2950

 29%|██▊       | 3002/10519 [04:43<13:23,  9.35it/s]

Checkpoint saved: 3000

 29%|██▉       | 3052/10519 [04:48<12:12, 10.20it/s]

Checkpoint saved: 3050

 29%|██▉       | 3102/10519 [04:53<11:51, 10.42it/s]

Checkpoint saved: 3100

 30%|██▉       | 3151/10519 [04:57<13:20,  9.20it/s]

Checkpoint saved: 3150

 30%|███       | 3200/10519 [05:02<13:47,  8.85it/s]

Checkpoint saved: 3200

 31%|███       | 3252/10519 [05:07<11:17, 10.73it/s]

Checkpoint saved: 3250

 31%|███▏      | 3302/10519 [05:12<10:28, 11.48it/s]

Checkpoint saved: 3300

 32%|███▏      | 3352/10519 [05:17<12:44,  9.38it/s]

Checkpoint saved: 3350

 32%|███▏      | 3401/10519 [05:21<10:09, 11.67it/s]

Checkpoint saved: 3400

 33%|███▎      | 3452/10519 [05:27<16:50,  6.99it/s]

Checkpoint saved: 3450

 33%|███▎      | 3501/10519 [05:32<11:45,  9.95it/s]

Checkpoint saved: 3500

 34%|███▍      | 3551/10519 [05:36<10:05, 11.50it/s]

Checkpoint saved: 3550

 34%|███▍      | 3602/10519 [05:41<10:56, 10.54it/s]

Checkpoint saved: 3600

 35%|███▍      | 3651/10519 [05:45<10:40, 10.72it/s]

Checkpoint saved: 3650

 35%|███▌      | 3701/10519 [05:50<09:31, 11.94it/s]

Checkpoint saved: 3700

 36%|███▌      | 3751/10519 [05:54<09:49, 11.48it/s]

Checkpoint saved: 3750

 36%|███▌      | 3801/10519 [05:59<09:36, 11.65it/s]

Checkpoint saved: 3800

 37%|███▋      | 3851/10519 [06:04<10:17, 10.80it/s]

Checkpoint saved: 3850

 37%|███▋      | 3901/10519 [06:08<11:22,  9.70it/s]

Checkpoint saved: 3900

 38%|███▊      | 3950/10519 [06:13<10:15, 10.68it/s]

Checkpoint saved: 3950

 38%|███▊      | 4002/10519 [06:18<11:42,  9.27it/s]

Checkpoint saved: 4000

 39%|███▊      | 4052/10519 [06:23<10:54,  9.88it/s]

Checkpoint saved: 4050

 39%|███▉      | 4102/10519 [06:28<10:26, 10.25it/s]

Checkpoint saved: 4100

 39%|███▉      | 4151/10519 [06:33<13:47,  7.70it/s]

Checkpoint saved: 4150

 40%|███▉      | 4203/10519 [06:38<09:44, 10.81it/s]

Checkpoint saved: 4200

 40%|████      | 4251/10519 [06:44<35:20,  2.96it/s]

Checkpoint saved: 4250

 41%|████      | 4301/10519 [06:49<09:34, 10.83it/s]

Checkpoint saved: 4300

 41%|████▏     | 4352/10519 [06:54<09:23, 10.95it/s]

Checkpoint saved: 4350

 42%|████▏     | 4402/10519 [06:59<11:25,  8.92it/s]

Checkpoint saved: 4400

 42%|████▏     | 4451/10519 [07:04<10:11,  9.92it/s]

Checkpoint saved: 4450

 43%|████▎     | 4501/10519 [07:09<11:19,  8.86it/s]

Checkpoint saved: 4500

 43%|████▎     | 4550/10519 [07:14<13:08,  7.57it/s]

Checkpoint saved: 4550

 44%|████▎     | 4601/10519 [07:20<09:17, 10.61it/s]

Checkpoint saved: 4600

 44%|████▍     | 4651/10519 [07:24<10:51,  9.00it/s]

Checkpoint saved: 4650

 45%|████▍     | 4702/10519 [07:29<09:31, 10.18it/s]

Checkpoint saved: 4700

 45%|████▌     | 4751/10519 [07:34<11:55,  8.07it/s]

Checkpoint saved: 4750

 46%|████▌     | 4802/10519 [07:39<10:32,  9.04it/s]

Checkpoint saved: 4800

 46%|████▌     | 4853/10519 [07:43<08:10, 11.56it/s]

Checkpoint saved: 4850

 47%|████▋     | 4902/10519 [07:48<10:12,  9.16it/s]

Checkpoint saved: 4900

 47%|████▋     | 4952/10519 [07:53<09:33,  9.70it/s]

Checkpoint saved: 4950

 48%|████▊     | 5002/10519 [07:58<09:59,  9.20it/s]

Checkpoint saved: 5000

 48%|████▊     | 5051/10519 [08:03<09:11,  9.91it/s]

Checkpoint saved: 5050

 48%|████▊     | 5100/10519 [08:08<11:05,  8.14it/s]

Checkpoint saved: 5100

 49%|████▉     | 5153/10519 [08:13<07:47, 11.47it/s]

Checkpoint saved: 5150

 49%|████▉     | 5203/10519 [08:18<07:18, 12.12it/s]

Checkpoint saved: 5200

 50%|████▉     | 5251/10519 [08:22<08:25, 10.42it/s]

Checkpoint saved: 5250

 50%|█████     | 5302/10519 [08:27<08:05, 10.74it/s]

Checkpoint saved: 5300

 51%|█████     | 5351/10519 [08:32<09:05,  9.47it/s]

Checkpoint saved: 5350

 51%|█████▏    | 5402/10519 [08:37<09:06,  9.36it/s]

Checkpoint saved: 5400

 52%|█████▏    | 5452/10519 [08:41<09:32,  8.85it/s]

Checkpoint saved: 5450

 52%|█████▏    | 5501/10519 [08:46<09:25,  8.88it/s]

Checkpoint saved: 5500

 53%|█████▎    | 5552/10519 [08:51<07:46, 10.66it/s]

Checkpoint saved: 5550

 53%|█████▎    | 5601/10519 [08:57<09:56,  8.25it/s]

Checkpoint saved: 5600

 54%|█████▎    | 5652/10519 [09:02<08:19,  9.75it/s]

Checkpoint saved: 5650

 54%|█████▍    | 5701/10519 [09:06<06:52, 11.69it/s]

Checkpoint saved: 5700

 55%|█████▍    | 5752/10519 [09:11<07:30, 10.59it/s]

Checkpoint saved: 5750

 55%|█████▌    | 5801/10519 [09:16<07:42, 10.20it/s]

Checkpoint saved: 5800

 56%|█████▌    | 5852/10519 [09:20<07:19, 10.61it/s]

Checkpoint saved: 5850

 56%|█████▌    | 5900/10519 [09:25<08:07,  9.48it/s]

Checkpoint saved: 5900

 57%|█████▋    | 5951/10519 [09:30<08:37,  8.83it/s]

Checkpoint saved: 5950

 57%|█████▋    | 6002/10519 [09:35<08:40,  8.67it/s]

Checkpoint saved: 6000

 58%|█████▊    | 6051/10519 [09:40<08:03,  9.25it/s]

Checkpoint saved: 6050

 58%|█████▊    | 6100/10519 [09:45<07:22,  9.99it/s]

Checkpoint saved: 6100

 58%|█████▊    | 6151/10519 [09:50<08:53,  8.19it/s]

Checkpoint saved: 6150

 59%|█████▉    | 6201/10519 [09:55<10:12,  7.05it/s]

Checkpoint saved: 6200

 59%|█████▉    | 6252/10519 [09:59<06:05, 11.68it/s]

Checkpoint saved: 6250

 60%|█████▉    | 6302/10519 [10:03<06:13, 11.29it/s]

Checkpoint saved: 6300

 60%|██████    | 6352/10519 [10:08<06:00, 11.55it/s]

Checkpoint saved: 6350

 61%|██████    | 6402/10519 [10:12<06:00, 11.42it/s]

Checkpoint saved: 6400

 61%|██████▏   | 6452/10519 [10:17<07:21,  9.21it/s]

Checkpoint saved: 6450

 62%|██████▏   | 6502/10519 [10:21<06:26, 10.40it/s]

Checkpoint saved: 6500

 62%|██████▏   | 6550/10519 [10:26<06:15, 10.58it/s]

Checkpoint saved: 6550

 63%|██████▎   | 6603/10519 [10:31<06:25, 10.17it/s]

Checkpoint saved: 6600

 63%|██████▎   | 6651/10519 [10:35<05:37, 11.45it/s]

Checkpoint saved: 6650

 64%|██████▎   | 6703/10519 [10:40<05:07, 12.43it/s]

Checkpoint saved: 6700

 64%|██████▍   | 6751/10519 [10:44<06:01, 10.43it/s]

Checkpoint saved: 6750

 65%|██████▍   | 6801/10519 [10:49<05:30, 11.26it/s]

Checkpoint saved: 6800

 65%|██████▌   | 6851/10519 [10:53<06:11,  9.88it/s]

Checkpoint saved: 6850

 66%|██████▌   | 6901/10519 [10:58<06:30,  9.27it/s]

Checkpoint saved: 6900

 66%|██████▌   | 6950/10519 [11:03<07:08,  8.33it/s]

Checkpoint saved: 6950

 67%|██████▋   | 7003/10519 [11:09<05:04, 11.54it/s]

Checkpoint saved: 7000

 67%|██████▋   | 7050/10519 [11:13<05:58,  9.69it/s]

Checkpoint saved: 7050

 68%|██████▊   | 7101/10519 [11:18<04:59, 11.41it/s]

Checkpoint saved: 7100

 68%|██████▊   | 7152/10519 [11:23<06:39,  8.42it/s]

Checkpoint saved: 7150

 68%|██████▊   | 7201/10519 [11:28<06:58,  7.92it/s]

Checkpoint saved: 7200

 69%|██████▉   | 7253/10519 [11:33<04:41, 11.61it/s]

Checkpoint saved: 7250

 69%|██████▉   | 7302/10519 [11:38<06:12,  8.63it/s]

Checkpoint saved: 7300

 70%|██████▉   | 7351/10519 [11:43<05:34,  9.47it/s]

Checkpoint saved: 7350

 70%|███████   | 7401/10519 [11:47<06:27,  8.04it/s]

Checkpoint saved: 7400

 71%|███████   | 7452/10519 [11:52<05:20,  9.57it/s]

Checkpoint saved: 7450

 71%|███████▏  | 7501/10519 [11:57<04:38, 10.85it/s]

Checkpoint saved: 7500

 72%|███████▏  | 7551/10519 [12:01<04:54, 10.08it/s]

Checkpoint saved: 7550

 72%|███████▏  | 7602/10519 [12:06<05:37,  8.64it/s]

Checkpoint saved: 7600

 73%|███████▎  | 7652/10519 [12:11<04:48,  9.93it/s]

Checkpoint saved: 7650

 73%|███████▎  | 7702/10519 [12:15<03:47, 12.37it/s]

Checkpoint saved: 7700

 74%|███████▎  | 7751/10519 [12:20<05:59,  7.70it/s]

Checkpoint saved: 7750

 74%|███████▍  | 7802/10519 [12:25<04:53,  9.25it/s]

Checkpoint saved: 7800

 75%|███████▍  | 7851/10519 [12:30<05:30,  8.07it/s]

Checkpoint saved: 7850

 75%|███████▌  | 7902/10519 [12:34<04:31,  9.63it/s]

Checkpoint saved: 7900

 76%|███████▌  | 7951/10519 [12:39<05:56,  7.19it/s]

Checkpoint saved: 7950

 76%|███████▌  | 8002/10519 [12:44<04:12,  9.98it/s]

Checkpoint saved: 8000

 77%|███████▋  | 8052/10519 [12:49<04:14,  9.68it/s]

Checkpoint saved: 8050

 77%|███████▋  | 8102/10519 [12:54<04:11,  9.59it/s]

Checkpoint saved: 8100

 77%|███████▋  | 8151/10519 [12:59<04:30,  8.76it/s]

Checkpoint saved: 8150

 78%|███████▊  | 8202/10519 [13:03<03:47, 10.18it/s]

Checkpoint saved: 8200

 78%|███████▊  | 8252/10519 [13:08<03:15, 11.57it/s]

Checkpoint saved: 8250

 79%|███████▉  | 8301/10519 [13:12<03:47,  9.74it/s]

Checkpoint saved: 8300

 79%|███████▉  | 8350/10519 [13:17<03:24, 10.58it/s]

Checkpoint saved: 8350

 80%|███████▉  | 8402/10519 [13:22<03:33,  9.94it/s]

Checkpoint saved: 8400

 80%|████████  | 8451/10519 [13:27<04:03,  8.48it/s]

Checkpoint saved: 8450

 81%|████████  | 8502/10519 [13:32<03:24,  9.85it/s]

Checkpoint saved: 8500

 81%|████████▏ | 8552/10519 [13:36<02:47, 11.72it/s]

Checkpoint saved: 8550

 82%|████████▏ | 8602/10519 [13:41<03:18,  9.65it/s]

Checkpoint saved: 8600

 82%|████████▏ | 8652/10519 [13:45<02:50, 10.95it/s]

Checkpoint saved: 8650

 83%|████████▎ | 8700/10519 [13:49<02:39, 11.39it/s]

Checkpoint saved: 8700

 83%|████████▎ | 8751/10519 [13:54<03:16,  8.99it/s]

Checkpoint saved: 8750

 84%|████████▎ | 8800/10519 [13:59<02:50, 10.05it/s]

Checkpoint saved: 8800

 84%|████████▍ | 8851/10519 [14:04<02:53,  9.62it/s]

Checkpoint saved: 8850

 85%|████████▍ | 8901/10519 [14:09<03:36,  7.49it/s]

Checkpoint saved: 8900

 85%|████████▌ | 8951/10519 [14:13<02:43,  9.58it/s]

Checkpoint saved: 8950

 86%|████████▌ | 9001/10519 [14:18<02:22, 10.64it/s]

Checkpoint saved: 9000

 86%|████████▌ | 9051/10519 [14:23<03:11,  7.68it/s]

Checkpoint saved: 9050

 87%|████████▋ | 9102/10519 [14:28<02:28,  9.55it/s]

Checkpoint saved: 9100

 87%|████████▋ | 9150/10519 [14:32<02:14, 10.19it/s]

Checkpoint saved: 9150

 87%|████████▋ | 9202/10519 [14:37<02:13,  9.88it/s]

Checkpoint saved: 9200

 88%|████████▊ | 9251/10519 [14:42<01:54, 11.05it/s]

Checkpoint saved: 9250

 88%|████████▊ | 9302/10519 [14:47<02:12,  9.18it/s]

Checkpoint saved: 9300

 89%|████████▉ | 9352/10519 [14:52<02:03,  9.47it/s]

Checkpoint saved: 9350

 89%|████████▉ | 9403/10519 [14:57<01:40, 11.10it/s]

Checkpoint saved: 9400

 90%|████████▉ | 9451/10519 [15:01<01:43, 10.35it/s]

Checkpoint saved: 9450

 90%|█████████ | 9501/10519 [15:06<01:57,  8.64it/s]

Checkpoint saved: 9500

 91%|█████████ | 9552/10519 [15:11<01:33, 10.39it/s]

Checkpoint saved: 9550

 91%|█████████▏| 9602/10519 [15:15<01:26, 10.65it/s]

Checkpoint saved: 9600

 92%|█████████▏| 9650/10519 [15:20<01:29,  9.72it/s]

Checkpoint saved: 9650

 92%|█████████▏| 9702/10519 [15:24<01:17, 10.59it/s]

Checkpoint saved: 9700

 93%|█████████▎| 9752/10519 [15:29<01:30,  8.45it/s]

Checkpoint saved: 9750

 93%|█████████▎| 9802/10519 [15:34<01:09, 10.36it/s]

Checkpoint saved: 9800

 94%|█████████▎| 9850/10519 [15:38<01:05, 10.17it/s]

Checkpoint saved: 9850

 94%|█████████▍| 9902/10519 [15:43<01:11,  8.57it/s]

Checkpoint saved: 9900

 95%|█████████▍| 9952/10519 [15:48<01:03,  8.97it/s]

Checkpoint saved: 9950

 95%|█████████▌| 10001/10519 [15:52<00:52,  9.85it/s]

Checkpoint saved: 10000

 96%|█████████▌| 10051/10519 [15:57<00:46, 10.08it/s]

Checkpoint saved: 10050

 96%|█████████▌| 10100/10519 [16:01<00:46,  9.01it/s]

Checkpoint saved: 10100

 97%|█████████▋| 10152/10519 [16:06<00:32, 11.19it/s]

Checkpoint saved: 10150

 97%|█████████▋| 10201/10519 [16:11<00:41,  7.72it/s]

Checkpoint saved: 10200

 97%|█████████▋| 10252/10519 [16:16<00:26,  9.91it/s]

Checkpoint saved: 10250

 98%|█████████▊| 10302/10519 [16:20<00:20, 10.53it/s]

Checkpoint saved: 10300

 98%|█████████▊| 10352/10519 [16:24<00:17,  9.78it/s]

Checkpoint saved: 10350

 99%|█████████▉| 10402/10519 [16:29<00:11, 10.00it/s]

Checkpoint saved: 10400

 99%|█████████▉| 10452/10519 [16:34<00:07,  9.23it/s]

Checkpoint saved: 10450

100%|█████████▉| 10501/10519 [16:39<00:02,  8.34it/s]

Checkpoint saved: 10500

100%|██████████| 10519/10519 [16:40<00:00, 10.51it/s]

Final checkpoint saved

In [ ]:
import re
import pandas as pd
import hazm
from jiwer import wer, cer
import torch

CHECKPOINT_PATH = "/content/drive/MyDrive/asr_project/w2v_checkpoint.csv"

df = pd.read_csv(CHECKPOINT_PATH)

print("Loaded:", len(df))

In [ ]:
normalizer = hazm.Normalizer()

PERSIAN_CHAR_MAP = {
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ؤ": "و",
    "ئ": "ی",
    "ة": "ه",
}

def normalize_persian(text):

    text = str(text)
    text = normalizer.normalize(text)

    for k, v in PERSIAN_CHAR_MAP.items():
        text = text.replace(k, v)

    text = re.sub(r"\d+", " <NUM> ", text)
    text = re.sub(r"[^\w\s<>]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
df["ref_norm"] = df["reference_raw"].apply(normalize_persian)
df["hyp_norm"] = df["prediction_raw"].apply(normalize_persian)

refs = df["ref_norm"].tolist()
hyps = df["hyp_norm"].tolist()

wer_score = wer(refs, hyps)
cer_score = cer(refs, hyps)

In [ ]:
total_audio = df["audio_duration"].sum()
total_inference = df["inference_time"].sum()

rtf = total_inference / total_audio
avg_latency = df["inference_time"].mean()

In [ ]:
if torch.cuda.is_available():
    peak_memory = torch.cuda.max_memory_allocated() / 1024**3
else:
    peak_memory = 0

In [ ]:
print("\n=========== WAV2VEC2 RESULTS ===========\n")
print("Samples:", len(df))
print("WER:", round(wer_score, 4))
print("CER:", round(cer_score, 4))
print("RTF:", round(rtf, 4))
print("Avg latency:", round(avg_latency, 4))
print("Peak GPU memory:", round(peak_memory, 2))
print("\n=======================================\n")

In [ ]:
summary = pd.DataFrame([{
    "model": "wav2vec2-large-xlsr-persian-v3",
    "samples": len(df),
    "wer": wer_score,
    "cer": cer_score,
    "rtf": rtf,
    "avg_latency_sec": avg_latency,
    "gpu_memory_gb": peak_memory,
    "total_inference_time_sec": total_inference
}])

summary.to_csv(
    "/content/drive/MyDrive/asr_project/w2v_summary.csv",
    index=False
)

print("Saved summary")

In [ ]:
pip install jiwer

Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.4.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 38.9 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.5

In [ ]:
import pandas as pd
import re
import unicodedata
from jiwer import wer, cer

CHECKPOINT_PATH = "/content/drive/MyDrive/asr_project/w2v_persian_checkpoint.csv"

df = pd.read_csv(CHECKPOINT_PATH)

df = df.dropna(subset=["reference_raw", "prediction_raw"]).reset_index(drop=True)

In [ ]:
df.head()

,audio_path,reference_raw,prediction_raw,audio_duration,inference_time
0,/content/drive/MyDrive/asr_project/asr_data/fa...,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,2.753750,0.079157
1,/content/drive/MyDrive/asr_project/asr_data/fa...,دعا خوان,دعا خوان,3.103500,0.075789
2,/content/drive/MyDrive/asr_project/asr_data/fa...,اعتماد کرد,به اعتماد کرد,4.651043,0.055044
3,/content/drive/MyDrive/asr_project/asr_data/fa...,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,3.701625,0.049486
4,/content/drive/MyDrive/asr_project/asr_data/fa...,آه، نه اصلاُ!,آه نه اصلا,2.429625,0.037833

In [ ]:
df_sub = df[['prediction_raw', 'reference_raw']]
df_sub.head()

           prediction_raw           reference_raw
0  از مهمونداری کنار بکشم  از مهمونداری کنار بکشم
1                دعا خوان                دعا خوان
2           به اعتماد کرد              اعتماد کرد
3      خب تو چیکار می کنی   خب ، تو چیكار می كنی؟
4              آه نه اصلا           آه، نه اصلاُ!

In [ ]:
pip install hazm

Collecting hazm
  Downloading hazm-0.12.1-py3-none-any.whl.metadata (9.3 kB)
Collecting flashtext<3.0,>=2.7 (from hazm)
  Downloading flashtext-2.7.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: huggingface-hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from hazm) (1.19.0)
Requirement already satisfied: nltk<4.0.0,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from hazm) (3.9.1)
Collecting python-crfsuite<0.10.0,>=0.9.12 (from hazm)
  Downloading python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.67.3 in /usr/local/lib/python3.12/dist-packages (from hazm) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.25.0->hazm) (4.15.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.9.0->hazm) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.9.0->hazm) (2025.11.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.25.0->hazm) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.25.0->hazm) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.25.0->hazm) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.25.0->hazm) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.25.0->hazm) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.25.0->hazm) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.25.0->hazm) (0.1.2)
Downloading hazm-0.12.1-py3-none-any.whl (887 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 22.9 MB/s eta 0:00:00
Downloading python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 41.9 MB/s eta 0:00:00
Building wheels for collected packages: flashtext
  Building wheel for flashtext (setup.py) ... done
  Created wheel for flashtext: filename=flashtext-2.7-py2.py3-none-any.whl size=9300 sha256=e34be35af0d1ae1cec93ca8ec4c6827e6e7feab5e4c5a1071e2ba8c265b05e3f
  Stored in directory: /root/.cache/pip/wheels/8c/24/da/4d994d7a27cfc73a4e513a669fbeec4a71f871fe245a81977f
Successfully built flashtext
Installing collected packages: flashtext, python-crfsuite, hazm
Successfully installed flashtext-2.7 hazm-0.12.1 python-crfsuite-0.9.12

In [ ]:
import re
import unicodedata
import string
import hazm

_normalizer = hazm.Normalizer()

SKIP = set(["ā", "š", "="])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])

# remove ASCII digits + Persian/Arabic digits (consistent with HF eval)
DIGITS = set("0123456789۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩")


def w2v_persian_normalize(text: str) -> str:
    if text is None:
        return ""

    text = str(text)

    # 1. Unicode normalization (critical)
    text = unicodedata.normalize("NFKC", text)

    # 2. lower + strip
    text = text.lower().strip()

    # 3. Hazm normalization (Persian-specific standardization)
    text = _normalizer.normalize(text)

    # 4. remove hashtags (same as HF script)
    text = " ".join(w for w in text.split() if not w.startswith("#"))

    # 5. character replacements (Arabic → Persian canonical form)
    for k, v in REPLACEMENTS.items():
        text = text.replace(k, v)

    # 6. remove unwanted punctuation
    for tok in DISCARD:
        text = text.replace(tok, " ")

    # 7. remove SKIP characters (HF ignores these explicitly)
    for ch in SKIP:
        text = text.replace(ch, " ")

    # 8. remove digits (HF wav2vec2 eval does this implicitly via ignore list)
    text = "".join(ch for ch in text if ch not in DIGITS)

    # 9. remove Arabic letter variation "hamza"
    text = text.replace("ء", "")

    # 10. collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
df["ref_norm"] = df["reference_raw"].apply(w2v_persian_normalize)
df["hyp_norm"] = df["prediction_raw"].apply(w2v_persian_normalize)

In [ ]:
df.head()

,audio_path,reference_raw,prediction_raw,audio_duration,inference_time,ref_norm,hyp_norm
0,/content/drive/MyDrive/asr_project/asr_data/fa...,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,2.753750,0.079157,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم
1,/content/drive/MyDrive/asr_project/asr_data/fa...,دعا خوان,دعا خوان,3.103500,0.075789,دعا خوان,دعا خوان
2,/content/drive/MyDrive/asr_project/asr_data/fa...,اعتماد کرد,به اعتماد کرد,4.651043,0.055044,اعتماد کرد,به اعتماد کرد
3,/content/drive/MyDrive/asr_project/asr_data/fa...,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,3.701625,0.049486,خب تو چیکار می‌کنی,خب تو چیکار می‌کنی
4,/content/drive/MyDrive/asr_project/asr_data/fa...,آه، نه اصلاُ!,آه نه اصلا,2.429625,0.037833,آه نه اصلا,آه نه اصلا

### results

In [ ]:
wer_score = wer(df["ref_norm"].tolist(), df["hyp_norm"].tolist())
cer_score = cer(df["ref_norm"].tolist(), df["hyp_norm"].tolist())

print("NeMo-replicated WER:", wer_score)
print("NeMo-replicated CER:", cer_score)
print("Samples:", len(df))

NeMo-replicated WER: 0.26152512998266897
NeMo-replicated CER: 0.13370709666174596
Samples: 10517

In [ ]:
pip install kaldialign

Collecting kaldialign
  Downloading kaldialign-0.12.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Downloading kaldialign-0.12.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (110 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 3.6 MB/s eta 0:00:00
Installing collected packages: kaldialign
Successfully installed kaldialign-0.12.0

In [ ]:
import pandas as pd
import kaldialign


def _alignment_error_rate(ref_tokens, hyp_tokens):
    """
    Compute error rate using Kaldi/Icefall alignment.

    Returns:
        error_rate, substitutions, deletions, insertions, reference_length
    """
    ali = kaldialign.align(ref_tokens, hyp_tokens, "*")

    subs = dels = ins = 0

    for r, h in ali:
        if r == "*":
            ins += 1
        elif h == "*":
            dels += 1
        elif r != h:
            subs += 1

    n_ref = len(ref_tokens)
    err = (subs + dels + ins) / max(1, n_ref)

    return err, subs, dels, ins, n_ref


def add_wer_cer_columns(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Adds per-sample WER and CER columns to a dataframe.

    Returns
    -------
    DataFrame
        Copy of dataframe with:
            wer
            cer
            wer_sub
            wer_del
            wer_ins
            cer_sub
            cer_del
            cer_ins
    """

    df = df.copy()

    wers = []
    cers = []

    wer_subs = []
    wer_dels = []
    wer_inss = []

    cer_subs = []
    cer_dels = []
    cer_inss = []

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        # ---------- WER ----------
        wer, s, d, i, _ = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        wers.append(wer)
        wer_subs.append(s)
        wer_dels.append(d)
        wer_inss.append(i)

        # ---------- CER ----------
        cer, s, d, i, _ = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        cers.append(cer)
        cer_subs.append(s)
        cer_dels.append(d)
        cer_inss.append(i)

    df["wer"] = wers
    df["cer"] = cers

    df["wer_sub"] = wer_subs
    df["wer_del"] = wer_dels
    df["wer_ins"] = wer_inss

    df["cer_sub"] = cer_subs
    df["cer_del"] = cer_dels
    df["cer_ins"] = cer_inss

    return df


def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
# Add per-utterance metrics
df = add_wer_cer_columns(df)

# Inspect individual utterances
df[["hyp_norm", "ref_norm", "wer", "cer"]].head()

                 hyp_norm                ref_norm  wer       cer
0  از مهمونداری کنار بکشم  از مهمونداری کنار بکشم  0.0  0.000000
1                دعا خوان                دعا خوان  0.0  0.000000
2           به اعتماد کرد              اعتماد کرد  0.5  0.222222
3      خب تو چیکار می‌کنی      خب تو چیکار می‌کنی  0.0  0.000000
4              آه نه اصلا              آه نه اصلا  0.0  0.000000

In [ ]:
df.head()

,audio_path,reference_raw,prediction_raw,audio_duration,inference_time,ref_norm,hyp_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
0,/content/drive/MyDrive/asr_project/asr_data/fa...,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,2.753750,0.079157,از مهمونداری کنار بکشم,از مهمونداری کنار بکشم,0.0,0.000000,0,0,0,0,0,0
1,/content/drive/MyDrive/asr_project/asr_data/fa...,دعا خوان,دعا خوان,3.103500,0.075789,دعا خوان,دعا خوان,0.0,0.000000,0,0,0,0,0,0
2,/content/drive/MyDrive/asr_project/asr_data/fa...,اعتماد کرد,به اعتماد کرد,4.651043,0.055044,اعتماد کرد,به اعتماد کرد,0.5,0.222222,0,0,1,0,0,2
3,/content/drive/MyDrive/asr_project/asr_data/fa...,خب ، تو چیكار می كنی؟,خب تو چیکار می کنی,3.701625,0.049486,خب تو چیکار می‌کنی,خب تو چیکار می‌کنی,0.0,0.000000,0,0,0,0,0,0
4,/content/drive/MyDrive/asr_project/asr_data/fa...,آه، نه اصلاُ!,آه نه اصلا,2.429625,0.037833,آه نه اصلا,آه نه اصلا,0.0,0.000000,0,0,0,0,0,0

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
results = compute_dataset_wer_cer(df)

print(f"WER: {results['WER']:.4f}")
print(f"CER: {results['CER']:.4f}")
print(results)

WER: 0.2615
CER: 0.1205
{'WER': 0.26152512998266897, 'CER': 0.12051892298513657, 'word_sub': 7852, 'word_del': 11808, 'word_ins': 1466, 'char_sub': 4495, 'char_del': 28584, 'char_ins': 4090, 'total_words': 80780, 'total_chars': 308408}

In [ ]:
df_sub_1 = df[df['cer'] > df['wer']]
df_sub_1

,audio_path,reference_raw,prediction_raw,audio_duration,inference_time,ref_norm,hyp_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
21,/content/drive/MyDrive/asr_project/asr_data/fa...,هیچ گل مینا دارید؟,گوشی سمسنگ م هانزم تلویزیون علدی,10.517625,0.130065,هیچ گل مینا دارید,گوشی سمسنگ م هانزم تلویزیون علدی,1.500000,1.571429,4,0,2,9,0,13
108,/content/drive/MyDrive/asr_project/asr_data/fa...,(خنده) فقط، رفتن تو بزرگراه و گشت زدن,ها فقط رفتن تو بزرگراه و گشت زدن,8.789625,0.105831,خنده فقط رفتن تو بزرگراه و گشت زدن,ها فقط رفتن تو بزرگراه و گشت زدن,0.125000,0.148148,1,0,0,0,3,1
169,/content/drive/MyDrive/asr_project/asr_data/fa...,زبان مادری من فارسی است,زبان نیدامی من فارسی است,4.133625,0.056593,زبان مادری من فارسی است,زبان نیدامی من فارسی است,0.200000,0.210526,1,0,0,3,0,1
403,/content/drive/MyDrive/asr_project/asr_data/fa...,ال:روز زن چی؟,ال دو نقطه روز زن چی,7.949625,0.107258,ال روز زن چی,ال دو نقطه روز زن چی,0.500000,0.666667,0,0,2,0,0,6
747,/content/drive/MyDrive/asr_project/asr_data/fa...,تا بفهمیم چه كلاه بزرگى این جمهورى اسلامى سر م...,تا بفهمیم چه کلاه بزرگ بزرگی این جمهوری اسلامی...,9.701625,0.128513,تا بفهمیم چه کلاه بزرگی این جمهوری اسلامی سر م...,تا بفهمیم چه کلاه بزرگ بزرگی این جمهوری اسلامی...,0.062500,0.064516,0,0,1,0,0,4
1126,/content/drive/MyDrive/asr_project/asr_data/fa...,از یخچال جویی بر داریم,از یخچال جویی بر می بریم,3.701625,0.054067,از یخچال جویی بر داریم,از یخچال جویی بر می‌بریم,0.200000,0.222222,1,0,0,2,0,2
1302,/content/drive/MyDrive/asr_project/asr_data/fa...,تو زندگی ما فقط آب و هواس که تغییر میکنه,تو زندگی ما فقط آب و هواس که تره میکنه,5.741625,0.076226,تو زندگی ما فقط آب و هواس که تغییر میکنه,تو زندگی ما فقط آب و هواس که تره میکنه,0.100000,0.129032,1,0,0,0,3,1
1389,/content/drive/MyDrive/asr_project/asr_data/fa...,من مسیحی هستم.,من بثیر هستم,2.861625,0.049241,من مسیحی هستم,من بثیر هستم,0.333333,0.363636,1,0,0,3,1,0
1969,/content/drive/MyDrive/asr_project/asr_data/fa...,چندباری که زنگ درمون رو زده بود و اجازه دادیم ...,چندباری که زنگ درمون رو زده بود و اجازه دادیم ...,7.709625,0.107446,چندباری که زنگ درمون رو زده بود و اجازه دادیم ...,چندباری که زنگ درمون رو زده بود و اجازه دادیم ...,0.062500,0.071429,0,0,1,0,0,4
2106,/content/drive/MyDrive/asr_project/asr_data/fa...,حکم قطعی محکوم به او ابلاغ شد,خوب ان قطعی محکوم به او ابراق شد,4.327500,0.066565,حکم قطعی محکوم به او ابلاغ شد,خوب‌ان قطعی محکوم به او ابراق شد,0.285714,0.347826,2,0,0,5,0,3
2813,/content/drive/MyDrive/asr_project/asr_data/fa...,چرا هستم؟ چرا موندم؟ چجوری طاقت می ارم؟,چرا هستم چرا موندم چجوری طاقت نه,3.701625,0.055083,چرا هستم چرا موندم چجوری طاقت می‌ارم,چرا هستم چرا موندم چجوری طاقت نه,0.142857,0.200000,1,0,0,2,4,0
3002,/content/drive/MyDrive/asr_project/asr_data/fa...,نزدیک ترین غرفه کتاب کجاست؟,نزدیک‌ترین بارز‌های کتاب کجاست,4.541625,0.068087,نزدیک‌ترین غرفه کتاب کجاست,نزدیک‌ترین بارز‌های کتاب کجاست,0.250000,0.260870,1,0,0,2,0,4
3775,/content/drive/MyDrive/asr_project/asr_data/fa...,از حضور او اطلاع نداشتم,از رمری او اطلاع نداشتم,3.823500,0.059958,از حضور او اطلاع نداشتم,از رمری او اطلاع نداشتم,0.200000,0.210526,1,0,0,2,1,1
4077,/content/drive/MyDrive/asr_project/asr_data/fa...,از خودم در نمیآورم,از خودم,5.669625,0.083991,از خودم در نمی‌آورم,از خودم,0.500000,0.625000,0,2,0,0,10,0
4466,/content/drive/MyDrive/asr_project/asr_data/fa...,برنامه داری قرار نمیدی,داری قرار نمیدی,4.709625,0.071888,برنامه داری قرار نمیدی,داری قرار نمیدی,0.250000,0.315789,0,1,0,0,6,0
4586,/content/drive/MyDrive/asr_project/asr_data/fa...,خیلی کارا کردم تا خشمم رو تسکین بدم,خیلی کارا کردم تا خشمم رو تسکین میدادم,3.797625,0.051294,خیلی کارا کردم تا خشمم رو تسکین بدم,خیلی کارا کردم تا خشمم رو تسکین می‌دادم,0.125000,0.178571,1,0,0,1,0,4
5003,/content/drive/MyDrive/asr_project/asr_data/fa...,جلال الدین محمد بلخی معروف به مولانا مولوی و ر...,زلالتین محمد بلخی معروف به مولانا مولوی و رومی...,7.949625,0.128258,جلال‌الدین محمد بلخی معروف به مولانا مولوی و ر...,زلالتین محمد بلخی معروف به مولانا مولوی و رومی...,0.100000,0.113636,1,0,0,2,3,0
5194,/content/drive/MyDrive/asr_project/asr_data/fa...,عسل دوست داری؟,ازطر دوست داری,3.629625,0.057822,عسل دوست داری,ازطر دوست داری,0.333333,0.363636,1,0,0,3,0,1
5508,/content/drive/MyDrive/asr_project/asr_data/fa...,همه ریخته بودن بیرون و بزن و برقص میکردن,همه ریخته بودن بیرون بیرون و بزن و برقص میکردن,5.909625,0.089657,همه ریخته بودن بیرون و بزن و برقص میکردن,همه ریخته بودن بیرون بیرون و بزن و برقص میکردن,0.111111,0.156250,0,0,1,0,0,5
7794,/content/drive/MyDrive/asr_project/asr_data/fa...,وقتی بزرگ شدم می خوام همونجایی که اون داره میر...,وقتی با برایی که اون داره میره برم,5.501625,0.078054,وقتی بزرگ شدم می‌خوام همونجایی که اون داره میر...,وقتی با برایی که اون داره میره برم,0.400000,0.404762,2,2,0,2,15,0
9233,/content/drive/MyDrive/asr_project/asr_data/fa...,چاد,جآندت,6.101625,0.090148,چاد,جآندت,1.000000,1.333333,1,0,0,2,0,2
9588,/content/drive/MyDrive/asr_project/asr_data/fa...,بدون موسیقی رپ و رقص نور,بدون رقص رپ و رقص نور,4.469625,0.073241,بدون موسیقی رپ و رقص نور,بدون رقص رپ و رقص نور,0.166667,0.263158,1,0,0,2,3,0
10011,/content/drive/MyDrive/asr_project/asr_data/fa...,عکس چپ، اولین مصاحبهش بعد خروج از ایران,عکس چپ اولین مساوش بعد خروج از ایران,4.781625,0.067660,عکس چپ اولین مصاحبهش بعد خروج از ایران,عکس چپ اولین مساوش بعد خروج از ایران,0.125000,0.129032,1,0,0,2,2,0

# Whisper

In [ ]:
!pip -q install hazm jiwer

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 43.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 86.8 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
import pandas as pd
import re
import unicodedata
from jiwer import wer, cer

CHECKPOINT_PATH = (
    f"/content/drive/MyDrive/asr_project/"
    f"whisper_large-v3_checkpoint.csv"
)

df = pd.read_csv(CHECKPOINT_PATH)

df = df.dropna(subset=["reference_raw", "prediction_raw"]).reset_index(drop=True)
df.head()

,audio_path,reference_raw,prediction_raw,audio_duration,inference_time
0,/content/drive/MyDrive/asr_project/asr_data/fa...,از مهمونداری کنار بکشم,از مهمانداری کنار بکشم,2.753750,4.007099
1,/content/drive/MyDrive/asr_project/asr_data/fa...,دعا خوان,دعا خان,3.103500,0.619558
2,/content/drive/MyDrive/asr_project/asr_data/fa...,اعتماد کرد,اعتماد کرد,4.651043,0.684038
3,/content/drive/MyDrive/asr_project/asr_data/fa...,خب ، تو چیكار می كنی؟,خوبتو چیکارن کن,3.701625,1.076763
4,/content/drive/MyDrive/asr_project/asr_data/fa...,آه، نه اصلاُ!,نه اصلا,2.429625,0.847911

In [ ]:
df_sub = df[['prediction_raw', 'reference_raw']]
df_sub.head()

            prediction_raw           reference_raw
0   از مهمانداری کنار بکشم  از مهمونداری کنار بکشم
1                  دعا خان                دعا خوان
2               اعتماد کرد              اعتماد کرد
3          خوبتو چیکارن کن   خب ، تو چیكار می كنی؟
4                  نه اصلا           آه، نه اصلاُ!

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:
    if text is None:
        return ""

    text = str(text)

    # Unicode normalization FIRST (important)
    text = unicodedata.normalize("NFKC", text)

    # remove hashtags (NeMo-style filtering)
    text = " ".join(w for w in text.split() if not w.startswith("#"))

    # character replacements
    for k, v in REPLACEMENTS.items():
        text = text.replace(k, v)

    # remove punctuation tokens
    for tok in DISCARD:
        text = text.replace(tok, " ")

    # remove Arabic letter variations like hamza
    text = text.replace("ء", "")

    # collapse whitespace
    text = " ".join(text.split())

    return text

In [ ]:
df_sub["hyp_norm"] = df_sub["prediction_raw"].apply(nemo_paper_normalize)
df_sub["ref_norm"] = df_sub["reference_raw"].apply(nemo_paper_normalize)

/tmp/ipykernel_1188/1633250410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["hyp_norm"] = df_sub["prediction_raw"].apply(nemo_paper_normalize)
/tmp/ipykernel_1188/1633250410.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["ref_norm"] = df_sub["reference_raw"].apply(nemo_paper_normalize)

In [ ]:
df_sub.loc[df_sub["hyp_norm"] == "", "hyp_norm"] = " "
df_sub.loc[df_sub["ref_norm"] == "", "ref_norm"] = " "

In [ ]:
wer_score = wer(df_sub["ref_norm"].tolist(), df_sub["hyp_norm"].tolist())
cer_score = cer(df_sub["ref_norm"].tolist(), df_sub["hyp_norm"].tolist())

print("NeMo-replicated WER:", wer_score)
print("NeMo-replicated CER:", cer_score)
print("Samples:", len(df_sub))

NeMo-replicated WER: 0.39246016426831376
NeMo-replicated CER: 0.2357303000747337
Samples: 10517

In [ ]:
pip install kaldialign

Requirement already satisfied: kaldialign in /usr/local/lib/python3.12/dist-packages (0.12.0)

In [ ]:
import pandas as pd
import kaldialign


def _alignment_error_rate(ref_tokens, hyp_tokens):
    """
    Compute error rate using Kaldi/Icefall alignment.

    Returns:
        error_rate, substitutions, deletions, insertions, reference_length
    """
    ali = kaldialign.align(ref_tokens, hyp_tokens, "*")

    subs = dels = ins = 0

    for r, h in ali:
        if r == "*":
            ins += 1
        elif h == "*":
            dels += 1
        elif r != h:
            subs += 1

    n_ref = len(ref_tokens)
    err = (subs + dels + ins) / max(1, n_ref)

    return err, subs, dels, ins, n_ref


def add_wer_cer_columns(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Adds per-sample WER and CER columns to a dataframe.

    Returns
    -------
    DataFrame
        Copy of dataframe with:
            wer
            cer
            wer_sub
            wer_del
            wer_ins
            cer_sub
            cer_del
            cer_ins
    """

    df = df.copy()

    wers = []
    cers = []

    wer_subs = []
    wer_dels = []
    wer_inss = []

    cer_subs = []
    cer_dels = []
    cer_inss = []

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        # ---------- WER ----------
        wer, s, d, i, _ = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        wers.append(wer)
        wer_subs.append(s)
        wer_dels.append(d)
        wer_inss.append(i)

        # ---------- CER ----------
        cer, s, d, i, _ = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        cers.append(cer)
        cer_subs.append(s)
        cer_dels.append(d)
        cer_inss.append(i)

    df["wer"] = wers
    df["cer"] = cers

    df["wer_sub"] = wer_subs
    df["wer_del"] = wer_dels
    df["wer_ins"] = wer_inss

    df["cer_sub"] = cer_subs
    df["cer_del"] = cer_dels
    df["cer_ins"] = cer_inss

    return df


def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
# Add per-utterance metrics
df_sub = add_wer_cer_columns(df_sub)

# Inspect individual utterances
df_sub[["hyp_norm", "ref_norm", "wer", "cer"]].head()

                 hyp_norm                ref_norm       wer       cer
0  از مهمانداری کنار بکشم  از مهمونداری کنار بکشم  0.250000  0.052632
1                 دعا خان                دعا خوان  0.500000  0.142857
2              اعتماد کرد              اعتماد کرد  0.000000  0.000000
3         خوبتو چیکارن کن      خب تو چیکار می کنی  1.000000  0.285714
4                 نه اصلا              آه نه اصلا  0.333333  0.250000

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):
    """
    Computes overall dataset WER/CER (Icefall/Kaldi style).

    Returns
    -------
    dict
    """

    total_word_sub = total_word_del = total_word_ins = 0
    total_words = 0

    total_char_sub = total_char_del = total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(df[ref_col], df[hyp_col]):

        ref = "" if pd.isna(ref) else str(ref)
        hyp = "" if pd.isna(hyp) else str(hyp)

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(ref.replace(" ", "")),
            list(hyp.replace(" ", ""))
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub + total_word_del + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub + total_char_del + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

compute_dataset_wer_cer(df_sub)

{'WER': 0.39246016426831376,
 'CER': 0.24328221221272767,
 'word_sub': 18522,
 'word_del': 5552,
 'word_ins': 5408,
 'char_sub': 12959,
 'char_del': 58545,
 'char_ins': 8811,
 'total_words': 75121,
 'total_chars': 330131}

### results

In [ ]:
results = compute_dataset_wer_cer(df_sub)

print(f"WER: {results['WER']:.4f}")
print(f"CER: {results['CER']:.4f}")
print(results)

WER: 0.3677
CER: 0.1064
{'WER': 0.36772021227951057, 'CER': 0.10642468992705639, 'word_sub': 18521, 'word_del': 2609, 'word_ins': 5408, 'char_sub': 12959, 'char_del': 7979, 'char_ins': 8811, 'total_words': 72169, 'total_chars': 279531}

In [ ]:
df_sub[df_sub["ref_norm"].str.match(r"^(?=.*\d)(?=.*[^\d]).+", na=False)]

,prediction_raw,reference_raw,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
1700,هی این خانم ایده جالبی داره اگذار گوش کنیم,هی، این خانم ایده جالبی دارد بگذار گوش کنیم\t\...,هی این خانم ایده جالبی داره اگذار گوش کنیم,هی این خانم ایده جالبی دارد بگذار گوش کنیم 2 0...,0.99729,0.999328,1,2943,0,0,50566,0

In [ ]:
df_sub_1 = df_sub[df_sub['cer'] > df_sub['wer']]
df_sub_1

,prediction_raw,reference_raw,hyp_norm,ref_norm,wer,cer,wer_sub,wer_del,wer_ins,cer_sub,cer_del,cer_ins
205,جد و جاحت,جد و جهد,جد و جاحت,جد و جهد,0.333333,0.500000,1,0,0,2,0,1
341,اوه این بازی مهمی نیست,اوه این قضیه مهمی نیست,اوه این بازی مهمی نیست,اوه این قضیه مهمی نیست,0.200000,0.222222,1,0,0,2,1,1
403,حل دو نقطه روز زن چی؟,ال:روز زن چی؟,حل دو نقطه روز زن چی,ال روز زن چی,0.750000,0.777778,1,0,2,1,0,6
648,قدیمی ترین بنا در شمال توکیو 50 هزار سال قدمت...,قدیمی ترین بنا در شمال توکیو پنجاه هزار سال قد...,قدیمی ترین بنا در شمال توکیو 50 هزار سال قدمت ...,قدیمی ترین بنا در شمال توکیو پنجاه هزار سال قد...,0.090909,0.116279,1,0,0,2,3,0
714,278 تا,دویست و هفتاد و هشت تا,278 تا,دویست و هفتاد و هشت تا,0.833333,0.882353,1,4,0,3,12,0
951,مردم در اینجا با اینجا با اینجا با اینجا با ا...,و این آب فایده ای ندارد!,مردم در اینجا با اینجا با اینجا با اینجا با ای...,و این آب فایده ای ندارد,12.500000,13.944444,6,0,69,8,0,243
1109,این قبیل زارد,این قبیل اظهارات,این قبیل زارد,این قبیل اظهارات,0.333333,0.357143,1,0,0,2,3,0
1244,بخش ۱۲۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰...,لطفاً یک گزارش سرقت پر کنید.,بخش ۱۲۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰۰...,لطفا یک گزارش سرقت پر کنید,1.000000,5.380952,2,4,0,21,0,92
1700,هی این خانم ایده جالبی داره اگذار گوش کنیم,هی، این خانم ایده جالبی دارد بگذار گوش کنیم\t\...,هی این خانم ایده جالبی داره اگذار گوش کنیم,هی این خانم ایده جالبی دارد بگذار گوش کنیم 2 0...,0.997290,0.999328,1,2943,0,0,50566,0
1763,ههههههههههههههههههههههههههههههههههههههههههههه...,(خنده) میخواست یک پولی دربیاورد,هههههههههههههههههههههههههههههههههههههههههههههه...,خنده میخواست یک پولی دربیاورد,1.000000,8.880000,1,4,0,24,0,198
2067,شما باید بردارید,صدا و سیما,شما باید بردارید,صدا و سیما,1.000000,1.375000,3,0,0,5,0,6
2195,دو آقاید ممکن است بر یک چیز اتفاق کنند,دو عاقل ممکن است بر یک چیز اتفاق کنند,دو آقاید ممکن است بر یک چیز اتفاق کنند,دو عاقل ممکن است بر یک چیز اتفاق کنند,0.111111,0.137931,1,0,0,3,0,1
2320,عشق آمد و خیمه زد به سهرایی دلم,عشق آمد و خیمه زد به صحرای دلم,عشق آمد و خیمه زد به سهرایی دلم,عشق آمد و خیمه زد به صحرای دلم,0.125000,0.130435,1,0,0,2,0,1
2617,مردم در اینجا با اینجا با اینجا با اینجا با ا...,من اشکال نمی بینم که هرروز با قطار سفر کنم.,مردم در اینجا با اینجا با اینجا با اینجا با ای...,من اشکال نمی بینم که هرروز با قطار سفر کنم,7.400000,7.515152,9,0,65,20,0,228
3654,شافید شافید شافید شافید شافید شافید شافید شاف...,شاه سویچ، سویچ اصلی,شافید شافید شافید شافید شافید شافید شافید شافی...,شاه سویچ سویچ اصلی,14.000000,18.200000,4,0,52,9,0,264
3749,بنابراین، بنابراین، بنابراین، بنابراین، بنابر...,بنویس والا هر چه ببینی از چشم خودت دیدهای!,بنابراین بنابراین بنابراین بنابراین بنابراین ب...,بنویس والا هر چه ببینی از چشم خودت دیدهای,4.222222,8.545455,9,0,29,18,0,264
4077,از خودم,از خودم در نمیآورم,از خودم,از خودم در نمیآورم,0.500000,0.600000,0,2,0,0,9,0
4094,تو نگران خودت باش نه شهاره مردم,تو نگران خودت باش نه شوهرای مردم!,تو نگران خودت باش نه شهاره مردم,تو نگران خودت باش نه شوهرای مردم,0.142857,0.153846,1,0,0,1,2,1
4122,این بعد از دو,این بعد از ظهر.,این بعد از دو,این بعد از ظهر,0.250000,0.272727,1,0,0,2,1,0
4467,داری قرار نمیدی,برنامه داری قرار نمیدی,داری قرار نمیدی,برنامه داری قرار نمیدی,0.250000,0.315789,0,1,0,0,6,0
4818,بله، فرهن,بله، واقعا.,بله فرهن,بله واقعا,0.500000,0.625000,1,0,0,4,1,0
5110,در اینجا، در اینجا، در اینجا، در اینجا، در ای...,برداشت و مثل یه زن شد,در اینجا در اینجا در اینجا در اینجا در اینجا د...,برداشت و مثل یه زن شد,10.666667,13.625000,6,0,58,10,0,208
5414,با سرعت 20 مایل در ساعت,با سرعت بیست مایل در ساعت,با سرعت 20 مایل در ساعت,با سرعت بیست مایل در ساعت,0.166667,0.200000,1,0,0,2,2,0
5540,بچه هاش بهش احتیاج زده,بچه هاش بهش احتیاج دارن,بچه هاش بهش احتیاج زده,بچه هاش بهش احتیاج دارن,0.200000,0.210526,1,0,0,1,2,1
5588,چی؟ ما همونطوریم؟,چی؟ ما هنوزم همونطوریم,چی ما همونطوریم,چی ما هنوزم همونطوریم,0.250000,0.277778,0,1,0,0,5,0
5947,با خدای من ری ری گرین,اوه خدای من ری ری گرین,با خدای من ری ری گرین,اوه خدای من ری ری گرین,0.166667,0.176471,1,0,0,0,2,1
6035,من شوید خواست که افراد یکی از ما,مشخصه که فقط یکی از ما,من شوید خواست که افراد یکی از ما,مشخصه که فقط یکی از ما,0.666667,0.705882,2,0,2,4,0,8
6492,چیه مونیکا می درزده؟,!چیه؟ مونیکا ، می ترسم,چیه مونیکا می درزده,چیه مونیکا می ترسم,0.250000,0.266667,1,0,0,3,0,1
6732,به هیچ برد دلیل این نیست که ما,به هیچ وجه دلیل این نیست که ما,به هیچ برد دلیل این نیست که ما,به هیچ وجه دلیل این نیست که ما,0.125000,0.130435,1,0,0,3,0,0
7064,مردم هایی که باید بردارید.,حال شما خوب است؟,مردم هایی که باید بردارید,حال شما خوب است,1.250000,1.416667,4,0,1,8,0,9
7200,نکنم از این چیزا خوشش بیاد,گمون نکنم از این چیزا خوشش بیاد,نکنم از این چیزا خوشش بیاد,گمون نکنم از این چیزا خوشش بیاد,0.142857,0.160000,0,1,0,0,4,0
7494,تو هم خیلی تغییر بازید,تو هم خیلی تغییر پذیری,تو هم خیلی تغییر بازید,تو هم خیلی تغییر پذیری,0.200000,0.277778,1,0,0,3,1,1
8033,باید باید باید باید باید باید باید باید باید ...,لطفا این را به اداره ما فکس کنید.,باید باید باید باید باید باید باید باید باید ب...,لطفا این را به اداره ما فکس کنید,7.000000,8.480000,8,0,48,14,0,198
8775,مرسی آزنیست مرسی آزنیست,این چه ارزی است؟,مرسی آزنیست مرسی آزنیست,این چه ارزی است,1.000000,1.166667,4,0,0,6,0,8
8779,امتحان است,او کر است.,امتحان است,او کر است,0.666667,0.714286,1,1,0,3,0,2
9411,اونه شست,بن شست,اونه شست,بن شست,0.500000,0.600000,1,0,0,1,0,2
9588,بدون بخصه باب و بخصه نور,بدون موسیقی رپ و رقص نور,بدون بخصه باب و بخصه نور,بدون موسیقی رپ و رقص نور,0.500000,0.578947,3,0,0,9,1,1
9733,حاجی خیلی حال داد به 20 نفر شماره دادم,حاجی خیلی حال داد به بیست نفر شماره دادم.,حاجی خیلی حال داد به 20 نفر شماره دادم,حاجی خیلی حال داد به بیست نفر شماره دادم,0.111111,0.125000,1,0,0,2,2,0
9836,اشخاهی گذشته را به حال وصل می کند.,عذرخواهی گذشته را به حال وصل می کند,اشخاهی گذشته را به حال وصل می کند,عذرخواهی گذشته را به حال وصل می کند,0.125000,0.142857,1,0,0,2,2,0
9911,بسیار درست دارید.,اِسپنتا,بسیار درست دارید,ا سپنتا,1.500000,1.833333,2,0,1,3,0,8

In [ ]:
df_sub = df_sub.drop(index=1700)
df_sub.count()

prediction_raw    10516
reference_raw     10516
hyp_norm          10516
ref_norm          10516
wer               10516
cer               10516
wer_sub           10516
wer_del           10516
wer_ins           10516
cer_sub           10516
cer_del           10516
cer_ins           10516
dtype: int64