### Sub-Common Voice evaluation

In [ ]:
!pip install -q transformers datasets evaluate jiwer
!pip install -q torchaudio librosa soundfile
!pip install -q hazm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 67.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 70.2 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/asr_project/asr_data/fa_test_only"

In [ ]:
import pandas as pd
import os

test_df = pd.read_csv(
    os.path.join(DATASET_PATH, "test.tsv"),
    sep="\t"
)

test_df["audio_path"] = test_df["path"].apply(
    lambda x: os.path.join(DATASET_PATH, "clips", x)
)

test_df = test_df[["audio_path", "sentence"]]

print(test_df.shape)

test_df.head()

(10519, 2)

                                          audio_path                sentence
0  /content/drive/MyDrive/asr_project/asr_data/fa...  از مهمونداری کنار بکشم
1  /content/drive/MyDrive/asr_project/asr_data/fa...                دعا خوان
2  /content/drive/MyDrive/asr_project/asr_data/fa...              اعتماد کرد
3  /content/drive/MyDrive/asr_project/asr_data/fa...   خب ، تو چیكار می كنی؟
4  /content/drive/MyDrive/asr_project/asr_data/fa...           آه، نه اصلاُ!

In [ ]:
import hazm
import re
import string

_normalizer = hazm.Normalizer()

chars_to_ignore = [
    ",", "?", ".", "!", "-", ";", ":", '"',
    "%", "'", "؟", "«", "»", "،", "(", ")",
    "؛", "_", "…"
]

chars_to_mapping = {
    'ك': 'ک',
    'ي': 'ی',
    'ى': 'ی',
    'أ': 'ا',
    'ؤ': 'و',
    'ئ': 'ی',
    'ة': 'ه',
    '\u200c': ' ',
    '\u200d': ' ',
}

def multiple_replace(text, mapping):
    pattern = "|".join(map(re.escape, mapping.keys()))
    return re.sub(pattern, lambda m: mapping[m.group()], text)

def normalize_persian(text):

    text = str(text).lower().strip()

    text = _normalizer.normalize(text)

    text = multiple_replace(text, chars_to_mapping)

    chars_to_ignore_regex = f"""[{"".join(chars_to_ignore)}]"""

    text = re.sub(chars_to_ignore_regex, '', text)

    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [ ]:
import torch
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC

MODEL_NAME = "m3hrdadfi/wav2vec2-large-xlsr-persian-v3"

processor = Wav2Vec2Processor.from_pretrained(MODEL_NAME)

model = Wav2Vec2ForCTC.from_pretrained(MODEL_NAME)

device = "cuda" if torch.cuda.is_available() else "cpu"

model = model.to(device)

print("Using device:", device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/307 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

Using device: cuda

In [ ]:
import librosa

sample_path = test_df.iloc[0]["audio_path"]

audio, sr = librosa.load(
    sample_path,
    sr=16000
)

inputs = processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt",
    padding=True
)

input_values = inputs.input_values.to(device)

with torch.no_grad():

    logits = model(input_values).logits

predicted_ids = torch.argmax(logits, dim=-1)

prediction = processor.batch_decode(predicted_ids)[0]

print("Prediction:")
print(prediction)

print("\nGround Truth:")
print(test_df.iloc[0]["sentence"])

Prediction:
از مهمونداری کنار بکشم

Ground Truth:
از مهمونداری کنار بکشم

In [ ]:
benchmark_df = test_df.sample(100, random_state=42)

In [ ]:
from jiwer import wer, cer
import time
from tqdm import tqdm
import librosa

predictions = []
references = []

total_audio_duration = 0

start_time = time.time()

for _, row in tqdm(benchmark_df.iterrows(), total=len(benchmark_df)):

    audio, sr = librosa.load(
        row["audio_path"],
        sr=16000
    )

    audio_duration = len(audio) / sr
    total_audio_duration += audio_duration

    inputs = processor(
        audio,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True
    )

    input_values = inputs.input_values.to(device)

    with torch.no_grad():

        logits = model(input_values).logits

    predicted_ids = torch.argmax(logits, dim=-1)

    pred_text = processor.batch_decode(predicted_ids)[0]

    pred_text = normalize_persian(pred_text)
    true_text = normalize_persian(row["sentence"])

    predictions.append(pred_text)
    references.append(true_text)

total_time = time.time() - start_time

wer_score = wer(references, predictions)
cer_score = cer(references, predictions)

rtf = total_time / total_audio_duration

print(f"WER: {wer_score:.4f}")
print(f"CER: {cer_score:.4f}")
print(f"RTF: {rtf:.4f}")
print(f"Total inference time: {total_time:.2f} sec")

100%|██████████| 100/100 [00:42<00:00,  2.37it/s]

WER: 0.1763
CER: 0.0486
RTF: 0.0866
Total inference time: 42.15 sec

In [ ]:
results = pd.DataFrame({
    "reference": references,
    "prediction": predictions
})

results.to_csv(
    "/content/drive/MyDrive/asr_project/w2v_results.csv",
    index=False
)

In [ ]:
# ============================================================
# Persian ASR Benchmark - wav2vec2 XLSR Persian v3
# PSRB-inspired Benchmark Pipeline
# ============================================================

# ------------------------------------------------------------
# 1. Install Dependencies
# ------------------------------------------------------------

!pip install -q transformers
!pip install -q jiwer evaluate
!pip install -q hazm librosa soundfile torchaudio
!pip install -q pandas tqdm

# ------------------------------------------------------------
# 2. Imports
# ------------------------------------------------------------

import os
import re
import time
import random
import numpy as np
import pandas as pd
import librosa
import soundfile as sf
import torch
import hazm

from tqdm import tqdm

from jiwer import wer, cer

from transformers import (
    Wav2Vec2Processor,
    Wav2Vec2ForCTC
)

# ------------------------------------------------------------
# 3. Reproducibility
# ------------------------------------------------------------

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ------------------------------------------------------------
# 4. Load Benchmark Subset
# ------------------------------------------------------------

benchmark_df = pd.read_csv(
    "/content/drive/MyDrive/asr_project/bench_sub.csv"
)

print("Benchmark samples:", len(benchmark_df))

benchmark_df = benchmark_df.dropna(
    subset=["audio_path", "sentence"]
)

benchmark_df = benchmark_df.reset_index(drop=True)

# ------------------------------------------------------------
# 5. Verify Paths
# ------------------------------------------------------------

missing = benchmark_df[
    ~benchmark_df["audio_path"].apply(os.path.exists)
]

print("Missing files:", len(missing))

# ------------------------------------------------------------
# 6. Persian Text Normalization
# ------------------------------------------------------------

normalizer = hazm.Normalizer()

PERSIAN_CHAR_MAP = {
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ؤ": "و",
    "ئ": "ی",
    "ة": "ه",
}

def normalize_persian(text):

    text = str(text)

    text = normalizer.normalize(text)

    for k, v in PERSIAN_CHAR_MAP.items():
        text = text.replace(k, v)

    # Remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # Persian spacing normalization
    text = text.replace("می ", "می")
    text = text.replace("نمی ", "نمی")

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

# ------------------------------------------------------------
# 7. Load Model
# ------------------------------------------------------------

MODEL_NAME = "m3hrdadfi/wav2vec2-large-xlsr-persian-v3"

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = Wav2Vec2Processor.from_pretrained(
    MODEL_NAME
)

model = Wav2Vec2ForCTC.from_pretrained(
    MODEL_NAME
)

model = model.to(device)

print("Using device:", device)

# ------------------------------------------------------------
# 8. Test on 1 Sample First
# ------------------------------------------------------------

# benchmark_df = benchmark_df.iloc[:1].copy()

# ------------------------------------------------------------
# 9. Benchmarking
# ------------------------------------------------------------

predictions = []
references = []
sample_cers = []
audio_paths = []

total_audio_duration = 0

torch.cuda.empty_cache()

if device == "cuda":
    torch.cuda.reset_peak_memory_stats()

start_time = time.time()

for idx, row in tqdm(
    benchmark_df.iterrows(),
    total=len(benchmark_df)
):

    try:

        audio_path = row["audio_path"]

        # ----------------------------------------------------
        # Audio duration (without decoding)
        # ----------------------------------------------------

        audio_info = sf.info(audio_path)

        audio_duration = (
            audio_info.frames /
            audio_info.samplerate
        )

        total_audio_duration += audio_duration

        # ----------------------------------------------------
        # Load audio
        # ----------------------------------------------------

        audio, sr = librosa.load(
            audio_path,
            sr=16000
        )

        # ----------------------------------------------------
        # Tokenization
        # ----------------------------------------------------

        inputs = processor(
            audio,
            sampling_rate=16000,
            return_tensors="pt",
            padding=True
        )

        input_values = (
            inputs.input_values.to(device)
        )

        # ----------------------------------------------------
        # Inference
        # ----------------------------------------------------

        with torch.no_grad():

            logits = model(
                input_values
            ).logits

        predicted_ids = torch.argmax(
            logits,
            dim=-1
        )

        pred_text = processor.batch_decode(
            predicted_ids
        )[0]

        # ----------------------------------------------------
        # Normalize texts
        # ----------------------------------------------------

        pred_text = normalize_persian(
            pred_text
        )

        true_text = normalize_persian(
            row["sentence"]
        )

        # ----------------------------------------------------
        # Save outputs
        # ----------------------------------------------------

        predictions.append(pred_text)

        references.append(true_text)

        audio_paths.append(audio_path)

        sample_cer = cer(
            true_text,
            pred_text
        )

        sample_cers.append(sample_cer)

        # ----------------------------------------------------
        # Progress checkpoint
        # ----------------------------------------------------

        if len(predictions) % 50 == 0:

            checkpoint_df = pd.DataFrame({

                "audio_path": audio_paths,

                "reference": references,

                "prediction": predictions,

                "sample_cer": sample_cers
            })

            checkpoint_df.to_csv(
                "/content/drive/MyDrive/asr_project/w2v_checkpoint.csv",
                index=False
            )

            print(
                f"Checkpoint saved at "
                f"{len(predictions)} samples"
            )

    except Exception as e:

        print(f"\nFAILED SAMPLE: {audio_path}")

        print(e)

# ------------------------------------------------------------
# 10. Final Metrics
# ------------------------------------------------------------

total_time = time.time() - start_time

wer_score = wer(
    references,
    predictions
)

cer_score = cer(
    references,
    predictions
)

rtf = (
    total_time /
    total_audio_duration
)

avg_latency = (
    total_time /
    len(predictions)
)

# ------------------------------------------------------------
# 11. GPU Memory
# ------------------------------------------------------------

if device == "cuda":

    peak_memory = (
        torch.cuda.max_memory_allocated()
        / 1024**3
    )

else:

    peak_memory = 0

# ------------------------------------------------------------
# 12. Print Results
# ------------------------------------------------------------

print("\n================ BENCHMARK RESULTS ================\n")

print(f"Model: wav2vec2-large-xlsr-persian-v3")

print(f"Samples: {len(predictions)}")

print(f"WER: {wer_score:.4f}")

print(f"CER: {cer_score:.4f}")

print(f"RTF: {rtf:.4f}")

print(f"Average latency: {avg_latency:.4f} sec")

print(f"Total inference time: {total_time:.2f} sec")

print(f"Total audio duration: {total_audio_duration:.2f} sec")

print(f"Peak GPU memory: {peak_memory:.2f} GB")

print("\n===================================================\n")

# ------------------------------------------------------------
# 13. Save Detailed Results
# ------------------------------------------------------------

results_df = pd.DataFrame({

    "audio_path": audio_paths,

    "reference": references,

    "prediction": predictions,

    "sample_cer": sample_cers
})

SAVE_PATH = (
    "/content/drive/MyDrive/asr_project/"
    "wav2vec2_persian_v3_results.csv"
)

results_df.to_csv(
    SAVE_PATH,
    index=False
)

print("Detailed results saved to:")
print(SAVE_PATH)

# ------------------------------------------------------------
# 14. Save Benchmark Summary
# ------------------------------------------------------------

summary_df = pd.DataFrame([{

    "model": "wav2vec2-large-xlsr-persian-v3",

    "samples": len(predictions),

    "wer": wer_score,

    "cer": cer_score,

    "rtf": rtf,

    "avg_latency_sec": avg_latency,

    "gpu_memory_gb": peak_memory,

    "total_inference_time_sec": total_time
}])

summary_df.to_csv(
    "/content/drive/MyDrive/asr_project/w2v_summary.csv",
    index=False
)

print("Summary saved.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 66.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 20.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 74.9 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done
Benchmark samples: 1052
Missing files: 0

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/307 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

Using device: cuda

  0%|          | 0/1052 [00:00<?, ?it/s]
  0%|          | 1/1052 [00:20<6:02:01, 20.67s/it]
  0%|          | 2/1052 [00:21<2:33:15,  8.76s/it]
  0%|          | 3/1052 [00:21<1:26:00,  4.92s/it]
  0%|          | 4/1052 [00:21<54:38,  3.13s/it]
  0%|          | 5/1052 [00:22<37:26,  2.15s/it]
  1%|          | 6/1052 [00:22<27:59,  1.61s/it]
  1%|          | 7/1052 [00:23<21:12,  1.22s/it]
  1%|          | 8/1052 [00:23<16:52,  1.03it/s]
  1%|          | 9/1052 [00:24<13:42,  1.27it/s]
  1%|          | 10/1052 [00:24<11:34,  1.50it/s]
  1%|          | 11/1052 [00:24<10:15,  1.69it/s]
  1%|          | 12/1052 [00:25<09:28,  1.83it/s]
  1%|          | 13/1052 [00:25<08:26,  2.05it/s]
  1%|▏         | 14/1052 [00:26<07:55,  2.18it/s]
  1%|▏         | 15/1052 [00:26<07:28,  2.31it/s]
  2%|▏         | 16/1052 [00:26<07:17,  2.37it/s]
  2%|▏         | 17/1052 [00:27<07:00,  2.46it/s]
  2%|▏         | 18/1052 [00:27<07:00,  2.46it/s]
  2%|▏         | 19/1052 [00:27<06:29,  2.65it/s]
  2%|▏         | 20/1052 [00:28<06:33,  2.62it/s]
  2%|▏         | 21/1052 [00:28<06:17,  2.73it/s]
  2%|▏         | 22/1052 [00:28<06:22,  2.70it/s]
  2%|▏         | 23/1052 [00:29<06:41,  2.56it/s]
  2%|▏         | 24/1052 [00:29<06:16,  2.73it/s]
  2%|▏         | 25/1052 [00:30<06:36,  2.59it/s]
  2%|▏         | 26/1052 [00:30<06:28,  2.64it/s]
  3%|▎         | 27/1052 [00:30<06:27,  2.65it/s]
  3%|▎         | 28/1052 [00:31<06:21,  2.68it/s]
  3%|▎         | 29/1052 [00:31<06:30,  2.62it/s]
  3%|▎         | 30/1052 [00:31<06:13,  2.74it/s]
  3%|▎         | 31/1052 [00:32<06:06,  2.78it/s]
  3%|▎         | 32/1052 [00:32<06:13,  2.73it/s]
  3%|▎         | 33/1052 [00:33<06:58,  2.43it/s]
  3%|▎         | 34/1052 [00:33<06:35,  2.57it/s]
  3%|▎         | 35/1052 [00:33<06:39,  2.54it/s]
  3%|▎         | 36/1052 [00:34<06:18,  2.68it/s]
  4%|▎         | 37/1052 [00:34<06:15,  2.70it/s]
  4%|▎         | 38/1052 [00:35<06:10,  2.74it/s]
  4%|▎         | 39/1052 [00:35<06:03,  2.79it/s]
  4%|▍         | 40/1052 [00:35<05:59,  2.82it/s]
  4%|▍         | 41/1052 [00:36<06:25,  2.62it/s]
  4%|▍         | 42/1052 [00:36<06:26,  2.61it/s]
  4%|▍         | 43/1052 [00:36<06:28,  2.60it/s]
  4%|▍         | 44/1052 [00:37<06:24,  2.62it/s]
  4%|▍         | 45/1052 [00:37<06:16,  2.67it/s]
  4%|▍         | 46/1052 [00:38<06:39,  2.52it/s]
  4%|▍         | 47/1052 [00:38<06:40,  2.51it/s]
  5%|▍         | 48/1052 [00:38<06:50,  2.45it/s]
  5%|▍         | 49/1052 [00:39<06:38,  2.52it/s]
  5%|▍         | 50/1052 [00:39<06:47,  2.46it/s]

Checkpoint saved at 50 samples

  5%|▍         | 51/1052 [00:40<07:45,  2.15it/s]
  5%|▍         | 52/1052 [00:40<07:20,  2.27it/s]
  5%|▌         | 53/1052 [00:41<07:11,  2.32it/s]
  5%|▌         | 54/1052 [00:41<07:31,  2.21it/s]
  5%|▌         | 55/1052 [00:42<07:12,  2.30it/s]
  5%|▌         | 56/1052 [00:42<06:48,  2.44it/s]
  5%|▌         | 57/1052 [00:42<06:35,  2.52it/s]
  6%|▌         | 58/1052 [00:43<06:57,  2.38it/s]
  6%|▌         | 59/1052 [00:43<06:43,  2.46it/s]
  6%|▌         | 60/1052 [00:44<07:11,  2.30it/s]
  6%|▌         | 61/1052 [00:44<06:57,  2.37it/s]
  6%|▌         | 62/1052 [00:44<06:32,  2.52it/s]
  6%|▌         | 63/1052 [00:45<06:46,  2.44it/s]
  6%|▌         | 64/1052 [00:45<06:24,  2.57it/s]
  6%|▌         | 65/1052 [00:45<06:16,  2.62it/s]
  6%|▋         | 66/1052 [00:46<06:03,  2.72it/s]
  6%|▋         | 67/1052 [00:46<05:55,  2.77it/s]
  6%|▋         | 68/1052 [00:47<05:58,  2.75it/s]
  7%|▋         | 69/1052 [00:47<06:18,  2.60it/s]
  7%|▋         | 70/1052 [00:47<06:18,  2.59it/s]
  7%|▋         | 71/1052 [00:48<06:10,  2.65it/s]
  7%|▋         | 72/1052 [00:48<05:49,  2.81it/s]
  7%|▋         | 73/1052 [00:48<05:59,  2.72it/s]
  7%|▋         | 74/1052 [00:49<06:02,  2.70it/s]
  7%|▋         | 75/1052 [00:49<06:07,  2.66it/s]
  7%|▋         | 76/1052 [00:50<06:03,  2.68it/s]
  7%|▋         | 77/1052 [00:50<06:24,  2.53it/s]
  7%|▋         | 78/1052 [00:50<06:31,  2.49it/s]
  8%|▊         | 79/1052 [00:51<06:32,  2.48it/s]
  8%|▊         | 80/1052 [00:51<06:42,  2.42it/s]
  8%|▊         | 81/1052 [00:52<06:31,  2.48it/s]
  8%|▊         | 82/1052 [00:52<06:30,  2.48it/s]
  8%|▊         | 83/1052 [00:52<06:31,  2.47it/s]
  8%|▊         | 84/1052 [00:53<06:30,  2.48it/s]
  8%|▊         | 85/1052 [00:53<06:18,  2.55it/s]
  8%|▊         | 86/1052 [00:54<06:24,  2.51it/s]
  8%|▊         | 87/1052 [00:54<06:11,  2.60it/s]
  8%|▊         | 88/1052 [00:54<06:19,  2.54it/s]
  8%|▊         | 89/1052 [00:55<05:46,  2.78it/s]
  9%|▊         | 90/1052 [00:55<06:14,  2.57it/s]
  9%|▊         | 91/1052 [00:56<06:12,  2.58it/s]
  9%|▊         | 92/1052 [00:56<05:53,  2.72it/s]
  9%|▉         | 93/1052 [00:56<05:48,  2.75it/s]
  9%|▉         | 94/1052 [00:57<05:52,  2.72it/s]
  9%|▉         | 95/1052 [00:57<05:57,  2.67it/s]
  9%|▉         | 96/1052 [00:57<05:41,  2.80it/s]
  9%|▉         | 97/1052 [00:58<06:39,  2.39it/s]
  9%|▉         | 98/1052 [00:58<06:25,  2.48it/s]
  9%|▉         | 99/1052 [00:59<06:18,  2.52it/s]
 10%|▉         | 100/1052 [00:59<06:09,  2.57it/s]

Checkpoint saved at 100 samples

 10%|▉         | 101/1052 [00:59<05:55,  2.67it/s]
 10%|▉         | 102/1052 [01:00<06:03,  2.61it/s]
 10%|▉         | 103/1052 [01:00<05:56,  2.66it/s]
 10%|▉         | 104/1052 [01:00<05:52,  2.69it/s]
 10%|▉         | 105/1052 [01:01<06:12,  2.54it/s]
 10%|█         | 106/1052 [01:01<06:18,  2.50it/s]
 10%|█         | 107/1052 [01:02<06:26,  2.45it/s]
 10%|█         | 108/1052 [01:02<06:19,  2.49it/s]
 10%|█         | 109/1052 [01:02<05:41,  2.76it/s]
 10%|█         | 110/1052 [01:03<05:42,  2.75it/s]
 11%|█         | 111/1052 [01:03<05:44,  2.73it/s]
 11%|█         | 112/1052 [01:03<05:46,  2.71it/s]
 11%|█         | 113/1052 [01:04<05:53,  2.66it/s]
 11%|█         | 114/1052 [01:04<05:29,  2.85it/s]
 11%|█         | 115/1052 [01:05<05:40,  2.76it/s]
 11%|█         | 116/1052 [01:05<05:47,  2.69it/s]
 11%|█         | 117/1052 [01:05<05:45,  2.71it/s]
 11%|█         | 118/1052 [01:06<05:54,  2.63it/s]
 11%|█▏        | 119/1052 [01:06<05:50,  2.66it/s]
 11%|█▏        | 120/1052 [01:06<05:55,  2.62it/s]
 12%|█▏        | 121/1052 [01:07<05:39,  2.74it/s]
 12%|█▏        | 122/1052 [01:07<05:39,  2.74it/s]
 12%|█▏        | 123/1052 [01:08<05:39,  2.74it/s]
 12%|█▏        | 124/1052 [01:08<05:42,  2.71it/s]
 12%|█▏        | 125/1052 [01:08<05:50,  2.64it/s]
 12%|█▏        | 126/1052 [01:09<05:53,  2.62it/s]
 12%|█▏        | 127/1052 [01:09<05:53,  2.61it/s]
 12%|█▏        | 128/1052 [01:09<05:54,  2.60it/s]
 12%|█▏        | 129/1052 [01:10<05:55,  2.59it/s]
 12%|█▏        | 130/1052 [01:10<06:08,  2.50it/s]
 12%|█▏        | 131/1052 [01:11<06:12,  2.47it/s]
 13%|█▎        | 132/1052 [01:11<06:08,  2.50it/s]
 13%|█▎        | 133/1052 [01:11<05:56,  2.58it/s]
 13%|█▎        | 134/1052 [01:12<06:00,  2.55it/s]
 13%|█▎        | 135/1052 [01:12<05:52,  2.60it/s]
 13%|█▎        | 136/1052 [01:13<06:02,  2.53it/s]
 13%|█▎        | 137/1052 [01:13<05:42,  2.67it/s]
 13%|█▎        | 138/1052 [01:13<05:55,  2.57it/s]
 13%|█▎        | 139/1052 [01:14<06:01,  2.53it/s]
 13%|█▎        | 140/1052 [01:14<05:50,  2.60it/s]
 13%|█▎        | 141/1052 [01:15<06:11,  2.45it/s]
 13%|█▎        | 142/1052 [01:15<06:09,  2.46it/s]
 14%|█▎        | 143/1052 [01:15<05:57,  2.54it/s]
 14%|█▎        | 144/1052 [01:16<06:25,  2.36it/s]
 14%|█▍        | 145/1052 [01:17<07:14,  2.09it/s]
 14%|█▍        | 146/1052 [01:17<06:28,  2.33it/s]
 14%|█▍        | 147/1052 [01:17<06:10,  2.44it/s]
 14%|█▍        | 148/1052 [01:18<06:02,  2.49it/s]
 14%|█▍        | 149/1052 [01:18<06:18,  2.39it/s]
 14%|█▍        | 150/1052 [01:18<06:09,  2.44it/s]

Checkpoint saved at 150 samples

 14%|█▍        | 151/1052 [01:19<06:10,  2.43it/s]
 14%|█▍        | 152/1052 [01:19<05:58,  2.51it/s]
 15%|█▍        | 153/1052 [01:20<05:36,  2.67it/s]
 15%|█▍        | 154/1052 [01:20<05:18,  2.82it/s]
 15%|█▍        | 155/1052 [01:20<05:08,  2.91it/s]
 15%|█▍        | 156/1052 [01:20<05:07,  2.91it/s]
 15%|█▍        | 157/1052 [01:21<04:51,  3.07it/s]
 15%|█▌        | 158/1052 [01:21<05:07,  2.90it/s]
 15%|█▌        | 159/1052 [01:22<05:54,  2.52it/s]
 15%|█▌        | 160/1052 [01:22<05:44,  2.59it/s]
 15%|█▌        | 161/1052 [01:23<06:08,  2.42it/s]
 15%|█▌        | 162/1052 [01:23<06:11,  2.39it/s]
 15%|█▌        | 163/1052 [01:23<05:43,  2.59it/s]
 16%|█▌        | 164/1052 [01:24<05:44,  2.58it/s]
 16%|█▌        | 165/1052 [01:24<06:00,  2.46it/s]
 16%|█▌        | 166/1052 [01:25<06:19,  2.34it/s]
 16%|█▌        | 167/1052 [01:25<05:59,  2.46it/s]
 16%|█▌        | 168/1052 [01:25<05:44,  2.57it/s]
 16%|█▌        | 169/1052 [01:26<05:39,  2.60it/s]
 16%|█▌        | 170/1052 [01:26<05:32,  2.65it/s]
 16%|█▋        | 171/1052 [01:26<05:26,  2.70it/s]
 16%|█▋        | 172/1052 [01:27<05:25,  2.70it/s]
 16%|█▋        | 173/1052 [01:27<05:30,  2.66it/s]
 17%|█▋        | 174/1052 [01:28<05:33,  2.63it/s]
 17%|█▋        | 175/1052 [01:28<05:25,  2.69it/s]
 17%|█▋        | 176/1052 [01:28<05:27,  2.68it/s]
 17%|█▋        | 177/1052 [01:29<05:38,  2.59it/s]
 17%|█▋        | 178/1052 [01:29<05:38,  2.58it/s]
 17%|█▋        | 179/1052 [01:29<05:30,  2.64it/s]
 17%|█▋        | 180/1052 [01:30<05:31,  2.63it/s]
 17%|█▋        | 181/1052 [01:30<05:27,  2.66it/s]
 17%|█▋        | 182/1052 [01:31<05:27,  2.66it/s]
 17%|█▋        | 183/1052 [01:31<06:13,  2.33it/s]
 17%|█▋        | 184/1052 [01:31<06:05,  2.37it/s]
 18%|█▊        | 185/1052 [01:32<06:07,  2.36it/s]
 18%|█▊        | 186/1052 [01:32<05:53,  2.45it/s]
 18%|█▊        | 187/1052 [01:33<05:42,  2.53it/s]
 18%|█▊        | 188/1052 [01:33<05:50,  2.47it/s]
 18%|█▊        | 189/1052 [01:33<05:25,  2.65it/s]
 18%|█▊        | 190/1052 [01:34<05:34,  2.57it/s]
 18%|█▊        | 191/1052 [01:34<05:29,  2.61it/s]
 18%|█▊        | 192/1052 [01:35<05:23,  2.66it/s]
 18%|█▊        | 193/1052 [01:35<05:25,  2.64it/s]
 18%|█▊        | 194/1052 [01:35<05:43,  2.49it/s]
 19%|█▊        | 195/1052 [01:36<05:40,  2.52it/s]
 19%|█▊        | 196/1052 [01:36<05:35,  2.55it/s]
 19%|█▊        | 197/1052 [01:37<05:39,  2.52it/s]
 19%|█▉        | 198/1052 [01:37<05:41,  2.50it/s]
 19%|█▉        | 199/1052 [01:37<05:34,  2.55it/s]
 19%|█▉        | 200/1052 [01:38<05:26,  2.61it/s]

Checkpoint saved at 200 samples

 19%|█▉        | 201/1052 [01:38<05:22,  2.64it/s]
 19%|█▉        | 202/1052 [01:39<05:36,  2.52it/s]
 19%|█▉        | 203/1052 [01:39<05:34,  2.54it/s]
 19%|█▉        | 204/1052 [01:39<05:07,  2.76it/s]
 19%|█▉        | 205/1052 [01:40<05:02,  2.80it/s]
 20%|█▉        | 206/1052 [01:40<05:04,  2.78it/s]
 20%|█▉        | 207/1052 [01:40<05:01,  2.80it/s]
 20%|█▉        | 208/1052 [01:41<05:01,  2.80it/s]
 20%|█▉        | 209/1052 [01:41<05:08,  2.73it/s]
 20%|█▉        | 210/1052 [01:41<05:20,  2.63it/s]
 20%|██        | 211/1052 [01:42<05:39,  2.48it/s]
 20%|██        | 212/1052 [01:42<06:04,  2.30it/s]
 20%|██        | 213/1052 [01:43<05:40,  2.47it/s]
 20%|██        | 214/1052 [01:43<05:29,  2.55it/s]
 20%|██        | 215/1052 [01:43<05:22,  2.60it/s]
 21%|██        | 216/1052 [01:44<05:23,  2.59it/s]
 21%|██        | 217/1052 [01:44<05:38,  2.47it/s]
 21%|██        | 218/1052 [01:45<05:41,  2.44it/s]
 21%|██        | 219/1052 [01:45<05:35,  2.49it/s]
 21%|██        | 220/1052 [01:45<05:18,  2.61it/s]
 21%|██        | 221/1052 [01:46<05:11,  2.67it/s]
 21%|██        | 222/1052 [01:46<05:05,  2.72it/s]
 21%|██        | 223/1052 [01:47<05:15,  2.63it/s]
 21%|██▏       | 224/1052 [01:47<05:18,  2.60it/s]
 21%|██▏       | 225/1052 [01:47<05:09,  2.67it/s]
 21%|██▏       | 226/1052 [01:48<05:14,  2.63it/s]
 22%|██▏       | 227/1052 [01:48<05:45,  2.39it/s]
 22%|██▏       | 228/1052 [01:48<05:18,  2.58it/s]
 22%|██▏       | 229/1052 [01:49<05:05,  2.69it/s]
 22%|██▏       | 230/1052 [01:49<05:20,  2.57it/s]
 22%|██▏       | 231/1052 [01:50<05:15,  2.60it/s]
 22%|██▏       | 232/1052 [01:50<05:15,  2.60it/s]
 22%|██▏       | 233/1052 [01:51<06:32,  2.09it/s]
 22%|██▏       | 234/1052 [01:51<06:34,  2.07it/s]
 22%|██▏       | 235/1052 [01:52<06:09,  2.21it/s]
 22%|██▏       | 236/1052 [01:52<05:41,  2.39it/s]
 23%|██▎       | 237/1052 [01:52<05:46,  2.35it/s]
 23%|██▎       | 238/1052 [01:53<05:40,  2.39it/s]
 23%|██▎       | 239/1052 [01:53<05:25,  2.50it/s]
 23%|██▎       | 240/1052 [01:53<05:13,  2.59it/s]
 23%|██▎       | 241/1052 [01:54<05:11,  2.60it/s]
 23%|██▎       | 242/1052 [01:54<05:09,  2.61it/s]
 23%|██▎       | 243/1052 [01:55<05:20,  2.53it/s]
 23%|██▎       | 244/1052 [01:55<05:22,  2.50it/s]
 23%|██▎       | 245/1052 [01:56<05:37,  2.39it/s]
 23%|██▎       | 246/1052 [01:56<05:47,  2.32it/s]
 23%|██▎       | 247/1052 [01:56<05:24,  2.48it/s]
 24%|██▎       | 248/1052 [01:57<05:10,  2.59it/s]
 24%|██▎       | 249/1052 [01:57<05:10,  2.58it/s]
 24%|██▍       | 250/1052 [01:57<04:59,  2.68it/s]

Checkpoint saved at 250 samples

 24%|██▍       | 251/1052 [01:58<04:44,  2.81it/s]
 24%|██▍       | 252/1052 [01:58<05:12,  2.56it/s]
 24%|██▍       | 253/1052 [01:59<05:32,  2.40it/s]
 24%|██▍       | 254/1052 [01:59<05:32,  2.40it/s]
 24%|██▍       | 255/1052 [01:59<05:14,  2.53it/s]
 24%|██▍       | 256/1052 [02:00<05:21,  2.48it/s]
 24%|██▍       | 257/1052 [02:00<05:12,  2.54it/s]
 25%|██▍       | 258/1052 [02:01<04:59,  2.65it/s]
 25%|██▍       | 259/1052 [02:01<04:58,  2.66it/s]
 25%|██▍       | 260/1052 [02:01<04:43,  2.79it/s]
 25%|██▍       | 261/1052 [02:02<06:04,  2.17it/s]
 25%|██▍       | 262/1052 [02:02<05:48,  2.27it/s]
 25%|██▌       | 263/1052 [02:03<05:44,  2.29it/s]
 25%|██▌       | 264/1052 [02:03<05:34,  2.35it/s]
 25%|██▌       | 265/1052 [02:04<07:03,  1.86it/s]
 25%|██▌       | 266/1052 [02:04<06:32,  2.00it/s]
 25%|██▌       | 267/1052 [02:05<06:33,  2.00it/s]
 25%|██▌       | 268/1052 [02:05<05:59,  2.18it/s]
 26%|██▌       | 269/1052 [02:06<05:44,  2.27it/s]
 26%|██▌       | 270/1052 [02:06<05:52,  2.22it/s]
 26%|██▌       | 271/1052 [02:07<06:13,  2.09it/s]
 26%|██▌       | 272/1052 [02:07<05:45,  2.26it/s]
 26%|██▌       | 273/1052 [02:07<05:21,  2.43it/s]
 26%|██▌       | 274/1052 [02:08<04:57,  2.61it/s]
 26%|██▌       | 275/1052 [02:08<04:57,  2.62it/s]
 26%|██▌       | 276/1052 [02:09<05:19,  2.43it/s]
 26%|██▋       | 277/1052 [02:09<05:03,  2.56it/s]
 26%|██▋       | 278/1052 [02:09<05:17,  2.44it/s]
 27%|██▋       | 279/1052 [02:10<06:00,  2.14it/s]
 27%|██▋       | 280/1052 [02:10<05:33,  2.32it/s]
 27%|██▋       | 281/1052 [02:11<05:20,  2.41it/s]
 27%|██▋       | 282/1052 [02:11<05:01,  2.55it/s]
 27%|██▋       | 283/1052 [02:11<05:03,  2.54it/s]
 27%|██▋       | 284/1052 [02:12<05:02,  2.54it/s]
 27%|██▋       | 285/1052 [02:12<05:09,  2.47it/s]
 27%|██▋       | 286/1052 [02:13<04:50,  2.64it/s]
 27%|██▋       | 287/1052 [02:13<04:48,  2.65it/s]
 27%|██▋       | 288/1052 [02:13<04:35,  2.77it/s]
 27%|██▋       | 289/1052 [02:14<04:39,  2.73it/s]
 28%|██▊       | 290/1052 [02:14<04:45,  2.67it/s]
 28%|██▊       | 291/1052 [02:14<04:55,  2.57it/s]
 28%|██▊       | 292/1052 [02:15<04:43,  2.68it/s]
 28%|██▊       | 293/1052 [02:15<04:51,  2.61it/s]
 28%|██▊       | 294/1052 [02:16<04:48,  2.63it/s]
 28%|██▊       | 295/1052 [02:16<04:35,  2.74it/s]
 28%|██▊       | 296/1052 [02:16<04:57,  2.54it/s]
 28%|██▊       | 297/1052 [02:17<05:02,  2.50it/s]
 28%|██▊       | 298/1052 [02:17<04:51,  2.59it/s]
 28%|██▊       | 299/1052 [02:17<04:40,  2.69it/s]
 29%|██▊       | 300/1052 [02:18<04:52,  2.57it/s]

Checkpoint saved at 300 samples

 29%|██▊       | 301/1052 [02:18<04:51,  2.57it/s]
 29%|██▊       | 302/1052 [02:19<04:41,  2.66it/s]
 29%|██▉       | 303/1052 [02:19<04:38,  2.69it/s]
 29%|██▉       | 304/1052 [02:19<04:48,  2.59it/s]
 29%|██▉       | 305/1052 [02:20<05:07,  2.43it/s]
 29%|██▉       | 306/1052 [02:20<05:02,  2.47it/s]
 29%|██▉       | 307/1052 [02:21<04:46,  2.60it/s]
 29%|██▉       | 308/1052 [02:21<04:49,  2.57it/s]
 29%|██▉       | 309/1052 [02:21<04:35,  2.70it/s]
 29%|██▉       | 310/1052 [02:22<04:37,  2.68it/s]
 30%|██▉       | 311/1052 [02:22<04:32,  2.72it/s]
 30%|██▉       | 312/1052 [02:22<04:16,  2.88it/s]
 30%|██▉       | 313/1052 [02:23<04:46,  2.58it/s]
 30%|██▉       | 314/1052 [02:23<05:03,  2.43it/s]
 30%|██▉       | 315/1052 [02:24<05:27,  2.25it/s]
 30%|███       | 316/1052 [02:24<05:03,  2.43it/s]
 30%|███       | 317/1052 [02:25<05:02,  2.43it/s]
 30%|███       | 318/1052 [02:25<05:06,  2.39it/s]
 30%|███       | 319/1052 [02:25<05:04,  2.41it/s]
 30%|███       | 320/1052 [02:26<05:29,  2.22it/s]
 31%|███       | 321/1052 [02:26<05:28,  2.23it/s]
 31%|███       | 322/1052 [02:27<05:11,  2.34it/s]
 31%|███       | 323/1052 [02:27<04:54,  2.47it/s]
 31%|███       | 324/1052 [02:27<04:47,  2.53it/s]
 31%|███       | 325/1052 [02:28<04:51,  2.50it/s]
 31%|███       | 326/1052 [02:28<04:56,  2.45it/s]
 31%|███       | 327/1052 [02:29<04:38,  2.60it/s]
 31%|███       | 328/1052 [02:29<04:36,  2.62it/s]
 31%|███▏      | 329/1052 [02:29<04:34,  2.63it/s]
 31%|███▏      | 330/1052 [02:30<04:38,  2.59it/s]
 31%|███▏      | 331/1052 [02:30<04:42,  2.55it/s]
 32%|███▏      | 332/1052 [02:31<04:39,  2.58it/s]
 32%|███▏      | 333/1052 [02:31<04:36,  2.60it/s]
 32%|███▏      | 334/1052 [02:31<04:28,  2.67it/s]
 32%|███▏      | 335/1052 [02:32<04:47,  2.50it/s]
 32%|███▏      | 336/1052 [02:32<04:37,  2.58it/s]
 32%|███▏      | 337/1052 [02:33<04:41,  2.54it/s]
 32%|███▏      | 338/1052 [02:33<04:50,  2.46it/s]
 32%|███▏      | 339/1052 [02:33<05:02,  2.36it/s]
 32%|███▏      | 340/1052 [02:34<04:51,  2.44it/s]
 32%|███▏      | 341/1052 [02:34<04:37,  2.57it/s]
 33%|███▎      | 342/1052 [02:35<04:58,  2.38it/s]
 33%|███▎      | 343/1052 [02:35<04:33,  2.59it/s]
 33%|███▎      | 344/1052 [02:35<04:35,  2.57it/s]
 33%|███▎      | 345/1052 [02:36<04:29,  2.63it/s]
 33%|███▎      | 346/1052 [02:36<04:31,  2.60it/s]
 33%|███▎      | 347/1052 [02:37<06:32,  1.80it/s]
 33%|███▎      | 348/1052 [02:37<05:56,  1.97it/s]
 33%|███▎      | 349/1052 [02:38<05:31,  2.12it/s]
 33%|███▎      | 350/1052 [02:38<05:13,  2.24it/s]

Checkpoint saved at 350 samples

 33%|███▎      | 351/1052 [02:39<05:10,  2.25it/s]
 33%|███▎      | 352/1052 [02:39<04:54,  2.38it/s]
 34%|███▎      | 353/1052 [02:39<04:53,  2.38it/s]
 34%|███▎      | 354/1052 [02:40<04:49,  2.41it/s]
 34%|███▎      | 355/1052 [02:40<04:56,  2.35it/s]
 34%|███▍      | 356/1052 [02:41<04:43,  2.46it/s]
 34%|███▍      | 357/1052 [02:41<04:47,  2.41it/s]
 34%|███▍      | 358/1052 [02:41<04:40,  2.48it/s]
 34%|███▍      | 359/1052 [02:42<04:28,  2.58it/s]
 34%|███▍      | 360/1052 [02:42<04:23,  2.63it/s]
 34%|███▍      | 361/1052 [02:43<04:21,  2.64it/s]
 34%|███▍      | 362/1052 [02:43<05:00,  2.30it/s]
 35%|███▍      | 363/1052 [02:44<04:46,  2.41it/s]
 35%|███▍      | 364/1052 [02:44<04:58,  2.30it/s]
 35%|███▍      | 365/1052 [02:44<05:01,  2.28it/s]
 35%|███▍      | 366/1052 [02:45<04:49,  2.37it/s]
 35%|███▍      | 367/1052 [02:45<04:53,  2.34it/s]
 35%|███▍      | 368/1052 [02:46<04:37,  2.47it/s]
 35%|███▌      | 369/1052 [02:46<04:29,  2.54it/s]
 35%|███▌      | 370/1052 [02:46<04:28,  2.54it/s]
 35%|███▌      | 371/1052 [02:47<04:22,  2.60it/s]
 35%|███▌      | 372/1052 [02:47<04:28,  2.54it/s]
 35%|███▌      | 373/1052 [02:48<04:17,  2.64it/s]
 36%|███▌      | 374/1052 [02:48<04:21,  2.60it/s]
 36%|███▌      | 375/1052 [02:48<04:16,  2.64it/s]
 36%|███▌      | 376/1052 [02:49<04:09,  2.71it/s]
 36%|███▌      | 377/1052 [02:49<04:44,  2.37it/s]
 36%|███▌      | 378/1052 [02:50<04:52,  2.31it/s]
 36%|███▌      | 379/1052 [02:50<04:53,  2.29it/s]
 36%|███▌      | 380/1052 [02:50<04:46,  2.34it/s]
 36%|███▌      | 381/1052 [02:51<04:38,  2.41it/s]
 36%|███▋      | 382/1052 [02:51<04:52,  2.29it/s]
 36%|███▋      | 383/1052 [02:52<04:43,  2.36it/s]
 37%|███▋      | 384/1052 [02:52<04:40,  2.38it/s]
 37%|███▋      | 385/1052 [02:52<04:25,  2.52it/s]
 37%|███▋      | 386/1052 [02:53<04:09,  2.67it/s]
 37%|███▋      | 387/1052 [02:53<04:03,  2.73it/s]
 37%|███▋      | 388/1052 [02:54<04:12,  2.63it/s]
 37%|███▋      | 389/1052 [02:54<04:12,  2.62it/s]
 37%|███▋      | 390/1052 [02:54<04:09,  2.66it/s]
 37%|███▋      | 391/1052 [02:55<04:03,  2.71it/s]
 37%|███▋      | 392/1052 [02:55<04:06,  2.68it/s]
 37%|███▋      | 393/1052 [02:55<04:13,  2.60it/s]
 37%|███▋      | 394/1052 [02:56<04:44,  2.31it/s]
 38%|███▊      | 395/1052 [02:56<04:34,  2.39it/s]
 38%|███▊      | 396/1052 [02:57<04:26,  2.46it/s]
 38%|███▊      | 397/1052 [02:57<04:22,  2.49it/s]
 38%|███▊      | 398/1052 [02:58<04:15,  2.56it/s]
 38%|███▊      | 399/1052 [02:58<04:10,  2.61it/s]
 38%|███▊      | 400/1052 [02:58<04:02,  2.69it/s]

Checkpoint saved at 400 samples

 38%|███▊      | 401/1052 [02:59<04:23,  2.47it/s]
 38%|███▊      | 402/1052 [02:59<04:20,  2.50it/s]
 38%|███▊      | 403/1052 [02:59<04:12,  2.57it/s]
 38%|███▊      | 404/1052 [03:00<04:18,  2.51it/s]
 38%|███▊      | 405/1052 [03:00<04:20,  2.49it/s]
 39%|███▊      | 406/1052 [03:01<04:20,  2.48it/s]
 39%|███▊      | 407/1052 [03:01<04:43,  2.28it/s]
 39%|███▉      | 408/1052 [03:02<04:36,  2.33it/s]
 39%|███▉      | 409/1052 [03:02<04:23,  2.44it/s]
 39%|███▉      | 410/1052 [03:02<04:21,  2.45it/s]
 39%|███▉      | 411/1052 [03:03<04:16,  2.50it/s]
 39%|███▉      | 412/1052 [03:03<04:16,  2.50it/s]
 39%|███▉      | 413/1052 [03:04<04:05,  2.60it/s]
 39%|███▉      | 414/1052 [03:04<04:01,  2.64it/s]
 39%|███▉      | 415/1052 [03:04<04:04,  2.61it/s]
 40%|███▉      | 416/1052 [03:05<04:09,  2.55it/s]
 40%|███▉      | 417/1052 [03:05<04:10,  2.54it/s]
 40%|███▉      | 418/1052 [03:05<04:06,  2.57it/s]
 40%|███▉      | 419/1052 [03:06<04:04,  2.59it/s]
 40%|███▉      | 420/1052 [03:06<04:37,  2.28it/s]
 40%|████      | 421/1052 [03:07<04:41,  2.24it/s]
 40%|████      | 422/1052 [03:08<05:39,  1.86it/s]
 40%|████      | 423/1052 [03:08<05:08,  2.04it/s]
 40%|████      | 424/1052 [03:08<04:58,  2.10it/s]
 40%|████      | 425/1052 [03:09<04:47,  2.18it/s]
 40%|████      | 426/1052 [03:10<05:26,  1.92it/s]
 41%|████      | 427/1052 [03:10<05:27,  1.91it/s]
 41%|████      | 428/1052 [03:10<04:56,  2.10it/s]
 41%|████      | 429/1052 [03:11<04:38,  2.24it/s]
 41%|████      | 430/1052 [03:11<04:16,  2.42it/s]
 41%|████      | 431/1052 [03:12<04:07,  2.51it/s]
 41%|████      | 432/1052 [03:12<04:00,  2.58it/s]
 41%|████      | 433/1052 [03:12<03:53,  2.65it/s]
 41%|████▏     | 434/1052 [03:13<03:56,  2.61it/s]
 41%|████▏     | 435/1052 [03:13<03:48,  2.70it/s]
 41%|████▏     | 436/1052 [03:13<03:46,  2.72it/s]
 42%|████▏     | 437/1052 [03:14<03:48,  2.69it/s]
 42%|████▏     | 438/1052 [03:14<04:12,  2.43it/s]
 42%|████▏     | 439/1052 [03:15<04:07,  2.47it/s]
 42%|████▏     | 440/1052 [03:15<04:07,  2.47it/s]
 42%|████▏     | 441/1052 [03:16<04:21,  2.34it/s]
 42%|████▏     | 442/1052 [03:16<04:22,  2.32it/s]
 42%|████▏     | 443/1052 [03:16<04:19,  2.34it/s]
 42%|████▏     | 444/1052 [03:17<04:16,  2.37it/s]
 42%|████▏     | 445/1052 [03:17<04:03,  2.50it/s]
 42%|████▏     | 446/1052 [03:17<03:46,  2.67it/s]
 42%|████▏     | 447/1052 [03:18<03:52,  2.61it/s]
 43%|████▎     | 448/1052 [03:18<03:44,  2.69it/s]
 43%|████▎     | 449/1052 [03:19<03:50,  2.61it/s]
 43%|████▎     | 450/1052 [03:19<03:41,  2.72it/s]

Checkpoint saved at 450 samples

 43%|████▎     | 451/1052 [03:19<04:08,  2.42it/s]
 43%|████▎     | 452/1052 [03:20<04:03,  2.46it/s]
 43%|████▎     | 453/1052 [03:20<04:02,  2.47it/s]
 43%|████▎     | 454/1052 [03:21<03:55,  2.54it/s]
 43%|████▎     | 455/1052 [03:21<03:42,  2.69it/s]
 43%|████▎     | 456/1052 [03:21<04:04,  2.44it/s]
 43%|████▎     | 457/1052 [03:22<03:54,  2.53it/s]
 44%|████▎     | 458/1052 [03:22<03:55,  2.52it/s]
 44%|████▎     | 459/1052 [03:23<03:47,  2.61it/s]
 44%|████▎     | 460/1052 [03:23<03:42,  2.66it/s]
 44%|████▍     | 461/1052 [03:23<03:37,  2.72it/s]
 44%|████▍     | 462/1052 [03:24<03:34,  2.75it/s]
 44%|████▍     | 463/1052 [03:24<03:43,  2.63it/s]
 44%|████▍     | 464/1052 [03:24<03:42,  2.64it/s]
 44%|████▍     | 465/1052 [03:25<03:32,  2.77it/s]
 44%|████▍     | 466/1052 [03:25<03:42,  2.63it/s]
 44%|████▍     | 467/1052 [03:25<03:36,  2.71it/s]
 44%|████▍     | 468/1052 [03:26<03:31,  2.76it/s]
 45%|████▍     | 469/1052 [03:26<03:24,  2.85it/s]
 45%|████▍     | 470/1052 [03:26<03:12,  3.02it/s]
 45%|████▍     | 471/1052 [03:27<03:19,  2.91it/s]
 45%|████▍     | 472/1052 [03:27<03:35,  2.69it/s]
 45%|████▍     | 473/1052 [03:28<03:47,  2.55it/s]
 45%|████▌     | 474/1052 [03:28<03:44,  2.57it/s]
 45%|████▌     | 475/1052 [03:28<03:45,  2.56it/s]
 45%|████▌     | 476/1052 [03:29<04:00,  2.39it/s]
 45%|████▌     | 477/1052 [03:29<03:53,  2.46it/s]
 45%|████▌     | 478/1052 [03:30<03:58,  2.41it/s]
 46%|████▌     | 479/1052 [03:30<03:51,  2.48it/s]
 46%|████▌     | 480/1052 [03:31<03:52,  2.46it/s]
 46%|████▌     | 481/1052 [03:31<03:32,  2.69it/s]
 46%|████▌     | 482/1052 [03:31<03:29,  2.73it/s]
 46%|████▌     | 483/1052 [03:32<03:44,  2.53it/s]
 46%|████▌     | 484/1052 [03:32<03:52,  2.44it/s]
 46%|████▌     | 485/1052 [03:32<03:44,  2.53it/s]
 46%|████▌     | 486/1052 [03:33<03:45,  2.51it/s]
 46%|████▋     | 487/1052 [03:33<03:41,  2.55it/s]
 46%|████▋     | 488/1052 [03:34<03:39,  2.57it/s]
 46%|████▋     | 489/1052 [03:34<03:26,  2.73it/s]
 47%|████▋     | 490/1052 [03:34<03:43,  2.52it/s]
 47%|████▋     | 491/1052 [03:35<03:46,  2.47it/s]
 47%|████▋     | 492/1052 [03:35<04:13,  2.21it/s]
 47%|████▋     | 493/1052 [03:36<03:58,  2.35it/s]
 47%|████▋     | 494/1052 [03:36<03:42,  2.51it/s]
 47%|████▋     | 495/1052 [03:36<03:34,  2.59it/s]
 47%|████▋     | 496/1052 [03:37<03:30,  2.64it/s]
 47%|████▋     | 497/1052 [03:37<03:29,  2.64it/s]
 47%|████▋     | 498/1052 [03:37<03:17,  2.80it/s]
 47%|████▋     | 499/1052 [03:38<03:20,  2.76it/s]
 48%|████▊     | 500/1052 [03:38<03:23,  2.72it/s]

Checkpoint saved at 500 samples

 48%|████▊     | 501/1052 [03:39<03:18,  2.78it/s]
 48%|████▊     | 502/1052 [03:39<03:17,  2.78it/s]
 48%|████▊     | 503/1052 [03:39<03:10,  2.89it/s]
 48%|████▊     | 504/1052 [03:40<03:03,  2.99it/s]
 48%|████▊     | 505/1052 [03:40<03:02,  2.99it/s]
 48%|████▊     | 506/1052 [03:40<03:17,  2.76it/s]
 48%|████▊     | 507/1052 [03:41<03:24,  2.66it/s]
 48%|████▊     | 508/1052 [03:41<03:22,  2.69it/s]
 48%|████▊     | 509/1052 [03:41<03:20,  2.71it/s]
 48%|████▊     | 510/1052 [03:42<03:32,  2.55it/s]
 49%|████▊     | 511/1052 [03:42<03:27,  2.61it/s]
 49%|████▊     | 512/1052 [03:43<03:28,  2.60it/s]
 49%|████▉     | 513/1052 [03:43<03:16,  2.74it/s]
 49%|████▉     | 514/1052 [03:44<03:44,  2.39it/s]
 49%|████▉     | 515/1052 [03:44<03:51,  2.32it/s]
 49%|████▉     | 516/1052 [03:44<03:55,  2.28it/s]
 49%|████▉     | 517/1052 [03:45<03:56,  2.26it/s]
 49%|████▉     | 518/1052 [03:45<03:31,  2.53it/s]
 49%|████▉     | 519/1052 [03:46<03:40,  2.42it/s]
 49%|████▉     | 520/1052 [03:46<03:24,  2.60it/s]
 50%|████▉     | 521/1052 [03:46<03:18,  2.68it/s]
 50%|████▉     | 522/1052 [03:47<03:21,  2.63it/s]
 50%|████▉     | 523/1052 [03:47<03:22,  2.62it/s]
 50%|████▉     | 524/1052 [03:47<03:23,  2.59it/s]
 50%|████▉     | 525/1052 [03:48<03:24,  2.58it/s]
 50%|█████     | 526/1052 [03:48<03:27,  2.54it/s]
 50%|█████     | 527/1052 [03:49<03:28,  2.52it/s]
 50%|█████     | 528/1052 [03:49<03:15,  2.67it/s]
 50%|█████     | 529/1052 [03:49<03:11,  2.72it/s]
 50%|█████     | 530/1052 [03:50<03:17,  2.65it/s]
 50%|█████     | 531/1052 [03:50<03:11,  2.71it/s]
 51%|█████     | 532/1052 [03:51<03:17,  2.63it/s]
 51%|█████     | 533/1052 [03:51<03:33,  2.43it/s]
 51%|█████     | 534/1052 [03:52<04:04,  2.12it/s]
 51%|█████     | 535/1052 [03:52<03:43,  2.32it/s]
 51%|█████     | 536/1052 [03:52<03:47,  2.27it/s]
 51%|█████     | 537/1052 [03:53<03:39,  2.34it/s]
 51%|█████     | 538/1052 [03:53<03:35,  2.39it/s]
 51%|█████     | 539/1052 [03:54<03:43,  2.29it/s]
 51%|█████▏    | 540/1052 [03:54<03:38,  2.34it/s]
 51%|█████▏    | 541/1052 [03:54<03:25,  2.49it/s]
 52%|█████▏    | 542/1052 [03:55<03:29,  2.43it/s]
 52%|█████▏    | 543/1052 [03:55<03:14,  2.62it/s]
 52%|█████▏    | 544/1052 [03:56<03:28,  2.43it/s]
 52%|█████▏    | 545/1052 [03:56<03:31,  2.40it/s]
 52%|█████▏    | 546/1052 [03:56<03:26,  2.45it/s]
 52%|█████▏    | 547/1052 [03:57<03:17,  2.56it/s]
 52%|█████▏    | 548/1052 [03:57<03:18,  2.54it/s]
 52%|█████▏    | 549/1052 [03:58<03:14,  2.59it/s]
 52%|█████▏    | 550/1052 [03:58<03:13,  2.60it/s]

Checkpoint saved at 550 samples

 52%|█████▏    | 551/1052 [03:58<03:08,  2.66it/s]
 52%|█████▏    | 552/1052 [03:59<03:30,  2.38it/s]
 53%|█████▎    | 553/1052 [03:59<03:21,  2.47it/s]
 53%|█████▎    | 554/1052 [04:00<03:24,  2.44it/s]
 53%|█████▎    | 555/1052 [04:00<03:59,  2.08it/s]
 53%|█████▎    | 556/1052 [04:01<04:00,  2.07it/s]
 53%|█████▎    | 557/1052 [04:01<03:44,  2.21it/s]
 53%|█████▎    | 558/1052 [04:02<03:32,  2.32it/s]
 53%|█████▎    | 559/1052 [04:02<03:46,  2.18it/s]
 53%|█████▎    | 560/1052 [04:02<03:35,  2.29it/s]
 53%|█████▎    | 561/1052 [04:03<03:29,  2.34it/s]
 53%|█████▎    | 562/1052 [04:03<03:23,  2.41it/s]
 54%|█████▎    | 563/1052 [04:04<03:22,  2.42it/s]
 54%|█████▎    | 564/1052 [04:04<03:09,  2.58it/s]
 54%|█████▎    | 565/1052 [04:04<03:07,  2.59it/s]
 54%|█████▍    | 566/1052 [04:05<03:11,  2.54it/s]
 54%|█████▍    | 567/1052 [04:05<03:11,  2.53it/s]
 54%|█████▍    | 568/1052 [04:06<03:20,  2.41it/s]
 54%|█████▍    | 569/1052 [04:06<03:10,  2.54it/s]
 54%|█████▍    | 570/1052 [04:06<03:07,  2.56it/s]
 54%|█████▍    | 571/1052 [04:07<03:11,  2.51it/s]
 54%|█████▍    | 572/1052 [04:07<02:59,  2.68it/s]
 54%|█████▍    | 573/1052 [04:07<02:57,  2.69it/s]
 55%|█████▍    | 574/1052 [04:08<02:55,  2.72it/s]
 55%|█████▍    | 575/1052 [04:08<02:55,  2.72it/s]
 55%|█████▍    | 576/1052 [04:09<03:00,  2.64it/s]
 55%|█████▍    | 577/1052 [04:09<02:47,  2.83it/s]
 55%|█████▍    | 578/1052 [04:09<03:10,  2.49it/s]
 55%|█████▌    | 579/1052 [04:10<02:55,  2.69it/s]
 55%|█████▌    | 580/1052 [04:10<03:03,  2.58it/s]
 55%|█████▌    | 581/1052 [04:11<03:10,  2.47it/s]
 55%|█████▌    | 582/1052 [04:11<03:07,  2.51it/s]
 55%|█████▌    | 583/1052 [04:11<02:57,  2.65it/s]
 56%|█████▌    | 584/1052 [04:12<03:10,  2.45it/s]
 56%|█████▌    | 585/1052 [04:12<03:09,  2.47it/s]
 56%|█████▌    | 586/1052 [04:13<03:06,  2.50it/s]
 56%|█████▌    | 587/1052 [04:13<03:11,  2.43it/s]
 56%|█████▌    | 588/1052 [04:13<03:06,  2.49it/s]
 56%|█████▌    | 589/1052 [04:14<03:08,  2.46it/s]
 56%|█████▌    | 590/1052 [04:14<02:54,  2.65it/s]
 56%|█████▌    | 591/1052 [04:14<02:52,  2.68it/s]
 56%|█████▋    | 592/1052 [04:15<02:41,  2.85it/s]
 56%|█████▋    | 593/1052 [04:15<02:42,  2.82it/s]
 56%|█████▋    | 594/1052 [04:15<02:45,  2.77it/s]
 57%|█████▋    | 595/1052 [04:16<02:45,  2.76it/s]
 57%|█████▋    | 596/1052 [04:16<02:47,  2.73it/s]
 57%|█████▋    | 597/1052 [04:17<02:45,  2.76it/s]
 57%|█████▋    | 598/1052 [04:17<02:48,  2.70it/s]
 57%|█████▋    | 599/1052 [04:17<02:51,  2.64it/s]
 57%|█████▋    | 600/1052 [04:18<03:02,  2.48it/s]

Checkpoint saved at 600 samples

 57%|█████▋    | 601/1052 [04:18<02:54,  2.59it/s]
 57%|█████▋    | 602/1052 [04:19<02:55,  2.56it/s]
 57%|█████▋    | 603/1052 [04:19<02:51,  2.62it/s]
 57%|█████▋    | 604/1052 [04:19<02:50,  2.63it/s]
 58%|█████▊    | 605/1052 [04:20<02:51,  2.61it/s]
 58%|█████▊    | 606/1052 [04:20<02:50,  2.61it/s]
 58%|█████▊    | 607/1052 [04:20<02:49,  2.62it/s]
 58%|█████▊    | 608/1052 [04:21<02:45,  2.68it/s]
 58%|█████▊    | 609/1052 [04:21<02:46,  2.66it/s]
 58%|█████▊    | 610/1052 [04:22<02:44,  2.68it/s]
 58%|█████▊    | 611/1052 [04:22<02:53,  2.54it/s]
 58%|█████▊    | 612/1052 [04:22<02:43,  2.68it/s]
 58%|█████▊    | 613/1052 [04:23<02:42,  2.70it/s]
 58%|█████▊    | 614/1052 [04:23<02:40,  2.72it/s]
 58%|█████▊    | 615/1052 [04:23<02:47,  2.62it/s]
 59%|█████▊    | 616/1052 [04:24<02:35,  2.80it/s]
 59%|█████▊    | 617/1052 [04:24<02:43,  2.67it/s]
 59%|█████▊    | 618/1052 [04:25<02:47,  2.59it/s]
 59%|█████▉    | 619/1052 [04:25<02:46,  2.60it/s]
 59%|█████▉    | 620/1052 [04:25<02:40,  2.70it/s]
 59%|█████▉    | 621/1052 [04:26<02:43,  2.63it/s]
 59%|█████▉    | 622/1052 [04:26<02:46,  2.58it/s]
 59%|█████▉    | 623/1052 [04:27<02:46,  2.58it/s]
 59%|█████▉    | 624/1052 [04:27<02:49,  2.53it/s]
 59%|█████▉    | 625/1052 [04:28<03:19,  2.15it/s]
 60%|█████▉    | 626/1052 [04:28<03:06,  2.29it/s]
 60%|█████▉    | 627/1052 [04:28<02:50,  2.49it/s]
 60%|█████▉    | 628/1052 [04:29<02:47,  2.54it/s]
 60%|█████▉    | 629/1052 [04:29<02:45,  2.55it/s]
 60%|█████▉    | 630/1052 [04:30<03:05,  2.28it/s]
 60%|█████▉    | 631/1052 [04:30<03:23,  2.07it/s]
 60%|██████    | 632/1052 [04:31<03:09,  2.22it/s]
 60%|██████    | 633/1052 [04:31<03:02,  2.29it/s]
 60%|██████    | 634/1052 [04:31<02:54,  2.40it/s]
 60%|██████    | 635/1052 [04:32<02:49,  2.46it/s]
 60%|██████    | 636/1052 [04:32<02:44,  2.53it/s]
 61%|██████    | 637/1052 [04:32<02:43,  2.54it/s]
 61%|██████    | 638/1052 [04:33<02:45,  2.50it/s]
 61%|██████    | 639/1052 [04:33<02:50,  2.42it/s]
 61%|██████    | 640/1052 [04:34<02:57,  2.32it/s]
 61%|██████    | 641/1052 [04:34<02:53,  2.37it/s]
 61%|██████    | 642/1052 [04:35<02:44,  2.49it/s]
 61%|██████    | 643/1052 [04:35<03:12,  2.13it/s]
 61%|██████    | 644/1052 [04:36<03:02,  2.23it/s]
 61%|██████▏   | 645/1052 [04:36<02:51,  2.37it/s]
 61%|██████▏   | 646/1052 [04:36<02:42,  2.50it/s]
 62%|██████▏   | 647/1052 [04:37<02:39,  2.55it/s]
 62%|██████▏   | 648/1052 [04:37<02:32,  2.66it/s]
 62%|██████▏   | 649/1052 [04:37<02:21,  2.85it/s]
 62%|██████▏   | 650/1052 [04:38<02:29,  2.70it/s]

Checkpoint saved at 650 samples

 62%|██████▏   | 651/1052 [04:38<02:33,  2.61it/s]
 62%|██████▏   | 652/1052 [04:39<02:42,  2.46it/s]
 62%|██████▏   | 653/1052 [04:39<02:36,  2.54it/s]
 62%|██████▏   | 654/1052 [04:39<02:29,  2.66it/s]
 62%|██████▏   | 655/1052 [04:40<02:27,  2.69it/s]
 62%|██████▏   | 656/1052 [04:40<02:23,  2.75it/s]
 62%|██████▏   | 657/1052 [04:40<02:26,  2.70it/s]
 63%|██████▎   | 658/1052 [04:41<02:38,  2.49it/s]
 63%|██████▎   | 659/1052 [04:41<02:34,  2.55it/s]
 63%|██████▎   | 660/1052 [04:42<02:28,  2.64it/s]
 63%|██████▎   | 661/1052 [04:42<02:36,  2.49it/s]
 63%|██████▎   | 662/1052 [04:42<02:34,  2.52it/s]
 63%|██████▎   | 663/1052 [04:43<02:29,  2.60it/s]
 63%|██████▎   | 664/1052 [04:43<02:33,  2.53it/s]
 63%|██████▎   | 665/1052 [04:44<02:31,  2.55it/s]
 63%|██████▎   | 666/1052 [04:44<02:28,  2.60it/s]
 63%|██████▎   | 667/1052 [04:44<02:30,  2.56it/s]
 63%|██████▎   | 668/1052 [04:45<02:27,  2.61it/s]
 64%|██████▎   | 669/1052 [04:45<02:33,  2.49it/s]
 64%|██████▎   | 670/1052 [04:46<02:35,  2.45it/s]
 64%|██████▍   | 671/1052 [04:46<02:36,  2.44it/s]
 64%|██████▍   | 672/1052 [04:47<03:07,  2.03it/s]
 64%|██████▍   | 673/1052 [04:47<02:53,  2.18it/s]
 64%|██████▍   | 674/1052 [04:47<02:44,  2.29it/s]
 64%|██████▍   | 675/1052 [04:48<02:37,  2.40it/s]
 64%|██████▍   | 676/1052 [04:48<02:34,  2.44it/s]
 64%|██████▍   | 677/1052 [04:49<02:34,  2.43it/s]
 64%|██████▍   | 678/1052 [04:49<02:26,  2.56it/s]
 65%|██████▍   | 679/1052 [04:49<02:28,  2.50it/s]
 65%|██████▍   | 680/1052 [04:50<02:27,  2.53it/s]
 65%|██████▍   | 681/1052 [04:50<02:30,  2.46it/s]
 65%|██████▍   | 682/1052 [04:51<02:31,  2.45it/s]
 65%|██████▍   | 683/1052 [04:51<02:26,  2.52it/s]
 65%|██████▌   | 684/1052 [04:51<02:22,  2.59it/s]
 65%|██████▌   | 685/1052 [04:52<02:21,  2.59it/s]
 65%|██████▌   | 686/1052 [04:52<02:23,  2.54it/s]
 65%|██████▌   | 687/1052 [04:52<02:21,  2.57it/s]
 65%|██████▌   | 688/1052 [04:53<02:21,  2.58it/s]
 65%|██████▌   | 689/1052 [04:53<02:30,  2.42it/s]
 66%|██████▌   | 690/1052 [04:54<02:20,  2.58it/s]
 66%|██████▌   | 691/1052 [04:54<02:11,  2.74it/s]
 66%|██████▌   | 692/1052 [04:54<02:15,  2.65it/s]
 66%|██████▌   | 693/1052 [04:55<02:20,  2.55it/s]
 66%|██████▌   | 694/1052 [04:55<02:18,  2.59it/s]
 66%|██████▌   | 695/1052 [04:56<02:33,  2.32it/s]
 66%|██████▌   | 696/1052 [04:56<02:28,  2.40it/s]
 66%|██████▋   | 697/1052 [04:57<02:26,  2.43it/s]
 66%|██████▋   | 698/1052 [04:57<02:39,  2.22it/s]
 66%|██████▋   | 699/1052 [04:57<02:27,  2.39it/s]
 67%|██████▋   | 700/1052 [04:58<02:23,  2.46it/s]

Checkpoint saved at 700 samples

 67%|██████▋   | 701/1052 [04:58<02:24,  2.43it/s]
 67%|██████▋   | 702/1052 [04:59<02:15,  2.59it/s]
 67%|██████▋   | 703/1052 [04:59<02:15,  2.58it/s]
 67%|██████▋   | 704/1052 [04:59<02:13,  2.60it/s]
 67%|██████▋   | 705/1052 [05:00<02:24,  2.40it/s]
 67%|██████▋   | 706/1052 [05:00<02:15,  2.55it/s]
 67%|██████▋   | 707/1052 [05:01<02:14,  2.57it/s]
 67%|██████▋   | 708/1052 [05:01<02:15,  2.54it/s]
 67%|██████▋   | 709/1052 [05:01<02:14,  2.54it/s]
 67%|██████▋   | 710/1052 [05:02<02:13,  2.56it/s]
 68%|██████▊   | 711/1052 [05:02<02:38,  2.15it/s]
 68%|██████▊   | 712/1052 [05:03<02:28,  2.29it/s]
 68%|██████▊   | 713/1052 [05:03<02:26,  2.32it/s]
 68%|██████▊   | 714/1052 [05:04<02:40,  2.11it/s]
 68%|██████▊   | 715/1052 [05:04<02:30,  2.24it/s]
 68%|██████▊   | 716/1052 [05:04<02:25,  2.32it/s]
 68%|██████▊   | 717/1052 [05:05<02:14,  2.49it/s]
 68%|██████▊   | 718/1052 [05:05<02:11,  2.54it/s]
 68%|██████▊   | 719/1052 [05:06<02:23,  2.32it/s]
 68%|██████▊   | 720/1052 [05:06<02:10,  2.55it/s]
 69%|██████▊   | 721/1052 [05:06<02:10,  2.54it/s]
 69%|██████▊   | 722/1052 [05:07<02:05,  2.64it/s]
 69%|██████▊   | 723/1052 [05:07<02:05,  2.61it/s]
 69%|██████▉   | 724/1052 [05:07<02:02,  2.68it/s]
 69%|██████▉   | 725/1052 [05:08<02:05,  2.61it/s]
 69%|██████▉   | 726/1052 [05:08<02:17,  2.38it/s]
 69%|██████▉   | 727/1052 [05:09<02:10,  2.48it/s]
 69%|██████▉   | 728/1052 [05:09<02:06,  2.55it/s]
 69%|██████▉   | 729/1052 [05:09<02:01,  2.66it/s]
 69%|██████▉   | 730/1052 [05:10<01:58,  2.71it/s]
 69%|██████▉   | 731/1052 [05:10<02:14,  2.39it/s]
 70%|██████▉   | 732/1052 [05:11<02:11,  2.44it/s]
 70%|██████▉   | 733/1052 [05:11<02:05,  2.54it/s]
 70%|██████▉   | 734/1052 [05:12<02:20,  2.26it/s]
 70%|██████▉   | 735/1052 [05:12<02:05,  2.52it/s]
 70%|██████▉   | 736/1052 [05:12<02:02,  2.59it/s]
 70%|███████   | 737/1052 [05:13<02:02,  2.57it/s]
 70%|███████   | 738/1052 [05:13<01:57,  2.67it/s]
 70%|███████   | 739/1052 [05:13<01:56,  2.69it/s]
 70%|███████   | 740/1052 [05:14<01:56,  2.68it/s]
 70%|███████   | 741/1052 [05:14<01:53,  2.75it/s]
 71%|███████   | 742/1052 [05:15<02:03,  2.52it/s]
 71%|███████   | 743/1052 [05:15<02:04,  2.48it/s]
 71%|███████   | 744/1052 [05:15<01:58,  2.59it/s]
 71%|███████   | 745/1052 [05:16<02:01,  2.52it/s]
 71%|███████   | 746/1052 [05:16<01:56,  2.64it/s]
 71%|███████   | 747/1052 [05:17<02:00,  2.54it/s]
 71%|███████   | 748/1052 [05:17<02:00,  2.53it/s]
 71%|███████   | 749/1052 [05:17<01:59,  2.54it/s]
 71%|███████▏  | 750/1052 [05:18<01:59,  2.53it/s]

Checkpoint saved at 750 samples

 71%|███████▏  | 751/1052 [05:18<01:58,  2.53it/s]
 71%|███████▏  | 752/1052 [05:19<01:58,  2.54it/s]
 72%|███████▏  | 753/1052 [05:19<01:56,  2.58it/s]
 72%|███████▏  | 754/1052 [05:19<01:53,  2.62it/s]
 72%|███████▏  | 755/1052 [05:20<01:49,  2.72it/s]
 72%|███████▏  | 756/1052 [05:20<01:46,  2.79it/s]
 72%|███████▏  | 757/1052 [05:20<01:48,  2.73it/s]
 72%|███████▏  | 758/1052 [05:21<01:54,  2.56it/s]
 72%|███████▏  | 759/1052 [05:21<01:51,  2.62it/s]
 72%|███████▏  | 760/1052 [05:22<01:52,  2.60it/s]
 72%|███████▏  | 761/1052 [05:22<01:53,  2.56it/s]
 72%|███████▏  | 762/1052 [05:22<01:51,  2.60it/s]
 73%|███████▎  | 763/1052 [05:23<01:51,  2.60it/s]
 73%|███████▎  | 764/1052 [05:23<01:54,  2.52it/s]
 73%|███████▎  | 765/1052 [05:23<01:49,  2.62it/s]
 73%|███████▎  | 766/1052 [05:24<01:50,  2.58it/s]
 73%|███████▎  | 767/1052 [05:24<01:47,  2.65it/s]
 73%|███████▎  | 768/1052 [05:25<01:47,  2.64it/s]
 73%|███████▎  | 769/1052 [05:25<01:47,  2.63it/s]
 73%|███████▎  | 770/1052 [05:25<01:44,  2.70it/s]
 73%|███████▎  | 771/1052 [05:26<01:40,  2.80it/s]
 73%|███████▎  | 772/1052 [05:26<01:43,  2.71it/s]
 73%|███████▎  | 773/1052 [05:26<01:47,  2.59it/s]
 74%|███████▎  | 774/1052 [05:27<01:48,  2.56it/s]
 74%|███████▎  | 775/1052 [05:27<01:50,  2.51it/s]
 74%|███████▍  | 776/1052 [05:28<01:53,  2.43it/s]
 74%|███████▍  | 777/1052 [05:28<01:51,  2.46it/s]
 74%|███████▍  | 778/1052 [05:29<01:49,  2.50it/s]
 74%|███████▍  | 779/1052 [05:29<01:57,  2.32it/s]
 74%|███████▍  | 780/1052 [05:29<01:49,  2.48it/s]
 74%|███████▍  | 781/1052 [05:30<01:47,  2.52it/s]
 74%|███████▍  | 782/1052 [05:30<01:43,  2.61it/s]
 74%|███████▍  | 783/1052 [05:30<01:44,  2.57it/s]
 75%|███████▍  | 784/1052 [05:31<01:39,  2.68it/s]
 75%|███████▍  | 785/1052 [05:31<01:43,  2.57it/s]
 75%|███████▍  | 786/1052 [05:32<01:44,  2.55it/s]
 75%|███████▍  | 787/1052 [05:32<01:45,  2.52it/s]
 75%|███████▍  | 788/1052 [05:32<01:43,  2.56it/s]
 75%|███████▌  | 789/1052 [05:33<01:37,  2.68it/s]
 75%|███████▌  | 790/1052 [05:33<01:37,  2.70it/s]
 75%|███████▌  | 791/1052 [05:34<02:16,  1.91it/s]
 75%|███████▌  | 792/1052 [05:34<02:03,  2.10it/s]
 75%|███████▌  | 793/1052 [05:35<01:53,  2.29it/s]
 75%|███████▌  | 794/1052 [05:35<01:54,  2.25it/s]
 76%|███████▌  | 795/1052 [05:36<01:51,  2.30it/s]
 76%|███████▌  | 796/1052 [05:36<01:47,  2.38it/s]
 76%|███████▌  | 797/1052 [05:36<01:43,  2.47it/s]
 76%|███████▌  | 798/1052 [05:37<01:37,  2.61it/s]
 76%|███████▌  | 799/1052 [05:37<01:35,  2.65it/s]
 76%|███████▌  | 800/1052 [05:37<01:35,  2.64it/s]

Checkpoint saved at 800 samples

 76%|███████▌  | 801/1052 [05:38<01:31,  2.73it/s]
 76%|███████▌  | 802/1052 [05:38<01:35,  2.63it/s]
 76%|███████▋  | 803/1052 [05:39<01:31,  2.72it/s]
 76%|███████▋  | 804/1052 [05:39<01:35,  2.58it/s]
 77%|███████▋  | 805/1052 [05:39<01:33,  2.64it/s]
 77%|███████▋  | 806/1052 [05:40<01:35,  2.57it/s]
 77%|███████▋  | 807/1052 [05:40<01:36,  2.54it/s]
 77%|███████▋  | 808/1052 [05:41<01:36,  2.52it/s]
 77%|███████▋  | 809/1052 [05:41<01:34,  2.58it/s]
 77%|███████▋  | 810/1052 [05:41<01:36,  2.51it/s]
 77%|███████▋  | 811/1052 [05:42<01:38,  2.45it/s]
 77%|███████▋  | 812/1052 [05:42<01:39,  2.40it/s]
 77%|███████▋  | 813/1052 [05:43<01:39,  2.41it/s]
 77%|███████▋  | 814/1052 [05:43<01:34,  2.51it/s]
 77%|███████▋  | 815/1052 [05:43<01:34,  2.50it/s]
 78%|███████▊  | 816/1052 [05:44<01:32,  2.56it/s]
 78%|███████▊  | 817/1052 [05:44<01:35,  2.46it/s]
 78%|███████▊  | 818/1052 [05:45<01:35,  2.46it/s]
 78%|███████▊  | 819/1052 [05:45<01:37,  2.38it/s]
 78%|███████▊  | 820/1052 [05:45<01:31,  2.54it/s]
 78%|███████▊  | 821/1052 [05:46<01:28,  2.62it/s]
 78%|███████▊  | 822/1052 [05:46<01:26,  2.67it/s]
 78%|███████▊  | 823/1052 [05:46<01:23,  2.73it/s]
 78%|███████▊  | 824/1052 [05:47<01:24,  2.70it/s]
 78%|███████▊  | 825/1052 [05:47<01:22,  2.74it/s]
 79%|███████▊  | 826/1052 [05:48<01:21,  2.76it/s]
 79%|███████▊  | 827/1052 [05:48<01:26,  2.60it/s]
 79%|███████▊  | 828/1052 [05:49<01:42,  2.19it/s]
 79%|███████▉  | 829/1052 [05:49<01:45,  2.12it/s]
 79%|███████▉  | 830/1052 [05:50<01:45,  2.11it/s]
 79%|███████▉  | 831/1052 [05:50<01:39,  2.23it/s]
 79%|███████▉  | 832/1052 [05:50<01:32,  2.38it/s]
 79%|███████▉  | 833/1052 [05:51<01:31,  2.40it/s]
 79%|███████▉  | 834/1052 [05:51<01:31,  2.38it/s]
 79%|███████▉  | 835/1052 [05:52<01:28,  2.47it/s]
 79%|███████▉  | 836/1052 [05:52<01:25,  2.52it/s]
 80%|███████▉  | 837/1052 [05:52<01:31,  2.35it/s]
 80%|███████▉  | 838/1052 [05:53<01:33,  2.30it/s]
 80%|███████▉  | 839/1052 [05:53<01:30,  2.36it/s]
 80%|███████▉  | 840/1052 [05:54<01:26,  2.45it/s]
 80%|███████▉  | 841/1052 [05:54<01:26,  2.43it/s]
 80%|████████  | 842/1052 [05:54<01:19,  2.63it/s]
 80%|████████  | 843/1052 [05:55<01:20,  2.59it/s]
 80%|████████  | 844/1052 [05:55<01:23,  2.50it/s]
 80%|████████  | 845/1052 [05:56<01:20,  2.56it/s]
 80%|████████  | 846/1052 [05:56<01:19,  2.58it/s]
 81%|████████  | 847/1052 [05:56<01:21,  2.51it/s]
 81%|████████  | 848/1052 [05:57<01:21,  2.51it/s]
 81%|████████  | 849/1052 [05:57<01:19,  2.56it/s]
 81%|████████  | 850/1052 [05:57<01:15,  2.66it/s]

Checkpoint saved at 850 samples

 81%|████████  | 851/1052 [05:58<01:13,  2.73it/s]
 81%|████████  | 852/1052 [05:58<01:10,  2.82it/s]
 81%|████████  | 853/1052 [05:59<01:12,  2.74it/s]
 81%|████████  | 854/1052 [05:59<01:22,  2.40it/s]
 81%|████████▏ | 855/1052 [05:59<01:20,  2.45it/s]
 81%|████████▏ | 856/1052 [06:00<01:19,  2.48it/s]
 81%|████████▏ | 857/1052 [06:00<01:18,  2.48it/s]
 82%|████████▏ | 858/1052 [06:01<01:16,  2.53it/s]
 82%|████████▏ | 859/1052 [06:01<01:15,  2.54it/s]
 82%|████████▏ | 860/1052 [06:01<01:15,  2.55it/s]
 82%|████████▏ | 861/1052 [06:02<01:15,  2.52it/s]
 82%|████████▏ | 862/1052 [06:02<01:12,  2.61it/s]
 82%|████████▏ | 863/1052 [06:03<01:12,  2.60it/s]
 82%|████████▏ | 864/1052 [06:03<01:13,  2.56it/s]
 82%|████████▏ | 865/1052 [06:03<01:10,  2.66it/s]
 82%|████████▏ | 866/1052 [06:04<01:10,  2.65it/s]
 82%|████████▏ | 867/1052 [06:04<01:07,  2.73it/s]
 83%|████████▎ | 868/1052 [06:04<01:10,  2.62it/s]
 83%|████████▎ | 869/1052 [06:05<01:13,  2.49it/s]
 83%|████████▎ | 870/1052 [06:05<01:14,  2.43it/s]
 83%|████████▎ | 871/1052 [06:06<01:18,  2.32it/s]
 83%|████████▎ | 872/1052 [06:06<01:14,  2.43it/s]
 83%|████████▎ | 873/1052 [06:07<01:11,  2.52it/s]
 83%|████████▎ | 874/1052 [06:07<01:09,  2.55it/s]
 83%|████████▎ | 875/1052 [06:07<01:09,  2.56it/s]
 83%|████████▎ | 876/1052 [06:08<01:04,  2.73it/s]
 83%|████████▎ | 877/1052 [06:08<01:07,  2.61it/s]
 83%|████████▎ | 878/1052 [06:08<01:04,  2.70it/s]
 84%|████████▎ | 879/1052 [06:09<00:59,  2.89it/s]
 84%|████████▎ | 880/1052 [06:09<01:02,  2.73it/s]
 84%|████████▎ | 881/1052 [06:09<01:03,  2.70it/s]
 84%|████████▍ | 882/1052 [06:10<01:02,  2.70it/s]
 84%|████████▍ | 883/1052 [06:10<01:02,  2.69it/s]
 84%|████████▍ | 884/1052 [06:11<01:06,  2.51it/s]
 84%|████████▍ | 885/1052 [06:11<01:05,  2.54it/s]
 84%|████████▍ | 886/1052 [06:11<01:04,  2.56it/s]
 84%|████████▍ | 887/1052 [06:12<01:03,  2.61it/s]
 84%|████████▍ | 888/1052 [06:12<01:02,  2.63it/s]
 85%|████████▍ | 889/1052 [06:13<01:05,  2.50it/s]
 85%|████████▍ | 890/1052 [06:13<01:01,  2.61it/s]
 85%|████████▍ | 891/1052 [06:13<01:02,  2.59it/s]
 85%|████████▍ | 892/1052 [06:14<01:01,  2.62it/s]
 85%|████████▍ | 893/1052 [06:14<01:00,  2.61it/s]
 85%|████████▍ | 894/1052 [06:14<00:57,  2.74it/s]
 85%|████████▌ | 895/1052 [06:15<00:58,  2.69it/s]
 85%|████████▌ | 896/1052 [06:15<00:59,  2.62it/s]
 85%|████████▌ | 897/1052 [06:16<00:58,  2.64it/s]
 85%|████████▌ | 898/1052 [06:16<00:56,  2.72it/s]
 85%|████████▌ | 899/1052 [06:16<00:57,  2.65it/s]
 86%|████████▌ | 900/1052 [06:17<00:56,  2.70it/s]

Checkpoint saved at 900 samples

 86%|████████▌ | 901/1052 [06:17<01:02,  2.40it/s]
 86%|████████▌ | 902/1052 [06:18<01:01,  2.42it/s]
 86%|████████▌ | 903/1052 [06:18<00:59,  2.49it/s]
 86%|████████▌ | 904/1052 [06:18<01:01,  2.41it/s]
 86%|████████▌ | 905/1052 [06:19<00:59,  2.46it/s]
 86%|████████▌ | 906/1052 [06:19<00:57,  2.52it/s]
 86%|████████▌ | 907/1052 [06:20<00:56,  2.58it/s]
 86%|████████▋ | 908/1052 [06:20<00:54,  2.63it/s]
 86%|████████▋ | 909/1052 [06:20<00:54,  2.62it/s]
 87%|████████▋ | 910/1052 [06:21<00:54,  2.62it/s]
 87%|████████▋ | 911/1052 [06:21<00:55,  2.53it/s]
 87%|████████▋ | 912/1052 [06:21<00:55,  2.53it/s]
 87%|████████▋ | 913/1052 [06:22<00:54,  2.53it/s]
 87%|████████▋ | 914/1052 [06:22<00:52,  2.63it/s]
 87%|████████▋ | 915/1052 [06:23<00:49,  2.75it/s]
 87%|████████▋ | 916/1052 [06:23<00:52,  2.60it/s]
 87%|████████▋ | 917/1052 [06:23<00:52,  2.55it/s]
 87%|████████▋ | 918/1052 [06:24<00:50,  2.63it/s]
 87%|████████▋ | 919/1052 [06:24<00:49,  2.67it/s]
 87%|████████▋ | 920/1052 [06:25<00:50,  2.64it/s]
 88%|████████▊ | 921/1052 [06:25<00:51,  2.57it/s]
 88%|████████▊ | 922/1052 [06:25<00:50,  2.59it/s]
 88%|████████▊ | 923/1052 [06:26<00:49,  2.63it/s]
 88%|████████▊ | 924/1052 [06:26<00:46,  2.78it/s]
 88%|████████▊ | 925/1052 [06:27<00:52,  2.44it/s]
 88%|████████▊ | 926/1052 [06:27<00:48,  2.62it/s]
 88%|████████▊ | 927/1052 [06:27<00:50,  2.46it/s]
 88%|████████▊ | 928/1052 [06:28<00:49,  2.52it/s]
 88%|████████▊ | 929/1052 [06:28<00:49,  2.48it/s]
 88%|████████▊ | 930/1052 [06:28<00:48,  2.54it/s]
 88%|████████▊ | 931/1052 [06:29<00:51,  2.37it/s]
 89%|████████▊ | 932/1052 [06:29<00:49,  2.43it/s]
 89%|████████▊ | 933/1052 [06:30<00:46,  2.56it/s]
 89%|████████▉ | 934/1052 [06:30<00:48,  2.43it/s]
 89%|████████▉ | 935/1052 [06:31<00:50,  2.30it/s]
 89%|████████▉ | 936/1052 [06:31<00:46,  2.48it/s]
 89%|████████▉ | 937/1052 [06:31<00:46,  2.45it/s]
 89%|████████▉ | 938/1052 [06:32<00:45,  2.48it/s]
 89%|████████▉ | 939/1052 [06:32<00:51,  2.21it/s]
 89%|████████▉ | 940/1052 [06:33<00:46,  2.42it/s]
 89%|████████▉ | 941/1052 [06:33<00:46,  2.40it/s]
 90%|████████▉ | 942/1052 [06:33<00:43,  2.51it/s]
 90%|████████▉ | 943/1052 [06:34<00:45,  2.39it/s]
 90%|████████▉ | 944/1052 [06:34<00:42,  2.54it/s]
 90%|████████▉ | 945/1052 [06:35<00:40,  2.62it/s]
 90%|████████▉ | 946/1052 [06:35<00:41,  2.58it/s]
 90%|█████████ | 947/1052 [06:35<00:39,  2.65it/s]
 90%|█████████ | 948/1052 [06:36<00:38,  2.70it/s]
 90%|█████████ | 949/1052 [06:36<00:38,  2.71it/s]
 90%|█████████ | 950/1052 [06:37<00:40,  2.51it/s]

Checkpoint saved at 950 samples

 90%|█████████ | 951/1052 [06:37<00:39,  2.53it/s]
 90%|█████████ | 952/1052 [06:37<00:40,  2.50it/s]
 91%|█████████ | 953/1052 [06:38<00:39,  2.48it/s]
 91%|█████████ | 954/1052 [06:38<00:42,  2.31it/s]
 91%|█████████ | 955/1052 [06:39<00:41,  2.32it/s]
 91%|█████████ | 956/1052 [06:39<00:39,  2.40it/s]
 91%|█████████ | 957/1052 [06:39<00:39,  2.43it/s]
 91%|█████████ | 958/1052 [06:40<00:37,  2.53it/s]
 91%|█████████ | 959/1052 [06:40<00:36,  2.53it/s]
 91%|█████████▏| 960/1052 [06:41<00:37,  2.47it/s]
 91%|█████████▏| 961/1052 [06:41<00:39,  2.32it/s]
 91%|█████████▏| 962/1052 [06:41<00:37,  2.40it/s]
 92%|█████████▏| 963/1052 [06:42<00:36,  2.43it/s]
 92%|█████████▏| 964/1052 [06:42<00:37,  2.34it/s]
 92%|█████████▏| 965/1052 [06:43<00:37,  2.29it/s]
 92%|█████████▏| 966/1052 [06:43<00:38,  2.24it/s]
 92%|█████████▏| 967/1052 [06:44<00:39,  2.17it/s]
 92%|█████████▏| 968/1052 [06:44<00:37,  2.22it/s]
 92%|█████████▏| 969/1052 [06:45<00:34,  2.39it/s]
 92%|█████████▏| 970/1052 [06:45<00:34,  2.39it/s]
 92%|█████████▏| 971/1052 [06:45<00:35,  2.28it/s]
 92%|█████████▏| 972/1052 [06:46<00:33,  2.40it/s]
 92%|█████████▏| 973/1052 [06:46<00:31,  2.53it/s]
 93%|█████████▎| 974/1052 [06:46<00:28,  2.74it/s]
 93%|█████████▎| 975/1052 [06:47<00:29,  2.64it/s]
 93%|█████████▎| 976/1052 [06:47<00:30,  2.52it/s]
 93%|█████████▎| 977/1052 [06:48<00:29,  2.57it/s]
 93%|█████████▎| 978/1052 [06:48<00:31,  2.38it/s]
 93%|█████████▎| 979/1052 [06:49<00:29,  2.49it/s]
 93%|█████████▎| 980/1052 [06:49<00:29,  2.42it/s]
 93%|█████████▎| 981/1052 [06:49<00:27,  2.58it/s]
 93%|█████████▎| 982/1052 [06:50<00:26,  2.60it/s]
 93%|█████████▎| 983/1052 [06:50<00:25,  2.73it/s]
 94%|█████████▎| 984/1052 [06:50<00:24,  2.77it/s]
 94%|█████████▎| 985/1052 [06:51<00:23,  2.81it/s]
 94%|█████████▎| 986/1052 [06:51<00:23,  2.78it/s]
 94%|█████████▍| 987/1052 [06:51<00:24,  2.70it/s]
 94%|█████████▍| 988/1052 [06:52<00:23,  2.68it/s]
 94%|█████████▍| 989/1052 [06:52<00:23,  2.73it/s]
 94%|█████████▍| 990/1052 [06:53<00:23,  2.66it/s]
 94%|█████████▍| 991/1052 [06:53<00:24,  2.53it/s]
 94%|█████████▍| 992/1052 [06:53<00:23,  2.57it/s]
 94%|█████████▍| 993/1052 [06:54<00:23,  2.55it/s]
 94%|█████████▍| 994/1052 [06:54<00:24,  2.32it/s]
 95%|█████████▍| 995/1052 [06:55<00:24,  2.36it/s]
 95%|█████████▍| 996/1052 [06:55<00:21,  2.57it/s]
 95%|█████████▍| 997/1052 [06:55<00:21,  2.60it/s]
 95%|█████████▍| 998/1052 [06:56<00:20,  2.64it/s]
 95%|█████████▍| 999/1052 [06:56<00:20,  2.61it/s]
 95%|█████████▌| 1000/1052 [06:57<00:20,  2.55it/s]

Checkpoint saved at 1000 samples

 95%|█████████▌| 1001/1052 [06:57<00:19,  2.56it/s]
 95%|█████████▌| 1002/1052 [06:57<00:20,  2.48it/s]
 95%|█████████▌| 1003/1052 [06:58<00:19,  2.54it/s]
 95%|█████████▌| 1004/1052 [06:58<00:19,  2.43it/s]
 96%|█████████▌| 1005/1052 [06:59<00:18,  2.50it/s]
 96%|█████████▌| 1006/1052 [06:59<00:17,  2.62it/s]
 96%|█████████▌| 1007/1052 [06:59<00:17,  2.65it/s]
 96%|█████████▌| 1008/1052 [07:00<00:16,  2.64it/s]
 96%|█████████▌| 1009/1052 [07:00<00:18,  2.34it/s]
 96%|█████████▌| 1010/1052 [07:01<00:17,  2.46it/s]
 96%|█████████▌| 1011/1052 [07:01<00:16,  2.54it/s]
 96%|█████████▌| 1012/1052 [07:01<00:15,  2.60it/s]
 96%|█████████▋| 1013/1052 [07:02<00:15,  2.58it/s]
 96%|█████████▋| 1014/1052 [07:02<00:14,  2.56it/s]
 96%|█████████▋| 1015/1052 [07:02<00:14,  2.62it/s]
 97%|█████████▋| 1016/1052 [07:03<00:13,  2.69it/s]
 97%|█████████▋| 1017/1052 [07:03<00:12,  2.78it/s]
 97%|█████████▋| 1018/1052 [07:04<00:12,  2.64it/s]
 97%|█████████▋| 1019/1052 [07:04<00:12,  2.60it/s]
 97%|█████████▋| 1020/1052 [07:04<00:12,  2.61it/s]
 97%|█████████▋| 1021/1052 [07:05<00:12,  2.56it/s]
 97%|█████████▋| 1022/1052 [07:05<00:11,  2.69it/s]
 97%|█████████▋| 1023/1052 [07:05<00:10,  2.78it/s]
 97%|█████████▋| 1024/1052 [07:06<00:10,  2.68it/s]
 97%|█████████▋| 1025/1052 [07:06<00:10,  2.69it/s]
 98%|█████████▊| 1026/1052 [07:07<00:10,  2.56it/s]
 98%|█████████▊| 1027/1052 [07:07<00:09,  2.73it/s]
 98%|█████████▊| 1028/1052 [07:07<00:08,  2.78it/s]
 98%|█████████▊| 1029/1052 [07:08<00:08,  2.82it/s]
 98%|█████████▊| 1030/1052 [07:08<00:07,  2.81it/s]
 98%|█████████▊| 1031/1052 [07:08<00:07,  2.91it/s]
 98%|█████████▊| 1032/1052 [07:09<00:07,  2.58it/s]
 98%|█████████▊| 1033/1052 [07:09<00:07,  2.63it/s]
 98%|█████████▊| 1034/1052 [07:10<00:07,  2.39it/s]
 98%|█████████▊| 1035/1052 [07:10<00:06,  2.44it/s]
 98%|█████████▊| 1036/1052 [07:10<00:06,  2.60it/s]
 99%|█████████▊| 1037/1052 [07:11<00:05,  2.62it/s]
 99%|█████████▊| 1038/1052 [07:11<00:05,  2.66it/s]
 99%|█████████▉| 1039/1052 [07:12<00:05,  2.47it/s]
 99%|█████████▉| 1040/1052 [07:12<00:05,  2.39it/s]
 99%|█████████▉| 1041/1052 [07:13<00:04,  2.27it/s]
 99%|█████████▉| 1042/1052 [07:13<00:04,  2.26it/s]
 99%|█████████▉| 1043/1052 [07:13<00:03,  2.38it/s]
 99%|█████████▉| 1044/1052 [07:14<00:03,  2.46it/s]
 99%|█████████▉| 1045/1052 [07:14<00:02,  2.51it/s]
 99%|█████████▉| 1046/1052 [07:14<00:02,  2.59it/s]
100%|█████████▉| 1047/1052 [07:15<00:02,  2.44it/s]
100%|█████████▉| 1048/1052 [07:15<00:01,  2.37it/s]
100%|█████████▉| 1049/1052 [07:16<00:01,  2.24it/s]
100%|█████████▉| 1050/1052 [07:16<00:00,  2.30it/s]

Checkpoint saved at 1050 samples

100%|█████████▉| 1051/1052 [07:17<00:00,  2.32it/s]
100%|██████████| 1052/1052 [07:17<00:00,  2.40it/s]

================ BENCHMARK RESULTS ================

Model: wav2vec2-large-xlsr-persian-v3
Samples: 1052
WER: 0.1704
CER: 0.0443
RTF: 0.0835
Average latency: 0.4161 sec
Total inference time: 437.69 sec
Total audio duration: 5241.78 sec
Peak GPU memory: 1.38 GB

===================================================

Detailed results saved to:
/content/drive/MyDrive/asr_project/wav2vec2_persian_v3_results.csv
Summary saved.

### FLEURS Evaluation

### w2vec

In [ ]:
from google.colab import drive
from pathlib import Path
import os

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")
else:
    print("Google Drive already mounted.")

BASE_DIR = Path(
    "/content/drive/MyDrive/persian_asr_llm_error_propagation"
)

DATA_DIR = BASE_DIR / "data"

ASR_COMPARE_DIR = BASE_DIR / "asr_comparison"

ASR_COMPARE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TSV_PATH = DATA_DIR / "test.tsv"

print("TSV:", TSV_PATH)
print("Exists:", TSV_PATH.exists())

Google Drive already mounted.
TSV: /content/drive/MyDrive/persian_asr_llm_error_propagation/data/test.tsv
Exists: True

In [ ]:
!pip install -q transformers accelerate soundfile librosa tqdm

In [ ]:
import os
import time
import hashlib
import unicodedata

import numpy as np
import pandas as pd
import soundfile as sf
import librosa
import torch

from tqdm.auto import tqdm

from transformers import (
    Wav2Vec2Processor,
    Wav2Vec2ForCTC,
)

In [ ]:
COLUMNS = [
    "id",
    "file_name",
    "raw_transcription",
    "transcription",
    "character_transcription",
    "num_samples",
    "gender",
]

df = pd.read_csv(
    TSV_PATH,
    sep="\t",
    header=None,
    names=COLUMNS,
)

print("Rows:", len(df))
print("Unique files:", df["file_name"].nunique())
print("Unique semantic IDs:", df["id"].nunique())

display(df.head())

Rows: 871
Unique files: 871
Unique semantic IDs: 324

,id,file_name,raw_transcription,transcription,character_transcription,num_samples,gender
0,1735,7913564082410055971.wav,محققان دانشگاه پرینستون آمریكا و دانشگاه اوپسا...,محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسا...,م ح ق ق ا ن | د ا ن ش گ ا ه | پ ر ی ن س ت و ن ...,518400,MALE
1,1720,621633057978356932.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,193920,MALE
2,1720,13180061520623477685.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,205440,MALE
3,1720,16484235889057265269.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,223680,MALE
4,1955,17985233135634044314.wav,MS نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,ms نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,m s | ن و ع ی | ب ی م ا ر ی | ا س ت | ک ه | ب ...,218880,MALE

In [ ]:
wav_files = list(
    DATA_DIR.rglob("*.wav")
)

print("WAV files found:", len(wav_files))

for p in wav_files[:5]:
    print(p)

WAV files found: 871
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/7099844447178454280.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/13720237503121452158.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/7557020602592715699.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/11242877790416358060.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/5039781156427225122.wav

In [ ]:
wav_map = {}

duplicates = []

for p in wav_files:

    if p.name in wav_map:
        duplicates.append(p.name)

    wav_map[p.name] = str(p)

print("Unique WAV filenames:", len(wav_map))
print("Duplicate filenames:", len(set(duplicates)))

Unique WAV filenames: 871
Duplicate filenames: 0

In [ ]:
df["audio_path"] = (
    df["file_name"]
    .map(wav_map)
)

missing = (
    df["audio_path"]
    .isna()
    .sum()
)

print("Matched audio:", df["audio_path"].notna().sum())
print("Missing audio:", missing)

assert len(df) == 871
assert df["file_name"].nunique() == 871
assert missing == 0

print("All 871 FLEURS recordings mapped successfully.")

Matched audio: 871
Missing audio: 0
All 871 FLEURS recordings mapped successfully.

In [ ]:
audio_info = []

for audio_path in df["audio_path"]:

    info = sf.info(
        audio_path
    )

    audio_info.append({
        "file_name": Path(audio_path).name,
        "sample_rate": info.samplerate,
        "channels": info.channels,
        "subtype": info.subtype,
        "duration": info.duration,
    })

audio_info_df = pd.DataFrame(
    audio_info
)

print("Sample rates:")
print(
    audio_info_df[
        "sample_rate"
    ].value_counts()
)

print("\nChannels:")
print(
    audio_info_df[
        "channels"
    ].value_counts()
)

print("\nWAV subtype:")
print(
    audio_info_df[
        "subtype"
    ].value_counts()
)

Sample rates:
sample_rate
16000    871
Name: count, dtype: int64

Channels:
channels
1    871
Name: count, dtype: int64

WAV subtype:
subtype
FLOAT    871
Name: count, dtype: int64

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:

    if text is None:
        return ""

    text = str(text)

    # Unicode normalization FIRST
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    # remove hashtags
    text = " ".join(
        w
        for w in text.split()
        if not w.startswith("#")
    )

    # character replacements
    for k, v in REPLACEMENTS.items():
        text = text.replace(
            k,
            v
        )

    # remove punctuation
    for tok in DISCARD:
        text = text.replace(
            tok,
            " "
        )

    # remove Arabic standalone hamza
    text = text.replace(
        "ء",
        ""
    )

    # collapse whitespace
    text = " ".join(
        text.split()
    )

    return text

In [ ]:
def _alignment_error_rate(
    reference,
    hypothesis,
):

    n = len(reference)
    m = len(hypothesis)

    dp = [
        [0] * (m + 1)
        for _ in range(n + 1)
    ]

    ops = [
        [None] * (m + 1)
        for _ in range(n + 1)
    ]

    for i in range(1, n + 1):
        dp[i][0] = i
        ops[i][0] = "D"

    for j in range(1, m + 1):
        dp[0][j] = j
        ops[0][j] = "I"

    for i in range(
        1,
        n + 1
    ):

        for j in range(
            1,
            m + 1
        ):

            if (
                reference[i - 1]
                == hypothesis[j - 1]
            ):

                dp[i][j] = (
                    dp[i - 1][j - 1]
                )

                ops[i][j] = "C"

            else:

                sub = (
                    dp[i - 1][j - 1]
                    + 1
                )

                delete = (
                    dp[i - 1][j]
                    + 1
                )

                insert = (
                    dp[i][j - 1]
                    + 1
                )

                best = min(
                    sub,
                    delete,
                    insert
                )

                dp[i][j] = best

                if best == sub:
                    ops[i][j] = "S"

                elif best == delete:
                    ops[i][j] = "D"

                else:
                    ops[i][j] = "I"

    i = n
    j = m

    substitutions = 0
    deletions = 0
    insertions = 0

    while i > 0 or j > 0:

        op = ops[i][j]

        if op == "C":

            i -= 1
            j -= 1

        elif op == "S":

            substitutions += 1

            i -= 1
            j -= 1

        elif op == "D":

            deletions += 1
            i -= 1

        elif op == "I":

            insertions += 1
            j -= 1

        else:

            break

    errors = (
        substitutions
        + deletions
        + insertions
    )

    error_rate = (
        errors / n
        if n > 0
        else float(errors > 0)
    )

    return (
        error_rate,
        substitutions,
        deletions,
        insertions,
        n,
    )

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):

    total_word_sub = 0
    total_word_del = 0
    total_word_ins = 0
    total_words = 0

    total_char_sub = 0
    total_char_del = 0
    total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(
        df[ref_col],
        df[hyp_col]
    ):

        ref = (
            ""
            if pd.isna(ref)
            else str(ref)
        )

        hyp = (
            ""
            if pd.isna(hyp)
            else str(hyp)
        )

        _, s, d, i, n = (
            _alignment_error_rate(
                ref.split(),
                hyp.split()
            )
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = (
            _alignment_error_rate(
                list(
                    ref.replace(
                        " ",
                        ""
                    )
                ),
                list(
                    hyp.replace(
                        " ",
                        ""
                    )
                )
            )
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub
        + total_word_del
        + total_word_ins
    ) / max(
        1,
        total_words
    )

    cer = (
        total_char_sub
        + total_char_del
        + total_char_ins
    ) / max(
        1,
        total_chars
    )

    return {
        "WER": wer,
        "CER": cer,

        "word_sub":
            total_word_sub,

        "word_del":
            total_word_del,

        "word_ins":
            total_word_ins,

        "char_sub":
            total_char_sub,

        "char_del":
            total_char_del,

        "char_ins":
            total_char_ins,

        "total_words":
            total_words,

        "total_chars":
            total_chars,
    }

In [ ]:
MODEL_NAME = (
    "m3hrdadfi/"
    "wav2vec2-large-xlsr-persian-v3"
)

processor = (
    Wav2Vec2Processor
    .from_pretrained(
        MODEL_NAME
    )
)

model = (
    Wav2Vec2ForCTC
    .from_pretrained(
        MODEL_NAME
    )
)

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

model = model.to(
    device
)

model.eval()

print(
    "Using device:",
    device
)

print(
    "Processor sample rate:",
    processor.feature_extractor.sampling_rate
)

print(
    "Model:",
    MODEL_NAME
)

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

Using device: cuda
Processor sample rate: 16000
Model: m3hrdadfi/wav2vec2-large-xlsr-persian-v3

In [ ]:
assert (
    processor
    .feature_extractor
    .sampling_rate
    == 16000
)

In [ ]:
def transcribe_wav2vec2(
    audio_path,
    processor,
    model,
    device,
):

    audio, sr = sf.read(
        audio_path,
        dtype="float32"
    )

    # Stereo -> mono only if required
    if audio.ndim > 1:

        audio = np.mean(
            audio,
            axis=1
        )

    target_sr = (
        processor
        .feature_extractor
        .sampling_rate
    )

    # Normally not triggered for FLEURS
    if sr != target_sr:

        audio = librosa.resample(
            audio,
            orig_sr=sr,
            target_sr=target_sr
        )

        sr = target_sr

    inputs = processor(
        audio,
        sampling_rate=sr,
        return_tensors="pt",
    )

    input_values = (
        inputs.input_values
        .to(device)
    )

    with torch.inference_mode():

        logits = model(
            input_values
        ).logits

    predicted_ids = torch.argmax(
        logits,
        dim=-1
    )

    prediction = (
        processor
        .batch_decode(
            predicted_ids
        )[0]
    )

    return prediction.strip()

In [ ]:
test_row = df.iloc[0]

test_prediction = (
    transcribe_wav2vec2(
        test_row["audio_path"],
        processor,
        model,
        device,
    )
)

print("REFERENCE:")
print(
    test_row["transcription"]
)

print("\nWAV2VEC2:")
print(
    test_prediction
)

print("\nNORMALIZED REFERENCE:")
print(
    nemo_paper_normalize(
        test_row["transcription"]
    )
)

print("\nNORMALIZED HYPOTHESIS:")
print(
    nemo_paper_normalize(
        test_prediction
    )
)

REFERENCE:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید تکامل یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینی متوسط و سهره کاکتوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید

WAV2VEC2:
محققان دانشگاه پرینستون آمریکا و دانشگاه ابسال‌ها در سوئد گونه‌های جدید جدید تکاملیافته ای را تن‌ها در دو نسل گزارش دادند اگر چه اعتقاد بر این بود که به دلیل لذات و ولد بین یک سهره دارین بومی صهره زمینی متوسط و سهره کاکوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیش‌تر طول کشید

NORMALIZED REFERENCE:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید تکامل یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینی متوسط و سهره کاکتوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید

NORMALIZED HYPOTHESIS:
محققان دانشگاه پرینستون آمریکا و دانشگاه ابسال‌ها در سوئد گونه‌های جدید جدید تکاملیافته ای را تن‌ها در دو نسل گزارش دادند اگر چه اعتقاد بر این بود که به دلیل لذات و ولد بین یک سهره دارین بومی صهره زمینی متوسط و سهره کاکوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیش‌تر طول کشید

In [ ]:
W2V_RESULTS_DIR = (
    ASR_COMPARE_DIR
    / "wav2vec2_large_xlsr_persian_v3"
)

W2V_RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

CHECKPOINT_PATH_W2V = (
    W2V_RESULTS_DIR
    / "wav2vec2_fleurs_checkpoint.csv"
)

FINAL_PATH_W2V = (
    W2V_RESULTS_DIR
    / "wav2vec2_fleurs_results_v1.csv"
)

SUMMARY_PATH_W2V = (
    W2V_RESULTS_DIR
    / "wav2vec2_fleurs_summary_v1.csv"
)

print(
    "Checkpoint:",
    CHECKPOINT_PATH_W2V
)

print(
    "Final:",
    FINAL_PATH_W2V
)

print(
    "Summary:",
    SUMMARY_PATH_W2V
)

Checkpoint: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/wav2vec2_large_xlsr_persian_v3/wav2vec2_fleurs_checkpoint.csv
Final: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/wav2vec2_large_xlsr_persian_v3/wav2vec2_fleurs_results_v1.csv
Summary: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/wav2vec2_large_xlsr_persian_v3/wav2vec2_fleurs_summary_v1.csv

In [ ]:
def atomic_save_result_map(
    result_map,
    path,
):

    checkpoint_df = pd.DataFrame(
        list(
            result_map.values()
        )
    )

    if len(checkpoint_df):

        checkpoint_df = (
            checkpoint_df
            .sort_values(
                [
                    "id",
                    "file_name"
                ]
            )
            .reset_index(
                drop=True
            )
        )

    tmp_path = (
        str(path)
        + ".tmp"
    )

    checkpoint_df.to_csv(
        tmp_path,
        index=False,
        encoding="utf-8-sig"
    )

    os.replace(
        tmp_path,
        path
    )

In [ ]:
w2v_results = {}

if CHECKPOINT_PATH_W2V.exists():

    previous_df = pd.read_csv(
        CHECKPOINT_PATH_W2V
    )

    for _, row in previous_df.iterrows():

        w2v_results[
            str(row["file_name"])
        ] = row.to_dict()

    print(
        "Checkpoint rows loaded:",
        len(w2v_results)
    )

else:

    print(
        "No existing Wav2Vec2 checkpoint."
    )

No existing Wav2Vec2 checkpoint.

In [ ]:
processed_w2v = {
    file_name
    for file_name, row
    in w2v_results.items()
    if row.get("status") == "ok"
}

print(
    "Already successful:",
    len(processed_w2v)
)

Already successful: 0

In [ ]:
for idx in tqdm(
    range(len(df)),
    desc="Wav2Vec2 FLEURS"
):

    row = df.iloc[idx]

    file_name = str(
        row["file_name"]
    )

    if file_name in processed_w2v:
        continue

    audio_path = (
        row["audio_path"]
    )

    try:

        info = sf.info(
            audio_path
        )

        duration = (
            info.duration
        )

        # CUDA operations are asynchronous,
        # so synchronize for valid timing.
        if device == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        pred_text = (
            transcribe_wav2vec2(
                audio_path,
                processor,
                model,
                device,
            )
        )

        if device == "cuda":
            torch.cuda.synchronize()

        inference_time = (
            time.perf_counter()
            - t0
        )

        w2v_results[
            file_name
        ] = {

            "id":
                int(row["id"]),

            "file_name":
                file_name,

            "audio_path":
                audio_path,

            "gender":
                row["gender"],

            "audio_duration":
                duration,

            "reference_raw":
                row[
                    "raw_transcription"
                ],

            # Official FLEURS reference
            # used for scoring
            "reference_normalized":
                row[
                    "transcription"
                ],

            "prediction_raw":
                pred_text,

            "inference_time":
                inference_time,

            "rtf": (
                inference_time
                / duration
                if duration > 0
                else None
            ),

            "status":
                "ok",

            "error":
                "",
        }

        processed_w2v.add(
            file_name
        )

    except Exception as e:

        w2v_results[
            file_name
        ] = {

            "id":
                int(row["id"]),

            "file_name":
                file_name,

            "audio_path":
                audio_path,

            "gender":
                row["gender"],

            "audio_duration":
                None,

            "reference_raw":
                row[
                    "raw_transcription"
                ],

            "reference_normalized":
                row[
                    "transcription"
                ],

            "prediction_raw":
                "",

            "inference_time":
                None,

            "rtf":
                None,

            "status":
                "error",

            "error":
                repr(e),
        }

        print(
            f"\nFAILED: {file_name}"
        )

        print(e)

    # Save after every recording
    atomic_save_result_map(
        w2v_results,
        CHECKPOINT_PATH_W2V
    )

Wav2Vec2 FLEURS:   0%|          | 0/871 [00:00<?, ?it/s]

In [ ]:
w2v_df = pd.read_csv(
    CHECKPOINT_PATH_W2V
)

print(
    "Checkpoint rows:",
    len(w2v_df)
)

print()

print(
    w2v_df[
        "status"
    ].value_counts(
        dropna=False
    )
)

Checkpoint rows: 871

status
ok    871
Name: count, dtype: int64

In [ ]:
w2v_sub = (
    w2v_df[
        w2v_df["status"]
        == "ok"
    ]
    .copy()
)

print(
    "Successful:",
    len(w2v_sub)
)

print(
    "Failed:",
    len(w2v_df)
    - len(w2v_sub)
)

print(
    "Unique files:",
    w2v_sub[
        "file_name"
    ].nunique()
)

Successful: 871
Failed: 0
Unique files: 871

In [ ]:
w2v_sub["hyp_norm"] = (
    w2v_sub[
        "prediction_raw"
    ]
    .apply(
        nemo_paper_normalize
    )
)

w2v_sub["ref_norm"] = (
    w2v_sub[
        "reference_normalized"
    ]
    .apply(
        nemo_paper_normalize
    )
)

In [ ]:
display(
    w2v_sub[
        [
            "reference_normalized",
            "prediction_raw",
            "ref_norm",
            "hyp_norm",
        ]
    ].head()
)

,reference_normalized,prediction_raw,ref_norm,hyp_norm
0,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رمانتیسم اثر عزیمی از جعبگرایی فرهنگی داشت که ...,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رمانتیسم اثر عزیمی از جعبگرایی فرهنگی داشت که ...
1,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رمان‌تیسم آنسل عظیمی از جبلگرای فرهنگی داشت که...,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رمان‌تیسم آنسل عظیمی از جبلگرای فرهنگی داشت که...
2,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی را برای این کاهش‌ها تعاییم نکرد و گفت ...,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی را برای این کاهش‌ها تعاییم نکرد و گفت ...
3,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رغمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رغمی برای این کاهش‌ها تعیین نکرد و گفت که ب...
4,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رغمی برای این کاهش‌ها تغییر تعیین نکرد و گف...,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رغمی برای این کاهش‌ها تغییر تعیین نکرد و گف...

In [ ]:
w2v_metrics = (
    compute_dataset_wer_cer(
        w2v_sub,
        ref_col="ref_norm",
        hyp_col="hyp_norm",
    )
)

print(
    w2v_metrics
)

{'WER': 0.2955755735828398, 'CER': 0.09038918063448673, 'word_sub': 4462, 'word_del': 467, 'word_ins': 1010, 'char_sub': 2703, 'char_del': 2043, 'char_ins': 2793, 'total_words': 20093, 'total_chars': 83406}

In [ ]:
print(
    f"Samples: {len(w2v_sub)}"
)

print(
    f"WER: {w2v_metrics['WER']:.6f}"
)

print(
    f"CER: {w2v_metrics['CER']:.6f}"
)

print(
    f"WER (%): "
    f"{w2v_metrics['WER'] * 100:.2f}%"
)

print(
    f"CER (%): "
    f"{w2v_metrics['CER'] * 100:.2f}%"
)

Samples: 871
WER: 0.295576
CER: 0.090389
WER (%): 29.56%
CER (%): 9.04%

In [ ]:
def compute_row_error_rates(
    row
):

    ref = (
        ""
        if pd.isna(
            row["ref_norm"]
        )
        else str(
            row["ref_norm"]
        )
    )

    hyp = (
        ""
        if pd.isna(
            row["hyp_norm"]
        )
        else str(
            row["hyp_norm"]
        )
    )

    wer, _, _, _, _ = (
        _alignment_error_rate(
            ref.split(),
            hyp.split()
        )
    )

    cer, _, _, _, _ = (
        _alignment_error_rate(
            list(
                ref.replace(
                    " ",
                    ""
                )
            ),
            list(
                hyp.replace(
                    " ",
                    ""
                )
            )
        )
    )

    return pd.Series({
        "wer": wer,
        "cer": cer,
    })

In [ ]:
w2v_sub[
    [
        "wer",
        "cer"
    ]
] = w2v_sub.apply(
    compute_row_error_rates,
    axis=1
)

In [ ]:
w2v_summary_df = pd.DataFrame([
    {
        "Samples":
            len(w2v_sub),

        "WER":
            w2v_metrics[
                "WER"
            ],

        "CER":
            w2v_metrics[
                "CER"
            ],
    }
])

display(
    w2v_summary_df
)

   Samples       WER       CER
0      871  0.295576  0.090389

In [ ]:
assert len(w2v_sub) == 871

assert (
    w2v_sub[
        "file_name"
    ].nunique()
    == 871
)

w2v_sub = (
    w2v_sub
    .sort_values(
        [
            "id",
            "file_name"
        ]
    )
    .reset_index(
        drop=True
    )
)

w2v_sub.to_csv(
    FINAL_PATH_W2V,
    index=False,
    encoding="utf-8-sig"
)

w2v_summary_df.to_csv(
    SUMMARY_PATH_W2V,
    index=False,
    encoding="utf-8-sig"
)

print(
    "Final predictions:",
    FINAL_PATH_W2V
)

print(
    "Summary:",
    SUMMARY_PATH_W2V
)

Final predictions: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/wav2vec2_large_xlsr_persian_v3/wav2vec2_fleurs_results_v1.csv
Summary: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/wav2vec2_large_xlsr_persian_v3/wav2vec2_fleurs_summary_v1.csv

In [ ]:
def sha256_file(
    path
):

    h = hashlib.sha256()

    with open(
        path,
        "rb"
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):

            h.update(
                chunk
            )

    return h.hexdigest()

In [ ]:
print(
    "Prediction SHA-256:"
)

print(
    sha256_file(
        FINAL_PATH_W2V
    )
)

print()

print(
    "Summary SHA-256:"
)

print(
    sha256_file(
        SUMMARY_PATH_W2V
    )
)

Prediction SHA-256:
020926d6edc7b1f5f4d20cf2c4a11b731c04f6119214e47626aa56dcb12c0505

Summary SHA-256:
2eda9373b0ba091396b388eec4e341657b98c076177130b0cbc088b92dd56c29

In [ ]:
print(
    w2v_summary_df
)

print()

print(
    w2v_metrics
)

   Samples       WER       CER
0      871  0.295576  0.090389

{'WER': 0.2955755735828398, 'CER': 0.09038918063448673, 'word_sub': 4462, 'word_del': 467, 'word_ins': 1010, 'char_sub': 2703, 'char_del': 2043, 'char_ins': 2793, 'total_words': 20093, 'total_chars': 83406}

### Whisper

In [ ]:
!pip install -q -U openai-whisper
!pip install -q soundfile librosa pandas tqdm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 39.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for openai-whisper (pyproject.toml) ... done

In [ ]:
import os
import time
import hashlib
import unicodedata

import numpy as np
import pandas as pd
import soundfile as sf
import librosa
import torch
import whisper

from tqdm.auto import tqdm

In [ ]:
COLUMNS = [
    "id",
    "file_name",
    "raw_transcription",
    "transcription",
    "character_transcription",
    "num_samples",
    "gender",
]

df = pd.read_csv(
    TSV_PATH,
    sep="\t",
    header=None,
    names=COLUMNS,
)

print("Rows:", len(df))
print("Unique files:", df["file_name"].nunique())
print("Unique semantic IDs:", df["id"].nunique())

display(df.head())

Rows: 871
Unique files: 871
Unique semantic IDs: 324

,id,file_name,raw_transcription,transcription,character_transcription,num_samples,gender
0,1735,7913564082410055971.wav,محققان دانشگاه پرینستون آمریكا و دانشگاه اوپسا...,محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسا...,م ح ق ق ا ن | د ا ن ش گ ا ه | پ ر ی ن س ت و ن ...,518400,MALE
1,1720,621633057978356932.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,193920,MALE
2,1720,13180061520623477685.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,205440,MALE
3,1720,16484235889057265269.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,223680,MALE
4,1955,17985233135634044314.wav,MS نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,ms نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,m s | ن و ع ی | ب ی م ا ر ی | ا س ت | ک ه | ب ...,218880,MALE

In [ ]:
df["audio_path"] = (
    df["file_name"]
    .map(wav_map)
)

missing = (
    df["audio_path"]
    .isna()
    .sum()
)

print(
    "Matched:",
    df["audio_path"].notna().sum()
)

print(
    "Missing:",
    missing
)

assert len(df) == 871
assert df["file_name"].nunique() == 871
assert missing == 0

print(
    "All 871 recordings mapped."
)

Matched: 871
Missing: 0
All 871 recordings mapped.

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:

    if text is None:
        return ""

    text = str(text)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = " ".join(
        w
        for w in text.split()
        if not w.startswith("#")
    )

    for k, v in REPLACEMENTS.items():

        text = text.replace(
            k,
            v
        )

    for tok in DISCARD:

        text = text.replace(
            tok,
            " "
        )

    text = text.replace(
        "ء",
        ""
    )

    text = " ".join(
        text.split()
    )

    return text

In [ ]:
def _alignment_error_rate(
    reference,
    hypothesis,
):

    n = len(reference)
    m = len(hypothesis)

    dp = [
        [0] * (m + 1)
        for _ in range(n + 1)
    ]

    ops = [
        [None] * (m + 1)
        for _ in range(n + 1)
    ]

    for i in range(1, n + 1):

        dp[i][0] = i
        ops[i][0] = "D"

    for j in range(1, m + 1):

        dp[0][j] = j
        ops[0][j] = "I"

    for i in range(1, n + 1):

        for j in range(1, m + 1):

            if (
                reference[i - 1]
                == hypothesis[j - 1]
            ):

                dp[i][j] = (
                    dp[i - 1][j - 1]
                )

                ops[i][j] = "C"

            else:

                sub = (
                    dp[i - 1][j - 1]
                    + 1
                )

                delete = (
                    dp[i - 1][j]
                    + 1
                )

                insert = (
                    dp[i][j - 1]
                    + 1
                )

                best = min(
                    sub,
                    delete,
                    insert
                )

                dp[i][j] = best

                if best == sub:
                    ops[i][j] = "S"

                elif best == delete:
                    ops[i][j] = "D"

                else:
                    ops[i][j] = "I"

    i = n
    j = m

    substitutions = 0
    deletions = 0
    insertions = 0

    while i > 0 or j > 0:

        op = ops[i][j]

        if op == "C":

            i -= 1
            j -= 1

        elif op == "S":

            substitutions += 1
            i -= 1
            j -= 1

        elif op == "D":

            deletions += 1
            i -= 1

        elif op == "I":

            insertions += 1
            j -= 1

        else:

            break

    errors = (
        substitutions
        + deletions
        + insertions
    )

    error_rate = (
        errors / n
        if n > 0
        else float(errors > 0)
    )

    return (
        error_rate,
        substitutions,
        deletions,
        insertions,
        n,
    )

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):

    total_word_sub = 0
    total_word_del = 0
    total_word_ins = 0
    total_words = 0

    total_char_sub = 0
    total_char_del = 0
    total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(
        df[ref_col],
        df[hyp_col]
    ):

        ref = (
            ""
            if pd.isna(ref)
            else str(ref)
        )

        hyp = (
            ""
            if pd.isna(hyp)
            else str(hyp)
        )

        _, s, d, i, n = (
            _alignment_error_rate(
                ref.split(),
                hyp.split()
            )
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = (
            _alignment_error_rate(
                list(
                    ref.replace(
                        " ",
                        ""
                    )
                ),
                list(
                    hyp.replace(
                        " ",
                        ""
                    )
                )
            )
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub
        + total_word_del
        + total_word_ins
    ) / max(
        1,
        total_words
    )

    cer = (
        total_char_sub
        + total_char_del
        + total_char_ins
    ) / max(
        1,
        total_chars
    )

    return {
        "WER": wer,
        "CER": cer,

        "word_sub":
            total_word_sub,

        "word_del":
            total_word_del,

        "word_ins":
            total_word_ins,

        "char_sub":
            total_char_sub,

        "char_del":
            total_char_del,

        "char_ins":
            total_char_ins,

        "total_words":
            total_words,

        "total_chars":
            total_chars,
    }

In [ ]:
MODEL_NAME = "large-v3"

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

model = whisper.load_model(
    MODEL_NAME,
    device=device
)

model.eval()

print(
    "Using device:",
    device
)

print(
    "Loaded Whisper model:",
    MODEL_NAME
)

100%|██████████████████████████████████████| 2.88G/2.88G [00:22<00:00, 135MiB/s]

Using device: cuda
Loaded Whisper model: large-v3

In [ ]:
WHISPER_LANGUAGE = "fa"
WHISPER_TASK = "transcribe"
WHISPER_TEMPERATURE = 0.0

WHISPER_FP16 = (
    device == "cuda"
)

print(
    "Language:",
    WHISPER_LANGUAGE
)

print(
    "Task:",
    WHISPER_TASK
)

print(
    "Temperature:",
    WHISPER_TEMPERATURE
)

print(
    "FP16:",
    WHISPER_FP16
)

Language: fa
Task: transcribe
Temperature: 0.0
FP16: True

In [ ]:
def transcribe_whisper(
    audio_path,
    model,
):

    audio, sr = sf.read(
        audio_path,
        dtype="float32"
    )

    # Stereo -> mono only if necessary
    if audio.ndim > 1:

        audio = np.mean(
            audio,
            axis=1
        )

    # Whisper expects 16 kHz
    if sr != 16000:

        audio = librosa.resample(
            audio,
            orig_sr=sr,
            target_sr=16000
        )

        sr = 16000

    # Make sure numpy representation
    # is clean float32
    audio = np.asarray(
        audio,
        dtype=np.float32
    )

    result = model.transcribe(
        audio,

        language=WHISPER_LANGUAGE,

        task=WHISPER_TASK,

        temperature=WHISPER_TEMPERATURE,

        fp16=WHISPER_FP16,

        verbose=False,
    )

    prediction = (
        result
        .get(
            "text",
            ""
        )
        .strip()
    )

    return prediction

In [ ]:
test_row = df.iloc[0]

test_prediction = (
    transcribe_whisper(
        test_row["audio_path"],
        model,
    )
)

print("REFERENCE:")
print(
    test_row["transcription"]
)

print("\nWHISPER:")
print(
    test_prediction
)

print("\nNORMALIZED REFERENCE:")
print(
    nemo_paper_normalize(
        test_row["transcription"]
    )
)

print("\nNORMALIZED HYPOTHESIS:")
print(
    nemo_paper_normalize(
        test_prediction
    )
)

100%|██████████| 3240/3240 [00:11<00:00, 276.65frames/s]

REFERENCE:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید تکامل یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینی متوسط و سهره کاکتوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید

WHISPER:
محققان دانشگاه پرینستون امریکا و دانشگاه اوبسالا در سوئیت گناه های جدید تکم و لیافده ای را تنها در دو نسل گزارش دادند. اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی، سهره زمنی متوسط و سهره کاکتوسی محاجر یعنی سهره کاکتوسی بزرگ، این روند خیلی بیشتر طول کشید. درست دارید.

NORMALIZED REFERENCE:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید تکامل یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینی متوسط و سهره کاکتوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید

NORMALIZED HYPOTHESIS:
محققان دانشگاه پرینستون امریکا و دانشگاه اوبسالا در سوئیت گناه های جدید تکم و لیافده ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمنی متوسط و سهره کاکتوسی محاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید درست دارید

In [ ]:
WHISPER_RESULTS_DIR = (
    ASR_COMPARE_DIR
    / "whisper_large_v3"
)

WHISPER_RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

CHECKPOINT_PATH_WHISPER = (
    WHISPER_RESULTS_DIR
    / "whisper_large_v3_fleurs_checkpoint.csv"
)

FINAL_PATH_WHISPER = (
    WHISPER_RESULTS_DIR
    / "whisper_large_v3_fleurs_results_v1.csv"
)

SUMMARY_PATH_WHISPER = (
    WHISPER_RESULTS_DIR
    / "whisper_large_v3_fleurs_summary_v1.csv"
)

print(
    "Checkpoint:",
    CHECKPOINT_PATH_WHISPER
)

print(
    "Final:",
    FINAL_PATH_WHISPER
)

print(
    "Summary:",
    SUMMARY_PATH_WHISPER
)

Checkpoint: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/whisper_large_v3/whisper_large_v3_fleurs_checkpoint.csv
Final: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/whisper_large_v3/whisper_large_v3_fleurs_results_v1.csv
Summary: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/whisper_large_v3/whisper_large_v3_fleurs_summary_v1.csv

In [ ]:
def atomic_save_result_map(
    result_map,
    path,
):

    checkpoint_df = pd.DataFrame(
        list(
            result_map.values()
        )
    )

    if len(checkpoint_df):

        checkpoint_df = (
            checkpoint_df
            .sort_values(
                [
                    "id",
                    "file_name"
                ]
            )
            .reset_index(
                drop=True
            )
        )

    tmp_path = (
        str(path)
        + ".tmp"
    )

    checkpoint_df.to_csv(
        tmp_path,
        index=False,
        encoding="utf-8-sig"
    )

    os.replace(
        tmp_path,
        path
    )

In [ ]:
whisper_results = {}

if CHECKPOINT_PATH_WHISPER.exists():

    previous_df = pd.read_csv(
        CHECKPOINT_PATH_WHISPER
    )

    for _, row in previous_df.iterrows():

        whisper_results[
            str(row["file_name"])
        ] = row.to_dict()

    print(
        "Checkpoint rows loaded:",
        len(whisper_results)
    )

else:

    print(
        "No Whisper checkpoint found."
    )

Checkpoint rows loaded: 850

In [ ]:
processed_whisper = {
    file_name
    for file_name, row
    in whisper_results.items()
    if row.get("status") == "ok"
}

print(
    "Already successful:",
    len(processed_whisper)
)

Already successful: 850

In [ ]:
for idx in tqdm(
    range(len(df)),
    desc="Whisper large-v3 FLEURS"
):

    row = df.iloc[idx]

    file_name = str(
        row["file_name"]
    )

    if file_name in processed_whisper:
        continue

    audio_path = (
        row["audio_path"]
    )

    try:

        info = sf.info(
            audio_path
        )

        duration = (
            info.duration
        )

        if device == "cuda":
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        pred_text = (
            transcribe_whisper(
                audio_path,
                model,
            )
        )

        if device == "cuda":
            torch.cuda.synchronize()

        inference_time = (
            time.perf_counter()
            - t0
        )

        whisper_results[
            file_name
        ] = {

            "id":
                int(row["id"]),

            "file_name":
                file_name,

            "audio_path":
                audio_path,

            "gender":
                row["gender"],

            "audio_duration":
                duration,

            "reference_raw":
                row[
                    "raw_transcription"
                ],

            # Official FLEURS scoring reference
            "reference_normalized":
                row[
                    "transcription"
                ],

            "prediction_raw":
                pred_text,

            "inference_time":
                inference_time,

            "rtf": (
                inference_time
                / duration
                if duration > 0
                else None
            ),

            "status":
                "ok",

            "error":
                "",
        }

        processed_whisper.add(
            file_name
        )

    except Exception as e:

        whisper_results[
            file_name
        ] = {

            "id":
                int(row["id"]),

            "file_name":
                file_name,

            "audio_path":
                audio_path,

            "gender":
                row["gender"],

            "audio_duration":
                None,

            "reference_raw":
                row[
                    "raw_transcription"
                ],

            "reference_normalized":
                row[
                    "transcription"
                ],

            "prediction_raw":
                "",

            "inference_time":
                None,

            "rtf":
                None,

            "status":
                "error",

            "error":
                repr(e),
        }

        print(
            f"\nFAILED: {file_name}"
        )

        print(e)

    # Save every recording
    atomic_save_result_map(
        whisper_results,
        CHECKPOINT_PATH_WHISPER
    )

Whisper large-v3 FLEURS:   0%|          | 0/871 [00:00<?, ?it/s]

  0%|          | 0/2076 [00:00<?, ?frames/s]
100%|██████████| 2076/2076 [00:07<00:00, 288.37frames/s]

  0%|          | 0/966 [00:00<?, ?frames/s]
100%|██████████| 966/966 [00:02<00:00, 382.01frames/s]

  0%|          | 0/936 [00:00<?, ?frames/s]
100%|██████████| 936/936 [00:03<00:00, 287.01frames/s]

  0%|          | 0/1398 [00:00<?, ?frames/s]
100%|██████████| 1398/1398 [00:02<00:00, 551.57frames/s]

  0%|          | 0/3822 [00:00<?, ?frames/s]
 62%|██████▏   | 2382/3822 [00:08<00:04, 291.48frames/s]
100%|██████████| 3822/3822 [00:16<00:00, 230.79frames/s]

  0%|          | 0/1638 [00:00<?, ?frames/s]
100%|██████████| 1638/1638 [00:03<00:00, 431.83frames/s]

  0%|          | 0/1362 [00:00<?, ?frames/s]
100%|██████████| 1362/1362 [00:04<00:00, 324.46frames/s]

  0%|          | 0/1566 [00:00<?, ?frames/s]
100%|██████████| 1566/1566 [00:03<00:00, 427.94frames/s]

  0%|          | 0/1290 [00:00<?, ?frames/s]
100%|██████████| 1290/1290 [00:03<00:00, 391.39frames/s]

  0%|          | 0/1644 [00:00<?, ?frames/s]
100%|██████████| 1644/1644 [00:03<00:00, 514.61frames/s]

  0%|          | 0/1704 [00:00<?, ?frames/s]
100%|██████████| 1704/1704 [00:03<00:00, 541.40frames/s]

  0%|          | 0/1578 [00:00<?, ?frames/s]
100%|██████████| 1578/1578 [00:05<00:00, 312.98frames/s]

  0%|          | 0/2316 [00:00<?, ?frames/s]
100%|██████████| 2316/2316 [00:04<00:00, 548.37frames/s]

  0%|          | 0/1956 [00:00<?, ?frames/s]
100%|██████████| 1956/1956 [00:04<00:00, 429.95frames/s]

  0%|          | 0/1854 [00:00<?, ?frames/s]
100%|██████████| 1854/1854 [00:05<00:00, 314.17frames/s]

  0%|          | 0/2064 [00:00<?, ?frames/s]
100%|██████████| 2064/2064 [00:05<00:00, 377.86frames/s]

  0%|          | 0/1944 [00:00<?, ?frames/s]
100%|██████████| 1944/1944 [00:06<00:00, 307.82frames/s]

  0%|          | 0/2316 [00:00<?, ?frames/s]
100%|██████████| 2316/2316 [00:05<00:00, 447.25frames/s]

  0%|          | 0/1926 [00:00<?, ?frames/s]
100%|██████████| 1926/1926 [00:06<00:00, 306.39frames/s]

  0%|          | 0/1932 [00:00<?, ?frames/s]
100%|██████████| 1932/1932 [00:04<00:00, 482.16frames/s]

  0%|          | 0/1824 [00:00<?, ?frames/s]
100%|██████████| 1824/1824 [00:04<00:00, 442.65frames/s]

In [ ]:
whisper_df = pd.read_csv(
    CHECKPOINT_PATH_WHISPER
)

print(
    "Checkpoint rows:",
    len(whisper_df)
)

print()

print(
    whisper_df[
        "status"
    ].value_counts(
        dropna=False
    )
)

Checkpoint rows: 871

status
ok    871
Name: count, dtype: int64

In [ ]:
whisper_sub = (
    whisper_df[
        whisper_df["status"]
        == "ok"
    ]
    .copy()
)

print(
    "Successful:",
    len(whisper_sub)
)

print(
    "Failed:",
    len(whisper_df)
    - len(whisper_sub)
)

print(
    "Unique files:",
    whisper_sub[
        "file_name"
    ].nunique()
)

Successful: 871
Failed: 0
Unique files: 871

In [ ]:
whisper_sub["hyp_norm"] = (
    whisper_sub[
        "prediction_raw"
    ]
    .apply(
        nemo_paper_normalize
    )
)

whisper_sub["ref_norm"] = (
    whisper_sub[
        "reference_normalized"
    ]
    .apply(
        nemo_paper_normalize
    )
)

In [ ]:
display(
    whisper_sub[
        [
            "reference_normalized",
            "prediction_raw",
            "ref_norm",
            "hyp_norm",
        ]
    ].head()
)

,reference_normalized,prediction_raw,ref_norm,hyp_norm
0,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رومانتیزم اثر عظیمی از جعبگرایی فرهنگی داشت که...,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رومانتیزم اثر عظیمی از جعبگرایی فرهنگی داشت که...
1,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رومانتیسم انصار عظیمی از جبرگرای فرهنگی داشت ک...,رمانتیسم عنصر عظیمی از جبرگرایی فرهنگی داشت که...,رومانتیسم انصار عظیمی از جبرگرای فرهنگی داشت ک...
2,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی را برای این کاهش ها تعین نکرد و گفت که...,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی را برای این کاهش ها تعین نکرد و گفت که...
3,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی برای این کاهش ها تعییم مکرد و گفت که ب...,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی برای این کاهش ها تعییم مکرد و گفت که ب...
4,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی برای این کاهش ها تغییر تعیین نکرد و گف...,او رقمی برای این کاهش‌ها تعیین نکرد و گفت که ب...,او رقمی برای این کاهش ها تغییر تعیین نکرد و گف...

In [ ]:
whisper_metrics = (
    compute_dataset_wer_cer(
        whisper_sub,
        ref_col="ref_norm",
        hyp_col="hyp_norm",
    )
)

print(
    whisper_metrics
)

{'WER': 0.31304434380132384, 'CER': 0.09131237560846941, 'word_sub': 4252, 'word_del': 261, 'word_ins': 1777, 'char_sub': 2780, 'char_del': 3038, 'char_ins': 1798, 'total_words': 20093, 'total_chars': 83406}

In [ ]:
print(
    f"Samples: {len(whisper_sub)}"
)

print(
    f"WER: {whisper_metrics['WER']:.6f}"
)

print(
    f"CER: {whisper_metrics['CER']:.6f}"
)

print(
    f"WER (%): "
    f"{whisper_metrics['WER'] * 100:.2f}%"
)

print(
    f"CER (%): "
    f"{whisper_metrics['CER'] * 100:.2f}%"
)

Samples: 871
WER: 0.313044
CER: 0.091312
WER (%): 31.30%
CER (%): 9.13%

In [ ]:
def compute_row_error_rates(
    row
):

    ref = (
        ""
        if pd.isna(
            row["ref_norm"]
        )
        else str(
            row["ref_norm"]
        )
    )

    hyp = (
        ""
        if pd.isna(
            row["hyp_norm"]
        )
        else str(
            row["hyp_norm"]
        )
    )

    wer, _, _, _, _ = (
        _alignment_error_rate(
            ref.split(),
            hyp.split()
        )
    )

    cer, _, _, _, _ = (
        _alignment_error_rate(
            list(
                ref.replace(
                    " ",
                    ""
                )
            ),
            list(
                hyp.replace(
                    " ",
                    ""
                )
            )
        )
    )

    return pd.Series({
        "wer": wer,
        "cer": cer,
    })

In [ ]:
whisper_sub[
    [
        "wer",
        "cer"
    ]
] = whisper_sub.apply(
    compute_row_error_rates,
    axis=1
)

In [ ]:
whisper_summary_df = pd.DataFrame([
    {
        "Samples":
            len(whisper_sub),

        "WER":
            whisper_metrics[
                "WER"
            ],

        "CER":
            whisper_metrics[
                "CER"
            ],
    }
])

display(
    whisper_summary_df
)

   Samples       WER       CER
0      871  0.313044  0.091312

In [ ]:
assert len(whisper_sub) == 871

assert (
    whisper_sub[
        "file_name"
    ].nunique()
    == 871
)

whisper_sub = (
    whisper_sub
    .sort_values(
        [
            "id",
            "file_name"
        ]
    )
    .reset_index(
        drop=True
    )
)

whisper_sub.to_csv(
    FINAL_PATH_WHISPER,
    index=False,
    encoding="utf-8-sig"
)

whisper_summary_df.to_csv(
    SUMMARY_PATH_WHISPER,
    index=False,
    encoding="utf-8-sig"
)

print(
    "Final predictions:",
    FINAL_PATH_WHISPER
)

print(
    "Summary:",
    SUMMARY_PATH_WHISPER
)

Final predictions: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/whisper_large_v3/whisper_large_v3_fleurs_results_v1.csv
Summary: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/whisper_large_v3/whisper_large_v3_fleurs_summary_v1.csv

In [ ]:
def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb"
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):

            h.update(
                chunk
            )

    return h.hexdigest()

In [ ]:
print(
    "Prediction SHA-256:"
)

print(
    sha256_file(
        FINAL_PATH_WHISPER
    )
)

print()

print(
    "Summary SHA-256:"
)

print(
    sha256_file(
        SUMMARY_PATH_WHISPER
    )
)

Prediction SHA-256:
3091fddf86c4feff189d1b60214dd0e2d4f4c608699aca12693ec639ddbf229f

Summary SHA-256:
1804c2cf30565e4eb54e7ba75ea531f5fa09176ce4088bb20e4b03fc654c4947

In [ ]:
print(
    whisper_summary_df
)

print()

print(
    whisper_metrics
)

   Samples       WER       CER
0      871  0.313044  0.091312

{'WER': 0.31304434380132384, 'CER': 0.09131237560846941, 'word_sub': 4252, 'word_del': 261, 'word_ins': 1777, 'char_sub': 2780, 'char_del': 3038, 'char_ins': 1798, 'total_words': 20093, 'total_chars': 83406}

# Nemo

In [ ]:
!pip install -q soundfile librosa pandas tqdm

In [ ]:
import os
import time
import hashlib
import unicodedata

import numpy as np
import pandas as pd
import soundfile as sf
import torch

from tqdm.auto import tqdm

import nemo.collections.asr as nemo_asr

In [ ]:
COLUMNS = [
    "id",
    "file_name",
    "raw_transcription",
    "transcription",
    "character_transcription",
    "num_samples",
    "gender",
]

df = pd.read_csv(
    TSV_PATH,
    sep="\t",
    header=None,
    names=COLUMNS,
)

print("Rows:", len(df))
print("Unique files:", df["file_name"].nunique())
print("Unique semantic IDs:", df["id"].nunique())

Rows: 871
Unique files: 871
Unique semantic IDs: 324

In [ ]:
wav_files = list(
    DATA_DIR.rglob("*.wav")
)

wav_map = {
    p.name: str(p)
    for p in wav_files
}

df["audio_path"] = (
    df["file_name"]
    .map(wav_map)
)

print(
    "Matched:",
    df["audio_path"].notna().sum()
)

print(
    "Missing:",
    df["audio_path"].isna().sum()
)

assert len(df) == 871
assert df["audio_path"].notna().all()

Matched: 871
Missing: 0

In [ ]:
audio_info = []

for path in df["audio_path"]:

    info = sf.info(path)

    audio_info.append({
        "sample_rate": info.samplerate,
        "channels": info.channels,
        "subtype": info.subtype,
    })

audio_info_df = pd.DataFrame(audio_info)

print("Sample rates:")
print(
    audio_info_df["sample_rate"]
    .value_counts()
)

print("\nChannels:")
print(
    audio_info_df["channels"]
    .value_counts()
)

print("\nSubtype:")
print(
    audio_info_df["subtype"]
    .value_counts()
)

Sample rates:
sample_rate
16000    871
Name: count, dtype: int64

Channels:
channels
1    871
Name: count, dtype: int64

Subtype:
subtype
FLOAT    871
Name: count, dtype: int64

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:

    if text is None:
        return ""

    text = str(text)

    text = unicodedata.normalize(
        "NFKC",
        text
    )

    text = " ".join(
        w
        for w in text.split()
        if not w.startswith("#")
    )

    for k, v in REPLACEMENTS.items():
        text = text.replace(k, v)

    for tok in DISCARD:
        text = text.replace(tok, " ")

    text = text.replace(
        "ء",
        ""
    )

    text = " ".join(
        text.split()
    )

    return text

In [ ]:
def _alignment_error_rate(
    reference,
    hypothesis,
):

    n = len(reference)
    m = len(hypothesis)

    dp = [
        [0] * (m + 1)
        for _ in range(n + 1)
    ]

    ops = [
        [None] * (m + 1)
        for _ in range(n + 1)
    ]

    for i in range(1, n + 1):
        dp[i][0] = i
        ops[i][0] = "D"

    for j in range(1, m + 1):
        dp[0][j] = j
        ops[0][j] = "I"

    for i in range(1, n + 1):

        for j in range(1, m + 1):

            if reference[i - 1] == hypothesis[j - 1]:

                dp[i][j] = dp[i - 1][j - 1]
                ops[i][j] = "C"

            else:

                sub = dp[i - 1][j - 1] + 1
                delete = dp[i - 1][j] + 1
                insert = dp[i][j - 1] + 1

                best = min(
                    sub,
                    delete,
                    insert
                )

                dp[i][j] = best

                if best == sub:
                    ops[i][j] = "S"

                elif best == delete:
                    ops[i][j] = "D"

                else:
                    ops[i][j] = "I"

    i = n
    j = m

    substitutions = 0
    deletions = 0
    insertions = 0

    while i > 0 or j > 0:

        op = ops[i][j]

        if op == "C":
            i -= 1
            j -= 1

        elif op == "S":
            substitutions += 1
            i -= 1
            j -= 1

        elif op == "D":
            deletions += 1
            i -= 1

        elif op == "I":
            insertions += 1
            j -= 1

        else:
            break

    errors = (
        substitutions
        + deletions
        + insertions
    )

    error_rate = (
        errors / n
        if n > 0
        else float(errors > 0)
    )

    return (
        error_rate,
        substitutions,
        deletions,
        insertions,
        n,
    )

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):

    total_word_sub = 0
    total_word_del = 0
    total_word_ins = 0
    total_words = 0

    total_char_sub = 0
    total_char_del = 0
    total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(
        df[ref_col],
        df[hyp_col]
    ):

        ref = (
            ""
            if pd.isna(ref)
            else str(ref)
        )

        hyp = (
            ""
            if pd.isna(hyp)
            else str(hyp)
        )

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(
                ref.replace(" ", "")
            ),
            list(
                hyp.replace(" ", "")
            )
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub
        + total_word_del
        + total_word_ins
    ) / max(
        1,
        total_words
    )

    cer = (
        total_char_sub
        + total_char_del
        + total_char_ins
    ) / max(
        1,
        total_chars
    )

    return {
        "WER": wer,
        "CER": cer,
        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,
        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,
        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
MODEL_NAME = (
    "nvidia/"
    "stt_fa_fastconformer_hybrid_large"
)

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

model = (
    nemo_asr.models
    .EncDecHybridRNNTCTCBPEModel
    .from_pretrained(
        model_name=MODEL_NAME
    )
)

model = model.to(
    device
)

model.eval()

print("Device:", device)
print("Model:", MODEL_NAME)
print("Actual class:", type(model))

[NeMo I 2026-08-25 14:43:59 mixins:194] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-08-25 14:44:00 modelPT:175] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: dummy
    sample_rate: 16000
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: true
    max_duration: 10
    min_duration: 0.5
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: fully_randomized
    bucketing_batch_size: null
    use_lhotse: true
    lhotse:
      shar_path: /data_artifacts/data/shar/train
      batch_duration: 1200
      quadratic_duration: 15
      num_buckets: 10
      num_cuts_for_bins_estimate: 10000
      buffer_size: 10000
      shuffle_buffer_size: 10000

[NeMo W 2026-08-25 14:44:00 modelPT:182] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /data_artifacts/data/nemo/dev_decoded_exprunner.json
    sample_rate: 16000
    batch_size: 512
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo W 2026-08-25 14:44:00 modelPT:189] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: /data_artifacts/data/nemo/test_decoded_exprunner.json
    sample_rate: 16000
    batch_size: 512
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo I 2026-08-25 14:44:01 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:44:01 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:44:02 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:44:02 save_restore_connector:287] Model EncDecHybridRNNTCTCBPEModel was successfully restored from /root/.cache/huggingface/hub/models--nvidia--stt_fa_fastconformer_hybrid_large/snapshots/249cf5bf70dda7220a60ddeeecff2f6aad8e1784/stt_fa_fastconformer_hybrid_large.nemo.
Device: cuda
Model: nvidia/stt_fa_fastconformer_hybrid_large
Actual class: <class 'nemo.collections.asr.models.hybrid_rnnt_ctc_bpe_models.EncDecHybridRNNTCTCBPEModel'>

In [ ]:
print(
    "Current decoder:",
    getattr(
        model,
        "cur_decoder",
        "attribute not available"
    )
)

Current decoder: rnnt

In [ ]:
def extract_nemo_text(output):

    # Some NeMo versions return:
    # [Hypothesis(text="...")]
    #
    # Others return:
    # ["..."]

    if isinstance(
        output,
        tuple
    ):
        output = output[0]

    if not isinstance(
        output,
        (list, tuple)
    ):
        raise TypeError(
            f"Unexpected NeMo output type: "
            f"{type(output)}"
        )

    if len(output) == 0:
        return ""

    item = output[0]

    if hasattr(
        item,
        "text"
    ):
        return str(
            item.text
        ).strip()

    if isinstance(
        item,
        str
    ):
        return item.strip()

    raise TypeError(
        "Unexpected NeMo hypothesis type: "
        f"{type(item)}"
    )

In [ ]:
def transcribe_nemo(
    audio_path,
    model,
):

    output = model.transcribe(
        [str(audio_path)],
        batch_size=1,
        verbose=False,
    )

    return extract_nemo_text(
        output
    )

In [ ]:
model.change_decoding_strategy(
    decoder_type="rnnt"
)

print(
    "Decoder after switch:",
    getattr(
        model,
        "cur_decoder",
        "not exposed"
    )
)

[NeMo I 2026-08-25 14:45:11 hybrid_rnnt_ctc_bpe_models:440] No `decoding_cfg` passed when changing decoding strategy, using internal config
[NeMo I 2026-08-25 14:45:11 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:45:11 hybrid_rnnt_ctc_bpe_models:479] Changed decoding strategy of the RNNT decoder to
    model_type: rnnt
    strategy: greedy_batch
    compute_hypothesis_token_set: false
    preserve_alignments: null
    tdt_include_token_duration: null
    confidence_cfg:
      preserve_frame_confidence: false
      preserve_token_confidence: false
      preserve_word_confidence: false
      exclude_blank: true
      aggregation: min
      tdt_include_duration: false
      method_cfg:
        name: entropy
        entropy_type: tsallis
        alpha: 0.33
        entropy_norm: exp
        temperature: DEPRECATED
    fused_batch_size: null
    compute_timestamps: null
    compute_langs: false
    word_seperator: ' '
    segment_seperators:
    - .
    - '!'
    - '?'
    segment_gap_threshold: null
    rnnt_timestamp_type: all
    greedy:
      max_symbols_per_step: 10
      preserve_alignments: false
      preserve_frame_confidence: false
      tdt_include_token_duration: false
      tdt_include_duration_confidence: false
      confidence_method_cfg:
        name: entropy
        entropy_type: tsallis
        alpha: 0.33
        entropy_norm: exp
        temperature: DEPRECATED
      loop_labels: true
      use_cuda_graph_decoder: true
      ngram_lm_model: null
      ngram_lm_alpha: 0.0
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        context_score: 1.0
        depth_scaling: 2.0
        unk_score: 0.0
        final_eos_score: 1.0
        score_per_phrase: 0.0
        source_lang: en
        use_triton: true
        uniform_weights: false
        use_bpe_dropout: false
        num_of_transcriptions: 5
        bpe_alpha: 0.3
      boosting_tree_alpha: 0.0
      enable_per_stream_biasing: false
      max_symbols: 10
    beam:
      beam_size: 2
      search_type: default
      score_norm: true
      return_best_hypothesis: false
      tsd_max_sym_exp_per_step: 50
      alsd_max_target_len: 2.0
      nsc_max_timesteps_expansion: 1
      nsc_prefix_alpha: 1
      maes_num_steps: 2
      maes_prefix_alpha: 1
      maes_expansion_gamma: 2.3
      maes_expansion_beta: 2
      language_model: null
      softmax_temperature: 1.0
      preserve_alignments: false
      ngram_lm_model: null
      ngram_lm_alpha: 0.0
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        context_score: 1.0
        depth_scaling: 2.0
        unk_score: 0.0
        final_eos_score: 1.0
        score_per_phrase: 0.0
        source_lang: en
        use_triton: true
        uniform_weights: false
        use_bpe_dropout: false
        num_of_transcriptions: 5
        bpe_alpha: 0.3
      boosting_tree_alpha: 0.0
      hat_subtract_ilm: false
      hat_ilm_weight: 0.0
      max_symbols_per_step: 10
      blank_lm_score_mode: LM_WEIGHTED_FULL
      pruning_mode: LATE
      allow_cuda_graphs: true
      tsd_max_sym_exp: 50
    temperature: 1.0
    durations: []
    big_blank_durations: []
    strip_lang_tags: false
    lang_tag_pattern: null

Decoder after switch: rnnt

In [ ]:
for idx in [
    0,
    1,
    2,
]:

    row = df.iloc[idx]

    prediction = transcribe_nemo(
        row["audio_path"],
        model,
    )

    print("=" * 100)

    print(
        "FILE:",
        row["file_name"]
    )

    print("\nREFERENCE:")
    print(
        row["transcription"]
    )

    print("\nRNNT:")
    print(
        prediction
    )

[NeMo W 2026-08-25 14:45:35 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:45:35 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:45:36 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:45:36 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

====================================================================================================
FILE: 7913564082410055971.wav

REFERENCE:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید تکامل یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینی متوسط و سهره کاکتوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید

RNNT:
محققان دانشگاه پون در سودگهای جدید تکامل را تنها در دو نسل گزارش دادند اگر چه بریم که به دلیل لذت بین یک سله دارین متوسط و سه موهاجر این روند خیلی بیشتر طول کشید

[NeMo W 2026-08-25 14:45:38 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:45:38 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

====================================================================================================
FILE: 621633057978356932.wav

REFERENCE:
شکلات داغ در حد استانداردهای بلژیکی است آبمیوه‌ها گران‌قیمت ولی عالی می‌باشند

RNNT:
شکلات داغ در استاندار بلژیکیان قیمت ولی عالی میب
====================================================================================================
FILE: 13180061520623477685.wav

REFERENCE:
شکلات داغ در حد استانداردهای بلژیکی است آبمیوه‌ها گران‌قیمت ولی عالی می‌باشند

RNNT:
شکلات داغ در استاندارد گران ولی عالی میباشد

In [ ]:
def atomic_save_result_map(
    result_map,
    path,
):

    checkpoint_df = pd.DataFrame(
        list(
            result_map.values()
        )
    )

    if len(checkpoint_df):

        checkpoint_df = (
            checkpoint_df
            .sort_values(
                [
                    "id",
                    "file_name"
                ]
            )
            .reset_index(
                drop=True
            )
        )

    tmp_path = (
        str(path)
        + ".tmp"
    )

    checkpoint_df.to_csv(
        tmp_path,
        index=False,
        encoding="utf-8-sig"
    )

    os.replace(
        tmp_path,
        path
    )

In [ ]:
def run_nemo_fleurs(
    decoder_type,
):

    assert decoder_type in {
        "rnnt",
        "ctc",
    }

    model.change_decoding_strategy(
        decoder_type=decoder_type
    )

    results_dir = (
        ASR_COMPARE_DIR
        / f"nemo_fastconformer_{decoder_type}"
    )

    results_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    checkpoint_path = (
        results_dir
        / f"nemo_{decoder_type}_fleurs_checkpoint.csv"
    )

    final_path = (
        results_dir
        / f"nemo_{decoder_type}_fleurs_results_v1.csv"
    )

    summary_path = (
        results_dir
        / f"nemo_{decoder_type}_fleurs_summary_v1.csv"
    )

    results = {}

    if checkpoint_path.exists():

        old = pd.read_csv(
            checkpoint_path
        )

        for _, old_row in old.iterrows():

            results[
                str(
                    old_row["file_name"]
                )
            ] = old_row.to_dict()

        print(
            f"Loaded {len(results)} "
            f"{decoder_type.upper()} checkpoint rows"
        )

    processed = {
        file_name
        for file_name, item
        in results.items()
        if item.get("status") == "ok"
    }

    print(
        "Already completed:",
        len(processed)
    )

    for idx in tqdm(
        range(len(df)),
        desc=f"NeMo {decoder_type.upper()} FLEURS"
    ):

        row = df.iloc[idx]

        file_name = str(
            row["file_name"]
        )

        if file_name in processed:
            continue

        audio_path = (
            row["audio_path"]
        )

        try:

            info = sf.info(
                audio_path
            )

            duration = (
                info.duration
            )

            if device == "cuda":
                torch.cuda.synchronize()

            t0 = time.perf_counter()

            pred_text = transcribe_nemo(
                audio_path,
                model,
            )

            if device == "cuda":
                torch.cuda.synchronize()

            inference_time = (
                time.perf_counter()
                - t0
            )

            results[file_name] = {

                "id":
                    int(row["id"]),

                "file_name":
                    file_name,

                "audio_path":
                    audio_path,

                "gender":
                    row["gender"],

                "audio_duration":
                    duration,

                "reference_raw":
                    row[
                        "raw_transcription"
                    ],

                "reference_normalized":
                    row[
                        "transcription"
                    ],

                "prediction_raw":
                    pred_text,

                "decoder_type":
                    decoder_type,

                "inference_time":
                    inference_time,

                "rtf": (
                    inference_time
                    / duration
                    if duration > 0
                    else None
                ),

                "status":
                    "ok",

                "error":
                    "",
            }

            processed.add(
                file_name
            )

        except Exception as e:

            results[file_name] = {

                "id":
                    int(row["id"]),

                "file_name":
                    file_name,

                "audio_path":
                    audio_path,

                "gender":
                    row["gender"],

                "audio_duration":
                    None,

                "reference_raw":
                    row[
                        "raw_transcription"
                    ],

                "reference_normalized":
                    row[
                        "transcription"
                    ],

                "prediction_raw":
                    "",

                "decoder_type":
                    decoder_type,

                "inference_time":
                    None,

                "rtf":
                    None,

                "status":
                    "error",

                "error":
                    repr(e),
            }

            print(
                f"\nFAILED: {file_name}"
            )

            print(e)

        atomic_save_result_map(
            results,
            checkpoint_path
        )

    result_df = pd.read_csv(
        checkpoint_path
    )

    result_sub = (
        result_df[
            result_df["status"]
            == "ok"
        ]
        .copy()
    )

    print(
        "\nSuccessful:",
        len(result_sub)
    )

    print(
        "Failed:",
        len(result_df)
        - len(result_sub)
    )

    assert len(result_sub) == 871
    assert (
        result_sub[
            "file_name"
        ].nunique()
        == 871
    )

    result_sub["hyp_norm"] = (
        result_sub[
            "prediction_raw"
        ]
        .apply(
            nemo_paper_normalize
        )
    )

    result_sub["ref_norm"] = (
        result_sub[
            "reference_normalized"
        ]
        .apply(
            nemo_paper_normalize
        )
    )

    metrics = (
        compute_dataset_wer_cer(
            result_sub,
            ref_col="ref_norm",
            hyp_col="hyp_norm",
        )
    )

    summary = pd.DataFrame([
        {
            "Decoder":
                decoder_type.upper(),

            "Samples":
                len(result_sub),

            "WER":
                metrics["WER"],

            "CER":
                metrics["CER"],
        }
    ])

    result_sub.to_csv(
        final_path,
        index=False,
        encoding="utf-8-sig"
    )

    summary.to_csv(
        summary_path,
        index=False,
        encoding="utf-8-sig"
    )

    display(
        summary
    )

    print(
        metrics
    )

    return {
        "summary": summary,
        "metrics": metrics,
        "results": result_sub,
        "final_path": final_path,
        "summary_path": summary_path,
    }

In [ ]:
rnnt_run = run_nemo_fleurs(
    "rnnt"
)

[NeMo I 2026-08-25 14:46:41 hybrid_rnnt_ctc_bpe_models:440] No `decoding_cfg` passed when changing decoding strategy, using internal config
[NeMo I 2026-08-25 14:46:41 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:46:41 hybrid_rnnt_ctc_bpe_models:479] Changed decoding strategy of the RNNT decoder to
    model_type: rnnt
    strategy: greedy_batch
    compute_hypothesis_token_set: false
    preserve_alignments: null
    tdt_include_token_duration: null
    confidence_cfg:
      preserve_frame_confidence: false
      preserve_token_confidence: false
      preserve_word_confidence: false
      exclude_blank: true
      aggregation: min
      tdt_include_duration: false
      method_cfg:
        name: entropy
        entropy_type: tsallis
        alpha: 0.33
        entropy_norm: exp
        temperature: DEPRECATED
    fused_batch_size: null
    compute_timestamps: null
    compute_langs: false
    word_seperator: ' '
    segment_seperators:
    - .
    - '!'
    - '?'
    segment_gap_threshold: null
    rnnt_timestamp_type: all
    greedy:
      max_symbols_per_step: 10
      preserve_alignments: false
      preserve_frame_confidence: false
      tdt_include_token_duration: false
      tdt_include_duration_confidence: false
      confidence_method_cfg:
        name: entropy
        entropy_type: tsallis
        alpha: 0.33
        entropy_norm: exp
        temperature: DEPRECATED
      loop_labels: true
      use_cuda_graph_decoder: true
      ngram_lm_model: null
      ngram_lm_alpha: 0.0
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        context_score: 1.0
        depth_scaling: 2.0
        unk_score: 0.0
        final_eos_score: 1.0
        score_per_phrase: 0.0
        source_lang: en
        use_triton: true
        uniform_weights: false
        use_bpe_dropout: false
        num_of_transcriptions: 5
        bpe_alpha: 0.3
      boosting_tree_alpha: 0.0
      enable_per_stream_biasing: false
      max_symbols: 10
    beam:
      beam_size: 2
      search_type: default
      score_norm: true
      return_best_hypothesis: false
      tsd_max_sym_exp_per_step: 50
      alsd_max_target_len: 2.0
      nsc_max_timesteps_expansion: 1
      nsc_prefix_alpha: 1
      maes_num_steps: 2
      maes_prefix_alpha: 1
      maes_expansion_gamma: 2.3
      maes_expansion_beta: 2
      language_model: null
      softmax_temperature: 1.0
      preserve_alignments: false
      ngram_lm_model: null
      ngram_lm_alpha: 0.0
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        context_score: 1.0
        depth_scaling: 2.0
        unk_score: 0.0
        final_eos_score: 1.0
        score_per_phrase: 0.0
        source_lang: en
        use_triton: true
        uniform_weights: false
        use_bpe_dropout: false
        num_of_transcriptions: 5
        bpe_alpha: 0.3
      boosting_tree_alpha: 0.0
      hat_subtract_ilm: false
      hat_ilm_weight: 0.0
      max_symbols_per_step: 10
      blank_lm_score_mode: LM_WEIGHTED_FULL
      pruning_mode: LATE
      allow_cuda_graphs: true
      tsd_max_sym_exp: 50
    temperature: 1.0
    durations: []
    big_blank_durations: []
    strip_lang_tags: false
    lang_tag_pattern: null

Already completed: 0

NeMo RNNT FLEURS:   0%|          | 0/871 [00:00<?, ?it/s]

[NeMo W 2026-08-25 14:46:41 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:41 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:41 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:41 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:41 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:41 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:41 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:41 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:42 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:42 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:43 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:43 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:45 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:45 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:46 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:46 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:47 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:47 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:48 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:48 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:48 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:48 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:48 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:48 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:49 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:49 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:49 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:49 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:49 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:49 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:49 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:49 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:49 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:49 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:50 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:50 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:50 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:50 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:50 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:50 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:50 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:50 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:50 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:50 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:50 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:50 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:51 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:51 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:52 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:52 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:52 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:52 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:52 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:52 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:52 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:52 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:52 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:46:52 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:46:52 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Successful: 871
Failed: 0

  Decoder  Samples       WER      CER
0    RNNT      871  0.433186  0.27769

{'WER': 0.4331856865575076, 'CER': 0.2776898544469223, 'word_sub': 4423, 'word_del': 4055, 'word_ins': 226, 'char_sub': 2440, 'char_del': 20251, 'char_ins': 470, 'total_words': 20093, 'total_chars': 83406}

In [ ]:
print(
    rnnt_run["summary"]
)

print()

print(
    rnnt_run["metrics"]
)

  Decoder  Samples       WER      CER
0    RNNT      871  0.433186  0.27769

{'WER': 0.4331856865575076, 'CER': 0.2776898544469223, 'word_sub': 4423, 'word_del': 4055, 'word_ins': 226, 'char_sub': 2440, 'char_del': 20251, 'char_ins': 470, 'total_words': 20093, 'total_chars': 83406}

In [ ]:
ctc_run = run_nemo_fleurs(
    "ctc"
)

[NeMo I 2026-08-25 14:49:57 hybrid_rnnt_ctc_bpe_models:488] No `decoding_cfg` passed when changing decoding strategy, using internal config
[NeMo I 2026-08-25 14:49:57 hybrid_rnnt_ctc_bpe_models:513] Changed decoding strategy of the CTC decoder to
    strategy: greedy
    preserve_alignments: null
    compute_timestamps: null
    word_seperator: ' '
    segment_seperators:
    - .
    - '!'
    - '?'
    segment_gap_threshold: null
    ctc_timestamp_type: all
    batch_dim_index: 0
    greedy:
      preserve_alignments: false
      compute_timestamps: false
      preserve_frame_confidence: false
      confidence_method_cfg:
        name: entropy
        entropy_type: tsallis
        alpha: 0.33
        entropy_norm: exp
        temperature: DEPRECATED
      ngram_lm_model: null
      ngram_lm_alpha: 0.0
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        context_score: 1.0
        depth_scaling: 2.0
        unk_score: 0.0
        final_eos_score: 1.0
        score_per_phrase: 0.0
        source_lang: en
        use_triton: true
        uniform_weights: false
        use_bpe_dropout: false
        num_of_transcriptions: 5
        bpe_alpha: 0.3
      boosting_tree_alpha: 0.0
      allow_cuda_graphs: true
    beam:
      beam_size: 4
      search_type: default
      preserve_alignments: false
      compute_timestamps: false
      return_best_hypothesis: true
      allow_cuda_graphs: true
      beam_alpha: 1.0
      beam_beta: 0.0
      beam_threshold: 20.0
      kenlm_path: null
      ngram_lm_alpha: 1.0
      ngram_lm_model: null
      boosting_tree:
        model_path: null
        key_phrases_file: null
        key_phrases_list: null
        key_phrase_items_list: null
        context_score: 1.0
        depth_scaling: 2.0
        unk_score: 0.0
        final_eos_score: 1.0
        score_per_phrase: 0.0
        source_lang: en
        use_triton: true
        uniform_weights: false
        use_bpe_dropout: false
        num_of_transcriptions: 5
        bpe_alpha: 0.3
      boosting_tree_alpha: 0.0
      flashlight_cfg:
        lexicon_path: null
        boost_path: null
        beam_size_token: 16
        beam_threshold: 20.0
        unk_weight: -.inf
        sil_weight: 0.0
      pyctcdecode_cfg:
        beam_prune_logp: -10.0
        token_min_logp: -5.0
        prune_history: false
        hotwords: null
        hotword_weight: 10.0
    wfst:
      beam_size: 4
      search_type: riva
      return_best_hypothesis: true
      preserve_alignments: false
      compute_timestamps: false
      decoding_mode: nbest
      open_vocabulary_decoding: false
      beam_width: 10.0
      lm_weight: 1.0
      device: cuda
      arpa_lm_path: null
      wfst_lm_path: null
      riva_decoding_cfg: {}
    confidence_cfg:
      preserve_frame_confidence: false
      preserve_token_confidence: false
      preserve_word_confidence: false
      exclude_blank: true
      aggregation: min
      tdt_include_duration: false
      method_cfg:
        name: entropy
        entropy_type: tsallis
        alpha: 0.33
        entropy_norm: exp
        temperature: DEPRECATED
    temperature: 1.0

Already completed: 0

NeMo CTC FLEURS:   0%|          | 0/871 [00:00<?, ?it/s]

[NeMo W 2026-08-25 14:49:57 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:57 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:57 ctc_greedy_decoding:277] CTC decoding strategy 'greedy' is slower than 'greedy_batch', which implements the same exact interface. Consider changing your strategy to 'greedy_batch' for a free performance improvement.
[NeMo W 2026-08-25 14:49:57 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:57 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:57 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:57 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:57 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:57 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:57 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:57 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:57 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:57 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:58 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:58 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:49:59 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:49:59 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:00 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:00 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:01 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:01 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:01 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:01 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:01 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:01 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:01 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-08-25 14:50:01 dataloader:533] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-08-25 14:50:01 dataloader:881] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

Successful: 871
Failed: 0

  Decoder  Samples       WER       CER
0     CTC      871  0.297218  0.105796

{'WER': 0.29721793659483403, 'CER': 0.10579574610939262, 'word_sub': 4566, 'word_del': 564, 'word_ins': 842, 'char_sub': 2706, 'char_del': 3830, 'char_ins': 2288, 'total_words': 20093, 'total_chars': 83406}

In [ ]:
print(
    ctc_run["summary"]
)

print()

print(
    ctc_run["metrics"]
)

  Decoder  Samples       WER       CER
0     CTC      871  0.297218  0.105796

{'WER': 0.29721793659483403, 'CER': 0.10579574610939262, 'word_sub': 4566, 'word_del': 564, 'word_ins': 842, 'char_sub': 2706, 'char_del': 3830, 'char_ins': 2288, 'total_words': 20093, 'total_chars': 83406}

In [ ]:
nemo_decoder_comparison = pd.concat(
    [
        rnnt_run["summary"],
        ctc_run["summary"],
    ],
    ignore_index=True
)

display(
    nemo_decoder_comparison
)

  Decoder  Samples       WER       CER
0    RNNT      871  0.433186  0.277690
1     CTC      871  0.297218  0.105796

In [ ]:
!pip install -q pandas==2.2.2
!pip install -q numpy==1.26.4
!pip install -q numba==0.60.0
!pip install -q nemo_toolkit['asr']

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 97.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for pandas (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 2.2.2 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 98.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for numpy (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 2.2.2 which is incompatible.
ml-dtypes 0.6.0 requires numpy>=2.0.0, but you have numpy 1.26.4 which is incompatible.
ml-dtypes 0.6.0 requires numpy>=2.1.0; python_version >= "3.13", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.11.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.14.0.94 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
dm-tree 0.1.10 requires numpy>=2.1.0; python_version >= "3.13", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.1 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.8.16 requires numpy>=2.1, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 51.5 MB/s eta 0:00:00
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 903.9/903.9 kB 52.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.0/811.0 kB 50.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 36.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 63.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 65.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 111.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 102.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 22.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 108.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.0/128.0 kB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 65.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.3/377.3 kB 34.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 2.2.2 which is incompatible.

In [ ]:
!pip install -q jiwer
!pip install -q hazm
!pip install -q soundfile

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 72.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 35.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 66.4 MB/s eta 0:00:00
  Building wheel for flashtext (setup.py) ... done

In [ ]:
import os
import re
import time
import random
import numpy as np
import pandas as pd
import torch
import soundfile as sf
from tqdm import tqdm
from jiwer import wer, cer
import nemo.collections.asr as nemo_asr
import hazm

WARNING:nv_one_logger.api.config:OneLogger: Setting error_handling_strategy to DISABLE_QUIETLY_AND_REPORT_METRIC_ERROR for rank (rank=0) with OneLogger disabled. To override: explicitly set error_handling_strategy parameter.
WARNING:nv_one_logger.training_telemetry.api.training_telemetry_provider:No exporters were provided. This means that no telemetry data will be collected.

In [ ]:
MODEL_NAME = "nvidia/stt_fa_fastconformer_hybrid_large"
device = "cuda" if torch.cuda.is_available() else "cpu"

model = nemo_asr.models.ASRModel.from_pretrained(MODEL_NAME)
model = model.to(device)

print("Device:", device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

stt_fa_fastconformer_hybrid_large.nemo: reconstructing file:   0%|          |  0.00B /  459MB

stt_fa_fastconformer_hybrid_large.nemo: downloading bytes:           |  0.00B

[NeMo I 2026-08-25 14:34:32 mixins:194] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-08-25 14:34:34 modelPT:175] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: dummy
    sample_rate: 16000
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: true
    max_duration: 10
    min_duration: 0.5
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: fully_randomized
    bucketing_batch_size: null
    use_lhotse: true
    lhotse:
      shar_path: /data_artifacts/data/shar/train
      batch_duration: 1200
      quadratic_duration: 15
      num_buckets: 10
      num_cuts_for_bins_estimate: 10000
      buffer_size: 10000
      shuffle_buffer_size: 10000

[NeMo W 2026-08-25 14:34:34 modelPT:182] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /data_artifacts/data/nemo/dev_decoded_exprunner.json
    sample_rate: 16000
    batch_size: 512
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo W 2026-08-25 14:34:34 modelPT:189] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: /data_artifacts/data/nemo/test_decoded_exprunner.json
    sample_rate: 16000
    batch_size: 512
    shuffle: false
    use_start_end_token: false
    num_workers: 8
    pin_memory: true

[NeMo I 2026-08-25 14:34:35 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:34:35 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:34:35 rnnt_models:226] Using RNNT Loss : warprnnt_numba
    Loss warprnnt_numba_kwargs: {'fastemit_lambda': 0.0, 'clamp': -1.0}
[NeMo I 2026-08-25 14:34:36 save_restore_connector:287] Model EncDecHybridRNNTCTCBPEModel was successfully restored from /root/.cache/huggingface/hub/models--nvidia--stt_fa_fastconformer_hybrid_large/snapshots/249cf5bf70dda7220a60ddeeecff2f6aad8e1784/stt_fa_fastconformer_hybrid_large.nemo.
Device: cuda

In [ ]:
from google.colab import drive
from pathlib import Path
import os

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")
else:
    print("Google Drive already mounted.")

BASE_DIR = Path(
    "/content/drive/MyDrive/persian_asr_llm_error_propagation"
)

DATA_DIR = BASE_DIR / "data"

ASR_COMPARE_DIR = BASE_DIR / "asr_comparison"

ASR_COMPARE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TSV_PATH = DATA_DIR / "test.tsv"

print("TSV:", TSV_PATH)
print("Exists:", TSV_PATH.exists())

Google Drive already mounted.
TSV: /content/drive/MyDrive/persian_asr_llm_error_propagation/data/test.tsv
Exists: True

In [ ]:
import os
import time
import hashlib
import unicodedata

import numpy as np
import pandas as pd
import soundfile as sf
import librosa
import torch

from tqdm.auto import tqdm

from transformers import (
    Wav2Vec2Processor,
    Wav2Vec2ForCTC,
)

In [ ]:
COLUMNS = [
    "id",
    "file_name",
    "raw_transcription",
    "transcription",
    "character_transcription",
    "num_samples",
    "gender",
]

df = pd.read_csv(
    TSV_PATH,
    sep="\t",
    header=None,
    names=COLUMNS,
)

print("Rows:", len(df))
print("Unique files:", df["file_name"].nunique())
print("Unique semantic IDs:", df["id"].nunique())

display(df.head())

Rows: 871
Unique files: 871
Unique semantic IDs: 324

,id,file_name,raw_transcription,transcription,character_transcription,num_samples,gender
0,1735,7913564082410055971.wav,محققان دانشگاه پرینستون آمریكا و دانشگاه اوپسا...,محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسا...,م ح ق ق ا ن | د ا ن ش گ ا ه | پ ر ی ن س ت و ن ...,518400,MALE
1,1720,621633057978356932.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,193920,MALE
2,1720,13180061520623477685.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,205440,MALE
3,1720,16484235889057265269.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,223680,MALE
4,1955,17985233135634044314.wav,MS نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,ms نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,m s | ن و ع ی | ب ی م ا ر ی | ا س ت | ک ه | ب ...,218880,MALE

In [ ]:
wav_files = list(
    DATA_DIR.rglob("*.wav")
)

print("WAV files found:", len(wav_files))

for p in wav_files[:5]:
    print(p)

WAV files found: 871
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/7099844447178454280.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/13720237503121452158.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/7557020602592715699.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/11242877790416358060.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/5039781156427225122.wav

In [ ]:
wav_map = {}

duplicates = []

for p in wav_files:

    if p.name in wav_map:
        duplicates.append(p.name)

    wav_map[p.name] = str(p)

print("Unique WAV filenames:", len(wav_map))
print("Duplicate filenames:", len(set(duplicates)))

Unique WAV filenames: 871
Duplicate filenames: 0

In [ ]:
df["audio_path"] = (
    df["file_name"]
    .map(wav_map)
)

missing = (
    df["audio_path"]
    .isna()
    .sum()
)

print("Matched audio:", df["audio_path"].notna().sum())
print("Missing audio:", missing)

assert len(df) == 871
assert df["file_name"].nunique() == 871
assert missing == 0

print("All 871 FLEURS recordings mapped successfully.")

Matched audio: 871
Missing audio: 0
All 871 FLEURS recordings mapped successfully.

In [ ]:
audio_info = []

for audio_path in df["audio_path"]:

    info = sf.info(
        audio_path
    )

    audio_info.append({
        "file_name": Path(audio_path).name,
        "sample_rate": info.samplerate,
        "channels": info.channels,
        "subtype": info.subtype,
        "duration": info.duration,
    })

audio_info_df = pd.DataFrame(
    audio_info
)

print("Sample rates:")
print(
    audio_info_df[
        "sample_rate"
    ].value_counts()
)

print("\nChannels:")
print(
    audio_info_df[
        "channels"
    ].value_counts()
)

print("\nWAV subtype:")
print(
    audio_info_df[
        "subtype"
    ].value_counts()
)

Sample rates:
sample_rate
16000    871
Name: count, dtype: int64

Channels:
channels
1    871
Name: count, dtype: int64

WAV subtype:
subtype
FLOAT    871
Name: count, dtype: int64

In [ ]:
SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:

    if text is None:
        return ""

    text = str(text)

    # Unicode normalization FIRST
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    # remove hashtags
    text = " ".join(
        w
        for w in text.split()
        if not w.startswith("#")
    )

    # character replacements
    for k, v in REPLACEMENTS.items():
        text = text.replace(
            k,
            v
        )

    # remove punctuation
    for tok in DISCARD:
        text = text.replace(
            tok,
            " "
        )

    # remove Arabic standalone hamza
    text = text.replace(
        "ء",
        ""
    )

    # collapse whitespace
    text = " ".join(
        text.split()
    )

    return text

In [ ]:
def _alignment_error_rate(
    reference,
    hypothesis,
):

    n = len(reference)
    m = len(hypothesis)

    dp = [
        [0] * (m + 1)
        for _ in range(n + 1)
    ]

    ops = [
        [None] * (m + 1)
        for _ in range(n + 1)
    ]

    for i in range(1, n + 1):
        dp[i][0] = i
        ops[i][0] = "D"

    for j in range(1, m + 1):
        dp[0][j] = j
        ops[0][j] = "I"

    for i in range(
        1,
        n + 1
    ):

        for j in range(
            1,
            m + 1
        ):

            if (
                reference[i - 1]
                == hypothesis[j - 1]
            ):

                dp[i][j] = (
                    dp[i - 1][j - 1]
                )

                ops[i][j] = "C"

            else:

                sub = (
                    dp[i - 1][j - 1]
                    + 1
                )

                delete = (
                    dp[i - 1][j]
                    + 1
                )

                insert = (
                    dp[i][j - 1]
                    + 1
                )

                best = min(
                    sub,
                    delete,
                    insert
                )

                dp[i][j] = best

                if best == sub:
                    ops[i][j] = "S"

                elif best == delete:
                    ops[i][j] = "D"

                else:
                    ops[i][j] = "I"

    i = n
    j = m

    substitutions = 0
    deletions = 0
    insertions = 0

    while i > 0 or j > 0:

        op = ops[i][j]

        if op == "C":

            i -= 1
            j -= 1

        elif op == "S":

            substitutions += 1

            i -= 1
            j -= 1

        elif op == "D":

            deletions += 1
            i -= 1

        elif op == "I":

            insertions += 1
            j -= 1

        else:

            break

    errors = (
        substitutions
        + deletions
        + insertions
    )

    error_rate = (
        errors / n
        if n > 0
        else float(errors > 0)
    )

    return (
        error_rate,
        substitutions,
        deletions,
        insertions,
        n,
    )

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):

    total_word_sub = 0
    total_word_del = 0
    total_word_ins = 0
    total_words = 0

    total_char_sub = 0
    total_char_del = 0
    total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(
        df[ref_col],
        df[hyp_col]
    ):

        ref = (
            ""
            if pd.isna(ref)
            else str(ref)
        )

        hyp = (
            ""
            if pd.isna(hyp)
            else str(hyp)
        )

        _, s, d, i, n = (
            _alignment_error_rate(
                ref.split(),
                hyp.split()
            )
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = (
            _alignment_error_rate(
                list(
                    ref.replace(
                        " ",
                        ""
                    )
                ),
                list(
                    hyp.replace(
                        " ",
                        ""
                    )
                )
            )
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub
        + total_word_del
        + total_word_ins
    ) / max(
        1,
        total_words
    )

    cer = (
        total_char_sub
        + total_char_del
        + total_char_ins
    ) / max(
        1,
        total_chars
    )

    return {
        "WER": wer,
        "CER": cer,

        "word_sub":
            total_word_sub,

        "word_del":
            total_word_del,

        "word_ins":
            total_word_ins,

        "char_sub":
            total_char_sub,

        "char_del":
            total_char_del,

        "char_ins":
            total_char_ins,

        "total_words":
            total_words,

        "total_chars":
            total_chars,
    }

In [ ]:
def transcribe_wav2vec2(
    audio_path,
    processor,
    model,
    device,
):

    audio, sr = sf.read(
        audio_path,
        dtype="float32"
    )

    # Stereo -> mono only if required
    if audio.ndim > 1:

        audio = np.mean(
            audio,
            axis=1
        )

    target_sr = (
        processor
        .feature_extractor
        .sampling_rate
    )

    # Normally not triggered for FLEURS
    if sr != target_sr:

        audio = librosa.resample(
            audio,
            orig_sr=sr,
            target_sr=target_sr
        )

        sr = target_sr

    inputs = processor(
        audio,
        sampling_rate=sr,
        return_tensors="pt",
    )

    input_values = (
        inputs.input_values
        .to(device)
    )

    with torch.inference_mode():

        logits = model(
            input_values
        ).logits

    predicted_ids = torch.argmax(
        logits,
        dim=-1
    )

    prediction = (
        processor
        .batch_decode(
            predicted_ids
        )[0]
    )

    return prediction.strip()

In [ ]:
test_row = df.iloc[0]

test_prediction = (
    transcribe_wav2vec2(
        test_row["audio_path"],
        processor,
        model,
        device,
    )
)

print("REFERENCE:")
print(
    test_row["transcription"]
)

print("\nWAV2VEC2:")
print(
    test_prediction
)

print("\nNORMALIZED REFERENCE:")
print(
    nemo_paper_normalize(
        test_row["transcription"]
    )
)

print("\nNORMALIZED HYPOTHESIS:")
print(
    nemo_paper_normalize(
        test_prediction
    )
)

NameError: name 'processor' is not defined

# Vosk

In [ ]:
!pip install -q vosk pandas tqdm

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 37.0 MB/s eta 0:00:00
  Building wheel for srt (setup.py) ... done

In [ ]:
from google.colab import drive
from pathlib import Path
import os

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")
else:
    print("Google Drive already mounted.")

BASE_DIR = Path(
    "/content/drive/MyDrive/persian_asr_llm_error_propagation"
)

DATA_DIR = BASE_DIR / "data"
ASR_COMPARE_DIR = BASE_DIR / "asr_comparison"

ASR_COMPARE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TSV_PATH = DATA_DIR / "test.tsv"

print("TSV:", TSV_PATH)
print("Exists:", TSV_PATH.exists())

Google Drive already mounted.
TSV: /content/drive/MyDrive/persian_asr_llm_error_propagation/data/test.tsv
Exists: True

In [ ]:
wav_files = list(
    DATA_DIR.rglob("*.wav")
)

print("WAV files found:", len(wav_files))

for p in wav_files[:5]:
    print(p)

WAV files found: 871
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/7099844447178454280.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/13720237503121452158.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/7557020602592715699.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/11242877790416358060.wav
/content/drive/MyDrive/persian_asr_llm_error_propagation/data/test_audio/test/5039781156427225122.wav

In [ ]:
wav_map = {
    p.name: str(p)
    for p in wav_files
}

print("Unique WAV filenames:", len(wav_map))

Unique WAV filenames: 871

In [ ]:
import pandas as pd

COLUMNS = [
    "id",
    "file_name",
    "raw_transcription",
    "transcription",
    "character_transcription",
    "num_samples",
    "gender",
]

df = pd.read_csv(
    TSV_PATH,
    sep="\t",
    header=None,
    names=COLUMNS,
)

print("Rows:", len(df))
print("Unique files:", df["file_name"].nunique())
print("Unique semantic IDs:", df["id"].nunique())

display(df.head())

Rows: 871
Unique files: 871
Unique semantic IDs: 324

,id,file_name,raw_transcription,transcription,character_transcription,num_samples,gender
0,1735,7913564082410055971.wav,محققان دانشگاه پرینستون آمریكا و دانشگاه اوپسا...,محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسا...,م ح ق ق ا ن | د ا ن ش گ ا ه | پ ر ی ن س ت و ن ...,518400,MALE
1,1720,621633057978356932.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,193920,MALE
2,1720,13180061520623477685.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,205440,MALE
3,1720,16484235889057265269.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,223680,MALE
4,1955,17985233135634044314.wav,MS نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,ms نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,m s | ن و ع ی | ب ی م ا ر ی | ا س ت | ک ه | ب ...,218880,MALE

In [ ]:
import pandas as pd

COLUMNS = [
    "id",
    "file_name",
    "raw_transcription",
    "transcription",
    "character_transcription",
    "num_samples",
    "gender",
]

df = pd.read_csv(
    TSV_PATH,
    sep="\t",
    header=None,
    names=COLUMNS,
)

print("Rows:", len(df))
print("Unique files:", df["file_name"].nunique())
print("Unique semantic IDs:", df["id"].nunique())

display(df.head())

Rows: 871
Unique files: 871
Unique semantic IDs: 324

,id,file_name,raw_transcription,transcription,character_transcription,num_samples,gender
0,1735,7913564082410055971.wav,محققان دانشگاه پرینستون آمریكا و دانشگاه اوپسا...,محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسا...,م ح ق ق ا ن | د ا ن ش گ ا ه | پ ر ی ن س ت و ن ...,518400,MALE
1,1720,621633057978356932.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,193920,MALE
2,1720,13180061520623477685.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,205440,MALE
3,1720,16484235889057265269.wav,شکلات داغ در حد استانداردهای بلژیکی است. آبمیو...,شکلات داغ در حد استانداردهای بلژیکی است آبمیوه...,ش ک ل ا ت | د ا غ | د ر | ح د | ا س ت ا ن د ا ...,223680,MALE
4,1955,17985233135634044314.wav,MS نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,ms نوعی بیماری است که بر سیستم عصبی مرکزی تأثی...,m s | ن و ع ی | ب ی م ا ر ی | ا س ت | ک ه | ب ...,218880,MALE

In [ ]:
df["audio_path"] = (
    df["file_name"]
    .map(wav_map)
)

missing = df["audio_path"].isna().sum()

print("Matched:", df["audio_path"].notna().sum())
print("Missing:", missing)

assert len(df) == 871
assert missing == 0

print("All FLEURS audio files mapped successfully.")

Matched: 871
Missing: 0
All FLEURS audio files mapped successfully.

In [ ]:
import unicodedata

SKIP = set([
    "ā", "š", "="
])

REPLACEMENTS = {
    "أ": "ا",
    "ك": "ک",
    "ي": "ی",
    "ى": "ی",
    "ﯽ": "ی",
    "ﻮ": "و",
    "ە": "ه",
    "ۀ": "ه",
}

DISCARD = set([
    "!", '"', "#", "&", "'", "(", ")", ",", "-", ".", ":",
    ";", "؟", "،", "؛", "ـ", "…", "«", "»", "–",
    "ً", "ٌ", "َ", "ُ", "ِ", "ّ", "ْ", "ٔ"
])


def nemo_paper_normalize(text: str) -> str:

    if text is None:
        return ""

    text = str(text)

    # Unicode normalization FIRST
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    # remove hashtags
    text = " ".join(
        w
        for w in text.split()
        if not w.startswith("#")
    )

    # character replacements
    for k, v in REPLACEMENTS.items():
        text = text.replace(k, v)

    # remove punctuation tokens
    for tok in DISCARD:
        text = text.replace(tok, " ")

    # remove standalone Arabic hamza
    text = text.replace("ء", "")

    # collapse whitespace
    text = " ".join(
        text.split()
    )

    return text

In [ ]:
def _alignment_error_rate(
    reference,
    hypothesis,
):
    """
    Levenshtein alignment.

    Returns:
        error_rate,
        substitutions,
        deletions,
        insertions,
        reference_length
    """

    n = len(reference)
    m = len(hypothesis)

    # dp[i][j] = minimum edits required
    # to transform reference[:i] into hypothesis[:j]
    dp = [
        [0] * (m + 1)
        for _ in range(n + 1)
    ]

    ops = [
        [None] * (m + 1)
        for _ in range(n + 1)
    ]

    for i in range(1, n + 1):
        dp[i][0] = i
        ops[i][0] = "D"

    for j in range(1, m + 1):
        dp[0][j] = j
        ops[0][j] = "I"

    for i in range(1, n + 1):

        for j in range(1, m + 1):

            if reference[i - 1] == hypothesis[j - 1]:

                dp[i][j] = dp[i - 1][j - 1]
                ops[i][j] = "C"

            else:

                sub = dp[i - 1][j - 1] + 1
                delete = dp[i - 1][j] + 1
                insert = dp[i][j - 1] + 1

                best = min(
                    sub,
                    delete,
                    insert
                )

                dp[i][j] = best

                # deterministic tie breaking
                if best == sub:
                    ops[i][j] = "S"
                elif best == delete:
                    ops[i][j] = "D"
                else:
                    ops[i][j] = "I"

    # backtrack
    i = n
    j = m

    substitutions = 0
    deletions = 0
    insertions = 0

    while i > 0 or j > 0:

        op = ops[i][j]

        if op == "C":
            i -= 1
            j -= 1

        elif op == "S":
            substitutions += 1
            i -= 1
            j -= 1

        elif op == "D":
            deletions += 1
            i -= 1

        elif op == "I":
            insertions += 1
            j -= 1

        else:
            break

    errors = (
        substitutions
        + deletions
        + insertions
    )

    error_rate = (
        errors / n
        if n > 0
        else float(errors > 0)
    )

    return (
        error_rate,
        substitutions,
        deletions,
        insertions,
        n,
    )

In [ ]:
def compute_dataset_wer_cer(
    df,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
):

    total_word_sub = 0
    total_word_del = 0
    total_word_ins = 0
    total_words = 0

    total_char_sub = 0
    total_char_del = 0
    total_char_ins = 0
    total_chars = 0

    for ref, hyp in zip(
        df[ref_col],
        df[hyp_col]
    ):

        ref = (
            ""
            if pd.isna(ref)
            else str(ref)
        )

        hyp = (
            ""
            if pd.isna(hyp)
            else str(hyp)
        )

        _, s, d, i, n = _alignment_error_rate(
            ref.split(),
            hyp.split()
        )

        total_word_sub += s
        total_word_del += d
        total_word_ins += i
        total_words += n

        _, s, d, i, n = _alignment_error_rate(
            list(
                ref.replace(" ", "")
            ),
            list(
                hyp.replace(" ", "")
            )
        )

        total_char_sub += s
        total_char_del += d
        total_char_ins += i
        total_chars += n

    wer = (
        total_word_sub
        + total_word_del
        + total_word_ins
    ) / max(1, total_words)

    cer = (
        total_char_sub
        + total_char_del
        + total_char_ins
    ) / max(1, total_chars)

    return {
        "WER": wer,
        "CER": cer,

        "word_sub": total_word_sub,
        "word_del": total_word_del,
        "word_ins": total_word_ins,

        "char_sub": total_char_sub,
        "char_del": total_char_del,
        "char_ins": total_char_ins,

        "total_words": total_words,
        "total_chars": total_chars,
    }

In [ ]:
!wget -nc https://alphacephei.com/vosk/models/vosk-model-fa-0.42.zip

--2026-08-25 05:59:46--  https://alphacephei.com/vosk/models/vosk-model-fa-0.42.zip
Resolving alphacephei.com (alphacephei.com)... 188.40.21.16, 2a01:4f8:13a:279f::2
Connecting to alphacephei.com (alphacephei.com)|188.40.21.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1667089770 (1.6G) [application/zip]
Saving to: ‘vosk-model-fa-0.42.zip’

vosk-model-fa-0.42. 100%[===================>]   1.55G  19.5MB/s    in 85s

2026-08-25 06:01:12 (18.7 MB/s) - ‘vosk-model-fa-0.42.zip’ saved [1667089770/1667089770]

In [ ]:
!unzip -q -n vosk-model-fa-0.42.zip -d /content/

In [ ]:
!ls -lh /content/vosk-model-fa-0.42

total 28K
drwxr-xr-x 2 root root 4.0K Oct 26  2024 am
drwxr-xr-x 2 root root 4.0K Sep 27  2024 conf
drwxr-xr-x 3 root root 4.0K Oct 26  2024 graph
drwxr-xr-x 2 root root 4.0K Oct 14  2024 ivector
-rw-r--r-- 1 root root  425 Oct 26  2024 README
drwxr-xr-x 2 root root 4.0K Jan 16  2021 rescore
drwxr-xr-x 2 root root 4.0K Jan 16  2021 test

In [ ]:
from vosk import Model

VOSK_MODEL_PATH = (
    "/content/vosk-model-fa-0.42"
)

model = Model(
    VOSK_MODEL_PATH
)

print(
    "Vosk model loaded successfully"
)

Vosk model loaded successfully

In [ ]:
!pip install -q soundfile

In [ ]:
import soundfile as sf
import numpy as np
from pathlib import Path

In [ ]:
for path in df["audio_path"].head(5):

    info = sf.info(path)

    print(
        Path(path).name,
        "| channels:", info.channels,
        "| rate:", info.samplerate,
        "| subtype:", info.subtype,
        "| format:", info.format,
    )

7913564082410055971.wav | channels: 1 | rate: 16000 | subtype: FLOAT | format: WAV
621633057978356932.wav | channels: 1 | rate: 16000 | subtype: FLOAT | format: WAV
13180061520623477685.wav | channels: 1 | rate: 16000 | subtype: FLOAT | format: WAV
16484235889057265269.wav | channels: 1 | rate: 16000 | subtype: FLOAT | format: WAV
17985233135634044314.wav | channels: 1 | rate: 16000 | subtype: FLOAT | format: WAV

In [ ]:
audio_formats = []

for path in df["audio_path"]:

    info = sf.info(path)

    audio_formats.append({
        "file_name": Path(path).name,
        "sample_rate": info.samplerate,
        "channels": info.channels,
        "subtype": info.subtype,
        "format": info.format,
    })

audio_formats_df = pd.DataFrame(audio_formats)

print("Sample rates:")
print(audio_formats_df["sample_rate"].value_counts())

print("\nChannels:")
print(audio_formats_df["channels"].value_counts())

print("\nSubtypes:")
print(audio_formats_df["subtype"].value_counts())

Sample rates:
sample_rate
16000    871
Name: count, dtype: int64

Channels:
channels
1    871
Name: count, dtype: int64

Subtypes:
subtype
FLOAT    871
Name: count, dtype: int64

In [ ]:
import json
import numpy as np
import soundfile as sf
import librosa

from vosk import KaldiRecognizer


def transcribe_vosk(audio_path, model):

    audio, sr = sf.read(
        audio_path,
        dtype="float32"
    )

    # Stereo -> mono, only if necessary
    if audio.ndim > 1:
        audio = np.mean(
            audio,
            axis=1
        )

    # Resample only if necessary
    if sr != 16000:

        audio = librosa.resample(
            audio,
            orig_sr=sr,
            target_sr=16000
        )

        sr = 16000

    # Prevent overflow before PCM16 conversion
    audio = np.clip(
        audio,
        -1.0,
        1.0
    )

    audio_int16 = (
        audio * 32767
    ).astype(np.int16)

    rec = KaldiRecognizer(
        model,
        16000
    )

    parts = []

    # Feed in chunks rather than one huge buffer
    chunk_size = 4000

    for start in range(
        0,
        len(audio_int16),
        chunk_size
    ):

        chunk = audio_int16[
            start:start + chunk_size
        ]

        if rec.AcceptWaveform(
            chunk.tobytes()
        ):

            result = json.loads(
                rec.Result()
            )

            text = result.get(
                "text",
                ""
            ).strip()

            if text:
                parts.append(text)

    final_result = json.loads(
        rec.FinalResult()
    )

    final_text = final_result.get(
        "text",
        ""
    ).strip()

    if final_text:
        parts.append(final_text)

    return " ".join(parts).strip()

In [ ]:
from pathlib import Path
import os
import time
import pandas as pd
from tqdm.auto import tqdm

VOSK_RESULTS_DIR = (
    BASE_DIR
    / "asr_comparison"
    / "vosk_model_fa_0_42"
)

VOSK_RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

CHECKPOINT_PATH = (
    VOSK_RESULTS_DIR
    / "vosk_fleurs_checkpoint.csv"
)

FINAL_PATH = (
    VOSK_RESULTS_DIR
    / "vosk_fleurs_results_v1.csv"
)

SUMMARY_PATH = (
    VOSK_RESULTS_DIR
    / "vosk_fleurs_summary_v1.csv"
)

print("Checkpoint:", CHECKPOINT_PATH)
print("Final:", FINAL_PATH)
print("Summary:", SUMMARY_PATH)

Checkpoint: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/vosk_model_fa_0_42/vosk_fleurs_checkpoint.csv
Final: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/vosk_model_fa_0_42/vosk_fleurs_results_v1.csv
Summary: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/vosk_model_fa_0_42/vosk_fleurs_summary_v1.csv

In [ ]:
def atomic_save_csv(df, path):

    tmp_path = str(path) + ".tmp"

    df.to_csv(
        tmp_path,
        index=False,
        encoding="utf-8-sig"
    )

    os.replace(
        tmp_path,
        path
    )

In [ ]:
if CHECKPOINT_PATH.exists():

    results_df = pd.read_csv(
        CHECKPOINT_PATH
    )

    processed = set(
        results_df.loc[
            results_df["status"] == "ok",
            "file_name"
        ].astype(str)
    )

    print(
        f"Loaded checkpoint: {len(results_df)} rows"
    )

    print(
        f"Already successful: {len(processed)}"
    )

else:

    results_df = pd.DataFrame()

    processed = set()

    print("No checkpoint found. Starting from zero.")

Loaded checkpoint: 871 rows
Already successful: 871

In [ ]:
test_row = df.iloc[0]

test_prediction = transcribe_vosk(
    test_row["audio_path"],
    model
)

print("REFERENCE:")
print(
    test_row["transcription"]
)

print("\nVOSK:")
print(
    test_prediction
)

REFERENCE:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید تکامل یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینی متوسط و سهره کاکتوسی مهاجر یعنی سهره کاکتوسی بزرگ این روند خیلی بیشتر طول کشید

VOSK:
محققان دانشگاه پرینستون آمریکا و دانشگاه اوپسالا در سوئد گونه‌های جدید جدید تکامل‌یافته‌ای را تنها در دو نسل گزارش دادند اگرچه اعتقاد بر این بود که به دلیل زاد و ولد بین یک سهره داروین بومی سهره زمینه‌ی متوسط و سهره کاکتوسی مهاجر یعنی سحر کاکتوسی بزرگ این روند خیلی بیشتر طول کشید ایست

In [ ]:
for idx in tqdm(
    range(len(df)),
    desc="Vosk FLEURS"
):

    row = df.iloc[idx]

    file_name = str(
        row["file_name"]
    )

    if file_name in processed:
        continue

    audio_path = row[
        "audio_path"
    ]

    try:

        info = sf.info(
            audio_path
        )

        duration = (
            info.duration
        )

        t0 = time.perf_counter()

        pred_text = transcribe_vosk(
            audio_path,
            model
        )

        inference_time = (
            time.perf_counter()
            - t0
        )

        new_row = {

            "id": int(row["id"]),

            "file_name": file_name,

            "audio_path": audio_path,

            "gender": row["gender"],

            "audio_duration": duration,

            # Keep original FLEURS text
            "reference_raw":
                row["raw_transcription"],

            # This is the official normalized
            # FLEURS transcript used for scoring
            "reference_normalized":
                row["transcription"],

            "prediction_raw":
                pred_text,

            "inference_time":
                inference_time,

            "rtf": (
                inference_time / duration
                if duration > 0
                else None
            ),

            "status": "ok",

            "error": "",
        }

        results_df = pd.concat(
            [
                results_df,
                pd.DataFrame([new_row])
            ],
            ignore_index=True
        )

        processed.add(
            file_name
        )

    except Exception as e:

        new_row = {

            "id": int(row["id"]),

            "file_name": file_name,

            "audio_path": audio_path,

            "gender": row["gender"],

            "audio_duration": None,

            "reference_raw":
                row["raw_transcription"],

            "reference_normalized":
                row["transcription"],

            "prediction_raw": "",

            "inference_time": None,

            "rtf": None,

            "status": "error",

            "error": repr(e),
        }

        results_df = pd.concat(
            [
                results_df,
                pd.DataFrame([new_row])
            ],
            ignore_index=True
        )

        print(
            f"\nFAILED: {file_name}"
        )

        print(e)

    # Save after every recording
    atomic_save_csv(
        results_df,
        CHECKPOINT_PATH
    )

Vosk FLEURS:   0%|          | 0/871 [00:00<?, ?it/s]

In [ ]:
print(
    "Total checkpoint rows:",
    len(results_df)
)

print()

print(
    results_df["status"]
    .value_counts(
        dropna=False
    )
)

Total checkpoint rows: 871

status
ok    871
Name: count, dtype: int64

In [ ]:
df_sub = (
    results_df[
        results_df["status"] == "ok"
    ]
    .copy()
)

print(
    "Successful:",
    len(df_sub)
)

print(
    "Failed:",
    len(results_df) - len(df_sub)
)

print(
    "Unique files:",
    df_sub["file_name"].nunique()
)

Successful: 871
Failed: 0
Unique files: 871

In [ ]:
vosk_df = pd.read_csv(
    CHECKPOINT_PATH
)

print(
    "Checkpoint rows:",
    len(vosk_df)
)

print()

print(
    vosk_df[
        "status"
    ].value_counts(
        dropna=False
    )
)

Checkpoint rows: 871

status
ok    871
Name: count, dtype: int64

In [ ]:
vosk_sub = (
    vosk_df[
        vosk_df["status"]
        == "ok"
    ]
    .copy()
)

print(
    "Successful:",
    len(vosk_sub)
)

print(
    "Failed:",
    len(vosk_df)
    - len(vosk_sub)
)

print(
    "Unique files:",
    vosk_sub[
        "file_name"
    ].nunique()
)

Successful: 871
Failed: 0
Unique files: 871

In [ ]:
vosk_sub["hyp_norm"] = (
    vosk_sub[
        "prediction_raw"
    ]
    .apply(
        nemo_paper_normalize
    )
)

vosk_sub["ref_norm"] = (
    vosk_sub[
        "reference_normalized"
    ]
    .apply(
        nemo_paper_normalize
    )
)

In [ ]:
metrics = compute_dataset_wer_cer(
    vosk_sub,
    ref_col="ref_norm",
    hyp_col="hyp_norm",
)

metrics

{'WER': 0.1674712586472901,
 'CER': 0.06280123732105604,
 'word_sub': 1872,
 'word_del': 568,
 'word_ins': 925,
 'char_sub': 1426,
 'char_del': 859,
 'char_ins': 2953,
 'total_words': 20093,
 'total_chars': 83406}

In [ ]:
print(
    f"Samples: {len(df_sub)}"
)

print(
    f"WER: {metrics['WER']:.6f}"
)

print(
    f"CER: {metrics['CER']:.6f}"
)

print(
    f"WER (%): {metrics['WER'] * 100:.2f}%"
)

print(
    f"CER (%): {metrics['CER'] * 100:.2f}%"
)

Samples: 871
WER: 0.167471
CER: 0.062801
WER (%): 16.75%
CER (%): 6.28%

In [ ]:
summary_df = pd.DataFrame([
    {
        "Samples": len(df_sub),
        "WER": metrics["WER"],
        "CER": metrics["CER"],
    }
])

display(summary_df)

   Samples       WER       CER
0      871  0.167471  0.062801

In [ ]:
summary_df.to_csv(
    SUMMARY_PATH,
    index=False,
    encoding="utf-8-sig"
)

print(
    "Summary saved to:",
    SUMMARY_PATH
)

Summary saved to: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/vosk_model_fa_0_42/vosk_fleurs_summary_v1.csv

In [ ]:
assert len(df_sub) == 871
assert df_sub["file_name"].nunique() == 871

df_sub = (
    df_sub
    .sort_values(
        [
            "id",
            "file_name"
        ]
    )
    .reset_index(
        drop=True
    )
)

df_sub.to_csv(
    FINAL_PATH,
    index=False,
    encoding="utf-8-sig"
)

print(
    "Final results saved to:",
    FINAL_PATH
)

Final results saved to: /content/drive/MyDrive/persian_asr_llm_error_propagation/asr_comparison/vosk_model_fa_0_42/vosk_fleurs_results_v1.csv

In [ ]:
import hashlib


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb"
    ) as f:

        for chunk in iter(
            lambda:
                f.read(1024 * 1024),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()

In [ ]:
print(
    "Final prediction SHA-256:"
)

print(
    sha256_file(
        FINAL_PATH
    )
)

print()

print(
    "Summary SHA-256:"
)

print(
    sha256_file(
        SUMMARY_PATH
    )
)

Final prediction SHA-256:
d530509ec3bfdc0e08ebead28c46dcf800d1300a4aeabcec41774ef47e5e8a7a

Summary SHA-256:
b2d2bcddd8e6cf776e3ad09f4e09b9518ffead2a4ed69a7f46881abda1d90e2d

In [ ]:
print(summary_df)

print()

print(metrics)

   Samples       WER       CER
0      871  0.167471  0.062801

{'WER': 0.1674712586472901, 'CER': 0.06280123732105604, 'word_sub': 1872, 'word_del': 568, 'word_ins': 925, 'char_sub': 1426, 'char_del': 859, 'char_ins': 2953, 'total_words': 20093, 'total_chars': 83406}